In [ ]:
import requests
import time
import pandas as pd

TOKEN = "d5c3d78fc111d88a0a37b4ab8f83cbd5"
BASE_URL = "https://ows.goszakup.gov.kz"
API_ENDPOINT = "/v3/plans/deleted"

headers = {
    "Authorization": f"Bearer {TOKEN}",
    "Content-Type": "application/json"
}

# Загружаем текущий parquet-файл
parquet_file = "goszakup_deleted_data.parquet"
try:
    df_existing = pd.read_parquet(parquet_file)
    max_index_date = df_existing["index_date"].max()  # Фиксированная максимальная дата
except FileNotFoundError:
    df_existing = pd.DataFrame()
    max_index_date = None

print(f"📌 Найдено {len(df_existing)} записей, max_index_date: {max_index_date}")

next_page = API_ENDPOINT + "?limit=500"
all_data = []
no_new_data_count = 0

while next_page:
    try:
        response = requests.get(BASE_URL + next_page, headers=headers, timeout=30)
        response.raise_for_status()
        data = response.json()

        items = data.get("items", [])
        if not items:
            print("🚫 Данных больше нет, остановка загрузки.")
            break

        first_index_date = items[0].get("index_date", "Нет даты")
        last_index_date = items[-1].get("index_date", "Нет даты")
        print(f"\n🔹 Запрос к API: {BASE_URL + next_page}")
        print(f"📅 Первая index_date: {first_index_date}, Последняя index_date: {last_index_date}")

        # Фильтруем записи с валидной датой
        valid_items = [item for item in items if item.get("index_date") is not None]
        total_items = len(valid_items)

        # Если max_index_date нет, берём все записи
        if max_index_date is None:
            new_items = valid_items
        else:
            # Фильтруем относительно фиксированного max_index_date
            new_items = [item for item in valid_items if item["index_date"] > max_index_date]

        # Диагностика
        print(f"📌 Всего записей на странице: {total_items}")
        print(f"📌 Примеры данных:")
        for i, item in enumerate(valid_items[:3]):
            print(f"  - ID: {item['id']}, index_date: {item.get('index_date', 'Нет даты')}")
        print(f"📌 Новых записей (index_date > {max_index_date}): {len(new_items)}")

        if new_items:
            all_data.extend(new_items)
            print(f"✅ Загружено {len(new_items)} новых записей с этой страницы...")
            no_new_data_count = 0
        else:
            no_new_data_count += 1
            print(f"⚠️ На этой странице нет новых записей ({no_new_data_count}/3).")

        # Если три страницы подряд без новых данных — завершаем
        if no_new_data_count >= 3:
            print("🚫 Три страницы без новых данных, остановка загрузки.")
            break

        # Следующая страница
        next_page = data.get("next_page")
        if not next_page:
            print("🏁 Достигнута последняя страница, завершаем загрузку.")
            break

        time.sleep(5)

    except requests.exceptions.RequestException as e:
        print(f"❌ Ошибка запроса: {e}")
        print("⏳ Ждём 30 сек и пробуем снова...")
        time.sleep(30)

# Сохранение данных
if all_data:
    df_new = pd.DataFrame(all_data)
    df_combined = pd.concat([df_existing, df_new], ignoring_index=True)
    df_combined = df_combined.drop_duplicates(subset=["id"], keep="last")
    df_combined.to_parquet(parquet_file, index=False, engine="pyarrow")
    print(f"🎉 Дозагрузка завершена, сохранено {len(df_combined)} записей в {parquet_file}")
else:
    print("🔍 Новых данных не найдено.")

📌 Найдено 19875273 записей, max_index_date: 2025-03-28 14:10:17

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?limit=500
📅 Первая index_date: 2025-03-31 20:01:24, Последняя index_date: 2025-03-31 19:41:12
📌 Всего записей на странице: 499
📌 Примеры данных:
  - ID: 78409647, index_date: 2025-03-31 20:01:24
  - ID: 78409635, index_date: 2025-03-31 20:01:25
  - ID: 78409628, index_date: 2025-03-31 20:01:25
📌 Новых записей (index_date > 2025-03-28 14:10:17): 499
✅ Загружено 499 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78409096
📅 Первая index_date: 2025-03-31 19:41:12, Последняя index_date: 2025-03-31 19:21:12
📌 Всего записей на странице: 500
📌 Примеры данных:
  - ID: 78409095, index_date: 2025-03-31 19:41:12
  - ID: 78409094, index_date: 2025-03-31 19:41:12
  - ID: 78409092, index_date: 2025-03-31 20:01:25
📌 Новых записей (index_date > 2025-03-28 14:10:17): 500
✅ Загружено 500 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78408488
📅 Первая index_date: 2025-03-31 19:21:11, Последняя index_date: 2025-03-31 19:01:32
📌 Всего записей на странице: 497
📌 Примеры данных:
  - ID: 78408487, index_date: 2025-03-31 19:21:11
  - ID: 78408482, index_date: 2025-03-31 19:21:12
  - ID: 78408477, index_date: 2025-03-31 19:21:12
📌 Новых записей (index_date > 2025-03-28 14:10:17): 497
✅ Загружено 497 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78407584
📅 Первая index_date: 2025-03-31 19:01:32, Последняя index_date: 2025-03-31 19:01:28
📌 Всего записей на странице: 489
📌 Примеры данных:
  - ID: 78407583, index_date: 2025-03-31 19:01:32
  - ID: 78407582, index_date: 2025-03-31 19:01:26
  - ID: 78407580, index_date: 2025-03-31 19:01:33
📌 Новых записей (index_date > 2025-03-28 14:10:17): 489
✅ Загружено 489 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78406646
📅 Первая index_date: 2025-03-31 19:01:32, Последняя index_date: 2025-03-31 17:44:27
📌 Всего записей на странице: 491
📌 Примеры данных:
  - ID: 78406641, index_date: 2025-03-31 19:01:32
  - ID: 78406640, index_date: 2025-03-31 19:01:31
  - ID: 78406638, index_date: 2025-03-31 19:01:31
📌 Новых записей (index_date > 2025-03-28 14:10:17): 491
✅ Загружено 491 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78405911
📅 Первая index_date: 2025-03-31 17:43:50, Последняя index_date: 2025-03-31 17:44:27
📌 Всего записей на странице: 485
📌 Примеры данных:
  - ID: 78405910, index_date: 2025-03-31 17:43:50
  - ID: 78405908, index_date: 2025-03-31 17:44:19
  - ID: 78405906, index_date: 2025-03-31 17:43:42
📌 Новых записей (index_date > 2025-03-28 14:10:17): 485
✅ Загружено 485 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78405008
📅 Первая index_date: 2025-03-31 17:44:09, Последняя index_date: 2025-03-31 17:43:42
📌 Всего записей на странице: 499
📌 Примеры данных:
  - ID: 78405007, index_date: 2025-03-31 17:44:09
  - ID: 78405006, index_date: 2025-03-31 17:43:35
  - ID: 78405005, index_date: 2025-03-31 17:43:35
📌 Новых записей (index_date > 2025-03-28 14:10:17): 499
✅ Загружено 499 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78404150
📅 Первая index_date: 2025-03-31 19:01:28, Последняя index_date: 2025-03-31 17:43:59
📌 Всего записей на странице: 490
📌 Примеры данных:
  - ID: 78404149, index_date: 2025-03-31 19:01:28
  - ID: 78404147, index_date: 2025-03-31 17:43:58
  - ID: 78404146, index_date: 2025-03-31 19:01:26
📌 Новых записей (index_date > 2025-03-28 14:10:17): 490
✅ Загружено 490 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78403322
📅 Первая index_date: 2025-03-31 17:44:19, Последняя index_date: 2025-03-31 17:43:55
📌 Всего записей на странице: 489
📌 Примеры данных:
  - ID: 78403319, index_date: 2025-03-31 17:44:19
  - ID: 78403317, index_date: 2025-03-31 17:43:47
  - ID: 78403316, index_date: 2025-03-31 17:44:30
📌 Новых записей (index_date > 2025-03-28 14:10:17): 489
✅ Загружено 489 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78402199
📅 Первая index_date: 2025-03-31 17:44:05, Последняя index_date: 2025-03-31 17:43:59
📌 Всего записей на странице: 495
📌 Примеры данных:
  - ID: 78402198, index_date: 2025-03-31 17:44:05
  - ID: 78402194, index_date: 2025-03-31 17:44:27
  - ID: 78402193, index_date: 2025-03-31 17:44:09
📌 Новых записей (index_date > 2025-03-28 14:10:17): 495
✅ Загружено 495 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78401176
📅 Первая index_date: 2025-03-31 17:44:09, Последняя index_date: 2025-03-31 17:44:30
📌 Всего записей на странице: 493
📌 Примеры данных:
  - ID: 78401174, index_date: 2025-03-31 17:44:09
  - ID: 78401173, index_date: 2025-03-31 17:43:35
  - ID: 78401171, index_date: 2025-03-31 17:44:27
📌 Новых записей (index_date > 2025-03-28 14:10:17): 493
✅ Загружено 493 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78400250
📅 Первая index_date: 2025-03-31 17:44:26, Последняя index_date: 2025-03-31 17:43:51
📌 Всего записей на странице: 387
📌 Примеры данных:
  - ID: 78400249, index_date: 2025-03-31 17:44:26
  - ID: 78400247, index_date: 2025-03-31 17:44:30
  - ID: 78400245, index_date: 2025-03-31 17:43:35
📌 Новых записей (index_date > 2025-03-28 14:10:17): 387
✅ Загружено 387 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78399437
📅 Первая index_date: 2025-03-31 17:43:42, Последняя index_date: 2025-03-31 17:43:50
📌 Всего записей на странице: 493
📌 Примеры данных:
  - ID: 78399436, index_date: 2025-03-31 17:43:42
  - ID: 78399434, index_date: 2025-03-31 17:44:27
  - ID: 78399431, index_date: 2025-03-31 17:43:35
📌 Новых записей (index_date > 2025-03-28 14:10:17): 493
✅ Загружено 493 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78398401
📅 Первая index_date: 2025-03-31 17:43:39, Последняя index_date: 2025-03-31 17:44:20
📌 Всего записей на странице: 497
📌 Примеры данных:
  - ID: 78398400, index_date: 2025-03-31 17:43:39
  - ID: 78398398, index_date: 2025-03-31 17:44:06
  - ID: 78398397, index_date: 2025-03-31 17:43:35
📌 Новых записей (index_date > 2025-03-28 14:10:17): 497
✅ Загружено 497 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78397505
📅 Первая index_date: 2025-03-31 17:43:55, Последняя index_date: 2025-03-31 17:43:47
📌 Всего записей на странице: 498
📌 Примеры данных:
  - ID: 78397504, index_date: 2025-03-31 17:43:55
  - ID: 78397501, index_date: 2025-03-31 17:43:55
  - ID: 78397500, index_date: 2025-03-31 17:44:26
📌 Новых записей (index_date > 2025-03-28 14:10:17): 498
✅ Загружено 498 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78396502
📅 Первая index_date: 2025-03-31 17:43:51, Последняя index_date: 2025-03-31 17:44:34
📌 Всего записей на странице: 495
📌 Примеры данных:
  - ID: 78396500, index_date: 2025-03-31 17:43:51
  - ID: 78396498, index_date: 2025-03-31 17:44:05
  - ID: 78396497, index_date: 2025-03-31 17:44:09
📌 Новых записей (index_date > 2025-03-28 14:10:17): 495
✅ Загружено 495 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78395658
📅 Первая index_date: 2025-03-31 17:43:35, Последняя index_date: 2025-03-31 17:44:09
📌 Всего записей на странице: 492
📌 Примеры данных:
  - ID: 78395657, index_date: 2025-03-31 17:43:35
  - ID: 78395656, index_date: 2025-03-31 17:43:59
  - ID: 78395655, index_date: 2025-03-31 17:44:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 492
✅ Загружено 492 новых записей с этой страницы...

❌ Ошибка запроса: HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=30)
⏳ Ждём 30 сек и пробуем снова...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78394516
📅 Первая index_date: 2025-03-31 17:43:50, Последняя index_date: 2025-03-31 12:11:22
📌 Всего записей на странице: 492
📌 Примеры данных:
  - ID: 78394513, index_date: 2025-03-31 17:43:50
  - ID: 78394510, index_date: 2025-03-31 17:44:05
  - ID: 78394509, index_date: 2025-03-31 19:01:32
📌 Новых записей (index_date > 2025-03-28 14:10:17): 492
✅ Загружено 492 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78393507
📅 Первая index_date: 2025-03-31 14:25:56, Последняя index_date: 2025-03-31 12:10:53
📌 Всего записей на странице: 496
📌 Примеры данных:
  - ID: 78393506, index_date: 2025-03-31 14:25:56
  - ID: 78393505, index_date: 2025-03-31 12:09:45
  - ID: 78393504, index_date: 2025-03-31 12:09:45
📌 Новых записей (index_date > 2025-03-28 14:10:17): 496
✅ Загружено 496 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78392483
📅 Первая index_date: 2025-03-31 12:13:12, Последняя index_date: 2025-03-31 12:09:01
📌 Всего записей на странице: 484
📌 Примеры данных:
  - ID: 78392481, index_date: 2025-03-31 12:13:12
  - ID: 78392475, index_date: 2025-03-31 12:10:21
  - ID: 78392474, index_date: 2025-03-31 12:13:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 484
✅ Загружено 484 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78391417
📅 Первая index_date: 2025-03-31 12:14:21, Последняя index_date: 2025-03-31 12:11:20
📌 Всего записей на странице: 484
📌 Примеры данных:
  - ID: 78391414, index_date: 2025-03-31 12:14:21
  - ID: 78391413, index_date: 2025-03-31 12:08:41
  - ID: 78391412, index_date: 2025-03-31 16:31:06
📌 Новых записей (index_date > 2025-03-28 14:10:17): 484
✅ Загружено 484 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78389910
📅 Первая index_date: 2025-03-31 12:09:12, Последняя index_date: 2025-03-31 12:10:14
📌 Всего записей на странице: 490
📌 Примеры данных:
  - ID: 78389909, index_date: 2025-03-31 12:09:12
  - ID: 78389907, index_date: 2025-03-31 12:14:04
  - ID: 78389906, index_date: 2025-03-31 12:13:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 490
✅ Загружено 490 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78388772
📅 Первая index_date: 2025-03-31 12:06:56, Последняя index_date: 2025-03-31 12:14:20
📌 Всего записей на странице: 500
📌 Примеры данных:
  - ID: 78388771, index_date: 2025-03-31 12:06:56
  - ID: 78388770, index_date: 2025-03-31 12:08:41
  - ID: 78388767, index_date: 2025-03-31 12:06:56
📌 Новых записей (index_date > 2025-03-28 14:10:17): 500
✅ Загружено 500 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78387938
📅 Первая index_date: 2025-03-31 12:14:20, Последняя index_date: 2025-03-31 12:05:40
📌 Всего записей на странице: 457
📌 Примеры данных:
  - ID: 78387936, index_date: 2025-03-31 12:14:20
  - ID: 78387934, index_date: 2025-03-31 12:13:22
  - ID: 78387931, index_date: 2025-03-31 17:44:09
📌 Новых записей (index_date > 2025-03-28 14:10:17): 457
✅ Загружено 457 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78386921
📅 Первая index_date: 2025-03-31 12:13:19, Последняя index_date: 2025-03-31 12:06:56
📌 Всего записей на странице: 483
📌 Примеры данных:
  - ID: 78386920, index_date: 2025-03-31 12:13:19
  - ID: 78386918, index_date: 2025-03-31 12:06:56
  - ID: 78386916, index_date: 2025-03-31 12:11:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 483
✅ Загружено 483 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78385801
📅 Первая index_date: 2025-03-31 12:06:56, Последняя index_date: 2025-03-31 12:09:14
📌 Всего записей на странице: 468
📌 Примеры данных:
  - ID: 78385800, index_date: 2025-03-31 12:06:56
  - ID: 78385799, index_date: 2025-03-31 12:08:03
  - ID: 78385798, index_date: 2025-03-31 12:09:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 468
✅ Загружено 468 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78384827
📅 Первая index_date: 2025-03-31 12:12:18, Последняя index_date: 2025-03-31 12:11:21
📌 Всего записей на странице: 494
📌 Примеры данных:
  - ID: 78384825, index_date: 2025-03-31 12:12:18
  - ID: 78384818, index_date: 2025-03-31 12:08:03
  - ID: 78384817, index_date: 2025-03-31 12:08:03
📌 Новых записей (index_date > 2025-03-28 14:10:17): 494
✅ Загружено 494 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78383963
📅 Первая index_date: 2025-03-31 17:44:23, Последняя index_date: 2025-03-31 12:10:10
📌 Всего записей на странице: 491
📌 Примеры данных:
  - ID: 78383962, index_date: 2025-03-31 17:44:23
  - ID: 78383960, index_date: 2025-03-31 12:12:19
  - ID: 78383959, index_date: 2025-03-31 17:44:09
📌 Новых записей (index_date > 2025-03-28 14:10:17): 491
✅ Загружено 491 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78382715
📅 Первая index_date: 2025-03-31 12:12:20, Последняя index_date: 2025-03-31 12:10:53
📌 Всего записей на странице: 488
📌 Примеры данных:
  - ID: 78382714, index_date: 2025-03-31 12:12:20
  - ID: 78382712, index_date: 2025-03-31 12:08:41
  - ID: 78382711, index_date: 2025-03-31 17:44:27
📌 Новых записей (index_date > 2025-03-28 14:10:17): 488
✅ Загружено 488 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78381489
📅 Первая index_date: 2025-03-31 12:09:45, Последняя index_date: 2025-03-31 12:06:47
📌 Всего записей на странице: 493
📌 Примеры данных:
  - ID: 78381487, index_date: 2025-03-31 12:09:45
  - ID: 78381485, index_date: 2025-03-31 12:10:53
  - ID: 78381483, index_date: 2025-03-31 12:07:31
📌 Новых записей (index_date > 2025-03-28 14:10:17): 493
✅ Загружено 493 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78379952
📅 Первая index_date: 2025-03-31 12:12:18, Последняя index_date: 2025-03-31 12:11:17
📌 Всего записей на странице: 480
📌 Примеры данных:
  - ID: 78379951, index_date: 2025-03-31 12:12:18
  - ID: 78379946, index_date: 2025-03-31 12:09:05
  - ID: 78379942, index_date: 2025-03-31 12:09:12
📌 Новых записей (index_date > 2025-03-28 14:10:17): 480
✅ Загружено 480 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78377943
📅 Первая index_date: 2025-03-31 12:06:50, Последняя index_date: 2025-03-31 12:07:51
📌 Всего записей на странице: 486
📌 Примеры данных:
  - ID: 78377942, index_date: 2025-03-31 12:06:50
  - ID: 78377936, index_date: 2025-03-31 12:06:56
  - ID: 78377935, index_date: 2025-03-31 12:10:21
📌 Новых записей (index_date > 2025-03-28 14:10:17): 486
✅ Загружено 486 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78376356
📅 Первая index_date: 2025-03-31 12:08:05, Последняя index_date: 2025-03-31 12:14:13
📌 Всего записей на странице: 474
📌 Примеры данных:
  - ID: 78376355, index_date: 2025-03-31 12:08:05
  - ID: 78376354, index_date: 2025-03-31 12:08:03
  - ID: 78376351, index_date: 2025-03-31 12:10:10
📌 Новых записей (index_date > 2025-03-28 14:10:17): 474
✅ Загружено 474 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78373930
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:05:40
📌 Всего записей на странице: 463
📌 Примеры данных:
  - ID: 78373922, index_date: 2025-03-31 12:10:10
  - ID: 78373920, index_date: 2025-03-31 12:07:31
  - ID: 78373919, index_date: 2025-03-31 12:12:12
📌 Новых записей (index_date > 2025-03-28 14:10:17): 463
✅ Загружено 463 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78372175
📅 Первая index_date: 2025-03-31 12:06:17, Последняя index_date: 2025-03-31 12:06:58
📌 Всего записей на странице: 473
📌 Примеры данных:
  - ID: 78372172, index_date: 2025-03-31 12:06:17
  - ID: 78372168, index_date: 2025-03-31 12:09:05
  - ID: 78372165, index_date: 2025-03-31 17:44:23
📌 Новых записей (index_date > 2025-03-28 14:10:17): 473
✅ Загружено 473 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78370294
📅 Первая index_date: 2025-03-31 12:12:01, Последняя index_date: 2025-03-31 12:13:17
📌 Всего записей на странице: 481
📌 Примеры данных:
  - ID: 78370289, index_date: 2025-03-31 12:12:01
  - ID: 78370288, index_date: 2025-03-31 12:10:14
  - ID: 78370287, index_date: 2025-03-31 12:09:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 481
✅ Загружено 481 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78367989
📅 Первая index_date: 2025-03-31 12:10:10, Последняя index_date: 2025-03-31 12:11:05
📌 Всего записей на странице: 462
📌 Примеры данных:
  - ID: 78367977, index_date: 2025-03-31 12:10:10
  - ID: 78367972, index_date: 2025-03-31 12:12:19
  - ID: 78367970, index_date: 2025-03-31 12:07:44
📌 Новых записей (index_date > 2025-03-28 14:10:17): 461
✅ Загружено 461 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78366081
📅 Первая index_date: 2025-03-31 12:11:21, Последняя index_date: 2025-03-31 12:07:51
📌 Всего записей на странице: 484
📌 Примеры данных:
  - ID: 78366078, index_date: 2025-03-31 12:11:21
  - ID: 78366077, index_date: 2025-03-31 12:13:24
  - ID: 78366072, index_date: 2025-03-31 12:08:41
📌 Новых записей (index_date > 2025-03-28 14:10:17): 484
✅ Загружено 484 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78364226
📅 Первая index_date: 2025-03-31 12:06:35, Последняя index_date: 2025-03-31 12:12:18
📌 Всего записей на странице: 481
📌 Примеры данных:
  - ID: 78364212, index_date: 2025-03-31 12:06:35
  - ID: 78364210, index_date: 2025-03-31 12:11:12
  - ID: 78364207, index_date: 2025-03-31 12:13:52
📌 Новых записей (index_date > 2025-03-28 14:10:17): 479
✅ Загружено 479 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78362029
📅 Первая index_date: 2025-03-31 12:08:03, Последняя index_date: 2025-03-31 12:10:21
📌 Всего записей на странице: 448
📌 Примеры данных:
  - ID: 78362028, index_date: 2025-03-31 12:08:03
  - ID: 78362024, index_date: 2025-03-31 12:10:14
  - ID: 78362022, index_date: 2025-03-31 12:08:03
📌 Новых записей (index_date > 2025-03-28 14:10:17): 448
✅ Загружено 448 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78360470
📅 Первая index_date: 2025-03-31 12:09:45, Последняя index_date: 2025-03-31 17:43:51
📌 Всего записей на странице: 460
📌 Примеры данных:
  - ID: 78360462, index_date: 2025-03-31 12:09:45
  - ID: 78360458, index_date: 2025-03-31 12:08:41
  - ID: 78360453, index_date: 2025-03-31 12:09:45
📌 Новых записей (index_date > 2025-03-28 14:10:17): 459
✅ Загружено 459 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78358304
📅 Первая index_date: 2025-03-31 17:43:47, Последняя index_date: 2025-03-31 12:11:20
📌 Всего записей на странице: 486
📌 Примеры данных:
  - ID: 78358285, index_date: 2025-03-31 17:43:47
  - ID: 78358284, index_date: 2025-03-31 12:12:16
  - ID: 78358277, index_date: 2025-03-31 19:01:26
📌 Новых записей (index_date > 2025-03-28 14:10:17): 478
✅ Загружено 478 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78355892
📅 Первая index_date: 2025-03-31 12:11:17, Последняя index_date: 2025-03-31 12:11:21
📌 Всего записей на странице: 479
📌 Примеры данных:
  - ID: 78355890, index_date: 2025-03-31 12:11:17
  - ID: 78355888, index_date: 2025-03-31 12:06:58
  - ID: 78355887, index_date: 2025-03-31 12:11:20
📌 Новых записей (index_date > 2025-03-28 14:10:17): 477
✅ Загружено 477 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78353784
📅 Первая index_date: 2025-03-31 17:44:20, Последняя index_date: 2025-03-31 12:08:04
📌 Всего записей на странице: 467
📌 Примеры данных:
  - ID: 78353776, index_date: 2025-03-31 17:44:20
  - ID: 78353770, index_date: 2025-03-31 12:09:12
  - ID: 78353766, index_date: 2025-03-31 12:13:23
📌 Новых записей (index_date > 2025-03-28 14:10:17): 458
✅ Загружено 458 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78351457
📅 Первая index_date: 2025-03-31 12:08:03, Последняя index_date: 2025-03-31 12:12:19
📌 Всего записей на странице: 478
📌 Примеры данных:
  - ID: 78351455, index_date: 2025-03-31 12:08:03
  - ID: 78351450, index_date: 2025-03-31 12:09:45
  - ID: 78351448, index_date: 2025-03-31 12:06:57
📌 Новых записей (index_date > 2025-03-28 14:10:17): 478
✅ Загружено 478 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78348775
📅 Первая index_date: 2025-03-31 12:06:57, Последняя index_date: 2025-03-31 12:06:35
📌 Всего записей на странице: 468
📌 Примеры данных:
  - ID: 78348771, index_date: 2025-03-31 12:06:57
  - ID: 78348767, index_date: 2025-03-31 12:12:18
  - ID: 78348765, index_date: 2025-03-31 12:10:21
📌 Новых записей (index_date > 2025-03-28 14:10:17): 466
✅ Загружено 466 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78345823
📅 Первая index_date: 2025-03-31 12:05:40, Последняя index_date: 2025-03-31 12:09:14
📌 Всего записей на странице: 450
📌 Примеры данных:
  - ID: 78345822, index_date: 2025-03-31 12:05:40
  - ID: 78345820, index_date: 2025-03-31 17:44:34
  - ID: 78345816, index_date: 2025-03-31 17:43:42
📌 Новых записей (index_date > 2025-03-28 14:10:17): 449
✅ Загружено 449 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78343429
📅 Первая index_date: 2025-03-31 17:43:50, Последняя index_date: 2025-03-31 12:11:21
📌 Всего записей на странице: 452
📌 Примеры данных:
  - ID: 78343424, index_date: 2025-03-31 17:43:50
  - ID: 78343418, index_date: 2025-03-31 12:11:05
  - ID: 78343417, index_date: 2025-03-31 12:07:58
📌 Новых записей (index_date > 2025-03-28 14:10:17): 452
✅ Загружено 452 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78341159
📅 Первая index_date: 2025-03-31 12:09:15, Последняя index_date: 2025-03-31 12:11:12
📌 Всего записей на странице: 421
📌 Примеры данных:
  - ID: 78341155, index_date: 2025-03-31 12:09:15
  - ID: 78341149, index_date: 2025-03-31 12:12:01
  - ID: 78341134, index_date: 2025-03-31 12:08:05
📌 Новых записей (index_date > 2025-03-28 14:10:17): 421
✅ Загружено 421 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78338840
📅 Первая index_date: 2025-03-31 12:10:08, Последняя index_date: 2025-03-31 12:06:57
📌 Всего записей на странице: 445
📌 Примеры данных:
  - ID: 78338836, index_date: 2025-03-31 12:10:08
  - ID: 78338829, index_date: 2025-03-31 12:11:05
  - ID: 78338827, index_date: 2025-03-31 12:07:45
📌 Новых записей (index_date > 2025-03-28 14:10:17): 445
✅ Загружено 445 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78335910
📅 Первая index_date: 2025-03-31 20:41:17, Последняя index_date: 2025-03-31 12:06:47
📌 Всего записей на странице: 436
📌 Примеры данных:
  - ID: 78335909, index_date: 2025-03-31 20:41:17
  - ID: 78335904, index_date: 2025-03-31 20:41:16
  - ID: 78335900, index_date: 2025-03-31 12:14:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 434
✅ Загружено 434 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78332937
📅 Первая index_date: 2025-03-31 12:07:45, Последняя index_date: 2025-03-31 12:13:22
📌 Всего записей на странице: 425
📌 Примеры данных:
  - ID: 78332920, index_date: 2025-03-31 12:07:45
  - ID: 78332918, index_date: 2025-03-31 12:14:17
  - ID: 78332916, index_date: 2025-03-31 12:07:31
📌 Новых записей (index_date > 2025-03-28 14:10:17): 422
✅ Загружено 422 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78330205
📅 Первая index_date: 2025-03-31 17:43:55, Последняя index_date: None
📌 Всего записей на странице: 439
📌 Примеры данных:
  - ID: 78330204, index_date: 2025-03-31 17:43:55
  - ID: 78330201, index_date: 2025-03-31 12:11:50
  - ID: 78330191, index_date: 2025-03-31 12:09:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 436
✅ Загружено 436 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78327236
📅 Первая index_date: 2025-03-31 12:11:05, Последняя index_date: 2025-03-31 12:11:20
📌 Всего записей на странице: 445
📌 Примеры данных:
  - ID: 78327221, index_date: 2025-03-31 12:11:05
  - ID: 78327217, index_date: 2025-03-31 12:11:19
  - ID: 78327211, index_date: 2025-03-31 12:10:10
📌 Новых записей (index_date > 2025-03-28 14:10:17): 444
✅ Загружено 444 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78323147
📅 Первая index_date: 2025-03-31 12:13:22, Последняя index_date: 2025-03-31 12:06:58
📌 Всего записей на странице: 442
📌 Примеры данных:
  - ID: 78323142, index_date: 2025-03-31 12:13:22
  - ID: 78323122, index_date: 2025-03-31 12:12:49
  - ID: 78323121, index_date: 2025-03-31 12:10:21
📌 Новых записей (index_date > 2025-03-28 14:10:17): 440
✅ Загружено 440 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78320913
📅 Первая index_date: 2025-03-31 12:12:01, Последняя index_date: 2025-03-31 12:06:17
📌 Всего записей на странице: 488
📌 Примеры данных:
  - ID: 78320910, index_date: 2025-03-31 12:12:01
  - ID: 78320875, index_date: 2025-03-31 12:12:01
  - ID: 78320851, index_date: 2025-03-31 12:09:06
📌 Новых записей (index_date > 2025-03-28 14:10:17): 487
✅ Загружено 487 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78318193
📅 Первая index_date: 2025-03-31 12:11:21, Последняя index_date: None
📌 Всего записей на странице: 341
📌 Примеры данных:
  - ID: 78318192, index_date: 2025-03-31 12:11:21
  - ID: 78318185, index_date: 2025-03-31 12:09:45
  - ID: 78318184, index_date: 2025-03-31 12:08:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 336
✅ Загружено 336 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78314526
📅 Первая index_date: 2025-03-31 12:14:13, Последняя index_date: None
📌 Всего записей на странице: 388
📌 Примеры данных:
  - ID: 78314454, index_date: 2025-03-31 12:14:13
  - ID: 78314423, index_date: 2025-03-31 12:10:08
  - ID: 78314422, index_date: 2025-03-31 12:13:17
📌 Новых записей (index_date > 2025-03-28 14:10:17): 386
✅ Загружено 386 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78309093
📅 Первая index_date: 2025-03-31 12:12:01, Последняя index_date: None
📌 Всего записей на странице: 398
📌 Примеры данных:
  - ID: 78309083, index_date: 2025-03-31 12:12:01
  - ID: 78309077, index_date: 2025-03-31 12:13:52
  - ID: 78309073, index_date: 2025-03-31 12:12:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 396
✅ Загружено 396 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78304858
📅 Первая index_date: 2025-03-31 12:14:20, Последняя index_date: 2025-03-31 12:07:55
📌 Всего записей на странице: 406
📌 Примеры данных:
  - ID: 78304855, index_date: 2025-03-31 12:14:20
  - ID: 78304849, index_date: 2025-03-31 12:06:58
  - ID: 78304838, index_date: 2025-03-31 12:13:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 402
✅ Загружено 402 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78300209
📅 Первая index_date: 2025-03-31 12:07:31, Последняя index_date: 2025-03-31 12:09:45
📌 Всего записей на странице: 394
📌 Примеры данных:
  - ID: 78300175, index_date: 2025-03-31 12:07:31
  - ID: 78300155, index_date: 2025-03-31 12:14:13
  - ID: 78300133, index_date: 2025-03-31 12:11:50
📌 Новых записей (index_date > 2025-03-28 14:10:17): 394
✅ Загружено 394 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78292529
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:12:20
📌 Всего записей на странице: 381
📌 Примеры данных:
  - ID: 78292501, index_date: 2025-03-31 12:11:51
  - ID: 78292495, index_date: 2025-03-31 12:06:58
  - ID: 78292484, index_date: 2025-03-31 12:13:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 378
✅ Загружено 378 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78286539
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:06:58
📌 Всего записей на странице: 405
📌 Примеры данных:
  - ID: 78286518, index_date: 2025-03-31 17:44:34
  - ID: 78286513, index_date: 2025-03-31 12:11:17
  - ID: 78286484, index_date: 2025-03-31 12:08:41
📌 Новых записей (index_date > 2025-03-28 14:10:17): 398
✅ Загружено 398 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78281278
📅 Первая index_date: 2025-03-31 12:09:15, Последняя index_date: 2025-03-31 17:43:42
📌 Всего записей на странице: 451
📌 Примеры данных:
  - ID: 78281262, index_date: 2025-03-31 12:09:15
  - ID: 78281254, index_date: 2025-03-31 12:06:50
  - ID: 78281253, index_date: 2025-03-31 18:16:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 448
✅ Загружено 448 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78276767
📅 Первая index_date: 2025-03-31 12:11:12, Последняя index_date: 2025-03-31 17:43:51
📌 Всего записей на странице: 382
📌 Примеры данных:
  - ID: 78276755, index_date: 2025-03-31 12:11:12
  - ID: 78276753, index_date: 2025-03-31 12:13:52
  - ID: 78276746, index_date: 2025-03-31 12:06:35
📌 Новых записей (index_date > 2025-03-28 14:10:17): 377
✅ Загружено 377 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78271256
📅 Первая index_date: 2025-03-31 12:09:56, Последняя index_date: 2025-03-31 12:09:15
📌 Всего записей на странице: 430
📌 Примеры данных:
  - ID: 78271245, index_date: 2025-03-31 12:09:56
  - ID: 78271241, index_date: 2025-03-31 17:43:31
  - ID: 78271202, index_date: 2025-03-31 12:12:09
📌 Новых записей (index_date > 2025-03-28 14:10:17): 430
✅ Загружено 430 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78266223
📅 Первая index_date: 2025-03-31 12:13:24, Последняя index_date: 2025-03-31 17:43:35
📌 Всего записей на странице: 386
📌 Примеры данных:
  - ID: 78266219, index_date: 2025-03-31 12:13:24
  - ID: 78266218, index_date: 2025-03-31 12:10:08
  - ID: 78266215, index_date: 2025-03-31 12:11:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 380
✅ Загружено 380 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78260488
📅 Первая index_date: 2025-03-31 12:06:50, Последняя index_date: 2025-03-31 12:07:32
📌 Всего записей на странице: 417
📌 Примеры данных:
  - ID: 78260470, index_date: 2025-03-31 12:06:50
  - ID: 78260463, index_date: 2025-03-31 12:09:12
  - ID: 78260461, index_date: 2025-03-31 12:09:15
📌 Новых записей (index_date > 2025-03-28 14:10:17): 414
✅ Загружено 414 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78256087
📅 Первая index_date: 2025-03-31 12:09:01, Последняя index_date: 2025-03-31 12:06:35
📌 Всего записей на странице: 377
📌 Примеры данных:
  - ID: 78256086, index_date: 2025-03-31 12:09:01
  - ID: 78256076, index_date: 2025-03-31 12:12:09
  - ID: 78256067, index_date: 2025-03-31 12:07:58
📌 Новых записей (index_date > 2025-03-28 14:10:17): 374
✅ Загружено 374 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78251588
📅 Первая index_date: 2025-03-31 12:13:03, Последняя index_date: None
📌 Всего записей на странице: 356
📌 Примеры данных:
  - ID: 78251583, index_date: 2025-03-31 12:13:03
  - ID: 78251572, index_date: 2025-03-31 12:10:53
  - ID: 78251568, index_date: 2025-03-31 12:09:01
📌 Новых записей (index_date > 2025-03-28 14:10:17): 351
✅ Загружено 351 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78247727
📅 Первая index_date: 2025-03-31 12:13:24, Последняя index_date: None
📌 Всего записей на странице: 383
📌 Примеры данных:
  - ID: 78247722, index_date: 2025-03-31 12:13:24
  - ID: 78247702, index_date: 2025-03-31 12:09:12
  - ID: 78247700, index_date: 2025-03-31 12:06:57
📌 Новых записей (index_date > 2025-03-28 14:10:17): 379
✅ Загружено 379 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78242692
📅 Первая index_date: 2025-03-31 12:12:16, Последняя index_date: 2025-03-31 12:11:51
📌 Всего записей на странице: 332
📌 Примеры данных:
  - ID: 78242679, index_date: 2025-03-31 12:12:16
  - ID: 78242671, index_date: 2025-03-31 12:11:22
  - ID: 78242666, index_date: 2025-03-31 17:43:38
📌 Новых записей (index_date > 2025-03-28 14:10:17): 331
✅ Загружено 331 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78238033
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:06:50
📌 Всего записей на странице: 338
📌 Примеры данных:
  - ID: 78238013, index_date: 2025-03-31 12:12:16
  - ID: 78238008, index_date: 2025-03-31 12:12:20
  - ID: 78237997, index_date: 2025-03-31 12:06:35
📌 Новых записей (index_date > 2025-03-28 14:10:17): 337
✅ Загружено 337 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78231682
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:11:05
📌 Всего записей на странице: 289
📌 Примеры данных:
  - ID: 78231663, index_date: 2025-03-31 12:07:55
  - ID: 78231657, index_date: 2025-03-31 12:05:40
  - ID: 78231656, index_date: 2025-03-31 12:14:20
📌 Новых записей (index_date > 2025-03-28 14:10:17): 286
✅ Загружено 286 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78226688
📅 Первая index_date: 2025-03-31 12:12:49, Последняя index_date: 2025-03-31 12:11:51
📌 Всего записей на странице: 365
📌 Примеры данных:
  - ID: 78226682, index_date: 2025-03-31 12:12:49
  - ID: 78226675, index_date: 2025-03-31 12:11:05
  - ID: 78226654, index_date: 2025-03-31 12:07:51
📌 Новых записей (index_date > 2025-03-28 14:10:17): 360
✅ Загружено 360 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78222300
📅 Первая index_date: 2025-03-31 12:12:49, Последняя index_date: 2025-03-31 12:08:05
📌 Всего записей на странице: 417
📌 Примеры данных:
  - ID: 78222294, index_date: 2025-03-31 12:12:49
  - ID: 78222286, index_date: 2025-03-31 12:09:46
  - ID: 78222269, index_date: 2025-03-31 12:08:41
📌 Новых записей (index_date > 2025-03-28 14:10:17): 415
✅ Загружено 415 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78215306
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:06:43
📌 Всего записей на странице: 350
📌 Примеры данных:
  - ID: 78215193, index_date: 2025-03-31 12:09:15
  - ID: 78215172, index_date: 2025-03-31 12:10:22
  - ID: 78215147, index_date: 2025-03-31 12:07:32
📌 Новых записей (index_date > 2025-03-28 14:10:17): 350
✅ Загружено 350 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78209452
📅 Первая index_date: 2025-03-31 12:06:58, Последняя index_date: 2025-03-31 17:43:50
📌 Всего записей на странице: 415
📌 Примеры данных:
  - ID: 78209447, index_date: 2025-03-31 12:06:58
  - ID: 78209444, index_date: 2025-03-31 12:10:04
  - ID: 78209435, index_date: 2025-03-31 12:14:13
📌 Новых записей (index_date > 2025-03-28 14:10:17): 415
✅ Загружено 415 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78205999
📅 Первая index_date: 2025-03-31 12:10:22, Последняя index_date: 2025-03-31 12:10:04
📌 Всего записей на странице: 416
📌 Примеры данных:
  - ID: 78205982, index_date: 2025-03-31 12:10:22
  - ID: 78205937, index_date: 2025-03-31 19:01:34
  - ID: 78205936, index_date: 2025-03-31 12:12:49
📌 Новых записей (index_date > 2025-03-28 14:10:17): 409
✅ Загружено 409 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78201258
📅 Первая index_date: 2025-03-31 12:09:46, Последняя index_date: 2025-03-31 12:11:12
📌 Всего записей на странице: 351
📌 Примеры данных:
  - ID: 78201251, index_date: 2025-03-31 12:09:46
  - ID: 78201249, index_date: 2025-03-31 12:12:18
  - ID: 78201246, index_date: 2025-03-31 18:32:20
📌 Новых записей (index_date > 2025-03-28 14:10:17): 349
✅ Загружено 349 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78196867
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:09:15
📌 Всего записей на странице: 395
📌 Примеры данных:
  - ID: 78196850, index_date: 2025-03-31 12:12:02
  - ID: 78196828, index_date: 2025-03-31 12:08:53
  - ID: 78196809, index_date: 2025-03-31 12:14:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 386
✅ Загружено 386 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78193552
📅 Первая index_date: 2025-03-31 12:06:44, Последняя index_date: None
📌 Всего записей на странице: 302
📌 Примеры данных:
  - ID: 78193549, index_date: 2025-03-31 12:06:44
  - ID: 78193528, index_date: 2025-03-31 12:06:36
  - ID: 78193487, index_date: 2025-03-31 12:11:23
📌 Новых записей (index_date > 2025-03-28 14:10:17): 291
✅ Загружено 291 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78189259
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:10:08
📌 Всего записей на странице: 335
📌 Примеры данных:
  - ID: 78189234, index_date: 2025-03-31 12:11:17
  - ID: 78189148, index_date: 2025-03-31 12:13:17
  - ID: 78189138, index_date: 2025-03-31 12:13:52
📌 Новых записей (index_date > 2025-03-28 14:10:17): 324
✅ Загружено 324 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78185199
📅 Первая index_date: 2025-03-31 19:01:34, Последняя index_date: 2025-03-31 12:12:20
📌 Всего записей на странице: 386
📌 Примеры данных:
  - ID: 78185196, index_date: 2025-03-31 19:01:34
  - ID: 78185159, index_date: 2025-03-31 12:06:36
  - ID: 78185136, index_date: 2025-03-31 19:01:33
📌 Новых записей (index_date > 2025-03-28 14:10:17): 377
✅ Загружено 377 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78181225
📅 Первая index_date: 2025-03-31 12:05:40, Последняя index_date: None
📌 Всего записей на странице: 349
📌 Примеры данных:
  - ID: 78181219, index_date: 2025-03-31 12:05:40
  - ID: 78181212, index_date: 2025-03-31 12:09:15
  - ID: 78181208, index_date: 2025-03-31 12:06:58
📌 Новых записей (index_date > 2025-03-28 14:10:17): 348
✅ Загружено 348 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78177246
📅 Первая index_date: 2025-03-31 17:44:26, Последняя index_date: 2025-03-31 12:07:58
📌 Всего записей на странице: 323
📌 Примеры данных:
  - ID: 78177242, index_date: 2025-03-31 17:44:26
  - ID: 78177186, index_date: 2025-03-31 12:06:58
  - ID: 78177182, index_date: 2025-03-31 17:43:55
📌 Новых записей (index_date > 2025-03-28 14:10:17): 321
✅ Загружено 321 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78172375
📅 Первая index_date: 2025-03-31 12:13:24, Последняя index_date: 2025-03-31 12:10:10
📌 Всего записей на странице: 406
📌 Примеры данных:
  - ID: 78172363, index_date: 2025-03-31 12:13:24
  - ID: 78172342, index_date: 2025-03-31 17:44:30
  - ID: 78172341, index_date: 2025-03-31 12:10:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 393
✅ Загружено 393 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78166206
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:14:13
📌 Всего записей на странице: 350
📌 Примеры данных:
  - ID: 78166194, index_date: 2025-03-31 12:09:01
  - ID: 78166177, index_date: 2025-03-31 12:09:01
  - ID: 78166165, index_date: 2025-03-31 12:12:20
📌 Новых записей (index_date > 2025-03-28 14:10:17): 341
✅ Загружено 341 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78161259
📅 Первая index_date: 2025-03-31 12:14:20, Последняя index_date: 2025-03-31 12:13:13
📌 Всего записей на странице: 380
📌 Примеры данных:
  - ID: 78161258, index_date: 2025-03-31 12:14:20
  - ID: 78161254, index_date: 2025-03-31 12:06:18
  - ID: 78161237, index_date: 2025-03-31 12:06:48
📌 Новых записей (index_date > 2025-03-28 14:10:17): 376
✅ Загружено 376 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78156580
📅 Первая index_date: 2025-03-31 12:13:13, Последняя index_date: 2025-03-31 12:10:04
📌 Всего записей на странице: 417
📌 Примеры данных:
  - ID: 78156572, index_date: 2025-03-31 12:13:13
  - ID: 78156553, index_date: 2025-03-31 12:13:13
  - ID: 78156545, index_date: 2025-03-31 12:12:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 414
✅ Загружено 414 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78151015
📅 Первая index_date: 2025-03-31 12:11:51, Последняя index_date: None
📌 Всего записей на странице: 414
📌 Примеры данных:
  - ID: 78151004, index_date: 2025-03-31 12:11:51
  - ID: 78151003, index_date: 2025-03-31 12:08:05
  - ID: 78150998, index_date: 2025-03-31 17:03:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 412
✅ Загружено 412 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78146280
📅 Первая index_date: 2025-03-31 17:44:13, Последняя index_date: 2025-03-31 16:44:57
📌 Всего записей на странице: 368
📌 Примеры данных:
  - ID: 78146276, index_date: 2025-03-31 17:44:13
  - ID: 78146265, index_date: 2025-03-31 12:14:13
  - ID: 78146203, index_date: 2025-03-31 17:43:47
📌 Новых записей (index_date > 2025-03-28 14:10:17): 354
✅ Загружено 354 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78140889
📅 Первая index_date: None, Последняя index_date: 2025-03-31 20:41:16
📌 Всего записей на странице: 351
📌 Примеры данных:
  - ID: 78140859, index_date: 2025-03-31 12:09:56
  - ID: 78140773, index_date: 2025-03-31 12:08:42
  - ID: 78140770, index_date: 2025-03-31 12:13:52
📌 Новых записей (index_date > 2025-03-28 14:10:17): 346
✅ Загружено 346 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78137269
📅 Первая index_date: None, Последняя index_date: 2025-03-31 17:43:35
📌 Всего записей на странице: 417
📌 Примеры данных:
  - ID: 78137262, index_date: 2025-03-31 12:13:17
  - ID: 78137258, index_date: 2025-03-31 12:13:22
  - ID: 78137251, index_date: 2025-03-31 12:06:18
📌 Новых записей (index_date > 2025-03-28 14:10:17): 408
✅ Загружено 408 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78133572
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:05:40
📌 Всего записей на странице: 425
📌 Примеры данных:
  - ID: 78133560, index_date: 2025-03-31 12:13:24
  - ID: 78133558, index_date: 2025-03-31 12:09:01
  - ID: 78133556, index_date: 2025-03-31 17:44:05
📌 Новых записей (index_date > 2025-03-28 14:10:17): 422
✅ Загружено 422 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78129783
📅 Первая index_date: 2025-03-31 12:11:13, Последняя index_date: 2025-03-31 12:07:58
📌 Всего записей на странице: 325
📌 Примеры данных:
  - ID: 78129775, index_date: 2025-03-31 12:11:13
  - ID: 78129767, index_date: 2025-03-31 12:09:06
  - ID: 78129755, index_date: 2025-03-31 12:11:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 324
✅ Загружено 324 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78126107
📅 Первая index_date: 2025-03-31 12:10:10, Последняя index_date: 2025-03-31 12:08:53
📌 Всего записей на странице: 341
📌 Примеры данных:
  - ID: 78126106, index_date: 2025-03-31 12:10:10
  - ID: 78126005, index_date: 2025-03-31 12:14:17
  - ID: 78125965, index_date: 2025-03-31 12:06:36
📌 Новых записей (index_date > 2025-03-28 14:10:17): 336
✅ Загружено 336 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78121440
📅 Первая index_date: 2025-03-31 12:10:54, Последняя index_date: 2025-03-31 12:11:23
📌 Всего записей на странице: 355
📌 Примеры данных:
  - ID: 78121432, index_date: 2025-03-31 12:10:54
  - ID: 78121368, index_date: 2025-03-31 12:07:55
  - ID: 78121294, index_date: 2025-03-31 12:07:55
📌 Новых записей (index_date > 2025-03-28 14:10:17): 352
✅ Загружено 352 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78117222
📅 Первая index_date: 2025-03-31 17:41:10, Последняя index_date: 2025-03-31 13:26:19
📌 Всего записей на странице: 359
📌 Примеры данных:
  - ID: 78117216, index_date: 2025-03-31 17:41:10
  - ID: 78117210, index_date: 2025-03-31 12:13:17
  - ID: 78117205, index_date: 2025-03-31 12:13:24
📌 Новых записей (index_date > 2025-03-28 14:10:17): 355
✅ Загружено 355 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78113176
📅 Первая index_date: 2025-03-31 12:10:54, Последняя index_date: 2025-03-31 12:13:22
📌 Всего записей на странице: 373
📌 Примеры данных:
  - ID: 78113172, index_date: 2025-03-31 12:10:54
  - ID: 78113170, index_date: 2025-03-31 12:05:40
  - ID: 78113152, index_date: 2025-03-31 12:09:46
📌 Новых записей (index_date > 2025-03-28 14:10:17): 355
✅ Загружено 355 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78108488
📅 Первая index_date: 2025-03-31 12:09:14, Последняя index_date: 2025-03-31 12:12:49
📌 Всего записей на странице: 378
📌 Примеры данных:
  - ID: 78108480, index_date: 2025-03-31 12:09:14
  - ID: 78108475, index_date: 2025-03-31 12:10:54
  - ID: 78108473, index_date: 2025-03-31 12:13:24
📌 Новых записей (index_date > 2025-03-28 14:10:17): 359
✅ Загружено 359 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78104195
📅 Первая index_date: 2025-03-31 12:13:03, Последняя index_date: None
📌 Всего записей на странице: 398
📌 Примеры данных:
  - ID: 78104189, index_date: 2025-03-31 12:13:03
  - ID: 78104170, index_date: 2025-03-31 12:13:52
  - ID: 78104150, index_date: 2025-03-11 11:58:07
📌 Новых записей (index_date > 2025-03-28 14:10:17): 375
✅ Загружено 375 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78100512
📅 Первая index_date: 2025-03-31 12:14:17, Последняя index_date: 2025-03-31 12:12:09
📌 Всего записей на странице: 356
📌 Примеры данных:
  - ID: 78100511, index_date: 2025-03-31 12:14:17
  - ID: 78100508, index_date: 2025-03-31 12:06:44
  - ID: 78100501, index_date: 2025-03-31 12:09:46
📌 Новых записей (index_date > 2025-03-28 14:10:17): 342
✅ Загружено 342 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78095646
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:11:19
📌 Всего записей на странице: 329
📌 Примеры данных:
  - ID: 78095633, index_date: 2025-03-31 12:10:04
  - ID: 78095630, index_date: 2025-03-31 12:10:08
  - ID: 78095623, index_date: 2025-03-31 12:14:13
📌 Новых записей (index_date > 2025-03-28 14:10:17): 298
✅ Загружено 298 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78091613
📅 Первая index_date: 2025-03-14 09:44:10, Последняя index_date: None
📌 Всего записей на странице: 309
📌 Примеры данных:
  - ID: 78091610, index_date: 2025-03-14 09:44:10
  - ID: 78091608, index_date: 2025-03-31 12:05:41
  - ID: 78091607, index_date: 2025-03-31 12:11:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 297
✅ Загружено 297 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78087962
📅 Первая index_date: 2025-03-31 12:11:17, Последняя index_date: 2025-03-31 12:11:19
📌 Всего записей на странице: 399
📌 Примеры данных:
  - ID: 78087959, index_date: 2025-03-31 12:11:17
  - ID: 78087935, index_date: 2025-03-31 12:09:16
  - ID: 78087933, index_date: 2025-03-31 12:05:41
📌 Новых записей (index_date > 2025-03-28 14:10:17): 398
✅ Загружено 398 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78082563
📅 Первая index_date: 2025-03-31 14:56:50, Последняя index_date: None
📌 Всего записей на странице: 380
📌 Примеры данных:
  - ID: 78082558, index_date: 2025-03-31 14:56:50
  - ID: 78082549, index_date: 2025-03-31 12:13:03
  - ID: 78082532, index_date: 2025-03-31 12:08:06
📌 Новых записей (index_date > 2025-03-28 14:10:17): 379
✅ Загружено 379 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78077841
📅 Первая index_date: None, Последняя index_date: None
📌 Всего записей на странице: 369
📌 Примеры данных:
  - ID: 78077838, index_date: 2025-03-31 12:06:18
  - ID: 78077824, index_date: 2025-03-31 12:13:13
  - ID: 78077820, index_date: 2025-03-31 12:12:49
📌 Новых записей (index_date > 2025-03-28 14:10:17): 368
✅ Загружено 368 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78074258
📅 Первая index_date: 2025-03-31 12:06:18, Последняя index_date: None
📌 Всего записей на странице: 419
📌 Примеры данных:
  - ID: 78074250, index_date: 2025-03-31 12:06:18
  - ID: 78074244, index_date: 2025-03-31 12:10:22
  - ID: 78074242, index_date: 2025-03-31 12:10:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 396
✅ Загружено 396 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78070048
📅 Первая index_date: 2025-03-31 12:10:54, Последняя index_date: 2025-03-31 12:12:49
📌 Всего записей на странице: 367
📌 Примеры данных:
  - ID: 78070047, index_date: 2025-03-31 12:10:54
  - ID: 78070037, index_date: 2025-03-31 13:28:40
  - ID: 78070032, index_date: 2025-03-31 17:43:55
📌 Новых записей (index_date > 2025-03-28 14:10:17): 365
✅ Загружено 365 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78066375
📅 Первая index_date: 2025-03-31 12:14:04, Последняя index_date: 2025-03-31 12:10:22
📌 Всего записей на странице: 358
📌 Примеры данных:
  - ID: 78066341, index_date: 2025-03-31 12:14:04
  - ID: 78066335, index_date: 2025-03-31 20:01:25
  - ID: 78066315, index_date: 2025-03-31 12:13:52
📌 Новых записей (index_date > 2025-03-28 14:10:17): 350
✅ Загружено 350 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78063170
📅 Первая index_date: 2025-03-31 12:11:23, Последняя index_date: 2025-03-31 12:07:45
📌 Всего записей на странице: 413
📌 Примеры данных:
  - ID: 78063167, index_date: 2025-03-31 12:11:23
  - ID: 78063160, index_date: 2025-03-31 12:06:18
  - ID: 78063151, index_date: 2025-03-31 12:13:25
📌 Новых записей (index_date > 2025-03-28 14:10:17): 412
✅ Загружено 412 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78060188
📅 Первая index_date: 2025-03-31 12:12:49, Последняя index_date: 2025-03-31 17:43:55
📌 Всего записей на странице: 357
📌 Примеры данных:
  - ID: 78060187, index_date: 2025-03-31 12:12:49
  - ID: 78060182, index_date: 2025-03-31 12:14:17
  - ID: 78060178, index_date: 2025-03-31 12:13:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 355
✅ Загружено 355 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78056719
📅 Первая index_date: 2025-03-31 12:05:41, Последняя index_date: 2025-03-31 12:09:46
📌 Всего записей на странице: 345
📌 Примеры данных:
  - ID: 78056705, index_date: 2025-03-31 12:05:41
  - ID: 78056685, index_date: 2025-03-31 12:06:18
  - ID: 78056674, index_date: 2025-03-31 17:44:08
📌 Новых записей (index_date > 2025-03-28 14:10:17): 343
✅ Загружено 343 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78049851
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:11:23
📌 Всего записей на странице: 319
📌 Примеры данных:
  - ID: 78049839, index_date: 2025-03-31 12:13:25
  - ID: 78049836, index_date: 2025-03-31 12:08:42
  - ID: 78049833, index_date: 2025-03-31 12:09:07
📌 Новых записей (index_date > 2025-03-28 14:10:17): 311
✅ Загружено 311 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78045616
📅 Первая index_date: 2025-03-31 12:08:06, Последняя index_date: 2025-03-31 12:11:23
📌 Всего записей на странице: 390
📌 Примеры данных:
  - ID: 78045609, index_date: 2025-03-31 12:08:06
  - ID: 78045587, index_date: 2025-03-31 12:10:11
  - ID: 78045584, index_date: 2025-03-31 12:12:18
📌 Новых записей (index_date > 2025-03-28 14:10:17): 387
✅ Загружено 387 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78041209
📅 Первая index_date: 2025-03-31 12:12:16, Последняя index_date: None
📌 Всего записей на странице: 382
📌 Примеры данных:
  - ID: 78041204, index_date: 2025-03-31 12:12:16
  - ID: 78041185, index_date: 2025-03-31 12:12:16
  - ID: 78041171, index_date: 2025-03-31 12:09:46
📌 Новых записей (index_date > 2025-03-28 14:10:17): 377
✅ Загружено 377 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78037114
📅 Первая index_date: 2025-03-31 12:12:49, Последняя index_date: 2025-03-31 12:06:59
📌 Всего записей на странице: 385
📌 Примеры данных:
  - ID: 78037111, index_date: 2025-03-31 12:12:49
  - ID: 78037107, index_date: 2025-03-31 12:12:02
  - ID: 78037094, index_date: 2025-03-31 12:13:03
📌 Новых записей (index_date > 2025-03-28 14:10:17): 384
✅ Загружено 384 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78033147
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:06:59
📌 Всего записей на странице: 390
📌 Примеры данных:
  - ID: 78033120, index_date: 2025-03-31 12:13:19
  - ID: 78033100, index_date: 2025-03-31 12:09:01
  - ID: 78033093, index_date: 2025-03-31 12:12:09
📌 Новых записей (index_date > 2025-03-28 14:10:17): 390
✅ Загружено 390 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78028814
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:11:13
📌 Всего записей на странице: 362
📌 Примеры данных:
  - ID: 78028790, index_date: 2025-03-31 12:06:59
  - ID: 78028754, index_date: 2025-03-31 12:14:04
  - ID: 78028748, index_date: 2025-03-31 12:10:11
📌 Новых записей (index_date > 2025-03-28 14:10:17): 362
✅ Загружено 362 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78023686
📅 Первая index_date: 2025-03-31 12:13:13, Последняя index_date: 2025-03-31 12:12:20
📌 Всего записей на странице: 396
📌 Примеры данных:
  - ID: 78023681, index_date: 2025-03-31 12:13:13
  - ID: 78023680, index_date: 2025-03-31 12:08:06
  - ID: 78023678, index_date: 2025-03-31 12:09:46
📌 Новых записей (index_date > 2025-03-28 14:10:17): 395
✅ Загружено 395 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78019422
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:10:08
📌 Всего записей на странице: 385
📌 Примеры данных:
  - ID: 78019409, index_date: 2025-03-31 12:06:59
  - ID: 78019408, index_date: 2025-03-31 12:11:23
  - ID: 78019389, index_date: 2025-03-31 12:10:54
📌 Новых записей (index_date > 2025-03-28 14:10:17): 377
✅ Загружено 377 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78015502
📅 Первая index_date: 2025-03-31 12:07:32, Последняя index_date: 2025-03-31 12:10:22
📌 Всего записей на странице: 366
📌 Примеры данных:
  - ID: 78015500, index_date: 2025-03-31 12:07:32
  - ID: 78015485, index_date: 2025-03-31 12:13:13
  - ID: 78015480, index_date: 2025-03-31 17:44:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 363
✅ Загружено 363 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78011234
📅 Первая index_date: 2025-03-31 12:06:58, Последняя index_date: 2025-03-31 12:11:51
📌 Всего записей на странице: 363
📌 Примеры данных:
  - ID: 78011206, index_date: 2025-03-31 12:06:58
  - ID: 78011203, index_date: 2025-03-31 12:06:44
  - ID: 78011201, index_date: 2025-03-31 17:44:34
📌 Новых записей (index_date > 2025-03-28 14:10:17): 360
✅ Загружено 360 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78007160
📅 Первая index_date: 2025-03-31 12:12:20, Последняя index_date: None
📌 Всего записей на странице: 352
📌 Примеры данных:
  - ID: 78007158, index_date: 2025-03-31 12:12:20
  - ID: 78007156, index_date: 2025-03-31 12:10:22
  - ID: 78007150, index_date: 2025-03-31 12:14:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 349
✅ Загружено 349 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=78003187
📅 Первая index_date: 2025-03-31 12:08:42, Последняя index_date: 2025-03-31 12:08:06
📌 Всего записей на странице: 361
📌 Примеры данных:
  - ID: 78003177, index_date: 2025-03-31 12:08:42
  - ID: 78003176, index_date: 2025-03-31 12:12:18
  - ID: 78003169, index_date: 2025-03-31 12:10:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 356
✅ Загружено 356 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77998489
📅 Первая index_date: None, Последняя index_date: None
📌 Всего записей на странице: 382
📌 Примеры данных:
  - ID: 77998471, index_date: 2025-03-06T19:58:12.559
  - ID: 77998470, index_date: 2025-03-31 12:14:13
  - ID: 77998458, index_date: 2025-03-31 12:09:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 377
✅ Загружено 377 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77994836
📅 Первая index_date: 2025-03-31 12:08:42, Последняя index_date: 2025-03-31 12:12:20
📌 Всего записей на странице: 358
📌 Примеры данных:
  - ID: 77994834, index_date: 2025-03-31 12:08:42
  - ID: 77994828, index_date: 2025-03-31 12:06:19
  - ID: 77994808, index_date: 2025-03-31 12:12:49
📌 Новых записей (index_date > 2025-03-28 14:10:17): 344
✅ Загружено 344 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77990046
📅 Первая index_date: 2025-03-31 12:13:22, Последняя index_date: 2025-03-31 12:07:51
📌 Всего записей на странице: 368
📌 Примеры данных:
  - ID: 77990036, index_date: 2025-03-31 12:13:22
  - ID: 77990033, index_date: 2025-03-31 12:12:02
  - ID: 77990008, index_date: 2025-03-31 12:09:16
📌 Новых записей (index_date > 2025-03-28 14:10:17): 365
✅ Загружено 365 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77986816
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:07:46
📌 Всего записей на странице: 341
📌 Примеры данных:
  - ID: 77986810, index_date: 2025-03-31 12:08:42
  - ID: 77986781, index_date: 2025-03-31 12:07:32
  - ID: 77986764, index_date: 2025-03-31 12:13:03
📌 Новых записей (index_date > 2025-03-28 14:10:17): 340
✅ Загружено 340 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77983198
📅 Первая index_date: 2025-03-31 17:43:46, Последняя index_date: 2025-03-31 12:10:22
📌 Всего записей на странице: 362
📌 Примеры данных:
  - ID: 77983195, index_date: 2025-03-31 17:43:46
  - ID: 77983183, index_date: 2025-03-31 12:09:56
  - ID: 77983171, index_date: 2025-03-31 12:09:16
📌 Новых записей (index_date > 2025-03-28 14:10:17): 342
✅ Загружено 342 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77980177
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:11:51
📌 Всего записей на странице: 372
📌 Примеры данных:
  - ID: 77980164, index_date: 2025-03-31 12:11:05
  - ID: 77980163, index_date: 2025-03-31 12:09:16
  - ID: 77980157, index_date: 2025-03-31 12:10:05
📌 Новых записей (index_date > 2025-03-28 14:10:17): 371
✅ Загружено 371 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77976947
📅 Первая index_date: 2025-03-31 12:06:59, Последняя index_date: 2025-03-31 12:12:49
📌 Всего записей на странице: 340
📌 Примеры данных:
  - ID: 77976938, index_date: 2025-03-31 12:06:59
  - ID: 77976934, index_date: 2025-03-31 12:08:07
  - ID: 77976903, index_date: 2025-03-31 12:10:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 328
✅ Загружено 328 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77973369
📅 Первая index_date: 2025-03-31 12:08:07, Последняя index_date: 2025-03-31 12:10:05
📌 Всего записей на странице: 387
📌 Примеры данных:
  - ID: 77973356, index_date: 2025-03-31 12:08:07
  - ID: 77973312, index_date: 2025-03-31 12:10:22
  - ID: 77973298, index_date: 2025-03-31 12:10:18
📌 Новых записей (index_date > 2025-03-28 14:10:17): 381
✅ Загружено 381 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77969921
📅 Первая index_date: 2025-03-31 12:12:20, Последняя index_date: None
📌 Всего записей на странице: 409
📌 Примеры данных:
  - ID: 77969913, index_date: 2025-03-31 12:12:20
  - ID: 77969902, index_date: 2025-03-31 20:41:16
  - ID: 77969890, index_date: 2025-03-31 12:08:07
📌 Новых записей (index_date > 2025-03-28 14:10:17): 404
✅ Загружено 404 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77965275
📅 Первая index_date: 2025-03-31 17:44:23, Последняя index_date: 2025-03-31 12:13:25
📌 Всего записей на странице: 399
📌 Примеры данных:
  - ID: 77965266, index_date: 2025-03-31 17:44:23
  - ID: 77965264, index_date: 2025-03-31 12:14:20
  - ID: 77965263, index_date: 2025-03-31 12:06:36
📌 Новых записей (index_date > 2025-03-28 14:10:17): 397
✅ Загружено 397 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77961653
📅 Первая index_date: 2025-03-31 12:14:20, Последняя index_date: None
📌 Всего записей на странице: 399
📌 Примеры данных:
  - ID: 77961646, index_date: 2025-03-31 12:14:20
  - ID: 77961644, index_date: 2025-03-31 12:11:51
  - ID: 77961639, index_date: 2025-03-31 12:08:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 397
✅ Загружено 397 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77958667
📅 Первая index_date: 2025-03-31 12:14:19, Последняя index_date: 2025-03-31 12:12:09
📌 Всего записей на странице: 364
📌 Примеры данных:
  - ID: 77958660, index_date: 2025-03-31 12:14:19
  - ID: 77958657, index_date: 2025-03-31 12:06:20
  - ID: 77958649, index_date: 2025-03-31 12:13:03
📌 Новых записей (index_date > 2025-03-28 14:10:17): 364
✅ Загружено 364 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77955290
📅 Первая index_date: 2025-03-31 12:14:17, Последняя index_date: 2025-03-31 17:43:59
📌 Всего записей на странице: 450
📌 Примеры данных:
  - ID: 77955251, index_date: 2025-03-31 12:14:17
  - ID: 77955247, index_date: 2025-03-31 12:11:51
  - ID: 77955240, index_date: 2025-03-31 12:08:07
📌 Новых записей (index_date > 2025-03-28 14:10:17): 448
✅ Загружено 448 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77952078
📅 Первая index_date: 2025-03-31 12:05:41, Последняя index_date: 2025-03-31 12:08:07
📌 Всего записей на странице: 393
📌 Примеры данных:
  - ID: 77952070, index_date: 2025-03-31 12:05:41
  - ID: 77952067, index_date: 2025-03-31 12:09:01
  - ID: 77952060, index_date: 2025-03-31 12:07:51
📌 Новых записей (index_date > 2025-03-28 14:10:17): 362
✅ Загружено 362 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77949345
📅 Первая index_date: 2025-03-31 12:11:51, Последняя index_date: 2025-03-31 12:09:56
📌 Всего записей на странице: 389
📌 Примеры данных:
  - ID: 77949338, index_date: 2025-03-31 12:11:51
  - ID: 77949337, index_date: 2025-03-31 12:07:32
  - ID: 77949332, index_date: 2025-03-31 12:06:59
📌 Новых записей (index_date > 2025-03-28 14:10:17): 365
✅ Загружено 365 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77946900
📅 Первая index_date: 2025-03-31 17:44:04, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 415
📌 Примеры данных:
  - ID: 77946895, index_date: 2025-03-31 17:44:04
  - ID: 77946894, index_date: 2025-03-31 12:13:13
  - ID: 77946891, index_date: 2025-03-31 12:07:58
📌 Новых записей (index_date > 2025-03-28 14:10:17): 389
✅ Загружено 389 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77944199
📅 Первая index_date: 2025-03-31 12:14:19, Последняя index_date: 2025-03-03T14:28:52.060
📌 Всего записей на странице: 418
📌 Примеры данных:
  - ID: 77944194, index_date: 2025-03-31 12:14:19
  - ID: 77944190, index_date: 2025-03-31 12:08:42
  - ID: 77944187, index_date: 2025-03-31 17:43:38
📌 Новых записей (index_date > 2025-03-28 14:10:17): 397
✅ Загружено 397 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77941693
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:12:09
📌 Всего записей на странице: 422
📌 Примеры данных:
  - ID: 77941691, index_date: 2025-03-31 12:08:42
  - ID: 77941688, index_date: 2025-03-31 12:08:53
  - ID: 77941685, index_date: 2025-03-31 12:06:20
📌 Новых записей (index_date > 2025-03-28 14:10:17): 396
✅ Загружено 396 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77938155
📅 Первая index_date: 2025-03-31 12:11:05, Последняя index_date: 2025-03-31 14:38:24
📌 Всего записей на странице: 421
📌 Примеры данных:
  - ID: 77938152, index_date: 2025-03-31 12:11:05
  - ID: 77938147, index_date: 2025-03-31 12:09:46
  - ID: 77938139, index_date: 2025-03-31 12:06:36
📌 Новых записей (index_date > 2025-03-28 14:10:17): 400
✅ Загружено 400 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77935030
📅 Первая index_date: None, Последняя index_date: None
📌 Всего записей на странице: 368
📌 Примеры данных:
  - ID: 77935023, index_date: 2025-03-31 14:38:24
  - ID: 77935016, index_date: 2025-03-31 12:05:41
  - ID: 77935013, index_date: 2025-03-31 14:38:24
📌 Новых записей (index_date > 2025-03-28 14:10:17): 307
✅ Загружено 307 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77932191
📅 Первая index_date: 2025-03-31 12:14:17, Последняя index_date: 2025-03-31 12:07:32
📌 Всего записей на странице: 409
📌 Примеры данных:
  - ID: 77932185, index_date: 2025-03-31 12:14:17
  - ID: 77932180, index_date: 2025-03-31 12:08:07
  - ID: 77932176, index_date: 2025-03-31 12:08:07
📌 Новых записей (index_date > 2025-03-28 14:10:17): 392
✅ Загружено 392 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77928807
📅 Первая index_date: 2025-03-31 12:06:20, Последняя index_date: 2025-03-31 12:07:46
📌 Всего записей на странице: 419
📌 Примеры данных:
  - ID: 77928806, index_date: 2025-03-31 12:06:20
  - ID: 77928804, index_date: 2025-03-31 12:09:14
  - ID: 77928802, index_date: 2025-03-31 12:10:08
📌 Новых записей (index_date > 2025-03-28 14:10:17): 362
✅ Загружено 362 новых записей с этой страницы...
❌ Ошибка запроса: HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⏳ Ждём 30 сек и пробуем снова...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77925363
📅 Первая index_date: 2025-03-31 12:11:19, Последняя index_date: None
📌 Всего записей на странице: 427
📌 Примеры данных:
  - ID: 77925355, index_date: 2025-03-31 12:11:19
  - ID: 77925354, index_date: 2025-03-31 12:05:41
  - ID: 77925348, index_date: 2025-03-31 12:12:20
📌 Новых записей (index_date > 2025-03-28 14:10:17): 412
✅ Загружено 412 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77922413
📅 Первая index_date: 2025-03-31 12:12:18, Последняя index_date: None
📌 Всего записей на странице: 394
📌 Примеры данных:
  - ID: 77922409, index_date: 2025-03-31 12:12:18
  - ID: 77922393, index_date: 2025-03-31 12:07:51
  - ID: 77922388, index_date: 2025-03-31 12:11:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 369
✅ Загружено 369 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77919091
📅 Первая index_date: 2025-03-31 12:09:16, Последняя index_date: 2025-03-31 17:44:30
📌 Всего записей на странице: 372
📌 Примеры данных:
  - ID: 77919085, index_date: 2025-03-31 12:09:16
  - ID: 77919084, index_date: 2025-03-31 12:06:59
  - ID: 77919083, index_date: 2025-03-31 12:12:13
📌 Новых записей (index_date > 2025-03-28 14:10:17): 351
✅ Загружено 351 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77915517
📅 Первая index_date: 2025-03-31 12:06:20, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 382
📌 Примеры данных:
  - ID: 77915513, index_date: 2025-03-31 12:06:20
  - ID: 77915510, index_date: 2025-03-31 12:06:44
  - ID: 77915503, index_date: 2025-03-31 12:12:50
📌 Новых записей (index_date > 2025-03-28 14:10:17): 340
✅ Загружено 340 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77912120
📅 Первая index_date: 2025-03-31 12:13:03, Последняя index_date: 2025-03-31 20:41:16
📌 Всего записей на странице: 385
📌 Примеры данных:
  - ID: 77912111, index_date: 2025-03-31 12:13:03
  - ID: 77912106, index_date: 2025-02-28 17:41:14
  - ID: 77912105, index_date: 2025-03-31 19:01:34
📌 Новых записей (index_date > 2025-03-28 14:10:17): 371
✅ Загружено 371 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77909687
📅 Первая index_date: 2025-03-31 12:12:02, Последняя index_date: 2025-03-31 12:13:13
📌 Всего записей на странице: 412
📌 Примеры данных:
  - ID: 77909685, index_date: 2025-03-31 12:12:02
  - ID: 77909679, index_date: 2025-03-31 20:41:17
  - ID: 77909675, index_date: 2025-03-31 12:09:56
📌 Новых записей (index_date > 2025-03-28 14:10:17): 404
✅ Загружено 404 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77906752
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:12:49
📌 Всего записей на странице: 413
📌 Примеры данных:
  - ID: 77906744, index_date: 2025-03-31 12:12:21
  - ID: 77906739, index_date: 2025-03-31 12:10:11
  - ID: 77906736, index_date: 2025-03-31 12:07:56
📌 Новых записей (index_date > 2025-03-28 14:10:17): 225
✅ Загружено 225 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77904578
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:08:07
📌 Всего записей на странице: 329
📌 Примеры данных:
  - ID: 77904548, index_date: 2025-03-31 12:09:12
  - ID: 77904544, index_date: 2025-03-31 17:42:43
  - ID: 77904530, index_date: 2025-03-31 13:50:50
📌 Новых записей (index_date > 2025-03-28 14:10:17): 320
✅ Загружено 320 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77901940
📅 Первая index_date: 2025-03-31 12:12:02, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 372
📌 Примеры данных:
  - ID: 77901936, index_date: 2025-03-31 12:12:02
  - ID: 77901927, index_date: 2025-03-31 12:07:46
  - ID: 77901910, index_date: 2025-03-31 12:09:16
📌 Новых записей (index_date > 2025-03-28 14:10:17): 366
✅ Загружено 366 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77898425
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:13:03
📌 Всего записей на странице: 351
📌 Примеры данных:
  - ID: 77898412, index_date: 2025-03-31 12:14:19
  - ID: 77898370, index_date: 2025-03-31 12:13:53
  - ID: 77898361, index_date: 2025-03-31 12:10:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 346
✅ Загружено 346 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77895360
📅 Первая index_date: 2025-03-31 12:09:07, Последняя index_date: None
📌 Всего записей на странице: 382
📌 Примеры данных:
  - ID: 77895357, index_date: 2025-03-31 12:09:07
  - ID: 77895351, index_date: 2025-03-31 12:09:46
  - ID: 77895337, index_date: 2025-03-31 12:09:46
📌 Новых записей (index_date > 2025-03-28 14:10:17): 371
✅ Загружено 371 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77892644
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:13:17
📌 Всего записей на странице: 371
📌 Примеры данных:
  - ID: 77892631, index_date: 2025-03-31 12:10:19
  - ID: 77892624, index_date: 2025-03-31 12:11:06
  - ID: 77892620, index_date: 2025-03-31 12:06:36
📌 Новых записей (index_date > 2025-03-28 14:10:17): 349
✅ Загружено 349 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77889926
📅 Первая index_date: 2025-03-31 12:07:51, Последняя index_date: None
📌 Всего записей на странице: 396
📌 Примеры данных:
  - ID: 77889925, index_date: 2025-03-31 12:07:51
  - ID: 77889924, index_date: 2025-03-31 12:13:13
  - ID: 77889916, index_date: 2025-03-31 12:12:50
📌 Новых записей (index_date > 2025-03-28 14:10:17): 387
✅ Загружено 387 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77886782
📅 Первая index_date: 2025-03-31 12:12:13, Последняя index_date: 2025-03-31 12:08:07
📌 Всего записей на странице: 427
📌 Примеры данных:
  - ID: 77886780, index_date: 2025-03-31 12:12:13
  - ID: 77886779, index_date: 2025-03-31 12:07:58
  - ID: 77886770, index_date: 2025-03-31 12:12:13
📌 Новых записей (index_date > 2025-03-28 14:10:17): 419
✅ Загружено 419 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77883810
📅 Первая index_date: 2025-03-31 12:09:46, Последняя index_date: 2025-03-31 12:14:17
📌 Всего записей на странице: 427
📌 Примеры данных:
  - ID: 77883808, index_date: 2025-03-31 12:09:46
  - ID: 77883802, index_date: 2025-03-31 16:48:38
  - ID: 77883799, index_date: 2025-03-31 12:07:32
📌 Новых записей (index_date > 2025-03-28 14:10:17): 401
✅ Загружено 401 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77881289
📅 Первая index_date: 2025-03-31 12:14:14, Последняя index_date: None
📌 Всего записей на странице: 357
📌 Примеры данных:
  - ID: 77881286, index_date: 2025-03-31 12:14:14
  - ID: 77881270, index_date: 2025-03-31 12:14:04
  - ID: 77881185, index_date: 2025-03-31 12:09:46
📌 Новых записей (index_date > 2025-03-28 14:10:17): 341
✅ Загружено 341 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77877957
📅 Первая index_date: 2025-03-31 12:11:05, Последняя index_date: 2025-03-31 12:06:20
📌 Всего записей на странице: 341
📌 Примеры данных:
  - ID: 77877956, index_date: 2025-03-31 12:11:05
  - ID: 77877950, index_date: 2025-02-28 17:41:14
  - ID: 77877943, index_date: 2025-03-31 12:09:07
📌 Новых записей (index_date > 2025-03-28 14:10:17): 314
✅ Загружено 314 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77874609
📅 Первая index_date: 2025-03-31 12:07:56, Последняя index_date: 2025-03-31 12:11:23
📌 Всего записей на странице: 399
📌 Примеры данных:
  - ID: 77874583, index_date: 2025-03-31 12:07:56
  - ID: 77874582, index_date: 2025-02-28 17:41:14
  - ID: 77874578, index_date: 2025-03-31 12:07:32
📌 Новых записей (index_date > 2025-03-28 14:10:17): 374
✅ Загружено 374 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77871160
📅 Первая index_date: 2025-03-31 12:12:50, Последняя index_date: 2025-03-31 12:10:22
📌 Всего записей на странице: 359
📌 Примеры данных:
  - ID: 77871156, index_date: 2025-03-31 12:12:50
  - ID: 77871075, index_date: 2025-03-31 12:14:05
  - ID: 77871070, index_date: 2025-03-31 12:11:06
📌 Новых записей (index_date > 2025-03-28 14:10:17): 340
✅ Загружено 340 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77867824
📅 Первая index_date: 2025-03-31 12:12:21, Последняя index_date: 2025-03-31 12:10:09
📌 Всего записей на странице: 375
📌 Примеры данных:
  - ID: 77867816, index_date: 2025-03-31 12:12:21
  - ID: 77867813, index_date: 2025-03-31 12:07:51
  - ID: 77867811, index_date: 2025-03-31 12:08:54
📌 Новых записей (index_date > 2025-03-28 14:10:17): 372
✅ Загружено 372 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77864488
📅 Первая index_date: 2025-03-31 12:12:13, Последняя index_date: None
📌 Всего записей на странице: 369
📌 Примеры данных:
  - ID: 77864486, index_date: 2025-03-31 12:12:13
  - ID: 77864484, index_date: 2025-03-31 12:13:17
  - ID: 77864474, index_date: 2025-03-31 12:07:56
📌 Новых записей (index_date > 2025-03-28 14:10:17): 365
✅ Загружено 365 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77861233
📅 Первая index_date: 2025-03-31 12:10:22, Последняя index_date: 2025-03-31 12:11:23
📌 Всего записей на странице: 432
📌 Примеры данных:
  - ID: 77861232, index_date: 2025-03-31 12:10:22
  - ID: 77861228, index_date: 2025-03-31 12:11:22
  - ID: 77861227, index_date: 2025-03-31 12:14:21
📌 Новых записей (index_date > 2025-03-28 14:10:17): 420
✅ Загружено 420 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77858885
📅 Первая index_date: 2025-03-31 12:08:05, Последняя index_date: 2025-03-31 12:07:56
📌 Всего записей на странице: 428
📌 Примеры данных:
  - ID: 77858884, index_date: 2025-03-31 12:08:05
  - ID: 77858882, index_date: 2025-03-31 12:12:21
  - ID: 77858881, index_date: 2025-03-31 12:11:21
📌 Новых записей (index_date > 2025-03-28 14:10:17): 421
✅ Загружено 421 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77856519
📅 Первая index_date: 2025-03-31 12:06:59, Последняя index_date: None
📌 Всего записей на странице: 405
📌 Примеры данных:
  - ID: 77856516, index_date: 2025-03-31 12:06:59
  - ID: 77856515, index_date: 2025-03-31 12:12:21
  - ID: 77856511, index_date: 2025-03-31 12:13:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 394
✅ Загружено 394 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77853891
📅 Первая index_date: 2025-03-31 12:13:04, Последняя index_date: 2025-03-31 12:13:25
📌 Всего записей на странице: 398
📌 Примеры данных:
  - ID: 77853890, index_date: 2025-03-31 12:13:04
  - ID: 77853881, index_date: 2025-03-31 12:08:07
  - ID: 77853874, index_date: 2025-03-31 12:11:06
📌 Новых записей (index_date > 2025-03-28 14:10:17): 387
✅ Загружено 387 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77851344
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:10:23
📌 Всего записей на странице: 417
📌 Примеры данных:
  - ID: 77851322, index_date: 2025-03-31 12:11:17
  - ID: 77851316, index_date: 2025-03-31 12:09:02
  - ID: 77851309, index_date: 2025-03-31 12:08:42
📌 Новых записей (index_date > 2025-03-28 14:10:17): 367
✅ Загружено 367 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77848696
📅 Первая index_date: 2025-03-31 12:13:13, Последняя index_date: 2025-03-31 17:43:42
📌 Всего записей на странице: 407
📌 Примеры данных:
  - ID: 77848680, index_date: 2025-03-31 12:13:13
  - ID: 77848672, index_date: 2025-03-31 12:09:02
  - ID: 77848664, index_date: 2025-03-31 12:12:13
📌 Новых записей (index_date > 2025-03-28 14:10:17): 404
✅ Загружено 404 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77845767
📅 Первая index_date: 2025-03-31 12:12:02, Последняя index_date: 2025-03-31 12:11:24
📌 Всего записей на странице: 419
📌 Примеры данных:
  - ID: 77845763, index_date: 2025-03-31 12:12:02
  - ID: 77845740, index_date: 2025-03-31 17:44:14
  - ID: 77845737, index_date: 2025-03-31 12:13:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 408
✅ Загружено 408 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77843429
📅 Первая index_date: 2025-03-31 17:43:55, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 395
📌 Примеры данных:
  - ID: 77843398, index_date: 2025-03-31 17:43:55
  - ID: 77843396, index_date: 2025-03-31 12:06:48
  - ID: 77843393, index_date: 2025-03-31 12:11:06
📌 Новых записей (index_date > 2025-03-28 14:10:17): 342
✅ Загружено 342 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77840898
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:11:52
📌 Всего записей на странице: 401
📌 Примеры данных:
  - ID: 77840889, index_date: 2025-02-28 17:41:14
  - ID: 77840888, index_date: 2025-03-31 12:09:17
  - ID: 77840881, index_date: 2025-03-31 12:11:24
📌 Новых записей (index_date > 2025-03-28 14:10:17): 394
✅ Загружено 394 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77837606
📅 Первая index_date: 2025-03-31 12:11:24, Последняя index_date: 2025-03-31 12:12:50
📌 Всего записей на странице: 348
📌 Примеры данных:
  - ID: 77837595, index_date: 2025-03-31 12:11:24
  - ID: 77837592, index_date: 2025-03-31 12:08:07
  - ID: 77837589, index_date: 2025-03-31 12:10:21
📌 Новых записей (index_date > 2025-03-28 14:10:17): 331
✅ Загружено 331 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77834567
📅 Первая index_date: 2025-03-31 12:07:32, Последняя index_date: 2025-03-31 12:09:12
📌 Всего записей на странице: 403
📌 Примеры данных:
  - ID: 77834563, index_date: 2025-03-31 12:07:32
  - ID: 77834559, index_date: 2025-03-31 12:13:19
  - ID: 77834556, index_date: 2025-03-31 12:06:59
📌 Новых записей (index_date > 2025-03-28 14:10:17): 391
✅ Загружено 391 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77831289
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:14:05
📌 Всего записей на странице: 358
📌 Примеры данных:
  - ID: 77831283, index_date: 2025-03-31 12:12:21
  - ID: 77831281, index_date: 2025-03-31 12:14:17
  - ID: 77831266, index_date: 2025-03-31 12:11:06
📌 Новых записей (index_date > 2025-03-28 14:10:17): 347
✅ Загружено 347 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77828140
📅 Первая index_date: None, Последняя index_date: None
📌 Всего записей на странице: 380
📌 Примеры данных:
  - ID: 77828133, index_date: 2025-03-31 12:06:51
  - ID: 77828131, index_date: 2025-03-31 19:01:34
  - ID: 77828129, index_date: 2025-03-31 12:13:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 358
✅ Загружено 358 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77824699
📅 Первая index_date: None, Последняя index_date: None
📌 Всего записей на странице: 336
📌 Примеры данных:
  - ID: 77824690, index_date: 2025-03-31 12:11:06
  - ID: 77824684, index_date: 2025-03-31 18:34:34
  - ID: 77824657, index_date: 2025-03-31 12:12:50
📌 Новых записей (index_date > 2025-03-28 14:10:17): 321
✅ Загружено 321 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77821709
📅 Первая index_date: 2025-03-31 17:44:15, Последняя index_date: 2025-03-31 12:14:05
📌 Всего записей на странице: 386
📌 Примеры данных:
  - ID: 77821707, index_date: 2025-03-31 17:44:15
  - ID: 77821704, index_date: 2025-02-28 17:41:14
  - ID: 77821703, index_date: 2025-03-31 14:45:34
📌 Новых записей (index_date > 2025-03-28 14:10:17): 373
✅ Загружено 373 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77818688
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:11:48
📌 Всего записей на странице: 395
📌 Примеры данных:
  - ID: 77818668, index_date: 2025-03-31 12:12:02
  - ID: 77818655, index_date: 2025-03-31 12:07:00
  - ID: 77818650, index_date: 2025-03-31 12:06:36
📌 Новых записей (index_date > 2025-03-28 14:10:17): 391
✅ Загружено 391 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77816025
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: None
📌 Всего записей на странице: 412
📌 Примеры данных:
  - ID: 77816022, index_date: 2025-02-28 17:41:14
  - ID: 77816014, index_date: 2025-03-31 12:11:16
  - ID: 77816005, index_date: 2025-03-31 12:07:32
📌 Новых записей (index_date > 2025-03-28 14:10:17): 384
✅ Загружено 384 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77813122
📅 Первая index_date: 2025-03-31 12:13:26, Последняя index_date: 2025-03-31 12:11:24
📌 Всего записей на странице: 359
📌 Примеры данных:
  - ID: 77813111, index_date: 2025-03-31 12:13:26
  - ID: 77813097, index_date: 2025-03-31 12:12:51
  - ID: 77813073, index_date: 2025-03-31 12:13:53
📌 Новых записей (index_date > 2025-03-28 14:10:17): 346
✅ Загружено 346 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77810098
📅 Первая index_date: 2025-03-31 12:11:06, Последняя index_date: 2025-03-31 12:08:04
📌 Всего записей на странице: 380
📌 Примеры данных:
  - ID: 77810093, index_date: 2025-03-31 12:11:06
  - ID: 77810091, index_date: 2025-03-31 17:43:50
  - ID: 77810090, index_date: 2025-03-31 12:07:32
📌 Новых записей (index_date > 2025-03-28 14:10:17): 364
✅ Загружено 364 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77807930
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:06:20
📌 Всего записей на странице: 380
📌 Примеры данных:
  - ID: 77807923, index_date: 2025-03-31 12:05:42
  - ID: 77807920, index_date: 2025-03-31 18:07:57
  - ID: 77807911, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 361
✅ Загружено 361 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77805086
📅 Первая index_date: 2025-03-31 12:11:13, Последняя index_date: 2025-03-31 12:12:02
📌 Всего записей на странице: 385
📌 Примеры данных:
  - ID: 77804948, index_date: 2025-03-31 12:11:13
  - ID: 77804943, index_date: 2025-03-31 12:12:21
  - ID: 77804828, index_date: 2025-03-31 12:12:21
📌 Новых записей (index_date > 2025-03-28 14:10:17): 370
✅ Загружено 370 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77802432
📅 Первая index_date: 2025-03-31 12:09:17, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 402
📌 Примеры данных:
  - ID: 77802429, index_date: 2025-03-31 12:09:17
  - ID: 77802426, index_date: 2025-03-31 12:11:06
  - ID: 77802423, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 370
✅ Загружено 370 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77799330
📅 Первая index_date: 2025-03-31 12:09:47, Последняя index_date: 2025-03-31 12:09:42
📌 Всего записей на странице: 396
📌 Примеры данных:
  - ID: 77799327, index_date: 2025-03-31 12:09:47
  - ID: 77799319, index_date: 2025-03-31 12:13:53
  - ID: 77799309, index_date: 2025-03-31 12:11:13
📌 Новых записей (index_date > 2025-03-28 14:10:17): 371
✅ Загружено 371 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77796827
📅 Первая index_date: 2025-03-31 12:07:32, Последняя index_date: 2025-03-31 12:09:47
📌 Всего записей на странице: 372
📌 Примеры данных:
  - ID: 77796821, index_date: 2025-03-31 12:07:32
  - ID: 77796818, index_date: 2025-03-31 12:06:06
  - ID: 77796802, index_date: 2025-03-31 12:07:00
📌 Новых записей (index_date > 2025-03-28 14:10:17): 342
✅ Загружено 342 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77793855
📅 Первая index_date: None, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 416
📌 Примеры данных:
  - ID: 77793843, index_date: 2025-03-31 12:13:13
  - ID: 77793837, index_date: 2025-03-31 12:09:12
  - ID: 77793832, index_date: 2025-03-31 12:09:43
📌 Новых записей (index_date > 2025-03-28 14:10:17): 392
✅ Загружено 392 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77790949
📅 Первая index_date: 2025-03-31 12:07:39, Последняя index_date: 2025-03-31 12:07:56
📌 Всего записей на странице: 403
📌 Примеры данных:
  - ID: 77790944, index_date: 2025-03-31 12:07:39
  - ID: 77790935, index_date: 2025-03-31 12:05:42
  - ID: 77790895, index_date: 2025-03-31 12:11:06
📌 Новых записей (index_date > 2025-03-28 14:10:17): 373
✅ Загружено 373 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77788259
📅 Первая index_date: 2025-03-31 12:07:00, Последняя index_date: None
📌 Всего записей на странице: 446
📌 Примеры данных:
  - ID: 77788258, index_date: 2025-03-31 12:07:00
  - ID: 77788256, index_date: 2025-03-31 12:07:00
  - ID: 77788255, index_date: 2025-03-31 12:08:07
📌 Новых записей (index_date > 2025-03-28 14:10:17): 374
✅ Загружено 374 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77786021
📅 Первая index_date: 2025-03-31 12:13:17, Последняя index_date: 2025-03-31 12:09:02
📌 Всего записей на странице: 414
📌 Примеры данных:
  - ID: 77786008, index_date: 2025-03-31 12:13:17
  - ID: 77785991, index_date: 2025-03-31 12:07:00
  - ID: 77785987, index_date: 2025-03-31 12:11:13
📌 Новых записей (index_date > 2025-03-28 14:10:17): 391
✅ Загружено 391 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77782826
📅 Первая index_date: 2025-03-31 12:09:07, Последняя index_date: 2025-03-31 12:09:47
📌 Всего записей на странице: 346
📌 Примеры данных:
  - ID: 77782820, index_date: 2025-03-31 12:09:07
  - ID: 77782810, index_date: 2025-03-31 12:13:26
  - ID: 77782797, index_date: 2025-03-31 12:11:17
📌 Новых записей (index_date > 2025-03-28 14:10:17): 294
✅ Загружено 294 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77778257
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:09:14
📌 Всего записей на странице: 353
📌 Примеры данных:
  - ID: 77778251, index_date: 2025-02-28 17:41:14
  - ID: 77778249, index_date: 2025-03-31 16:08:50
  - ID: 77778245, index_date: 2025-03-31 12:11:52
📌 Новых записей (index_date > 2025-03-28 14:10:17): 288
✅ Загружено 288 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77775654
📅 Первая index_date: 2025-03-31 12:09:07, Последняя index_date: 2025-03-31 12:07:32
📌 Всего записей на странице: 328
📌 Примеры данных:
  - ID: 77775652, index_date: 2025-03-31 12:09:07
  - ID: 77775642, index_date: 2025-03-31 12:11:59
  - ID: 77775634, index_date: 2025-03-31 12:08:43
📌 Новых записей (index_date > 2025-03-28 14:10:17): 292
✅ Загружено 292 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77772949
📅 Первая index_date: 2025-03-31 12:13:13, Последняя index_date: None
📌 Всего записей на странице: 342
📌 Примеры данных:
  - ID: 77772944, index_date: 2025-03-31 12:13:13
  - ID: 77772943, index_date: 2025-03-31 12:13:22
  - ID: 77772942, index_date: 2025-03-31 12:07:56
📌 Новых записей (index_date > 2025-03-28 14:10:17): 310
✅ Загружено 310 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77770201
📅 Первая index_date: None, Последняя index_date: None
📌 Всего записей на странице: 367
📌 Примеры данных:
  - ID: 77770192, index_date: 2025-03-31 12:06:20
  - ID: 77770191, index_date: 2025-03-31 12:08:43
  - ID: 77770180, index_date: 2025-03-31 12:13:53
📌 Новых записей (index_date > 2025-03-28 14:10:17): 344
✅ Загружено 344 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77767408
📅 Первая index_date: 2025-03-31 12:10:05, Последняя index_date: 2025-03-31 12:11:20
📌 Всего записей на странице: 335
📌 Примеры данных:
  - ID: 77767403, index_date: 2025-03-31 12:10:05
  - ID: 77767394, index_date: 2025-03-31 12:08:07
  - ID: 77767393, index_date: 2025-03-31 12:06:51
📌 Новых записей (index_date > 2025-03-28 14:10:17): 312
✅ Загружено 312 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77764766
📅 Первая index_date: 2025-03-31 12:08:07, Последняя index_date: 2025-03-31 17:54:59
📌 Всего записей на странице: 337
📌 Примеры данных:
  - ID: 77764764, index_date: 2025-03-31 12:08:07
  - ID: 77764741, index_date: 2025-02-28 17:41:14
  - ID: 77764727, index_date: 2025-03-31 12:05:42
📌 Новых записей (index_date > 2025-03-28 14:10:17): 277
✅ Загружено 277 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77762138
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:12:51
📌 Всего записей на странице: 323
📌 Примеры данных:
  - ID: 77762131, index_date: 2025-02-28 17:41:14
  - ID: 77762121, index_date: 2025-03-31 12:12:13
  - ID: 77762102, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 283
✅ Загружено 283 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77759343
📅 Первая index_date: 2025-03-31 12:12:09, Последняя index_date: 2025-03-31 12:09:17
📌 Всего записей на странице: 412
📌 Примеры данных:
  - ID: 77759338, index_date: 2025-03-31 12:12:09
  - ID: 77759333, index_date: 2025-03-31 12:07:33
  - ID: 77759331, index_date: 2025-03-31 12:11:52
📌 Новых записей (index_date > 2025-03-28 14:10:17): 391
✅ Загружено 391 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77757189
📅 Первая index_date: 2025-03-31 12:11:24, Последняя index_date: None
📌 Всего записей на странице: 414
📌 Примеры данных:
  - ID: 77757185, index_date: 2025-03-31 12:11:24
  - ID: 77757175, index_date: 2025-03-31 12:13:10
  - ID: 77757165, index_date: 2025-03-31 12:11:10
📌 Новых записей (index_date > 2025-03-28 14:10:17): 382
✅ Загружено 382 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77754753
📅 Первая index_date: 2025-03-31 12:13:16, Последняя index_date: 2025-03-31 12:07:00
📌 Всего записей на странице: 376
📌 Примеры данных:
  - ID: 77754751, index_date: 2025-03-31 12:13:16
  - ID: 77754713, index_date: 2025-03-31 12:05:42
  - ID: 77754710, index_date: 2025-03-31 12:08:55
📌 Новых записей (index_date > 2025-03-28 14:10:17): 354
✅ Загружено 354 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77752026
📅 Первая index_date: 2025-03-31 12:13:12, Последняя index_date: 2025-03-31 12:12:03
📌 Всего записей на странице: 392
📌 Примеры данных:
  - ID: 77752019, index_date: 2025-03-31 12:13:12
  - ID: 77752018, index_date: 2025-02-28 17:41:14
  - ID: 77752005, index_date: 2025-03-31 12:10:05
📌 Новых записей (index_date > 2025-03-28 14:10:17): 347
✅ Загружено 347 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77749490
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:10:55
📌 Всего записей на странице: 362
📌 Примеры данных:
  - ID: 77749477, index_date: 2025-03-31 12:11:52
  - ID: 77749468, index_date: 2025-03-31 12:12:03
  - ID: 77749450, index_date: 2025-03-31 12:12:17
📌 Новых записей (index_date > 2025-03-28 14:10:17): 346
✅ Загружено 346 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77747035
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:05:42
📌 Всего записей на странице: 319
📌 Примеры данных:
  - ID: 77747027, index_date: 2025-03-31 12:09:05
  - ID: 77747023, index_date: 2025-02-28 17:41:14
  - ID: 77747015, index_date: 2025-03-31 20:41:16
📌 Новых записей (index_date > 2025-03-28 14:10:17): 306
✅ Загружено 306 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77744724
📅 Первая index_date: 2025-03-31 12:11:13, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 346
📌 Примеры данных:
  - ID: 77744717, index_date: 2025-03-31 12:11:13
  - ID: 77744710, index_date: 2025-03-31 12:13:13
  - ID: 77744707, index_date: 2025-03-31 12:12:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 293
✅ Загружено 293 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77741813
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: 2025-03-31 12:09:51
📌 Всего записей на странице: 411
📌 Примеры данных:
  - ID: 77741812, index_date: 2025-02-28 17:41:14
  - ID: 77741811, index_date: 2025-02-28 17:41:14
  - ID: 77741810, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 300
✅ Загружено 300 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77739510
📅 Первая index_date: 2025-03-31 12:14:15, Последняя index_date: 2025-03-31 12:09:47
📌 Всего записей на странице: 388
📌 Примеры данных:
  - ID: 77739501, index_date: 2025-03-31 12:14:15
  - ID: 77739500, index_date: 2025-02-28 17:41:14
  - ID: 77739495, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 368
✅ Загружено 368 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77736535
📅 Первая index_date: 2025-03-31 12:09:43, Последняя index_date: 2025-03-31 12:10:05
📌 Всего записей на странице: 382
📌 Примеры данных:
  - ID: 77736513, index_date: 2025-03-31 12:09:43
  - ID: 77736506, index_date: 2025-03-31 12:12:09
  - ID: 77736499, index_date: 2025-03-31 12:13:01
📌 Новых записей (index_date > 2025-03-28 14:10:17): 355
✅ Загружено 355 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77733288
📅 Первая index_date: 2025-03-31 12:13:17, Последняя index_date: 2025-03-31 12:09:17
📌 Всего записей на странице: 369
📌 Примеры данных:
  - ID: 77733285, index_date: 2025-03-31 12:13:17
  - ID: 77733284, index_date: 2025-03-31 12:05:42
  - ID: 77733280, index_date: 2025-03-31 12:10:23
📌 Новых записей (index_date > 2025-03-28 14:10:17): 350
✅ Загружено 350 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77730650
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:12:46
📌 Всего записей на странице: 372
📌 Примеры данных:
  - ID: 77730644, index_date: 2025-03-31 17:44:34
  - ID: 77730640, index_date: 2025-03-31 12:10:55
  - ID: 77730637, index_date: 2025-03-31 12:09:17
📌 Новых записей (index_date > 2025-03-28 14:10:17): 340
✅ Загружено 340 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77728083
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:10:23
📌 Всего записей на странице: 416
📌 Примеры данных:
  - ID: 77728062, index_date: 2025-03-31 17:43:58
  - ID: 77728059, index_date: 2025-03-31 12:08:08
  - ID: 77728058, index_date: 2025-03-31 12:13:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 363
✅ Загружено 363 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77726076
📅 Первая index_date: None, Последняя index_date: None
📌 Всего записей на странице: 363
📌 Примеры данных:
  - ID: 77726058, index_date: 2025-03-31 12:12:12
  - ID: 77726054, index_date: 2025-03-31 12:11:24
  - ID: 77726046, index_date: 2025-03-31 12:12:12
📌 Новых записей (index_date > 2025-03-28 14:10:17): 336
✅ Загружено 336 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77723770
📅 Первая index_date: 2025-03-31 12:09:14, Последняя index_date: None
📌 Всего записей на странице: 376
📌 Примеры данных:
  - ID: 77723765, index_date: 2025-03-31 12:09:14
  - ID: 77723756, index_date: 2025-02-28 17:41:14
  - ID: 77723746, index_date: 2025-03-31 12:12:21
📌 Новых записей (index_date > 2025-03-28 14:10:17): 354
✅ Загружено 354 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77721243
📅 Первая index_date: 2025-03-31 12:09:03, Последняя index_date: None
📌 Всего записей на странице: 366
📌 Примеры данных:
  - ID: 77721242, index_date: 2025-03-31 12:09:03
  - ID: 77721241, index_date: 2025-03-31 12:12:51
  - ID: 77721240, index_date: 2025-03-31 12:12:51
📌 Новых записей (index_date > 2025-03-28 14:10:17): 325
✅ Загружено 325 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77718659
📅 Первая index_date: None, Последняя index_date: None
📌 Всего записей на странице: 365
📌 Примеры данных:
  - ID: 77718657, index_date: 2025-03-31 12:12:09
  - ID: 77718645, index_date: 2025-03-31 12:13:58
  - ID: 77718642, index_date: 2025-03-31 12:13:20
📌 Новых записей (index_date > 2025-03-28 14:10:17): 333
✅ Загружено 333 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77716323
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:09:17
📌 Всего записей на странице: 386
📌 Примеры данных:
  - ID: 77716313, index_date: 2025-03-31 12:10:23
  - ID: 77716305, index_date: 2025-03-31 12:11:52
  - ID: 77716303, index_date: 2025-03-31 12:12:51
📌 Новых записей (index_date > 2025-03-28 14:10:17): 368
✅ Загружено 368 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77713850
📅 Первая index_date: 2025-03-31 12:10:44, Последняя index_date: 2025-03-31 12:07:01
📌 Всего записей на странице: 315
📌 Примеры данных:
  - ID: 77713849, index_date: 2025-03-31 12:10:44
  - ID: 77713846, index_date: 2025-03-31 12:07:58
  - ID: 77713841, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 295
✅ Загружено 295 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77711928
📅 Первая index_date: None, Последняя index_date: None
📌 Всего записей на странице: 417
📌 Примеры данных:
  - ID: 77711920, index_date: 2025-03-31 19:01:33
  - ID: 77711919, index_date: 2025-03-31 12:14:05
  - ID: 77711908, index_date: 2025-03-31 12:07:50
📌 Новых записей (index_date > 2025-03-28 14:10:17): 368
✅ Загружено 368 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77709391
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: 2025-03-31 12:13:46
📌 Всего записей на странице: 375
📌 Примеры данных:
  - ID: 77709386, index_date: 2025-02-28 17:41:14
  - ID: 77709379, index_date: 2025-03-28 12:30:41
  - ID: 77709377, index_date: 2025-03-31 12:08:08
📌 Новых записей (index_date > 2025-03-28 14:10:17): 343
✅ Загружено 343 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77706565
📅 Первая index_date: None, Последняя index_date: 2025-03-31 17:44:13
📌 Всего записей на странице: 344
📌 Примеры данных:
  - ID: 77706527, index_date: 2025-03-31 12:11:52
  - ID: 77706514, index_date: 2025-03-31 12:09:00
  - ID: 77706488, index_date: 2025-03-31 14:40:18
📌 Новых записей (index_date > 2025-03-28 14:10:17): 320
✅ Загружено 320 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77703982
📅 Первая index_date: None, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 347
📌 Примеры данных:
  - ID: 77703968, index_date: 2025-03-31 19:21:11
  - ID: 77703967, index_date: 2025-03-31 12:08:08
  - ID: 77703965, index_date: 2025-03-31 12:12:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 316
✅ Загружено 316 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77701328
📅 Первая index_date: 2025-03-31 12:09:00, Последняя index_date: 2025-03-31 12:11:24
📌 Всего записей на странице: 436
📌 Примеры данных:
  - ID: 77701298, index_date: 2025-03-31 12:09:00
  - ID: 77701283, index_date: 2025-03-31 12:07:33
  - ID: 77701270, index_date: 2025-03-31 13:06:40
📌 Новых записей (index_date > 2025-03-28 14:10:17): 364
✅ Загружено 364 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77697901
📅 Первая index_date: 2025-03-31 12:07:01, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 324
📌 Примеры данных:
  - ID: 77697899, index_date: 2025-03-31 12:07:01
  - ID: 77697891, index_date: 2025-03-31 12:11:24
  - ID: 77697888, index_date: 2025-03-31 12:09:17
📌 Новых записей (index_date > 2025-03-28 14:10:17): 274
✅ Загружено 274 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77695440
📅 Первая index_date: 2025-03-31 12:07:50, Последняя index_date: 2025-03-31 12:11:24
📌 Всего записей на странице: 402
📌 Примеры данных:
  - ID: 77695437, index_date: 2025-03-31 12:07:50
  - ID: 77695433, index_date: 2025-02-28 17:41:14
  - ID: 77695431, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 315
✅ Загружено 315 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77692561
📅 Первая index_date: 2025-03-18 14:59:20, Последняя index_date: 2025-03-31 12:05:43
📌 Всего записей на странице: 403
📌 Примеры данных:
  - ID: 77692560, index_date: 2025-03-18 14:59:20
  - ID: 77692548, index_date: 2025-03-18 14:59:20
  - ID: 77692545, index_date: 2025-03-31 12:11:11
📌 Новых записей (index_date > 2025-03-28 14:10:17): 370
✅ Загружено 370 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77690616
📅 Первая index_date: 2025-03-31 12:09:47, Последняя index_date: 2025-03-31 12:07:55
📌 Всего записей на странице: 377
📌 Примеры данных:
  - ID: 77690613, index_date: 2025-03-31 12:09:47
  - ID: 77690609, index_date: 2025-03-31 12:12:00
  - ID: 77690599, index_date: 2025-03-31 12:08:41
📌 Новых записей (index_date > 2025-03-28 14:10:17): 354
✅ Загружено 354 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77688175
📅 Первая index_date: 2025-03-31 12:09:02, Последняя index_date: None
📌 Всего записей на странице: 368
📌 Примеры данных:
  - ID: 77688172, index_date: 2025-03-31 12:09:02
  - ID: 77688171, index_date: 2025-03-31 12:09:07
  - ID: 77688164, index_date: 2025-03-31 12:10:23
📌 Новых записей (index_date > 2025-03-28 14:10:17): 337
✅ Загружено 337 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77685348
📅 Первая index_date: 2025-03-31 17:44:15, Последняя index_date: None
📌 Всего записей на странице: 375
📌 Примеры данных:
  - ID: 77685346, index_date: 2025-03-31 17:44:15
  - ID: 77685338, index_date: 2025-03-31 12:10:24
  - ID: 77685331, index_date: 2025-03-31 12:11:52
📌 Новых записей (index_date > 2025-03-28 14:10:17): 344
✅ Загружено 344 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77682833
📅 Первая index_date: 2025-03-31 12:13:02, Последняя index_date: 2025-03-31 12:08:38
📌 Всего записей на странице: 404
📌 Примеры данных:
  - ID: 77682829, index_date: 2025-03-31 12:13:02
  - ID: 77682825, index_date: 2025-03-31 12:10:55
  - ID: 77682823, index_date: 2025-03-31 12:07:51
📌 Новых записей (index_date > 2025-03-28 14:10:17): 390
✅ Загружено 390 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77681002
📅 Первая index_date: 2025-03-31 12:08:43, Последняя index_date: 2025-03-31 12:13:19
📌 Всего записей на странице: 404
📌 Примеры данных:
  - ID: 77680999, index_date: 2025-03-31 12:08:43
  - ID: 77680996, index_date: 2025-03-31 12:10:04
  - ID: 77680995, index_date: 2025-03-31 12:06:45
📌 Новых записей (index_date > 2025-03-28 14:10:17): 380
✅ Загружено 380 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77678807
📅 Первая index_date: 2025-03-31 12:06:46, Последняя index_date: 2025-03-31 12:11:24
📌 Всего записей на странице: 389
📌 Примеры данных:
  - ID: 77678801, index_date: 2025-03-31 12:06:46
  - ID: 77678797, index_date: 2025-03-31 12:11:14
  - ID: 77678731, index_date: 2025-03-31 12:06:45
📌 Новых записей (index_date > 2025-03-28 14:10:17): 343
✅ Загружено 343 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77676040
📅 Первая index_date: 2025-03-31 12:07:33, Последняя index_date: 2025-03-31 12:09:57
📌 Всего записей на странице: 420
📌 Примеры данных:
  - ID: 77676039, index_date: 2025-03-31 12:07:33
  - ID: 77676037, index_date: 2025-03-31 12:14:19
  - ID: 77676032, index_date: 2025-03-31 12:08:39
📌 Новых записей (index_date > 2025-03-28 14:10:17): 388
✅ Загружено 388 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77673810
📅 Первая index_date: 2025-03-31 12:08:55, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 410
📌 Примеры данных:
  - ID: 77673809, index_date: 2025-03-31 12:08:55
  - ID: 77673808, index_date: 2025-03-31 12:12:03
  - ID: 77673802, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 362
✅ Загружено 362 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77670725
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: None
📌 Всего записей на странице: 452
📌 Примеры данных:
  - ID: 77670724, index_date: 2025-02-28 17:41:14
  - ID: 77670723, index_date: 2025-02-28 17:41:14
  - ID: 77670720, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 386
✅ Загружено 386 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77668589
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: 2025-03-31 12:07:01
📌 Всего записей на странице: 442
📌 Примеры данных:
  - ID: 77668582, index_date: 2025-02-28 17:41:14
  - ID: 77668578, index_date: 2025-03-31 12:07:02
  - ID: 77668576, index_date: 2025-03-31 12:13:16
📌 Новых записей (index_date > 2025-03-28 14:10:17): 389
✅ Загружено 389 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77666074
📅 Первая index_date: 2025-03-31 17:44:13, Последняя index_date: 2025-03-31 12:05:43
📌 Всего записей на странице: 454
📌 Примеры данных:
  - ID: 77666072, index_date: 2025-03-31 17:44:13
  - ID: 77666058, index_date: 2025-03-31 12:06:14
  - ID: 77666053, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 397
✅ Загружено 397 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77663741
📅 Первая index_date: 2025-03-31 12:12:09, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 410
📌 Примеры данных:
  - ID: 77663738, index_date: 2025-03-31 12:12:09
  - ID: 77663736, index_date: 2025-03-31 12:10:55
  - ID: 77663734, index_date: 2025-03-31 12:13:02
📌 Новых записей (index_date > 2025-03-28 14:10:17): 350
✅ Загружено 350 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77661305
📅 Первая index_date: 2025-03-31 18:31:16, Последняя index_date: 2025-03-31 12:14:13
📌 Всего записей на странице: 395
📌 Примеры данных:
  - ID: 77661303, index_date: 2025-03-31 18:31:16
  - ID: 77661297, index_date: 2025-03-31 12:14:05
  - ID: 77661296, index_date: 2025-03-31 12:05:43
📌 Новых записей (index_date > 2025-03-28 14:10:17): 343
✅ Загружено 343 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77659070
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:07:55
📌 Всего записей на странице: 394
📌 Примеры данных:
  - ID: 77659054, index_date: 2025-03-31 12:14:20
  - ID: 77659046, index_date: 2025-03-28 11:13:41
  - ID: 77659036, index_date: 2025-03-31 12:09:43
📌 Новых записей (index_date > 2025-03-28 14:10:17): 358
✅ Загружено 358 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77656280
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:30:06
📌 Всего записей на странице: 382
📌 Примеры данных:
  - ID: 77656267, index_date: 2025-03-31 12:07:30
  - ID: 77656261, index_date: 2025-03-31 12:10:08
  - ID: 77656244, index_date: 2025-03-31 12:09:15
📌 Новых записей (index_date > 2025-03-28 14:10:17): 342
✅ Загружено 342 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77653703
📅 Первая index_date: 2025-03-31 12:08:53, Последняя index_date: 2025-03-31 12:07:01
📌 Всего записей на странице: 410
📌 Примеры данных:
  - ID: 77653696, index_date: 2025-03-31 12:08:53
  - ID: 77653694, index_date: 2025-03-31 12:14:19
  - ID: 77653691, index_date: 2025-03-31 12:10:23
📌 Новых записей (index_date > 2025-03-28 14:10:17): 367
✅ Загружено 367 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77651021
📅 Первая index_date: 2025-03-31 12:11:19, Последняя index_date: 2025-03-31 17:44:17
📌 Всего записей на странице: 384
📌 Примеры данных:
  - ID: 77651013, index_date: 2025-03-31 12:11:19
  - ID: 77651009, index_date: 2025-03-31 12:10:55
  - ID: 77651004, index_date: 2025-03-31 12:09:43
📌 Новых записей (index_date > 2025-03-28 14:10:17): 319
✅ Загружено 319 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77647464
📅 Первая index_date: 2025-03-31 12:07:55, Последняя index_date: 2025-03-31 12:07:29
📌 Всего записей на странице: 405
📌 Примеры данных:
  - ID: 77647454, index_date: 2025-03-31 12:07:55
  - ID: 77647452, index_date: 2025-03-19 17:11:57
  - ID: 77647450, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 326
✅ Загружено 326 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77643996
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:14:14
📌 Всего записей на странице: 464
📌 Примеры данных:
  - ID: 77643993, index_date: 2025-03-31 12:07:02
  - ID: 77643989, index_date: 2025-03-31 12:14:13
  - ID: 77643986, index_date: 2025-03-31 12:11:03
📌 Новых записей (index_date > 2025-03-28 14:10:17): 286
✅ Загружено 286 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77640908
📅 Первая index_date: 2025-03-31 12:10:05, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 407
📌 Примеры данных:
  - ID: 77640903, index_date: 2025-03-31 12:10:05
  - ID: 77640899, index_date: 2025-03-31 12:06:45
  - ID: 77640898, index_date: 2025-03-31 12:13:26
📌 Новых записей (index_date > 2025-03-28 14:10:17): 324
✅ Загружено 324 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77638112
📅 Первая index_date: 2025-03-31 12:09:05, Последняя index_date: 2025-03-31 12:08:08
📌 Всего записей на странице: 408
📌 Примеры данных:
  - ID: 77638108, index_date: 2025-03-31 12:09:05
  - ID: 77638106, index_date: 2025-03-31 18:16:14
  - ID: 77638102, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 315
✅ Загружено 315 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77635514
📅 Первая index_date: 2025-03-31 12:05:43, Последняя index_date: 2025-03-31 17:44:02
📌 Всего записей на странице: 394
📌 Примеры данных:
  - ID: 77635512, index_date: 2025-03-31 12:05:43
  - ID: 77635504, index_date: 2025-03-31 18:29:04
  - ID: 77635502, index_date: 2025-03-31 12:14:17
📌 Новых записей (index_date > 2025-03-28 14:10:17): 334
✅ Загружено 334 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77632861
📅 Первая index_date: 2025-03-31 12:11:17, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 383
📌 Примеры данных:
  - ID: 77632847, index_date: 2025-03-31 12:11:17
  - ID: 77632837, index_date: 2025-03-31 12:06:23
  - ID: 77632824, index_date: 2025-03-06T19:59:07.005
📌 Новых записей (index_date > 2025-03-28 14:10:17): 323
✅ Загружено 323 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77630575
📅 Первая index_date: 2025-03-17 02:23:50, Последняя index_date: 2025-03-31 12:12:17
📌 Всего записей на странице: 402
📌 Примеры данных:
  - ID: 77630569, index_date: 2025-03-17 02:23:50
  - ID: 77630563, index_date: 2025-02-28 17:41:14
  - ID: 77630549, index_date: 2025-03-31 12:13:53
📌 Новых записей (index_date > 2025-03-28 14:10:17): 348
✅ Загружено 348 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77627906
📅 Первая index_date: 2025-03-31 12:10:24, Последняя index_date: 2025-03-31 12:07:46
📌 Всего записей на странице: 370
📌 Примеры данных:
  - ID: 77627903, index_date: 2025-03-31 12:10:24
  - ID: 77627898, index_date: 2025-03-31 12:09:00
  - ID: 77627895, index_date: 2025-03-31 12:06:23
📌 Новых записей (index_date > 2025-03-28 14:10:17): 309
✅ Загружено 309 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77625197
📅 Первая index_date: 2025-03-31 12:12:08, Последняя index_date: None
📌 Всего записей на странице: 357
📌 Примеры данных:
  - ID: 77625194, index_date: 2025-03-31 12:12:08
  - ID: 77625193, index_date: 2025-03-31 12:08:08
  - ID: 77625191, index_date: 2025-03-31 12:08:08
📌 Новых записей (index_date > 2025-03-28 14:10:17): 315
✅ Загружено 315 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77622455
📅 Первая index_date: 2025-03-31 13:15:57, Последняя index_date: None
📌 Всего записей на странице: 388
📌 Примеры данных:
  - ID: 77622451, index_date: 2025-03-31 13:15:57
  - ID: 77622450, index_date: 2025-03-31 12:07:51
  - ID: 77622440, index_date: 2025-03-31 12:13:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 312
✅ Загружено 312 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77620258
📅 Первая index_date: 2025-03-31 12:14:04, Последняя index_date: 2025-03-31 12:10:24
📌 Всего записей на странице: 432
📌 Примеры данных:
  - ID: 77620255, index_date: 2025-03-31 12:14:04
  - ID: 77620251, index_date: 2025-03-31 09:28:49
  - ID: 77620244, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 375
✅ Загружено 375 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77618351
📅 Первая index_date: 2025-03-31 12:09:37, Последняя index_date: 2025-03-31 12:08:28
📌 Всего записей на странице: 436
📌 Примеры данных:
  - ID: 77618343, index_date: 2025-03-31 12:09:37
  - ID: 77618342, index_date: 2025-03-31 12:06:15
  - ID: 77618340, index_date: 2025-03-31 17:44:18
📌 Новых записей (index_date > 2025-03-28 14:10:17): 397
✅ Загружено 397 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77616344
📅 Первая index_date: 2025-03-31 12:08:28, Последняя index_date: None
📌 Всего записей на странице: 393
📌 Примеры данных:
  - ID: 77616336, index_date: 2025-03-31 12:08:28
  - ID: 77616334, index_date: 2025-03-31 12:09:47
  - ID: 77616331, index_date: 2025-03-31 12:07:33
📌 Новых записей (index_date > 2025-03-28 14:10:17): 339
✅ Загружено 339 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77613742
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:11:24
📌 Всего записей на странице: 365
📌 Примеры данных:
  - ID: 77613736, index_date: 2025-03-31 12:07:46
  - ID: 77613710, index_date: 2025-03-31 12:13:12
  - ID: 77613704, index_date: 2025-03-31 12:06:37
📌 Новых записей (index_date > 2025-03-28 14:10:17): 299
✅ Загружено 299 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77610852
📅 Первая index_date: 2025-03-31 12:13:50, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 399
📌 Примеры данных:
  - ID: 77610849, index_date: 2025-03-31 12:13:50
  - ID: 77610848, index_date: 2025-02-28 17:41:14
  - ID: 77610846, index_date: 2025-03-31 12:14:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 370
✅ Загружено 370 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77608600
📅 Первая index_date: 2025-03-31 12:11:17, Последняя index_date: None
📌 Всего записей на странице: 463
📌 Примеры данных:
  - ID: 77608598, index_date: 2025-03-31 12:11:17
  - ID: 77608597, index_date: 2025-03-31 12:09:00
  - ID: 77608594, index_date: 2025-03-31 12:13:50
📌 Новых записей (index_date > 2025-03-28 14:10:17): 396
✅ Загружено 396 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77606936
📅 Первая index_date: 2025-03-31 12:10:24, Последняя index_date: 2025-03-31 19:01:29
📌 Всего записей на странице: 409
📌 Примеры данных:
  - ID: 77606935, index_date: 2025-03-31 12:10:24
  - ID: 77606933, index_date: 2025-02-28 17:41:14
  - ID: 77606928, index_date: 2025-03-31 12:10:20
📌 Новых записей (index_date > 2025-03-28 14:10:17): 279
✅ Загружено 279 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77605066
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:06:58
📌 Всего записей на странице: 433
📌 Примеры данных:
  - ID: 77605063, index_date: 2025-03-31 12:08:08
  - ID: 77605051, index_date: 2025-03-31 12:06:58
  - ID: 77605043, index_date: 2025-03-31 12:12:03
📌 Новых записей (index_date > 2025-03-28 14:10:17): 380
✅ Загружено 380 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77602757
📅 Первая index_date: 2025-03-31 12:13:04, Последняя index_date: 2025-03-31 12:12:14
📌 Всего записей на странице: 405
📌 Примеры данных:
  - ID: 77602745, index_date: 2025-03-31 12:13:04
  - ID: 77602743, index_date: 2025-03-31 12:14:14
  - ID: 77602740, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 337
✅ Загружено 337 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77600065
📅 Первая index_date: 2025-03-31 12:14:17, Последняя index_date: 2025-03-31 12:11:19
📌 Всего записей на странице: 401
📌 Примеры данных:
  - ID: 77600046, index_date: 2025-03-31 12:14:17
  - ID: 77600043, index_date: 2025-03-31 12:12:49
  - ID: 77600040, index_date: 2025-03-31 12:09:08
📌 Новых записей (index_date > 2025-03-28 14:10:17): 325
✅ Загружено 325 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77597150
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:16:10
📌 Всего записей на странице: 358
📌 Примеры данных:
  - ID: 77597139, index_date: 2025-03-31 12:08:03
  - ID: 77597138, index_date: 2025-03-31 17:44:22
  - ID: 77597137, index_date: 2025-03-31 12:11:52
📌 Новых записей (index_date > 2025-03-28 14:10:17): 302
✅ Загружено 302 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77594564
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: 2025-03-31 12:12:01
📌 Всего записей на странице: 426
📌 Примеры данных:
  - ID: 77594557, index_date: 2025-02-28 17:41:14
  - ID: 77594552, index_date: 2025-03-31 12:09:57
  - ID: 77594549, index_date: 2025-03-31 12:07:50
📌 Новых записей (index_date > 2025-03-28 14:10:17): 355
✅ Загружено 355 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77591850
📅 Первая index_date: 2025-03-31 12:09:05, Последняя index_date: None
📌 Всего записей на странице: 389
📌 Примеры данных:
  - ID: 77591847, index_date: 2025-03-31 12:09:05
  - ID: 77591837, index_date: 2025-03-31 12:14:20
  - ID: 77591832, index_date: 2025-03-31 12:10:55
📌 Новых записей (index_date > 2025-03-28 14:10:17): 319
✅ Загружено 319 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77589495
📅 Первая index_date: 2025-03-31 12:11:20, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 378
📌 Примеры данных:
  - ID: 77589489, index_date: 2025-03-31 12:11:20
  - ID: 77589485, index_date: 2025-03-31 12:12:52
  - ID: 77589484, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 327
✅ Загружено 327 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77587362
📅 Первая index_date: 2025-03-31 12:11:05, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 416
📌 Примеры данных:
  - ID: 77587360, index_date: 2025-03-31 12:11:05
  - ID: 77587354, index_date: 2025-03-31 12:13:26
  - ID: 77587349, index_date: 2025-03-31 12:12:19
📌 Новых записей (index_date > 2025-03-28 14:10:17): 314
✅ Загружено 314 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77585190
📅 Первая index_date: 2025-03-31 12:11:52, Последняя index_date: 2025-03-31 12:10:09
📌 Всего записей на странице: 439
📌 Примеры данных:
  - ID: 77585189, index_date: 2025-03-31 12:11:52
  - ID: 77585187, index_date: 2025-03-31 12:12:48
  - ID: 77585181, index_date: 2025-03-31 12:09:44
📌 Новых записей (index_date > 2025-03-28 14:10:17): 375
✅ Загружено 375 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77583059
📅 Первая index_date: 2025-03-31 12:11:25, Последняя index_date: 2025-03-31 12:14:17
📌 Всего записей на странице: 444
📌 Примеры данных:
  - ID: 77583054, index_date: 2025-03-31 12:11:25
  - ID: 77583048, index_date: 2025-03-31 12:08:50
  - ID: 77583043, index_date: 2025-03-31 12:11:05
📌 Новых записей (index_date > 2025-03-28 14:10:17): 393
✅ Загружено 393 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77580740
📅 Первая index_date: 2025-03-31 12:10:55, Последняя index_date: None
📌 Всего записей на странице: 442
📌 Примеры данных:
  - ID: 77580734, index_date: 2025-03-31 12:10:55
  - ID: 77580731, index_date: 2025-03-31 12:09:42
  - ID: 77580728, index_date: 2025-03-31 17:44:33
📌 Новых записей (index_date > 2025-03-28 14:10:17): 384
✅ Загружено 384 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77578151
📅 Первая index_date: 2025-03-31 12:12:46, Последняя index_date: 2025-03-31 12:07:56
📌 Всего записей на странице: 405
📌 Примеры данных:
  - ID: 77578135, index_date: 2025-03-31 12:12:46
  - ID: 77578125, index_date: 2025-03-31 12:12:09
  - ID: 77578115, index_date: 2025-03-31 12:12:46
📌 Новых записей (index_date > 2025-03-28 14:10:17): 345
✅ Загружено 345 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77574783
📅 Первая index_date: 2025-03-31 12:08:39, Последняя index_date: 2025-03-31 12:06:45
📌 Всего записей на странице: 425
📌 Примеры данных:
  - ID: 77574780, index_date: 2025-03-31 12:08:39
  - ID: 77574777, index_date: 2025-02-28 17:41:14
  - ID: 77574766, index_date: 2025-03-31 12:14:03
📌 Новых записей (index_date > 2025-03-28 14:10:17): 325
✅ Загружено 325 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77572272
📅 Первая index_date: 2025-03-31 12:07:50, Последняя index_date: 2025-03-31 12:11:16
📌 Всего записей на странице: 424
📌 Примеры данных:
  - ID: 77572252, index_date: 2025-03-31 12:07:50
  - ID: 77572250, index_date: 2025-03-31 12:08:43
  - ID: 77572233, index_date: 2025-03-31 12:09:02
📌 Новых записей (index_date > 2025-03-28 14:10:17): 322
✅ Загружено 322 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77569459
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:07:29
📌 Всего записей на странице: 409
📌 Примеры данных:
  - ID: 77569457, index_date: 2025-03-31 12:09:43
  - ID: 77569454, index_date: 2025-03-31 12:13:04
  - ID: 77569445, index_date: 2025-03-31 12:12:18
📌 Новых записей (index_date > 2025-03-28 14:10:17): 337
✅ Загружено 337 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77567370
📅 Первая index_date: 2025-03-31 12:11:49, Последняя index_date: 2025-03-31 12:12:45
📌 Всего записей на странице: 460
📌 Примеры данных:
  - ID: 77567364, index_date: 2025-03-31 12:11:49
  - ID: 77567362, index_date: 2025-03-31 12:09:48
  - ID: 77567361, index_date: 2025-03-31 12:09:18
📌 Новых записей (index_date > 2025-03-28 14:10:17): 228
✅ Загружено 228 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77566005
📅 Первая index_date: 2025-03-31 12:13:19, Последняя index_date: 2025-03-31 12:07:29
📌 Всего записей на странице: 418
📌 Примеры данных:
  - ID: 77566001, index_date: 2025-03-31 12:13:19
  - ID: 77565997, index_date: 2025-03-31 12:08:53
  - ID: 77565996, index_date: 2025-03-31 12:09:18
📌 Новых записей (index_date > 2025-03-28 14:10:17): 323
✅ Загружено 323 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77563931
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: 2025-03-31 12:06:56
📌 Всего записей на странице: 434
📌 Примеры данных:
  - ID: 77563927, index_date: 2025-02-28 17:41:14
  - ID: 77563926, index_date: 2025-03-31 12:06:17
  - ID: 77563921, index_date: 2025-03-31 12:13:15
📌 Новых записей (index_date > 2025-03-28 14:10:17): 357
✅ Загружено 357 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77561815
📅 Первая index_date: 2025-03-31 12:06:14, Последняя index_date: 2025-03-31 12:08:43
📌 Всего записей на странице: 431
📌 Примеры данных:
  - ID: 77561814, index_date: 2025-03-31 12:06:14
  - ID: 77561809, index_date: 2025-02-28 17:41:14
  - ID: 77561803, index_date: 2025-03-31 12:13:22
📌 Новых записей (index_date > 2025-03-28 14:10:17): 376
✅ Загружено 376 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77559707
📅 Первая index_date: 2025-03-31 12:11:04, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 436
📌 Примеры данных:
  - ID: 77559703, index_date: 2025-03-31 12:11:04
  - ID: 77559701, index_date: 2025-03-31 12:11:25
  - ID: 77559699, index_date: 2025-03-31 12:06:43
📌 Новых записей (index_date > 2025-03-28 14:10:17): 377
✅ Загружено 377 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77557290
📅 Первая index_date: 2025-03-31 12:13:17, Последняя index_date: 2025-03-31 12:06:58
📌 Всего записей на странице: 435
📌 Примеры данных:
  - ID: 77557289, index_date: 2025-03-31 12:13:17
  - ID: 77557287, index_date: 2025-03-31 12:12:22
  - ID: 77557283, index_date: 2025-03-31 12:06:37
📌 Новых записей (index_date > 2025-03-28 14:10:17): 365
✅ Загружено 365 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77555035
📅 Первая index_date: 2025-03-31 12:09:33, Последняя index_date: 2025-03-31 12:10:55
📌 Всего записей на странице: 449
📌 Примеры данных:
  - ID: 77555034, index_date: 2025-03-31 12:09:33
  - ID: 77555032, index_date: 2025-03-31 12:07:57
  - ID: 77555026, index_date: 2025-03-31 12:10:52
📌 Новых записей (index_date > 2025-03-28 14:10:17): 359
✅ Загружено 359 новых записей с этой страницы...
❌ Ошибка запроса: HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⏳ Ждём 30 сек и пробуем снова...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77552862
📅 Первая index_date: 2025-03-19 05:33:49, Последняя index_date: 2025-03-31 14:14:16
📌 Всего записей на странице: 414
📌 Примеры данных:
  - ID: 77552854, index_date: 2025-03-19 05:33:49
  - ID: 77552853, index_date: 2025-03-31 12:06:47
  - ID: 77552851, index_date: 2025-03-31 12:13:49
📌 Новых записей (index_date > 2025-03-28 14:10:17): 309
✅ Загружено 309 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77550909
📅 Первая index_date: 2025-03-31 12:09:56, Последняя index_date: 2025-03-31 12:12:03
📌 Всего записей на странице: 419
📌 Примеры данных:
  - ID: 77550905, index_date: 2025-03-31 12:09:56
  - ID: 77550896, index_date: 2025-03-31 12:09:29
  - ID: 77550889, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 350
✅ Загружено 350 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77548871
📅 Первая index_date: 2025-03-31 12:14:20, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 449
📌 Примеры данных:
  - ID: 77548867, index_date: 2025-03-31 12:14:20
  - ID: 77548863, index_date: 2025-03-31 12:11:14
  - ID: 77548848, index_date: 2025-03-31 12:08:09
📌 Новых записей (index_date > 2025-03-28 14:10:17): 306
✅ Загружено 306 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77546204
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: None
📌 Всего записей на странице: 414
📌 Примеры данных:
  - ID: 77546196, index_date: 2025-02-28 17:41:14
  - ID: 77546193, index_date: 2025-03-31 12:06:33
  - ID: 77546190, index_date: 2025-03-31 12:08:04
📌 Новых записей (index_date > 2025-03-28 14:10:17): 313
✅ Загружено 313 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77543726
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:14:21
📌 Всего записей на странице: 404
📌 Примеры данных:
  - ID: 77543724, index_date: 2025-03-31 12:14:05
  - ID: 77543721, index_date: 2025-02-28 17:41:14
  - ID: 77543719, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 289
✅ Загружено 289 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77541358
📅 Первая index_date: 2025-03-31 12:07:29, Последняя index_date: 2025-03-31 12:14:15
📌 Всего записей на странице: 419
📌 Примеры данных:
  - ID: 77541348, index_date: 2025-03-31 12:07:29
  - ID: 77541344, index_date: 2025-03-18 11:18:44
  - ID: 77541342, index_date: 2025-03-31 17:43:55
📌 Новых записей (index_date > 2025-03-28 14:10:17): 348
✅ Загружено 348 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77537595
📅 Первая index_date: 2025-03-31 12:07:54, Последняя index_date: 2025-03-31 12:12:01
📌 Всего записей на странице: 355
📌 Примеры данных:
  - ID: 77537588, index_date: 2025-03-31 12:07:54
  - ID: 77537585, index_date: 2025-03-31 12:07:46
  - ID: 77537583, index_date: 2025-03-31 12:08:43
📌 Новых записей (index_date > 2025-03-28 14:10:17): 266
✅ Загружено 266 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77535305
📅 Первая index_date: 2025-03-31 12:11:11, Последняя index_date: 2025-03-31 12:10:24
📌 Всего записей на странице: 423
📌 Примеры данных:
  - ID: 77535295, index_date: 2025-03-31 12:11:11
  - ID: 77535270, index_date: 2025-03-31 12:09:47
  - ID: 77535266, index_date: 2025-03-31 12:13:16
📌 Новых записей (index_date > 2025-03-28 14:10:17): 304
✅ Загружено 304 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77531957
📅 Первая index_date: 2025-03-27 16:41:27, Последняя index_date: None
📌 Всего записей на странице: 379
📌 Примеры данных:
  - ID: 77531948, index_date: 2025-03-27 16:41:27
  - ID: 77531939, index_date: 2025-02-28 17:41:14
  - ID: 77531921, index_date: 2025-03-27 16:41:27
📌 Новых записей (index_date > 2025-03-28 14:10:17): 309
✅ Загружено 309 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77527969
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:06:23
📌 Всего записей на странице: 401
📌 Примеры данных:
  - ID: 77527845, index_date: 2025-03-31 12:12:22
  - ID: 77527844, index_date: 2025-03-31 12:11:47
  - ID: 77527823, index_date: 2025-03-31 12:13:39
📌 Новых записей (index_date > 2025-03-28 14:10:17): 320
✅ Загружено 320 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77525636
📅 Первая index_date: 2025-03-31 12:10:20, Последняя index_date: 2025-03-31 12:14:05
📌 Всего записей на странице: 446
📌 Примеры данных:
  - ID: 77525635, index_date: 2025-03-31 12:10:20
  - ID: 77525627, index_date: 2025-03-31 12:09:14
  - ID: 77525623, index_date: 2025-03-31 12:09:05
📌 Новых записей (index_date > 2025-03-28 14:10:17): 344
✅ Загружено 344 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77523443
📅 Первая index_date: 2025-03-31 12:08:55, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 429
📌 Примеры данных:
  - ID: 77523439, index_date: 2025-03-31 12:08:55
  - ID: 77523435, index_date: 2025-02-28 17:41:14
  - ID: 77523433, index_date: 2025-03-31 12:10:24
📌 Новых записей (index_date > 2025-03-28 14:10:17): 312
✅ Загружено 312 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77520809
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: 2025-03-31 12:07:55
📌 Всего записей на странице: 406
📌 Примеры данных:
  - ID: 77520805, index_date: 2025-02-28 17:41:14
  - ID: 77520801, index_date: 2025-03-31 12:07:33
  - ID: 77520799, index_date: 2025-03-31 12:14:20
📌 Новых записей (index_date > 2025-03-28 14:10:17): 313
✅ Загружено 313 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77518527
📅 Первая index_date: 2025-03-31 12:07:33, Последняя index_date: 2025-03-31 12:12:03
📌 Всего записей на странице: 412
📌 Примеры данных:
  - ID: 77518524, index_date: 2025-03-31 12:07:33
  - ID: 77518523, index_date: 2025-03-31 12:12:22
  - ID: 77518520, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 325
✅ Загружено 325 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77515685
📅 Первая index_date: 2025-03-28 12:36:13, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 445
📌 Примеры данных:
  - ID: 77515682, index_date: 2025-03-28 12:36:13
  - ID: 77515681, index_date: 2025-03-31 12:06:45
  - ID: 77515680, index_date: 2025-03-31 10:56:59
📌 Новых записей (index_date > 2025-03-28 14:10:17): 336
✅ Загружено 336 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77513261
📅 Первая index_date: None, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 418
📌 Примеры данных:
  - ID: 77513247, index_date: 2025-02-28 17:41:14
  - ID: 77513230, index_date: 2025-03-31 12:12:18
  - ID: 77513224, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 350
✅ Загружено 350 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77511111
📅 Первая index_date: 2025-03-31 12:05:43, Последняя index_date: None
📌 Всего записей на странице: 375
📌 Примеры данных:
  - ID: 77511106, index_date: 2025-03-31 12:05:43
  - ID: 77511105, index_date: 2025-02-28 17:41:14
  - ID: 77511095, index_date: 2025-03-31 12:05:43
📌 Новых записей (index_date > 2025-03-28 14:10:17): 302
✅ Загружено 302 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77509107
📅 Первая index_date: None, Последняя index_date: None
📌 Всего записей на странице: 380
📌 Примеры данных:
  - ID: 77509100, index_date: 2025-02-28 17:41:14
  - ID: 77509099, index_date: 2025-03-31 12:09:18
  - ID: 77509082, index_date: 2025-03-31 12:09:05
📌 Новых записей (index_date > 2025-03-28 14:10:17): 293
✅ Загружено 293 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77506835
📅 Первая index_date: 2025-03-31 12:14:14, Последняя index_date: 2025-03-31 12:13:27
📌 Всего записей на странице: 376
📌 Примеры данных:
  - ID: 77506819, index_date: 2025-03-31 12:14:14
  - ID: 77506798, index_date: 2025-03-31 12:53:56
  - ID: 77506796, index_date: 2025-03-31 12:11:25
📌 Новых записей (index_date > 2025-03-28 14:10:17): 296
✅ Загружено 296 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77504362
📅 Первая index_date: 2025-03-31 12:13:18, Последняя index_date: 2025-03-31 12:09:18
📌 Всего записей на странице: 393
📌 Примеры данных:
  - ID: 77504353, index_date: 2025-03-31 12:13:18
  - ID: 77504349, index_date: 2025-03-31 12:13:54
  - ID: 77504348, index_date: 2025-03-31 12:06:49
📌 Новых записей (index_date > 2025-03-28 14:10:17): 320
✅ Загружено 320 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77502058
📅 Первая index_date: 2025-03-31 12:13:12, Последняя index_date: 2025-03-31 19:01:27
📌 Всего записей на странице: 429
📌 Примеры данных:
  - ID: 77502056, index_date: 2025-03-31 12:13:12
  - ID: 77502048, index_date: 2025-03-31 12:09:00
  - ID: 77502044, index_date: 2025-03-31 12:11:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 272
✅ Загружено 272 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77499480
📅 Первая index_date: 2025-03-31 12:07:24, Последняя index_date: 2025-03-31 12:07:56
📌 Всего записей на странице: 444
📌 Примеры данных:
  - ID: 77499479, index_date: 2025-03-31 12:07:24
  - ID: 77499478, index_date: 2025-03-31 12:09:18
  - ID: 77499473, index_date: 2025-03-31 12:05:44
📌 Новых записей (index_date > 2025-03-28 14:10:17): 314
✅ Загружено 314 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77497379
📅 Первая index_date: 2025-03-31 12:13:47, Последняя index_date: 2025-03-31 12:13:27
📌 Всего записей на странице: 434
📌 Примеры данных:
  - ID: 77497377, index_date: 2025-03-31 12:13:47
  - ID: 77497370, index_date: 2025-03-31 12:12:12
  - ID: 77497336, index_date: 2025-03-31 12:13:49
📌 Новых записей (index_date > 2025-03-28 14:10:17): 357
✅ Загружено 357 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77494694
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: 2025-03-31 12:11:14
📌 Всего записей на странице: 376
📌 Примеры данных:
  - ID: 77494692, index_date: 2025-02-28 17:41:14
  - ID: 77494681, index_date: 2025-03-31 12:09:43
  - ID: 77494675, index_date: 2025-03-31 12:05:44
📌 Новых записей (index_date > 2025-03-28 14:10:17): 294
✅ Загружено 294 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77491978
📅 Первая index_date: 2025-03-31 12:10:04, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 443
📌 Примеры данных:
  - ID: 77491974, index_date: 2025-03-31 12:10:04
  - ID: 77491973, index_date: 2025-03-31 12:10:25
  - ID: 77491969, index_date: 2025-03-31 12:09:41
📌 Новых записей (index_date > 2025-03-28 14:10:17): 348
✅ Загружено 348 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77490055
📅 Первая index_date: 2025-03-31 12:09:12, Последняя index_date: 2025-03-31 12:12:48
📌 Всего записей на странице: 422
📌 Примеры данных:
  - ID: 77490054, index_date: 2025-03-31 12:09:12
  - ID: 77490041, index_date: 2025-03-31 12:11:19
  - ID: 77490037, index_date: 2025-03-31 12:14:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 319
✅ Загружено 319 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77487552
📅 Первая index_date: 2025-03-31 12:07:43, Последняя index_date: 2025-03-31 12:12:48
📌 Всего записей на странице: 438
📌 Примеры данных:
  - ID: 77487551, index_date: 2025-03-31 12:07:43
  - ID: 77487547, index_date: 2025-03-31 12:11:25
  - ID: 77487546, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 223
✅ Загружено 223 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77485899
📅 Первая index_date: None, Последняя index_date: 2025-03-31 17:44:10
📌 Всего записей на странице: 400
📌 Примеры данных:
  - ID: 77485891, index_date: 2025-02-28 17:41:14
  - ID: 77485886, index_date: 2025-02-28 17:41:14
  - ID: 77485881, index_date: 2025-03-31 12:11:50
📌 Новых записей (index_date > 2025-03-28 14:10:17): 283
✅ Загружено 283 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77483830
📅 Первая index_date: 2025-03-31 12:06:42, Последняя index_date: 2025-03-31 12:09:47
📌 Всего записей на странице: 450
📌 Примеры данных:
  - ID: 77483828, index_date: 2025-03-31 12:06:42
  - ID: 77483826, index_date: 2025-03-31 12:13:04
  - ID: 77483814, index_date: 2025-03-31 12:12:52
📌 Новых записей (index_date > 2025-03-28 14:10:17): 395
✅ Загружено 395 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77481864
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: 2025-03-31 12:11:15
📌 Всего записей на странице: 427
📌 Примеры данных:
  - ID: 77481863, index_date: 2025-02-28 17:41:14
  - ID: 77481861, index_date: 2025-03-31 12:09:18
  - ID: 77481860, index_date: 2025-03-31 12:11:49
📌 Новых записей (index_date > 2025-03-28 14:10:17): 365
✅ Загружено 365 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77479721
📅 Первая index_date: 2025-03-31 12:11:25, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 435
📌 Примеры данных:
  - ID: 77479718, index_date: 2025-03-31 12:11:25
  - ID: 77479715, index_date: 2025-03-31 12:10:04
  - ID: 77479713, index_date: 2025-03-31 12:13:18
📌 Новых записей (index_date > 2025-03-28 14:10:17): 343
✅ Загружено 343 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77477145
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: 2025-03-31 12:12:18
📌 Всего записей на странице: 427
📌 Примеры данных:
  - ID: 77477132, index_date: 2025-02-28 17:41:14
  - ID: 77477131, index_date: 2025-03-31 12:07:56
  - ID: 77477118, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 323
✅ Загружено 323 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77475125
📅 Первая index_date: 2025-02-28 17:41:14, Последняя index_date: 2025-03-31 12:08:40
📌 Всего записей на странице: 426
📌 Примеры данных:
  - ID: 77475122, index_date: 2025-02-28 17:41:14
  - ID: 77475121, index_date: 2025-03-31 12:12:48
  - ID: 77475117, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 353
✅ Загружено 353 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77473294
📅 Первая index_date: 2025-03-31 12:07:56, Последняя index_date: None
📌 Всего записей на странице: 414
📌 Примеры данных:
  - ID: 77473288, index_date: 2025-03-31 12:07:56
  - ID: 77473286, index_date: 2025-03-31 12:09:35
  - ID: 77473282, index_date: 2025-03-31 14:29:47
📌 Новых записей (index_date > 2025-03-28 14:10:17): 358
✅ Загружено 358 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77471424
📅 Первая index_date: None, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 416
📌 Примеры данных:
  - ID: 77471413, index_date: 2025-03-31 12:08:55
  - ID: 77471411, index_date: 2025-03-31 12:09:00
  - ID: 77471408, index_date: 2025-02-28 17:41:14
📌 Новых записей (index_date > 2025-03-28 14:10:17): 332
✅ Загружено 332 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77469201
📅 Первая index_date: 2025-03-31 12:14:22, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 432
📌 Примеры данных:
  - ID: 77469194, index_date: 2025-03-31 12:14:22
  - ID: 77469192, index_date: 2025-03-31 12:11:22
  - ID: 77469191, index_date: 2025-03-31 21:01:07
📌 Новых записей (index_date > 2025-03-28 14:10:17): 384
✅ Загружено 384 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77466938
📅 Первая index_date: None, Последняя index_date: 2025-02-28 17:41:14
📌 Всего записей на странице: 439
📌 Примеры данных:
  - ID: 77466935, index_date: 2025-03-31 12:06:37
  - ID: 77466934, index_date: 2025-03-31 12:07:30
  - ID: 77466930, index_date: 2025-03-31 12:11:58
📌 Новых записей (index_date > 2025-03-28 14:10:17): 309
✅ Загружено 309 новых записей с этой страницы...

🔹 Запрос к API: https://ows.goszakup.gov.kz/v3/plans/deleted?page=next&limit=500&search_after=77464804
📅 Первая index_date: None, Последняя index_date: 2025-03-31 12:13:20
📌 Всего записей на странице: 455
📌 Примеры данных:
  - ID: 77464798, index_date: 2025-02-28 17:41:14
  - ID: 77464796, index_date: 2025-03-31 12:11:06
  - ID: 77464792, index_date: 2025-03-31 12:10:21
📌 Новых записей (index_date > 2025-03-28 14:10:17): 352
✅ Загружено 352 новых записей с этой страницы...

In [25]:
df_combined = df_combined.sort_values(by='index_date')
df_combined.head()

                id  rootrecord_id  is_deleted           index_date
9937885    3131588      2097933.0           1  2025-02-28 17:41:14
13242428  59721376     59721376.0           1  2025-02-28 17:41:14
13242427  59721378     59721378.0           1  2025-02-28 17:41:14
13242426  59721381     56700930.0           1  2025-02-28 17:41:14
13242425  59721384     58511109.0           1  2025-02-28 17:41:14

In [21]:
df_combined.tail(501)

                id  rootrecord_id  is_deleted           index_date
18772863  77267462     74964094.0           1  2025-03-28 14:10:17
18772843  77267552     74951894.0           1  2025-03-28 14:10:17
19875695  78409180            NaN           1  2025-03-31 19:41:11
19875696  78409179            NaN           1  2025-03-31 19:41:11
19875697  78409178            NaN           1  2025-03-31 19:41:11
...            ...            ...         ...                  ...
19875564  78409323            NaN           1  2025-03-31 20:01:25
19875563  78409324            NaN           1  2025-03-31 20:01:25
19875562  78409325            NaN           1  2025-03-31 20:01:25
19875568  78409318            NaN           1  2025-03-31 20:01:25
19875483  78409406     77879718.0           1  2025-03-31 20:04:35

[501 rows x 4 columns]