In [8]:
import requests
import pandas as pd
import time
import os
from datetime import datetime, timedelta

GRAPHQL_URL = "https://ows.goszakup.gov.kz/v3/graphql"
HEADERS = {
    "Content-Type": "application/json",
    "Authorization": "Bearer d5c3d78fc111d88a0a37b4ab8f83cbd5"
}

query_template = """
query GetPlans($filter: PlansFiltersInput, $after: Int) {
    Plans(filter: $filter, limit: 200, after: $after) {
        id
        dateCreate
        
        PlansSpec {
            id
            plnPointsId
            refEkrbId
            ekrbCode
            ekrbNameRu
            ekrbNameKz
            count
            price
            refFkrbSubprogramId
            fkrbSubprogramCode
            fkrbSubprogramNameRu
            fkrbSubprogramNameKz
            refFkrbId
            abpCode
            abpNameRu
            abpNameKz
            amount
            refFkrbProgramId
            fkrbProgramCode
            fkrbProgramNameRu
            fkrbProgramNameKz
            isActive
            isDeleted
            systemId
            indexDate
        }
    }
}
"""

output_dir = "plans_data_spec"
os.makedirs(output_dir, exist_ok=True)
combined_file = os.path.join(output_dir, "plans_combined_spec.parquet")

end_date = datetime(2024, 1, 1)
time_step = timedelta(days=7)

# Определяем начальную дату
if os.path.exists(combined_file):
    print(f"📂 Файл {combined_file} существует, проверяем самую старую дату...")
    df_existing = pd.read_parquet(combined_file)
    if not df_existing.empty and 'dateCreate' in df_existing.columns:
        start_date = pd.to_datetime(df_existing['dateCreate']).min().to_pydatetime()
        print(f"📅 Самая старая дата в файле: {start_date}")
    else:
        print("Файл пустой или нет столбца 'dateCreate', начинаем с текущей даты.")
        start_date = datetime.now()
else:
    print("Файл не существует, начинаем с текущей даты.")
    start_date = datetime.now()

request_count = 0
total_loaded = 0
plans_without_spec = 0
batch_size = 10000

def save_batch(plans_batch, file_path, append=True):
    df = pd.DataFrame(plans_batch)
    if append and os.path.exists(file_path):
        df.to_parquet(file_path, engine='fastparquet', append=True)
    else:
        df.to_parquet(file_path, index=False)
    print(f"📤 Сохранено {len(plans_batch)} записей в {file_path}")
    return []

def check_server_availability(url, headers, timeout=10):
    try:
        response = requests.get(url, headers=headers, timeout=timeout)
        return response.status_code == 200
    except:
        return False

plans_batch = []
current_end_date = start_date

while current_end_date > end_date:
    current_start_date = max(current_end_date - time_step, end_date)
    variables = {
        "filter": {
            "dateCreate": {
                "gte": current_start_date.strftime("%Y-%m-%d %H:%M:%S"),
                "lte": current_end_date.strftime("%Y-%m-%d %H:%M:%S")
            }
        },
        "after": None
    }
    
    range_completed = False
    retry_range_attempts = 0
    max_range_retries = 5

    while not range_completed and retry_range_attempts < max_range_retries:
        retry_range_attempts += 1
        print(f"📅 Обрабатываем диапазон {current_start_date} - {current_end_date} (попытка {retry_range_attempts}/{max_range_retries})")
        
        while True:
            request_count += 1
            print(f"🔄 Запрос #{request_count} для {current_start_date} - {current_end_date}")

            max_retries = 3
            response = None
            for attempt in range(max_retries):
                try:
                    response = requests.post(GRAPHQL_URL, json={"query": query_template, "variables": variables}, headers=HEADERS, timeout=15)
                    response.raise_for_status()
                    break
                except Exception as e:
                    print(f"⚠️ Ошибка (попытка {attempt + 1}/{max_retries}): {e}")
                    if attempt < max_retries - 1:
                        time.sleep(5)
                    else:
                        if not check_server_availability(GRAPHQL_URL, HEADERS):
                            print("Сервер недоступен. Ожидаем восстановления связи...")
                            time.sleep(30)
                            break
                        else:
                            print("Сервер доступен, но запрос не удался.")
                            break
            
            if response is None:
                print("Проблема с запросом — повторяем диапазон.")
                break

            data = response.json()
            plans = data.get("data", {}).get("Plans", [])
            if not plans:
                range_completed = True
                break

            count_loaded = 0
            for plan in plans:
                plans_spec = plan.get("PlansSpec", [])
                if not plans_spec:
                    plans_without_spec += 1
                    continue

                for spec in plans_spec:
                    plans_batch.append({
                        "plan_id": plan.get("id"),
                        "dateCreate": plan.get("dateCreate"),
                        "specId": spec.get("id"),
                        "plnPointsId": spec.get("plnPointsId"),
                        "refEkrbId": spec.get("refEkrbId"),
                        "ekrbCode": spec.get("ekrbCode"),
                        "ekrbNameRu": spec.get("ekrbNameRu"),
                        "ekrbNameKz": spec.get("ekrbNameKz"),
                        "count": spec.get("count"),
                        "price": spec.get("price"),
                        "refFkrbSubprogramId": spec.get("refFkrbSubprogramId"),
                        "fkrbSubprogramCode": spec.get("fkrbSubprogramCode"),
                        "fkrbSubprogramNameRu": spec.get("fkrbSubprogramNameRu"),
                        "fkrbSubprogramNameKz": spec.get("fkrbSubprogramNameKz"),
                        "refFkrbId": spec.get("refFkrbId"),
                        "abpCode": spec.get("abpCode"),
                        "abpNameRu": spec.get("abpNameRu"),
                        "abpNameKz": spec.get("abpNameKz"),
                        "amount": spec.get("amount"),
                        "refFkrbProgramId": spec.get("refFkrbProgramId"),
                        "fkrbProgramCode": spec.get("fkrbProgramCode"),
                        "fkrbProgramNameRu": spec.get("fkrbProgramNameRu"),
                        "fkrbProgramNameKz": spec.get("fkrbProgramNameKz"),
                        "isActive": spec.get("isActive"),
                        "isDeleted": spec.get("isDeleted"),
                        "systemId": spec.get("systemId"),
                        "indexDate": spec.get("indexDate")
                    })
                    count_loaded += 1

            total_loaded += count_loaded
            print(f"📥 Загружено {count_loaded} спецификаций. Всего: {total_loaded}")

            if len(plans_batch) >= batch_size:
                plans_batch = save_batch(plans_batch, combined_file, append=(total_loaded > batch_size))

            last_id = plans[-1].get("id")
            if last_id and len(plans) == 200:
                variables["after"] = int(last_id) if isinstance(last_id, str) and last_id.isdigit() else last_id
            else:
                range_completed = True
                break

            time.sleep(1)

        if not range_completed:
            print(f"Диапазон не завершен, повторяем через 30 секунд...")
            time.sleep(30)

    if not range_completed:
        print(f"Не удалось обработать диапазон {current_start_date} - {current_end_date} после {max_range_retries} попыток. Пропускаем.")
    
    current_end_date = current_start_date

if plans_batch:
    plans_batch = save_batch(plans_batch, combined_file, append=(total_loaded > len(plans_batch)))

print(f"Итог: планов без PlansSpec: {plans_without_spec}")
print(f"✅ Завершено. Всего загружено: {total_loaded}")

📂 Файл plans_data_spec\plans_combined_spec.parquet существует, проверяем самую старую дату...
📅 Самая старая дата в файле: 2025-01-09 20:44:09
📅 Обрабатываем диапазон 2025-01-02 20:44:09 - 2025-01-09 20:44:09 (попытка 1/5)
🔄 Запрос #1 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 118
🔄 Запрос #2 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 148 спецификаций. Всего: 266
🔄 Запрос #3 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 402
🔄 Запрос #4 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 141 спецификаций. Всего: 543
🔄 Запрос #5 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 642
🔄 Запрос #6 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 756
🔄 Запрос #7 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 845
🔄 Запрос #8 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 976
🔄 Запрос #9 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 164 спецификаций. Всего: 1140
🔄 Запрос #10 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 1265
🔄 Запрос #11 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 1369
🔄 Запрос #12 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 1481
🔄 Запрос #13 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 1617
🔄 Запрос #14 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 1741
🔄 Запрос #15 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 75 спецификаций. Всего: 1816
🔄 Запрос #16 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 1916
🔄 Запрос #17 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 2050
🔄 Запрос #18 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 156 спецификаций. Всего: 2206
🔄 Запрос #19 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 2334
🔄 Запрос #20 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 2470
🔄 Запрос #21 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 2605
🔄 Запрос #22 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 2738
🔄 Запрос #23 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 2869
🔄 Запрос #24 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 3004
🔄 Запрос #25 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 3107
🔄 Запрос #26 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 3195
🔄 Запрос #27 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 8 спецификаций. Всего: 3203
🔄 Запрос #28 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 7 спецификаций. Всего: 3210
🔄 Запрос #29 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 52 спецификаций. Всего: 3262
🔄 Запрос #30 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 3389
🔄 Запрос #31 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 141 спецификаций. Всего: 3530
🔄 Запрос #32 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 164 спецификаций. Всего: 3694
🔄 Запрос #33 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 141 спецификаций. Всего: 3835
🔄 Запрос #34 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 153 спецификаций. Всего: 3988
🔄 Запрос #35 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 137 спецификаций. Всего: 4125
🔄 Запрос #36 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 140 спецификаций. Всего: 4265
🔄 Запрос #37 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 146 спецификаций. Всего: 4411
🔄 Запрос #38 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 4520
🔄 Запрос #39 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 4639
🔄 Запрос #40 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 4724
🔄 Запрос #41 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 4856
🔄 Запрос #42 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 4958
🔄 Запрос #43 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 5087
🔄 Запрос #44 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 5225
🔄 Запрос #45 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 5355
🔄 Запрос #46 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 5488
🔄 Запрос #47 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 142 спецификаций. Всего: 5630
🔄 Запрос #48 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 148 спецификаций. Всего: 5778
🔄 Запрос #49 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 5921
🔄 Запрос #50 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 6042
🔄 Запрос #51 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 6143
🔄 Запрос #52 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 6274
🔄 Запрос #53 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 6384
🔄 Запрос #54 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 6492
🔄 Запрос #55 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 6582
🔄 Запрос #56 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 6647
🔄 Запрос #57 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 6760
🔄 Запрос #58 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 6874
🔄 Запрос #59 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 6986
🔄 Запрос #60 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 7115
🔄 Запрос #61 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 137 спецификаций. Всего: 7252
🔄 Запрос #62 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 53 спецификаций. Всего: 7305
🔄 Запрос #63 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 7389
🔄 Запрос #64 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 7454
🔄 Запрос #65 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 7583
🔄 Запрос #66 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 140 спецификаций. Всего: 7723
🔄 Запрос #67 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 7833
🔄 Запрос #68 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 7961
🔄 Запрос #69 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 164 спецификаций. Всего: 8125
🔄 Запрос #70 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 8241
🔄 Запрос #71 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 8298
🔄 Запрос #72 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 8434
🔄 Запрос #73 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 8516
🔄 Запрос #74 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 8646
🔄 Запрос #75 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 8758
🔄 Запрос #76 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 102 спецификаций. Всего: 8860
🔄 Запрос #77 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 8974
🔄 Запрос #78 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 9087
🔄 Запрос #79 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 9201
🔄 Запрос #80 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 9287
🔄 Запрос #81 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 9402
🔄 Запрос #82 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 9512
🔄 Запрос #83 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 145 спецификаций. Всего: 9657
🔄 Запрос #84 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 9763
🔄 Запрос #85 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 9879
🔄 Запрос #86 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 9998
🔄 Запрос #87 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 10106
📤 Сохранено 10106 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #88 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 10208
🔄 Запрос #89 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 10340
🔄 Запрос #90 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 10447
🔄 Запрос #91 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 10534
🔄 Запрос #92 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 157 спецификаций. Всего: 10691
🔄 Запрос #93 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 10795
🔄 Запрос #94 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 10891
🔄 Запрос #95 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 11026
🔄 Запрос #96 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 11112
🔄 Запрос #97 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 11190
🔄 Запрос #98 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 77 спецификаций. Всего: 11267
🔄 Запрос #99 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 11403
🔄 Запрос #100 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 11533
🔄 Запрос #101 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 11657
🔄 Запрос #102 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 11776
🔄 Запрос #103 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 11896
🔄 Запрос #104 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 12019
🔄 Запрос #105 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 23 спецификаций. Всего: 12042
🔄 Запрос #106 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 39 спецификаций. Всего: 12081
🔄 Запрос #107 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 12202
🔄 Запрос #108 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 12310
🔄 Запрос #109 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 12418
🔄 Запрос #110 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 12549
🔄 Запрос #111 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 12671
🔄 Запрос #112 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 72 спецификаций. Всего: 12743
🔄 Запрос #113 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 12841
🔄 Запрос #114 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 142 спецификаций. Всего: 12983
🔄 Запрос #115 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 13068
🔄 Запрос #116 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 79 спецификаций. Всего: 13147
🔄 Запрос #117 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 13241
🔄 Запрос #118 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 13343
🔄 Запрос #119 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 13457
🔄 Запрос #120 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 81 спецификаций. Всего: 13538
🔄 Запрос #121 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 13612
🔄 Запрос #122 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 13719
🔄 Запрос #123 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 13827
🔄 Запрос #124 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 13916
🔄 Запрос #125 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 14025
🔄 Запрос #126 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 14132
🔄 Запрос #127 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 14232
🔄 Запрос #128 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 14335
🔄 Запрос #129 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 72 спецификаций. Всего: 14407
🔄 Запрос #130 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 14511
🔄 Запрос #131 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 14604
🔄 Запрос #132 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 14714
🔄 Запрос #133 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 14806
🔄 Запрос #134 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 14871
🔄 Запрос #135 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 14957
🔄 Запрос #136 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 15086
🔄 Запрос #137 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 15184
🔄 Запрос #138 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 15293
🔄 Запрос #139 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 15388
🔄 Запрос #140 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 15485
🔄 Запрос #141 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 15601
🔄 Запрос #142 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 75 спецификаций. Всего: 15676
🔄 Запрос #143 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 15770
🔄 Запрос #144 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 15838
🔄 Запрос #145 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 15911
🔄 Запрос #146 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 45 спецификаций. Всего: 15956
🔄 Запрос #147 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 35 спецификаций. Всего: 15991
🔄 Запрос #148 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 63 спецификаций. Всего: 16054
🔄 Запрос #149 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 16155
🔄 Запрос #150 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 16239
🔄 Запрос #151 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 16339
🔄 Запрос #152 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 16430

🔄 Запрос #153 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 67 спецификаций. Всего: 16497
🔄 Запрос #154 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 77 спецификаций. Всего: 16574
🔄 Запрос #155 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 16658
🔄 Запрос #156 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 16767
🔄 Запрос #157 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 16876
🔄 Запрос #158 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 16959
🔄 Запрос #159 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 17058
🔄 Запрос #160 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 17163
🔄 Запрос #161 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 4 спецификаций. Всего: 17167
🔄 Запрос #162 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 3 спецификаций. Всего: 17170
🔄 Запрос #163 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 17282
🔄 Запрос #164 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 142 спецификаций. Всего: 17424
🔄 Запрос #165 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 17514
🔄 Запрос #166 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 17629
🔄 Запрос #167 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 17756
🔄 Запрос #168 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 17877
🔄 Запрос #169 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 146 спецификаций. Всего: 18023
🔄 Запрос #170 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 18116
🔄 Запрос #171 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 18219
🔄 Запрос #172 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 162 спецификаций. Всего: 18381
🔄 Запрос #173 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 18519
🔄 Запрос #174 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 18662
🔄 Запрос #175 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 149 спецификаций. Всего: 18811
🔄 Запрос #176 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 18926
🔄 Запрос #177 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 19032
🔄 Запрос #178 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 144 спецификаций. Всего: 19176
🔄 Запрос #179 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 163 спецификаций. Всего: 19339
🔄 Запрос #180 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 19465
🔄 Запрос #181 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 19592
🔄 Запрос #182 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 19721
🔄 Запрос #183 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 148 спецификаций. Всего: 19869
🔄 Запрос #184 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 19982
🔄 Запрос #185 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 20106
📤 Сохранено 10000 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #186 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 20249
🔄 Запрос #187 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 20361
🔄 Запрос #188 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 20429
🔄 Запрос #189 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 27 спецификаций. Всего: 20456
🔄 Запрос #190 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 20561
🔄 Запрос #191 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 20688
🔄 Запрос #192 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 20818
🔄 Запрос #193 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 20940
🔄 Запрос #194 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 21041
🔄 Запрос #195 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 21167
🔄 Запрос #196 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 21302
🔄 Запрос #197 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 139 спецификаций. Всего: 21441
🔄 Запрос #198 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 21567
🔄 Запрос #199 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 21696
🔄 Запрос #200 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 21822
🔄 Запрос #201 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 21928
🔄 Запрос #202 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 22038
🔄 Запрос #203 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 22154
🔄 Запрос #204 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 160 спецификаций. Всего: 22314
🔄 Запрос #205 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 22431
🔄 Запрос #206 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 22524
🔄 Запрос #207 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 22621
🔄 Запрос #208 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 22742
🔄 Запрос #209 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 22870
🔄 Запрос #210 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 23005
🔄 Запрос #211 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 23124
🔄 Запрос #212 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 23232
🔄 Запрос #213 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 23354
🔄 Запрос #214 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 23432
🔄 Запрос #215 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 23551
🔄 Запрос #216 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 156 спецификаций. Всего: 23707
🔄 Запрос #217 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 23828
🔄 Запрос #218 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 23936
🔄 Запрос #219 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 24060
🔄 Запрос #220 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 24190
🔄 Запрос #221 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 67 спецификаций. Всего: 24257
🔄 Запрос #222 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 24360
🔄 Запрос #223 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 24470
🔄 Запрос #224 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 24572
🔄 Запрос #225 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 24667
🔄 Запрос #226 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 24775
🔄 Запрос #227 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 24870
🔄 Запрос #228 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 24956
🔄 Запрос #229 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 123 спецификаций. Всего: 25079
🔄 Запрос #230 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 25186
🔄 Запрос #231 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 152 спецификаций. Всего: 25338
🔄 Запрос #232 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 25454
🔄 Запрос #233 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 25546
🔄 Запрос #234 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 25657
🔄 Запрос #235 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 25776
🔄 Запрос #236 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 25889
🔄 Запрос #237 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 26012
🔄 Запрос #238 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 26117
🔄 Запрос #239 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 26207
🔄 Запрос #240 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 26294
🔄 Запрос #241 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 62 спецификаций. Всего: 26356
🔄 Запрос #242 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 26470
🔄 Запрос #243 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 26552
🔄 Запрос #244 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 26653
🔄 Запрос #245 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 72 спецификаций. Всего: 26725
🔄 Запрос #246 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 26846
🔄 Запрос #247 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 62 спецификаций. Всего: 26908
🔄 Запрос #248 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 27033
🔄 Запрос #249 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 27158
🔄 Запрос #250 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 27270
🔄 Запрос #251 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 27390
🔄 Запрос #252 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 27520
🔄 Запрос #253 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 27628
🔄 Запрос #254 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 27706
🔄 Запрос #255 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 27809
🔄 Запрос #256 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 27931
🔄 Запрос #257 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 28021
🔄 Запрос #258 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 28121
🔄 Запрос #259 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 28189
🔄 Запрос #260 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 51 спецификаций. Всего: 28240
🔄 Запрос #261 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 23 спецификаций. Всего: 28263
🔄 Запрос #262 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 28362
🔄 Запрос #263 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 28486
🔄 Запрос #264 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 28596
🔄 Запрос #265 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 28707
🔄 Запрос #266 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 28805
🔄 Запрос #267 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 28929
🔄 Запрос #268 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 29030
🔄 Запрос #269 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 29162
🔄 Запрос #270 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 29283
🔄 Запрос #271 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 29409
🔄 Запрос #272 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 29529
🔄 Запрос #273 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 29613
🔄 Запрос #274 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 29713
🔄 Запрос #275 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 29806
🔄 Запрос #276 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 139 спецификаций. Всего: 29945
🔄 Запрос #277 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 30073
🔄 Запрос #278 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 27 спецификаций. Всего: 30100
🔄 Запрос #279 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 30184
📤 Сохранено 10078 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #280 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 43 спецификаций. Всего: 30227
🔄 Запрос #281 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 36 спецификаций. Всего: 30263
🔄 Запрос #282 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 30359
🔄 Запрос #283 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 30466
🔄 Запрос #284 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 30570
🔄 Запрос #285 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 30671
🔄 Запрос #286 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 30790
🔄 Запрос #287 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 30909
🔄 Запрос #288 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 31040
🔄 Запрос #289 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 149 спецификаций. Всего: 31189
🔄 Запрос #290 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 148 спецификаций. Всего: 31337
🔄 Запрос #291 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 47 спецификаций. Всего: 31384
🔄 Запрос #292 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 31514
🔄 Запрос #293 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 192 спецификаций. Всего: 31706
🔄 Запрос #294 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 139 спецификаций. Всего: 31845
🔄 Запрос #295 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 31953
🔄 Запрос #296 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 32047
🔄 Запрос #297 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 32167
🔄 Запрос #298 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 32266
🔄 Запрос #299 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 32323
🔄 Запрос #300 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 32396
🔄 Запрос #301 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 70 спецификаций. Всего: 32466
🔄 Запрос #302 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 32593
🔄 Запрос #303 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 32702
🔄 Запрос #304 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 32800
🔄 Запрос #305 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 32904
🔄 Запрос #306 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 13 спецификаций. Всего: 32917
🔄 Запрос #307 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 33000
🔄 Запрос #308 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 33120
🔄 Запрос #309 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 33225
🔄 Запрос #310 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 33353
🔄 Запрос #311 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 33445
🔄 Запрос #312 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 33581
🔄 Запрос #313 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 146 спецификаций. Всего: 33727
🔄 Запрос #314 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 33858
🔄 Запрос #315 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 34001
🔄 Запрос #316 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 34137
🔄 Запрос #317 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 34260
🔄 Запрос #318 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 143 спецификаций. Всего: 34403
🔄 Запрос #319 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 34538
🔄 Запрос #320 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 34674
🔄 Запрос #321 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 34803
🔄 Запрос #322 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 137 спецификаций. Всего: 34940
🔄 Запрос #323 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 35072
🔄 Запрос #324 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 137 спецификаций. Всего: 35209
🔄 Запрос #325 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 146 спецификаций. Всего: 35355
🔄 Запрос #326 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 35489
🔄 Запрос #327 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 35612
🔄 Запрос #328 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 35721
🔄 Запрос #329 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 35854
🔄 Запрос #330 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 35988
🔄 Запрос #331 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 36120
🔄 Запрос #332 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 139 спецификаций. Всего: 36259
🔄 Запрос #333 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 36373
🔄 Запрос #334 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 138 спецификаций. Всего: 36511
🔄 Запрос #335 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 36612
🔄 Запрос #336 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 32 спецификаций. Всего: 36644
🔄 Запрос #337 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 36733
🔄 Запрос #338 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 36860
🔄 Запрос #339 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 49 спецификаций. Всего: 36909
🔄 Запрос #340 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 37045
🔄 Запрос #341 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 150 спецификаций. Всего: 37195
🔄 Запрос #342 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 158 спецификаций. Всего: 37353
🔄 Запрос #343 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 37488
🔄 Запрос #344 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 37578
🔄 Запрос #345 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 37679
🔄 Запрос #346 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 37822
🔄 Запрос #347 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 37954
🔄 Запрос #348 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 158 спецификаций. Всего: 38112
🔄 Запрос #349 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 38190
🔄 Запрос #350 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 142 спецификаций. Всего: 38332
🔄 Запрос #351 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 157 спецификаций. Всего: 38489
🔄 Запрос #352 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 38620
🔄 Запрос #353 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 69 спецификаций. Всего: 38689
🔄 Запрос #354 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 38798
🔄 Запрос #355 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 38925
🔄 Запрос #356 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 39044
🔄 Запрос #357 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 157 спецификаций. Всего: 39201
🔄 Запрос #358 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 150 спецификаций. Всего: 39351
🔄 Запрос #359 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 159 спецификаций. Всего: 39510
🔄 Запрос #360 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 39599
🔄 Запрос #361 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 145 спецификаций. Всего: 39744
🔄 Запрос #362 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 39879
🔄 Запрос #363 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 151 спецификаций. Всего: 40030
🔄 Запрос #364 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 162 спецификаций. Всего: 40192
📤 Сохранено 10008 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #365 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 40323
🔄 Запрос #366 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 147 спецификаций. Всего: 40470
🔄 Запрос #367 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 172 спецификаций. Всего: 40642
🔄 Запрос #368 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 149 спецификаций. Всего: 40791
🔄 Запрос #369 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 161 спецификаций. Всего: 40952
🔄 Запрос #370 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 148 спецификаций. Всего: 41100
🔄 Запрос #371 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 141 спецификаций. Всего: 41241
🔄 Запрос #372 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 70 спецификаций. Всего: 41311
🔄 Запрос #373 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 41422
🔄 Запрос #374 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 141 спецификаций. Всего: 41563
🔄 Запрос #375 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 41684
🔄 Запрос #376 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 167 спецификаций. Всего: 41851
🔄 Запрос #377 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 154 спецификаций. Всего: 42005
🔄 Запрос #378 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 42123
🔄 Запрос #379 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 42244
🔄 Запрос #380 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 104 спецификаций. Всего: 42348
🔄 Запрос #381 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 42482
🔄 Запрос #382 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 42589
🔄 Запрос #383 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 42688
🔄 Запрос #384 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 42795
🔄 Запрос #385 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 42931
🔄 Запрос #386 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 43048
🔄 Запрос #387 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 43175
🔄 Запрос #388 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 43302
🔄 Запрос #389 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 43386
🔄 Запрос #390 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 43491
🔄 Запрос #391 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 43587
🔄 Запрос #392 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 43717
🔄 Запрос #393 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 43799
🔄 Запрос #394 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 43901
🔄 Запрос #395 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 43992
🔄 Запрос #396 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 44108
🔄 Запрос #397 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 44226
🔄 Запрос #398 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 44362
🔄 Запрос #399 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 44489
🔄 Запрос #400 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 44601
🔄 Запрос #401 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 44683
🔄 Запрос #402 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 44816
🔄 Запрос #403 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 44931
🔄 Запрос #404 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 45051
🔄 Запрос #405 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 45160
🔄 Запрос #406 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 45265
🔄 Запрос #407 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 45351
🔄 Запрос #408 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 45424
🔄 Запрос #409 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 46 спецификаций. Всего: 45470
🔄 Запрос #410 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 45592
🔄 Запрос #411 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 45699
🔄 Запрос #412 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 45813
🔄 Запрос #413 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 79 спецификаций. Всего: 45892
🔄 Запрос #414 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 45949
🔄 Запрос #415 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 75 спецификаций. Всего: 46024
🔄 Запрос #416 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 46089
🔄 Запрос #417 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 165 спецификаций. Всего: 46254
🔄 Запрос #418 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 46381
🔄 Запрос #419 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 46497
🔄 Запрос #420 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 46570
🔄 Запрос #421 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 146 спецификаций. Всего: 46716
🔄 Запрос #422 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 46841
🔄 Запрос #423 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 46946
🔄 Запрос #424 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 47070
🔄 Запрос #425 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 159 спецификаций. Всего: 47229
🔄 Запрос #426 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 67 спецификаций. Всего: 47296
🔄 Запрос #427 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 47416
🔄 Запрос #428 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 131 спецификаций. Всего: 47547
🔄 Запрос #429 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 47658
🔄 Запрос #430 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 47760
🔄 Запрос #431 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 47872
🔄 Запрос #432 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 47995
🔄 Запрос #433 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 48083
🔄 Запрос #434 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 48208
🔄 Запрос #435 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 48331
🔄 Запрос #436 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 48447
🔄 Запрос #437 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 48560
🔄 Запрос #438 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 48665
🔄 Запрос #439 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 45 спецификаций. Всего: 48710
🔄 Запрос #440 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 48833
🔄 Запрос #441 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 48921
🔄 Запрос #442 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 72 спецификаций. Всего: 48993
🔄 Запрос #443 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 61 спецификаций. Всего: 49054
🔄 Запрос #444 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 24 спецификаций. Всего: 49078
🔄 Запрос #445 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 49168
🔄 Запрос #446 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 49281
🔄 Запрос #447 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 49385
🔄 Запрос #448 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 49470
🔄 Запрос #449 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 49579
🔄 Запрос #450 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 49655
🔄 Запрос #451 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 49762
🔄 Запрос #452 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 49879
🔄 Запрос #453 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 49973
🔄 Запрос #454 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 50058
🔄 Запрос #455 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 50161
🔄 Запрос #456 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 50258

📤 Сохранено 10066 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #457 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 95 спецификаций. Всего: 50353
🔄 Запрос #458 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 50454
🔄 Запрос #459 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 50587
🔄 Запрос #460 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 50692
🔄 Запрос #461 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 50797
🔄 Запрос #462 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 50920
🔄 Запрос #463 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 51040
🔄 Запрос #464 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 51148
🔄 Запрос #465 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 51231
🔄 Запрос #466 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 51341
🔄 Запрос #467 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 51445
🔄 Запрос #468 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 51523
🔄 Запрос #469 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 51 спецификаций. Всего: 51574
🔄 Запрос #470 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 51676
🔄 Запрос #471 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 51778
🔄 Запрос #472 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 51875
🔄 Запрос #473 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 51981
🔄 Запрос #474 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 52101
🔄 Запрос #475 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 52219
🔄 Запрос #476 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 52339
🔄 Запрос #477 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 81 спецификаций. Всего: 52420
🔄 Запрос #478 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 52549
🔄 Запрос #479 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 52640
🔄 Запрос #480 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 52754
🔄 Запрос #481 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 52865
🔄 Запрос #482 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 52975
🔄 Запрос #483 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 53059
🔄 Запрос #484 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 53150
🔄 Запрос #485 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 140 спецификаций. Всего: 53290
🔄 Запрос #486 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 53414
🔄 Запрос #487 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 53539
🔄 Запрос #488 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 53657
🔄 Запрос #489 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 53784
🔄 Запрос #490 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 53892
🔄 Запрос #491 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 53978
🔄 Запрос #492 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 54 спецификаций. Всего: 54032
🔄 Запрос #493 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 54 спецификаций. Всего: 54086
🔄 Запрос #494 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 151 спецификаций. Всего: 54237
🔄 Запрос #495 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 54349
🔄 Запрос #496 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 72 спецификаций. Всего: 54421
🔄 Запрос #497 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 54507
🔄 Запрос #498 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 54635
🔄 Запрос #499 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 54746
🔄 Запрос #500 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 54860
🔄 Запрос #501 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 54996
🔄 Запрос #502 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 55118
🔄 Запрос #503 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 55215
🔄 Запрос #504 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 55336
🔄 Запрос #505 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 140 спецификаций. Всего: 55476
🔄 Запрос #506 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 55594
🔄 Запрос #507 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 55703
🔄 Запрос #508 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 55834
🔄 Запрос #509 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 47 спецификаций. Всего: 55881
🔄 Запрос #510 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 41 спецификаций. Всего: 55922
🔄 Запрос #511 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 56010
🔄 Запрос #512 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 56078
🔄 Запрос #513 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 56152
🔄 Запрос #514 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 42 спецификаций. Всего: 56194
🔄 Запрос #515 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 56259
🔄 Запрос #516 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 56355
🔄 Запрос #517 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 56470
🔄 Запрос #518 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 75 спецификаций. Всего: 56545
🔄 Запрос #519 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 81 спецификаций. Всего: 56626
🔄 Запрос #520 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 56721
🔄 Запрос #521 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 56853
🔄 Запрос #522 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 56956
🔄 Запрос #523 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 23 спецификаций. Всего: 56979
🔄 Запрос #524 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 57057
🔄 Запрос #525 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 3 спецификаций. Всего: 57060
🔄 Запрос #526 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 44 спецификаций. Всего: 57104
🔄 Запрос #527 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 57186
🔄 Запрос #528 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 79 спецификаций. Всего: 57265
🔄 Запрос #529 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 57333
🔄 Запрос #530 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 88 спецификаций. Всего: 57421
🔄 Запрос #531 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 57494
🔄 Запрос #532 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 57579
🔄 Запрос #533 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 61 спецификаций. Всего: 57640
🔄 Запрос #534 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 75 спецификаций. Всего: 57715
🔄 Запрос #535 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 57839
🔄 Запрос #536 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 57954
🔄 Запрос #537 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 58061
🔄 Запрос #538 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 51 спецификаций. Всего: 58112
🔄 Запрос #539 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 58204
🔄 Запрос #540 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 58301
🔄 Запрос #541 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 58407
🔄 Запрос #542 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 58506
🔄 Запрос #543 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 58592
🔄 Запрос #544 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 29 спецификаций. Всего: 58621
🔄 Запрос #545 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 58726
🔄 Запрос #546 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 58841
🔄 Запрос #547 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 58951
🔄 Запрос #548 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 59059
🔄 Запрос #549 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 59187
🔄 Запрос #550 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 59299
🔄 Запрос #551 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 59398
🔄 Запрос #552 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 59491
🔄 Запрос #553 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 59603
🔄 Запрос #554 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 59709
🔄 Запрос #555 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 59836
🔄 Запрос #556 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 59979
🔄 Запрос #557 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 60089
🔄 Запрос #558 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 60175
🔄 Запрос #559 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 7 спецификаций. Всего: 60182
🔄 Запрос #560 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 60280
📤 Сохранено 10022 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #561 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 60395
🔄 Запрос #562 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 60499
🔄 Запрос #563 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 60604
🔄 Запрос #564 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 157 спецификаций. Всего: 60761
🔄 Запрос #565 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 60858
🔄 Запрос #566 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 60981
🔄 Запрос #567 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 61082
🔄 Запрос #568 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 61199
🔄 Запрос #569 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 61327
🔄 Запрос #570 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 61457
🔄 Запрос #571 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 61583
🔄 Запрос #572 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 61684
🔄 Запрос #573 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 142 спецификаций. Всего: 61826
🔄 Запрос #574 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 61949
🔄 Запрос #575 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 62078
🔄 Запрос #576 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 62190
🔄 Запрос #577 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 62305
🔄 Запрос #578 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 62420
🔄 Запрос #579 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 62521
🔄 Запрос #580 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 62644
🔄 Запрос #581 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 62755
🔄 Запрос #582 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 62869
🔄 Запрос #583 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 62996
🔄 Запрос #584 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 63124
🔄 Запрос #585 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 63227
🔄 Запрос #586 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 63354
🔄 Запрос #587 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 151 спецификаций. Всего: 63505
🔄 Запрос #588 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 63615
🔄 Запрос #589 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 63705
🔄 Запрос #590 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 63834
🔄 Запрос #591 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 63918
🔄 Запрос #592 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 64048
🔄 Запрос #593 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 64179
🔄 Запрос #594 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 64317
🔄 Запрос #595 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 66 спецификаций. Всего: 64383
🔄 Запрос #596 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 64515
🔄 Запрос #597 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 64639
🔄 Запрос #598 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 64763
🔄 Запрос #599 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 139 спецификаций. Всего: 64902
🔄 Запрос #600 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 65014
🔄 Запрос #601 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 65133
🔄 Запрос #602 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 65263
🔄 Запрос #603 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 65363
🔄 Запрос #604 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 65480
🔄 Запрос #605 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 119 спецификаций. Всего: 65599
🔄 Запрос #606 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 65721
🔄 Запрос #607 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 65826
🔄 Запрос #608 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 65942
🔄 Запрос #609 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 66070
🔄 Запрос #610 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 66203
🔄 Запрос #611 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 66337
🔄 Запрос #612 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 66438
🔄 Запрос #613 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 157 спецификаций. Всего: 66595
🔄 Запрос #614 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 76 спецификаций. Всего: 66671
🔄 Запрос #615 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 64 спецификаций. Всего: 66735
🔄 Запрос #616 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 81 спецификаций. Всего: 66816
🔄 Запрос #617 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 66881
🔄 Запрос #618 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 66972
🔄 Запрос #619 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 159 спецификаций. Всего: 67131
🔄 Запрос #620 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 67245
🔄 Запрос #621 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 59 спецификаций. Всего: 67304
🔄 Запрос #622 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 141 спецификаций. Всего: 67445
🔄 Запрос #623 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 67550
🔄 Запрос #624 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 67675
🔄 Запрос #625 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 67796
🔄 Запрос #626 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 67912
🔄 Запрос #627 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 68003
🔄 Запрос #628 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 68124
🔄 Запрос #629 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 68228
🔄 Запрос #630 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 62 спецификаций. Всего: 68290
🔄 Запрос #631 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 63 спецификаций. Всего: 68353
🔄 Запрос #632 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 68460
🔄 Запрос #633 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 68585
🔄 Запрос #634 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 148 спецификаций. Всего: 68733
🔄 Запрос #635 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 68857
🔄 Запрос #636 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 150 спецификаций. Всего: 69007
🔄 Запрос #637 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 69103
🔄 Запрос #638 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 69219
🔄 Запрос #639 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 148 спецификаций. Всего: 69367
🔄 Запрос #640 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 53 спецификаций. Всего: 69420
🔄 Запрос #641 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 69535
🔄 Запрос #642 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 110 спецификаций. Всего: 69645
🔄 Запрос #643 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 69768
🔄 Запрос #644 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 69887
🔄 Запрос #645 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 69992
🔄 Запрос #646 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 70124
🔄 Запрос #647 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 46 спецификаций. Всего: 70170
🔄 Запрос #648 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 63 спецификаций. Всего: 70233
🔄 Запрос #649 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 70363
📤 Сохранено 10083 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #650 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 70466
🔄 Запрос #651 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 60 спецификаций. Всего: 70526
🔄 Запрос #652 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 70637
🔄 Запрос #653 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 70749
🔄 Запрос #654 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 180 спецификаций. Всего: 70929
🔄 Запрос #655 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 71041
🔄 Запрос #656 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 71164
🔄 Запрос #657 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 71288
🔄 Запрос #658 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 71345
🔄 Запрос #659 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 71423
🔄 Запрос #660 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 71540
🔄 Запрос #661 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 71656
🔄 Запрос #662 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 71758
🔄 Запрос #663 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 62 спецификаций. Всего: 71820
🔄 Запрос #664 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 71902
🔄 Запрос #665 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 72012
🔄 Запрос #666 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 72125
🔄 Запрос #667 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 72218
🔄 Запрос #668 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 72286
🔄 Запрос #669 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 72386
🔄 Запрос #670 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 72471
🔄 Запрос #671 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 72590
🔄 Запрос #672 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 72685
🔄 Запрос #673 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 143 спецификаций. Всего: 72828
🔄 Запрос #674 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 72925
🔄 Запрос #675 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 108 спецификаций. Всего: 73033
🔄 Запрос #676 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 73139
🔄 Запрос #677 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 73264
🔄 Запрос #678 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 73357
🔄 Запрос #679 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 73430
🔄 Запрос #680 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 73547
🔄 Запрос #681 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 73650
🔄 Запрос #682 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 73741
🔄 Запрос #683 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 73863
🔄 Запрос #684 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 73972
🔄 Запрос #685 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 74087
🔄 Запрос #686 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 74198
🔄 Запрос #687 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 62 спецификаций. Всего: 74260
🔄 Запрос #688 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 74371
🔄 Запрос #689 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 74463
🔄 Запрос #690 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 60 спецификаций. Всего: 74523
🔄 Запрос #691 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 74625
🔄 Запрос #692 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 74693
🔄 Запрос #693 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 74799
🔄 Запрос #694 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 74895
🔄 Запрос #695 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 75038
🔄 Запрос #696 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 80 спецификаций. Всего: 75118
🔄 Запрос #697 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 75234
🔄 Запрос #698 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 81 спецификаций. Всего: 75315
🔄 Запрос #699 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 75410
🔄 Запрос #700 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 139 спецификаций. Всего: 75549
🔄 Запрос #701 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 75657
🔄 Запрос #702 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 75762
🔄 Запрос #703 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 1 спецификаций. Всего: 75763
🔄 Запрос #704 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 58 спецификаций. Всего: 75821
🔄 Запрос #705 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 146 спецификаций. Всего: 75967
🔄 Запрос #706 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 76099
🔄 Запрос #707 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 76222
🔄 Запрос #708 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 144 спецификаций. Всего: 76366
🔄 Запрос #709 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 76498
🔄 Запрос #710 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 137 спецификаций. Всего: 76635
🔄 Запрос #711 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 76756
🔄 Запрос #712 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 76886
🔄 Запрос #713 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 77015
🔄 Запрос #714 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 144 спецификаций. Всего: 77159
🔄 Запрос #715 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 77297
🔄 Запрос #716 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 77414
🔄 Запрос #717 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 77504
🔄 Запрос #718 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 148 спецификаций. Всего: 77652
🔄 Запрос #719 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 61 спецификаций. Всего: 77713
🔄 Запрос #720 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 77797
🔄 Запрос #721 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 77880
🔄 Запрос #722 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 77970
🔄 Запрос #723 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 92 спецификаций. Всего: 78062
🔄 Запрос #724 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 78173
🔄 Запрос #725 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 78269
🔄 Запрос #726 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 78398
🔄 Запрос #727 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 78534
🔄 Запрос #728 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 78635
🔄 Запрос #729 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 155 спецификаций. Всего: 78790
🔄 Запрос #730 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 150 спецификаций. Всего: 78940
🔄 Запрос #731 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 79072
🔄 Запрос #732 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 79207
🔄 Запрос #733 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 79297
🔄 Запрос #734 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 79423
🔄 Запрос #735 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 60 спецификаций. Всего: 79483
🔄 Запрос #736 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 79621
🔄 Запрос #737 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 79753
🔄 Запрос #738 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 79889
🔄 Запрос #739 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 79981
🔄 Запрос #740 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 80091
🔄 Запрос #741 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 80156
🔄 Запрос #742 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 80264
🔄 Запрос #743 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 52 спецификаций. Всего: 80316
🔄 Запрос #744 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 80419
📤 Сохранено 10056 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #745 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 80506
🔄 Запрос #746 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 80644
🔄 Запрос #747 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 80772
🔄 Запрос #748 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 145 спецификаций. Всего: 80917
🔄 Запрос #749 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 81023
🔄 Запрос #750 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 120 спецификаций. Всего: 81143
🔄 Запрос #751 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 81254
🔄 Запрос #752 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 81344
🔄 Запрос #753 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 81474
🔄 Запрос #754 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 81539
🔄 Запрос #755 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 81664
🔄 Запрос #756 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 150 спецификаций. Всего: 81814
🔄 Запрос #757 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 81934
🔄 Запрос #758 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 82027
🔄 Запрос #759 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 82156
🔄 Запрос #760 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 160 спецификаций. Всего: 82316
🔄 Запрос #761 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 165 спецификаций. Всего: 82481
🔄 Запрос #762 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 164 спецификаций. Всего: 82645
🔄 Запрос #763 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 154 спецификаций. Всего: 82799
🔄 Запрос #764 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 82921
🔄 Запрос #765 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 159 спецификаций. Всего: 83080
🔄 Запрос #766 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 72 спецификаций. Всего: 83152
🔄 Запрос #767 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 83262
🔄 Запрос #768 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 152 спецификаций. Всего: 83414
🔄 Запрос #769 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 83501
🔄 Запрос #770 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 166 спецификаций. Всего: 83667
🔄 Запрос #771 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 147 спецификаций. Всего: 83814
🔄 Запрос #772 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 83919
🔄 Запрос #773 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 84028
🔄 Запрос #774 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 84111
🔄 Запрос #775 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 81 спецификаций. Всего: 84192
🔄 Запрос #776 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 84330
🔄 Запрос #777 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 84457
🔄 Запрос #778 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 84539
🔄 Запрос #779 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 84634
🔄 Запрос #780 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 84753
🔄 Запрос #781 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 84879
🔄 Запрос #782 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 139 спецификаций. Всего: 85018
🔄 Запрос #783 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 85117
🔄 Запрос #784 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 139 спецификаций. Всего: 85256
🔄 Запрос #785 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 148 спецификаций. Всего: 85404
🔄 Запрос #786 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 85478
🔄 Запрос #787 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 79 спецификаций. Всего: 85557
🔄 Запрос #788 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 85639
🔄 Запрос #789 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 85774
🔄 Запрос #790 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 85897
🔄 Запрос #791 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 53 спецификаций. Всего: 85950
🔄 Запрос #792 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 163 спецификаций. Всего: 86113
🔄 Запрос #793 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 150 спецификаций. Всего: 86263
🔄 Запрос #794 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 167 спецификаций. Всего: 86430
🔄 Запрос #795 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 39 спецификаций. Всего: 86469
🔄 Запрос #796 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 86604
🔄 Запрос #797 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 86701
🔄 Запрос #798 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 32 спецификаций. Всего: 86733
🔄 Запрос #799 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 86851
🔄 Запрос #800 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 159 спецификаций. Всего: 87010
🔄 Запрос #801 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 67 спецификаций. Всего: 87077
🔄 Запрос #802 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 87186
🔄 Запрос #803 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 87271
🔄 Запрос #804 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 87376
🔄 Запрос #805 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 87467
🔄 Запрос #806 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 87560
🔄 Запрос #807 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 87694
🔄 Запрос #808 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 87814
🔄 Запрос #809 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 87924
🔄 Запрос #810 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 88033
🔄 Запрос #811 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 144 спецификаций. Всего: 88177
🔄 Запрос #812 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 88315
🔄 Запрос #813 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 64 спецификаций. Всего: 88379
🔄 Запрос #814 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 88493
🔄 Запрос #815 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 88616
🔄 Запрос #816 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 88713
🔄 Запрос #817 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 88820
🔄 Запрос #818 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 88938
🔄 Запрос #819 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 89023
🔄 Запрос #820 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 89091
🔄 Запрос #821 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 140 спецификаций. Всего: 89231
🔄 Запрос #822 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 145 спецификаций. Всего: 89376
🔄 Запрос #823 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 89461
🔄 Запрос #824 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 89573
🔄 Запрос #825 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 89716
🔄 Запрос #826 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 89851

🔄 Запрос #827 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 89979
🔄 Запрос #828 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 90036
🔄 Запрос #829 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 6 спецификаций. Всего: 90042
🔄 Запрос #830 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 90174
🔄 Запрос #831 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 90307
🔄 Запрос #832 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 90445
📤 Сохранено 10026 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #833 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 90552
🔄 Запрос #834 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 90684
🔄 Запрос #835 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 90810
🔄 Запрос #836 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 90932
🔄 Запрос #837 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 91062
🔄 Запрос #838 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 163 спецификаций. Всего: 91225
🔄 Запрос #839 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 91356
🔄 Запрос #840 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 91467
🔄 Запрос #841 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 91599
🔄 Запрос #842 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 140 спецификаций. Всего: 91739
🔄 Запрос #843 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 154 спецификаций. Всего: 91893
🔄 Запрос #844 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 141 спецификаций. Всего: 92034
🔄 Запрос #845 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 92137
🔄 Запрос #846 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 151 спецификаций. Всего: 92288
🔄 Запрос #847 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 161 спецификаций. Всего: 92449
🔄 Запрос #848 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 147 спецификаций. Всего: 92596
🔄 Запрос #849 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 142 спецификаций. Всего: 92738
🔄 Запрос #850 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 92869
🔄 Запрос #851 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 92987
🔄 Запрос #852 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 141 спецификаций. Всего: 93128
🔄 Запрос #853 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 93258
🔄 Запрос #854 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 150 спецификаций. Всего: 93408
🔄 Запрос #855 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 93491
🔄 Запрос #856 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 93595
🔄 Запрос #857 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 148 спецификаций. Всего: 93743
🔄 Запрос #858 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 93870
🔄 Запрос #859 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 93983
🔄 Запрос #860 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 94113
🔄 Запрос #861 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 94242
🔄 Запрос #862 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 94365
🔄 Запрос #863 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 94492
🔄 Запрос #864 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 94576
🔄 Запрос #865 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 94710
🔄 Запрос #866 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 94798
🔄 Запрос #867 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 94908
🔄 Запрос #868 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 95043
🔄 Запрос #869 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 95173
🔄 Запрос #870 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 95293
🔄 Запрос #871 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 95395
🔄 Запрос #872 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 95520
🔄 Запрос #873 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 95646
🔄 Запрос #874 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 95789
🔄 Запрос #875 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 95932
🔄 Запрос #876 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 96059
🔄 Запрос #877 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 72 спецификаций. Всего: 96131
🔄 Запрос #878 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 33 спецификаций. Всего: 96164
🔄 Запрос #879 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 96285
🔄 Запрос #880 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 165 спецификаций. Всего: 96450
🔄 Запрос #881 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 178 спецификаций. Всего: 96628
🔄 Запрос #882 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 96711
🔄 Запрос #883 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 96814
🔄 Запрос #884 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 96927
🔄 Запрос #885 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 97057
🔄 Запрос #886 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 97183
🔄 Запрос #887 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 97301
🔄 Запрос #888 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 48 спецификаций. Всего: 97349
🔄 Запрос #889 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 97467
🔄 Запрос #890 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 97582
🔄 Запрос #891 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 97715
🔄 Запрос #892 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 97836
🔄 Запрос #893 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 97947
🔄 Запрос #894 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 98064
🔄 Запрос #895 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 98153
🔄 Запрос #896 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 98274
🔄 Запрос #897 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 98400
🔄 Запрос #898 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 98492
🔄 Запрос #899 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 98609
🔄 Запрос #900 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 59 спецификаций. Всего: 98668
🔄 Запрос #901 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 98783

🔄 Запрос #902 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 98882
🔄 Запрос #903 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 35 спецификаций. Всего: 98917
🔄 Запрос #904 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 98995
🔄 Запрос #905 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 75 спецификаций. Всего: 99070
🔄 Запрос #906 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 99169
🔄 Запрос #907 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 99294
🔄 Запрос #908 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 99391
🔄 Запрос #909 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 99520
🔄 Запрос #910 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 99644
🔄 Запрос #911 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 99769
🔄 Запрос #912 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 99887
🔄 Запрос #913 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 100003
🔄 Запрос #914 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 100085
🔄 Запрос #915 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 100203
🔄 Запрос #916 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 100319
🔄 Запрос #917 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 100424
🔄 Запрос #918 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 100552
📤 Сохранено 10107 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #919 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 43 спецификаций. Всего: 100595
🔄 Запрос #920 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 100687
🔄 Запрос #921 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 100821
🔄 Запрос #922 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 63 спецификаций. Всего: 100884
🔄 Запрос #923 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 100989
🔄 Запрос #924 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 101082
🔄 Запрос #925 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 101176
🔄 Запрос #926 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 101295
🔄 Запрос #927 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 80 спецификаций. Всего: 101375
🔄 Запрос #928 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 51 спецификаций. Всего: 101426
🔄 Запрос #929 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 101539
🔄 Запрос #930 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 101633
🔄 Запрос #931 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 101706
🔄 Запрос #932 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 145 спецификаций. Всего: 101851
🔄 Запрос #933 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 101933
🔄 Запрос #934 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 102009
🔄 Запрос #935 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 102116
🔄 Запрос #936 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 102221
🔄 Запрос #937 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 102315
🔄 Запрос #938 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 102413
🔄 Запрос #939 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 102525
🔄 Запрос #940 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 102608
🔄 Запрос #941 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 102740
🔄 Запрос #942 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 58 спецификаций. Всего: 102798
🔄 Запрос #943 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 102894
🔄 Запрос #944 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 103013
🔄 Запрос #945 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 103109
🔄 Запрос #946 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 103240
🔄 Запрос #947 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 103338
🔄 Запрос #948 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 103454
🔄 Запрос #949 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 103543
🔄 Запрос #950 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 103638
🔄 Запрос #951 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 103732
🔄 Запрос #952 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 103856
🔄 Запрос #953 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 103929
🔄 Запрос #954 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 81 спецификаций. Всего: 104010
🔄 Запрос #955 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 104084
🔄 Запрос #956 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 50 спецификаций. Всего: 104134
🔄 Запрос #957 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 71 спецификаций. Всего: 104205
🔄 Запрос #958 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 70 спецификаций. Всего: 104275
🔄 Запрос #959 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 67 спецификаций. Всего: 104342
🔄 Запрос #960 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 77 спецификаций. Всего: 104419
🔄 Запрос #961 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 104493
🔄 Запрос #962 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 104579
🔄 Запрос #963 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 104664
🔄 Запрос #964 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 104763
🔄 Запрос #965 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 46 спецификаций. Всего: 104809
🔄 Запрос #966 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 104899
🔄 Запрос #967 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 105014
🔄 Запрос #968 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 70 спецификаций. Всего: 105084
🔄 Запрос #969 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 72 спецификаций. Всего: 105156
🔄 Запрос #970 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 81 спецификаций. Всего: 105237
🔄 Запрос #971 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 105321
🔄 Запрос #972 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 105409
🔄 Запрос #973 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 105493
🔄 Запрос #974 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 105579
🔄 Запрос #975 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 105657
🔄 Запрос #976 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 105750
🔄 Запрос #977 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 105850
🔄 Запрос #978 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 90 спецификаций. Всего: 105940
🔄 Запрос #979 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 106026
🔄 Запрос #980 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 106123
🔄 Запрос #981 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 106214
🔄 Запрос #982 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 106316
🔄 Запрос #983 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 106405
🔄 Запрос #984 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 106519
🔄 Запрос #985 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 36 спецификаций. Всего: 106555
🔄 Запрос #986 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 5 спецификаций. Всего: 106560
🔄 Запрос #987 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 106695
🔄 Запрос #988 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 106800
🔄 Запрос #989 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 115 спецификаций. Всего: 106915
🔄 Запрос #990 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 107039
🔄 Запрос #991 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 107125
🔄 Запрос #992 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 107219
🔄 Запрос #993 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 107341
🔄 Запрос #994 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 107444
🔄 Запрос #995 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 107563
🔄 Запрос #996 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 53 спецификаций. Всего: 107616
🔄 Запрос #997 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 107710
🔄 Запрос #998 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 107767
🔄 Запрос #999 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 107892
🔄 Запрос #1000 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 107991
🔄 Запрос #1001 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 108084
🔄 Запрос #1002 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 81 спецификаций. Всего: 108165
🔄 Запрос #1003 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 108254
🔄 Запрос #1004 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 44 спецификаций. Всего: 108298
🔄 Запрос #1005 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 108363
🔄 Запрос #1006 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 108459
🔄 Запрос #1007 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 108535
🔄 Запрос #1008 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 108611
🔄 Запрос #1009 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 108730
🔄 Запрос #1010 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 108834
🔄 Запрос #1011 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 108954
🔄 Запрос #1012 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 109064
🔄 Запрос #1013 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 109169
🔄 Запрос #1014 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 109269
🔄 Запрос #1015 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 79 спецификаций. Всего: 109348
🔄 Запрос #1016 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 109458
🔄 Запрос #1017 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 109551
🔄 Запрос #1018 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 109646
🔄 Запрос #1019 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 109764
🔄 Запрос #1020 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 66 спецификаций. Всего: 109830
🔄 Запрос #1021 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 28 спецификаций. Всего: 109858
🔄 Запрос #1022 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 109932
🔄 Запрос #1023 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 110023
🔄 Запрос #1024 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 110154
🔄 Запрос #1025 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 110261
🔄 Запрос #1026 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 80 спецификаций. Всего: 110341
🔄 Запрос #1027 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 110453
🔄 Запрос #1028 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 140 спецификаций. Всего: 110593
📤 Сохранено 10041 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #1029 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 46 спецификаций. Всего: 110639
🔄 Запрос #1030 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 110713
🔄 Запрос #1031 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 6 спецификаций. Всего: 110719
🔄 Запрос #1032 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 110812
🔄 Запрос #1033 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 49 спецификаций. Всего: 110861
🔄 Запрос #1034 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 110963
🔄 Запрос #1035 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 111064
🔄 Запрос #1036 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 111149
🔄 Запрос #1037 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 111269
🔄 Запрос #1038 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 137 спецификаций. Всего: 111406
🔄 Запрос #1039 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 111523
🔄 Запрос #1040 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 59 спецификаций. Всего: 111582
🔄 Запрос #1041 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 111701
🔄 Запрос #1042 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 48 спецификаций. Всего: 111749
🔄 Запрос #1043 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 61 спецификаций. Всего: 111810
🔄 Запрос #1044 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 35 спецификаций. Всего: 111845
🔄 Запрос #1045 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 111947
🔄 Запрос #1046 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 112073
🔄 Запрос #1047 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 112130
🔄 Запрос #1048 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 112250
🔄 Запрос #1049 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 59 спецификаций. Всего: 112309
🔄 Запрос #1050 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 112385
🔄 Запрос #1051 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 10 спецификаций. Всего: 112395
🔄 Запрос #1052 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 112493
🔄 Запрос #1053 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 112618
🔄 Запрос #1054 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 112732
🔄 Запрос #1055 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 112846
🔄 Запрос #1056 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 59 спецификаций. Всего: 112905
🔄 Запрос #1057 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 112990
🔄 Запрос #1058 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 113124
🔄 Запрос #1059 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 113192
🔄 Запрос #1060 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 113290
🔄 Запрос #1061 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 59 спецификаций. Всего: 113349
🔄 Запрос #1062 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 18 спецификаций. Всего: 113367
🔄 Запрос #1063 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 113505
🔄 Запрос #1064 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 53 спецификаций. Всего: 113558
🔄 Запрос #1065 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 9 спецификаций. Всего: 113567
🔄 Запрос #1066 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 5 спецификаций. Всего: 113572
🔄 Запрос #1067 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 80 спецификаций. Всего: 113652
🔄 Запрос #1068 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 113748
🔄 Запрос #1069 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 113840
🔄 Запрос #1070 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 39 спецификаций. Всего: 113879
🔄 Запрос #1071 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 25 спецификаций. Всего: 113904
🔄 Запрос #1072 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 113994
🔄 Запрос #1073 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 52 спецификаций. Всего: 114046
🔄 Запрос #1074 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 114173
🔄 Запрос #1075 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 146 спецификаций. Всего: 114319
🔄 Запрос #1076 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 70 спецификаций. Всего: 114389
🔄 Запрос #1077 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 114515
🔄 Запрос #1078 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 114620
🔄 Запрос #1079 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 114733
🔄 Запрос #1080 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 69 спецификаций. Всего: 114802
🔄 Запрос #1081 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 114914
🔄 Запрос #1082 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 115033
🔄 Запрос #1083 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 115107
🔄 Запрос #1084 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 160 спецификаций. Всего: 115267
🔄 Запрос #1085 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 29 спецификаций. Всего: 115296
🔄 Запрос #1086 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 11 спецификаций. Всего: 115307
🔄 Запрос #1087 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 3 спецификаций. Всего: 115310
🔄 Запрос #1088 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 36 спецификаций. Всего: 115346
🔄 Запрос #1089 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 115424
🔄 Запрос #1090 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 115525
🔄 Запрос #1091 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 146 спецификаций. Всего: 115671
🔄 Запрос #1092 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 115759
🔄 Запрос #1093 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 115855
🔄 Запрос #1094 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 10 спецификаций. Всего: 115865
🔄 Запрос #1095 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 9 спецификаций. Всего: 115874
🔄 Запрос #1096 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 7 спецификаций. Всего: 115881
🔄 Запрос #1097 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 40 спецификаций. Всего: 115921
🔄 Запрос #1098 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 60 спецификаций. Всего: 115981
🔄 Запрос #1099 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 46 спецификаций. Всего: 116027
🔄 Запрос #1100 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 116128
🔄 Запрос #1101 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 63 спецификаций. Всего: 116191
🔄 Запрос #1102 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 9 спецификаций. Всего: 116200
🔄 Запрос #1103 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 16 спецификаций. Всего: 116216
🔄 Запрос #1104 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 32 спецификаций. Всего: 116248
🔄 Запрос #1105 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 116335
🔄 Запрос #1106 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 163 спецификаций. Всего: 116498
🔄 Запрос #1107 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 116555
🔄 Запрос #1108 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 31 спецификаций. Всего: 116586
🔄 Запрос #1109 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 36 спецификаций. Всего: 116622
🔄 Запрос #1110 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 29 спецификаций. Всего: 116651
🔄 Запрос #1111 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 79 спецификаций. Всего: 116730
🔄 Запрос #1112 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 116808
🔄 Запрос #1113 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 116917
🔄 Запрос #1114 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 117006
🔄 Запрос #1115 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 117109
🔄 Запрос #1116 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 117193
🔄 Запрос #1117 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 181 спецификаций. Всего: 117374
🔄 Запрос #1118 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 117506
🔄 Запрос #1119 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 117622
🔄 Запрос #1120 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 185 спецификаций. Всего: 117807
🔄 Запрос #1121 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 117910
🔄 Запрос #1122 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 118026
🔄 Запрос #1123 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 118153
🔄 Запрос #1124 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 137 спецификаций. Всего: 118290
🔄 Запрос #1125 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 118382
🔄 Запрос #1126 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 41 спецификаций. Всего: 118423

🔄 Запрос #1127 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 77 спецификаций. Всего: 118500
🔄 Запрос #1128 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 118601
🔄 Запрос #1129 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 118720
🔄 Запрос #1130 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 118828
🔄 Запрос #1131 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 118961
🔄 Запрос #1132 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 119076
🔄 Запрос #1133 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 62 спецификаций. Всего: 119138
🔄 Запрос #1134 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 119233
🔄 Запрос #1135 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 119356
🔄 Запрос #1136 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 119454
🔄 Запрос #1137 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 42 спецификаций. Всего: 119496
🔄 Запрос #1138 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 56 спецификаций. Всего: 119552
🔄 Запрос #1139 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 119620
🔄 Запрос #1140 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 119732
🔄 Запрос #1141 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 48 спецификаций. Всего: 119780
🔄 Запрос #1142 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 119888
🔄 Запрос #1143 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 120022
🔄 Запрос #1144 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 120111
🔄 Запрос #1145 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 120227
🔄 Запрос #1146 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 158 спецификаций. Всего: 120385
🔄 Запрос #1147 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 157 спецификаций. Всего: 120542
🔄 Запрос #1148 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 71 спецификаций. Всего: 120613
📤 Сохранено 10020 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #1149 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 120720
🔄 Запрос #1150 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 120815
🔄 Запрос #1151 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 120925
🔄 Запрос #1152 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 80 спецификаций. Всего: 121005
🔄 Запрос #1153 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 121124
🔄 Запрос #1154 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 121242
🔄 Запрос #1155 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 121363
🔄 Запрос #1156 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 80 спецификаций. Всего: 121443
🔄 Запрос #1157 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 121569
🔄 Запрос #1158 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 121690
🔄 Запрос #1159 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 70 спецификаций. Всего: 121760
🔄 Запрос #1160 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 121870
🔄 Запрос #1161 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 121987
🔄 Запрос #1162 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 122103
🔄 Запрос #1163 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 122189
🔄 Запрос #1164 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 122290
🔄 Запрос #1165 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 122413
🔄 Запрос #1166 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 122551
🔄 Запрос #1167 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 122638
🔄 Запрос #1168 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 51 спецификаций. Всего: 122689
🔄 Запрос #1169 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 122746
🔄 Запрос #1170 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 44 спецификаций. Всего: 122790
🔄 Запрос #1171 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 122906
🔄 Запрос #1172 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 122980
🔄 Запрос #1173 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 123095
🔄 Запрос #1174 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 123228
🔄 Запрос #1175 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 152 спецификаций. Всего: 123380
🔄 Запрос #1176 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 123482
🔄 Запрос #1177 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 123594
🔄 Запрос #1178 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 56 спецификаций. Всего: 123650
🔄 Запрос #1179 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 123765
🔄 Запрос #1180 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 47 спецификаций. Всего: 123812
🔄 Запрос #1181 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 123940
🔄 Запрос #1182 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 124057
🔄 Запрос #1183 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 124148
🔄 Запрос #1184 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 124271
🔄 Запрос #1185 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 124390
🔄 Запрос #1186 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 126 спецификаций. Всего: 124516
🔄 Запрос #1187 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 124620
🔄 Запрос #1188 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 124706
🔄 Запрос #1189 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 24 спецификаций. Всего: 124730
🔄 Запрос #1190 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 124795
🔄 Запрос #1191 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 132 спецификаций. Всего: 124927
🔄 Запрос #1192 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 125023
🔄 Запрос #1193 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 125157
🔄 Запрос #1194 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 64 спецификаций. Всего: 125221
🔄 Запрос #1195 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 125289
🔄 Запрос #1196 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 70 спецификаций. Всего: 125359
🔄 Запрос #1197 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 125489
🔄 Запрос #1198 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 125604
🔄 Запрос #1199 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 140 спецификаций. Всего: 125744
🔄 Запрос #1200 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 161 спецификаций. Всего: 125905
🔄 Запрос #1201 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 147 спецификаций. Всего: 126052
🔄 Запрос #1202 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 138 спецификаций. Всего: 126190
🔄 Запрос #1203 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 79 спецификаций. Всего: 126269
🔄 Запрос #1204 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 126373
🔄 Запрос #1205 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 138 спецификаций. Всего: 126511
🔄 Запрос #1206 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 126644
🔄 Запрос #1207 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 137 спецификаций. Всего: 126781
🔄 Запрос #1208 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 155 спецификаций. Всего: 126936
🔄 Запрос #1209 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 160 спецификаций. Всего: 127096
🔄 Запрос #1210 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 147 спецификаций. Всего: 127243
🔄 Запрос #1211 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 43 спецификаций. Всего: 127286
🔄 Запрос #1212 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 127371
🔄 Запрос #1213 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 42 спецификаций. Всего: 127413
🔄 Запрос #1214 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 127542
🔄 Запрос #1215 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 152 спецификаций. Всего: 127694
🔄 Запрос #1216 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 127792
🔄 Запрос #1217 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 61 спецификаций. Всего: 127853
🔄 Запрос #1218 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 148 спецификаций. Всего: 128001
🔄 Запрос #1219 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 62 спецификаций. Всего: 128063
🔄 Запрос #1220 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 36 спецификаций. Всего: 128099
🔄 Запрос #1221 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 70 спецификаций. Всего: 128169
🔄 Запрос #1222 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 47 спецификаций. Всего: 128216
🔄 Запрос #1223 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 25 спецификаций. Всего: 128241
🔄 Запрос #1224 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 128306
🔄 Запрос #1225 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 61 спецификаций. Всего: 128367
🔄 Запрос #1226 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 58 спецификаций. Всего: 128425
🔄 Запрос #1227 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 54 спецификаций. Всего: 128479
🔄 Запрос #1228 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 58 спецификаций. Всего: 128537
🔄 Запрос #1229 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 55 спецификаций. Всего: 128592
🔄 Запрос #1230 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 18 спецификаций. Всего: 128610
🔄 Запрос #1231 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 128675
🔄 Запрос #1232 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 144 спецификаций. Всего: 128819
🔄 Запрос #1233 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 128913
🔄 Запрос #1234 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 34 спецификаций. Всего: 128947
🔄 Запрос #1235 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 129037
🔄 Запрос #1236 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 129180
🔄 Запрос #1237 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 129300
🔄 Запрос #1238 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 129424
🔄 Запрос #1239 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 146 спецификаций. Всего: 129570
🔄 Запрос #1240 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 148 спецификаций. Всего: 129718
🔄 Запрос #1241 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 129831
🔄 Запрос #1242 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 129926
🔄 Запрос #1243 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 130000
🔄 Запрос #1244 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 130135
🔄 Запрос #1245 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 130231
🔄 Запрос #1246 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 130358
🔄 Запрос #1247 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 130465
🔄 Запрос #1248 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 66 спецификаций. Всего: 130531
🔄 Запрос #1249 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 34 спецификаций. Всего: 130565
🔄 Запрос #1250 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 49 спецификаций. Всего: 130614
📤 Сохранено 10001 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #1251 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 130709
🔄 Запрос #1252 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 45 спецификаций. Всего: 130754
🔄 Запрос #1253 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 130851
🔄 Запрос #1254 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 55 спецификаций. Всего: 130906
🔄 Запрос #1255 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 12 спецификаций. Всего: 130918
🔄 Запрос #1256 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 48 спецификаций. Всего: 130966
🔄 Запрос #1257 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 38 спецификаций. Всего: 131004
🔄 Запрос #1258 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 60 спецификаций. Всего: 131064
🔄 Запрос #1259 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 131158
🔄 Запрос #1260 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 60 спецификаций. Всего: 131218
🔄 Запрос #1261 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 147 спецификаций. Всего: 131365
🔄 Запрос #1262 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 131482
🔄 Запрос #1263 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 131596
🔄 Запрос #1264 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 131716
🔄 Запрос #1265 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 131818
🔄 Запрос #1266 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 27 спецификаций. Всего: 131845
🔄 Запрос #1267 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 131913
🔄 Запрос #1268 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 132036
🔄 Запрос #1269 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 81 спецификаций. Всего: 132117
🔄 Запрос #1270 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 132228
🔄 Запрос #1271 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 132344
🔄 Запрос #1272 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 137 спецификаций. Всего: 132481
🔄 Запрос #1273 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 153 спецификаций. Всего: 132634
🔄 Запрос #1274 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 132749
🔄 Запрос #1275 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 54 спецификаций. Всего: 132803
🔄 Запрос #1276 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 5 спецификаций. Всего: 132808
🔄 Запрос #1277 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 79 спецификаций. Всего: 132887
🔄 Запрос #1278 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 142 спецификаций. Всего: 133029

🔄 Запрос #1279 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 43 спецификаций. Всего: 133072
🔄 Запрос #1280 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 133140
🔄 Запрос #1281 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 170 спецификаций. Всего: 133310
🔄 Запрос #1282 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 133443
🔄 Запрос #1283 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 133533
🔄 Запрос #1284 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 45 спецификаций. Всего: 133578
🔄 Запрос #1285 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 61 спецификаций. Всего: 133639
🔄 Запрос #1286 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 133737
🔄 Запрос #1287 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 133841
🔄 Запрос #1288 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 46 спецификаций. Всего: 133887
🔄 Запрос #1289 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 2 спецификаций. Всего: 133889
🔄 Запрос #1290 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 47 спецификаций. Всего: 133936
🔄 Запрос #1291 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 37 спецификаций. Всего: 133973
🔄 Запрос #1292 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 34 спецификаций. Всего: 134007
🔄 Запрос #1293 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 140 спецификаций. Всего: 134147
🔄 Запрос #1294 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 176 спецификаций. Всего: 134323
🔄 Запрос #1295 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 134438
🔄 Запрос #1296 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 134581
🔄 Запрос #1297 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 134682
🔄 Запрос #1298 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 35 спецификаций. Всего: 134717
🔄 Запрос #1299 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 64 спецификаций. Всего: 134781
🔄 Запрос #1300 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 134892
🔄 Запрос #1301 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 134995
🔄 Запрос #1302 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 135097
🔄 Запрос #1303 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 30 спецификаций. Всего: 135127
🔄 Запрос #1304 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 2 спецификаций. Всего: 135129
🔄 Запрос #1305 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 36 спецификаций. Всего: 135165
🔄 Запрос #1306 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 4 спецификаций. Всего: 135169
🔄 Запрос #1307 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 49 спецификаций. Всего: 135218
🔄 Запрос #1308 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 167 спецификаций. Всего: 135385
🔄 Запрос #1309 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 135490
🔄 Запрос #1310 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 58 спецификаций. Всего: 135548
🔄 Запрос #1311 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 135681
🔄 Запрос #1312 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 18 спецификаций. Всего: 135699
🔄 Запрос #1313 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 135794
🔄 Запрос #1314 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 135909
🔄 Запрос #1315 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 136019
🔄 Запрос #1316 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 35 спецификаций. Всего: 136054
🔄 Запрос #1317 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 42 спецификаций. Всего: 136096
🔄 Запрос #1318 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 44 спецификаций. Всего: 136140
🔄 Запрос #1319 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 41 спецификаций. Всего: 136181
🔄 Запрос #1320 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 136305
🔄 Запрос #1321 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 136396
🔄 Запрос #1322 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 136511
🔄 Запрос #1323 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 144 спецификаций. Всего: 136655
🔄 Запрос #1324 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 136742
🔄 Запрос #1325 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 36 спецификаций. Всего: 136778
🔄 Запрос #1326 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 136902
🔄 Запрос #1327 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 67 спецификаций. Всего: 136969
🔄 Запрос #1328 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 59 спецификаций. Всего: 137028
🔄 Запрос #1329 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 137102
🔄 Запрос #1330 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 137185
🔄 Запрос #1331 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 137274
🔄 Запрос #1332 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 137371
🔄 Запрос #1333 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 137497
🔄 Запрос #1334 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 137616
🔄 Запрос #1335 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 137706
🔄 Запрос #1336 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 137763
🔄 Запрос #1337 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 137841
🔄 Запрос #1338 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 137943
🔄 Запрос #1339 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 43 спецификаций. Всего: 137986
🔄 Запрос #1340 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 1 спецификаций. Всего: 137987
🔄 Запрос #1341 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 1 спецификаций. Всего: 137988
🔄 Запрос #1342 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 2 спецификаций. Всего: 137990
🔄 Запрос #1343 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 2 спецификаций. Всего: 137992
🔄 Запрос #1344 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 0 спецификаций. Всего: 137992
🔄 Запрос #1345 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 6 спецификаций. Всего: 137998
🔄 Запрос #1346 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 138119
🔄 Запрос #1347 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 138234
🔄 Запрос #1348 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 138322
🔄 Запрос #1349 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 27 спецификаций. Всего: 138349
🔄 Запрос #1350 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 138466
🔄 Запрос #1351 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 138587
🔄 Запрос #1352 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 138714
🔄 Запрос #1353 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 138857
🔄 Запрос #1354 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 138987
🔄 Запрос #1355 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 122 спецификаций. Всего: 139109
🔄 Запрос #1356 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 139209
🔄 Запрос #1357 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 139317
🔄 Запрос #1358 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 139393
🔄 Запрос #1359 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 30 спецификаций. Всего: 139423
🔄 Запрос #1360 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 6 спецификаций. Всего: 139429
🔄 Запрос #1361 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 80 спецификаций. Всего: 139509
🔄 Запрос #1362 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 139637
🔄 Запрос #1363 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 141 спецификаций. Всего: 139778
🔄 Запрос #1364 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 139866
🔄 Запрос #1365 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 139969
🔄 Запрос #1366 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 140059
🔄 Запрос #1367 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 140179
🔄 Запрос #1368 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 67 спецификаций. Всего: 140246
🔄 Запрос #1369 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 46 спецификаций. Всего: 140292
🔄 Запрос #1370 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 77 спецификаций. Всего: 140369
🔄 Запрос #1371 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 41 спецификаций. Всего: 140410
🔄 Запрос #1372 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 140529
🔄 Запрос #1373 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 140642
📤 Сохранено 10028 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #1374 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 147 спецификаций. Всего: 140789
🔄 Запрос #1375 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 140919
🔄 Запрос #1376 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 141033
🔄 Запрос #1377 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 141124
🔄 Запрос #1378 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 141230
🔄 Запрос #1379 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 135 спецификаций. Всего: 141365
🔄 Запрос #1380 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 141471
🔄 Запрос #1381 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 141582
🔄 Запрос #1382 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 141668
🔄 Запрос #1383 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 60 спецификаций. Всего: 141728
🔄 Запрос #1384 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 142 спецификаций. Всего: 141870
🔄 Запрос #1385 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 158 спецификаций. Всего: 142028
🔄 Запрос #1386 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 142149
🔄 Запрос #1387 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 158 спецификаций. Всего: 142307
🔄 Запрос #1388 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 50 спецификаций. Всего: 142357
🔄 Запрос #1389 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 142459
🔄 Запрос #1390 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 142592
🔄 Запрос #1391 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 142677
🔄 Запрос #1392 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 142769
🔄 Запрос #1393 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 142870
🔄 Запрос #1394 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 142968
🔄 Запрос #1395 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 143074
🔄 Запрос #1396 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 75 спецификаций. Всего: 143149
🔄 Запрос #1397 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 50 спецификаций. Всего: 143199
🔄 Запрос #1398 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 143283
🔄 Запрос #1399 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 56 спецификаций. Всего: 143339
🔄 Запрос #1400 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 64 спецификаций. Всего: 143403
🔄 Запрос #1401 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 143502
🔄 Запрос #1402 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 21 спецификаций. Всего: 143523
🔄 Запрос #1403 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 143580
🔄 Запрос #1404 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 19 спецификаций. Всего: 143599
🔄 Запрос #1405 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 143672
🔄 Запрос #1406 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 143781
🔄 Запрос #1407 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 143879
🔄 Запрос #1408 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 67 спецификаций. Всего: 143946
🔄 Запрос #1409 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 144054
🔄 Запрос #1410 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 52 спецификаций. Всего: 144106
🔄 Запрос #1411 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 46 спецификаций. Всего: 144152
🔄 Запрос #1412 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 144225
🔄 Запрос #1413 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 144328
🔄 Запрос #1414 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 139 спецификаций. Всего: 144467
🔄 Запрос #1415 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 143 спецификаций. Всего: 144610
🔄 Запрос #1416 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 144743
🔄 Запрос #1417 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 144821
🔄 Запрос #1418 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 144878
🔄 Запрос #1419 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 52 спецификаций. Всего: 144930
🔄 Запрос #1420 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 144998
🔄 Запрос #1421 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 145071
🔄 Запрос #1422 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 145186
🔄 Запрос #1423 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 8 спецификаций. Всего: 145194
🔄 Запрос #1424 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 3 спецификаций. Всего: 145197
🔄 Запрос #1425 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 5 спецификаций. Всего: 145202
🔄 Запрос #1426 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 58 спецификаций. Всего: 145260
🔄 Запрос #1427 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 145344
🔄 Запрос #1428 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 145457
🔄 Запрос #1429 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 39 спецификаций. Всего: 145496
🔄 Запрос #1430 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 145583
🔄 Запрос #1431 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 4 спецификаций. Всего: 145587

🔄 Запрос #1432 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 145660
🔄 Запрос #1433 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 24 спецификаций. Всего: 145684
🔄 Запрос #1434 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 22 спецификаций. Всего: 145706
🔄 Запрос #1435 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 1 спецификаций. Всего: 145707
🔄 Запрос #1436 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 58 спецификаций. Всего: 145765
🔄 Запрос #1437 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 26 спецификаций. Всего: 145791
🔄 Запрос #1438 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 43 спецификаций. Всего: 145834
🔄 Запрос #1439 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 61 спецификаций. Всего: 145895
🔄 Запрос #1440 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 145983
🔄 Запрос #1441 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 67 спецификаций. Всего: 146050
🔄 Запрос #1442 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 146118
🔄 Запрос #1443 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 146216
🔄 Запрос #1444 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 42 спецификаций. Всего: 146258
🔄 Запрос #1445 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 151 спецификаций. Всего: 146409
🔄 Запрос #1446 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 146516
🔄 Запрос #1447 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 21 спецификаций. Всего: 146537
🔄 Запрос #1448 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 146594
🔄 Запрос #1449 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 154 спецификаций. Всего: 146748
🔄 Запрос #1450 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 146841
🔄 Запрос #1451 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 71 спецификаций. Всего: 146912
🔄 Запрос #1452 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 146999
🔄 Запрос #1453 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 147075
🔄 Запрос #1454 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 147199
🔄 Запрос #1455 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 147303
🔄 Запрос #1456 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 147426
🔄 Запрос #1457 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 150 спецификаций. Всего: 147576
🔄 Запрос #1458 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 156 спецификаций. Всего: 147732
🔄 Запрос #1459 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 48 спецификаций. Всего: 147780
🔄 Запрос #1460 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 1 спецификаций. Всего: 147781
🔄 Запрос #1461 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 3 спецификаций. Всего: 147784
🔄 Запрос #1462 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 71 спецификаций. Всего: 147855
🔄 Запрос #1463 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 147964
🔄 Запрос #1464 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 148071
🔄 Запрос #1465 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 148175
🔄 Запрос #1466 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 148302
🔄 Запрос #1467 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 72 спецификаций. Всего: 148374
🔄 Запрос #1468 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 165 спецификаций. Всего: 148539
🔄 Запрос #1469 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 149 спецификаций. Всего: 148688
🔄 Запрос #1470 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 9 спецификаций. Всего: 148697
🔄 Запрос #1471 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 4 спецификаций. Всего: 148701
🔄 Запрос #1472 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 50 спецификаций. Всего: 148751
🔄 Запрос #1473 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 148856
🔄 Запрос #1474 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 6 спецификаций. Всего: 148862
🔄 Запрос #1475 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 4 спецификаций. Всего: 148866
🔄 Запрос #1476 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 41 спецификаций. Всего: 148907
🔄 Запрос #1477 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 154 спецификаций. Всего: 149061
🔄 Запрос #1478 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 149143
🔄 Запрос #1479 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 149259
🔄 Запрос #1480 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 149368
🔄 Запрос #1481 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 149436
🔄 Запрос #1482 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 75 спецификаций. Всего: 149511
🔄 Запрос #1483 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 56 спецификаций. Всего: 149567
🔄 Запрос #1484 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 72 спецификаций. Всего: 149639
🔄 Запрос #1485 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 44 спецификаций. Всего: 149683
🔄 Запрос #1486 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 55 спецификаций. Всего: 149738
🔄 Запрос #1487 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 52 спецификаций. Всего: 149790
🔄 Запрос #1488 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 121 спецификаций. Всего: 149911
🔄 Запрос #1489 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 149993
🔄 Запрос #1490 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 150061
🔄 Запрос #1491 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 150156
🔄 Запрос #1492 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 150247
🔄 Запрос #1493 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 72 спецификаций. Всего: 150319
🔄 Запрос #1494 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 150407
🔄 Запрос #1495 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 150509
🔄 Запрос #1496 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 150637
🔄 Запрос #1497 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 150754
📤 Сохранено 10112 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #1498 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 150865
🔄 Запрос #1499 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 29 спецификаций. Всего: 150894
🔄 Запрос #1500 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 150976
🔄 Запрос #1501 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 151089
🔄 Запрос #1502 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 151176
🔄 Запрос #1503 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 151259
🔄 Запрос #1504 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 69 спецификаций. Всего: 151328
🔄 Запрос #1505 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 151424
🔄 Запрос #1506 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09

📥 Загружено 51 спецификаций. Всего: 151475
🔄 Запрос #1507 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 151566
🔄 Запрос #1508 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 151649
🔄 Запрос #1509 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 42 спецификаций. Всего: 151691
🔄 Запрос #1510 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 10 спецификаций. Всего: 151701
🔄 Запрос #1511 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 40 спецификаций. Всего: 151741
🔄 Запрос #1512 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 75 спецификаций. Всего: 151816
🔄 Запрос #1513 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 64 спецификаций. Всего: 151880
🔄 Запрос #1514 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 61 спецификаций. Всего: 151941
🔄 Запрос #1515 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 152019
🔄 Запрос #1516 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 77 спецификаций. Всего: 152096
🔄 Запрос #1517 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 71 спецификаций. Всего: 152167
🔄 Запрос #1518 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 152285
🔄 Запрос #1519 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 152382
🔄 Запрос #1520 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 137 спецификаций. Всего: 152519
🔄 Запрос #1521 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 152642
🔄 Запрос #1522 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 152762
🔄 Запрос #1523 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 152866
🔄 Запрос #1524 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 161 спецификаций. Всего: 153027
🔄 Запрос #1525 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 153133
🔄 Запрос #1526 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 153253
🔄 Запрос #1527 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 153310
🔄 Запрос #1528 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 153408
🔄 Запрос #1529 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 153512
🔄 Запрос #1530 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 153607
🔄 Запрос #1531 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 153729
🔄 Запрос #1532 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 69 спецификаций. Всего: 153798
🔄 Запрос #1533 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 153886
🔄 Запрос #1534 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 47 спецификаций. Всего: 153933
🔄 Запрос #1535 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 154011
🔄 Запрос #1536 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 39 спецификаций. Всего: 154050
🔄 Запрос #1537 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 47 спецификаций. Всего: 154097
🔄 Запрос #1538 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 154173
🔄 Запрос #1539 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 23 спецификаций. Всего: 154196
🔄 Запрос #1540 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 154289
🔄 Запрос #1541 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 75 спецификаций. Всего: 154364
🔄 Запрос #1542 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 65 спецификаций. Всего: 154429
🔄 Запрос #1543 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 154536
🔄 Запрос #1544 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 49 спецификаций. Всего: 154585
🔄 Запрос #1545 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 59 спецификаций. Всего: 154644
🔄 Запрос #1546 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 154731
🔄 Запрос #1547 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 154860
🔄 Запрос #1548 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 154943
🔄 Запрос #1549 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 155025
🔄 Запрос #1550 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 155125
🔄 Запрос #1551 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 155256
🔄 Запрос #1552 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 69 спецификаций. Всего: 155325
🔄 Запрос #1553 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 155438
🔄 Запрос #1554 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 50 спецификаций. Всего: 155488
🔄 Запрос #1555 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 25 спецификаций. Всего: 155513
🔄 Запрос #1556 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 140 спецификаций. Всего: 155653
🔄 Запрос #1557 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 57 спецификаций. Всего: 155710
🔄 Запрос #1558 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 155821
🔄 Запрос #1559 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 155922
🔄 Запрос #1560 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 156038
🔄 Запрос #1561 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 156126
🔄 Запрос #1562 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 156226
🔄 Запрос #1563 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 156343
🔄 Запрос #1564 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 156439
🔄 Запрос #1565 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 156529
🔄 Запрос #1566 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 156646
🔄 Запрос #1567 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 140 спецификаций. Всего: 156786
🔄 Запрос #1568 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 156862
🔄 Запрос #1569 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 50 спецификаций. Всего: 156912
🔄 Запрос #1570 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 157004
🔄 Запрос #1571 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 157098
🔄 Запрос #1572 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 36 спецификаций. Всего: 157134
🔄 Запрос #1573 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 52 спецификаций. Всего: 157186
🔄 Запрос #1574 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 157281
🔄 Запрос #1575 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 157375
🔄 Запрос #1576 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 69 спецификаций. Всего: 157444
🔄 Запрос #1577 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 26 спецификаций. Всего: 157470
🔄 Запрос #1578 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 157587
🔄 Запрос #1579 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 157681
🔄 Запрос #1580 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 157787
🔄 Запрос #1581 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 68 спецификаций. Всего: 157855

🔄 Запрос #1582 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 157948
🔄 Запрос #1583 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 158062
🔄 Запрос #1584 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 158148
🔄 Запрос #1585 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 158257
🔄 Запрос #1586 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 158369
🔄 Запрос #1587 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 69 спецификаций. Всего: 158438
🔄 Запрос #1588 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 158529
🔄 Запрос #1589 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 164 спецификаций. Всего: 158693
🔄 Запрос #1590 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 158815
🔄 Запрос #1591 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 158911
🔄 Запрос #1592 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 10 спецификаций. Всего: 158921
🔄 Запрос #1593 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 159036
🔄 Запрос #1594 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 14 спецификаций. Всего: 159050
🔄 Запрос #1595 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 159134
🔄 Запрос #1596 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 159250
🔄 Запрос #1597 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 159370
🔄 Запрос #1598 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 20 спецификаций. Всего: 159390
🔄 Запрос #1599 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 159491
🔄 Запрос #1600 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 159602
🔄 Запрос #1601 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 159727
🔄 Запрос #1602 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 141 спецификаций. Всего: 159868
🔄 Запрос #1603 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 95 спецификаций. Всего: 159963
🔄 Запрос #1604 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 0 спецификаций. Всего: 159963
🔄 Запрос #1605 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 62 спецификаций. Всего: 160025
🔄 Запрос #1606 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 160125
🔄 Запрос #1607 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 16 спецификаций. Всего: 160141
🔄 Запрос #1608 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 0 спецификаций. Всего: 160141
🔄 Запрос #1609 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 16 спецификаций. Всего: 160157
🔄 Запрос #1610 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 160288
🔄 Запрос #1611 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 160362
🔄 Запрос #1612 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 80 спецификаций. Всего: 160442
🔄 Запрос #1613 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 160557
🔄 Запрос #1614 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 64 спецификаций. Всего: 160621
🔄 Запрос #1615 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 60 спецификаций. Всего: 160681
🔄 Запрос #1616 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 71 спецификаций. Всего: 160752
🔄 Запрос #1617 для 2025-01-02 20:44:09 - 2025-01-09 20:44:09
📥 Загружено 84 спецификаций. Всего: 160836
📤 Сохранено 10082 записей в plans_data_spec\plans_combined_spec.parquet
📅 Обрабатываем диапазон 2024-12-26 20:44:09 - 2025-01-02 20:44:09 (попытка 1/5)
🔄 Запрос #1618 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 54 спецификаций. Всего: 160890
🔄 Запрос #1619 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 31 спецификаций. Всего: 160921
🔄 Запрос #1620 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 96 спецификаций. Всего: 161017
🔄 Запрос #1621 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 137 спецификаций. Всего: 161154
🔄 Запрос #1622 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 161218
🔄 Запрос #1623 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 98 спецификаций. Всего: 161316
🔄 Запрос #1624 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 149 спецификаций. Всего: 161465
🔄 Запрос #1625 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 161568
🔄 Запрос #1626 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 129 спецификаций. Всего: 161697
🔄 Запрос #1627 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 119 спецификаций. Всего: 161816
🔄 Запрос #1628 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 161868
🔄 Запрос #1629 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 115 спецификаций. Всего: 161983
🔄 Запрос #1630 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 102 спецификаций. Всего: 162085
🔄 Запрос #1631 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 25 спецификаций. Всего: 162110
🔄 Запрос #1632 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 28 спецификаций. Всего: 162138
🔄 Запрос #1633 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 70 спецификаций. Всего: 162208
🔄 Запрос #1634 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 162208
🔄 Запрос #1635 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 6 спецификаций. Всего: 162214
🔄 Запрос #1636 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 162293
🔄 Запрос #1637 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 145 спецификаций. Всего: 162438
🔄 Запрос #1638 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 162 спецификаций. Всего: 162600
🔄 Запрос #1639 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 127 спецификаций. Всего: 162727
🔄 Запрос #1640 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 159 спецификаций. Всего: 162886
🔄 Запрос #1641 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 166 спецификаций. Всего: 163052
🔄 Запрос #1642 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 163158
🔄 Запрос #1643 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 85 спецификаций. Всего: 163243
🔄 Запрос #1644 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 48 спецификаций. Всего: 163291
🔄 Запрос #1645 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 21 спецификаций. Всего: 163312
🔄 Запрос #1646 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 163418
🔄 Запрос #1647 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 100 спецификаций. Всего: 163518
🔄 Запрос #1648 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 95 спецификаций. Всего: 163613
🔄 Запрос #1649 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 109 спецификаций. Всего: 163722
🔄 Запрос #1650 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 163804
🔄 Запрос #1651 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 137 спецификаций. Всего: 163941
🔄 Запрос #1652 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 163994
🔄 Запрос #1653 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 30 спецификаций. Всего: 164024
🔄 Запрос #1654 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 164059
🔄 Запрос #1655 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09

📥 Загружено 37 спецификаций. Всего: 164096
🔄 Запрос #1656 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 19 спецификаций. Всего: 164115
🔄 Запрос #1657 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 164115
🔄 Запрос #1658 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 8 спецификаций. Всего: 164123
🔄 Запрос #1659 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 36 спецификаций. Всего: 164159
🔄 Запрос #1660 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 136 спецификаций. Всего: 164295
🔄 Запрос #1661 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 164387
🔄 Запрос #1662 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 164451
🔄 Запрос #1663 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 164526
🔄 Запрос #1664 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 43 спецификаций. Всего: 164569
🔄 Запрос #1665 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 44 спецификаций. Всего: 164613
🔄 Запрос #1666 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 70 спецификаций. Всего: 164683
🔄 Запрос #1667 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 164745
🔄 Запрос #1668 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 36 спецификаций. Всего: 164781
🔄 Запрос #1669 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 164845
🔄 Запрос #1670 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 56 спецификаций. Всего: 164901
🔄 Запрос #1671 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 39 спецификаций. Всего: 164940
🔄 Запрос #1672 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 57 спецификаций. Всего: 164997
🔄 Запрос #1673 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 26 спецификаций. Всего: 165023
🔄 Запрос #1674 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 10 спецификаций. Всего: 165033
🔄 Запрос #1675 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 165086
🔄 Запрос #1676 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 47 спецификаций. Всего: 165133
🔄 Запрос #1677 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 42 спецификаций. Всего: 165175
🔄 Запрос #1678 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 34 спецификаций. Всего: 165209
🔄 Запрос #1679 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 165284
🔄 Запрос #1680 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 51 спецификаций. Всего: 165335
🔄 Запрос #1681 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 165417
🔄 Запрос #1682 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 18 спецификаций. Всего: 165435
🔄 Запрос #1683 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 165487
🔄 Запрос #1684 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 56 спецификаций. Всего: 165543
🔄 Запрос #1685 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 46 спецификаций. Всего: 165589
🔄 Запрос #1686 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 42 спецификаций. Всего: 165631
🔄 Запрос #1687 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 67 спецификаций. Всего: 165698
🔄 Запрос #1688 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 165769
🔄 Запрос #1689 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 113 спецификаций. Всего: 165882
🔄 Запрос #1690 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 165960
🔄 Запрос #1691 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 63 спецификаций. Всего: 166023
🔄 Запрос #1692 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 80 спецификаций. Всего: 166103
🔄 Запрос #1693 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 166167
🔄 Запрос #1694 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 49 спецификаций. Всего: 166216
🔄 Запрос #1695 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 85 спецификаций. Всего: 166301
🔄 Запрос #1696 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 43 спецификаций. Всего: 166344
🔄 Запрос #1697 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 166449
🔄 Запрос #1698 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 166543
🔄 Запрос #1699 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 166644
🔄 Запрос #1700 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 166723
🔄 Запрос #1701 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 166817
🔄 Запрос #1702 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 166852
🔄 Запрос #1703 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 43 спецификаций. Всего: 166895
🔄 Запрос #1704 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 166992
🔄 Запрос #1705 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 167073
🔄 Запрос #1706 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 41 спецификаций. Всего: 167114
🔄 Запрос #1707 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 167114
🔄 Запрос #1708 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 167114
🔄 Запрос #1709 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 167187
🔄 Запрос #1710 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 13 спецификаций. Всего: 167200
🔄 Запрос #1711 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 2 спецификаций. Всего: 167202
🔄 Запрос #1712 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 167255
🔄 Запрос #1713 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 1 спецификаций. Всего: 167256
🔄 Запрос #1714 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 56 спецификаций. Всего: 167312
🔄 Запрос #1715 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 167347
🔄 Запрос #1716 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 45 спецификаций. Всего: 167392
🔄 Запрос #1717 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 167470
🔄 Запрос #1718 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 167575
🔄 Запрос #1719 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 88 спецификаций. Всего: 167663
🔄 Запрос #1720 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 167741
🔄 Запрос #1721 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 40 спецификаций. Всего: 167781
🔄 Запрос #1722 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 167886
🔄 Запрос #1723 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 118 спецификаций. Всего: 168004
🔄 Запрос #1724 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 168096
🔄 Запрос #1725 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 41 спецификаций. Всего: 168137
🔄 Запрос #1726 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 40 спецификаций. Всего: 168177
🔄 Запрос #1727 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 168271
🔄 Запрос #1728 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 123 спецификаций. Всего: 168394
🔄 Запрос #1729 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 61 спецификаций. Всего: 168455
🔄 Запрос #1730 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 50 спецификаций. Всего: 168505
🔄 Запрос #1731 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 168597

🔄 Запрос #1732 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 51 спецификаций. Всего: 168648
🔄 Запрос #1733 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 66 спецификаций. Всего: 168714
🔄 Запрос #1734 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 168811
🔄 Запрос #1735 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 168902
🔄 Запрос #1736 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 125 спецификаций. Всего: 169027
🔄 Запрос #1737 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 88 спецификаций. Всего: 169115
🔄 Запрос #1738 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 169205
🔄 Запрос #1739 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 28 спецификаций. Всего: 169233
🔄 Запрос #1740 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 169316
🔄 Запрос #1741 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 169369
🔄 Запрос #1742 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 50 спецификаций. Всего: 169419
🔄 Запрос #1743 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 169483
🔄 Запрос #1744 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 55 спецификаций. Всего: 169538
🔄 Запрос #1745 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 59 спецификаций. Всего: 169597
🔄 Запрос #1746 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 169672
🔄 Запрос #1747 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 51 спецификаций. Всего: 169723
🔄 Запрос #1748 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 24 спецификаций. Всего: 169747
🔄 Запрос #1749 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 5 спецификаций. Всего: 169752
🔄 Запрос #1750 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 4 спецификаций. Всего: 169756
🔄 Запрос #1751 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 13 спецификаций. Всего: 169769
🔄 Запрос #1752 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 67 спецификаций. Всего: 169836
🔄 Запрос #1753 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 57 спецификаций. Всего: 169893
🔄 Запрос #1754 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 169951
🔄 Запрос #1755 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 63 спецификаций. Всего: 170014
🔄 Запрос #1756 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 170092
🔄 Запрос #1757 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 107 спецификаций. Всего: 170199
🔄 Запрос #1758 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 170305
🔄 Запрос #1759 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 170411
🔄 Запрос #1760 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 170500
🔄 Запрос #1761 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 13 спецификаций. Всего: 170513
🔄 Запрос #1762 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 27 спецификаций. Всего: 170540
🔄 Запрос #1763 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 56 спецификаций. Всего: 170596
🔄 Запрос #1764 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 68 спецификаций. Всего: 170664
🔄 Запрос #1765 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 170746
🔄 Запрос #1766 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 170832
🔄 Запрос #1767 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 170919
📤 Сохранено 10083 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #1768 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 171018
🔄 Запрос #1769 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 88 спецификаций. Всего: 171106
🔄 Запрос #1770 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 171222
🔄 Запрос #1771 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 171286
🔄 Запрос #1772 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 116 спецификаций. Всего: 171402
🔄 Запрос #1773 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 171480
🔄 Запрос #1774 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 171577
🔄 Запрос #1775 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 171629
🔄 Запрос #1776 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 171702
🔄 Запрос #1777 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 171737
🔄 Запрос #1778 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 171816
🔄 Запрос #1779 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 109 спецификаций. Всего: 171925
🔄 Запрос #1780 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 119 спецификаций. Всего: 172044
🔄 Запрос #1781 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 121 спецификаций. Всего: 172165
🔄 Запрос #1782 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 172262
🔄 Запрос #1783 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 172370
🔄 Запрос #1784 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 119 спецификаций. Всего: 172489
🔄 Запрос #1785 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 172576
🔄 Запрос #1786 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 129 спецификаций. Всего: 172705
🔄 Запрос #1787 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 44 спецификаций. Всего: 172749
🔄 Запрос #1788 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 76 спецификаций. Всего: 172825
🔄 Запрос #1789 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 109 спецификаций. Всего: 172934
🔄 Запрос #1790 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 173040
🔄 Запрос #1791 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 38 спецификаций. Всего: 173078
🔄 Запрос #1792 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 3 спецификаций. Всего: 173081
🔄 Запрос #1793 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 173172
🔄 Запрос #1794 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 173245
🔄 Запрос #1795 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 110 спецификаций. Всего: 173355
🔄 Запрос #1796 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 137 спецификаций. Всего: 173492
🔄 Запрос #1797 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 55 спецификаций. Всего: 173547
🔄 Запрос #1798 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 173644
🔄 Запрос #1799 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 72 спецификаций. Всего: 173716
🔄 Запрос #1800 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 173819
🔄 Запрос #1801 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 173925
🔄 Запрос #1802 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 174047
🔄 Запрос #1803 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 174137
🔄 Запрос #1804 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 56 спецификаций. Всего: 174193
🔄 Запрос #1805 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 174279

🔄 Запрос #1806 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 127 спецификаций. Всего: 174406
🔄 Запрос #1807 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 142 спецификаций. Всего: 174548
🔄 Запрос #1808 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 29 спецификаций. Всего: 174577
🔄 Запрос #1809 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 26 спецификаций. Всего: 174603
🔄 Запрос #1810 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 174678
🔄 Запрос #1811 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 93 спецификаций. Всего: 174771
🔄 Запрос #1812 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 174833
🔄 Запрос #1813 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 174914
🔄 Запрос #1814 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 74 спецификаций. Всего: 174988
🔄 Запрос #1815 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 30 спецификаций. Всего: 175018
🔄 Запрос #1816 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 68 спецификаций. Всего: 175086
🔄 Запрос #1817 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 104 спецификаций. Всего: 175190
🔄 Запрос #1818 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 77 спецификаций. Всего: 175267
🔄 Запрос #1819 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 74 спецификаций. Всего: 175341
🔄 Запрос #1820 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 88 спецификаций. Всего: 175429
🔄 Запрос #1821 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 72 спецификаций. Всего: 175501
🔄 Запрос #1822 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 175570
🔄 Запрос #1823 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 175623
🔄 Запрос #1824 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 34 спецификаций. Всего: 175657
🔄 Запрос #1825 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 175715
🔄 Запрос #1826 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 175773
🔄 Запрос #1827 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 80 спецификаций. Всего: 175853
🔄 Запрос #1828 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 68 спецификаций. Всего: 175921
🔄 Запрос #1829 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 176011
🔄 Запрос #1830 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 46 спецификаций. Всего: 176057
🔄 Запрос #1831 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 176149
🔄 Запрос #1832 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 176235
🔄 Запрос #1833 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 43 спецификаций. Всего: 176278
🔄 Запрос #1834 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 55 спецификаций. Всего: 176333
🔄 Запрос #1835 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 67 спецификаций. Всего: 176400
🔄 Запрос #1836 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 176453
🔄 Запрос #1837 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 84 спецификаций. Всего: 176537
🔄 Запрос #1838 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 61 спецификаций. Всего: 176598
🔄 Запрос #1839 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 54 спецификаций. Всего: 176652
🔄 Запрос #1840 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 176741
🔄 Запрос #1841 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 77 спецификаций. Всего: 176818
🔄 Запрос #1842 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 45 спецификаций. Всего: 176863
🔄 Запрос #1843 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 61 спецификаций. Всего: 176924
🔄 Запрос #1844 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 72 спецификаций. Всего: 176996
🔄 Запрос #1845 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 49 спецификаций. Всего: 177045
🔄 Запрос #1846 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 177097
🔄 Запрос #1847 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 56 спецификаций. Всего: 177153
🔄 Запрос #1848 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 177215
🔄 Запрос #1849 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 40 спецификаций. Всего: 177255
🔄 Запрос #1850 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 45 спецификаций. Всего: 177300
🔄 Запрос #1851 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 29 спецификаций. Всего: 177329
🔄 Запрос #1852 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 39 спецификаций. Всего: 177368
🔄 Запрос #1853 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 49 спецификаций. Всего: 177417
🔄 Запрос #1854 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 177486
🔄 Запрос #1855 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 93 спецификаций. Всего: 177579
🔄 Запрос #1856 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 42 спецификаций. Всего: 177621
🔄 Запрос #1857 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 177720
🔄 Запрос #1858 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 38 спецификаций. Всего: 177758
🔄 Запрос #1859 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 12 спецификаций. Всего: 177770
🔄 Запрос #1860 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 18 спецификаций. Всего: 177788
🔄 Запрос #1861 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 9 спецификаций. Всего: 177797
🔄 Запрос #1862 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 8 спецификаций. Всего: 177805
🔄 Запрос #1863 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 10 спецификаций. Всего: 177815
🔄 Запрос #1864 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 6 спецификаций. Всего: 177821
🔄 Запрос #1865 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 5 спецификаций. Всего: 177826
🔄 Запрос #1866 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 39 спецификаций. Всего: 177865
🔄 Запрос #1867 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 49 спецификаций. Всего: 177914
🔄 Запрос #1868 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 50 спецификаций. Всего: 177964
🔄 Запрос #1869 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 178053
🔄 Запрос #1870 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 32 спецификаций. Всего: 178085
🔄 Запрос #1871 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 29 спецификаций. Всего: 178114
🔄 Запрос #1872 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 19 спецификаций. Всего: 178133
🔄 Запрос #1873 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 85 спецификаций. Всего: 178218
🔄 Запрос #1874 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 178296
🔄 Запрос #1875 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 128 спецификаций. Всего: 178424
🔄 Запрос #1876 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 113 спецификаций. Всего: 178537
🔄 Запрос #1877 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 178619
🔄 Запрос #1878 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 68 спецификаций. Всего: 178687
🔄 Запрос #1879 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 178758
🔄 Запрос #1880 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 93 спецификаций. Всего: 178851
🔄 Запрос #1881 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 178942
🔄 Запрос #1882 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 117 спецификаций. Всего: 179059
🔄 Запрос #1883 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 96 спецификаций. Всего: 179155
🔄 Запрос #1884 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 12 спецификаций. Всего: 179167
🔄 Запрос #1885 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 55 спецификаций. Всего: 179222
🔄 Запрос #1886 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 50 спецификаций. Всего: 179272
🔄 Запрос #1887 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 179330
🔄 Запрос #1888 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 119 спецификаций. Всего: 179449
🔄 Запрос #1889 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 136 спецификаций. Всего: 179585
🔄 Запрос #1890 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 179672
🔄 Запрос #1891 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 72 спецификаций. Всего: 179744
🔄 Запрос #1892 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 179825
🔄 Запрос #1893 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 179907
🔄 Запрос #1894 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 49 спецификаций. Всего: 179956
🔄 Запрос #1895 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 37 спецификаций. Всего: 179993
🔄 Запрос #1896 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 180096
🔄 Запрос #1897 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 96 спецификаций. Всего: 180192
🔄 Запрос #1898 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 41 спецификаций. Всего: 180233
🔄 Запрос #1899 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 16 спецификаций. Всего: 180249
🔄 Запрос #1900 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 41 спецификаций. Всего: 180290
🔄 Запрос #1901 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 180384
🔄 Запрос #1902 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 103 спецификаций. Всего: 180487
🔄 Запрос #1903 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 180573
🔄 Запрос #1904 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 180646
🔄 Запрос #1905 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 121 спецификаций. Всего: 180767
🔄 Запрос #1906 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 132 спецификаций. Всего: 180899
🔄 Запрос #1907 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 180970
📤 Сохранено 10051 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #1908 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 88 спецификаций. Всего: 181058
🔄 Запрос #1909 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 181147
🔄 Запрос #1910 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 181233
🔄 Запрос #1911 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 181336
🔄 Запрос #1912 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 181433
🔄 Запрос #1913 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 181525
🔄 Запрос #1914 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 181587
🔄 Запрос #1915 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 181678
🔄 Запрос #1916 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 80 спецификаций. Всего: 181758
🔄 Запрос #1917 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 114 спецификаций. Всего: 181872
🔄 Запрос #1918 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 181958
🔄 Запрос #1919 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 182040
🔄 Запрос #1920 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 182122
🔄 Запрос #1921 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 77 спецификаций. Всего: 182199
🔄 Запрос #1922 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 100 спецификаций. Всего: 182299
🔄 Запрос #1923 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 41 спецификаций. Всего: 182340
🔄 Запрос #1924 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 43 спецификаций. Всего: 182383
🔄 Запрос #1925 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 24 спецификаций. Всего: 182407
🔄 Запрос #1926 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 39 спецификаций. Всего: 182446
🔄 Запрос #1927 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 182510
🔄 Запрос #1928 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 171 спецификаций. Всего: 182681
🔄 Запрос #1929 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 124 спецификаций. Всего: 182805
🔄 Запрос #1930 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 182910
🔄 Запрос #1931 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 182993
🔄 Запрос #1932 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 183099
🔄 Запрос #1933 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 183161
🔄 Запрос #1934 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 122 спецификаций. Всего: 183283
🔄 Запрос #1935 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 142 спецификаций. Всего: 183425
🔄 Запрос #1936 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 56 спецификаций. Всего: 183481
🔄 Запрос #1937 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 183571
🔄 Запрос #1938 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 84 спецификаций. Всего: 183655
🔄 Запрос #1939 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 88 спецификаций. Всего: 183743
🔄 Запрос #1940 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 183837
🔄 Запрос #1941 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 43 спецификаций. Всего: 183880
🔄 Запрос #1942 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 76 спецификаций. Всего: 183956
🔄 Запрос #1943 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 184042
🔄 Запрос #1944 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 36 спецификаций. Всего: 184078
🔄 Запрос #1945 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 37 спецификаций. Всего: 184115
🔄 Запрос #1946 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 33 спецификаций. Всего: 184148
🔄 Запрос #1947 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 184212
🔄 Запрос #1948 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 84 спецификаций. Всего: 184296
🔄 Запрос #1949 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 39 спецификаций. Всего: 184335
🔄 Запрос #1950 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 56 спецификаций. Всего: 184391
🔄 Запрос #1951 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 51 спецификаций. Всего: 184442
🔄 Запрос #1952 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 138 спецификаций. Всего: 184580
🔄 Запрос #1953 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 104 спецификаций. Всего: 184684
🔄 Запрос #1954 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 184755
🔄 Запрос #1955 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 77 спецификаций. Всего: 184832
🔄 Запрос #1956 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09

📥 Загружено 31 спецификаций. Всего: 184863
🔄 Запрос #1957 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 184936
🔄 Запрос #1958 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 185027
🔄 Запрос #1959 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 34 спецификаций. Всего: 185061
🔄 Запрос #1960 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 185125
🔄 Запрос #1961 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 107 спецификаций. Всего: 185232
🔄 Запрос #1962 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 21 спецификаций. Всего: 185253
🔄 Запрос #1963 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 63 спецификаций. Всего: 185316
🔄 Запрос #1964 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 138 спецификаций. Всего: 185454
🔄 Запрос #1965 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 59 спецификаций. Всего: 185513
🔄 Запрос #1966 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 60 спецификаций. Всего: 185573
🔄 Запрос #1967 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 185635
🔄 Запрос #1968 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 48 спецификаций. Всего: 185683
🔄 Запрос #1969 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 54 спецификаций. Всего: 185737
🔄 Запрос #1970 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 60 спецификаций. Всего: 185797
🔄 Запрос #1971 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 57 спецификаций. Всего: 185854
🔄 Запрос #1972 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 80 спецификаций. Всего: 185934
🔄 Запрос #1973 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 185934
🔄 Запрос #1974 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 185969
🔄 Запрос #1975 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 186055
🔄 Запрос #1976 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 186130
🔄 Запрос #1977 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 186211
🔄 Запрос #1978 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 186302
🔄 Запрос #1979 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 186392
🔄 Запрос #1980 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 61 спецификаций. Всего: 186453
🔄 Запрос #1981 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 57 спецификаций. Всего: 186510
🔄 Запрос #1982 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 186618
🔄 Запрос #1983 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 186687
🔄 Запрос #1984 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 107 спецификаций. Всего: 186794
🔄 Запрос #1985 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 107 спецификаций. Всего: 186901
🔄 Запрос #1986 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 187007
🔄 Запрос #1987 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 102 спецификаций. Всего: 187109
🔄 Запрос #1988 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 187208
🔄 Запрос #1989 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 187289
🔄 Запрос #1990 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 187368
🔄 Запрос #1991 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 119 спецификаций. Всего: 187487
🔄 Запрос #1992 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 109 спецификаций. Всего: 187596
🔄 Запрос #1993 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 68 спецификаций. Всего: 187664
🔄 Запрос #1994 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 187739
🔄 Запрос #1995 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 187810
🔄 Запрос #1996 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 63 спецификаций. Всего: 187873
🔄 Запрос #1997 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 126 спецификаций. Всего: 187999
🔄 Запрос #1998 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 188077
🔄 Запрос #1999 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 188180
🔄 Запрос #2000 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 188279
🔄 Запрос #2001 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 188385
🔄 Запрос #2002 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 3 спецификаций. Всего: 188388
🔄 Запрос #2003 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 188450
🔄 Запрос #2004 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 147 спецификаций. Всего: 188597
🔄 Запрос #2005 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 109 спецификаций. Всего: 188706
🔄 Запрос #2006 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 188788
🔄 Запрос #2007 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 113 спецификаций. Всего: 188901
🔄 Запрос #2008 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 188992
🔄 Запрос #2009 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 189067
🔄 Запрос #2010 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 119 спецификаций. Всего: 189186
🔄 Запрос #2011 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 111 спецификаций. Всего: 189297
🔄 Запрос #2012 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 189359
🔄 Запрос #2013 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 93 спецификаций. Всего: 189452
🔄 Запрос #2014 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 17 спецификаций. Всего: 189469
🔄 Запрос #2015 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 189542
🔄 Запрос #2016 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 189632
🔄 Запрос #2017 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 76 спецификаций. Всего: 189708
🔄 Запрос #2018 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 50 спецификаций. Всего: 189758
🔄 Запрос #2019 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 189855
🔄 Запрос #2020 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 113 спецификаций. Всего: 189968
🔄 Запрос #2021 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 51 спецификаций. Всего: 190019
🔄 Запрос #2022 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 190113
🔄 Запрос #2023 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 76 спецификаций. Всего: 190189
🔄 Запрос #2024 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 190268
🔄 Запрос #2025 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 102 спецификаций. Всего: 190370
🔄 Запрос #2026 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 190428
🔄 Запрос #2027 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 78 спецификаций. Всего: 190506
🔄 Запрос #2028 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 190614
🔄 Запрос #2029 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 120 спецификаций. Всего: 190734
🔄 Запрос #2030 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 85 спецификаций. Всего: 190819
🔄 Запрос #2031 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 190902

🔄 Запрос #2032 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 142 спецификаций. Всего: 191044
📤 Сохранено 10074 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #2033 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 39 спецификаций. Всего: 191083
🔄 Запрос #2034 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 174 спецификаций. Всего: 191257
🔄 Запрос #2035 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 77 спецификаций. Всего: 191334
🔄 Запрос #2036 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 191433
🔄 Запрос #2037 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 145 спецификаций. Всего: 191578
🔄 Запрос #2038 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 76 спецификаций. Всего: 191654
🔄 Запрос #2039 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 85 спецификаций. Всего: 191739
🔄 Запрос #2040 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 191830
🔄 Запрос #2041 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 191927
🔄 Запрос #2042 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 93 спецификаций. Всего: 192020
🔄 Запрос #2043 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 115 спецификаций. Всего: 192135
🔄 Запрос #2044 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 192197
🔄 Запрос #2045 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 139 спецификаций. Всего: 192336
🔄 Запрос #2046 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 107 спецификаций. Всего: 192443
🔄 Запрос #2047 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 192533
🔄 Запрос #2048 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 192622
🔄 Запрос #2049 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 192714
🔄 Запрос #2050 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 117 спецификаций. Всего: 192831
🔄 Запрос #2051 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 5 спецификаций. Всего: 192836
🔄 Запрос #2052 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 2 спецификаций. Всего: 192838
🔄 Запрос #2053 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 51 спецификаций. Всего: 192889
🔄 Запрос #2054 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 146 спецификаций. Всего: 193035
🔄 Запрос #2055 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 131 спецификаций. Всего: 193166
🔄 Запрос #2056 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 193258
🔄 Запрос #2057 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 193316
🔄 Запрос #2058 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 193419
🔄 Запрос #2059 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 22 спецификаций. Всего: 193441
🔄 Запрос #2060 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 193493
🔄 Запрос #2061 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 47 спецификаций. Всего: 193540
🔄 Запрос #2062 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 3 спецификаций. Всего: 193543
🔄 Запрос #2063 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 27 спецификаций. Всего: 193570
🔄 Запрос #2064 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 60 спецификаций. Всего: 193630
🔄 Запрос #2065 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 193720
🔄 Запрос #2066 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 193755
🔄 Запрос #2067 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 24 спецификаций. Всего: 193779
🔄 Запрос #2068 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 57 спецификаций. Всего: 193836
🔄 Запрос #2069 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 46 спецификаций. Всего: 193882
🔄 Запрос #2070 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 40 спецификаций. Всего: 193922
🔄 Запрос #2071 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 10 спецификаций. Всего: 193932
🔄 Запрос #2072 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 44 спецификаций. Всего: 193976
🔄 Запрос #2073 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 48 спецификаций. Всего: 194024
🔄 Запрос #2074 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 59 спецификаций. Всего: 194083
🔄 Запрос #2075 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 194147
🔄 Запрос #2076 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 49 спецификаций. Всего: 194196
🔄 Запрос #2077 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 194277
🔄 Запрос #2078 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 46 спецификаций. Всего: 194323
🔄 Запрос #2079 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 59 спецификаций. Всего: 194382
🔄 Запрос #2080 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 63 спецификаций. Всего: 194445
🔄 Запрос #2081 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 194546
🔄 Запрос #2082 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 194643
🔄 Запрос #2083 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 57 спецификаций. Всего: 194700
🔄 Запрос #2084 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 194762
🔄 Запрос #2085 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 194837
🔄 Запрос #2086 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 194915
🔄 Запрос #2087 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 194977
🔄 Запрос #2088 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 195058
🔄 Запрос #2089 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 72 спецификаций. Всего: 195130
🔄 Запрос #2090 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 60 спецификаций. Всего: 195190
🔄 Запрос #2091 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 30 спецификаций. Всего: 195220
🔄 Запрос #2092 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 72 спецификаций. Всего: 195292
🔄 Запрос #2093 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 195371
🔄 Запрос #2094 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 195452
🔄 Запрос #2095 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 195525
🔄 Запрос #2096 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 48 спецификаций. Всего: 195573
🔄 Запрос #2097 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 4 спецификаций. Всего: 195577
🔄 Запрос #2098 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 48 спецификаций. Всего: 195625
🔄 Запрос #2099 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 63 спецификаций. Всего: 195688
🔄 Запрос #2100 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 42 спецификаций. Всего: 195730
🔄 Запрос #2101 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 88 спецификаций. Всего: 195818
🔄 Запрос #2102 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 85 спецификаций. Всего: 195903
🔄 Запрос #2103 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 61 спецификаций. Всего: 195964
🔄 Запрос #2104 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 196043
🔄 Запрос #2105 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 196151
🔄 Запрос #2106 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 92 спецификаций. Всего: 196243
🔄 Запрос #2107 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 196321
🔄 Запрос #2108 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 70 спецификаций. Всего: 196391
🔄 Запрос #2109 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 66 спецификаций. Всего: 196457
🔄 Запрос #2110 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 88 спецификаций. Всего: 196545
🔄 Запрос #2111 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 51 спецификаций. Всего: 196596
🔄 Запрос #2112 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 61 спецификаций. Всего: 196657
🔄 Запрос #2113 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 27 спецификаций. Всего: 196684
🔄 Запрос #2114 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 71 спецификаций. Всего: 196755
🔄 Запрос #2115 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 41 спецификаций. Всего: 196796
🔄 Запрос #2116 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 33 спецификаций. Всего: 196829
🔄 Запрос #2117 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 196887
🔄 Запрос #2118 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 196939
🔄 Запрос #2119 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 51 спецификаций. Всего: 196990
🔄 Запрос #2120 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 17 спецификаций. Всего: 197007
🔄 Запрос #2121 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 197059
🔄 Запрос #2122 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 57 спецификаций. Всего: 197116
🔄 Запрос #2123 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 68 спецификаций. Всего: 197184
🔄 Запрос #2124 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 44 спецификаций. Всего: 197228
🔄 Запрос #2125 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 197299
🔄 Запрос #2126 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 66 спецификаций. Всего: 197365
🔄 Запрос #2127 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 72 спецификаций. Всего: 197437
🔄 Запрос #2128 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 197499
🔄 Запрос #2129 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 77 спецификаций. Всего: 197576
🔄 Запрос #2130 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 41 спецификаций. Всего: 197617
🔄 Запрос #2131 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 65 спецификаций. Всего: 197682
🔄 Запрос #2132 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 20 спецификаций. Всего: 197702
🔄 Запрос #2133 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 17 спецификаций. Всего: 197719
🔄 Запрос #2134 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 77 спецификаций. Всего: 197796
🔄 Запрос #2135 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 45 спецификаций. Всего: 197841
🔄 Запрос #2136 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 60 спецификаций. Всего: 197901
🔄 Запрос #2137 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 47 спецификаций. Всего: 197948
🔄 Запрос #2138 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 197948
🔄 Запрос #2139 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 197948
🔄 Запрос #2140 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 41 спецификаций. Всего: 197989
🔄 Запрос #2141 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 55 спецификаций. Всего: 198044
🔄 Запрос #2142 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 198117
🔄 Запрос #2143 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 198175
🔄 Запрос #2144 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 88 спецификаций. Всего: 198263
🔄 Запрос #2145 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 198348
🔄 Запрос #2146 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 198401
🔄 Запрос #2147 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 198454
🔄 Запрос #2148 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 38 спецификаций. Всего: 198492
🔄 Запрос #2149 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 198565
🔄 Запрос #2150 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 198648
🔄 Запрос #2151 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 39 спецификаций. Всего: 198687
🔄 Запрос #2152 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 198722
🔄 Запрос #2153 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 198795
🔄 Запрос #2154 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 198894
🔄 Запрос #2155 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 198995
🔄 Запрос #2156 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 40 спецификаций. Всего: 199035
🔄 Запрос #2157 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 57 спецификаций. Всего: 199092
🔄 Запрос #2158 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 85 спецификаций. Всего: 199177
🔄 Запрос #2159 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 45 спецификаций. Всего: 199222
🔄 Запрос #2160 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 199280
🔄 Запрос #2161 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 78 спецификаций. Всего: 199358
🔄 Запрос #2162 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 84 спецификаций. Всего: 199442
🔄 Запрос #2163 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 80 спецификаций. Всего: 199522
🔄 Запрос #2164 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 199580
🔄 Запрос #2165 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 199659
🔄 Запрос #2166 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 42 спецификаций. Всего: 199701
🔄 Запрос #2167 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 40 спецификаций. Всего: 199741
🔄 Запрос #2168 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 199832
🔄 Запрос #2169 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 199894
🔄 Запрос #2170 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 43 спецификаций. Всего: 199937
🔄 Запрос #2171 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 199989
🔄 Запрос #2172 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 18 спецификаций. Всего: 200007
🔄 Запрос #2173 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 32 спецификаций. Всего: 200039
🔄 Запрос #2174 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 25 спецификаций. Всего: 200064
🔄 Запрос #2175 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 21 спецификаций. Всего: 200085
🔄 Запрос #2176 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 11 спецификаций. Всего: 200096
🔄 Запрос #2177 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 17 спецификаций. Всего: 200113
🔄 Запрос #2178 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 16 спецификаций. Всего: 200129
🔄 Запрос #2179 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 200129

🔄 Запрос #2180 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 200129
🔄 Запрос #2181 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 19 спецификаций. Всего: 200148
🔄 Запрос #2182 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 17 спецификаций. Всего: 200165
🔄 Запрос #2183 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 200217
🔄 Запрос #2184 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 34 спецификаций. Всего: 200251
🔄 Запрос #2185 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 80 спецификаций. Всего: 200331
🔄 Запрос #2186 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 41 спецификаций. Всего: 200372
🔄 Запрос #2187 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 38 спецификаций. Всего: 200410
🔄 Запрос #2188 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 200488
🔄 Запрос #2189 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 31 спецификаций. Всего: 200519
🔄 Запрос #2190 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 200554
🔄 Запрос #2191 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 21 спецификаций. Всего: 200575
🔄 Запрос #2192 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 5 спецификаций. Всего: 200580
🔄 Запрос #2193 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 24 спецификаций. Всего: 200604
🔄 Запрос #2194 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 31 спецификаций. Всего: 200635
🔄 Запрос #2195 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 31 спецификаций. Всего: 200666
🔄 Запрос #2196 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 88 спецификаций. Всего: 200754
🔄 Запрос #2197 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 200816
🔄 Запрос #2198 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 43 спецификаций. Всего: 200859
🔄 Запрос #2199 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 44 спецификаций. Всего: 200903
🔄 Запрос #2200 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 21 спецификаций. Всего: 200924
🔄 Запрос #2201 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 23 спецификаций. Всего: 200947
🔄 Запрос #2202 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 201016
🔄 Запрос #2203 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 201080
📤 Сохранено 10036 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #2204 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 85 спецификаций. Всего: 201165
🔄 Запрос #2205 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 37 спецификаций. Всего: 201202
🔄 Запрос #2206 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 201275
🔄 Запрос #2207 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 133 спецификаций. Всего: 201408
🔄 Запрос #2208 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 48 спецификаций. Всего: 201456
🔄 Запрос #2209 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 50 спецификаций. Всего: 201506
🔄 Запрос #2210 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 201558
🔄 Запрос #2211 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 12 спецификаций. Всего: 201570
🔄 Запрос #2212 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 8 спецификаций. Всего: 201578
🔄 Запрос #2213 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 201656
🔄 Запрос #2214 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 201727
🔄 Запрос #2215 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 70 спецификаций. Всего: 201797
🔄 Запрос #2216 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 67 спецификаций. Всего: 201864
🔄 Запрос #2217 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 201958
🔄 Запрос #2218 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 201958
🔄 Запрос #2219 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 66 спецификаций. Всего: 202024
🔄 Запрос #2220 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 202059
🔄 Запрос #2221 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 29 спецификаций. Всего: 202088
🔄 Запрос #2222 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 6 спецификаций. Всего: 202094
🔄 Запрос #2223 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 29 спецификаций. Всего: 202123
🔄 Запрос #2224 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 202210
🔄 Запрос #2225 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 76 спецификаций. Всего: 202286
🔄 Запрос #2226 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 66 спецификаций. Всего: 202352
🔄 Запрос #2227 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 200 спецификаций. Всего: 202552
🔄 Запрос #2228 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 117 спецификаций. Всего: 202669
🔄 Запрос #2229 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 202761
🔄 Запрос #2230 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 16 спецификаций. Всего: 202777
🔄 Запрос #2231 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 76 спецификаций. Всего: 202853
🔄 Запрос #2232 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 202934
🔄 Запрос #2233 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 93 спецификаций. Всего: 203027
🔄 Запрос #2234 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 61 спецификаций. Всего: 203088
🔄 Запрос #2235 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 203161
🔄 Запрос #2236 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 203232
🔄 Запрос #2237 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 70 спецификаций. Всего: 203302
🔄 Запрос #2238 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 95 спецификаций. Всего: 203397
🔄 Запрос #2239 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 203498
🔄 Запрос #2240 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 203577
🔄 Запрос #2241 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 38 спецификаций. Всего: 203615
🔄 Запрос #2242 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 203688
🔄 Запрос #2243 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 203740
🔄 Запрос #2244 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 31 спецификаций. Всего: 203771
🔄 Запрос #2245 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 203865
🔄 Запрос #2246 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 203934
🔄 Запрос #2247 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 40 спецификаций. Всего: 203974
🔄 Запрос #2248 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 42 спецификаций. Всего: 204016
🔄 Запрос #2249 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 72 спецификаций. Всего: 204088
🔄 Запрос #2250 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 55 спецификаций. Всего: 204143
🔄 Запрос #2251 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 115 спецификаций. Всего: 204258
🔄 Запрос #2252 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 123 спецификаций. Всего: 204381
🔄 Запрос #2253 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 119 спецификаций. Всего: 204500
🔄 Запрос #2254 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 204581
🔄 Запрос #2255 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 112 спецификаций. Всего: 204693
🔄 Запрос #2256 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09

📥 Загружено 99 спецификаций. Всего: 204792
🔄 Запрос #2257 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 204878
🔄 Запрос #2258 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 204969
🔄 Запрос #2259 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 205048
🔄 Запрос #2260 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 109 спецификаций. Всего: 205157
🔄 Запрос #2261 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 205239
🔄 Запрос #2262 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 95 спецификаций. Всего: 205334
🔄 Запрос #2263 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 23 спецификаций. Всего: 205357
🔄 Запрос #2264 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 77 спецификаций. Всего: 205434
🔄 Запрос #2265 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 50 спецификаций. Всего: 205484
🔄 Запрос #2266 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 39 спецификаций. Всего: 205523
🔄 Запрос #2267 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 32 спецификаций. Всего: 205555
🔄 Запрос #2268 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 29 спецификаций. Всего: 205584
🔄 Запрос #2269 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 31 спецификаций. Всего: 205615
🔄 Запрос #2270 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 100 спецификаций. Всего: 205715
🔄 Запрос #2271 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 134 спецификаций. Всего: 205849
🔄 Запрос #2272 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 123 спецификаций. Всего: 205972
🔄 Запрос #2273 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 90 спецификаций. Всего: 206062
🔄 Запрос #2274 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 68 спецификаций. Всего: 206130
🔄 Запрос #2275 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 107 спецификаций. Всего: 206237
🔄 Запрос #2276 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 206326
🔄 Запрос #2277 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 206408
🔄 Запрос #2278 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 60 спецификаций. Всего: 206468
🔄 Запрос #2279 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 206503
🔄 Запрос #2280 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 52 спецификаций. Всего: 206555
🔄 Запрос #2281 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 34 спецификаций. Всего: 206589
🔄 Запрос #2282 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 206694
🔄 Запрос #2283 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 206752
🔄 Запрос #2284 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 96 спецификаций. Всего: 206848
🔄 Запрос #2285 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 95 спецификаций. Всего: 206943
🔄 Запрос #2286 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 63 спецификаций. Всего: 207006
🔄 Запрос #2287 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 31 спецификаций. Всего: 207037
🔄 Запрос #2288 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 74 спецификаций. Всего: 207111
🔄 Запрос #2289 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 207200
🔄 Запрос #2290 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 93 спецификаций. Всего: 207293
🔄 Запрос #2291 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 207387
🔄 Запрос #2292 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 207456
🔄 Запрос #2293 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 207509
🔄 Запрос #2294 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 70 спецификаций. Всего: 207579
🔄 Запрос #2295 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 207695
🔄 Запрос #2296 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 95 спецификаций. Всего: 207790
🔄 Запрос #2297 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 52 спецификаций. Всего: 207842
🔄 Запрос #2298 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 207904
🔄 Запрос #2299 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 208005
🔄 Запрос #2300 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 66 спецификаций. Всего: 208071
🔄 Запрос #2301 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 208158
🔄 Запрос #2302 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 208240
🔄 Запрос #2303 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 38 спецификаций. Всего: 208278
🔄 Запрос #2304 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 208361
🔄 Запрос #2305 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 169 спецификаций. Всего: 208530
🔄 Запрос #2306 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 208633
🔄 Запрос #2307 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 208732
🔄 Запрос #2308 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 39 спецификаций. Всего: 208771
🔄 Запрос #2309 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 68 спецификаций. Всего: 208839
🔄 Запрос #2310 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 208925
🔄 Запрос #2311 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 209031
🔄 Запрос #2312 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 209117
🔄 Запрос #2313 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 209200
🔄 Запрос #2314 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 61 спецификаций. Всего: 209261
🔄 Запрос #2315 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 209350
🔄 Запрос #2316 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 209465
🔄 Запрос #2317 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 209555
🔄 Запрос #2318 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 57 спецификаций. Всего: 209612
🔄 Запрос #2319 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 114 спецификаций. Всего: 209726
🔄 Запрос #2320 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 209820
🔄 Запрос #2321 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 209873
🔄 Запрос #2322 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 23 спецификаций. Всего: 209896
🔄 Запрос #2323 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 25 спецификаций. Всего: 209921
🔄 Запрос #2324 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 47 спецификаций. Всего: 209968
🔄 Запрос #2325 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 31 спецификаций. Всего: 209999
🔄 Запрос #2326 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 28 спецификаций. Всего: 210027
🔄 Запрос #2327 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 210113
🔄 Запрос #2328 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 210210

🔄 Запрос #2329 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 126 спецификаций. Всего: 210336
🔄 Запрос #2330 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 210425
🔄 Запрос #2331 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 115 спецификаций. Всего: 210540
🔄 Запрос #2332 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 210602
🔄 Запрос #2333 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 9 спецификаций. Всего: 210611
🔄 Запрос #2334 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 19 спецификаций. Всего: 210630
🔄 Запрос #2335 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 210688
🔄 Запрос #2336 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 210767
🔄 Запрос #2337 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 59 спецификаций. Всего: 210826
🔄 Запрос #2338 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 52 спецификаций. Всего: 210878
🔄 Запрос #2339 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 210969
🔄 Запрос #2340 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 37 спецификаций. Всего: 211006
🔄 Запрос #2341 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 211102
📤 Сохранено 10022 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #2342 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 125 спецификаций. Всего: 211227
🔄 Запрос #2343 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 211326
🔄 Запрос #2344 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 100 спецификаций. Всего: 211426
🔄 Запрос #2345 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 125 спецификаций. Всего: 211551
🔄 Запрос #2346 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 149 спецификаций. Всего: 211700
🔄 Запрос #2347 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 211792
🔄 Запрос #2348 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 211873
🔄 Запрос #2349 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 211981
🔄 Запрос #2350 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 119 спецификаций. Всего: 212100
🔄 Запрос #2351 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 212181
🔄 Запрос #2352 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 98 спецификаций. Всего: 212279
🔄 Запрос #2353 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 104 спецификаций. Всего: 212383
🔄 Запрос #2354 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 212445
🔄 Запрос #2355 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 41 спецификаций. Всего: 212486
🔄 Запрос #2356 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 85 спецификаций. Всего: 212571
🔄 Запрос #2357 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 212646
🔄 Запрос #2358 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 212751
🔄 Запрос #2359 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 132 спецификаций. Всего: 212883
🔄 Запрос #2360 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 95 спецификаций. Всего: 212978
🔄 Запрос #2361 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 213070
🔄 Запрос #2362 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 77 спецификаций. Всего: 213147
🔄 Запрос #2363 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 113 спецификаций. Всего: 213260
🔄 Запрос #2364 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 213354
🔄 Запрос #2365 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 213462
🔄 Запрос #2366 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 213565
🔄 Запрос #2367 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 136 спецификаций. Всего: 213701
🔄 Запрос #2368 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 70 спецификаций. Всего: 213771
🔄 Запрос #2369 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 34 спецификаций. Всего: 213805
🔄 Запрос #2370 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 46 спецификаций. Всего: 213851
🔄 Запрос #2371 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 213959
🔄 Запрос #2372 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 91 спецификаций. Всего: 214050
🔄 Запрос #2373 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 107 спецификаций. Всего: 214157
🔄 Запрос #2374 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 44 спецификаций. Всего: 214201
🔄 Запрос #2375 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 31 спецификаций. Всего: 214232
🔄 Запрос #2376 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 70 спецификаций. Всего: 214302
🔄 Запрос #2377 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 214389
🔄 Запрос #2378 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 39 спецификаций. Всего: 214428
🔄 Запрос #2379 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 214481
🔄 Запрос #2380 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 93 спецификаций. Всего: 214574
🔄 Запрос #2381 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 214638
🔄 Запрос #2382 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 61 спецификаций. Всего: 214699
🔄 Запрос #2383 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 46 спецификаций. Всего: 214745
🔄 Запрос #2384 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 44 спецификаций. Всего: 214789
🔄 Запрос #2385 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 124 спецификаций. Всего: 214913
🔄 Запрос #2386 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 70 спецификаций. Всего: 214983
🔄 Запрос #2387 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 215054
🔄 Запрос #2388 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 56 спецификаций. Всего: 215110
🔄 Запрос #2389 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 55 спецификаций. Всего: 215165
🔄 Запрос #2390 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 215266
🔄 Запрос #2391 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 66 спецификаций. Всего: 215332
🔄 Запрос #2392 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 111 спецификаций. Всего: 215443
🔄 Запрос #2393 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 215521
🔄 Запрос #2394 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 215596
🔄 Запрос #2395 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 215697
🔄 Запрос #2396 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 215784
🔄 Запрос #2397 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 20 спецификаций. Всего: 215804
🔄 Запрос #2398 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 3 спецификаций. Всего: 215807
🔄 Запрос #2399 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 215888
🔄 Запрос #2400 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 129 спецификаций. Всего: 216017
🔄 Запрос #2401 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09

📥 Загружено 106 спецификаций. Всего: 216123
🔄 Запрос #2402 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 59 спецификаций. Всего: 216182
🔄 Запрос #2403 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 21 спецификаций. Всего: 216203
🔄 Запрос #2404 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 29 спецификаций. Всего: 216232
🔄 Запрос #2405 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 31 спецификаций. Всего: 216263
🔄 Запрос #2406 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 54 спецификаций. Всего: 216317
🔄 Запрос #2407 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 110 спецификаций. Всего: 216427
🔄 Запрос #2408 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 216496
🔄 Запрос #2409 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 216531
🔄 Запрос #2410 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 63 спецификаций. Всего: 216594
🔄 Запрос #2411 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 74 спецификаций. Всего: 216668
🔄 Запрос #2412 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 100 спецификаций. Всего: 216768
🔄 Запрос #2413 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 35 спецификаций. Всего: 216803
🔄 Запрос #2414 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 1 спецификаций. Всего: 216804
🔄 Запрос #2415 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 216804
🔄 Запрос #2416 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 1 спецификаций. Всего: 216805
🔄 Запрос #2417 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 181 спецификаций. Всего: 216986
🔄 Запрос #2418 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 217069
🔄 Запрос #2419 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 27 спецификаций. Всего: 217096
🔄 Запрос #2420 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 217182
🔄 Запрос #2421 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 38 спецификаций. Всего: 217220
🔄 Запрос #2422 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 22 спецификаций. Всего: 217242
🔄 Запрос #2423 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 140 спецификаций. Всего: 217382
🔄 Запрос #2424 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 217464
🔄 Запрос #2425 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 217553
🔄 Запрос #2426 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 44 спецификаций. Всего: 217597
🔄 Запрос #2427 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 57 спецификаций. Всего: 217654
🔄 Запрос #2428 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 48 спецификаций. Всего: 217702
🔄 Запрос #2429 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 217771
🔄 Запрос #2430 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 217833
🔄 Запрос #2431 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 217902
🔄 Запрос #2432 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 152 спецификаций. Всего: 218054
🔄 Запрос #2433 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 130 спецификаций. Всего: 218184
🔄 Запрос #2434 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 40 спецификаций. Всего: 218224
🔄 Запрос #2435 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 60 спецификаций. Всего: 218284
🔄 Запрос #2436 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 50 спецификаций. Всего: 218334
🔄 Запрос #2437 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 218392
🔄 Запрос #2438 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 65 спецификаций. Всего: 218457
🔄 Запрос #2439 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 218528
🔄 Запрос #2440 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 70 спецификаций. Всего: 218598
🔄 Запрос #2441 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 218706
🔄 Запрос #2442 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 218811
🔄 Запрос #2443 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 88 спецификаций. Всего: 218899
🔄 Запрос #2444 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 218993
🔄 Запрос #2445 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 96 спецификаций. Всего: 219089
🔄 Запрос #2446 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 219158
🔄 Запрос #2447 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 55 спецификаций. Всего: 219213
🔄 Запрос #2448 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 219282
🔄 Запрос #2449 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
📥 Загружено 43 спецификаций. Всего: 219325
🔄 Запрос #2450 для 2024-12-26 20:44:09 - 2025-01-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 90 спецификаций. Всего: 219415
📅 Обрабатываем диапазон 2024-12-19 20:44:09 - 2024-12-26 20:44:09 (попытка 1/5)
🔄 Запрос #2451 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 219478
🔄 Запрос #2452 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 219553
🔄 Запрос #2453 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 219641
🔄 Запрос #2454 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 219735
🔄 Запрос #2455 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 37 спецификаций. Всего: 219772
🔄 Запрос #2456 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 67 спецификаций. Всего: 219839
🔄 Запрос #2457 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 19 спецификаций. Всего: 219858
🔄 Запрос #2458 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 26 спецификаций. Всего: 219884
🔄 Запрос #2459 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 219967
🔄 Запрос #2460 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 52 спецификаций. Всего: 220019
🔄 Запрос #2461 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 220100
🔄 Запрос #2462 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 66 спецификаций. Всего: 220166
🔄 Запрос #2463 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 220259
🔄 Запрос #2464 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 47 спецификаций. Всего: 220306
🔄 Запрос #2465 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 220361
🔄 Запрос #2466 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 42 спецификаций. Всего: 220403
🔄 Запрос #2467 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 49 спецификаций. Всего: 220452
🔄 Запрос #2468 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 220538
🔄 Запрос #2469 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 220630
🔄 Запрос #2470 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 47 спецификаций. Всего: 220677
🔄 Запрос #2471 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 220767
🔄 Запрос #2472 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 220849
🔄 Запрос #2473 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 56 спецификаций. Всего: 220905
🔄 Запрос #2474 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 221001
🔄 Запрос #2475 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 34 спецификаций. Всего: 221035

🔄 Запрос #2476 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 23 спецификаций. Всего: 221058
🔄 Запрос #2477 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 221129
📤 Сохранено 10027 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #2478 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 221227
🔄 Запрос #2479 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 221306
🔄 Запрос #2480 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 221393
🔄 Запрос #2481 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 48 спецификаций. Всего: 221441
🔄 Запрос #2482 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 221511
🔄 Запрос #2483 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 221590
🔄 Запрос #2484 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 221685
🔄 Запрос #2485 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 221763
🔄 Запрос #2486 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 221867
🔄 Запрос #2487 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 39 спецификаций. Всего: 221906
🔄 Запрос #2488 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 222012
🔄 Запрос #2489 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 222101
🔄 Запрос #2490 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 222195
🔄 Запрос #2491 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 114 спецификаций. Всего: 222309
🔄 Запрос #2492 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 222388
🔄 Запрос #2493 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 56 спецификаций. Всего: 222444
🔄 Запрос #2494 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 41 спецификаций. Всего: 222485
🔄 Запрос #2495 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 222581
🔄 Запрос #2496 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 150 спецификаций. Всего: 222731
🔄 Запрос #2497 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 222806
🔄 Запрос #2498 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 222911
🔄 Запрос #2499 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 222992
🔄 Запрос #2500 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 223089
🔄 Запрос #2501 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 223195
🔄 Запрос #2502 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 223283
🔄 Запрос #2503 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 41 спецификаций. Всего: 223324
🔄 Запрос #2504 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 223405
🔄 Запрос #2505 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 223499
🔄 Запрос #2506 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 223580
🔄 Запрос #2507 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 223664
🔄 Запрос #2508 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 223776
🔄 Запрос #2509 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 223861
🔄 Запрос #2510 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 223931
🔄 Запрос #2511 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 224028
🔄 Запрос #2512 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 224115
🔄 Запрос #2513 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 224233
🔄 Запрос #2514 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 124 спецификаций. Всего: 224357
🔄 Запрос #2515 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 12 спецификаций. Всего: 224369
🔄 Запрос #2516 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 2 спецификаций. Всего: 224371
🔄 Запрос #2517 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 21 спецификаций. Всего: 224392
🔄 Запрос #2518 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 224487
🔄 Запрос #2519 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 224573
🔄 Запрос #2520 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 224652
🔄 Запрос #2521 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 224748
🔄 Запрос #2522 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 224866
🔄 Запрос #2523 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 34 спецификаций. Всего: 224900
🔄 Запрос #2524 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 224979
🔄 Запрос #2525 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 225067
🔄 Запрос #2526 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 77 спецификаций. Всего: 225144
🔄 Запрос #2527 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 225239
🔄 Запрос #2528 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 225349
🔄 Запрос #2529 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 225456
🔄 Запрос #2530 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 225536
🔄 Запрос #2531 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 225635
🔄 Запрос #2532 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 225726
🔄 Запрос #2533 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 225816
🔄 Запрос #2534 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 225919
🔄 Запрос #2535 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 226015
🔄 Запрос #2536 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 226087
🔄 Запрос #2537 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 226181
🔄 Запрос #2538 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 67 спецификаций. Всего: 226248
🔄 Запрос #2539 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 226344
🔄 Запрос #2540 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 226437
🔄 Запрос #2541 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 62 спецификаций. Всего: 226499
🔄 Запрос #2542 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 7 спецификаций. Всего: 226506
🔄 Запрос #2543 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 62 спецификаций. Всего: 226568
🔄 Запрос #2544 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 226681
🔄 Запрос #2545 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 226779
🔄 Запрос #2546 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 51 спецификаций. Всего: 226830
🔄 Запрос #2547 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 58 спецификаций. Всего: 226888
🔄 Запрос #2548 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 58 спецификаций. Всего: 226946
🔄 Запрос #2549 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 53 спецификаций. Всего: 226999
🔄 Запрос #2550 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 51 спецификаций. Всего: 227050

🔄 Запрос #2551 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 227141
🔄 Запрос #2552 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 227216
🔄 Запрос #2553 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 227279
🔄 Запрос #2554 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 227358
🔄 Запрос #2555 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 227430
🔄 Запрос #2556 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 227515
🔄 Запрос #2557 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 28 спецификаций. Всего: 227543
🔄 Запрос #2558 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 227614
🔄 Запрос #2559 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 19 спецификаций. Всего: 227633
🔄 Запрос #2560 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 227702
🔄 Запрос #2561 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 36 спецификаций. Всего: 227738
🔄 Запрос #2562 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 51 спецификаций. Всего: 227789
🔄 Запрос #2563 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 66 спецификаций. Всего: 227855
🔄 Запрос #2564 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 227934
🔄 Запрос #2565 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 228012
🔄 Запрос #2566 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 53 спецификаций. Всего: 228065
🔄 Запрос #2567 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 228155
🔄 Запрос #2568 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 228247
🔄 Запрос #2569 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 67 спецификаций. Всего: 228314
🔄 Запрос #2570 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 228392
🔄 Запрос #2571 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 228486
🔄 Запрос #2572 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 28 спецификаций. Всего: 228514
🔄 Запрос #2573 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 50 спецификаций. Всего: 228564
🔄 Запрос #2574 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 228639
🔄 Запрос #2575 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 120 спецификаций. Всего: 228759
🔄 Запрос #2576 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 66 спецификаций. Всего: 228825
🔄 Запрос #2577 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 125 спецификаций. Всего: 228950
🔄 Запрос #2578 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 174 спецификаций. Всего: 229124
🔄 Запрос #2579 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 123 спецификаций. Всего: 229247
🔄 Запрос #2580 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 229325
🔄 Запрос #2581 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 229404
🔄 Запрос #2582 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 59 спецификаций. Всего: 229463
🔄 Запрос #2583 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 229555
🔄 Запрос #2584 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 43 спецификаций. Всего: 229598
🔄 Запрос #2585 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 229669
🔄 Запрос #2586 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 229750
🔄 Запрос #2587 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 229838
🔄 Запрос #2588 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 30 спецификаций. Всего: 229868
🔄 Запрос #2589 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 229950
🔄 Запрос #2590 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 20 спецификаций. Всего: 229970
🔄 Запрос #2591 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 16 спецификаций. Всего: 229986
🔄 Запрос #2592 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 230076
🔄 Запрос #2593 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 230182
🔄 Запрос #2594 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 77 спецификаций. Всего: 230259
🔄 Запрос #2595 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 230341
🔄 Запрос #2596 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 120 спецификаций. Всего: 230461
🔄 Запрос #2597 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 230562
🔄 Запрос #2598 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 230655
🔄 Запрос #2599 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 77 спецификаций. Всего: 230732
🔄 Запрос #2600 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 230819
🔄 Запрос #2601 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 230921
🔄 Запрос #2602 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 231002
🔄 Запрос #2603 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 231057
🔄 Запрос #2604 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 231169
📤 Сохранено 10040 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #2605 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 231277
🔄 Запрос #2606 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 231349
🔄 Запрос #2607 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 231443
🔄 Запрос #2608 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 231542
🔄 Запрос #2609 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 231652
🔄 Запрос #2610 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 231768
🔄 Запрос #2611 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 231875
🔄 Запрос #2612 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 231945
🔄 Запрос #2613 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 62 спецификаций. Всего: 232007
🔄 Запрос #2614 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 232094
🔄 Запрос #2615 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 6 спецификаций. Всего: 232100
🔄 Запрос #2616 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 4 спецификаций. Всего: 232104
🔄 Запрос #2617 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 3 спецификаций. Всего: 232107
🔄 Запрос #2618 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 232202
🔄 Запрос #2619 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 232307
🔄 Запрос #2620 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 232375
🔄 Запрос #2621 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 9 спецификаций. Всего: 232384
🔄 Запрос #2622 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 61 спецификаций. Всего: 232445
🔄 Запрос #2623 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 40 спецификаций. Всего: 232485
🔄 Запрос #2624 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09

📥 Загружено 65 спецификаций. Всего: 232550
🔄 Запрос #2625 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 232652
🔄 Запрос #2626 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 232756
🔄 Запрос #2627 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 232838
🔄 Запрос #2628 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 29 спецификаций. Всего: 232867
🔄 Запрос #2629 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 232966
🔄 Запрос #2630 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 76 спецификаций. Всего: 233042
🔄 Запрос #2631 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 233097
🔄 Запрос #2632 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 59 спецификаций. Всего: 233156
🔄 Запрос #2633 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 74 спецификаций. Всего: 233230
🔄 Запрос #2634 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 159 спецификаций. Всего: 233389
🔄 Запрос #2635 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 14 спецификаций. Всего: 233403
🔄 Запрос #2636 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 3 спецификаций. Всего: 233406
🔄 Запрос #2637 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 27 спецификаций. Всего: 233433
🔄 Запрос #2638 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 66 спецификаций. Всего: 233499
🔄 Запрос #2639 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 76 спецификаций. Всего: 233575
🔄 Запрос #2640 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 37 спецификаций. Всего: 233612
🔄 Запрос #2641 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 233715
🔄 Запрос #2642 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 135 спецификаций. Всего: 233850
🔄 Запрос #2643 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 233921
🔄 Запрос #2644 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 76 спецификаций. Всего: 233997
🔄 Запрос #2645 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 234078
🔄 Запрос #2646 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 234163
🔄 Запрос #2647 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 26 спецификаций. Всего: 234189
🔄 Запрос #2648 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 66 спецификаций. Всего: 234255
🔄 Запрос #2649 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 52 спецификаций. Всего: 234307
🔄 Запрос #2650 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 60 спецификаций. Всего: 234367
🔄 Запрос #2651 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 234469
🔄 Запрос #2652 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 48 спецификаций. Всего: 234517
🔄 Запрос #2653 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 234581
🔄 Запрос #2654 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 234661
🔄 Запрос #2655 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 24 спецификаций. Всего: 234685
🔄 Запрос #2656 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 2 спецификаций. Всего: 234687
🔄 Запрос #2657 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 73 спецификаций. Всего: 234760
🔄 Запрос #2658 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 234841
🔄 Запрос #2659 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 15 спецификаций. Всего: 234856
🔄 Запрос #2660 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 234937
🔄 Запрос #2661 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 235016
🔄 Запрос #2662 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 235071
🔄 Запрос #2663 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 235154
🔄 Запрос #2664 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 235222
🔄 Запрос #2665 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 235310
🔄 Запрос #2666 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 235405
🔄 Запрос #2667 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 126 спецификаций. Всего: 235531
🔄 Запрос #2668 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 235624
🔄 Запрос #2669 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 235725
🔄 Запрос #2670 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 114 спецификаций. Всего: 235839
🔄 Запрос #2671 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 235925
🔄 Запрос #2672 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 236035
🔄 Запрос #2673 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 236118
🔄 Запрос #2674 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 43 спецификаций. Всего: 236161
🔄 Запрос #2675 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 59 спецификаций. Всего: 236220
🔄 Запрос #2676 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 236220
🔄 Запрос #2677 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 236289
🔄 Запрос #2678 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 34 спецификаций. Всего: 236323
🔄 Запрос #2679 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 236386
🔄 Запрос #2680 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 125 спецификаций. Всего: 236511
🔄 Запрос #2681 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 48 спецификаций. Всего: 236559
🔄 Запрос #2682 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 50 спецификаций. Всего: 236609
🔄 Запрос #2683 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 236680
🔄 Запрос #2684 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 67 спецификаций. Всего: 236747
🔄 Запрос #2685 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 236842
🔄 Запрос #2686 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 122 спецификаций. Всего: 236964
🔄 Запрос #2687 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 135 спецификаций. Всего: 237099
🔄 Запрос #2688 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 139 спецификаций. Всего: 237238
🔄 Запрос #2689 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 135 спецификаций. Всего: 237373
🔄 Запрос #2690 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 237464
🔄 Запрос #2691 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 237556
🔄 Запрос #2692 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 46 спецификаций. Всего: 237602
🔄 Запрос #2693 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 39 спецификаций. Всего: 237641
🔄 Запрос #2694 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 10 спецификаций. Всего: 237651
🔄 Запрос #2695 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 54 спецификаций. Всего: 237705
🔄 Запрос #2696 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 237769
🔄 Запрос #2697 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 135 спецификаций. Всего: 237904
🔄 Запрос #2698 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 237989
🔄 Запрос #2699 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 238074
🔄 Запрос #2700 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 52 спецификаций. Всего: 238126

🔄 Запрос #2701 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 238126
🔄 Запрос #2702 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 238126
🔄 Запрос #2703 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 238126
🔄 Запрос #2704 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 25 спецификаций. Всего: 238151
🔄 Запрос #2705 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 109 спецификаций. Всего: 238260
🔄 Запрос #2706 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 67 спецификаций. Всего: 238327
🔄 Запрос #2707 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 9 спецификаций. Всего: 238336
🔄 Запрос #2708 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 30 спецификаций. Всего: 238366
🔄 Запрос #2709 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 238449
🔄 Запрос #2710 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 238520
🔄 Запрос #2711 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 73 спецификаций. Всего: 238593
🔄 Запрос #2712 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 35 спецификаций. Всего: 238628
🔄 Запрос #2713 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 238628
🔄 Запрос #2714 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 238628
🔄 Запрос #2715 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 238628
🔄 Запрос #2716 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 1 спецификаций. Всего: 238629
🔄 Запрос #2717 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 1 спецификаций. Всего: 238630
🔄 Запрос #2718 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 238630
🔄 Запрос #2719 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 52 спецификаций. Всего: 238682
🔄 Запрос #2720 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 12 спецификаций. Всего: 238694
🔄 Запрос #2721 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 5 спецификаций. Всего: 238699
🔄 Запрос #2722 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 31 спецификаций. Всего: 238730
🔄 Запрос #2723 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 42 спецификаций. Всего: 238772
🔄 Запрос #2724 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 238859
🔄 Запрос #2725 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 115 спецификаций. Всего: 238974
🔄 Запрос #2726 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 43 спецификаций. Всего: 239017
🔄 Запрос #2727 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 14 спецификаций. Всего: 239031
🔄 Запрос #2728 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 76 спецификаций. Всего: 239107
🔄 Запрос #2729 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 123 спецификаций. Всего: 239230
🔄 Запрос #2730 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 239313
🔄 Запрос #2731 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 239408
🔄 Запрос #2732 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 239478
🔄 Запрос #2733 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 239583
🔄 Запрос #2734 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 239696
🔄 Запрос #2735 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 120 спецификаций. Всего: 239816
🔄 Запрос #2736 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 137 спецификаций. Всего: 239953
🔄 Запрос #2737 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 240061
🔄 Запрос #2738 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 11 спецификаций. Всего: 240072
🔄 Запрос #2739 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 17 спецификаций. Всего: 240089
🔄 Запрос #2740 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 240185
🔄 Запрос #2741 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 240282
🔄 Запрос #2742 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 240367
🔄 Запрос #2743 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 240438
🔄 Запрос #2744 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 126 спецификаций. Всего: 240564
🔄 Запрос #2745 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 29 спецификаций. Всего: 240593
🔄 Запрос #2746 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 240677
🔄 Запрос #2747 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 49 спецификаций. Всего: 240726
🔄 Запрос #2748 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 240842
🔄 Запрос #2749 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 240935
🔄 Запрос #2750 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 14 спецификаций. Всего: 240949
🔄 Запрос #2751 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 241029
🔄 Запрос #2752 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 241126
🔄 Запрос #2753 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 241214
📤 Сохранено 10045 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #2754 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 77 спецификаций. Всего: 241291
🔄 Запрос #2755 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 44 спецификаций. Всего: 241335
🔄 Запрос #2756 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 241422
🔄 Запрос #2757 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 66 спецификаций. Всего: 241488
🔄 Запрос #2758 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 241593
🔄 Запрос #2759 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 241690
🔄 Запрос #2760 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 241781
🔄 Запрос #2761 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 241889
🔄 Запрос #2762 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 109 спецификаций. Всего: 241998
🔄 Запрос #2763 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 117 спецификаций. Всего: 242115
🔄 Запрос #2764 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 242199
🔄 Запрос #2765 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 242301
🔄 Запрос #2766 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 242388
🔄 Запрос #2767 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 242488
🔄 Запрос #2768 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 242577
🔄 Запрос #2769 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 242668
🔄 Запрос #2770 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 60 спецификаций. Всего: 242728
🔄 Запрос #2771 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 122 спецификаций. Всего: 242850
🔄 Запрос #2772 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 34 спецификаций. Всего: 242884
🔄 Запрос #2773 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)

📥 Загружено 6 спецификаций. Всего: 242890
🔄 Запрос #2774 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 62 спецификаций. Всего: 242952
🔄 Запрос #2775 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 76 спецификаций. Всего: 243028
🔄 Запрос #2776 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 243118
🔄 Запрос #2777 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 45 спецификаций. Всего: 243163
🔄 Запрос #2778 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 109 спецификаций. Всего: 243272
🔄 Запрос #2779 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 243364
🔄 Запрос #2780 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 140 спецификаций. Всего: 243504
🔄 Запрос #2781 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 158 спецификаций. Всего: 243662
🔄 Запрос #2782 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 191 спецификаций. Всего: 243853
🔄 Запрос #2783 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 162 спецификаций. Всего: 244015
🔄 Запрос #2784 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 244102
🔄 Запрос #2785 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 142 спецификаций. Всего: 244244
🔄 Запрос #2786 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 73 спецификаций. Всего: 244317
🔄 Запрос #2787 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 76 спецификаций. Всего: 244393
🔄 Запрос #2788 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 11 спецификаций. Всего: 244404
🔄 Запрос #2789 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 244490
🔄 Запрос #2790 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 244576
🔄 Запрос #2791 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 244667
🔄 Запрос #2792 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 244755
🔄 Запрос #2793 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 244827
🔄 Запрос #2794 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 36 спецификаций. Всего: 244863
🔄 Запрос #2795 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 123 спецификаций. Всего: 244986
🔄 Запрос #2796 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 62 спецификаций. Всего: 245048
🔄 Запрос #2797 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 57 спецификаций. Всего: 245105
🔄 Запрос #2798 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 115 спецификаций. Всего: 245220
🔄 Запрос #2799 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 245330
🔄 Запрос #2800 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 245434
🔄 Запрос #2801 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 41 спецификаций. Всего: 245475
🔄 Запрос #2802 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 47 спецификаций. Всего: 245522
🔄 Запрос #2803 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 48 спецификаций. Всего: 245570
🔄 Запрос #2804 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 1 спецификаций. Всего: 245571
🔄 Запрос #2805 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 47 спецификаций. Всего: 245618
🔄 Запрос #2806 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 74 спецификаций. Всего: 245692
🔄 Запрос #2807 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 245787
🔄 Запрос #2808 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 245866
🔄 Запрос #2809 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 115 спецификаций. Всего: 245981
🔄 Запрос #2810 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 246068
🔄 Запрос #2811 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 246175
🔄 Запрос #2812 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 246272
🔄 Запрос #2813 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 246357
🔄 Запрос #2814 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 246441
🔄 Запрос #2815 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 246548
🔄 Запрос #2816 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 126 спецификаций. Всего: 246674
🔄 Запрос #2817 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 246784
🔄 Запрос #2818 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 57 спецификаций. Всего: 246841
🔄 Запрос #2819 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 29 спецификаций. Всего: 246870
🔄 Запрос #2820 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 246953
🔄 Запрос #2821 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 33 спецификаций. Всего: 246986
🔄 Запрос #2822 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 247077
🔄 Запрос #2823 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 12 спецификаций. Всего: 247089
🔄 Запрос #2824 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 247159
🔄 Запрос #2825 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 247228
🔄 Запрос #2826 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 111 спецификаций. Всего: 247339
🔄 Запрос #2827 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 247407
🔄 Запрос #2828 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 247490
🔄 Запрос #2829 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 247597
🔄 Запрос #2830 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 127 спецификаций. Всего: 247724
🔄 Запрос #2831 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 134 спецификаций. Всего: 247858
🔄 Запрос #2832 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 247940
🔄 Запрос #2833 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 60 спецификаций. Всего: 248000
🔄 Запрос #2834 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 73 спецификаций. Всего: 248073
🔄 Запрос #2835 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 248185
🔄 Запрос #2836 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 248281
🔄 Запрос #2837 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 248384
🔄 Запрос #2838 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 248488
🔄 Запрос #2839 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 26 спецификаций. Всего: 248514
🔄 Запрос #2840 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 111 спецификаций. Всего: 248625
🔄 Запрос #2841 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 57 спецификаций. Всего: 248682
🔄 Запрос #2842 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 60 спецификаций. Всего: 248742
🔄 Запрос #2843 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 8 спецификаций. Всего: 248750
🔄 Запрос #2844 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 248849
🔄 Запрос #2845 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 248953
🔄 Запрос #2846 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 41 спецификаций. Всего: 248994
🔄 Запрос #2847 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 150 спецификаций. Всего: 249144
🔄 Запрос #2848 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 126 спецификаций. Всего: 249270
🔄 Запрос #2849 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 73 спецификаций. Всего: 249343
🔄 Запрос #2850 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 249447

🔄 Запрос #2851 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 249536
🔄 Запрос #2852 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 249652
🔄 Запрос #2853 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 249753
🔄 Запрос #2854 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 249855
🔄 Запрос #2855 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 249949
🔄 Запрос #2856 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 250032
🔄 Запрос #2857 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 127 спецификаций. Всего: 250159
🔄 Запрос #2858 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 250260
🔄 Запрос #2859 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 121 спецификаций. Всего: 250381
🔄 Запрос #2860 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 120 спецификаций. Всего: 250501
🔄 Запрос #2861 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 250572
🔄 Запрос #2862 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 250658
🔄 Запрос #2863 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 250721
🔄 Запрос #2864 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 250818
🔄 Запрос #2865 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 250905
🔄 Запрос #2866 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 251009
🔄 Запрос #2867 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 251115
🔄 Запрос #2868 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 251202
🔄 Запрос #2869 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 251270
📤 Сохранено 10056 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #2870 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 251371
🔄 Запрос #2871 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 251469
🔄 Запрос #2872 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 251577
🔄 Запрос #2873 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 33 спецификаций. Всего: 251610
🔄 Запрос #2874 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 47 спецификаций. Всего: 251657
🔄 Запрос #2875 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 41 спецификаций. Всего: 251698
🔄 Запрос #2876 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 251761
🔄 Запрос #2877 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 251858
🔄 Запрос #2878 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 251970
🔄 Запрос #2879 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 137 спецификаций. Всего: 252107
🔄 Запрос #2880 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 252217
🔄 Запрос #2881 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 147 спецификаций. Всего: 252364
🔄 Запрос #2882 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 252452
🔄 Запрос #2883 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 43 спецификаций. Всего: 252495
🔄 Запрос #2884 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 109 спецификаций. Всего: 252604
🔄 Запрос #2885 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 252694
🔄 Запрос #2886 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 74 спецификаций. Всего: 252768
🔄 Запрос #2887 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 130 спецификаций. Всего: 252898
🔄 Запрос #2888 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 252988
🔄 Запрос #2889 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 253101
🔄 Запрос #2890 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 123 спецификаций. Всего: 253224
🔄 Запрос #2891 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 60 спецификаций. Всего: 253284
🔄 Запрос #2892 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 130 спецификаций. Всего: 253414
🔄 Запрос #2893 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 253517
🔄 Запрос #2894 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 253600
🔄 Запрос #2895 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 253706
🔄 Запрос #2896 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 253824
🔄 Запрос #2897 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 253921
🔄 Запрос #2898 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 17 спецификаций. Всего: 253938
🔄 Запрос #2899 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 143 спецификаций. Всего: 254081
🔄 Запрос #2900 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 254156
🔄 Запрос #2901 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 82 спецификаций. Всего: 254238
🔄 Запрос #2902 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 254331
🔄 Запрос #2903 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 254395
🔄 Запрос #2904 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 254481
🔄 Запрос #2905 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 142 спецификаций. Всего: 254623
🔄 Запрос #2906 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 151 спецификаций. Всего: 254774
🔄 Запрос #2907 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 254856
🔄 Запрос #2908 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 135 спецификаций. Всего: 254991
🔄 Запрос #2909 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 255109
🔄 Запрос #2910 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 255229
🔄 Запрос #2911 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 255328
🔄 Запрос #2912 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 255425
🔄 Запрос #2913 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 255526
🔄 Запрос #2914 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 255626
🔄 Запрос #2915 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 49 спецификаций. Всего: 255675
🔄 Запрос #2916 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 255781
🔄 Запрос #2917 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 120 спецификаций. Всего: 255901
🔄 Запрос #2918 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 76 спецификаций. Всего: 255977
🔄 Запрос #2919 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 74 спецификаций. Всего: 256051
🔄 Запрос #2920 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 256147
🔄 Запрос #2921 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 256236
🔄 Запрос #2922 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09

📥 Загружено 111 спецификаций. Всего: 256347
🔄 Запрос #2923 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 124 спецификаций. Всего: 256471
🔄 Запрос #2924 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 256576
🔄 Запрос #2925 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 256689
🔄 Запрос #2926 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 256783
🔄 Запрос #2927 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 256867
🔄 Запрос #2928 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 34 спецификаций. Всего: 256901
🔄 Запрос #2929 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 141 спецификаций. Всего: 257042
🔄 Запрос #2930 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 137 спецификаций. Всего: 257179
🔄 Запрос #2931 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 257265
🔄 Запрос #2932 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 257348
🔄 Запрос #2933 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 109 спецификаций. Всего: 257457
🔄 Запрос #2934 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 257512
🔄 Запрос #2935 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 257622
🔄 Запрос #2936 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 139 спецификаций. Всего: 257761
🔄 Запрос #2937 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 257877
🔄 Запрос #2938 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 119 спецификаций. Всего: 257996
🔄 Запрос #2939 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 258099
🔄 Запрос #2940 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 49 спецификаций. Всего: 258148
🔄 Запрос #2941 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 258232
🔄 Запрос #2942 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 258342
🔄 Запрос #2943 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 258438
🔄 Запрос #2944 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 258537
🔄 Запрос #2945 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 258632
🔄 Запрос #2946 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 258729
🔄 Запрос #2947 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 258798
🔄 Запрос #2948 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 61 спецификаций. Всего: 258859
🔄 Запрос #2949 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 258969
🔄 Запрос #2950 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 128 спецификаций. Всего: 259097
🔄 Запрос #2951 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 259205
🔄 Запрос #2952 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 259310
🔄 Запрос #2953 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 121 спецификаций. Всего: 259431
🔄 Запрос #2954 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 98 спецификаций. Всего: 259529
🔄 Запрос #2955 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 259601
🔄 Запрос #2956 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 259679
🔄 Запрос #2957 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 259779
🔄 Запрос #2958 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 139 спецификаций. Всего: 259918
🔄 Запрос #2959 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 260009
🔄 Запрос #2960 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 260112
🔄 Запрос #2961 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 115 спецификаций. Всего: 260227
🔄 Запрос #2962 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 260325
🔄 Запрос #2963 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 260428
🔄 Запрос #2964 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 74 спецификаций. Всего: 260502
🔄 Запрос #2965 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 260596
🔄 Запрос #2966 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 260693
🔄 Запрос #2967 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 98 спецификаций. Всего: 260791
🔄 Запрос #2968 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 260896
🔄 Запрос #2969 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 261004
🔄 Запрос #2970 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 130 спецификаций. Всего: 261134
🔄 Запрос #2971 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 261252
🔄 Запрос #2972 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 60 спецификаций. Всего: 261312
📤 Сохранено 10042 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #2973 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 261376
🔄 Запрос #2974 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 261486
🔄 Запрос #2975 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 261588
🔄 Запрос #2976 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 261652
🔄 Запрос #2977 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 261716
🔄 Запрос #2978 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 73 спецификаций. Всего: 261789
🔄 Запрос #2979 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 261852
🔄 Запрос #2980 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 261922
🔄 Запрос #2981 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 262014
🔄 Запрос #2982 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 262113
🔄 Запрос #2983 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 262188
🔄 Запрос #2984 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 262294
🔄 Запрос #2985 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 262378
🔄 Запрос #2986 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 53 спецификаций. Всего: 262431
🔄 Запрос #2987 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 37 спецификаций. Всего: 262468
🔄 Запрос #2988 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 262568
🔄 Запрос #2989 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 262660
🔄 Запрос #2990 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 262744
🔄 Запрос #2991 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 262829
🔄 Запрос #2992 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 25 спецификаций. Всего: 262854
🔄 Запрос #2993 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)

📥 Загружено 34 спецификаций. Всего: 262888
🔄 Запрос #2994 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 39 спецификаций. Всего: 262927
🔄 Запрос #2995 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 263029
🔄 Запрос #2996 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 263127
🔄 Запрос #2997 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 263217
🔄 Запрос #2998 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 76 спецификаций. Всего: 263293
🔄 Запрос #2999 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 263375
🔄 Запрос #3000 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 58 спецификаций. Всего: 263433
🔄 Запрос #3001 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 263501
🔄 Запрос #3002 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 263580
🔄 Запрос #3003 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 263663
🔄 Запрос #3004 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 263773
🔄 Запрос #3005 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 263870
🔄 Запрос #3006 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 263933
🔄 Запрос #3007 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 264039
🔄 Запрос #3008 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 264140
🔄 Запрос #3009 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 4 спецификаций. Всего: 264144
🔄 Запрос #3010 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 4 спецификаций. Всего: 264148
🔄 Запрос #3011 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 264219
🔄 Запрос #3012 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 172 спецификаций. Всего: 264391
🔄 Запрос #3013 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 115 спецификаций. Всего: 264506
🔄 Запрос #3014 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 264613
🔄 Запрос #3015 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 3 спецификаций. Всего: 264616
🔄 Запрос #3016 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 4 спецификаций. Всего: 264620
🔄 Запрос #3017 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 264710
🔄 Запрос #3018 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 264785
🔄 Запрос #3019 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 264865
🔄 Запрос #3020 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 264943
🔄 Запрос #3021 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 30 спецификаций. Всего: 264973
🔄 Запрос #3022 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 27 спецификаций. Всего: 265000
🔄 Запрос #3023 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 265100
🔄 Запрос #3024 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 66 спецификаций. Всего: 265166
🔄 Запрос #3025 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 10 спецификаций. Всего: 265176
🔄 Запрос #3026 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 47 спецификаций. Всего: 265223
🔄 Запрос #3027 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 265278
🔄 Запрос #3028 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 36 спецификаций. Всего: 265314
🔄 Запрос #3029 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 5 спецификаций. Всего: 265319
🔄 Запрос #3030 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 265374
🔄 Запрос #3031 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 57 спецификаций. Всего: 265431
🔄 Запрос #3032 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 138 спецификаций. Всего: 265569
🔄 Запрос #3033 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 65 спецификаций. Всего: 265634
🔄 Запрос #3034 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 66 спецификаций. Всего: 265700
🔄 Запрос #3035 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 162 спецификаций. Всего: 265862
🔄 Запрос #3036 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 265949
🔄 Запрос #3037 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 266017
🔄 Запрос #3038 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 266087
🔄 Запрос #3039 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 266175
🔄 Запрос #3040 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 59 спецификаций. Всего: 266234
🔄 Запрос #3041 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 266325
🔄 Запрос #3042 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 65 спецификаций. Всего: 266390
🔄 Запрос #3043 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 266497
🔄 Запрос #3044 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 266580
🔄 Запрос #3045 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 266668
🔄 Запрос #3046 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 266752
🔄 Запрос #3047 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 49 спецификаций. Всего: 266801
🔄 Запрос #3048 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 22 спецификаций. Всего: 266823
🔄 Запрос #3049 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 266912
🔄 Запрос #3050 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 267015
🔄 Запрос #3051 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 267110
🔄 Запрос #3052 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 267198
🔄 Запрос #3053 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 267305
🔄 Запрос #3054 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 267384
🔄 Запрос #3055 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 267463
🔄 Запрос #3056 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 267543
🔄 Запрос #3057 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 267642
🔄 Запрос #3058 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 267727
🔄 Запрос #3059 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 136 спецификаций. Всего: 267863
🔄 Запрос #3060 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 267968
🔄 Запрос #3061 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 128 спецификаций. Всего: 268096
🔄 Запрос #3062 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 268176
🔄 Запрос #3063 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 268257
🔄 Запрос #3064 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 59 спецификаций. Всего: 268316
🔄 Запрос #3065 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 268400
🔄 Запрос #3066 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 68 спецификаций. Всего: 268468
🔄 Запрос #3067 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 268566
🔄 Запрос #3068 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 73 спецификаций. Всего: 268639
🔄 Запрос #3069 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 74 спецификаций. Всего: 268713

🔄 Запрос #3070 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 268782
🔄 Запрос #3071 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 62 спецификаций. Всего: 268844
🔄 Запрос #3072 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 76 спецификаций. Всего: 268920
🔄 Запрос #3073 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 77 спецификаций. Всего: 268997
🔄 Запрос #3074 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 269094
🔄 Запрос #3075 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 134 спецификаций. Всего: 269228
🔄 Запрос #3076 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 269311
🔄 Запрос #3077 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 4 спецификаций. Всего: 269315
🔄 Запрос #3078 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 43 спецификаций. Всего: 269358
🔄 Запрос #3079 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 269446
🔄 Запрос #3080 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 269556
🔄 Запрос #3081 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 269659
🔄 Запрос #3082 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 269731
🔄 Запрос #3083 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 53 спецификаций. Всего: 269784
🔄 Запрос #3084 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 38 спецификаций. Всего: 269822
🔄 Запрос #3085 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 269901
🔄 Запрос #3086 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 270019
🔄 Запрос #3087 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 270113
🔄 Запрос #3088 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 270203
🔄 Запрос #3089 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 270298
🔄 Запрос #3090 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 270393
🔄 Запрос #3091 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 33 спецификаций. Всего: 270426
🔄 Запрос #3092 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 270529
🔄 Запрос #3093 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 31 спецификаций. Всего: 270560
🔄 Запрос #3094 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 16 спецификаций. Всего: 270576
🔄 Запрос #3095 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 133 спецификаций. Всего: 270709
🔄 Запрос #3096 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 60 спецификаций. Всего: 270769
🔄 Запрос #3097 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 270833
🔄 Запрос #3098 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 37 спецификаций. Всего: 270870
🔄 Запрос #3099 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 35 спецификаций. Всего: 270905
🔄 Запрос #3100 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 31 спецификаций. Всего: 270936
🔄 Запрос #3101 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 271016
🔄 Запрос #3102 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 47 спецификаций. Всего: 271063
🔄 Запрос #3103 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 271147
🔄 Запрос #3104 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 271227
🔄 Запрос #3105 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 139 спецификаций. Всего: 271366
📤 Сохранено 10054 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #3106 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 114 спецификаций. Всего: 271480
🔄 Запрос #3107 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 58 спецификаций. Всего: 271538
🔄 Запрос #3108 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 271623
🔄 Запрос #3109 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 271721
🔄 Запрос #3110 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 271819
🔄 Запрос #3111 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 271910
🔄 Запрос #3112 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 272004
🔄 Запрос #3113 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 272120
🔄 Запрос #3114 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 17 спецификаций. Всего: 272137
🔄 Запрос #3115 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 272226
🔄 Запрос #3116 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 272319
🔄 Запрос #3117 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 272390
🔄 Запрос #3118 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 272487
🔄 Запрос #3119 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 272595
🔄 Запрос #3120 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 135 спецификаций. Всего: 272730
🔄 Запрос #3121 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 272814
🔄 Запрос #3122 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 272878
🔄 Запрос #3123 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 45 спецификаций. Всего: 272923
🔄 Запрос #3124 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 59 спецификаций. Всего: 272982
🔄 Запрос #3125 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 273064
🔄 Запрос #3126 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 127 спецификаций. Всего: 273191
🔄 Запрос #3127 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 77 спецификаций. Всего: 273268
🔄 Запрос #3128 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 131 спецификаций. Всего: 273399
🔄 Запрос #3129 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 273474
🔄 Запрос #3130 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 123 спецификаций. Всего: 273597
🔄 Запрос #3131 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 273676
🔄 Запрос #3132 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 273794
🔄 Запрос #3133 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 273886
🔄 Запрос #3134 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 1 спецификаций. Всего: 273887
🔄 Запрос #3135 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 273969
🔄 Запрос #3136 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 274044
🔄 Запрос #3137 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 58 спецификаций. Всего: 274102
🔄 Запрос #3138 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 28 спецификаций. Всего: 274130
🔄 Запрос #3139 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 274198
🔄 Запрос #3140 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 74 спецификаций. Всего: 274272
🔄 Запрос #3141 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 274356
🔄 Запрос #3142 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 76 спецификаций. Всего: 274432
🔄 Запрос #3143 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 52 спецификаций. Всего: 274484

🔄 Запрос #3144 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 274578
🔄 Запрос #3145 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 274686
🔄 Запрос #3146 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 274778
🔄 Запрос #3147 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 274874
🔄 Запрос #3148 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 35 спецификаций. Всего: 274909
🔄 Запрос #3149 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 2 спецификаций. Всего: 274911
🔄 Запрос #3150 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 3 спецификаций. Всего: 274914
🔄 Запрос #3151 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 274914
🔄 Запрос #3152 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 275011
🔄 Запрос #3153 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 275118
🔄 Запрос #3154 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 275234
🔄 Запрос #3155 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 275337
🔄 Запрос #3156 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 275337
🔄 Запрос #3157 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 52 спецификаций. Всего: 275389
🔄 Запрос #3158 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 275444
🔄 Запрос #3159 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 42 спецификаций. Всего: 275486
🔄 Запрос #3160 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 275575
🔄 Запрос #3161 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 58 спецификаций. Всего: 275633
🔄 Запрос #3162 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 275735
🔄 Запрос #3163 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 275836
🔄 Запрос #3164 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 275925
🔄 Запрос #3165 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 276035
🔄 Запрос #3166 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 276135
🔄 Запрос #3167 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 147 спецификаций. Всего: 276282
🔄 Запрос #3168 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 73 спецификаций. Всего: 276355
🔄 Запрос #3169 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 276441
🔄 Запрос #3170 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 114 спецификаций. Всего: 276555
🔄 Запрос #3171 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 276654
🔄 Запрос #3172 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 109 спецификаций. Всего: 276763
🔄 Запрос #3173 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 276865
🔄 Запрос #3174 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 276978
🔄 Запрос #3175 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 277047
🔄 Запрос #3176 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 277142
🔄 Запрос #3177 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 67 спецификаций. Всего: 277209
🔄 Запрос #3178 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 42 спецификаций. Всего: 277251
🔄 Запрос #3179 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 277349
🔄 Запрос #3180 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 83 спецификаций. Всего: 277432
🔄 Запрос #3181 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 277527
🔄 Запрос #3182 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 277612
🔄 Запрос #3183 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 277707
🔄 Запрос #3184 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 277800
🔄 Запрос #3185 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 277900
🔄 Запрос #3186 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 277996
🔄 Запрос #3187 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 45 спецификаций. Всего: 278041
🔄 Запрос #3188 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 278131
🔄 Запрос #3189 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 31 спецификаций. Всего: 278162
🔄 Запрос #3190 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 59 спецификаций. Всего: 278221
🔄 Запрос #3191 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 278314
🔄 Запрос #3192 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 278403
🔄 Запрос #3193 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 278483
🔄 Запрос #3194 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 278572
🔄 Запрос #3195 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 278657
🔄 Запрос #3196 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 278732
🔄 Запрос #3197 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 53 спецификаций. Всего: 278785
🔄 Запрос #3198 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 278878
🔄 Запрос #3199 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 278990
🔄 Запрос #3200 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 279073
🔄 Запрос #3201 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 279185
🔄 Запрос #3202 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 279265
🔄 Запрос #3203 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 61 спецификаций. Всего: 279326
🔄 Запрос #3204 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 2 спецификаций. Всего: 279328
🔄 Запрос #3205 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 34 спецификаций. Всего: 279362
🔄 Запрос #3206 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 48 спецификаций. Всего: 279410
🔄 Запрос #3207 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 45 спецификаций. Всего: 279455
🔄 Запрос #3208 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 59 спецификаций. Всего: 279514
🔄 Запрос #3209 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 279611
🔄 Запрос #3210 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 279686
🔄 Запрос #3211 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 77 спецификаций. Всего: 279763
🔄 Запрос #3212 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 279848
🔄 Запрос #3213 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 279934
🔄 Запрос #3214 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 280026
🔄 Запрос #3215 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 73 спецификаций. Всего: 280099
🔄 Запрос #3216 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 5 спецификаций. Всего: 280104
🔄 Запрос #3217 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09

📥 Загружено 20 спецификаций. Всего: 280124
🔄 Запрос #3218 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 158 спецификаций. Всего: 280282
🔄 Запрос #3219 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 280371
🔄 Запрос #3220 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 62 спецификаций. Всего: 280433
🔄 Запрос #3221 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 28 спецификаций. Всего: 280461
🔄 Запрос #3222 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 280543
🔄 Запрос #3223 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 48 спецификаций. Всего: 280591
🔄 Запрос #3224 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 280659
🔄 Запрос #3225 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 17 спецификаций. Всего: 280676
🔄 Запрос #3226 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 280731
🔄 Запрос #3227 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 43 спецификаций. Всего: 280774
🔄 Запрос #3228 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 3 спецификаций. Всего: 280777
🔄 Запрос #3229 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 1 спецификаций. Всего: 280778
🔄 Запрос #3230 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 12 спецификаций. Всего: 280790
🔄 Запрос #3231 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 280908
🔄 Запрос #3232 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 280994
🔄 Запрос #3233 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 281077
🔄 Запрос #3234 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 281158
🔄 Запрос #3235 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 281236
🔄 Запрос #3236 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 34 спецификаций. Всего: 281270
🔄 Запрос #3237 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 281333
🔄 Запрос #3238 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 281403
📤 Сохранено 10037 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #3239 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 281484
🔄 Запрос #3240 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 281566
🔄 Запрос #3241 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 49 спецификаций. Всего: 281615
🔄 Запрос #3242 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 281713
🔄 Запрос #3243 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 62 спецификаций. Всего: 281775
🔄 Запрос #3244 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 26 спецификаций. Всего: 281801
🔄 Запрос #3245 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 281870
🔄 Запрос #3246 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 281961
🔄 Запрос #3247 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 282058
🔄 Запрос #3248 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 62 спецификаций. Всего: 282120
🔄 Запрос #3249 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 282175
🔄 Запрос #3250 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 282245
🔄 Запрос #3251 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 53 спецификаций. Всего: 282298
🔄 Запрос #3252 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 282388
🔄 Запрос #3253 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 282466
🔄 Запрос #3254 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 155 спецификаций. Всего: 282621
🔄 Запрос #3255 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 282689
🔄 Запрос #3256 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 37 спецификаций. Всего: 282726
🔄 Запрос #3257 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 282806
🔄 Запрос #3258 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 52 спецификаций. Всего: 282858
🔄 Запрос #3259 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 20 спецификаций. Всего: 282878
🔄 Запрос #3260 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 282961
🔄 Запрос #3261 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 283030
🔄 Запрос #3262 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 283093
🔄 Запрос #3263 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 283193
🔄 Запрос #3264 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 283263
🔄 Запрос #3265 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 65 спецификаций. Всего: 283328
🔄 Запрос #3266 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 77 спецификаций. Всего: 283405
🔄 Запрос #3267 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 61 спецификаций. Всего: 283466
🔄 Запрос #3268 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 7 спецификаций. Всего: 283473
🔄 Запрос #3269 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 283566
🔄 Запрос #3270 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 283668
🔄 Запрос #3271 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 283756
🔄 Запрос #3272 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 283811
🔄 Запрос #3273 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 283909
🔄 Запрос #3274 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 284001
🔄 Запрос #3275 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 138 спецификаций. Всего: 284139
🔄 Запрос #3276 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 284252
🔄 Запрос #3277 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 121 спецификаций. Всего: 284373
🔄 Запрос #3278 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 115 спецификаций. Всего: 284488
🔄 Запрос #3279 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 34 спецификаций. Всего: 284522
🔄 Запрос #3280 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 60 спецификаций. Всего: 284582
🔄 Запрос #3281 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 284677
🔄 Запрос #3282 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 284761
🔄 Запрос #3283 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 284868
🔄 Запрос #3284 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 284954
🔄 Запрос #3285 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 44 спецификаций. Всего: 284998
🔄 Запрос #3286 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 58 спецификаций. Всего: 285056
🔄 Запрос #3287 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 285135
🔄 Запрос #3288 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 285232
🔄 Запрос #3289 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 65 спецификаций. Всего: 285297
🔄 Запрос #3290 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 45 спецификаций. Всего: 285342
🔄 Запрос #3291 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 3 спецификаций. Всего: 285345
🔄 Запрос #3292 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 8 спецификаций. Всего: 285353
🔄 Запрос #3293 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09

📥 Загружено 69 спецификаций. Всего: 285422
🔄 Запрос #3294 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 13 спецификаций. Всего: 285435
🔄 Запрос #3295 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 7 спецификаций. Всего: 285442
🔄 Запрос #3296 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 115 спецификаций. Всего: 285557
🔄 Запрос #3297 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 65 спецификаций. Всего: 285622
🔄 Запрос #3298 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 60 спецификаций. Всего: 285682
🔄 Запрос #3299 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 52 спецификаций. Всего: 285734
🔄 Запрос #3300 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 62 спецификаций. Всего: 285796
🔄 Запрос #3301 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 25 спецификаций. Всего: 285821
🔄 Запрос #3302 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 285893
🔄 Запрос #3303 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 77 спецификаций. Всего: 285970
🔄 Запрос #3304 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 286070
🔄 Запрос #3305 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 58 спецификаций. Всего: 286128
🔄 Запрос #3306 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 286212
🔄 Запрос #3307 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 286282
🔄 Запрос #3308 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 286377
🔄 Запрос #3309 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 286447
🔄 Запрос #3310 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 286525
🔄 Запрос #3311 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 286613
🔄 Запрос #3312 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 13 спецификаций. Всего: 286626
🔄 Запрос #3313 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 286696
🔄 Запрос #3314 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 286760
🔄 Запрос #3315 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 4 спецификаций. Всего: 286764
🔄 Запрос #3316 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 37 спецификаций. Всего: 286801
🔄 Запрос #3317 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 2 спецификаций. Всего: 286803
🔄 Запрос #3318 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 3 спецификаций. Всего: 286806
🔄 Запрос #3319 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 57 спецификаций. Всего: 286863
🔄 Запрос #3320 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 286965
🔄 Запрос #3321 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 287058
🔄 Запрос #3322 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 287145
🔄 Запрос #3323 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 4 спецификаций. Всего: 287149
🔄 Запрос #3324 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 27 спецификаций. Всего: 287176
🔄 Запрос #3325 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 5 спецификаций. Всего: 287181
🔄 Запрос #3326 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 4 спецификаций. Всего: 287185
🔄 Запрос #3327 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 49 спецификаций. Всего: 287234
🔄 Запрос #3328 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 34 спецификаций. Всего: 287268
🔄 Запрос #3329 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 31 спецификаций. Всего: 287299
🔄 Запрос #3330 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 6 спецификаций. Всего: 287305
🔄 Запрос #3331 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 287389
🔄 Запрос #3332 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 77 спецификаций. Всего: 287466
🔄 Запрос #3333 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 287551
🔄 Запрос #3334 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 287652
🔄 Запрос #3335 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 287760
🔄 Запрос #3336 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 287864
🔄 Запрос #3337 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 127 спецификаций. Всего: 287991
🔄 Запрос #3338 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 288074
🔄 Запрос #3339 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 288144
🔄 Запрос #3340 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 288249
🔄 Запрос #3341 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 288320
🔄 Запрос #3342 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 288392
🔄 Запрос #3343 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 122 спецификаций. Всего: 288514
🔄 Запрос #3344 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 288600
🔄 Запрос #3345 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 288671
🔄 Запрос #3346 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 288741
🔄 Запрос #3347 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 31 спецификаций. Всего: 288772
🔄 Запрос #3348 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 27 спецификаций. Всего: 288799
🔄 Запрос #3349 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 121 спецификаций. Всего: 288920
🔄 Запрос #3350 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 288988
🔄 Запрос #3351 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 14 спецификаций. Всего: 289002
🔄 Запрос #3352 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 289002
🔄 Запрос #3353 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 29 спецификаций. Всего: 289031
🔄 Запрос #3354 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 15 спецификаций. Всего: 289046
🔄 Запрос #3355 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 8 спецификаций. Всего: 289054
🔄 Запрос #3356 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 37 спецификаций. Всего: 289091
🔄 Запрос #3357 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 81 спецификаций. Всего: 289172
🔄 Запрос #3358 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 46 спецификаций. Всего: 289218
🔄 Запрос #3359 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 32 спецификаций. Всего: 289250
🔄 Запрос #3360 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 50 спецификаций. Всего: 289300
🔄 Запрос #3361 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 289383
🔄 Запрос #3362 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 289492
🔄 Запрос #3363 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 289608
🔄 Запрос #3364 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 289715
🔄 Запрос #3365 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 289798
🔄 Запрос #3366 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09

📥 Загружено 88 спецификаций. Всего: 289886
🔄 Запрос #3367 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 289973
🔄 Запрос #3368 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 290045
🔄 Запрос #3369 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 290108
🔄 Запрос #3370 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 290190
🔄 Запрос #3371 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 57 спецификаций. Всего: 290247
🔄 Запрос #3372 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 67 спецификаций. Всего: 290314
🔄 Запрос #3373 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 290398
🔄 Запрос #3374 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 290477
🔄 Запрос #3375 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 290593
🔄 Запрос #3376 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 290693
🔄 Запрос #3377 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 290771
🔄 Запрос #3378 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 290843
🔄 Запрос #3379 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 290937
🔄 Запрос #3380 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 40 спецификаций. Всего: 290977
🔄 Запрос #3381 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 291080
🔄 Запрос #3382 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 291151
🔄 Запрос #3383 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 31 спецификаций. Всего: 291182
🔄 Запрос #3384 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 9 спецификаций. Всего: 291191
🔄 Запрос #3385 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 67 спецификаций. Всего: 291258
🔄 Запрос #3386 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 291330
🔄 Запрос #3387 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 291412
📤 Сохранено 10009 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #3388 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 291505
🔄 Запрос #3389 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 51 спецификаций. Всего: 291556
🔄 Запрос #3390 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 51 спецификаций. Всего: 291607
🔄 Запрос #3391 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 53 спецификаций. Всего: 291660
🔄 Запрос #3392 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 49 спецификаций. Всего: 291709
🔄 Запрос #3393 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 61 спецификаций. Всего: 291770
🔄 Запрос #3394 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 58 спецификаций. Всего: 291828
🔄 Запрос #3395 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 44 спецификаций. Всего: 291872
🔄 Запрос #3396 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 291872
🔄 Запрос #3397 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 29 спецификаций. Всего: 291901
🔄 Запрос #3398 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 291987
🔄 Запрос #3399 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 49 спецификаций. Всего: 292036
🔄 Запрос #3400 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 17 спецификаций. Всего: 292053
🔄 Запрос #3401 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 33 спецификаций. Всего: 292086
🔄 Запрос #3402 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 77 спецификаций. Всего: 292163
🔄 Запрос #3403 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 292246
🔄 Запрос #3404 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 66 спецификаций. Всего: 292312
🔄 Запрос #3405 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 292407
🔄 Запрос #3406 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 23 спецификаций. Всего: 292430
🔄 Запрос #3407 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 292499
🔄 Запрос #3408 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 43 спецификаций. Всего: 292542
🔄 Запрос #3409 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 292542
🔄 Запрос #3410 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 292627
🔄 Запрос #3411 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 44 спецификаций. Всего: 292671
🔄 Запрос #3412 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 292671
🔄 Запрос #3413 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 26 спецификаций. Всего: 292697
🔄 Запрос #3414 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 65 спецификаций. Всего: 292762
🔄 Запрос #3415 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 58 спецификаций. Всего: 292820
🔄 Запрос #3416 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 29 спецификаций. Всего: 292849
🔄 Запрос #3417 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 1 спецификаций. Всего: 292850
🔄 Запрос #3418 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 56 спецификаций. Всего: 292906
🔄 Запрос #3419 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 293010
🔄 Запрос #3420 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 293110
🔄 Запрос #3421 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 293201
🔄 Запрос #3422 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 293319
🔄 Запрос #3423 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 293391
🔄 Запрос #3424 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 293462
🔄 Запрос #3425 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 293554
🔄 Запрос #3426 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 293650
🔄 Запрос #3427 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 66 спецификаций. Всего: 293716
🔄 Запрос #3428 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 293813
🔄 Запрос #3429 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 130 спецификаций. Всего: 293943
🔄 Запрос #3430 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 294045
🔄 Запрос #3431 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 117 спецификаций. Всего: 294162
🔄 Запрос #3432 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 294272
🔄 Запрос #3433 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 294357
🔄 Запрос #3434 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 0 спецификаций. Всего: 294357
🔄 Запрос #3435 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 19 спецификаций. Всего: 294376
🔄 Запрос #3436 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 294431
🔄 Запрос #3437 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 38 спецификаций. Всего: 294469
🔄 Запрос #3438 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 294563
🔄 Запрос #3439 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 294664
🔄 Запрос #3440 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 294770
🔄 Запрос #3441 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09

📥 Загружено 102 спецификаций. Всего: 294872
🔄 Запрос #3442 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 294936
🔄 Запрос #3443 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 61 спецификаций. Всего: 294997
🔄 Запрос #3444 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 295072
🔄 Запрос #3445 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 295150
🔄 Запрос #3446 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 44 спецификаций. Всего: 295194
🔄 Запрос #3447 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 52 спецификаций. Всего: 295246
🔄 Запрос #3448 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 295324
🔄 Запрос #3449 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 295405
🔄 Запрос #3450 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 295504
🔄 Запрос #3451 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 131 спецификаций. Всего: 295635
🔄 Запрос #3452 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 166 спецификаций. Всего: 295801
🔄 Запрос #3453 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 295899
🔄 Запрос #3454 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 130 спецификаций. Всего: 296029
🔄 Запрос #3455 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 296137
🔄 Запрос #3456 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 296215
🔄 Запрос #3457 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 296312
🔄 Запрос #3458 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 296425
🔄 Запрос #3459 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 128 спецификаций. Всего: 296553
🔄 Запрос #3460 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 296653
🔄 Запрос #3461 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 296746
🔄 Запрос #3462 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 296814
🔄 Запрос #3463 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 4 спецификаций. Всего: 296818
🔄 Запрос #3464 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 11 спецификаций. Всего: 296829
🔄 Запрос #3465 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 66 спецификаций. Всего: 296895
🔄 Запрос #3466 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 296965
🔄 Запрос #3467 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 41 спецификаций. Всего: 297006
🔄 Запрос #3468 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 114 спецификаций. Всего: 297120
🔄 Запрос #3469 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 119 спецификаций. Всего: 297239
🔄 Запрос #3470 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 155 спецификаций. Всего: 297394
🔄 Запрос #3471 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 131 спецификаций. Всего: 297525
🔄 Запрос #3472 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 115 спецификаций. Всего: 297640
🔄 Запрос #3473 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 133 спецификаций. Всего: 297773
🔄 Запрос #3474 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 133 спецификаций. Всего: 297906
🔄 Запрос #3475 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 297992
🔄 Запрос #3476 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 123 спецификаций. Всего: 298115
🔄 Запрос #3477 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 127 спецификаций. Всего: 298242
🔄 Запрос #3478 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 298332
🔄 Запрос #3479 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 28 спецификаций. Всего: 298360
🔄 Запрос #3480 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 298470
🔄 Запрос #3481 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 134 спецификаций. Всего: 298604
🔄 Запрос #3482 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 124 спецификаций. Всего: 298728
🔄 Запрос #3483 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 298817
🔄 Запрос #3484 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 298911
🔄 Запрос #3485 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 57 спецификаций. Всего: 298968
🔄 Запрос #3486 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 10 спецификаций. Всего: 298978
🔄 Запрос #3487 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 7 спецификаций. Всего: 298985
🔄 Запрос #3488 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 39 спецификаций. Всего: 299024
🔄 Запрос #3489 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 299124
🔄 Запрос #3490 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 299211
🔄 Запрос #3491 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 299304
🔄 Запрос #3492 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 299406
🔄 Запрос #3493 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 299518
🔄 Запрос #3494 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 299626
🔄 Запрос #3495 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 299727
🔄 Запрос #3496 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 299830
🔄 Запрос #3497 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 40 спецификаций. Всего: 299870
🔄 Запрос #3498 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 6 спецификаций. Всего: 299876
🔄 Запрос #3499 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 299954
🔄 Запрос #3500 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 300056
🔄 Запрос #3501 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 300128
🔄 Запрос #3502 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 300217
🔄 Запрос #3503 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 300272
🔄 Запрос #3504 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 300327
🔄 Запрос #3505 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 300421
🔄 Запрос #3506 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 300503
🔄 Запрос #3507 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 300581
🔄 Запрос #3508 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 300673
🔄 Запрос #3509 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 62 спецификаций. Всего: 300735
🔄 Запрос #3510 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 300820
🔄 Запрос #3511 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 40 спецификаций. Всего: 300860
🔄 Запрос #3512 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 300953
🔄 Запрос #3513 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 74 спецификаций. Всего: 301027
🔄 Запрос #3514 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 74 спецификаций. Всего: 301101
🔄 Запрос #3515 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 301179

🔄 Запрос #3516 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 301282
🔄 Запрос #3517 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 301394
🔄 Запрос #3518 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 120 спецификаций. Всего: 301514
📤 Сохранено 10102 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #3519 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 301626
🔄 Запрос #3520 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 119 спецификаций. Всего: 301745
🔄 Запрос #3521 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 301844
🔄 Запрос #3522 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 301946
🔄 Запрос #3523 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 302010
🔄 Запрос #3524 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 64 спецификаций. Всего: 302074
🔄 Запрос #3525 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 57 спецификаций. Всего: 302131
🔄 Запрос #3526 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 302221
🔄 Запрос #3527 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 302327
🔄 Запрос #3528 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 55 спецификаций. Всего: 302382
🔄 Запрос #3529 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 302475
🔄 Запрос #3530 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 83 спецификаций. Всего: 302558
🔄 Запрос #3531 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 80 спецификаций. Всего: 302638
🔄 Запрос #3532 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 53 спецификаций. Всего: 302691
🔄 Запрос #3533 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 4 спецификаций. Всего: 302695
🔄 Запрос #3534 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 2 спецификаций. Всего: 302697
🔄 Запрос #3535 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 302804
🔄 Запрос #3536 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 50 спецификаций. Всего: 302854
🔄 Запрос #3537 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 67 спецификаций. Всего: 302921
🔄 Запрос #3538 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 26 спецификаций. Всего: 302947
🔄 Запрос #3539 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 2 спецификаций. Всего: 302949
🔄 Запрос #3540 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 61 спецификаций. Всего: 303010
🔄 Запрос #3541 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 303080
🔄 Запрос #3542 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 303173
🔄 Запрос #3543 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 303248
🔄 Запрос #3544 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 303327
🔄 Запрос #3545 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 66 спецификаций. Всего: 303393
🔄 Запрос #3546 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 303501
🔄 Запрос #3547 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 303587
🔄 Запрос #3548 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 303690
🔄 Запрос #3549 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 303786
🔄 Запрос #3550 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 57 спецификаций. Всего: 303843
🔄 Запрос #3551 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 303959
🔄 Запрос #3552 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 11 спецификаций. Всего: 303970
🔄 Запрос #3553 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 128 спецификаций. Всего: 304098
🔄 Запрос #3554 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 304182
🔄 Запрос #3555 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 124 спецификаций. Всего: 304306
🔄 Запрос #3556 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 304407
🔄 Запрос #3557 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 73 спецификаций. Всего: 304480
🔄 Запрос #3558 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 60 спецификаций. Всего: 304540
🔄 Запрос #3559 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 49 спецификаций. Всего: 304589
🔄 Запрос #3560 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 304681
🔄 Запрос #3561 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 304760
🔄 Запрос #3562 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 304867
🔄 Запрос #3563 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 304953
🔄 Запрос #3564 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 305059
🔄 Запрос #3565 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 305156
🔄 Запрос #3566 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 305227
🔄 Запрос #3567 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 305290
🔄 Запрос #3568 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 77 спецификаций. Всего: 305367
🔄 Запрос #3569 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 305436
🔄 Запрос #3570 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 120 спецификаций. Всего: 305556
🔄 Запрос #3571 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 57 спецификаций. Всего: 305613
🔄 Запрос #3572 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 139 спецификаций. Всего: 305752
🔄 Запрос #3573 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 305851
🔄 Запрос #3574 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 2 спецификаций. Всего: 305853
🔄 Запрос #3575 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 2 спецификаций. Всего: 305855
🔄 Запрос #3576 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 305961
🔄 Запрос #3577 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 306029
🔄 Запрос #3578 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 306115
🔄 Запрос #3579 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 76 спецификаций. Всего: 306191
🔄 Запрос #3580 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 306294
🔄 Запрос #3581 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 15 спецификаций. Всего: 306309
🔄 Запрос #3582 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 306417
🔄 Запрос #3583 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 306510
🔄 Запрос #3584 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 57 спецификаций. Всего: 306567
🔄 Запрос #3585 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 306649
🔄 Запрос #3586 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 144 спецификаций. Всего: 306793
🔄 Запрос #3587 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09

📥 Загружено 115 спецификаций. Всего: 306908
🔄 Запрос #3588 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 306994
🔄 Запрос #3589 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 307091
🔄 Запрос #3590 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 307169
🔄 Запрос #3591 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 114 спецификаций. Всего: 307283
🔄 Запрос #3592 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 307369
🔄 Запрос #3593 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 307473
🔄 Запрос #3594 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 67 спецификаций. Всего: 307540
🔄 Запрос #3595 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 125 спецификаций. Всего: 307665
🔄 Запрос #3596 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 307751
🔄 Запрос #3597 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 307820
🔄 Запрос #3598 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 54 спецификаций. Всего: 307874
🔄 Запрос #3599 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 307987
🔄 Запрос #3600 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 308080
🔄 Запрос #3601 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 308150
🔄 Запрос #3602 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 86 спецификаций. Всего: 308236
🔄 Запрос #3603 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 308338
🔄 Запрос #3604 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 308428
🔄 Запрос #3605 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 308536
🔄 Запрос #3606 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 48 спецификаций. Всего: 308584
🔄 Запрос #3607 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 29 спецификаций. Всего: 308613
🔄 Запрос #3608 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 48 спецификаций. Всего: 308661
🔄 Запрос #3609 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 72 спецификаций. Всего: 308733
🔄 Запрос #3610 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 308811
🔄 Запрос #3611 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 63 спецификаций. Всего: 308874
🔄 Запрос #3612 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 308955
🔄 Запрос #3613 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 309053
🔄 Запрос #3614 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 309165
🔄 Запрос #3615 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 309257
🔄 Запрос #3616 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 309359
🔄 Запрос #3617 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 109 спецификаций. Всего: 309468
🔄 Запрос #3618 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 75 спецификаций. Всего: 309543
🔄 Запрос #3619 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 145 спецификаций. Всего: 309688
🔄 Запрос #3620 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 309794
🔄 Запрос #3621 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 309902
🔄 Запрос #3622 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 309972
🔄 Запрос #3623 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 310060
🔄 Запрос #3624 для 2024-12-19 20:44:09 - 2024-12-26 20:44:09
📥 Загружено 25 спецификаций. Всего: 310085
📅 Обрабатываем диапазон 2024-12-12 20:44:09 - 2024-12-19 20:44:09 (попытка 1/5)
🔄 Запрос #3625 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 310183
🔄 Запрос #3626 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 143 спецификаций. Всего: 310326
🔄 Запрос #3627 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 310428
🔄 Запрос #3628 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 21 спецификаций. Всего: 310449
🔄 Запрос #3629 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 310560
🔄 Запрос #3630 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 310687
🔄 Запрос #3631 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 52 спецификаций. Всего: 310739
🔄 Запрос #3632 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 78 спецификаций. Всего: 310817
🔄 Запрос #3633 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 137 спецификаций. Всего: 310954
🔄 Запрос #3634 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 142 спецификаций. Всего: 311096
🔄 Запрос #3635 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 117 спецификаций. Всего: 311213
🔄 Запрос #3636 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 120 спецификаций. Всего: 311333
🔄 Запрос #3637 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 130 спецификаций. Всего: 311463
🔄 Запрос #3638 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 143 спецификаций. Всего: 311606
📤 Сохранено 10092 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #3639 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 126 спецификаций. Всего: 311732
🔄 Запрос #3640 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 311843
🔄 Запрос #3641 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 131 спецификаций. Всего: 311974
🔄 Запрос #3642 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 312093
🔄 Запрос #3643 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 117 спецификаций. Всего: 312210
🔄 Запрос #3644 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 312315
🔄 Запрос #3645 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 113 спецификаций. Всего: 312428
🔄 Запрос #3646 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 312539
🔄 Запрос #3647 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 49 спецификаций. Всего: 312588
🔄 Запрос #3648 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 312683
🔄 Запрос #3649 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 24 спецификаций. Всего: 312707
🔄 Запрос #3650 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 31 спецификаций. Всего: 312738
🔄 Запрос #3651 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 33 спецификаций. Всего: 312771
🔄 Запрос #3652 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 60 спецификаций. Всего: 312831
🔄 Запрос #3653 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 122 спецификаций. Всего: 312953
🔄 Запрос #3654 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 10 спецификаций. Всего: 312963
🔄 Запрос #3655 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 313077
🔄 Запрос #3656 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 313185
🔄 Запрос #3657 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 120 спецификаций. Всего: 313305
🔄 Запрос #3658 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 313406
🔄 Запрос #3659 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 40 спецификаций. Всего: 313446
🔄 Запрос #3660 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 118 спецификаций. Всего: 313564
🔄 Запрос #3661 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 313672
🔄 Запрос #3662 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 313791
🔄 Запрос #3663 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09

📥 Загружено 118 спецификаций. Всего: 313909
🔄 Запрос #3664 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 314007
🔄 Запрос #3665 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 314106
🔄 Запрос #3666 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 44 спецификаций. Всего: 314150
🔄 Запрос #3667 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 75 спецификаций. Всего: 314225
🔄 Запрос #3668 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 124 спецификаций. Всего: 314349
🔄 Запрос #3669 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 21 спецификаций. Всего: 314370
🔄 Запрос #3670 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 93 спецификаций. Всего: 314463
🔄 Запрос #3671 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 314561
🔄 Запрос #3672 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 104 спецификаций. Всего: 314665
🔄 Запрос #3673 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 144 спецификаций. Всего: 314809
🔄 Запрос #3674 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 94 спецификаций. Всего: 314903
🔄 Запрос #3675 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 72 спецификаций. Всего: 314975
🔄 Запрос #3676 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 315091
🔄 Запрос #3677 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 94 спецификаций. Всего: 315185
🔄 Запрос #3678 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 77 спецификаций. Всего: 315262
🔄 Запрос #3679 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 100 спецификаций. Всего: 315362
🔄 Запрос #3680 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 39 спецификаций. Всего: 315401
🔄 Запрос #3681 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 3 спецификаций. Всего: 315404
🔄 Запрос #3682 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 0 спецификаций. Всего: 315404
🔄 Запрос #3683 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 6 спецификаций. Всего: 315410
🔄 Запрос #3684 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 1 спецификаций. Всего: 315411
🔄 Запрос #3685 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 4 спецификаций. Всего: 315415
🔄 Запрос #3686 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 2 спецификаций. Всего: 315417
🔄 Запрос #3687 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 6 спецификаций. Всего: 315423
🔄 Запрос #3688 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 0 спецификаций. Всего: 315423
🔄 Запрос #3689 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 4 спецификаций. Всего: 315427
🔄 Запрос #3690 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 6 спецификаций. Всего: 315433
🔄 Запрос #3691 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 19 спецификаций. Всего: 315452
🔄 Запрос #3692 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 315560
🔄 Запрос #3693 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 38 спецификаций. Всего: 315598
🔄 Запрос #3694 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 315709
🔄 Запрос #3695 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 93 спецификаций. Всего: 315802
🔄 Запрос #3696 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 117 спецификаций. Всего: 315919
🔄 Запрос #3697 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 316014
🔄 Запрос #3698 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 75 спецификаций. Всего: 316089
🔄 Запрос #3699 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 65 спецификаций. Всего: 316154
🔄 Запрос #3700 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 88 спецификаций. Всего: 316242
🔄 Запрос #3701 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 316344
🔄 Запрос #3702 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 129 спецификаций. Всего: 316473
🔄 Запрос #3703 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 316575
🔄 Запрос #3704 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 75 спецификаций. Всего: 316650
🔄 Запрос #3705 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 33 спецификаций. Всего: 316683
🔄 Запрос #3706 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 48 спецификаций. Всего: 316731
🔄 Запрос #3707 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 72 спецификаций. Всего: 316803
🔄 Запрос #3708 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 34 спецификаций. Всего: 316837
🔄 Запрос #3709 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 8 спецификаций. Всего: 316845
🔄 Запрос #3710 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 316950
🔄 Запрос #3711 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 317035
🔄 Запрос #3712 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 317120
🔄 Запрос #3713 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 317225
🔄 Запрос #3714 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 317330
🔄 Запрос #3715 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 88 спецификаций. Всего: 317418
🔄 Запрос #3716 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 10 спецификаций. Всего: 317428
🔄 Запрос #3717 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 40 спецификаций. Всего: 317468
🔄 Запрос #3718 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 94 спецификаций. Всего: 317562
🔄 Запрос #3719 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 317676
🔄 Запрос #3720 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 317766
🔄 Запрос #3721 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 81 спецификаций. Всего: 317847
🔄 Запрос #3722 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 124 спецификаций. Всего: 317971
🔄 Запрос #3723 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 100 спецификаций. Всего: 318071
🔄 Запрос #3724 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 135 спецификаций. Всего: 318206
🔄 Запрос #3725 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 82 спецификаций. Всего: 318288
🔄 Запрос #3726 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 318406
🔄 Запрос #3727 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 118 спецификаций. Всего: 318524
🔄 Запрос #3728 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 57 спецификаций. Всего: 318581
🔄 Запрос #3729 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 318684
🔄 Запрос #3730 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 77 спецификаций. Всего: 318761
🔄 Запрос #3731 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 318859
🔄 Запрос #3732 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 318957
🔄 Запрос #3733 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 49 спецификаций. Всего: 319006
🔄 Запрос #3734 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 94 спецификаций. Всего: 319100
🔄 Запрос #3735 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09

📥 Загружено 63 спецификаций. Всего: 319163
🔄 Запрос #3736 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 122 спецификаций. Всего: 319285
🔄 Запрос #3737 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 319391
🔄 Запрос #3738 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 73 спецификаций. Всего: 319464
🔄 Запрос #3739 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 319563
🔄 Запрос #3740 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 124 спецификаций. Всего: 319687
🔄 Запрос #3741 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 96 спецификаций. Всего: 319783
🔄 Запрос #3742 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 319886
🔄 Запрос #3743 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 136 спецификаций. Всего: 320022
🔄 Запрос #3744 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 320130
🔄 Запрос #3745 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 118 спецификаций. Всего: 320248
🔄 Запрос #3746 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 320358
🔄 Запрос #3747 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 84 спецификаций. Всего: 320442
🔄 Запрос #3748 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 121 спецификаций. Всего: 320563
🔄 Запрос #3749 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 49 спецификаций. Всего: 320612
🔄 Запрос #3750 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 1 спецификаций. Всего: 320613
🔄 Запрос #3751 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 61 спецификаций. Всего: 320674
🔄 Запрос #3752 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 80 спецификаций. Всего: 320754
🔄 Запрос #3753 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 117 спецификаций. Всего: 320871
🔄 Запрос #3754 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 134 спецификаций. Всего: 321005
🔄 Запрос #3755 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 94 спецификаций. Всего: 321099
🔄 Запрос #3756 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 83 спецификаций. Всего: 321182
🔄 Запрос #3757 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 75 спецификаций. Всего: 321257
🔄 Запрос #3758 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 86 спецификаций. Всего: 321343
🔄 Запрос #3759 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 321438
🔄 Запрос #3760 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 321533
🔄 Запрос #3761 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 117 спецификаций. Всего: 321650
📤 Сохранено 10044 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #3762 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 124 спецификаций. Всего: 321774
🔄 Запрос #3763 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 94 спецификаций. Всего: 321868
🔄 Запрос #3764 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 321953
🔄 Запрос #3765 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 322054
🔄 Запрос #3766 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 122 спецификаций. Всего: 322176
🔄 Запрос #3767 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 146 спецификаций. Всего: 322322
🔄 Запрос #3768 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 16 спецификаций. Всего: 322338
🔄 Запрос #3769 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 322437
🔄 Запрос #3770 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 70 спецификаций. Всего: 322507
🔄 Запрос #3771 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 3 спецификаций. Всего: 322510
🔄 Запрос #3772 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 322601
🔄 Запрос #3773 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 104 спецификаций. Всего: 322705
🔄 Запрос #3774 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 82 спецификаций. Всего: 322787
🔄 Запрос #3775 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 77 спецификаций. Всего: 322864
🔄 Запрос #3776 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 123 спецификаций. Всего: 322987
🔄 Запрос #3777 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 35 спецификаций. Всего: 323022
🔄 Запрос #3778 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 84 спецификаций. Всего: 323106
🔄 Запрос #3779 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 166 спецификаций. Всего: 323272
🔄 Запрос #3780 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 199 спецификаций. Всего: 323471
🔄 Запрос #3781 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 183 спецификаций. Всего: 323654
🔄 Запрос #3782 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 120 спецификаций. Всего: 323774
🔄 Запрос #3783 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 115 спецификаций. Всего: 323889
🔄 Запрос #3784 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 323995
🔄 Запрос #3785 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 26 спецификаций. Всего: 324021
🔄 Запрос #3786 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 3 спецификаций. Всего: 324024
🔄 Запрос #3787 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 93 спецификаций. Всего: 324117
🔄 Запрос #3788 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 134 спецификаций. Всего: 324251
🔄 Запрос #3789 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 324348
🔄 Запрос #3790 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 81 спецификаций. Всего: 324429
🔄 Запрос #3791 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 324545
🔄 Запрос #3792 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 104 спецификаций. Всего: 324649
🔄 Запрос #3793 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 324742
🔄 Запрос #3794 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 132 спецификаций. Всего: 324874
🔄 Запрос #3795 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 324988
🔄 Запрос #3796 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 141 спецификаций. Всего: 325129
🔄 Запрос #3797 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 325224
🔄 Запрос #3798 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 325314
🔄 Запрос #3799 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 325409
🔄 Запрос #3800 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 131 спецификаций. Всего: 325540
🔄 Запрос #3801 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 136 спецификаций. Всего: 325676
🔄 Запрос #3802 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 117 спецификаций. Всего: 325793
🔄 Запрос #3803 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 325895
🔄 Запрос #3804 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 325994
🔄 Запрос #3805 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 164 спецификаций. Всего: 326158
🔄 Запрос #3806 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 82 спецификаций. Всего: 326240
🔄 Запрос #3807 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 121 спецификаций. Всего: 326361
🔄 Запрос #3808 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 93 спецификаций. Всего: 326454
🔄 Запрос #3809 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 132 спецификаций. Всего: 326586

🔄 Запрос #3810 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 326688
🔄 Запрос #3811 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 326787
🔄 Запрос #3812 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 86 спецификаций. Всего: 326873
🔄 Запрос #3813 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 87 спецификаций. Всего: 326960
🔄 Запрос #3814 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 327062
🔄 Запрос #3815 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 327167
🔄 Запрос #3816 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 327252
🔄 Запрос #3817 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 72 спецификаций. Всего: 327324
🔄 Запрос #3818 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 37 спецификаций. Всего: 327361
🔄 Запрос #3819 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 86 спецификаций. Всего: 327447
🔄 Запрос #3820 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 61 спецификаций. Всего: 327508
🔄 Запрос #3821 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 79 спецификаций. Всего: 327587
🔄 Запрос #3822 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 47 спецификаций. Всего: 327634
🔄 Запрос #3823 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 327740
🔄 Запрос #3824 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 179 спецификаций. Всего: 327919
🔄 Запрос #3825 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 167 спецификаций. Всего: 328086
🔄 Запрос #3826 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 123 спецификаций. Всего: 328209
🔄 Запрос #3827 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 124 спецификаций. Всего: 328333
🔄 Запрос #3828 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 328436
🔄 Запрос #3829 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 328537
🔄 Запрос #3830 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 328640
🔄 Запрос #3831 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 120 спецификаций. Всего: 328760
🔄 Запрос #3832 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 86 спецификаций. Всего: 328846
🔄 Запрос #3833 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 83 спецификаций. Всего: 328929
🔄 Запрос #3834 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 329019
🔄 Запрос #3835 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 329122
🔄 Запрос #3836 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 67 спецификаций. Всего: 329189
🔄 Запрос #3837 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 61 спецификаций. Всего: 329250
🔄 Запрос #3838 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 96 спецификаций. Всего: 329346
🔄 Запрос #3839 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 64 спецификаций. Всего: 329410
🔄 Запрос #3840 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 74 спецификаций. Всего: 329484
🔄 Запрос #3841 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 329569
🔄 Запрос #3842 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 23 спецификаций. Всего: 329592
🔄 Запрос #3843 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 8 спецификаций. Всего: 329600
🔄 Запрос #3844 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 329706
🔄 Запрос #3845 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 61 спецификаций. Всего: 329767
🔄 Запрос #3846 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 72 спецификаций. Всего: 329839
🔄 Запрос #3847 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 329930
🔄 Запрос #3848 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 81 спецификаций. Всего: 330011
🔄 Запрос #3849 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 107 спецификаций. Всего: 330118
🔄 Запрос #3850 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 87 спецификаций. Всего: 330205
🔄 Запрос #3851 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 72 спецификаций. Всего: 330277
🔄 Запрос #3852 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 330372
🔄 Запрос #3853 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 94 спецификаций. Всего: 330466
🔄 Запрос #3854 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 330561
🔄 Запрос #3855 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 330646
🔄 Запрос #3856 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 73 спецификаций. Всего: 330719
🔄 Запрос #3857 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 330809
🔄 Запрос #3858 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 56 спецификаций. Всего: 330865
🔄 Запрос #3859 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 71 спецификаций. Всего: 330936
🔄 Запрос #3860 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 100 спецификаций. Всего: 331036
🔄 Запрос #3861 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 19 спецификаций. Всего: 331055
🔄 Запрос #3862 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 21 спецификаций. Всего: 331076
🔄 Запрос #3863 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 26 спецификаций. Всего: 331102
🔄 Запрос #3864 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 21 спецификаций. Всего: 331123
🔄 Запрос #3865 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 2 спецификаций. Всего: 331125
🔄 Запрос #3866 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 55 спецификаций. Всего: 331180
🔄 Запрос #3867 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 80 спецификаций. Всего: 331260
🔄 Запрос #3868 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 331374
🔄 Запрос #3869 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 331477
🔄 Запрос #3870 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 331562
🔄 Запрос #3871 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 80 спецификаций. Всего: 331642
🔄 Запрос #3872 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 331761
📤 Сохранено 10111 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #3873 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 118 спецификаций. Всего: 331879
🔄 Запрос #3874 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 187 спецификаций. Всего: 332066
🔄 Запрос #3875 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 122 спецификаций. Всего: 332188
🔄 Запрос #3876 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 124 спецификаций. Всего: 332312
🔄 Запрос #3877 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 54 спецификаций. Всего: 332366
🔄 Запрос #3878 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 70 спецификаций. Всего: 332436
🔄 Запрос #3879 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 107 спецификаций. Всего: 332543
🔄 Запрос #3880 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 81 спецификаций. Всего: 332624
🔄 Запрос #3881 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 332726
🔄 Запрос #3882 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 44 спецификаций. Всего: 332770
🔄 Запрос #3883 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 31 спецификаций. Всего: 332801
🔄 Запрос #3884 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09

📥 Загружено 103 спецификаций. Всего: 332904
🔄 Запрос #3885 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 120 спецификаций. Всего: 333024
🔄 Запрос #3886 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 333143
🔄 Запрос #3887 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 333242
🔄 Запрос #3888 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 333341
🔄 Запрос #3889 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 29 спецификаций. Всего: 333370
🔄 Запрос #3890 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 333489
🔄 Запрос #3891 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 333616
🔄 Запрос #3892 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 107 спецификаций. Всего: 333723
🔄 Запрос #3893 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 333832
🔄 Запрос #3894 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 87 спецификаций. Всего: 333919
🔄 Запрос #3895 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 70 спецификаций. Всего: 333989
🔄 Запрос #3896 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 92 спецификаций. Всего: 334081
🔄 Запрос #3897 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 84 спецификаций. Всего: 334165
🔄 Запрос #3898 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 45 спецификаций. Всего: 334210
🔄 Запрос #3899 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 63 спецификаций. Всего: 334273
🔄 Запрос #3900 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 89 спецификаций. Всего: 334362
🔄 Запрос #3901 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 120 спецификаций. Всего: 334482
🔄 Запрос #3902 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 334596
🔄 Запрос #3903 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 53 спецификаций. Всего: 334649
🔄 Запрос #3904 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 93 спецификаций. Всего: 334742
🔄 Запрос #3905 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 77 спецификаций. Всего: 334819
🔄 Запрос #3906 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 100 спецификаций. Всего: 334919
🔄 Запрос #3907 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 100 спецификаций. Всего: 335019
🔄 Запрос #3908 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 62 спецификаций. Всего: 335081
🔄 Запрос #3909 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 335192
🔄 Запрос #3910 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 335300
🔄 Запрос #3911 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 77 спецификаций. Всего: 335377
🔄 Запрос #3912 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 128 спецификаций. Всего: 335505
🔄 Запрос #3913 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 129 спецификаций. Всего: 335634
🔄 Запрос #3914 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 152 спецификаций. Всего: 335786
🔄 Запрос #3915 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 133 спецификаций. Всего: 335919
🔄 Запрос #3916 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 121 спецификаций. Всего: 336040
🔄 Запрос #3917 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 125 спецификаций. Всего: 336165
🔄 Запрос #3918 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 113 спецификаций. Всего: 336278
🔄 Запрос #3919 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 104 спецификаций. Всего: 336382
🔄 Запрос #3920 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 336482
🔄 Запрос #3921 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 336583
🔄 Запрос #3922 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 123 спецификаций. Всего: 336706
🔄 Запрос #3923 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 25 спецификаций. Всего: 336731
🔄 Запрос #3924 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 38 спецификаций. Всего: 336769
🔄 Запрос #3925 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 96 спецификаций. Всего: 336865
🔄 Запрос #3926 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 121 спецификаций. Всего: 336986
🔄 Запрос #3927 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 47 спецификаций. Всего: 337033
🔄 Запрос #3928 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 9 спецификаций. Всего: 337042
🔄 Запрос #3929 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 78 спецификаций. Всего: 337120
🔄 Запрос #3930 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 337236
🔄 Запрос #3931 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 65 спецификаций. Всего: 337301
🔄 Запрос #3932 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 112 спецификаций. Всего: 337413
🔄 Запрос #3933 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 337518
🔄 Запрос #3934 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 33 спецификаций. Всего: 337551
🔄 Запрос #3935 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 88 спецификаций. Всего: 337639
🔄 Запрос #3936 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 33 спецификаций. Всего: 337672
🔄 Запрос #3937 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 337791
🔄 Запрос #3938 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 337907
🔄 Запрос #3939 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 338026
🔄 Запрос #3940 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 113 спецификаций. Всего: 338139
🔄 Запрос #3941 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 123 спецификаций. Всего: 338262
🔄 Запрос #3942 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 92 спецификаций. Всего: 338354
🔄 Запрос #3943 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 124 спецификаций. Всего: 338478
🔄 Запрос #3944 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 187 спецификаций. Всего: 338665
🔄 Запрос #3945 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 181 спецификаций. Всего: 338846
🔄 Запрос #3946 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 100 спецификаций. Всего: 338946
🔄 Запрос #3947 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 25 спецификаций. Всего: 338971
🔄 Запрос #3948 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 139 спецификаций. Всего: 339110
🔄 Запрос #3949 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 145 спецификаций. Всего: 339255
🔄 Запрос #3950 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 138 спецификаций. Всего: 339393
🔄 Запрос #3951 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 118 спецификаций. Всего: 339511
🔄 Запрос #3952 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 131 спецификаций. Всего: 339642
🔄 Запрос #3953 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 130 спецификаций. Всего: 339772
🔄 Запрос #3954 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 157 спецификаций. Всего: 339929
🔄 Запрос #3955 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 128 спецификаций. Всего: 340057
🔄 Запрос #3956 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 340154
🔄 Запрос #3957 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 340252
🔄 Запрос #3958 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 46 спецификаций. Всего: 340298

🔄 Запрос #3959 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 59 спецификаций. Всего: 340357
🔄 Запрос #3960 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 340455
🔄 Запрос #3961 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 340556
🔄 Запрос #3962 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 139 спецификаций. Всего: 340695
🔄 Запрос #3963 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 340803
🔄 Запрос #3964 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 73 спецификаций. Всего: 340876
🔄 Запрос #3965 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 47 спецификаций. Всего: 340923
🔄 Запрос #3966 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 87 спецификаций. Всего: 341010
🔄 Запрос #3967 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 113 спецификаций. Всего: 341123
🔄 Запрос #3968 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 65 спецификаций. Всего: 341188
🔄 Запрос #3969 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 55 спецификаций. Всего: 341243
🔄 Запрос #3970 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 33 спецификаций. Всего: 341276
🔄 Запрос #3971 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 341385
🔄 Запрос #3972 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 341494
🔄 Запрос #3973 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 107 спецификаций. Всего: 341601
🔄 Запрос #3974 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 79 спецификаций. Всего: 341680
🔄 Запрос #3975 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 341786
📤 Сохранено 10025 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #3976 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 137 спецификаций. Всего: 341923
🔄 Запрос #3977 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 342024
🔄 Запрос #3978 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 342109
🔄 Запрос #3979 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 342207
🔄 Запрос #3980 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 80 спецификаций. Всего: 342287
🔄 Запрос #3981 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 104 спецификаций. Всего: 342391
🔄 Запрос #3982 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 342496
🔄 Запрос #3983 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 72 спецификаций. Всего: 342568
🔄 Запрос #3984 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 124 спецификаций. Всего: 342692
🔄 Запрос #3985 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 342797
🔄 Запрос #3986 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 342913
🔄 Запрос #3987 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 131 спецификаций. Всего: 343044
🔄 Запрос #3988 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 115 спецификаций. Всего: 343159
🔄 Запрос #3989 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 49 спецификаций. Всего: 343208
🔄 Запрос #3990 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 343335
🔄 Запрос #3991 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 343446
🔄 Запрос #3992 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 50 спецификаций. Всего: 343496
🔄 Запрос #3993 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 66 спецификаций. Всего: 343562
🔄 Запрос #3994 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 66 спецификаций. Всего: 343628
🔄 Запрос #3995 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 49 спецификаций. Всего: 343677
🔄 Запрос #3996 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 78 спецификаций. Всего: 343755
🔄 Запрос #3997 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 89 спецификаций. Всего: 343844
🔄 Запрос #3998 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 343946
🔄 Запрос #3999 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 93 спецификаций. Всего: 344039
🔄 Запрос #4000 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 77 спецификаций. Всего: 344116
🔄 Запрос #4001 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 43 спецификаций. Всего: 344159
🔄 Запрос #4002 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 92 спецификаций. Всего: 344251
🔄 Запрос #4003 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 344346
🔄 Запрос #4004 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 63 спецификаций. Всего: 344409
🔄 Запрос #4005 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 87 спецификаций. Всего: 344496
🔄 Запрос #4006 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 344586
🔄 Запрос #4007 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 84 спецификаций. Всего: 344670
🔄 Запрос #4008 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 74 спецификаций. Всего: 344744
🔄 Запрос #4009 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 87 спецификаций. Всего: 344831
🔄 Запрос #4010 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 92 спецификаций. Всего: 344923
🔄 Запрос #4011 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 345018
🔄 Запрос #4012 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 61 спецификаций. Всего: 345079
🔄 Запрос #4013 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 2 спецификаций. Всего: 345081
🔄 Запрос #4014 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 4 спецификаций. Всего: 345085
🔄 Запрос #4015 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 65 спецификаций. Всего: 345150
🔄 Запрос #4016 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 54 спецификаций. Всего: 345204
🔄 Запрос #4017 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 345306
🔄 Запрос #4018 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 93 спецификаций. Всего: 345399
🔄 Запрос #4019 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 345505
🔄 Запрос #4020 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 118 спецификаций. Всего: 345623
🔄 Запрос #4021 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 345737
🔄 Запрос #4022 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 83 спецификаций. Всего: 345820
🔄 Запрос #4023 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 96 спецификаций. Всего: 345916
🔄 Запрос #4024 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 126 спецификаций. Всего: 346042
🔄 Запрос #4025 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 117 спецификаций. Всего: 346159
🔄 Запрос #4026 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 346268
🔄 Запрос #4027 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 346369
🔄 Запрос #4028 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 346459
🔄 Запрос #4029 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 153 спецификаций. Всего: 346612
🔄 Запрос #4030 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 120 спецификаций. Всего: 346732
🔄 Запрос #4031 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 346838
🔄 Запрос #4032 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09

📥 Загружено 97 спецификаций. Всего: 346935
🔄 Запрос #4033 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 146 спецификаций. Всего: 347081
🔄 Запрос #4034 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 121 спецификаций. Всего: 347202
🔄 Запрос #4035 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 87 спецификаций. Всего: 347289
🔄 Запрос #4036 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 96 спецификаций. Всего: 347385
🔄 Запрос #4037 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 347496
🔄 Запрос #4038 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 347597
🔄 Запрос #4039 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 347707
🔄 Запрос #4040 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 20 спецификаций. Всего: 347727
🔄 Запрос #4041 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 347826
🔄 Запрос #4042 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 347931
🔄 Запрос #4043 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 48 спецификаций. Всего: 347979
🔄 Запрос #4044 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 1 спецификаций. Всего: 347980
🔄 Запрос #4045 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 35 спецификаций. Всего: 348015
🔄 Запрос #4046 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 93 спецификаций. Всего: 348108
🔄 Запрос #4047 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 81 спецификаций. Всего: 348189
🔄 Запрос #4048 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 70 спецификаций. Всего: 348259
🔄 Запрос #4049 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 113 спецификаций. Всего: 348372
🔄 Запрос #4050 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 144 спецификаций. Всего: 348516
🔄 Запрос #4051 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 348606
🔄 Запрос #4052 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 78 спецификаций. Всего: 348684
🔄 Запрос #4053 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 113 спецификаций. Всего: 348797
🔄 Запрос #4054 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 68 спецификаций. Всего: 348865
🔄 Запрос #4055 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 348981
🔄 Запрос #4056 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 349089
🔄 Запрос #4057 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 104 спецификаций. Всего: 349193
🔄 Запрос #4058 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 165 спецификаций. Всего: 349358
🔄 Запрос #4059 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 57 спецификаций. Всего: 349415
🔄 Запрос #4060 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 349525
🔄 Запрос #4061 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 349641
🔄 Запрос #4062 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 48 спецификаций. Всего: 349689
🔄 Запрос #4063 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 64 спецификаций. Всего: 349753
🔄 Запрос #4064 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 87 спецификаций. Всего: 349840
🔄 Запрос #4065 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 84 спецификаций. Всего: 349924
🔄 Запрос #4066 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 51 спецификаций. Всего: 349975
🔄 Запрос #4067 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 129 спецификаций. Всего: 350104
🔄 Запрос #4068 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 350203
🔄 Запрос #4069 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 144 спецификаций. Всего: 350347
🔄 Запрос #4070 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 142 спецификаций. Всего: 350489
🔄 Запрос #4071 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 124 спецификаций. Всего: 350613
🔄 Запрос #4072 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 80 спецификаций. Всего: 350693
🔄 Запрос #4073 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 125 спецификаций. Всего: 350818
🔄 Запрос #4074 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 350946
🔄 Запрос #4075 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 77 спецификаций. Всего: 351023
🔄 Запрос #4076 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 351114
🔄 Запрос #4077 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 93 спецификаций. Всего: 351207
🔄 Запрос #4078 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 59 спецификаций. Всего: 351266
🔄 Запрос #4079 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 83 спецификаций. Всего: 351349
🔄 Запрос #4080 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 68 спецификаций. Всего: 351417
🔄 Запрос #4081 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 351502
🔄 Запрос #4082 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 351616
🔄 Запрос #4083 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 351735
🔄 Запрос #4084 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 144 спецификаций. Всего: 351879
📤 Сохранено 10093 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #4085 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 136 спецификаций. Всего: 352015
🔄 Запрос #4086 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 126 спецификаций. Всего: 352141
🔄 Запрос #4087 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 352259
🔄 Запрос #4088 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 352356
🔄 Запрос #4089 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 352461
🔄 Запрос #4090 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 59 спецификаций. Всего: 352520
🔄 Запрос #4091 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 72 спецификаций. Всего: 352592
🔄 Запрос #4092 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 92 спецификаций. Всего: 352684
🔄 Запрос #4093 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 135 спецификаций. Всего: 352819
🔄 Запрос #4094 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 41 спецификаций. Всего: 352860
🔄 Запрос #4095 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 84 спецификаций. Всего: 352944
🔄 Запрос #4096 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 57 спецификаций. Всего: 353001
🔄 Запрос #4097 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 45 спецификаций. Всего: 353046
🔄 Запрос #4098 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 100 спецификаций. Всего: 353146
🔄 Запрос #4099 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 64 спецификаций. Всего: 353210
🔄 Запрос #4100 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 66 спецификаций. Всего: 353276
🔄 Запрос #4101 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 96 спецификаций. Всего: 353372
🔄 Запрос #4102 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 353478
🔄 Запрос #4103 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 353579
🔄 Запрос #4104 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09

📥 Загружено 124 спецификаций. Всего: 353703
🔄 Запрос #4105 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 353830
🔄 Запрос #4106 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 353935
🔄 Запрос #4107 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 66 спецификаций. Всего: 354001
🔄 Запрос #4108 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 39 спецификаций. Всего: 354040
🔄 Запрос #4109 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 70 спецификаций. Всего: 354110
🔄 Запрос #4110 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 354195
🔄 Запрос #4111 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 63 спецификаций. Всего: 354258
🔄 Запрос #4112 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 76 спецификаций. Всего: 354334
🔄 Запрос #4113 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 80 спецификаций. Всего: 354414
🔄 Запрос #4114 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 57 спецификаций. Всего: 354471
🔄 Запрос #4115 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 55 спецификаций. Всего: 354526
🔄 Запрос #4116 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 57 спецификаций. Всего: 354583
🔄 Запрос #4117 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 162 спецификаций. Всего: 354745
🔄 Запрос #4118 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 161 спецификаций. Всего: 354906
🔄 Запрос #4119 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 69 спецификаций. Всего: 354975
🔄 Запрос #4120 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 355066
🔄 Запрос #4121 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 104 спецификаций. Всего: 355170
🔄 Запрос #4122 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 124 спецификаций. Всего: 355294
🔄 Запрос #4123 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 355396
🔄 Запрос #4124 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 355486
🔄 Запрос #4125 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 113 спецификаций. Всего: 355599
🔄 Запрос #4126 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 92 спецификаций. Всего: 355691
🔄 Запрос #4127 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 12 спецификаций. Всего: 355703
🔄 Запрос #4128 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 16 спецификаций. Всего: 355719
🔄 Запрос #4129 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 0 спецификаций. Всего: 355719
🔄 Запрос #4130 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 9 спецификаций. Всего: 355728
🔄 Запрос #4131 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 11 спецификаций. Всего: 355739
🔄 Запрос #4132 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 2 спецификаций. Всего: 355741
🔄 Запрос #4133 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 33 спецификаций. Всего: 355774
🔄 Запрос #4134 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 36 спецификаций. Всего: 355810
🔄 Запрос #4135 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 121 спецификаций. Всего: 355931
🔄 Запрос #4136 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 134 спецификаций. Всего: 356065
🔄 Запрос #4137 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 148 спецификаций. Всего: 356213
🔄 Запрос #4138 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 151 спецификаций. Всего: 356364
🔄 Запрос #4139 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 122 спецификаций. Всего: 356486
🔄 Запрос #4140 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 356605
🔄 Запрос #4141 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 356721
🔄 Запрос #4142 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 122 спецификаций. Всего: 356843
🔄 Запрос #4143 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 356959
🔄 Запрос #4144 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 357054
🔄 Запрос #4145 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 69 спецификаций. Всего: 357123
🔄 Запрос #4146 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 117 спецификаций. Всего: 357240
🔄 Запрос #4147 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 94 спецификаций. Всего: 357334
🔄 Запрос #4148 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 357427
🔄 Запрос #4149 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 357539
🔄 Запрос #4150 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 357655
🔄 Запрос #4151 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 112 спецификаций. Всего: 357767
🔄 Запрос #4152 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 357867
🔄 Запрос #4153 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 357970
🔄 Запрос #4154 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 82 спецификаций. Всего: 358052
🔄 Запрос #4155 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 358163
🔄 Запрос #4156 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 358254
🔄 Запрос #4157 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 358363
🔄 Запрос #4158 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 358465
🔄 Запрос #4159 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 96 спецификаций. Всего: 358561
🔄 Запрос #4160 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 122 спецификаций. Всего: 358683
🔄 Запрос #4161 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 358780
🔄 Запрос #4162 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 170 спецификаций. Всего: 358950
🔄 Запрос #4163 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 359077
🔄 Запрос #4164 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 45 спецификаций. Всего: 359122
🔄 Запрос #4165 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 77 спецификаций. Всего: 359199
🔄 Запрос #4166 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 92 спецификаций. Всего: 359291
🔄 Запрос #4167 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 359402
🔄 Запрос #4168 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 112 спецификаций. Всего: 359514
🔄 Запрос #4169 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 359615
🔄 Запрос #4170 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 81 спецификаций. Всего: 359696
🔄 Запрос #4171 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 118 спецификаций. Всего: 359814
🔄 Запрос #4172 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 74 спецификаций. Всего: 359888
🔄 Запрос #4173 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 86 спецификаций. Всего: 359974
🔄 Запрос #4174 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 360079
🔄 Запрос #4175 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 82 спецификаций. Всего: 360161
🔄 Запрос #4176 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 92 спецификаций. Всего: 360253
🔄 Запрос #4177 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 69 спецификаций. Всего: 360322
🔄 Запрос #4178 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 68 спецификаций. Всего: 360390

🔄 Запрос #4179 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 89 спецификаций. Всего: 360479
🔄 Запрос #4180 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 57 спецификаций. Всего: 360536
🔄 Запрос #4181 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 70 спецификаций. Всего: 360606
🔄 Запрос #4182 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 360705
🔄 Запрос #4183 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 137 спецификаций. Всего: 360842
🔄 Запрос #4184 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 75 спецификаций. Всего: 360917
🔄 Запрос #4185 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 60 спецификаций. Всего: 360977
🔄 Запрос #4186 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 1 спецификаций. Всего: 360978
🔄 Запрос #4187 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 28 спецификаций. Всего: 361006
🔄 Запрос #4188 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 23 спецификаций. Всего: 361029
🔄 Запрос #4189 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 361134
🔄 Запрос #4190 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 118 спецификаций. Всего: 361252
🔄 Запрос #4191 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 361351
🔄 Запрос #4192 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 361461
🔄 Запрос #4193 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 361560
🔄 Запрос #4194 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 361657
🔄 Запрос #4195 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 107 спецификаций. Всего: 361764
🔄 Запрос #4196 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 84 спецификаций. Всего: 361848
🔄 Запрос #4197 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 83 спецификаций. Всего: 361931
📤 Сохранено 10052 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #4198 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 79 спецификаций. Всего: 362010
🔄 Запрос #4199 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 78 спецификаций. Всего: 362088
🔄 Запрос #4200 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 51 спецификаций. Всего: 362139
🔄 Запрос #4201 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 45 спецификаций. Всего: 362184
🔄 Запрос #4202 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 100 спецификаций. Всего: 362284
🔄 Запрос #4203 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 126 спецификаций. Всего: 362410
🔄 Запрос #4204 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 123 спецификаций. Всего: 362533
🔄 Запрос #4205 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 362632
🔄 Запрос #4206 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 362730
🔄 Запрос #4207 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 89 спецификаций. Всего: 362819
🔄 Запрос #4208 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 96 спецификаций. Всего: 362915
🔄 Запрос #4209 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 73 спецификаций. Всего: 362988
🔄 Запрос #4210 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 66 спецификаций. Всего: 363054
🔄 Запрос #4211 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 89 спецификаций. Всего: 363143
🔄 Запрос #4212 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 363234
🔄 Запрос #4213 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 79 спецификаций. Всего: 363313
🔄 Запрос #4214 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 79 спецификаций. Всего: 363392
🔄 Запрос #4215 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 363483
🔄 Запрос #4216 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 89 спецификаций. Всего: 363572
🔄 Запрос #4217 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 363670
🔄 Запрос #4218 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 363761
🔄 Запрос #4219 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 61 спецификаций. Всего: 363822
🔄 Запрос #4220 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 41 спецификаций. Всего: 363863
🔄 Запрос #4221 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 40 спецификаций. Всего: 363903
🔄 Запрос #4222 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 364001
🔄 Запрос #4223 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 66 спецификаций. Всего: 364067
🔄 Запрос #4224 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 137 спецификаций. Всего: 364204
🔄 Запрос #4225 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 150 спецификаций. Всего: 364354
🔄 Запрос #4226 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 123 спецификаций. Всего: 364477
🔄 Запрос #4227 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 134 спецификаций. Всего: 364611
🔄 Запрос #4228 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 364727
🔄 Запрос #4229 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 364826
🔄 Запрос #4230 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 364911
🔄 Запрос #4231 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 365017
🔄 Запрос #4232 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 126 спецификаций. Всего: 365143
🔄 Запрос #4233 для 2024-12-12 20:44:09 - 2024-12-19 20:44:09
📥 Загружено 22 спецификаций. Всего: 365165
📅 Обрабатываем диапазон 2024-12-05 20:44:09 - 2024-12-12 20:44:09 (попытка 1/5)
🔄 Запрос #4234 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 160 спецификаций. Всего: 365325
🔄 Запрос #4235 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 137 спецификаций. Всего: 365462
🔄 Запрос #4236 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 365578
🔄 Запрос #4237 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 365665
🔄 Запрос #4238 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 365775
🔄 Запрос #4239 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 365873
🔄 Запрос #4240 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 365980
🔄 Запрос #4241 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 366094
🔄 Запрос #4242 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 366213
🔄 Запрос #4243 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 366326
🔄 Запрос #4244 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 366449
🔄 Запрос #4245 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 132 спецификаций. Всего: 366581
🔄 Запрос #4246 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 366700
🔄 Запрос #4247 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 122 спецификаций. Всего: 366822
🔄 Запрос #4248 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 122 спецификаций. Всего: 366944
🔄 Запрос #4249 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 367058
🔄 Запрос #4250 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 84 спецификаций. Всего: 367142
🔄 Запрос #4251 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09

📥 Загружено 69 спецификаций. Всего: 367211
🔄 Запрос #4252 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 367335
🔄 Запрос #4253 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 81 спецификаций. Всего: 367416
🔄 Запрос #4254 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 367504
🔄 Запрос #4255 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 367595
🔄 Запрос #4256 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 367703
🔄 Запрос #4257 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 85 спецификаций. Всего: 367788
🔄 Запрос #4258 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 367875
🔄 Запрос #4259 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 90 спецификаций. Всего: 367965
🔄 Запрос #4260 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 368071
🔄 Запрос #4261 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 368173
🔄 Запрос #4262 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 368267
🔄 Запрос #4263 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 46 спецификаций. Всего: 368313
🔄 Запрос #4264 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 368401
🔄 Запрос #4265 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 97 спецификаций. Всего: 368498
🔄 Запрос #4266 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 100 спецификаций. Всего: 368598
🔄 Запрос #4267 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 368694
🔄 Запрос #4268 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 368802
🔄 Запрос #4269 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 368890
🔄 Запрос #4270 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 368996
🔄 Запрос #4271 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 76 спецификаций. Всего: 369072
🔄 Запрос #4272 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 79 спецификаций. Всего: 369151
🔄 Запрос #4273 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 369249
🔄 Запрос #4274 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 39 спецификаций. Всего: 369288
🔄 Запрос #4275 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 76 спецификаций. Всего: 369364
🔄 Запрос #4276 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 65 спецификаций. Всего: 369429
🔄 Запрос #4277 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 70 спецификаций. Всего: 369499
🔄 Запрос #4278 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 369622
🔄 Запрос #4279 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 79 спецификаций. Всего: 369701
🔄 Запрос #4280 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 80 спецификаций. Всего: 369781
🔄 Запрос #4281 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 369886
🔄 Запрос #4282 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 74 спецификаций. Всего: 369960
🔄 Запрос #4283 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 78 спецификаций. Всего: 370038
🔄 Запрос #4284 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 61 спецификаций. Всего: 370099
🔄 Запрос #4285 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 46 спецификаций. Всего: 370145
🔄 Запрос #4286 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 73 спецификаций. Всего: 370218
🔄 Запрос #4287 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 78 спецификаций. Всего: 370296
🔄 Запрос #4288 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 84 спецификаций. Всего: 370380
🔄 Запрос #4289 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 92 спецификаций. Всего: 370472
🔄 Запрос #4290 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 76 спецификаций. Всего: 370548
🔄 Запрос #4291 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 370639
🔄 Запрос #4292 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 70 спецификаций. Всего: 370709
🔄 Запрос #4293 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 7 спецификаций. Всего: 370716
🔄 Запрос #4294 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 97 спецификаций. Всего: 370813
🔄 Запрос #4295 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 370901
🔄 Запрос #4296 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 370989
🔄 Запрос #4297 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 78 спецификаций. Всего: 371067
🔄 Запрос #4298 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 71 спецификаций. Всего: 371138
🔄 Запрос #4299 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 70 спецификаций. Всего: 371208
🔄 Запрос #4300 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 371302
🔄 Запрос #4301 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 371403
🔄 Запрос #4302 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 97 спецификаций. Всего: 371500
🔄 Запрос #4303 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 104 спецификаций. Всего: 371604
🔄 Запрос #4304 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 85 спецификаций. Всего: 371689
🔄 Запрос #4305 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 69 спецификаций. Всего: 371758
🔄 Запрос #4306 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 81 спецификаций. Всего: 371839
🔄 Запрос #4307 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 371946
📤 Сохранено 10015 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #4308 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 92 спецификаций. Всего: 372038
🔄 Запрос #4309 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 372125
🔄 Запрос #4310 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 372213
🔄 Запрос #4311 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 78 спецификаций. Всего: 372291
🔄 Запрос #4312 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 372378
🔄 Запрос #4313 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 104 спецификаций. Всего: 372482
🔄 Запрос #4314 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 64 спецификаций. Всего: 372546
🔄 Запрос #4315 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 79 спецификаций. Всего: 372625
🔄 Запрос #4316 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 372740
🔄 Запрос #4317 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 100 спецификаций. Всего: 372840
🔄 Запрос #4318 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 81 спецификаций. Всего: 372921
🔄 Запрос #4319 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 134 спецификаций. Всего: 373055
🔄 Запрос #4320 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 373148
🔄 Запрос #4321 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 373262
🔄 Запрос #4322 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 74 спецификаций. Всего: 373336
🔄 Запрос #4323 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 44 спецификаций. Всего: 373380
🔄 Запрос #4324 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 61 спецификаций. Всего: 373441
🔄 Запрос #4325 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 373549
🔄 Запрос #4326 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 78 спецификаций. Всего: 373627
🔄 Запрос #4327 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 373734
🔄 Запрос #4328 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09

📥 Загружено 90 спецификаций. Всего: 373824
🔄 Запрос #4329 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 58 спецификаций. Всего: 373882
🔄 Запрос #4330 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 373975
🔄 Запрос #4331 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 374091
🔄 Запрос #4332 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 70 спецификаций. Всего: 374161
🔄 Запрос #4333 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 78 спецификаций. Всего: 374239
🔄 Запрос #4334 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 60 спецификаций. Всего: 374299
🔄 Запрос #4335 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 62 спецификаций. Всего: 374361
🔄 Запрос #4336 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 120 спецификаций. Всего: 374481
🔄 Запрос #4337 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 157 спецификаций. Всего: 374638
🔄 Запрос #4338 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 136 спецификаций. Всего: 374774
🔄 Запрос #4339 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 374893
🔄 Запрос #4340 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 117 спецификаций. Всего: 375010
🔄 Запрос #4341 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 375108
🔄 Запрос #4342 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 135 спецификаций. Всего: 375243
🔄 Запрос #4343 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 145 спецификаций. Всего: 375388
🔄 Запрос #4344 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 162 спецификаций. Всего: 375550
🔄 Запрос #4345 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 11 спецификаций. Всего: 375561
🔄 Запрос #4346 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 181 спецификаций. Всего: 375742
🔄 Запрос #4347 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 188 спецификаций. Всего: 375930
🔄 Запрос #4348 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 174 спецификаций. Всего: 376104
🔄 Запрос #4349 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 141 спецификаций. Всего: 376245
🔄 Запрос #4350 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 376354
🔄 Запрос #4351 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 138 спецификаций. Всего: 376492
🔄 Запрос #4352 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 132 спецификаций. Всего: 376624
🔄 Запрос #4353 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 376747
🔄 Запрос #4354 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 376861
🔄 Запрос #4355 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 138 спецификаций. Всего: 376999
🔄 Запрос #4356 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 92 спецификаций. Всего: 377091
🔄 Запрос #4357 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 117 спецификаций. Всего: 377208
🔄 Запрос #4358 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 377331
🔄 Запрос #4359 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 104 спецификаций. Всего: 377435
🔄 Запрос #4360 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 377548
🔄 Запрос #4361 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 377650
🔄 Запрос #4362 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 377746
🔄 Запрос #4363 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 99 спецификаций. Всего: 377845
🔄 Запрос #4364 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 377946
🔄 Запрос #4365 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 89 спецификаций. Всего: 378035
🔄 Запрос #4366 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 378126
🔄 Запрос #4367 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 378226
🔄 Запрос #4368 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 139 спецификаций. Всего: 378365
🔄 Запрос #4369 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 378471
🔄 Запрос #4370 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 378584
🔄 Запрос #4371 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 137 спецификаций. Всего: 378721
🔄 Запрос #4372 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 378847
🔄 Запрос #4373 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 135 спецификаций. Всего: 378982
🔄 Запрос #4374 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 379094
🔄 Запрос #4375 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 79 спецификаций. Всего: 379173
🔄 Запрос #4376 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 17 спецификаций. Всего: 379190
🔄 Запрос #4377 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 121 спецификаций. Всего: 379311
🔄 Запрос #4378 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 95 спецификаций. Всего: 379406
🔄 Запрос #4379 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 84 спецификаций. Всего: 379490
🔄 Запрос #4380 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 379593
🔄 Запрос #4381 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 97 спецификаций. Всего: 379690
🔄 Запрос #4382 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 379777
🔄 Запрос #4383 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 71 спецификаций. Всего: 379848
🔄 Запрос #4384 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 379936
🔄 Запрос #4385 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 380049
🔄 Запрос #4386 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 47 спецификаций. Всего: 380096
🔄 Запрос #4387 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 380192
🔄 Запрос #4388 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 137 спецификаций. Всего: 380329
🔄 Запрос #4389 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 83 спецификаций. Всего: 380412
🔄 Запрос #4390 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 30 спецификаций. Всего: 380442
🔄 Запрос #4391 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 380568
🔄 Запрос #4392 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 131 спецификаций. Всего: 380699
🔄 Запрос #4393 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 380818
🔄 Запрос #4394 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 380927
🔄 Запрос #4395 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 381038
🔄 Запрос #4396 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 381150
🔄 Запрос #4397 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 381253
🔄 Запрос #4398 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 72 спецификаций. Всего: 381325
🔄 Запрос #4399 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 77 спецификаций. Всего: 381402
🔄 Запрос #4400 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 117 спецификаций. Всего: 381519
🔄 Запрос #4401 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 381624
🔄 Запрос #4402 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 44 спецификаций. Всего: 381668
🔄 Запрос #4403 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09

📥 Загружено 91 спецификаций. Всего: 381759
🔄 Запрос #4404 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 132 спецификаций. Всего: 381891
🔄 Запрос #4405 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 139 спецификаций. Всего: 382030
📤 Сохранено 10084 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #4406 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 382132
🔄 Запрос #4407 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 99 спецификаций. Всего: 382231
🔄 Запрос #4408 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 382334
🔄 Запрос #4409 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 382421
🔄 Запрос #4410 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 69 спецификаций. Всего: 382490
🔄 Запрос #4411 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 92 спецификаций. Всего: 382582
🔄 Запрос #4412 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 80 спецификаций. Всего: 382662
🔄 Запрос #4413 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 152 спецификаций. Всего: 382814
🔄 Запрос #4414 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 148 спецификаций. Всего: 382962
🔄 Запрос #4415 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 86 спецификаций. Всего: 383048
🔄 Запрос #4416 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 83 спецификаций. Всего: 383131
🔄 Запрос #4417 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 71 спецификаций. Всего: 383202
🔄 Запрос #4418 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 383295
🔄 Запрос #4419 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 83 спецификаций. Всего: 383378
🔄 Запрос #4420 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 383476
🔄 Запрос #4421 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 383585
🔄 Запрос #4422 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 383679
🔄 Запрос #4423 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 383781
🔄 Запрос #4424 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 383890
🔄 Запрос #4425 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 383993
🔄 Запрос #4426 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 129 спецификаций. Всего: 384122
🔄 Запрос #4427 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 384238
🔄 Запрос #4428 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 384346
🔄 Запрос #4429 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 384433
🔄 Запрос #4430 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 384549
🔄 Запрос #4431 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 90 спецификаций. Всего: 384639
🔄 Запрос #4432 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 2 спецификаций. Всего: 384641
🔄 Запрос #4433 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 75 спецификаций. Всего: 384716
🔄 Запрос #4434 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 31 спецификаций. Всего: 384747
🔄 Запрос #4435 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 384849
🔄 Запрос #4436 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 58 спецификаций. Всего: 384907
🔄 Запрос #4437 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 120 спецификаций. Всего: 385027
🔄 Запрос #4438 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 145 спецификаций. Всего: 385172
🔄 Запрос #4439 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 156 спецификаций. Всего: 385328
🔄 Запрос #4440 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 59 спецификаций. Всего: 385387
🔄 Запрос #4441 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 164 спецификаций. Всего: 385551
🔄 Запрос #4442 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 153 спецификаций. Всего: 385704
🔄 Запрос #4443 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 385828
🔄 Запрос #4444 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 203 спецификаций. Всего: 386031
🔄 Запрос #4445 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 155 спецификаций. Всего: 386186
🔄 Запрос #4446 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 0 спецификаций. Всего: 386186
🔄 Запрос #4447 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 0 спецификаций. Всего: 386186
🔄 Запрос #4448 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 76 спецификаций. Всего: 386262
🔄 Запрос #4449 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 161 спецификаций. Всего: 386423
🔄 Запрос #4450 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 167 спецификаций. Всего: 386590
🔄 Запрос #4451 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 149 спецификаций. Всего: 386739
🔄 Запрос #4452 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 121 спецификаций. Всего: 386860
🔄 Запрос #4453 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 144 спецификаций. Всего: 387004
🔄 Запрос #4454 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 121 спецификаций. Всего: 387125
🔄 Запрос #4455 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 128 спецификаций. Всего: 387253
🔄 Запрос #4456 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 387354
🔄 Запрос #4457 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 387465
🔄 Запрос #4458 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 149 спецификаций. Всего: 387614
🔄 Запрос #4459 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 387707
🔄 Запрос #4460 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 387810
🔄 Запрос #4461 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 387904
🔄 Запрос #4462 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 388009
🔄 Запрос #4463 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 388115
🔄 Запрос #4464 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 121 спецификаций. Всего: 388236
🔄 Запрос #4465 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 104 спецификаций. Всего: 388340
🔄 Запрос #4466 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 85 спецификаций. Всего: 388425
🔄 Запрос #4467 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 86 спецификаций. Всего: 388511
🔄 Запрос #4468 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 80 спецификаций. Всего: 388591
🔄 Запрос #4469 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 73 спецификаций. Всего: 388664
🔄 Запрос #4470 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 117 спецификаций. Всего: 388781
🔄 Запрос #4471 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 167 спецификаций. Всего: 388948
🔄 Запрос #4472 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 121 спецификаций. Всего: 389069
🔄 Запрос #4473 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 100 спецификаций. Всего: 389169
🔄 Запрос #4474 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 76 спецификаций. Всего: 389245
🔄 Запрос #4475 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 389348
🔄 Запрос #4476 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 97 спецификаций. Всего: 389445

🔄 Запрос #4477 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 389548
🔄 Запрос #4478 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 99 спецификаций. Всего: 389647
🔄 Запрос #4479 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 389756
🔄 Запрос #4480 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 389868
🔄 Запрос #4481 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 83 спецификаций. Всего: 389951
🔄 Запрос #4482 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 390062
🔄 Запрос #4483 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 79 спецификаций. Всего: 390141
🔄 Запрос #4484 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 72 спецификаций. Всего: 390213
🔄 Запрос #4485 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 97 спецификаций. Всего: 390310
🔄 Запрос #4486 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 390421
🔄 Запрос #4487 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 63 спецификаций. Всего: 390484
🔄 Запрос #4488 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 74 спецификаций. Всего: 390558
🔄 Запрос #4489 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 390673
🔄 Запрос #4490 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 54 спецификаций. Всего: 390727
🔄 Запрос #4491 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 2 спецификаций. Всего: 390729
🔄 Запрос #4492 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 2 спецификаций. Всего: 390731
🔄 Запрос #4493 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 68 спецификаций. Всего: 390799
🔄 Запрос #4494 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 390892
🔄 Запрос #4495 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 50 спецификаций. Всего: 390942
🔄 Запрос #4496 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 74 спецификаций. Всего: 391016
🔄 Запрос #4497 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 2 спецификаций. Всего: 391018
🔄 Запрос #4498 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 59 спецификаций. Всего: 391077
🔄 Запрос #4499 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 391193
🔄 Запрос #4500 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 391284
🔄 Запрос #4501 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 391389
🔄 Запрос #4502 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 60 спецификаций. Всего: 391449
🔄 Запрос #4503 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 391537
🔄 Запрос #4504 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 37 спецификаций. Всего: 391574
🔄 Запрос #4505 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 3 спецификаций. Всего: 391577
🔄 Запрос #4506 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 1 спецификаций. Всего: 391578
🔄 Запрос #4507 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 0 спецификаций. Всего: 391578
🔄 Запрос #4508 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 2 спецификаций. Всего: 391580
🔄 Запрос #4509 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 0 спецификаций. Всего: 391580
🔄 Запрос #4510 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 2 спецификаций. Всего: 391582
🔄 Запрос #4511 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 2 спецификаций. Всего: 391584
🔄 Запрос #4512 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 20 спецификаций. Всего: 391604
🔄 Запрос #4513 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 125 спецификаций. Всего: 391729
🔄 Запрос #4514 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 95 спецификаций. Всего: 391824
🔄 Запрос #4515 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 73 спецификаций. Всего: 391897
🔄 Запрос #4516 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 391991
🔄 Запрос #4517 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 392102
📤 Сохранено 10072 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #4518 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 69 спецификаций. Всего: 392171
🔄 Запрос #4519 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 135 спецификаций. Всего: 392306
🔄 Запрос #4520 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 13 спецификаций. Всего: 392319
🔄 Запрос #4521 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 75 спецификаций. Всего: 392394
🔄 Запрос #4522 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 392505
🔄 Запрос #4523 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 392624
🔄 Запрос #4524 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 132 спецификаций. Всего: 392756
🔄 Запрос #4525 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 53 спецификаций. Всего: 392809
🔄 Запрос #4526 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 392914
🔄 Запрос #4527 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 97 спецификаций. Всего: 393011
🔄 Запрос #4528 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 18 спецификаций. Всего: 393029
🔄 Запрос #4529 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 4 спецификаций. Всего: 393033
🔄 Запрос #4530 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 393120
🔄 Запрос #4531 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 393239
🔄 Запрос #4532 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 393341
🔄 Запрос #4533 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 130 спецификаций. Всего: 393471
🔄 Запрос #4534 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 100 спецификаций. Всего: 393571
🔄 Запрос #4535 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 63 спецификаций. Всего: 393634
🔄 Запрос #4536 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 393753
🔄 Запрос #4537 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 393854
🔄 Запрос #4538 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 393963
🔄 Запрос #4539 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 65 спецификаций. Всего: 394028
🔄 Запрос #4540 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 394136
🔄 Запрос #4541 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 394248
🔄 Запрос #4542 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 47 спецификаций. Всего: 394295
🔄 Запрос #4543 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 117 спецификаций. Всего: 394412
🔄 Запрос #4544 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 394525
🔄 Запрос #4545 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 70 спецификаций. Всего: 394595
🔄 Запрос #4546 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 394707
🔄 Запрос #4547 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 394805
🔄 Запрос #4548 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 394920
🔄 Запрос #4549 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 41 спецификаций. Всего: 394961
🔄 Запрос #4550 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 45 спецификаций. Всего: 395006
🔄 Запрос #4551 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 76 спецификаций. Всего: 395082
🔄 Запрос #4552 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09

📥 Загружено 68 спецификаций. Всего: 395150
🔄 Запрос #4553 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 116 спецификаций. Всего: 395266
🔄 Запрос #4554 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 158 спецификаций. Всего: 395424
🔄 Запрос #4555 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 395520
🔄 Запрос #4556 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 139 спецификаций. Всего: 395659
🔄 Запрос #4557 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 151 спецификаций. Всего: 395810
🔄 Запрос #4558 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 115 спецификаций. Всего: 395925
🔄 Запрос #4559 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 31 спецификаций. Всего: 395956
🔄 Запрос #4560 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 396065
🔄 Запрос #4561 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 104 спецификаций. Всего: 396169
🔄 Запрос #4562 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 396256
🔄 Запрос #4563 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 396369
🔄 Запрос #4564 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 140 спецификаций. Всего: 396509
🔄 Запрос #4565 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 13 спецификаций. Всего: 396522
🔄 Запрос #4566 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 396615
🔄 Запрос #4567 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 118 спецификаций. Всего: 396733
🔄 Запрос #4568 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 396843
🔄 Запрос #4569 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 396955
🔄 Запрос #4570 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 62 спецификаций. Всего: 397017
🔄 Запрос #4571 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 82 спецификаций. Всего: 397099
🔄 Запрос #4572 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 397215
🔄 Запрос #4573 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 89 спецификаций. Всего: 397304
🔄 Запрос #4574 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 397395
🔄 Запрос #4575 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 22 спецификаций. Всего: 397417
🔄 Запрос #4576 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 397543
🔄 Запрос #4577 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 397666
🔄 Запрос #4578 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 130 спецификаций. Всего: 397796
🔄 Запрос #4579 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 397915
🔄 Запрос #4580 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 122 спецификаций. Всего: 398037
🔄 Запрос #4581 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 127 спецификаций. Всего: 398164
🔄 Запрос #4582 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 398255
🔄 Запрос #4583 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 398360
🔄 Запрос #4584 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 79 спецификаций. Всего: 398439
🔄 Запрос #4585 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 398544
🔄 Запрос #4586 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 398647
🔄 Запрос #4587 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 398760
🔄 Запрос #4588 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 398883
🔄 Запрос #4589 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 69 спецификаций. Всего: 398952
🔄 Запрос #4590 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 139 спецификаций. Всего: 399091
🔄 Запрос #4591 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 399198
🔄 Запрос #4592 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 86 спецификаций. Всего: 399284
🔄 Запрос #4593 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 70 спецификаций. Всего: 399354
🔄 Запрос #4594 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 62 спецификаций. Всего: 399416
🔄 Запрос #4595 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 399509
🔄 Запрос #4596 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 399619
🔄 Запрос #4597 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 95 спецификаций. Всего: 399714
🔄 Запрос #4598 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 399810
🔄 Запрос #4599 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 399898
🔄 Запрос #4600 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 99 спецификаций. Всего: 399997
🔄 Запрос #4601 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 81 спецификаций. Всего: 400078
🔄 Запрос #4602 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 400171
🔄 Запрос #4603 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 24 спецификаций. Всего: 400195
🔄 Запрос #4604 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 400319
🔄 Запрос #4605 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 400420
🔄 Запрос #4606 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 64 спецификаций. Всего: 400484
🔄 Запрос #4607 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 32 спецификаций. Всего: 400516
🔄 Запрос #4608 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 400607
🔄 Запрос #4609 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 400703
🔄 Запрос #4610 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 76 спецификаций. Всего: 400779
🔄 Запрос #4611 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 62 спецификаций. Всего: 400841
🔄 Запрос #4612 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 74 спецификаций. Всего: 400915
🔄 Запрос #4613 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 401008
🔄 Запрос #4614 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 401092
🔄 Запрос #4615 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 64 спецификаций. Всего: 401156
🔄 Запрос #4616 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 99 спецификаций. Всего: 401255
🔄 Запрос #4617 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 401348
🔄 Запрос #4618 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 129 спецификаций. Всего: 401477
🔄 Запрос #4619 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 133 спецификаций. Всего: 401610
🔄 Запрос #4620 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 401723
🔄 Запрос #4621 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 401830
🔄 Запрос #4622 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 70 спецификаций. Всего: 401900
🔄 Запрос #4623 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 117 спецификаций. Всего: 402017
🔄 Запрос #4624 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 402126
📤 Сохранено 10024 записей в plans_data_spec\plans_combined_spec.parquet

🔄 Запрос #4625 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 402239
🔄 Запрос #4626 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 95 спецификаций. Всего: 402334
🔄 Запрос #4627 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 45 спецификаций. Всего: 402379
🔄 Запрос #4628 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 402472
🔄 Запрос #4629 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 402598
🔄 Запрос #4630 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 130 спецификаций. Всего: 402728
🔄 Запрос #4631 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 82 спецификаций. Всего: 402810
🔄 Запрос #4632 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 402943
🔄 Запрос #4633 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 139 спецификаций. Всего: 403082
🔄 Запрос #4634 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 100 спецификаций. Всего: 403182
🔄 Запрос #4635 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 104 спецификаций. Всего: 403286
🔄 Запрос #4636 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 403388
🔄 Запрос #4637 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 73 спецификаций. Всего: 403461
🔄 Запрос #4638 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 56 спецификаций. Всего: 403517
🔄 Запрос #4639 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 98 спецификаций. Всего: 403615
🔄 Запрос #4640 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 403723
🔄 Запрос #4641 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 174 спецификаций. Всего: 403897
🔄 Запрос #4642 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 148 спецификаций. Всего: 404045
🔄 Запрос #4643 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 122 спецификаций. Всего: 404167
🔄 Запрос #4644 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 128 спецификаций. Всего: 404295
🔄 Запрос #4645 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 11 спецификаций. Всего: 404306
🔄 Запрос #4646 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 86 спецификаций. Всего: 404392
🔄 Запрос #4647 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 95 спецификаций. Всего: 404487
🔄 Запрос #4648 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 404583
🔄 Запрос #4649 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 404684
🔄 Запрос #4650 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 404780
🔄 Запрос #4651 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 99 спецификаций. Всего: 404879
🔄 Запрос #4652 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 405002
🔄 Запрос #4653 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 143 спецификаций. Всего: 405145
🔄 Запрос #4654 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 142 спецификаций. Всего: 405287
🔄 Запрос #4655 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 405395
🔄 Запрос #4656 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 92 спецификаций. Всего: 405487
🔄 Запрос #4657 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 59 спецификаций. Всего: 405546
🔄 Запрос #4658 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 64 спецификаций. Всего: 405610
🔄 Запрос #4659 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 61 спецификаций. Всего: 405671
🔄 Запрос #4660 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 202 спецификаций. Всего: 405873
🔄 Запрос #4661 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 405989
🔄 Запрос #4662 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 69 спецификаций. Всего: 406058
🔄 Запрос #4663 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 75 спецификаций. Всего: 406133
🔄 Запрос #4664 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 406244
🔄 Запрос #4665 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 199 спецификаций. Всего: 406443
🔄 Запрос #4666 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 196 спецификаций. Всего: 406639
🔄 Запрос #4667 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 68 спецификаций. Всего: 406707
🔄 Запрос #4668 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 80 спецификаций. Всего: 406787
🔄 Запрос #4669 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 406897
🔄 Запрос #4670 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 47 спецификаций. Всего: 406944
🔄 Запрос #4671 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 70 спецификаций. Всего: 407014
🔄 Запрос #4672 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 407128
🔄 Запрос #4673 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 407237
🔄 Запрос #4674 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 63 спецификаций. Всего: 407300
🔄 Запрос #4675 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 407396
🔄 Запрос #4676 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 407489
🔄 Запрос #4677 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 71 спецификаций. Всего: 407560
🔄 Запрос #4678 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 104 спецификаций. Всего: 407664
🔄 Запрос #4679 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 90 спецификаций. Всего: 407754
🔄 Запрос #4680 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 142 спецификаций. Всего: 407896
🔄 Запрос #4681 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 407999
🔄 Запрос #4682 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 54 спецификаций. Всего: 408053
🔄 Запрос #4683 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 72 спецификаций. Всего: 408125
🔄 Запрос #4684 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 408212
🔄 Запрос #4685 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 408321
🔄 Запрос #4686 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 408447
🔄 Запрос #4687 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 136 спецификаций. Всего: 408583
🔄 Запрос #4688 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 199 спецификаций. Всего: 408782
🔄 Запрос #4689 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 137 спецификаций. Всего: 408919
🔄 Запрос #4690 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 127 спецификаций. Всего: 409046
🔄 Запрос #4691 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 149 спецификаций. Всего: 409195
🔄 Запрос #4692 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 128 спецификаций. Всего: 409323
🔄 Запрос #4693 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 409446
🔄 Запрос #4694 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 143 спецификаций. Всего: 409589
🔄 Запрос #4695 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 134 спецификаций. Всего: 409723
🔄 Запрос #4696 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 118 спецификаций. Всего: 409841
🔄 Запрос #4697 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 130 спецификаций. Всего: 409971

🔄 Запрос #4698 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 83 спецификаций. Всего: 410054
🔄 Запрос #4699 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 410170
🔄 Запрос #4700 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 39 спецификаций. Всего: 410209
🔄 Запрос #4701 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 48 спецификаций. Всего: 410257
🔄 Запрос #4702 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 410369
🔄 Запрос #4703 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 76 спецификаций. Всего: 410445
🔄 Запрос #4704 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 410543
🔄 Запрос #4705 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 410636
🔄 Запрос #4706 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 66 спецификаций. Всего: 410702
🔄 Запрос #4707 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 31 спецификаций. Всего: 410733
🔄 Запрос #4708 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 410820
🔄 Запрос #4709 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 90 спецификаций. Всего: 410910
🔄 Запрос #4710 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 81 спецификаций. Всего: 410991
🔄 Запрос #4711 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 80 спецификаций. Всего: 411071
🔄 Запрос #4712 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 73 спецификаций. Всего: 411144
🔄 Запрос #4713 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 83 спецификаций. Всего: 411227
🔄 Запрос #4714 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 92 спецификаций. Всего: 411319
🔄 Запрос #4715 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 14 спецификаций. Всего: 411333
🔄 Запрос #4716 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 28 спецификаций. Всего: 411361
🔄 Запрос #4717 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 72 спецификаций. Всего: 411433
🔄 Запрос #4718 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 81 спецификаций. Всего: 411514
🔄 Запрос #4719 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 71 спецификаций. Всего: 411585
🔄 Запрос #4720 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 73 спецификаций. Всего: 411658
🔄 Запрос #4721 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 411745
🔄 Запрос #4722 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 81 спецификаций. Всего: 411826
🔄 Запрос #4723 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 78 спецификаций. Всего: 411904
🔄 Запрос #4724 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 66 спецификаций. Всего: 411970
🔄 Запрос #4725 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 412064
🔄 Запрос #4726 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 135 спецификаций. Всего: 412199
📤 Сохранено 10073 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #4727 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 77 спецификаций. Всего: 412276
🔄 Запрос #4728 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 412363
🔄 Запрос #4729 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 95 спецификаций. Всего: 412458
🔄 Запрос #4730 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 86 спецификаций. Всего: 412544
🔄 Запрос #4731 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 48 спецификаций. Всего: 412592
🔄 Запрос #4732 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 78 спецификаций. Всего: 412670
🔄 Запрос #4733 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 100 спецификаций. Всего: 412770
🔄 Запрос #4734 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 140 спецификаций. Всего: 412910
🔄 Запрос #4735 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 86 спецификаций. Всего: 412996
🔄 Запрос #4736 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 413094
🔄 Запрос #4737 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 413204
🔄 Запрос #4738 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 413295
🔄 Запрос #4739 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 413398
🔄 Запрос #4740 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 89 спецификаций. Всего: 413487
🔄 Запрос #4741 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 413575
🔄 Запрос #4742 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 73 спецификаций. Всего: 413648
🔄 Запрос #4743 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 74 спецификаций. Всего: 413722
🔄 Запрос #4744 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 65 спецификаций. Всего: 413787
🔄 Запрос #4745 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 413883
🔄 Запрос #4746 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 413974
🔄 Запрос #4747 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 4 спецификаций. Всего: 413978
🔄 Запрос #4748 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 414096
🔄 Запрос #4749 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 414194
🔄 Запрос #4750 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 414295
🔄 Запрос #4751 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 78 спецификаций. Всего: 414373
🔄 Запрос #4752 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 100 спецификаций. Всего: 414473
🔄 Запрос #4753 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 414599
🔄 Запрос #4754 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 150 спецификаций. Всего: 414749
🔄 Запрос #4755 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 414845
🔄 Запрос #4756 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 414948
🔄 Запрос #4757 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 85 спецификаций. Всего: 415033
🔄 Запрос #4758 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 97 спецификаций. Всего: 415130
🔄 Запрос #4759 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 65 спецификаций. Всего: 415195
🔄 Запрос #4760 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 72 спецификаций. Всего: 415267
🔄 Запрос #4761 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 415360
🔄 Запрос #4762 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 99 спецификаций. Всего: 415459
🔄 Запрос #4763 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 415566
🔄 Запрос #4764 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 70 спецификаций. Всего: 415636
🔄 Запрос #4765 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 415729
🔄 Запрос #4766 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 415842
🔄 Запрос #4767 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 415965
🔄 Запрос #4768 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 416056
🔄 Запрос #4769 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 77 спецификаций. Всего: 416133
🔄 Запрос #4770 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 416227
🔄 Запрос #4771 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 92 спецификаций. Всего: 416319
🔄 Запрос #4772 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 89 спецификаций. Всего: 416408
🔄 Запрос #4773 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09

📥 Загружено 95 спецификаций. Всего: 416503
🔄 Запрос #4774 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 69 спецификаций. Всего: 416572
🔄 Запрос #4775 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 75 спецификаций. Всего: 416647
🔄 Запрос #4776 для 2024-12-05 20:44:09 - 2024-12-12 20:44:09
📥 Загружено 40 спецификаций. Всего: 416687
📅 Обрабатываем диапазон 2024-11-28 20:44:09 - 2024-12-05 20:44:09 (попытка 1/5)
🔄 Запрос #4777 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 90 спецификаций. Всего: 416777
🔄 Запрос #4778 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 89 спецификаций. Всего: 416866
🔄 Запрос #4779 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 83 спецификаций. Всего: 416949
🔄 Запрос #4780 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 417058
🔄 Запрос #4781 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 417176
🔄 Запрос #4782 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 116 спецификаций. Всего: 417292
🔄 Запрос #4783 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 122 спецификаций. Всего: 417414
🔄 Запрос #4784 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 134 спецификаций. Всего: 417548
🔄 Запрос #4785 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 126 спецификаций. Всего: 417674
🔄 Запрос #4786 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 138 спецификаций. Всего: 417812
🔄 Запрос #4787 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 137 спецификаций. Всего: 417949
🔄 Запрос #4788 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 418063
🔄 Запрос #4789 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 418180
🔄 Запрос #4790 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 125 спецификаций. Всего: 418305
🔄 Запрос #4791 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 131 спецификаций. Всего: 418436
🔄 Запрос #4792 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 123 спецификаций. Всего: 418559
🔄 Запрос #4793 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 111 спецификаций. Всего: 418670
🔄 Запрос #4794 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 105 спецификаций. Всего: 418775
🔄 Запрос #4795 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 418877
🔄 Запрос #4796 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 418979
🔄 Запрос #4797 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 419081
🔄 Запрос #4798 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 419180
🔄 Запрос #4799 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 419286
🔄 Запрос #4800 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 125 спецификаций. Всего: 419411
🔄 Запрос #4801 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 419528
🔄 Запрос #4802 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 419635
🔄 Запрос #4803 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 112 спецификаций. Всего: 419747
🔄 Запрос #4804 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 419861
🔄 Запрос #4805 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 419967
🔄 Запрос #4806 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 105 спецификаций. Всего: 420072
🔄 Запрос #4807 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 420173
🔄 Запрос #4808 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 420264
🔄 Запрос #4809 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 143 спецификаций. Всего: 420407
🔄 Запрос #4810 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 140 спецификаций. Всего: 420547
🔄 Запрос #4811 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 141 спецификаций. Всего: 420688
🔄 Запрос #4812 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 154 спецификаций. Всего: 420842
🔄 Запрос #4813 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 420933
🔄 Запрос #4814 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 93 спецификаций. Всего: 421026
🔄 Запрос #4815 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 57 спецификаций. Всего: 421083
🔄 Запрос #4816 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 83 спецификаций. Всего: 421166
🔄 Запрос #4817 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 53 спецификаций. Всего: 421219
🔄 Запрос #4818 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 421323
🔄 Запрос #4819 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 421414
🔄 Запрос #4820 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 125 спецификаций. Всего: 421539
🔄 Запрос #4821 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 130 спецификаций. Всего: 421669
🔄 Запрос #4822 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 126 спецификаций. Всего: 421795
🔄 Запрос #4823 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 421908
🔄 Запрос #4824 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 77 спецификаций. Всего: 421985
🔄 Запрос #4825 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 422094
🔄 Запрос #4826 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 124 спецификаций. Всего: 422218
📤 Сохранено 10019 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #4827 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 422332
🔄 Запрос #4828 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 422435
🔄 Запрос #4829 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 422526
🔄 Запрос #4830 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 422618
🔄 Запрос #4831 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 110 спецификаций. Всего: 422728
🔄 Запрос #4832 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 126 спецификаций. Всего: 422854
🔄 Запрос #4833 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 422946
🔄 Запрос #4834 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 21 спецификаций. Всего: 422967
🔄 Запрос #4835 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 423066
🔄 Запрос #4836 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 75 спецификаций. Всего: 423141
🔄 Запрос #4837 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 15 спецификаций. Всего: 423156
🔄 Запрос #4838 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 82 спецификаций. Всего: 423238
🔄 Запрос #4839 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 67 спецификаций. Всего: 423305
🔄 Запрос #4840 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 58 спецификаций. Всего: 423363
🔄 Запрос #4841 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 27 спецификаций. Всего: 423390
🔄 Запрос #4842 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 61 спецификаций. Всего: 423451
🔄 Запрос #4843 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 96 спецификаций. Всего: 423547
🔄 Запрос #4844 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 95 спецификаций. Всего: 423642
🔄 Запрос #4845 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 423759
🔄 Запрос #4846 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 138 спецификаций. Всего: 423897
🔄 Запрос #4847 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 423998
🔄 Запрос #4848 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 424089

🔄 Запрос #4849 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 424188
🔄 Запрос #4850 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 424294
🔄 Запрос #4851 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 424411
🔄 Запрос #4852 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 424515
🔄 Запрос #4853 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 21 спецификаций. Всего: 424536
🔄 Запрос #4854 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 3 спецификаций. Всего: 424539
🔄 Запрос #4855 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 82 спецификаций. Всего: 424621
🔄 Запрос #4856 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 73 спецификаций. Всего: 424694
🔄 Запрос #4857 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 58 спецификаций. Всего: 424752
🔄 Запрос #4858 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 424861
🔄 Запрос #4859 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 100 спецификаций. Всего: 424961
🔄 Запрос #4860 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 425064
🔄 Запрос #4861 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 425168
🔄 Запрос #4862 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 85 спецификаций. Всего: 425253
🔄 Запрос #4863 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 69 спецификаций. Всего: 425322
🔄 Запрос #4864 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 159 спецификаций. Всего: 425481
🔄 Запрос #4865 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 78 спецификаций. Всего: 425559
🔄 Запрос #4866 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 179 спецификаций. Всего: 425738
🔄 Запрос #4867 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 425855
🔄 Запрос #4868 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 125 спецификаций. Всего: 425980
🔄 Запрос #4869 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 144 спецификаций. Всего: 426124
🔄 Запрос #4870 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 154 спецификаций. Всего: 426278
🔄 Запрос #4871 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 139 спецификаций. Всего: 426417
🔄 Запрос #4872 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 143 спецификаций. Всего: 426560
🔄 Запрос #4873 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 426662
🔄 Запрос #4874 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 130 спецификаций. Всего: 426792
🔄 Запрос #4875 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 426898
🔄 Запрос #4876 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 76 спецификаций. Всего: 426974
🔄 Запрос #4877 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 427091
🔄 Запрос #4878 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 64 спецификаций. Всего: 427155
🔄 Запрос #4879 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 124 спецификаций. Всего: 427279
🔄 Запрос #4880 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 31 спецификаций. Всего: 427310
🔄 Запрос #4881 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 427424
🔄 Запрос #4882 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 89 спецификаций. Всего: 427513
🔄 Запрос #4883 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 74 спецификаций. Всего: 427587
🔄 Запрос #4884 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 121 спецификаций. Всего: 427708
🔄 Запрос #4885 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 427815
🔄 Запрос #4886 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 98 спецификаций. Всего: 427913
🔄 Запрос #4887 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 428027
🔄 Запрос #4888 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 428128
🔄 Запрос #4889 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 123 спецификаций. Всего: 428251
🔄 Запрос #4890 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 428369
🔄 Запрос #4891 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 115 спецификаций. Всего: 428484
🔄 Запрос #4892 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 428602
🔄 Запрос #4893 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 131 спецификаций. Всего: 428733
🔄 Запрос #4894 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 428837
🔄 Запрос #4895 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 70 спецификаций. Всего: 428907
🔄 Запрос #4896 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 429021
🔄 Запрос #4897 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 116 спецификаций. Всего: 429137
🔄 Запрос #4898 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 130 спецификаций. Всего: 429267
🔄 Запрос #4899 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 127 спецификаций. Всего: 429394
🔄 Запрос #4900 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 81 спецификаций. Всего: 429475
🔄 Запрос #4901 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 111 спецификаций. Всего: 429586
🔄 Запрос #4902 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 429685
🔄 Запрос #4903 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 164 спецификаций. Всего: 429849
🔄 Запрос #4904 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 429950
🔄 Запрос #4905 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 430057
🔄 Запрос #4906 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 430171
🔄 Запрос #4907 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 430274
🔄 Запрос #4908 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 94 спецификаций. Всего: 430368
🔄 Запрос #4909 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 430470
🔄 Запрос #4910 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 430573
🔄 Запрос #4911 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 61 спецификаций. Всего: 430634
🔄 Запрос #4912 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 76 спецификаций. Всего: 430710
🔄 Запрос #4913 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 430817
🔄 Запрос #4914 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 430909
🔄 Запрос #4915 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 431012
🔄 Запрос #4916 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 431125
🔄 Запрос #4917 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 431211
🔄 Запрос #4918 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 97 спецификаций. Всего: 431308
🔄 Запрос #4919 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 431410
🔄 Запрос #4920 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 83 спецификаций. Всего: 431493
🔄 Запрос #4921 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 98 спецификаций. Всего: 431591
🔄 Запрос #4922 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 122 спецификаций. Всего: 431713
🔄 Запрос #4923 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 111 спецификаций. Всего: 431824
🔄 Запрос #4924 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 64 спецификаций. Всего: 431888

🔄 Запрос #4925 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 432005
🔄 Запрос #4926 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 432114
🔄 Запрос #4927 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 432210
🔄 Запрос #4928 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 432314
📤 Сохранено 10096 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #4929 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 127 спецификаций. Всего: 432441
🔄 Запрос #4930 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 54 спецификаций. Всего: 432495
🔄 Запрос #4931 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 432601
🔄 Запрос #4932 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 432692
🔄 Запрос #4933 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 120 спецификаций. Всего: 432812
🔄 Запрос #4934 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 73 спецификаций. Всего: 432885
🔄 Запрос #4935 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 432988
🔄 Запрос #4936 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 433090
🔄 Запрос #4937 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 433197
🔄 Запрос #4938 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 123 спецификаций. Всего: 433320
🔄 Запрос #4939 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 433426
🔄 Запрос #4940 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 433525
🔄 Запрос #4941 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 433631
🔄 Запрос #4942 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 433734
🔄 Запрос #4943 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 89 спецификаций. Всего: 433823
🔄 Запрос #4944 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 88 спецификаций. Всего: 433911
🔄 Запрос #4945 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 433997
🔄 Запрос #4946 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 94 спецификаций. Всего: 434091
🔄 Запрос #4947 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 61 спецификаций. Всего: 434152
🔄 Запрос #4948 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 47 спецификаций. Всего: 434199
🔄 Запрос #4949 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 49 спецификаций. Всего: 434248
🔄 Запрос #4950 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 153 спецификаций. Всего: 434401
🔄 Запрос #4951 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 122 спецификаций. Всего: 434523
🔄 Запрос #4952 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 111 спецификаций. Всего: 434634
🔄 Запрос #4953 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 119 спецификаций. Всего: 434753
🔄 Запрос #4954 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 434854
🔄 Запрос #4955 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 434953
🔄 Запрос #4956 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 115 спецификаций. Всего: 435068
🔄 Запрос #4957 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 435171
🔄 Запрос #4958 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 59 спецификаций. Всего: 435230
🔄 Запрос #4959 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 112 спецификаций. Всего: 435342
🔄 Запрос #4960 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 121 спецификаций. Всего: 435463
🔄 Запрос #4961 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 137 спецификаций. Всего: 435600
🔄 Запрос #4962 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 133 спецификаций. Всего: 435733
🔄 Запрос #4963 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 435851
🔄 Запрос #4964 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 119 спецификаций. Всего: 435970
🔄 Запрос #4965 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 436073
🔄 Запрос #4966 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 95 спецификаций. Всего: 436168
🔄 Запрос #4967 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 126 спецификаций. Всего: 436294
🔄 Запрос #4968 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 84 спецификаций. Всего: 436378
🔄 Запрос #4969 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 96 спецификаций. Всего: 436474
🔄 Запрос #4970 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 436566
🔄 Запрос #4971 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 436675
🔄 Запрос #4972 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 98 спецификаций. Всего: 436773
🔄 Запрос #4973 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 436859
🔄 Запрос #4974 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 436945
🔄 Запрос #4975 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 75 спецификаций. Всего: 437020
🔄 Запрос #4976 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 82 спецификаций. Всего: 437102
🔄 Запрос #4977 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 82 спецификаций. Всего: 437184
🔄 Запрос #4978 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 82 спецификаций. Всего: 437266
🔄 Запрос #4979 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 94 спецификаций. Всего: 437360
🔄 Запрос #4980 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 77 спецификаций. Всего: 437437
🔄 Запрос #4981 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 80 спецификаций. Всего: 437517
🔄 Запрос #4982 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 70 спецификаций. Всего: 437587
🔄 Запрос #4983 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 437686
🔄 Запрос #4984 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 55 спецификаций. Всего: 437741
🔄 Запрос #4985 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 72 спецификаций. Всего: 437813
🔄 Запрос #4986 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 75 спецификаций. Всего: 437888
🔄 Запрос #4987 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 76 спецификаций. Всего: 437964
🔄 Запрос #4988 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 83 спецификаций. Всего: 438047
🔄 Запрос #4989 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 75 спецификаций. Всего: 438122
🔄 Запрос #4990 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 78 спецификаций. Всего: 438200
🔄 Запрос #4991 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 41 спецификаций. Всего: 438241
🔄 Запрос #4992 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 75 спецификаций. Всего: 438316
🔄 Запрос #4993 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 72 спецификаций. Всего: 438388
🔄 Запрос #4994 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 61 спецификаций. Всего: 438449
🔄 Запрос #4995 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 63 спецификаций. Всего: 438512
🔄 Запрос #4996 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 83 спецификаций. Всего: 438595
🔄 Запрос #4997 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 78 спецификаций. Всего: 438673
🔄 Запрос #4998 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09

📥 Загружено 72 спецификаций. Всего: 438745
🔄 Запрос #4999 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 62 спецификаций. Всего: 438807
🔄 Запрос #5000 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 60 спецификаций. Всего: 438867
🔄 Запрос #5001 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 54 спецификаций. Всего: 438921
🔄 Запрос #5002 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 69 спецификаций. Всего: 438990
🔄 Запрос #5003 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 77 спецификаций. Всего: 439067
🔄 Запрос #5004 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 119 спецификаций. Всего: 439186
🔄 Запрос #5005 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 116 спецификаций. Всего: 439302
🔄 Запрос #5006 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 85 спецификаций. Всего: 439387
🔄 Запрос #5007 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 64 спецификаций. Всего: 439451
🔄 Запрос #5008 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 80 спецификаций. Всего: 439531
🔄 Запрос #5009 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 68 спецификаций. Всего: 439599
🔄 Запрос #5010 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 81 спецификаций. Всего: 439680
🔄 Запрос #5011 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 70 спецификаций. Всего: 439750
🔄 Запрос #5012 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 89 спецификаций. Всего: 439839
🔄 Запрос #5013 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 105 спецификаций. Всего: 439944
🔄 Запрос #5014 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 77 спецификаций. Всего: 440021
🔄 Запрос #5015 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 98 спецификаций. Всего: 440119
🔄 Запрос #5016 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 87 спецификаций. Всего: 440206
🔄 Запрос #5017 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 57 спецификаций. Всего: 440263
🔄 Запрос #5018 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 43 спецификаций. Всего: 440306
🔄 Запрос #5019 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 72 спецификаций. Всего: 440378
🔄 Запрос #5020 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 127 спецификаций. Всего: 440505
🔄 Запрос #5021 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 440606
🔄 Запрос #5022 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 440698
🔄 Запрос #5023 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 440801
🔄 Запрос #5024 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 83 спецификаций. Всего: 440884
🔄 Запрос #5025 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 76 спецификаций. Всего: 440960
🔄 Запрос #5026 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 94 спецификаций. Всего: 441054
🔄 Запрос #5027 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 96 спецификаций. Всего: 441150
🔄 Запрос #5028 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 94 спецификаций. Всего: 441244
🔄 Запрос #5029 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 108 спецификаций. Всего: 441352
🔄 Запрос #5030 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 70 спецификаций. Всего: 441422
🔄 Запрос #5031 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 80 спецификаций. Всего: 441502
🔄 Запрос #5032 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 100 спецификаций. Всего: 441602
🔄 Запрос #5033 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 89 спецификаций. Всего: 441691
🔄 Запрос #5034 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 441800
🔄 Запрос #5035 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 96 спецификаций. Всего: 441896
🔄 Запрос #5036 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 124 спецификаций. Всего: 442020
🔄 Запрос #5037 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 139 спецификаций. Всего: 442159
🔄 Запрос #5038 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 76 спецификаций. Всего: 442235
🔄 Запрос #5039 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 105 спецификаций. Всего: 442340
📤 Сохранено 10026 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #5040 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 105 спецификаций. Всего: 442445
🔄 Запрос #5041 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 0 спецификаций. Всего: 442445
🔄 Запрос #5042 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 55 спецификаций. Всего: 442500
🔄 Запрос #5043 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 442586
🔄 Запрос #5044 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 126 спецификаций. Всего: 442712
🔄 Запрос #5045 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 97 спецификаций. Всего: 442809
🔄 Запрос #5046 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 132 спецификаций. Всего: 442941
🔄 Запрос #5047 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 94 спецификаций. Всего: 443035
🔄 Запрос #5048 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 83 спецификаций. Всего: 443118
🔄 Запрос #5049 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 131 спецификаций. Всего: 443249
🔄 Запрос #5050 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 129 спецификаций. Всего: 443378
🔄 Запрос #5051 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 144 спецификаций. Всего: 443522
🔄 Запрос #5052 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 173 спецификаций. Всего: 443695
🔄 Запрос #5053 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 131 спецификаций. Всего: 443826
🔄 Запрос #5054 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 443930
🔄 Запрос #5055 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 137 спецификаций. Всего: 444067
🔄 Запрос #5056 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 444170
🔄 Запрос #5057 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 111 спецификаций. Всего: 444281
🔄 Запрос #5058 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 154 спецификаций. Всего: 444435
🔄 Запрос #5059 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 139 спецификаций. Всего: 444574
🔄 Запрос #5060 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 444680
🔄 Запрос #5061 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 159 спецификаций. Всего: 444839
🔄 Запрос #5062 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 444943
🔄 Запрос #5063 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 445057
🔄 Запрос #5064 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 445163
🔄 Запрос #5065 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 445264
🔄 Запрос #5066 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 445368
🔄 Запрос #5067 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 445485
🔄 Запрос #5068 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 98 спецификаций. Всего: 445583
🔄 Запрос #5069 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 445685
🔄 Запрос #5070 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 110 спецификаций. Всего: 445795
🔄 Запрос #5071 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 445894
🔄 Запрос #5072 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 445993
🔄 Запрос #5073 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 446085
🔄 Запрос #5074 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 147 спецификаций. Всего: 446232

🔄 Запрос #5075 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 446346
🔄 Запрос #5076 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 446432
🔄 Запрос #5077 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 77 спецификаций. Всего: 446509
🔄 Запрос #5078 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 89 спецификаций. Всего: 446598
🔄 Запрос #5079 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 95 спецификаций. Всего: 446693
🔄 Запрос #5080 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 446807
🔄 Запрос #5081 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 446913
🔄 Запрос #5082 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 90 спецификаций. Всего: 447003
🔄 Запрос #5083 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 108 спецификаций. Всего: 447111
🔄 Запрос #5084 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 447217
🔄 Запрос #5085 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 447303
🔄 Запрос #5086 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 85 спецификаций. Всего: 447388
🔄 Запрос #5087 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 2 спецификаций. Всего: 447390
🔄 Запрос #5088 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 14 спецификаций. Всего: 447404
🔄 Запрос #5089 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 53 спецификаций. Всего: 447457
🔄 Запрос #5090 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 64 спецификаций. Всего: 447521
🔄 Запрос #5091 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 39 спецификаций. Всего: 447560
🔄 Запрос #5092 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 447659
🔄 Запрос #5093 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 447765
🔄 Запрос #5094 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 88 спецификаций. Всего: 447853
🔄 Запрос #5095 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 98 спецификаций. Всего: 447951
🔄 Запрос #5096 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 81 спецификаций. Всего: 448032
🔄 Запрос #5097 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 123 спецификаций. Всего: 448155
🔄 Запрос #5098 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 448247
🔄 Запрос #5099 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 110 спецификаций. Всего: 448357
🔄 Запрос #5100 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 122 спецификаций. Всего: 448479
🔄 Запрос #5101 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 110 спецификаций. Всего: 448589
🔄 Запрос #5102 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 105 спецификаций. Всего: 448694
🔄 Запрос #5103 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 448777
🔄 Запрос #5104 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 27 спецификаций. Всего: 448804
🔄 Запрос #5105 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 68 спецификаций. Всего: 448872
🔄 Запрос #5106 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 100 спецификаций. Всего: 448972
🔄 Запрос #5107 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 449064
🔄 Запрос #5108 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 449155
🔄 Запрос #5109 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 449261
🔄 Запрос #5110 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 449360
🔄 Запрос #5111 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 47 спецификаций. Всего: 449407
🔄 Запрос #5112 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 2 спецификаций. Всего: 449409
🔄 Запрос #5113 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 23 спецификаций. Всего: 449432
🔄 Запрос #5114 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 449534
🔄 Запрос #5115 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 79 спецификаций. Всего: 449613
🔄 Запрос #5116 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 449716
🔄 Запрос #5117 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 449825
🔄 Запрос #5118 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 77 спецификаций. Всего: 449902
🔄 Запрос #5119 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 115 спецификаций. Всего: 450017
🔄 Запрос #5120 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 450120
🔄 Запрос #5121 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 61 спецификаций. Всего: 450181
🔄 Запрос #5122 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 67 спецификаций. Всего: 450248
🔄 Запрос #5123 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 97 спецификаций. Всего: 450345
🔄 Запрос #5124 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 48 спецификаций. Всего: 450393
🔄 Запрос #5125 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 450497
🔄 Запрос #5126 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 39 спецификаций. Всего: 450536
🔄 Запрос #5127 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 450649
🔄 Запрос #5128 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 51 спецификаций. Всего: 450700
🔄 Запрос #5129 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 42 спецификаций. Всего: 450742
🔄 Запрос #5130 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 47 спецификаций. Всего: 450789
🔄 Запрос #5131 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 71 спецификаций. Всего: 450860
🔄 Запрос #5132 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 83 спецификаций. Всего: 450943
🔄 Запрос #5133 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 35 спецификаций. Всего: 450978
🔄 Запрос #5134 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 451070
🔄 Запрос #5135 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 47 спецификаций. Всего: 451117
🔄 Запрос #5136 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 44 спецификаций. Всего: 451161
🔄 Запрос #5137 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 31 спецификаций. Всего: 451192
🔄 Запрос #5138 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 39 спецификаций. Всего: 451231
🔄 Запрос #5139 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 31 спецификаций. Всего: 451262
🔄 Запрос #5140 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 38 спецификаций. Всего: 451300
🔄 Запрос #5141 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 66 спецификаций. Всего: 451366
🔄 Запрос #5142 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 451473
🔄 Запрос #5143 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 151 спецификаций. Всего: 451624
🔄 Запрос #5144 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 139 спецификаций. Всего: 451763
🔄 Запрос #5145 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 41 спецификаций. Всего: 451804
🔄 Запрос #5146 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 14 спецификаций. Всего: 451818
🔄 Запрос #5147 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 50 спецификаций. Всего: 451868
🔄 Запрос #5148 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 95 спецификаций. Всего: 451963
🔄 Запрос #5149 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 57 спецификаций. Всего: 452020
🔄 Запрос #5150 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 71 спецификаций. Всего: 452091
🔄 Запрос #5151 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09

📥 Загружено 88 спецификаций. Всего: 452179
🔄 Запрос #5152 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 146 спецификаций. Всего: 452325
🔄 Запрос #5153 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 81 спецификаций. Всего: 452406
📤 Сохранено 10066 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #5154 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 146 спецификаций. Всего: 452552
🔄 Запрос #5155 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 3 спецификаций. Всего: 452555
🔄 Запрос #5156 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 70 спецификаций. Всего: 452625
🔄 Запрос #5157 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 90 спецификаций. Всего: 452715
🔄 Запрос #5158 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 137 спецификаций. Всего: 452852
🔄 Запрос #5159 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 163 спецификаций. Всего: 453015
🔄 Запрос #5160 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 142 спецификаций. Всего: 453157
🔄 Запрос #5161 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 453261
🔄 Запрос #5162 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 453374
🔄 Запрос #5163 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 95 спецификаций. Всего: 453469
🔄 Запрос #5164 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 125 спецификаций. Всего: 453594
🔄 Запрос #5165 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 139 спецификаций. Всего: 453733
🔄 Запрос #5166 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 453835
🔄 Запрос #5167 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 110 спецификаций. Всего: 453945
🔄 Запрос #5168 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 28 спецификаций. Всего: 453973
🔄 Запрос #5169 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 20 спецификаций. Всего: 453993
🔄 Запрос #5170 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 85 спецификаций. Всего: 454078
🔄 Запрос #5171 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 70 спецификаций. Всего: 454148
🔄 Запрос #5172 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 454234
🔄 Запрос #5173 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 89 спецификаций. Всего: 454323
🔄 Запрос #5174 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 94 спецификаций. Всего: 454417
🔄 Запрос #5175 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 454518
🔄 Запрос #5176 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 454620
🔄 Запрос #5177 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 454738
🔄 Запрос #5178 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 97 спецификаций. Всего: 454835
🔄 Запрос #5179 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 454927
🔄 Запрос #5180 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 95 спецификаций. Всего: 455022
🔄 Запрос #5181 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 123 спецификаций. Всего: 455145
🔄 Запрос #5182 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 121 спецификаций. Всего: 455266
🔄 Запрос #5183 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 115 спецификаций. Всего: 455381
🔄 Запрос #5184 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 3 спецификаций. Всего: 455384
🔄 Запрос #5185 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 53 спецификаций. Всего: 455437
🔄 Запрос #5186 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 85 спецификаций. Всего: 455522
🔄 Запрос #5187 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 455626
🔄 Запрос #5188 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 124 спецификаций. Всего: 455750
🔄 Запрос #5189 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 455854
🔄 Запрос #5190 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 455963
🔄 Запрос #5191 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 172 спецификаций. Всего: 456135
🔄 Запрос #5192 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 146 спецификаций. Всего: 456281
🔄 Запрос #5193 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 126 спецификаций. Всего: 456407
🔄 Запрос #5194 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 100 спецификаций. Всего: 456507
🔄 Запрос #5195 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 456616
🔄 Запрос #5196 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 153 спецификаций. Всего: 456769
🔄 Запрос #5197 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 456879
🔄 Запрос #5198 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 71 спецификаций. Всего: 456950
🔄 Запрос #5199 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 457059
🔄 Запрос #5200 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 457150
🔄 Запрос #5201 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 100 спецификаций. Всего: 457250
🔄 Запрос #5202 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 457351
🔄 Запрос #5203 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 457443
🔄 Запрос #5204 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 77 спецификаций. Всего: 457520
🔄 Запрос #5205 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 457633
🔄 Запрос #5206 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 457719
🔄 Запрос #5207 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 457837
🔄 Запрос #5208 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 457944
🔄 Запрос #5209 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 71 спецификаций. Всего: 458015
🔄 Запрос #5210 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 9 спецификаций. Всего: 458024
🔄 Запрос #5211 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 458142
🔄 Запрос #5212 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 458256
🔄 Запрос #5213 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 458355
🔄 Запрос #5214 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 2 спецификаций. Всего: 458357
🔄 Запрос #5215 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 78 спецификаций. Всего: 458435
🔄 Запрос #5216 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 51 спецификаций. Всего: 458486
🔄 Запрос #5217 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 66 спецификаций. Всего: 458552
🔄 Запрос #5218 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 134 спецификаций. Всего: 458686
🔄 Запрос #5219 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 130 спецификаций. Всего: 458816
🔄 Запрос #5220 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 458902
🔄 Запрос #5221 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 72 спецификаций. Всего: 458974
🔄 Запрос #5222 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 459065
🔄 Запрос #5223 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 80 спецификаций. Всего: 459145
🔄 Запрос #5224 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 66 спецификаций. Всего: 459211
🔄 Запрос #5225 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09

📥 Загружено 81 спецификаций. Всего: 459292
🔄 Запрос #5226 для 2024-11-28 20:44:09 - 2024-12-05 20:44:09
📥 Загружено 6 спецификаций. Всего: 459298
📅 Обрабатываем диапазон 2024-11-21 20:44:09 - 2024-11-28 20:44:09 (попытка 1/5)
🔄 Запрос #5227 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 459379
🔄 Запрос #5228 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 115 спецификаций. Всего: 459494
🔄 Запрос #5229 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 74 спецификаций. Всего: 459568
🔄 Запрос #5230 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 134 спецификаций. Всего: 459702
🔄 Запрос #5231 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 107 спецификаций. Всего: 459809
🔄 Запрос #5232 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 115 спецификаций. Всего: 459924
🔄 Запрос #5233 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 86 спецификаций. Всего: 460010
🔄 Запрос #5234 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 460098
🔄 Запрос #5235 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 83 спецификаций. Всего: 460181
🔄 Запрос #5236 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 85 спецификаций. Всего: 460266
🔄 Запрос #5237 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 460369
🔄 Запрос #5238 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 69 спецификаций. Всего: 460438
🔄 Запрос #5239 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 56 спецификаций. Всего: 460494
🔄 Запрос #5240 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 85 спецификаций. Всего: 460579
🔄 Запрос #5241 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 69 спецификаций. Всего: 460648
🔄 Запрос #5242 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 460744
🔄 Запрос #5243 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 460840
🔄 Запрос #5244 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 82 спецификаций. Всего: 460922
🔄 Запрос #5245 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 100 спецификаций. Всего: 461022
🔄 Запрос #5246 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 109 спецификаций. Всего: 461131
🔄 Запрос #5247 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 84 спецификаций. Всего: 461215
🔄 Запрос #5248 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 51 спецификаций. Всего: 461266
🔄 Запрос #5249 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 2 спецификаций. Всего: 461268
🔄 Запрос #5250 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 1 спецификаций. Всего: 461269
🔄 Запрос #5251 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 67 спецификаций. Всего: 461336
🔄 Запрос #5252 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 461424
🔄 Запрос #5253 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 86 спецификаций. Всего: 461510
🔄 Запрос #5254 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 58 спецификаций. Всего: 461568
🔄 Запрос #5255 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 23 спецификаций. Всего: 461591
🔄 Запрос #5256 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 48 спецификаций. Всего: 461639
🔄 Запрос #5257 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 80 спецификаций. Всего: 461719
🔄 Запрос #5258 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 70 спецификаций. Всего: 461789
🔄 Запрос #5259 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 70 спецификаций. Всего: 461859
🔄 Запрос #5260 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 461940
🔄 Запрос #5261 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 134 спецификаций. Всего: 462074
🔄 Запрос #5262 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 84 спецификаций. Всего: 462158
🔄 Запрос #5263 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 82 спецификаций. Всего: 462240
🔄 Запрос #5264 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 462343
🔄 Запрос #5265 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 75 спецификаций. Всего: 462418
📤 Сохранено 10012 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #5266 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 75 спецификаций. Всего: 462493
🔄 Запрос #5267 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 67 спецификаций. Всего: 462560
🔄 Запрос #5268 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 79 спецификаций. Всего: 462639
🔄 Запрос #5269 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 79 спецификаций. Всего: 462718
🔄 Запрос #5270 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 31 спецификаций. Всего: 462749
🔄 Запрос #5271 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 33 спецификаций. Всего: 462782
🔄 Запрос #5272 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 48 спецификаций. Всего: 462830
🔄 Запрос #5273 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 462918
🔄 Запрос #5274 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 463009
🔄 Запрос #5275 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 114 спецификаций. Всего: 463123
🔄 Запрос #5276 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 463216
🔄 Запрос #5277 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 99 спецификаций. Всего: 463315
🔄 Запрос #5278 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 463408
🔄 Запрос #5279 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 90 спецификаций. Всего: 463498
🔄 Запрос #5280 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 463591
🔄 Запрос #5281 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 463682
🔄 Запрос #5282 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 94 спецификаций. Всего: 463776
🔄 Запрос #5283 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 70 спецификаций. Всего: 463846
🔄 Запрос #5284 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 87 спецификаций. Всего: 463933
🔄 Запрос #5285 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 82 спецификаций. Всего: 464015
🔄 Запрос #5286 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 82 спецификаций. Всего: 464097
🔄 Запрос #5287 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 77 спецификаций. Всего: 464174
🔄 Запрос #5288 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 78 спецификаций. Всего: 464252
🔄 Запрос #5289 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 94 спецификаций. Всего: 464346
🔄 Запрос #5290 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 464437
🔄 Запрос #5291 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 464525
🔄 Запрос #5292 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 77 спецификаций. Всего: 464602
🔄 Запрос #5293 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 109 спецификаций. Всего: 464711
🔄 Запрос #5294 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 84 спецификаций. Всего: 464795
🔄 Запрос #5295 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 68 спецификаций. Всего: 464863
🔄 Запрос #5296 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 464967
🔄 Запрос #5297 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 124 спецификаций. Всего: 465091
🔄 Запрос #5298 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 178 спецификаций. Всего: 465269
🔄 Запрос #5299 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 129 спецификаций. Всего: 465398
🔄 Запрос #5300 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09

📥 Загружено 105 спецификаций. Всего: 465503
🔄 Запрос #5301 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 465599
🔄 Запрос #5302 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 69 спецификаций. Всего: 465668
🔄 Запрос #5303 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 49 спецификаций. Всего: 465717
🔄 Запрос #5304 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 465820
🔄 Запрос #5305 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 100 спецификаций. Всего: 465920
🔄 Запрос #5306 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 125 спецификаций. Всего: 466045
🔄 Запрос #5307 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 131 спецификаций. Всего: 466176
🔄 Запрос #5308 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 146 спецификаций. Всего: 466322
🔄 Запрос #5309 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 139 спецификаций. Всего: 466461
🔄 Запрос #5310 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 117 спецификаций. Всего: 466578
🔄 Запрос #5311 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 106 спецификаций. Всего: 466684
🔄 Запрос #5312 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 109 спецификаций. Всего: 466793
🔄 Запрос #5313 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 70 спецификаций. Всего: 466863
🔄 Запрос #5314 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 466959
🔄 Запрос #5315 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 467062
🔄 Запрос #5316 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 467165
🔄 Запрос #5317 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 105 спецификаций. Всего: 467270
🔄 Запрос #5318 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 467374
🔄 Запрос #5319 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 100 спецификаций. Всего: 467474
🔄 Запрос #5320 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 467555
🔄 Запрос #5321 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 90 спецификаций. Всего: 467645
🔄 Запрос #5322 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 467736
🔄 Запрос #5323 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 89 спецификаций. Всего: 467825
🔄 Запрос #5324 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 467913
🔄 Запрос #5325 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 90 спецификаций. Всего: 468003
🔄 Запрос #5326 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 105 спецификаций. Всего: 468108
🔄 Запрос #5327 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 94 спецификаций. Всего: 468202
🔄 Запрос #5328 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 468290
🔄 Запрос #5329 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 138 спецификаций. Всего: 468428
🔄 Запрос #5330 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 468521
🔄 Запрос #5331 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 71 спецификаций. Всего: 468592
🔄 Запрос #5332 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 25 спецификаций. Всего: 468617
🔄 Запрос #5333 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 20 спецификаций. Всего: 468637
🔄 Запрос #5334 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 20 спецификаций. Всего: 468657
🔄 Запрос #5335 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 22 спецификаций. Всего: 468679
🔄 Запрос #5336 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 15 спецификаций. Всего: 468694
🔄 Запрос #5337 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 49 спецификаций. Всего: 468743
🔄 Запрос #5338 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 468831
🔄 Запрос #5339 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 468922
🔄 Запрос #5340 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 100 спецификаций. Всего: 469022
🔄 Запрос #5341 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 75 спецификаций. Всего: 469097
🔄 Запрос #5342 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 71 спецификаций. Всего: 469168
🔄 Запрос #5343 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 56 спецификаций. Всего: 469224
🔄 Запрос #5344 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 50 спецификаций. Всего: 469274
🔄 Запрос #5345 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 102 спецификаций. Всего: 469376
🔄 Запрос #5346 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 105 спецификаций. Всего: 469481
🔄 Запрос #5347 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 135 спецификаций. Всего: 469616
🔄 Запрос #5348 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 94 спецификаций. Всего: 469710
🔄 Запрос #5349 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 55 спецификаций. Всего: 469765
🔄 Запрос #5350 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 138 спецификаций. Всего: 469903
🔄 Запрос #5351 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 95 спецификаций. Всего: 469998
🔄 Запрос #5352 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 144 спецификаций. Всего: 470142
🔄 Запрос #5353 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 129 спецификаций. Всего: 470271
🔄 Запрос #5354 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 113 спецификаций. Всего: 470384
🔄 Запрос #5355 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 113 спецификаций. Всего: 470497
🔄 Запрос #5356 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 470600
🔄 Запрос #5357 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 110 спецификаций. Всего: 470710
🔄 Запрос #5358 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 470801
🔄 Запрос #5359 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 470889
🔄 Запрос #5360 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 68 спецификаций. Всего: 470957
🔄 Запрос #5361 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 85 спецификаций. Всего: 471042
🔄 Запрос #5362 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 105 спецификаций. Всего: 471147
🔄 Запрос #5363 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 26 спецификаций. Всего: 471173
🔄 Запрос #5364 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 17 спецификаций. Всего: 471190
🔄 Запрос #5365 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 54 спецификаций. Всего: 471244
🔄 Запрос #5366 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 85 спецификаций. Всего: 471329
🔄 Запрос #5367 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 471430
🔄 Запрос #5368 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 105 спецификаций. Всего: 471535
🔄 Запрос #5369 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 102 спецификаций. Всего: 471637
🔄 Запрос #5370 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 69 спецификаций. Всего: 471706
🔄 Запрос #5371 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 471797
🔄 Запрос #5372 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 108 спецификаций. Всего: 471905
🔄 Запрос #5373 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 95 спецификаций. Всего: 472000
🔄 Запрос #5374 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 472093
🔄 Запрос #5375 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 94 спецификаций. Всего: 472187
🔄 Запрос #5376 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 123 спецификаций. Всего: 472310

🔄 Запрос #5377 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 99 спецификаций. Всего: 472409
🔄 Запрос #5378 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 472507
📤 Сохранено 10089 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #5379 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 69 спецификаций. Всего: 472576
🔄 Запрос #5380 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 472679
🔄 Запрос #5381 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 128 спецификаций. Всего: 472807
🔄 Запрос #5382 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 128 спецификаций. Всего: 472935
🔄 Запрос #5383 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 129 спецификаций. Всего: 473064
🔄 Запрос #5384 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 136 спецификаций. Всего: 473200
🔄 Запрос #5385 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 141 спецификаций. Всего: 473341
🔄 Запрос #5386 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 113 спецификаций. Всего: 473454
🔄 Запрос #5387 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 473542
🔄 Запрос #5388 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 473640
🔄 Запрос #5389 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 121 спецификаций. Всего: 473761
🔄 Запрос #5390 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 473862
🔄 Запрос #5391 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 119 спецификаций. Всего: 473981
🔄 Запрос #5392 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 117 спецификаций. Всего: 474098
🔄 Запрос #5393 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 155 спецификаций. Всего: 474253
🔄 Запрос #5394 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 137 спецификаций. Всего: 474390
🔄 Запрос #5395 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 138 спецификаций. Всего: 474528
🔄 Запрос #5396 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 127 спецификаций. Всего: 474655
🔄 Запрос #5397 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 131 спецификаций. Всего: 474786
🔄 Запрос #5398 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 107 спецификаций. Всего: 474893
🔄 Запрос #5399 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 92 спецификаций. Всего: 474985
🔄 Запрос #5400 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 90 спецификаций. Всего: 475075
🔄 Запрос #5401 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 90 спецификаций. Всего: 475165
🔄 Запрос #5402 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 80 спецификаций. Всего: 475245
🔄 Запрос #5403 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 53 спецификаций. Всего: 475298
🔄 Запрос #5404 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 75 спецификаций. Всего: 475373
🔄 Запрос #5405 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 73 спецификаций. Всего: 475446
🔄 Запрос #5406 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 84 спецификаций. Всего: 475530
🔄 Запрос #5407 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 131 спецификаций. Всего: 475661
🔄 Запрос #5408 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 69 спецификаций. Всего: 475730
🔄 Запрос #5409 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 76 спецификаций. Всего: 475806
🔄 Запрос #5410 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 128 спецификаций. Всего: 475934
🔄 Запрос #5411 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 84 спецификаций. Всего: 476018
🔄 Запрос #5412 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 114 спецификаций. Всего: 476132
🔄 Запрос #5413 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 143 спецификаций. Всего: 476275
🔄 Запрос #5414 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 153 спецификаций. Всего: 476428
🔄 Запрос #5415 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 87 спецификаций. Всего: 476515
🔄 Запрос #5416 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 110 спецификаций. Всего: 476625
🔄 Запрос #5417 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 123 спецификаций. Всего: 476748
🔄 Запрос #5418 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 143 спецификаций. Всего: 476891
🔄 Запрос #5419 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 99 спецификаций. Всего: 476990
🔄 Запрос #5420 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 477088
🔄 Запрос #5421 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 110 спецификаций. Всего: 477198
🔄 Запрос #5422 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 113 спецификаций. Всего: 477311
🔄 Запрос #5423 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 115 спецификаций. Всего: 477426
🔄 Запрос #5424 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 97 спецификаций. Всего: 477523
🔄 Запрос #5425 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 99 спецификаций. Всего: 477622
🔄 Запрос #5426 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 477725
🔄 Запрос #5427 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 124 спецификаций. Всего: 477849
🔄 Запрос #5428 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 105 спецификаций. Всего: 477954
🔄 Запрос #5429 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 114 спецификаций. Всего: 478068
🔄 Запрос #5430 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 58 спецификаций. Всего: 478126
🔄 Запрос #5431 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 478229
🔄 Запрос #5432 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 97 спецификаций. Всего: 478326
🔄 Запрос #5433 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 478419
🔄 Запрос #5434 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 97 спецификаций. Всего: 478516
🔄 Запрос #5435 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 116 спецификаций. Всего: 478632
🔄 Запрос #5436 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 103 спецификаций. Всего: 478735
🔄 Запрос #5437 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 478823
🔄 Запрос #5438 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 76 спецификаций. Всего: 478899
🔄 Запрос #5439 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 74 спецификаций. Всего: 478973
🔄 Запрос #5440 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 479056
🔄 Запрос #5441 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 479154
🔄 Запрос #5442 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 479255
🔄 Запрос #5443 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 479356
🔄 Запрос #5444 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 479457
🔄 Запрос #5445 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 102 спецификаций. Всего: 479559
🔄 Запрос #5446 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 479640
🔄 Запрос #5447 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 92 спецификаций. Всего: 479732
🔄 Запрос #5448 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 479830
🔄 Запрос #5449 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09

📥 Загружено 115 спецификаций. Всего: 479945
🔄 Запрос #5450 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 480041
🔄 Запрос #5451 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 115 спецификаций. Всего: 480156
🔄 Запрос #5452 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 111 спецификаций. Всего: 480267
🔄 Запрос #5453 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 480371
🔄 Запрос #5454 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 106 спецификаций. Всего: 480477
🔄 Запрос #5455 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 78 спецификаций. Всего: 480555
🔄 Запрос #5456 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 480653
🔄 Запрос #5457 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 113 спецификаций. Всего: 480766
🔄 Запрос #5458 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 109 спецификаций. Всего: 480875
🔄 Запрос #5459 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 121 спецификаций. Всего: 480996
🔄 Запрос #5460 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 92 спецификаций. Всего: 481088
🔄 Запрос #5461 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 481181
🔄 Запрос #5462 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 481282
🔄 Запрос #5463 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 481370
🔄 Запрос #5464 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 481471
🔄 Запрос #5465 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 124 спецификаций. Всего: 481595
🔄 Запрос #5466 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 94 спецификаций. Всего: 481689
🔄 Запрос #5467 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 116 спецификаций. Всего: 481805
🔄 Запрос #5468 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 120 спецификаций. Всего: 481925
🔄 Запрос #5469 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 138 спецификаций. Всего: 482063
🔄 Запрос #5470 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 118 спецификаций. Всего: 482181
🔄 Запрос #5471 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 106 спецификаций. Всего: 482287
🔄 Запрос #5472 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 482391
🔄 Запрос #5473 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 63 спецификаций. Всего: 482454
🔄 Запрос #5474 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 78 спецификаций. Всего: 482532
📤 Сохранено 10025 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #5475 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 482630
🔄 Запрос #5476 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 86 спецификаций. Всего: 482716
🔄 Запрос #5477 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 114 спецификаций. Всего: 482830
🔄 Запрос #5478 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 115 спецификаций. Всего: 482945
🔄 Запрос #5479 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 164 спецификаций. Всего: 483109
🔄 Запрос #5480 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 483207
🔄 Запрос #5481 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 69 спецификаций. Всего: 483276
🔄 Запрос #5482 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 120 спецификаций. Всего: 483396
🔄 Запрос #5483 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 483497
🔄 Запрос #5484 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 89 спецификаций. Всего: 483586
🔄 Запрос #5485 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 74 спецификаций. Всего: 483660
🔄 Запрос #5486 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 483758
🔄 Запрос #5487 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 27 спецификаций. Всего: 483785
🔄 Запрос #5488 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 92 спецификаций. Всего: 483877
🔄 Запрос #5489 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 116 спецификаций. Всего: 483993
🔄 Запрос #5490 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 126 спецификаций. Всего: 484119
🔄 Запрос #5491 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 166 спецификаций. Всего: 484285
🔄 Запрос #5492 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 165 спецификаций. Всего: 484450
🔄 Запрос #5493 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 90 спецификаций. Всего: 484540
🔄 Запрос #5494 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 122 спецификаций. Всего: 484662
🔄 Запрос #5495 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 154 спецификаций. Всего: 484816
🔄 Запрос #5496 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 174 спецификаций. Всего: 484990
🔄 Запрос #5497 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 149 спецификаций. Всего: 485139
🔄 Запрос #5498 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 132 спецификаций. Всего: 485271
🔄 Запрос #5499 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 134 спецификаций. Всего: 485405
🔄 Запрос #5500 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 147 спецификаций. Всего: 485552
🔄 Запрос #5501 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 139 спецификаций. Всего: 485691
🔄 Запрос #5502 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 128 спецификаций. Всего: 485819
🔄 Запрос #5503 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 149 спецификаций. Всего: 485968
🔄 Запрос #5504 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 121 спецификаций. Всего: 486089
🔄 Запрос #5505 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 109 спецификаций. Всего: 486198
🔄 Запрос #5506 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 486299
🔄 Запрос #5507 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 95 спецификаций. Всего: 486394
🔄 Запрос #5508 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 486495
🔄 Запрос #5509 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 486598
🔄 Запрос #5510 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 84 спецификаций. Всего: 486682
🔄 Запрос #5511 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 107 спецификаций. Всего: 486789
🔄 Запрос #5512 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 112 спецификаций. Всего: 486901
🔄 Запрос #5513 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 113 спецификаций. Всего: 487014
🔄 Запрос #5514 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 82 спецификаций. Всего: 487096
🔄 Запрос #5515 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 67 спецификаций. Всего: 487163
🔄 Запрос #5516 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 82 спецификаций. Всего: 487245
🔄 Запрос #5517 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 67 спецификаций. Всего: 487312
🔄 Запрос #5518 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 87 спецификаций. Всего: 487399
🔄 Запрос #5519 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 79 спецификаций. Всего: 487478
🔄 Запрос #5520 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 74 спецификаций. Всего: 487552
🔄 Запрос #5521 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 487653
🔄 Запрос #5522 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 89 спецификаций. Всего: 487742
🔄 Запрос #5523 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 112 спецификаций. Всего: 487854
🔄 Запрос #5524 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 116 спецификаций. Всего: 487970

🔄 Запрос #5525 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 114 спецификаций. Всего: 488084
🔄 Запрос #5526 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 132 спецификаций. Всего: 488216
🔄 Запрос #5527 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 488297
🔄 Запрос #5528 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 111 спецификаций. Всего: 488408
🔄 Запрос #5529 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 488509
🔄 Запрос #5530 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 102 спецификаций. Всего: 488611
🔄 Запрос #5531 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 488714
🔄 Запрос #5532 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 99 спецификаций. Всего: 488813
🔄 Запрос #5533 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 488917
🔄 Запрос #5534 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 99 спецификаций. Всего: 489016
🔄 Запрос #5535 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 130 спецификаций. Всего: 489146
🔄 Запрос #5536 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 132 спецификаций. Всего: 489278
🔄 Запрос #5537 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 124 спецификаций. Всего: 489402
🔄 Запрос #5538 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 121 спецификаций. Всего: 489523
🔄 Запрос #5539 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 116 спецификаций. Всего: 489639
🔄 Запрос #5540 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 117 спецификаций. Всего: 489756
🔄 Запрос #5541 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 92 спецификаций. Всего: 489848
🔄 Запрос #5542 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 111 спецификаций. Всего: 489959
🔄 Запрос #5543 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 142 спецификаций. Всего: 490101
🔄 Запрос #5544 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 490197
🔄 Запрос #5545 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 40 спецификаций. Всего: 490237
🔄 Запрос #5546 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 133 спецификаций. Всего: 490370
🔄 Запрос #5547 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 121 спецификаций. Всего: 490491
🔄 Запрос #5548 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 490592
🔄 Запрос #5549 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 137 спецификаций. Всего: 490729
🔄 Запрос #5550 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 128 спецификаций. Всего: 490857
🔄 Запрос #5551 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 158 спецификаций. Всего: 491015
🔄 Запрос #5552 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 134 спецификаций. Всего: 491149
🔄 Запрос #5553 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 102 спецификаций. Всего: 491251
🔄 Запрос #5554 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 491349
🔄 Запрос #5555 для 2024-11-21 20:44:09 - 2024-11-28 20:44:09
📥 Загружено 3 спецификаций. Всего: 491352
📅 Обрабатываем диапазон 2024-11-14 20:44:09 - 2024-11-21 20:44:09 (попытка 1/5)
🔄 Запрос #5556 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 491466
🔄 Запрос #5557 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 140 спецификаций. Всего: 491606
🔄 Запрос #5558 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 138 спецификаций. Всего: 491744
🔄 Запрос #5559 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 164 спецификаций. Всего: 491908
🔄 Запрос #5560 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 126 спецификаций. Всего: 492034
🔄 Запрос #5561 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 161 спецификаций. Всего: 492195
🔄 Запрос #5562 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 492307
🔄 Запрос #5563 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 126 спецификаций. Всего: 492433
🔄 Запрос #5564 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 134 спецификаций. Всего: 492567
📤 Сохранено 10035 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #5565 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 133 спецификаций. Всего: 492700
🔄 Запрос #5566 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 492818
🔄 Запрос #5567 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 126 спецификаций. Всего: 492944
🔄 Запрос #5568 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 133 спецификаций. Всего: 493077
🔄 Запрос #5569 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 493184
🔄 Запрос #5570 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 129 спецификаций. Всего: 493313
🔄 Запрос #5571 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 98 спецификаций. Всего: 493411
🔄 Запрос #5572 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 493518
🔄 Запрос #5573 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 98 спецификаций. Всего: 493616
🔄 Запрос #5574 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 493725
🔄 Запрос #5575 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 493830
🔄 Запрос #5576 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 493924
🔄 Запрос #5577 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 86 спецификаций. Всего: 494010
🔄 Запрос #5578 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 54 спецификаций. Всего: 494064
🔄 Запрос #5579 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 79 спецификаций. Всего: 494143
🔄 Запрос #5580 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 494238
🔄 Запрос #5581 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 98 спецификаций. Всего: 494336
🔄 Запрос #5582 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 494441
🔄 Запрос #5583 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 494550
🔄 Запрос #5584 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 59 спецификаций. Всего: 494609
🔄 Запрос #5585 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 29 спецификаций. Всего: 494638
🔄 Запрос #5586 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 494744
🔄 Запрос #5587 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 96 спецификаций. Всего: 494840
🔄 Запрос #5588 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 9 спецификаций. Всего: 494849
🔄 Запрос #5589 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 73 спецификаций. Всего: 494922
🔄 Запрос #5590 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 74 спецификаций. Всего: 494996
🔄 Запрос #5591 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 495091
🔄 Запрос #5592 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 137 спецификаций. Всего: 495228
🔄 Запрос #5593 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 135 спецификаций. Всего: 495363
🔄 Запрос #5594 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 495491
🔄 Запрос #5595 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 133 спецификаций. Всего: 495624
🔄 Запрос #5596 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 120 спецификаций. Всего: 495744
🔄 Запрос #5597 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 31 спецификаций. Всего: 495775
🔄 Запрос #5598 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 10 спецификаций. Всего: 495785
🔄 Запрос #5599 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 22 спецификаций. Всего: 495807
🔄 Запрос #5600 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09

📥 Загружено 113 спецификаций. Всего: 495920
🔄 Запрос #5601 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 153 спецификаций. Всего: 496073
🔄 Запрос #5602 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 496185
🔄 Запрос #5603 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 496294
🔄 Запрос #5604 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 127 спецификаций. Всего: 496421
🔄 Запрос #5605 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 104 спецификаций. Всего: 496525
🔄 Запрос #5606 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 496639
🔄 Запрос #5607 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 115 спецификаций. Всего: 496754
🔄 Запрос #5608 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 126 спецификаций. Всего: 496880
🔄 Запрос #5609 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 133 спецификаций. Всего: 497013
🔄 Запрос #5610 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 138 спецификаций. Всего: 497151
🔄 Запрос #5611 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 135 спецификаций. Всего: 497286
🔄 Запрос #5612 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 126 спецификаций. Всего: 497412
🔄 Запрос #5613 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 497524
🔄 Запрос #5614 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 497642
🔄 Запрос #5615 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 121 спецификаций. Всего: 497763
🔄 Запрос #5616 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 497881
🔄 Запрос #5617 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 497993
🔄 Запрос #5618 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 120 спецификаций. Всего: 498113
🔄 Запрос #5619 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 158 спецификаций. Всего: 498271
🔄 Запрос #5620 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 498378
🔄 Запрос #5621 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 147 спецификаций. Всего: 498525
🔄 Запрос #5622 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 139 спецификаций. Всего: 498664
🔄 Запрос #5623 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 498754
🔄 Запрос #5624 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 498855
🔄 Запрос #5625 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 123 спецификаций. Всего: 498978
🔄 Запрос #5626 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 139 спецификаций. Всего: 499117
🔄 Запрос #5627 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 123 спецификаций. Всего: 499240
🔄 Запрос #5628 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 121 спецификаций. Всего: 499361
🔄 Запрос #5629 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 124 спецификаций. Всего: 499485
🔄 Запрос #5630 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 133 спецификаций. Всего: 499618
🔄 Запрос #5631 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 121 спецификаций. Всего: 499739
🔄 Запрос #5632 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 155 спецификаций. Всего: 499894
🔄 Запрос #5633 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 122 спецификаций. Всего: 500016
🔄 Запрос #5634 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 500144
🔄 Запрос #5635 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 126 спецификаций. Всего: 500270
🔄 Запрос #5636 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 500388
🔄 Запрос #5637 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 122 спецификаций. Всего: 500510
🔄 Запрос #5638 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 500615
🔄 Запрос #5639 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 500728
🔄 Запрос #5640 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 85 спецификаций. Всего: 500813
🔄 Запрос #5641 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 123 спецификаций. Всего: 500936
🔄 Запрос #5642 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 116 спецификаций. Всего: 501052
🔄 Запрос #5643 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 501166
🔄 Запрос #5644 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 501275
🔄 Запрос #5645 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 501376
🔄 Запрос #5646 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 501486
🔄 Запрос #5647 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 501586
🔄 Запрос #5648 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 91 спецификаций. Всего: 501677
🔄 Запрос #5649 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 103 спецификаций. Всего: 501780
🔄 Запрос #5650 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 501875
🔄 Запрос #5651 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 501982
🔄 Запрос #5652 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 502092
🔄 Запрос #5653 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 99 спецификаций. Всего: 502191
🔄 Запрос #5654 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 502292
🔄 Запрос #5655 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 81 спецификаций. Всего: 502373
🔄 Запрос #5656 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 502456
🔄 Запрос #5657 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 502539
🔄 Запрос #5658 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 61 спецификаций. Всего: 502600
📤 Сохранено 10033 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #5659 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 77 спецификаций. Всего: 502677
🔄 Запрос #5660 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 68 спецификаций. Всего: 502745
🔄 Запрос #5661 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 116 спецификаций. Всего: 502861
🔄 Запрос #5662 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 122 спецификаций. Всего: 502983
🔄 Запрос #5663 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 503077
🔄 Запрос #5664 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 503186
🔄 Запрос #5665 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 119 спецификаций. Всего: 503305
🔄 Запрос #5666 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 38 спецификаций. Всего: 503343
🔄 Запрос #5667 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 34 спецификаций. Всего: 503377
🔄 Запрос #5668 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 503490
🔄 Запрос #5669 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 503597
🔄 Запрос #5670 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 503691
🔄 Запрос #5671 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 503785
🔄 Запрос #5672 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 503880
🔄 Запрос #5673 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 503986
🔄 Запрос #5674 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 93 спецификаций. Всего: 504079
🔄 Запрос #5675 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 91 спецификаций. Всего: 504170
🔄 Запрос #5676 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 99 спецификаций. Всего: 504269

🔄 Запрос #5677 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 125 спецификаций. Всего: 504394
🔄 Запрос #5678 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 131 спецификаций. Всего: 504525
🔄 Запрос #5679 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 40 спецификаций. Всего: 504565
🔄 Запрос #5680 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 54 спецификаций. Всего: 504619
🔄 Запрос #5681 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 125 спецификаций. Всего: 504744
🔄 Запрос #5682 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 122 спецификаций. Всего: 504866
🔄 Запрос #5683 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 117 спецификаций. Всего: 504983
🔄 Запрос #5684 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 99 спецификаций. Всего: 505082
🔄 Запрос #5685 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 78 спецификаций. Всего: 505160
🔄 Запрос #5686 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 68 спецификаций. Всего: 505228
🔄 Запрос #5687 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 102 спецификаций. Всего: 505330
🔄 Запрос #5688 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 117 спецификаций. Всего: 505447
🔄 Запрос #5689 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 82 спецификаций. Всего: 505529
🔄 Запрос #5690 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 0 спецификаций. Всего: 505529
🔄 Запрос #5691 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 1 спецификаций. Всего: 505530
🔄 Запрос #5692 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 9 спецификаций. Всего: 505539
🔄 Запрос #5693 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 92 спецификаций. Всего: 505631
🔄 Запрос #5694 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 80 спецификаций. Всего: 505711
🔄 Запрос #5695 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 505823
🔄 Запрос #5696 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 140 спецификаций. Всего: 505963
🔄 Запрос #5697 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 148 спецификаций. Всего: 506111
🔄 Запрос #5698 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 148 спецификаций. Всего: 506259
🔄 Запрос #5699 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 163 спецификаций. Всего: 506422
🔄 Запрос #5700 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 506550
🔄 Запрос #5701 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 151 спецификаций. Всего: 506701
🔄 Запрос #5702 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 150 спецификаций. Всего: 506851
🔄 Запрос #5703 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 151 спецификаций. Всего: 507002
🔄 Запрос #5704 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 131 спецификаций. Всего: 507133
🔄 Запрос #5705 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 136 спецификаций. Всего: 507269
🔄 Запрос #5706 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 122 спецификаций. Всего: 507391
🔄 Запрос #5707 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 123 спецификаций. Всего: 507514
🔄 Запрос #5708 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 115 спецификаций. Всего: 507629
🔄 Запрос #5709 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 144 спецификаций. Всего: 507773
🔄 Запрос #5710 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 121 спецификаций. Всего: 507894
🔄 Запрос #5711 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 131 спецификаций. Всего: 508025
🔄 Запрос #5712 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 108 спецификаций. Всего: 508133
🔄 Запрос #5713 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 508251
🔄 Запрос #5714 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 130 спецификаций. Всего: 508381
🔄 Запрос #5715 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 136 спецификаций. Всего: 508517
🔄 Запрос #5716 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 508645
🔄 Запрос #5717 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 127 спецификаций. Всего: 508772
🔄 Запрос #5718 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 127 спецификаций. Всего: 508899
🔄 Запрос #5719 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 509004
🔄 Запрос #5720 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 509094
🔄 Запрос #5721 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 121 спецификаций. Всего: 509215
🔄 Запрос #5722 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 119 спецификаций. Всего: 509334
🔄 Запрос #5723 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 98 спецификаций. Всего: 509432
🔄 Запрос #5724 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 120 спецификаций. Всего: 509552
🔄 Запрос #5725 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 509680
🔄 Запрос #5726 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 509787
🔄 Запрос #5727 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 80 спецификаций. Всего: 509867
🔄 Запрос #5728 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 93 спецификаций. Всего: 509960
🔄 Запрос #5729 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 58 спецификаций. Всего: 510018
🔄 Запрос #5730 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 22 спецификаций. Всего: 510040
🔄 Запрос #5731 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 21 спецификаций. Всего: 510061
🔄 Запрос #5732 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 11 спецификаций. Всего: 510072
🔄 Запрос #5733 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 42 спецификаций. Всего: 510114
🔄 Запрос #5734 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 510197
🔄 Запрос #5735 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 77 спецификаций. Всего: 510274
🔄 Запрос #5736 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 74 спецификаций. Всего: 510348
🔄 Запрос #5737 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 510455
🔄 Запрос #5738 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 80 спецификаций. Всего: 510535
🔄 Запрос #5739 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 74 спецификаций. Всего: 510609
🔄 Запрос #5740 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 96 спецификаций. Всего: 510705
🔄 Запрос #5741 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 168 спецификаций. Всего: 510873
🔄 Запрос #5742 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 124 спецификаций. Всего: 510997
🔄 Запрос #5743 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 511110
🔄 Запрос #5744 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 511221
🔄 Запрос #5745 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 52 спецификаций. Всего: 511273
🔄 Запрос #5746 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 511373
🔄 Запрос #5747 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 76 спецификаций. Всего: 511449
🔄 Запрос #5748 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 46 спецификаций. Всего: 511495
🔄 Запрос #5749 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 103 спецификаций. Всего: 511598
🔄 Запрос #5750 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 92 спецификаций. Всего: 511690
🔄 Запрос #5751 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 511801
🔄 Запрос #5752 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 511912

🔄 Запрос #5753 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 512002
🔄 Запрос #5754 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 512109
🔄 Запрос #5755 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 512215
🔄 Запрос #5756 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 79 спецификаций. Всего: 512294
🔄 Запрос #5757 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 49 спецификаций. Всего: 512343
🔄 Запрос #5758 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 84 спецификаций. Всего: 512427
🔄 Запрос #5759 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 93 спецификаций. Всего: 512520
🔄 Запрос #5760 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 104 спецификаций. Всего: 512624
📤 Сохранено 10024 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #5761 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 120 спецификаций. Всего: 512744
🔄 Запрос #5762 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 512855
🔄 Запрос #5763 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 512950
🔄 Запрос #5764 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 513051
🔄 Запрос #5765 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 134 спецификаций. Всего: 513185
🔄 Запрос #5766 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 108 спецификаций. Всего: 513293
🔄 Запрос #5767 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 66 спецификаций. Всего: 513359
🔄 Запрос #5768 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 513466
🔄 Запрос #5769 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 96 спецификаций. Всего: 513562
🔄 Запрос #5770 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 93 спецификаций. Всего: 513655
🔄 Запрос #5771 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 513765
🔄 Запрос #5772 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 97 спецификаций. Всего: 513862
🔄 Запрос #5773 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 124 спецификаций. Всего: 513986
🔄 Запрос #5774 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 77 спецификаций. Всего: 514063
🔄 Запрос #5775 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 127 спецификаций. Всего: 514190
🔄 Запрос #5776 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 122 спецификаций. Всего: 514312
🔄 Запрос #5777 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 74 спецификаций. Всего: 514386
🔄 Запрос #5778 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 132 спецификаций. Всего: 514518
🔄 Запрос #5779 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 108 спецификаций. Всего: 514626
🔄 Запрос #5780 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 6 спецификаций. Всего: 514632
🔄 Запрос #5781 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 6 спецификаций. Всего: 514638
🔄 Запрос #5782 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 49 спецификаций. Всего: 514687
🔄 Запрос #5783 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 116 спецификаций. Всего: 514803
🔄 Запрос #5784 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 148 спецификаций. Всего: 514951
🔄 Запрос #5785 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 148 спецификаций. Всего: 515099
🔄 Запрос #5786 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 131 спецификаций. Всего: 515230
🔄 Запрос #5787 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 515343
🔄 Запрос #5788 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 515457
🔄 Запрос #5789 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 122 спецификаций. Всего: 515579
🔄 Запрос #5790 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 133 спецификаций. Всего: 515712
🔄 Запрос #5791 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 68 спецификаций. Всего: 515780
🔄 Запрос #5792 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 28 спецификаций. Всего: 515808
🔄 Запрос #5793 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 515926
🔄 Запрос #5794 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 60 спецификаций. Всего: 515986
🔄 Запрос #5795 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 51 спецификаций. Всего: 516037
🔄 Запрос #5796 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 516142
🔄 Запрос #5797 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 116 спецификаций. Всего: 516258
🔄 Запрос #5798 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 103 спецификаций. Всего: 516361
🔄 Запрос #5799 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 516461
🔄 Запрос #5800 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 102 спецификаций. Всего: 516563
🔄 Запрос #5801 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 40 спецификаций. Всего: 516603
🔄 Запрос #5802 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 99 спецификаций. Всего: 516702
🔄 Запрос #5803 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 516816
🔄 Запрос #5804 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 516929
🔄 Запрос #5805 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 108 спецификаций. Всего: 517037
🔄 Запрос #5806 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 517147
🔄 Запрос #5807 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 108 спецификаций. Всего: 517255
🔄 Запрос #5808 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 87 спецификаций. Всего: 517342
🔄 Запрос #5809 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 517448
🔄 Запрос #5810 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 517538
🔄 Запрос #5811 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 517649
🔄 Запрос #5812 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 517743
🔄 Запрос #5813 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 517826
🔄 Запрос #5814 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 76 спецификаций. Всего: 517902
🔄 Запрос #5815 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 517995
🔄 Запрос #5816 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 518096
🔄 Запрос #5817 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 518224
🔄 Запрос #5818 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 518338
🔄 Запрос #5819 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 518447
🔄 Запрос #5820 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 518548
🔄 Запрос #5821 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 518660
🔄 Запрос #5822 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 108 спецификаций. Всего: 518768
🔄 Запрос #5823 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 518869
🔄 Запрос #5824 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 108 спецификаций. Всего: 518977
🔄 Запрос #5825 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 89 спецификаций. Всего: 519066
🔄 Запрос #5826 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 2 спецификаций. Всего: 519068
🔄 Запрос #5827 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09

📥 Загружено 3 спецификаций. Всего: 519071
🔄 Запрос #5828 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 1 спецификаций. Всего: 519072
🔄 Запрос #5829 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 2 спецификаций. Всего: 519074
🔄 Запрос #5830 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 37 спецификаций. Всего: 519111
🔄 Запрос #5831 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 103 спецификаций. Всего: 519214
🔄 Запрос #5832 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 519327
🔄 Запрос #5833 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 519427
🔄 Запрос #5834 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 519532
🔄 Запрос #5835 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 519633
🔄 Запрос #5836 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 519727
🔄 Запрос #5837 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 103 спецификаций. Всего: 519830
🔄 Запрос #5838 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 519948
🔄 Запрос #5839 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 125 спецификаций. Всего: 520073
🔄 Запрос #5840 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 520201
🔄 Запрос #5841 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 76 спецификаций. Всего: 520277
🔄 Запрос #5842 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 25 спецификаций. Всего: 520302
🔄 Запрос #5843 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 86 спецификаций. Всего: 520388
🔄 Запрос #5844 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 174 спецификаций. Всего: 520562
🔄 Запрос #5845 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 180 спецификаций. Всего: 520742
🔄 Запрос #5846 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 141 спецификаций. Всего: 520883
🔄 Запрос #5847 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 96 спецификаций. Всего: 520979
🔄 Запрос #5848 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 129 спецификаций. Всего: 521108
🔄 Запрос #5849 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 521214
🔄 Запрос #5850 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 151 спецификаций. Всего: 521365
🔄 Запрос #5851 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 521470
🔄 Запрос #5852 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 521570
🔄 Запрос #5853 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 133 спецификаций. Всего: 521703
🔄 Запрос #5854 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 98 спецификаций. Всего: 521801
🔄 Запрос #5855 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 102 спецификаций. Всего: 521903
🔄 Запрос #5856 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 42 спецификаций. Всего: 521945
🔄 Запрос #5857 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 3 спецификаций. Всего: 521948
🔄 Запрос #5858 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 4 спецификаций. Всего: 521952
🔄 Запрос #5859 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 64 спецификаций. Всего: 522016
🔄 Запрос #5860 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 129 спецификаций. Всего: 522145
🔄 Запрос #5861 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 69 спецификаций. Всего: 522214
🔄 Запрос #5862 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 91 спецификаций. Всего: 522305
🔄 Запрос #5863 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 144 спецификаций. Всего: 522449
🔄 Запрос #5864 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 522544
🔄 Запрос #5865 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 522627
📤 Сохранено 10003 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #5866 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 165 спецификаций. Всего: 522792
🔄 Запрос #5867 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 122 спецификаций. Всего: 522914
🔄 Запрос #5868 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 523021
🔄 Запрос #5869 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 124 спецификаций. Всего: 523145
🔄 Запрос #5870 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 115 спецификаций. Всего: 523260
🔄 Запрос #5871 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 523372
🔄 Запрос #5872 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 115 спецификаций. Всего: 523487
🔄 Запрос #5873 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 57 спецификаций. Всего: 523544
🔄 Запрос #5874 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 68 спецификаций. Всего: 523612
🔄 Запрос #5875 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 71 спецификаций. Всего: 523683
🔄 Запрос #5876 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 73 спецификаций. Всего: 523756
🔄 Запрос #5877 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 98 спецификаций. Всего: 523854
🔄 Запрос #5878 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 57 спецификаций. Всего: 523911
🔄 Запрос #5879 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 38 спецификаций. Всего: 523949
🔄 Запрос #5880 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 524059
🔄 Запрос #5881 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 524165
🔄 Запрос #5882 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 136 спецификаций. Всего: 524301
🔄 Запрос #5883 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 141 спецификаций. Всего: 524442
🔄 Запрос #5884 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 122 спецификаций. Всего: 524564
🔄 Запрос #5885 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 524682
🔄 Запрос #5886 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 524791
🔄 Запрос #5887 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 104 спецификаций. Всего: 524895
🔄 Запрос #5888 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 525001
🔄 Запрос #5889 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 525112
🔄 Запрос #5890 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 525219
🔄 Запрос #5891 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 79 спецификаций. Всего: 525298
🔄 Запрос #5892 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 87 спецификаций. Всего: 525385
🔄 Запрос #5893 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 99 спецификаций. Всего: 525484
🔄 Запрос #5894 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 119 спецификаций. Всего: 525603
🔄 Запрос #5895 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 144 спецификаций. Всего: 525747
🔄 Запрос #5896 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 525860
🔄 Запрос #5897 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 121 спецификаций. Всего: 525981
🔄 Запрос #5898 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 526076
🔄 Запрос #5899 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 16 спецификаций. Всего: 526092
🔄 Запрос #5900 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 54 спецификаций. Всего: 526146
🔄 Запрос #5901 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 123 спецификаций. Всего: 526269
🔄 Запрос #5902 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 131 спецификаций. Всего: 526400
🔄 Запрос #5903 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 526518
🔄 Запрос #5904 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 84 спецификаций. Всего: 526602
🔄 Запрос #5905 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 526696
🔄 Запрос #5906 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 45 спецификаций. Всего: 526741
🔄 Запрос #5907 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 93 спецификаций. Всего: 526834
🔄 Запрос #5908 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 123 спецификаций. Всего: 526957
🔄 Запрос #5909 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 141 спецификаций. Всего: 527098
🔄 Запрос #5910 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 527209
🔄 Запрос #5911 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 527316
🔄 Запрос #5912 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 527411
🔄 Запрос #5913 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 527525
🔄 Запрос #5914 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 527653
🔄 Запрос #5915 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 527758
🔄 Запрос #5916 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 527868
🔄 Запрос #5917 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 527996
🔄 Запрос #5918 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 151 спецификаций. Всего: 528147
🔄 Запрос #5919 для 2024-11-14 20:44:09 - 2024-11-21 20:44:09
📥 Загружено 27 спецификаций. Всего: 528174
📅 Обрабатываем диапазон 2024-11-07 20:44:09 - 2024-11-14 20:44:09 (попытка 1/5)
🔄 Запрос #5920 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 154 спецификаций. Всего: 528328
🔄 Запрос #5921 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 166 спецификаций. Всего: 528494
🔄 Запрос #5922 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 158 спецификаций. Всего: 528652
🔄 Запрос #5923 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 155 спецификаций. Всего: 528807
🔄 Запрос #5924 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 181 спецификаций. Всего: 528988
🔄 Запрос #5925 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 140 спецификаций. Всего: 529128
🔄 Запрос #5926 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 127 спецификаций. Всего: 529255
🔄 Запрос #5927 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 128 спецификаций. Всего: 529383
🔄 Запрос #5928 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 529506
🔄 Запрос #5929 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 529619
🔄 Запрос #5930 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 529715
🔄 Запрос #5931 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 120 спецификаций. Всего: 529835
🔄 Запрос #5932 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 529951
🔄 Запрос #5933 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 530060
🔄 Запрос #5934 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 530173
🔄 Запрос #5935 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 530296
🔄 Запрос #5936 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 530409
🔄 Запрос #5937 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 530525
🔄 Запрос #5938 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 530636
🔄 Запрос #5939 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 530757
🔄 Запрос #5940 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 129 спецификаций. Всего: 530886
🔄 Запрос #5941 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 531000
🔄 Запрос #5942 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 97 спецификаций. Всего: 531097
🔄 Запрос #5943 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 531199
🔄 Запрос #5944 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 531305
🔄 Запрос #5945 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 78 спецификаций. Всего: 531383
🔄 Запрос #5946 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 75 спецификаций. Всего: 531458
🔄 Запрос #5947 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 80 спецификаций. Всего: 531538
🔄 Запрос #5948 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 531657
🔄 Запрос #5949 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 531772
🔄 Запрос #5950 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 531872
🔄 Запрос #5951 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 531976
🔄 Запрос #5952 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 532081
🔄 Запрос #5953 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 532194
🔄 Запрос #5954 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 532296
🔄 Запрос #5955 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 532400
🔄 Запрос #5956 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 532512
🔄 Запрос #5957 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 532623
🔄 Запрос #5958 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 532722
📤 Сохранено 10095 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #5959 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 532831
🔄 Запрос #5960 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 532943
🔄 Запрос #5961 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 533058
🔄 Запрос #5962 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 533177
🔄 Запрос #5963 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 533284
🔄 Запрос #5964 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 533384
🔄 Запрос #5965 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 533487
🔄 Запрос #5966 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 533587
🔄 Запрос #5967 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 92 спецификаций. Всего: 533679
🔄 Запрос #5968 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 75 спецификаций. Всего: 533754
🔄 Запрос #5969 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 70 спецификаций. Всего: 533824
🔄 Запрос #5970 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 533930
🔄 Запрос #5971 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 97 спецификаций. Всего: 534027
🔄 Запрос #5972 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 534148
🔄 Запрос #5973 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 534250
🔄 Запрос #5974 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 534355
🔄 Запрос #5975 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 534446

🔄 Запрос #5976 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 2 спецификаций. Всего: 534448
🔄 Запрос #5977 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 83 спецификаций. Всего: 534531
🔄 Запрос #5978 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 88 спецификаций. Всего: 534619
🔄 Запрос #5979 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 534719
🔄 Запрос #5980 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 162 спецификаций. Всего: 534881
🔄 Запрос #5981 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 83 спецификаций. Всего: 534964
🔄 Запрос #5982 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 535085
🔄 Запрос #5983 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 142 спецификаций. Всего: 535227
🔄 Запрос #5984 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 535346
🔄 Запрос #5985 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 535462
🔄 Запрос #5986 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 124 спецификаций. Всего: 535586
🔄 Запрос #5987 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 141 спецификаций. Всего: 535727
🔄 Запрос #5988 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 131 спецификаций. Всего: 535858
🔄 Запрос #5989 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 143 спецификаций. Всего: 536001
🔄 Запрос #5990 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 536103
🔄 Запрос #5991 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 536202
🔄 Запрос #5992 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 536314
🔄 Запрос #5993 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 536420
🔄 Запрос #5994 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 536533
🔄 Запрос #5995 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 92 спецификаций. Всего: 536625
🔄 Запрос #5996 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 536729
🔄 Запрос #5997 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 536841
🔄 Запрос #5998 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 536949
🔄 Запрос #5999 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 89 спецификаций. Всего: 537038
🔄 Запрос #6000 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 85 спецификаций. Всего: 537123
🔄 Запрос #6001 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 537230
🔄 Запрос #6002 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 537335
🔄 Запрос #6003 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 537451
🔄 Запрос #6004 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 537562
🔄 Запрос #6005 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 35 спецификаций. Всего: 537597
🔄 Запрос #6006 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 54 спецификаций. Всего: 537651
🔄 Запрос #6007 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 537762
🔄 Запрос #6008 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 537871
🔄 Запрос #6009 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 537976
🔄 Запрос #6010 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 538082
🔄 Запрос #6011 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 538184
🔄 Запрос #6012 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 90 спецификаций. Всего: 538274
🔄 Запрос #6013 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 538373
🔄 Запрос #6014 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 538489
🔄 Запрос #6015 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 95 спецификаций. Всего: 538584
🔄 Запрос #6016 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 163 спецификаций. Всего: 538747
🔄 Запрос #6017 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 80 спецификаций. Всего: 538827
🔄 Запрос #6018 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 94 спецификаций. Всего: 538921
🔄 Запрос #6019 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 132 спецификаций. Всего: 539053
🔄 Запрос #6020 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 146 спецификаций. Всего: 539199
🔄 Запрос #6021 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 539324
🔄 Запрос #6022 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 163 спецификаций. Всего: 539487
🔄 Запрос #6023 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 172 спецификаций. Всего: 539659
🔄 Запрос #6024 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 539770
🔄 Запрос #6025 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 98 спецификаций. Всего: 539868
🔄 Запрос #6026 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 131 спецификаций. Всего: 539999
🔄 Запрос #6027 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 540110
🔄 Запрос #6028 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 540221
🔄 Запрос #6029 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 540329
🔄 Запрос #6030 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 540432
🔄 Запрос #6031 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 540548
🔄 Запрос #6032 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 540650
🔄 Запрос #6033 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 46 спецификаций. Всего: 540696
🔄 Запрос #6034 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 2 спецификаций. Всего: 540698
🔄 Запрос #6035 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 29 спецификаций. Всего: 540727
🔄 Запрос #6036 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 18 спецификаций. Всего: 540745
🔄 Запрос #6037 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 10 спецификаций. Всего: 540755
🔄 Запрос #6038 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 2 спецификаций. Всего: 540757
🔄 Запрос #6039 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 10 спецификаций. Всего: 540767
🔄 Запрос #6040 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 4 спецификаций. Всего: 540771
🔄 Запрос #6041 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 5 спецификаций. Всего: 540776
🔄 Запрос #6042 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 3 спецификаций. Всего: 540779
🔄 Запрос #6043 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 6 спецификаций. Всего: 540785
🔄 Запрос #6044 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 7 спецификаций. Всего: 540792
🔄 Запрос #6045 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 14 спецификаций. Всего: 540806
🔄 Запрос #6046 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 3 спецификаций. Всего: 540809
🔄 Запрос #6047 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 5 спецификаций. Всего: 540814
🔄 Запрос #6048 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 20 спецификаций. Всего: 540834
🔄 Запрос #6049 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 540940
🔄 Запрос #6050 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 62 спецификаций. Всего: 541002
🔄 Запрос #6051 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 79 спецификаций. Всего: 541081
🔄 Запрос #6052 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09

📥 Загружено 115 спецификаций. Всего: 541196
🔄 Запрос #6053 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 117 спецификаций. Всего: 541313
🔄 Запрос #6054 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 541424
🔄 Запрос #6055 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 541543
🔄 Запрос #6056 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 124 спецификаций. Всего: 541667
🔄 Запрос #6057 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 126 спецификаций. Всего: 541793
🔄 Запрос #6058 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 142 спецификаций. Всего: 541935
🔄 Запрос #6059 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 542053
🔄 Запрос #6060 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 127 спецификаций. Всего: 542180
🔄 Запрос #6061 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 49 спецификаций. Всего: 542229
🔄 Запрос #6062 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 41 спецификаций. Всего: 542270
🔄 Запрос #6063 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 85 спецификаций. Всего: 542355
🔄 Запрос #6064 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 92 спецификаций. Всего: 542447
🔄 Запрос #6065 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 81 спецификаций. Всего: 542528
🔄 Запрос #6066 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 542639
🔄 Запрос #6067 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 542757
📤 Сохранено 10035 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #6068 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 542878
🔄 Запрос #6069 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 542983
🔄 Запрос #6070 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 110 спецификаций. Всего: 543093
🔄 Запрос #6071 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 92 спецификаций. Всего: 543185
🔄 Запрос #6072 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 543288
🔄 Запрос #6073 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 543403
🔄 Запрос #6074 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 543528
🔄 Запрос #6075 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 141 спецификаций. Всего: 543669
🔄 Запрос #6076 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 543787
🔄 Запрос #6077 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 130 спецификаций. Всего: 543917
🔄 Запрос #6078 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 544033
🔄 Запрос #6079 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 135 спецификаций. Всего: 544168
🔄 Запрос #6080 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 75 спецификаций. Всего: 544243
🔄 Запрос #6081 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 23 спецификаций. Всего: 544266
🔄 Запрос #6082 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 74 спецификаций. Всего: 544340
🔄 Запрос #6083 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 110 спецификаций. Всего: 544450
🔄 Запрос #6084 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 544568
🔄 Запрос #6085 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 122 спецификаций. Всего: 544690
🔄 Запрос #6086 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 132 спецификаций. Всего: 544822
🔄 Запрос #6087 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 130 спецификаций. Всего: 544952
🔄 Запрос #6088 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 545063
🔄 Запрос #6089 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 545169
🔄 Запрос #6090 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 117 спецификаций. Всего: 545286
🔄 Запрос #6091 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 545402
🔄 Запрос #6092 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 545498
🔄 Запрос #6093 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 545612
🔄 Запрос #6094 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 545708
🔄 Запрос #6095 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 545808
🔄 Запрос #6096 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 545921
🔄 Запрос #6097 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 546046
🔄 Запрос #6098 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 546169
🔄 Запрос #6099 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 546281
🔄 Запрос #6100 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 546394
🔄 Запрос #6101 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 71 спецификаций. Всего: 546465
🔄 Запрос #6102 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 92 спецификаций. Всего: 546557
🔄 Запрос #6103 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 82 спецификаций. Всего: 546639
🔄 Запрос #6104 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 78 спецификаций. Всего: 546717
🔄 Запрос #6105 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 83 спецификаций. Всего: 546800
🔄 Запрос #6106 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 60 спецификаций. Всего: 546860
🔄 Запрос #6107 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 546966
🔄 Запрос #6108 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 547075
🔄 Запрос #6109 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 95 спецификаций. Всего: 547170
🔄 Запрос #6110 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 547283
🔄 Запрос #6111 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 547406
🔄 Запрос #6112 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 63 спецификаций. Всего: 547469
🔄 Запрос #6113 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 98 спецификаций. Всего: 547567
🔄 Запрос #6114 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 547688
🔄 Запрос #6115 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 89 спецификаций. Всего: 547777
🔄 Запрос #6116 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 92 спецификаций. Всего: 547869
🔄 Запрос #6117 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 78 спецификаций. Всего: 547947
🔄 Запрос #6118 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 548065
🔄 Запрос #6119 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 548186
🔄 Запрос #6120 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 548305
🔄 Запрос #6121 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 548418
🔄 Запрос #6122 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 548527
🔄 Запрос #6123 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 95 спецификаций. Всего: 548622
🔄 Запрос #6124 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 81 спецификаций. Всего: 548703
🔄 Запрос #6125 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 548809
🔄 Запрос #6126 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 548922
🔄 Запрос #6127 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 549026

🔄 Запрос #6128 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 117 спецификаций. Всего: 549143
🔄 Запрос #6129 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 549248
🔄 Запрос #6130 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 549355
🔄 Запрос #6131 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 70 спецификаций. Всего: 549425
🔄 Запрос #6132 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 132 спецификаций. Всего: 549557
🔄 Запрос #6133 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 549653
🔄 Запрос #6134 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 549749
🔄 Запрос #6135 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 94 спецификаций. Всего: 549843
🔄 Запрос #6136 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 139 спецификаций. Всего: 549982
🔄 Запрос #6137 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 134 спецификаций. Всего: 550116
🔄 Запрос #6138 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 122 спецификаций. Всего: 550238
🔄 Запрос #6139 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 137 спецификаций. Всего: 550375
🔄 Запрос #6140 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 153 спецификаций. Всего: 550528
🔄 Запрос #6141 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 550640
🔄 Запрос #6142 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 550759
🔄 Запрос #6143 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 120 спецификаций. Всего: 550879
🔄 Запрос #6144 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 550984
🔄 Запрос #6145 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 120 спецификаций. Всего: 551104
🔄 Запрос #6146 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 551203
🔄 Запрос #6147 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 551308
🔄 Запрос #6148 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 551408
🔄 Запрос #6149 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 88 спецификаций. Всего: 551496
🔄 Запрос #6150 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 95 спецификаций. Всего: 551591
🔄 Запрос #6151 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 88 спецификаций. Всего: 551679
🔄 Запрос #6152 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 551778
🔄 Запрос #6153 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 70 спецификаций. Всего: 551848
🔄 Запрос #6154 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 551947
🔄 Запрос #6155 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 129 спецификаций. Всего: 552076
🔄 Запрос #6156 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 552167
🔄 Запрос #6157 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 83 спецификаций. Всего: 552250
🔄 Запрос #6158 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 552366
🔄 Запрос #6159 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 552466
🔄 Запрос #6160 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 552568
🔄 Запрос #6161 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 552676
🔄 Запрос #6162 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 552801
📤 Сохранено 10044 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #6163 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 552916
🔄 Запрос #6164 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 553030
🔄 Запрос #6165 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 97 спецификаций. Всего: 553127
🔄 Запрос #6166 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 46 спецификаций. Всего: 553173
🔄 Запрос #6167 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 61 спецификаций. Всего: 553234
🔄 Запрос #6168 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 553337
🔄 Запрос #6169 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 553433
🔄 Запрос #6170 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 553551
🔄 Запрос #6171 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 553670
🔄 Запрос #6172 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 553786
🔄 Запрос #6173 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 131 спецификаций. Всего: 553917
🔄 Запрос #6174 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 554031
🔄 Запрос #6175 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 554130
🔄 Запрос #6176 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 554234
🔄 Запрос #6177 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 554353
🔄 Запрос #6178 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 554464
🔄 Запрос #6179 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 554575
🔄 Запрос #6180 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 85 спецификаций. Всего: 554660
🔄 Запрос #6181 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 554769
🔄 Запрос #6182 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 554875
🔄 Запрос #6183 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 101 спецификаций. Всего: 554976
🔄 Запрос #6184 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 555076
🔄 Запрос #6185 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 555184
🔄 Запрос #6186 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 555287
🔄 Запрос #6187 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 555410
🔄 Запрос #6188 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 124 спецификаций. Всего: 555534
🔄 Запрос #6189 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 78 спецификаций. Всего: 555612
🔄 Запрос #6190 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 555727
🔄 Запрос #6191 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 555843
🔄 Запрос #6192 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 124 спецификаций. Всего: 555967
🔄 Запрос #6193 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 55 спецификаций. Всего: 556022
🔄 Запрос #6194 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 556137
🔄 Запрос #6195 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 556258
🔄 Запрос #6196 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 556377
🔄 Запрос #6197 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 556481
🔄 Запрос #6198 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 155 спецификаций. Всего: 556636
🔄 Запрос #6199 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 122 спецификаций. Всего: 556758
🔄 Запрос #6200 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 556876
🔄 Запрос #6201 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 139 спецификаций. Всего: 557015
🔄 Запрос #6202 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 184 спецификаций. Всего: 557199
🔄 Запрос #6203 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 126 спецификаций. Всего: 557325
🔄 Запрос #6204 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09

📥 Загружено 144 спецификаций. Всего: 557469
🔄 Запрос #6205 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 135 спецификаций. Всего: 557604
🔄 Запрос #6206 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 557725
🔄 Запрос #6207 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 117 спецификаций. Всего: 557842
🔄 Запрос #6208 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 97 спецификаций. Всего: 557939
🔄 Запрос #6209 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 84 спецификаций. Всего: 558023
🔄 Запрос #6210 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 93 спецификаций. Всего: 558116
🔄 Запрос #6211 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 558222
🔄 Запрос #6212 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 101 спецификаций. Всего: 558323
🔄 Запрос #6213 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 558441
🔄 Запрос #6214 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 558566
🔄 Запрос #6215 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 558657
🔄 Запрос #6216 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 558762
🔄 Запрос #6217 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 558878
🔄 Запрос #6218 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 558987
🔄 Запрос #6219 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 559091
🔄 Запрос #6220 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 117 спецификаций. Всего: 559208
🔄 Запрос #6221 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 559307
🔄 Запрос #6222 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 559421
🔄 Запрос #6223 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 117 спецификаций. Всего: 559538
🔄 Запрос #6224 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 98 спецификаций. Всего: 559636
🔄 Запрос #6225 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 559750
🔄 Запрос #6226 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 559858
🔄 Запрос #6227 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 559976
🔄 Запрос #6228 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 560097
🔄 Запрос #6229 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 93 спецификаций. Всего: 560190
🔄 Запрос #6230 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 84 спецификаций. Всего: 560274
🔄 Запрос #6231 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 88 спецификаций. Всего: 560362
🔄 Запрос #6232 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 110 спецификаций. Всего: 560472
🔄 Запрос #6233 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 560586
🔄 Запрос #6234 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 134 спецификаций. Всего: 560720
🔄 Запрос #6235 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 560838
🔄 Запрос #6236 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 560961
🔄 Запрос #6237 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 561074
🔄 Запрос #6238 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 561189
🔄 Запрос #6239 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 561301
🔄 Запрос #6240 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 561410
🔄 Запрос #6241 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 561501
🔄 Запрос #6242 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 561622
🔄 Запрос #6243 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 561735
🔄 Запрос #6244 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 139 спецификаций. Всего: 561874
🔄 Запрос #6245 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 561974
🔄 Запрос #6246 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 93 спецификаций. Всего: 562067
🔄 Запрос #6247 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 562174
🔄 Запрос #6248 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 562285
🔄 Запрос #6249 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 562391
🔄 Запрос #6250 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 562512
🔄 Запрос #6251 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 562624
🔄 Запрос #6252 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 133 спецификаций. Всего: 562757
🔄 Запрос #6253 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 562872
📤 Сохранено 10071 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #6254 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 135 спецификаций. Всего: 563007
🔄 Запрос #6255 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 141 спецификаций. Всего: 563148
🔄 Запрос #6256 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 147 спецификаций. Всего: 563295
🔄 Запрос #6257 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 563401
🔄 Запрос #6258 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 563506
🔄 Запрос #6259 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 50 спецификаций. Всего: 563556
🔄 Запрос #6260 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 563662
🔄 Запрос #6261 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 140 спецификаций. Всего: 563802
🔄 Запрос #6262 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 563921
🔄 Запрос #6263 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 564037
🔄 Запрос #6264 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 564155
🔄 Запрос #6265 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 564246
🔄 Запрос #6266 для 2024-11-07 20:44:09 - 2024-11-14 20:44:09
📥 Загружено 29 спецификаций. Всего: 564275
📅 Обрабатываем диапазон 2024-10-31 20:44:09 - 2024-11-07 20:44:09 (попытка 1/5)
🔄 Запрос #6267 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 88 спецификаций. Всего: 564363
🔄 Запрос #6268 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 145 спецификаций. Всего: 564508
🔄 Запрос #6269 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 162 спецификаций. Всего: 564670
🔄 Запрос #6270 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 170 спецификаций. Всего: 564840
🔄 Запрос #6271 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 158 спецификаций. Всего: 564998
🔄 Запрос #6272 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 146 спецификаций. Всего: 565144
🔄 Запрос #6273 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 142 спецификаций. Всего: 565286
🔄 Запрос #6274 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 125 спецификаций. Всего: 565411
🔄 Запрос #6275 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 126 спецификаций. Всего: 565537
🔄 Запрос #6276 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 127 спецификаций. Всего: 565664
🔄 Запрос #6277 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 565786
🔄 Запрос #6278 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 141 спецификаций. Всего: 565927
🔄 Запрос #6279 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 144 спецификаций. Всего: 566071

🔄 Запрос #6280 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 163 спецификаций. Всего: 566234
🔄 Запрос #6281 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 138 спецификаций. Всего: 566372
🔄 Запрос #6282 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 133 спецификаций. Всего: 566505
🔄 Запрос #6283 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 66 спецификаций. Всего: 566571
🔄 Запрос #6284 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 50 спецификаций. Всего: 566621
🔄 Запрос #6285 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 566732
🔄 Запрос #6286 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 47 спецификаций. Всего: 566779
🔄 Запрос #6287 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 566899
🔄 Запрос #6288 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 567018
🔄 Запрос #6289 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 567111
🔄 Запрос #6290 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 567222
🔄 Запрос #6291 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 567328
🔄 Запрос #6292 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 567429
🔄 Запрос #6293 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 567544
🔄 Запрос #6294 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 567639
🔄 Запрос #6295 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 567756
🔄 Запрос #6296 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 567877
🔄 Запрос #6297 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 133 спецификаций. Всего: 568010
🔄 Запрос #6298 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 129 спецификаций. Всего: 568139
🔄 Запрос #6299 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 129 спецификаций. Всего: 568268
🔄 Запрос #6300 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 568371
🔄 Запрос #6301 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 78 спецификаций. Всего: 568449
🔄 Запрос #6302 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 568550
🔄 Запрос #6303 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 568656
🔄 Запрос #6304 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 568766
🔄 Запрос #6305 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 81 спецификаций. Всего: 568847
🔄 Запрос #6306 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 147 спецификаций. Всего: 568994
🔄 Запрос #6307 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 98 спецификаций. Всего: 569092
🔄 Запрос #6308 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 130 спецификаций. Всего: 569222
🔄 Запрос #6309 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 134 спецификаций. Всего: 569356
🔄 Запрос #6310 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 569470
🔄 Запрос #6311 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 140 спецификаций. Всего: 569610
🔄 Запрос #6312 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 129 спецификаций. Всего: 569739
🔄 Запрос #6313 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 130 спецификаций. Всего: 569869
🔄 Запрос #6314 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 136 спецификаций. Всего: 570005
🔄 Запрос #6315 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 100 спецификаций. Всего: 570105
🔄 Запрос #6316 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 570215
🔄 Запрос #6317 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 98 спецификаций. Всего: 570313
🔄 Запрос #6318 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 570414
🔄 Запрос #6319 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 570525
🔄 Запрос #6320 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 570631
🔄 Запрос #6321 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 142 спецификаций. Всего: 570773
🔄 Запрос #6322 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 570892
🔄 Запрос #6323 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 571000
🔄 Запрос #6324 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 571110
🔄 Запрос #6325 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 571232
🔄 Запрос #6326 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 571355
🔄 Запрос #6327 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 130 спецификаций. Всего: 571485
🔄 Запрос #6328 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 134 спецификаций. Всего: 571619
🔄 Запрос #6329 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 571736
🔄 Запрос #6330 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 91 спецификаций. Всего: 571827
🔄 Запрос #6331 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 92 спецификаций. Всего: 571919
🔄 Запрос #6332 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 90 спецификаций. Всего: 572009
🔄 Запрос #6333 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 166 спецификаций. Всего: 572175
🔄 Запрос #6334 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 146 спецификаций. Всего: 572321
🔄 Запрос #6335 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 153 спецификаций. Всего: 572474
🔄 Запрос #6336 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 168 спецификаций. Всего: 572642
🔄 Запрос #6337 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 126 спецификаций. Всего: 572768
🔄 Запрос #6338 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 150 спецификаций. Всего: 572918
📤 Сохранено 10046 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #6339 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 148 спецификаций. Всего: 573066
🔄 Запрос #6340 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 148 спецификаций. Всего: 573214
🔄 Запрос #6341 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 573331
🔄 Запрос #6342 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 137 спецификаций. Всего: 573468
🔄 Запрос #6343 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 132 спецификаций. Всего: 573600
🔄 Запрос #6344 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 133 спецификаций. Всего: 573733
🔄 Запрос #6345 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 573854
🔄 Запрос #6346 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 573976
🔄 Запрос #6347 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 574091
🔄 Запрос #6348 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 134 спецификаций. Всего: 574225
🔄 Запрос #6349 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 574342
🔄 Запрос #6350 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 574451
🔄 Запрос #6351 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 574565
🔄 Запрос #6352 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 574669
🔄 Запрос #6353 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 131 спецификаций. Всего: 574800
🔄 Запрос #6354 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 574912
🔄 Запрос #6355 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 129 спецификаций. Всего: 575041

🔄 Запрос #6356 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 126 спецификаций. Всего: 575167
🔄 Запрос #6357 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 575288
🔄 Запрос #6358 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 575398
🔄 Запрос #6359 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 575518
🔄 Запрос #6360 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 575619
🔄 Запрос #6361 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 575724
🔄 Запрос #6362 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 575825
🔄 Запрос #6363 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 575926
🔄 Запрос #6364 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 576038
🔄 Запрос #6365 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 576137
🔄 Запрос #6366 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 576248
🔄 Запрос #6367 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 576364
🔄 Запрос #6368 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 576482
🔄 Запрос #6369 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 576585
🔄 Запрос #6370 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 576678
🔄 Запрос #6371 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 78 спецификаций. Всего: 576756
🔄 Запрос #6372 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 576855
🔄 Запрос #6373 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 127 спецификаций. Всего: 576982
🔄 Запрос #6374 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 577100
🔄 Запрос #6375 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 130 спецификаций. Всего: 577230
🔄 Запрос #6376 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 128 спецификаций. Всего: 577358
🔄 Запрос #6377 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 126 спецификаций. Всего: 577484
🔄 Запрос #6378 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 133 спецификаций. Всего: 577617
🔄 Запрос #6379 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 577733
🔄 Запрос #6380 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 130 спецификаций. Всего: 577863
🔄 Запрос #6381 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 130 спецификаций. Всего: 577993
🔄 Запрос #6382 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 578114
🔄 Запрос #6383 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 578219
🔄 Запрос #6384 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 578332
🔄 Запрос #6385 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 578453
🔄 Запрос #6386 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 578552
🔄 Запрос #6387 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 578654
🔄 Запрос #6388 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 578765
🔄 Запрос #6389 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 578861
🔄 Запрос #6390 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 92 спецификаций. Всего: 578953
🔄 Запрос #6391 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 579052
🔄 Запрос #6392 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 579159
🔄 Запрос #6393 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 579271
🔄 Запрос #6394 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 579390
🔄 Запрос #6395 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 579508
🔄 Запрос #6396 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 579605
🔄 Запрос #6397 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 579710
🔄 Запрос #6398 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 579818
🔄 Запрос #6399 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 579915
🔄 Запрос #6400 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 580030
🔄 Запрос #6401 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 580132
🔄 Запрос #6402 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 580234
🔄 Запрос #6403 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 580343
🔄 Запрос #6404 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 580456
🔄 Запрос #6405 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 580545
🔄 Запрос #6406 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 580644
🔄 Запрос #6407 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 580757
🔄 Запрос #6408 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 580867
🔄 Запрос #6409 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 79 спецификаций. Всего: 580946
🔄 Запрос #6410 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 124 спецификаций. Всего: 581070
🔄 Запрос #6411 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 138 спецификаций. Всего: 581208
🔄 Запрос #6412 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 160 спецификаций. Всего: 581368
🔄 Запрос #6413 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 140 спецификаций. Всего: 581508
🔄 Запрос #6414 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 133 спецификаций. Всего: 581641
🔄 Запрос #6415 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 128 спецификаций. Всего: 581769
🔄 Запрос #6416 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 128 спецификаций. Всего: 581897
🔄 Запрос #6417 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 137 спецификаций. Всего: 582034
🔄 Запрос #6418 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 582148
🔄 Запрос #6419 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 582270
🔄 Запрос #6420 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 139 спецификаций. Всего: 582409
🔄 Запрос #6421 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 582527
🔄 Запрос #6422 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 131 спецификаций. Всего: 582658
🔄 Запрос #6423 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 582771
🔄 Запрос #6424 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 582875
🔄 Запрос #6425 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 582986
📤 Сохранено 10068 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #6426 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 583089
🔄 Запрос #6427 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 583207
🔄 Запрос #6428 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 583325
🔄 Запрос #6429 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 583436
🔄 Запрос #6430 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 583548
🔄 Запрос #6431 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 583662
🔄 Запрос #6432 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 583770
🔄 Запрос #6433 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 583872
🔄 Запрос #6434 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 583973
🔄 Запрос #6435 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 584082
🔄 Запрос #6436 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 584203
🔄 Запрос #6437 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 584310
🔄 Запрос #6438 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 584405
🔄 Запрос #6439 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 79 спецификаций. Всего: 584484
🔄 Запрос #6440 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 584579
🔄 Запрос #6441 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 584686
🔄 Запрос #6442 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 584782
🔄 Запрос #6443 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 35 спецификаций. Всего: 584817
🔄 Запрос #6444 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 1 спецификаций. Всего: 584818
🔄 Запрос #6445 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 78 спецификаций. Всего: 584896
🔄 Запрос #6446 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 94 спецификаций. Всего: 584990
🔄 Запрос #6447 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 585083
🔄 Запрос #6448 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 126 спецификаций. Всего: 585209
🔄 Запрос #6449 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 131 спецификаций. Всего: 585340
🔄 Запрос #6450 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 133 спецификаций. Всего: 585473
🔄 Запрос #6451 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 94 спецификаций. Всего: 585567
🔄 Запрос #6452 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 585689
🔄 Запрос #6453 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 585808
🔄 Запрос #6454 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 585912
🔄 Запрос #6455 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 144 спецификаций. Всего: 586056
🔄 Запрос #6456 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 586155
🔄 Запрос #6457 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 586267
🔄 Запрос #6458 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 586377
🔄 Запрос #6459 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 586473
🔄 Запрос #6460 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 68 спецификаций. Всего: 586541
🔄 Запрос #6461 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 53 спецификаций. Всего: 586594
🔄 Запрос #6462 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 100 спецификаций. Всего: 586694
🔄 Запрос #6463 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 586799
🔄 Запрос #6464 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 94 спецификаций. Всего: 586893
🔄 Запрос #6465 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 587010
🔄 Запрос #6466 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 587121
🔄 Запрос #6467 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 587237
🔄 Запрос #6468 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 587360
🔄 Запрос #6469 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 587473
🔄 Запрос #6470 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 587581
🔄 Запрос #6471 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 587680
🔄 Запрос #6472 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 587787
🔄 Запрос #6473 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 587908
🔄 Запрос #6474 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 588010
🔄 Запрос #6475 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 142 спецификаций. Всего: 588152
🔄 Запрос #6476 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 183 спецификаций. Всего: 588335
🔄 Запрос #6477 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 184 спецификаций. Всего: 588519
🔄 Запрос #6478 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 162 спецификаций. Всего: 588681
🔄 Запрос #6479 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 152 спецификаций. Всего: 588833
🔄 Запрос #6480 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 139 спецификаций. Всего: 588972
🔄 Запрос #6481 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 589075
🔄 Запрос #6482 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 88 спецификаций. Всего: 589163
🔄 Запрос #6483 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 73 спецификаций. Всего: 589236
🔄 Запрос #6484 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 589350
🔄 Запрос #6485 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 140 спецификаций. Всего: 589490
🔄 Запрос #6486 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 589612
🔄 Запрос #6487 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 133 спецификаций. Всего: 589745
🔄 Запрос #6488 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 136 спецификаций. Всего: 589881
🔄 Запрос #6489 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 128 спецификаций. Всего: 590009
🔄 Запрос #6490 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 590113
🔄 Запрос #6491 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 124 спецификаций. Всего: 590237
🔄 Запрос #6492 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 590359
🔄 Запрос #6493 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 590472
🔄 Запрос #6494 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 590580
🔄 Запрос #6495 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 590703
🔄 Запрос #6496 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 89 спецификаций. Всего: 590792
🔄 Запрос #6497 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 590912
🔄 Запрос #6498 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 140 спецификаций. Всего: 591052
🔄 Запрос #6499 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 131 спецификаций. Всего: 591183
🔄 Запрос #6500 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 125 спецификаций. Всего: 591308
🔄 Запрос #6501 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 134 спецификаций. Всего: 591442
🔄 Запрос #6502 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 140 спецификаций. Всего: 591582
🔄 Запрос #6503 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 591701
🔄 Запрос #6504 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 129 спецификаций. Всего: 591830
🔄 Запрос #6505 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 125 спецификаций. Всего: 591955
🔄 Запрос #6506 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09

📥 Загружено 119 спецификаций. Всего: 592074
🔄 Запрос #6507 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 592183
🔄 Запрос #6508 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 592292
🔄 Запрос #6509 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 90 спецификаций. Всего: 592382
🔄 Запрос #6510 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 592479
🔄 Запрос #6511 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 88 спецификаций. Всего: 592567
🔄 Запрос #6512 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 592663
🔄 Запрос #6513 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 592783
🔄 Запрос #6514 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 145 спецификаций. Всего: 592928
🔄 Запрос #6515 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 593045
📤 Сохранено 10059 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #6516 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 593161
🔄 Запрос #6517 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 128 спецификаций. Всего: 593289
🔄 Запрос #6518 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 593402
🔄 Запрос #6519 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 593510
🔄 Запрос #6520 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 593622
🔄 Запрос #6521 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 124 спецификаций. Всего: 593746
🔄 Запрос #6522 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 91 спецификаций. Всего: 593837
🔄 Запрос #6523 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 72 спецификаций. Всего: 593909
🔄 Запрос #6524 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 164 спецификаций. Всего: 594073
🔄 Запрос #6525 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 594182
🔄 Запрос #6526 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 594275
🔄 Запрос #6527 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 594385
🔄 Запрос #6528 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 124 спецификаций. Всего: 594509
🔄 Запрос #6529 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 594608
🔄 Запрос #6530 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 126 спецификаций. Всего: 594734
🔄 Запрос #6531 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 137 спецификаций. Всего: 594871
🔄 Запрос #6532 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 594981
🔄 Запрос #6533 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 137 спецификаций. Всего: 595118
🔄 Запрос #6534 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 595227
🔄 Запрос #6535 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 138 спецификаций. Всего: 595365
🔄 Запрос #6536 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 77 спецификаций. Всего: 595442
🔄 Запрос #6537 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 595555
🔄 Запрос #6538 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 154 спецификаций. Всего: 595709
🔄 Запрос #6539 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 149 спецификаций. Всего: 595858
🔄 Запрос #6540 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 124 спецификаций. Всего: 595982
🔄 Запрос #6541 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 136 спецификаций. Всего: 596118
🔄 Запрос #6542 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 92 спецификаций. Всего: 596210
🔄 Запрос #6543 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 596307
🔄 Запрос #6544 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 596427
🔄 Запрос #6545 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 91 спецификаций. Всего: 596518
🔄 Запрос #6546 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 174 спецификаций. Всего: 596692
🔄 Запрос #6547 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 596810
🔄 Запрос #6548 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 152 спецификаций. Всего: 596962
🔄 Запрос #6549 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 148 спецификаций. Всего: 597110
🔄 Запрос #6550 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 597226
🔄 Запрос #6551 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 597327
🔄 Запрос #6552 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 147 спецификаций. Всего: 597474
🔄 Запрос #6553 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 597595
🔄 Запрос #6554 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 597703
🔄 Запрос #6555 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 98 спецификаций. Всего: 597801
🔄 Запрос #6556 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 597902
🔄 Запрос #6557 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 98 спецификаций. Всего: 598000
🔄 Запрос #6558 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 89 спецификаций. Всего: 598089
🔄 Запрос #6559 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 598203
🔄 Запрос #6560 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 598321
🔄 Запрос #6561 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 598433
🔄 Запрос #6562 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 598536
🔄 Запрос #6563 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 128 спецификаций. Всего: 598664
🔄 Запрос #6564 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 598783
🔄 Запрос #6565 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 598899
🔄 Запрос #6566 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 598992
🔄 Запрос #6567 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 98 спецификаций. Всего: 599090
🔄 Запрос #6568 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 599183
🔄 Запрос #6569 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 90 спецификаций. Всего: 599273
🔄 Запрос #6570 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 90 спецификаций. Всего: 599363
🔄 Запрос #6571 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 599458
🔄 Запрос #6572 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 599577
🔄 Запрос #6573 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 599690
🔄 Запрос #6574 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 85 спецификаций. Всего: 599775
🔄 Запрос #6575 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 132 спецификаций. Всего: 599907
🔄 Запрос #6576 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 132 спецификаций. Всего: 600039
🔄 Запрос #6577 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 130 спецификаций. Всего: 600169
🔄 Запрос #6578 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 131 спецификаций. Всего: 600300
🔄 Запрос #6579 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 600407

🔄 Запрос #6580 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 600504
🔄 Запрос #6581 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 600606
🔄 Запрос #6582 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 600689
🔄 Запрос #6583 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 90 спецификаций. Всего: 600779
🔄 Запрос #6584 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 83 спецификаций. Всего: 600862
🔄 Запрос #6585 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 98 спецификаций. Всего: 600960
🔄 Запрос #6586 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 91 спецификаций. Всего: 601051
🔄 Запрос #6587 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 89 спецификаций. Всего: 601140
🔄 Запрос #6588 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 601254
🔄 Запрос #6589 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 90 спецификаций. Всего: 601344
🔄 Запрос #6590 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 601446
🔄 Запрос #6591 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 601543
🔄 Запрос #6592 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 601640
🔄 Запрос #6593 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 601749
🔄 Запрос #6594 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 124 спецификаций. Всего: 601873
🔄 Запрос #6595 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 601979
🔄 Запрос #6596 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 83 спецификаций. Всего: 602062
🔄 Запрос #6597 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 33 спецификаций. Всего: 602095
🔄 Запрос #6598 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 602190
🔄 Запрос #6599 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 602295
🔄 Запрос #6600 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 602403
🔄 Запрос #6601 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 87 спецификаций. Всего: 602490
🔄 Запрос #6602 для 2024-10-31 20:44:09 - 2024-11-07 20:44:09
📥 Загружено 89 спецификаций. Всего: 602579
📅 Обрабатываем диапазон 2024-10-24 20:44:09 - 2024-10-31 20:44:09 (попытка 1/5)
🔄 Запрос #6603 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 113 спецификаций. Всего: 602692
🔄 Запрос #6604 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 130 спецификаций. Всего: 602822
🔄 Запрос #6605 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 79 спецификаций. Всего: 602901
🔄 Запрос #6606 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 128 спецификаций. Всего: 603029
🔄 Запрос #6607 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 115 спецификаций. Всего: 603144
📤 Сохранено 10099 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #6608 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 92 спецификаций. Всего: 603236
🔄 Запрос #6609 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 114 спецификаций. Всего: 603350
🔄 Запрос #6610 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 100 спецификаций. Всего: 603450
🔄 Запрос #6611 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 115 спецификаций. Всего: 603565
🔄 Запрос #6612 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 134 спецификаций. Всего: 603699
🔄 Запрос #6613 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 102 спецификаций. Всего: 603801
🔄 Запрос #6614 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 88 спецификаций. Всего: 603889
🔄 Запрос #6615 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 118 спецификаций. Всего: 604007
🔄 Запрос #6616 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 120 спецификаций. Всего: 604127
🔄 Запрос #6617 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 86 спецификаций. Всего: 604213
🔄 Запрос #6618 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 103 спецификаций. Всего: 604316
🔄 Запрос #6619 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 102 спецификаций. Всего: 604418
🔄 Запрос #6620 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 101 спецификаций. Всего: 604519
🔄 Запрос #6621 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 60 спецификаций. Всего: 604579
🔄 Запрос #6622 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 98 спецификаций. Всего: 604677
🔄 Запрос #6623 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 106 спецификаций. Всего: 604783
🔄 Запрос #6624 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 108 спецификаций. Всего: 604891
🔄 Запрос #6625 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 109 спецификаций. Всего: 605000
🔄 Запрос #6626 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 102 спецификаций. Всего: 605102
🔄 Запрос #6627 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 74 спецификаций. Всего: 605176
🔄 Запрос #6628 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 61 спецификаций. Всего: 605237
🔄 Запрос #6629 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 43 спецификаций. Всего: 605280
🔄 Запрос #6630 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 55 спецификаций. Всего: 605335
🔄 Запрос #6631 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 109 спецификаций. Всего: 605444
🔄 Запрос #6632 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 119 спецификаций. Всего: 605563
🔄 Запрос #6633 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 130 спецификаций. Всего: 605693
🔄 Запрос #6634 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 119 спецификаций. Всего: 605812
🔄 Запрос #6635 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 78 спецификаций. Всего: 605890
🔄 Запрос #6636 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 88 спецификаций. Всего: 605978
🔄 Запрос #6637 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 98 спецификаций. Всего: 606076
🔄 Запрос #6638 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 111 спецификаций. Всего: 606187
🔄 Запрос #6639 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 108 спецификаций. Всего: 606295
🔄 Запрос #6640 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 120 спецификаций. Всего: 606415
🔄 Запрос #6641 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 109 спецификаций. Всего: 606524
🔄 Запрос #6642 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 101 спецификаций. Всего: 606625
🔄 Запрос #6643 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 107 спецификаций. Всего: 606732
🔄 Запрос #6644 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 114 спецификаций. Всего: 606846
🔄 Запрос #6645 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 111 спецификаций. Всего: 606957
🔄 Запрос #6646 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 43 спецификаций. Всего: 607000
🔄 Запрос #6647 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 38 спецификаций. Всего: 607038
🔄 Запрос #6648 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 84 спецификаций. Всего: 607122
🔄 Запрос #6649 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 102 спецификаций. Всего: 607224
🔄 Запрос #6650 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 65 спецификаций. Всего: 607289
🔄 Запрос #6651 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 81 спецификаций. Всего: 607370
🔄 Запрос #6652 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 106 спецификаций. Всего: 607476
🔄 Запрос #6653 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 107 спецификаций. Всего: 607583
🔄 Запрос #6654 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09

📥 Загружено 130 спецификаций. Всего: 607713
🔄 Запрос #6655 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 114 спецификаций. Всего: 607827
🔄 Запрос #6656 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 175 спецификаций. Всего: 608002
🔄 Запрос #6657 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 163 спецификаций. Всего: 608165
🔄 Запрос #6658 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 145 спецификаций. Всего: 608310
🔄 Запрос #6659 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 153 спецификаций. Всего: 608463
🔄 Запрос #6660 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 136 спецификаций. Всего: 608599
🔄 Запрос #6661 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 125 спецификаций. Всего: 608724
🔄 Запрос #6662 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 101 спецификаций. Всего: 608825
🔄 Запрос #6663 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 113 спецификаций. Всего: 608938
🔄 Запрос #6664 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 117 спецификаций. Всего: 609055
🔄 Запрос #6665 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 609172
🔄 Запрос #6666 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 127 спецификаций. Всего: 609299
🔄 Запрос #6667 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 129 спецификаций. Всего: 609428
🔄 Запрос #6668 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 131 спецификаций. Всего: 609559
🔄 Запрос #6669 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 116 спецификаций. Всего: 609675
🔄 Запрос #6670 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 93 спецификаций. Всего: 609768
🔄 Запрос #6671 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 103 спецификаций. Всего: 609871
🔄 Запрос #6672 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 102 спецификаций. Всего: 609973
🔄 Запрос #6673 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 83 спецификаций. Всего: 610056
🔄 Запрос #6674 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 85 спецификаций. Всего: 610141
🔄 Запрос #6675 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 36 спецификаций. Всего: 610177
🔄 Запрос #6676 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 3 спецификаций. Всего: 610180
🔄 Запрос #6677 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 1 спецификаций. Всего: 610181
🔄 Запрос #6678 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 0 спецификаций. Всего: 610181
🔄 Запрос #6679 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 22 спецификаций. Всего: 610203
🔄 Запрос #6680 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 79 спецификаций. Всего: 610282
🔄 Запрос #6681 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 99 спецификаций. Всего: 610381
🔄 Запрос #6682 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 74 спецификаций. Всего: 610455
🔄 Запрос #6683 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 97 спецификаций. Всего: 610552
🔄 Запрос #6684 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 145 спецификаций. Всего: 610697
🔄 Запрос #6685 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 115 спецификаций. Всего: 610812
🔄 Запрос #6686 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 131 спецификаций. Всего: 610943
🔄 Запрос #6687 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 115 спецификаций. Всего: 611058
🔄 Запрос #6688 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 94 спецификаций. Всего: 611152
🔄 Запрос #6689 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 101 спецификаций. Всего: 611253
🔄 Запрос #6690 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 109 спецификаций. Всего: 611362
🔄 Запрос #6691 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 121 спецификаций. Всего: 611483
🔄 Запрос #6692 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 119 спецификаций. Всего: 611602
🔄 Запрос #6693 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 109 спецификаций. Всего: 611711
🔄 Запрос #6694 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 116 спецификаций. Всего: 611827
🔄 Запрос #6695 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 111 спецификаций. Всего: 611938
🔄 Запрос #6696 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 109 спецификаций. Всего: 612047
🔄 Запрос #6697 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 101 спецификаций. Всего: 612148
🔄 Запрос #6698 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 125 спецификаций. Всего: 612273
🔄 Запрос #6699 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 131 спецификаций. Всего: 612404
🔄 Запрос #6700 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 130 спецификаций. Всего: 612534
🔄 Запрос #6701 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 136 спецификаций. Всего: 612670
🔄 Запрос #6702 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 105 спецификаций. Всего: 612775
🔄 Запрос #6703 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 148 спецификаций. Всего: 612923
🔄 Запрос #6704 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 106 спецификаций. Всего: 613029
🔄 Запрос #6705 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 140 спецификаций. Всего: 613169
📤 Сохранено 10025 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #6706 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 138 спецификаций. Всего: 613307
🔄 Запрос #6707 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 107 спецификаций. Всего: 613414
🔄 Запрос #6708 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 139 спецификаций. Всего: 613553
🔄 Запрос #6709 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 168 спецификаций. Всего: 613721
🔄 Запрос #6710 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 175 спецификаций. Всего: 613896
🔄 Запрос #6711 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 153 спецификаций. Всего: 614049
🔄 Запрос #6712 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 129 спецификаций. Всего: 614178
🔄 Запрос #6713 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 131 спецификаций. Всего: 614309
🔄 Запрос #6714 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 137 спецификаций. Всего: 614446
🔄 Запрос #6715 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 614571
🔄 Запрос #6716 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 119 спецификаций. Всего: 614690
🔄 Запрос #6717 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 110 спецификаций. Всего: 614800
🔄 Запрос #6718 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 119 спецификаций. Всего: 614919
🔄 Запрос #6719 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 120 спецификаций. Всего: 615039
🔄 Запрос #6720 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 109 спецификаций. Всего: 615148
🔄 Запрос #6721 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 97 спецификаций. Всего: 615245
🔄 Запрос #6722 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 88 спецификаций. Всего: 615333
🔄 Запрос #6723 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 96 спецификаций. Всего: 615429
🔄 Запрос #6724 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 104 спецификаций. Всего: 615533
🔄 Запрос #6725 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 104 спецификаций. Всего: 615637
🔄 Запрос #6726 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 106 спецификаций. Всего: 615743
🔄 Запрос #6727 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 109 спецификаций. Всего: 615852
🔄 Запрос #6728 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 108 спецификаций. Всего: 615960

🔄 Запрос #6729 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 103 спецификаций. Всего: 616063
🔄 Запрос #6730 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 89 спецификаций. Всего: 616152
🔄 Запрос #6731 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 75 спецификаций. Всего: 616227
🔄 Запрос #6732 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 73 спецификаций. Всего: 616300
🔄 Запрос #6733 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 98 спецификаций. Всего: 616398
🔄 Запрос #6734 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 102 спецификаций. Всего: 616500
🔄 Запрос #6735 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 75 спецификаций. Всего: 616575
🔄 Запрос #6736 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 72 спецификаций. Всего: 616647
🔄 Запрос #6737 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 88 спецификаций. Всего: 616735
🔄 Запрос #6738 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 87 спецификаций. Всего: 616822
🔄 Запрос #6739 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 80 спецификаций. Всего: 616902
🔄 Запрос #6740 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 117 спецификаций. Всего: 617019
🔄 Запрос #6741 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 106 спецификаций. Всего: 617125
🔄 Запрос #6742 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 87 спецификаций. Всего: 617212
🔄 Запрос #6743 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 106 спецификаций. Всего: 617318
🔄 Запрос #6744 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 136 спецификаций. Всего: 617454
🔄 Запрос #6745 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 116 спецификаций. Всего: 617570
🔄 Запрос #6746 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 111 спецификаций. Всего: 617681
🔄 Запрос #6747 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 112 спецификаций. Всего: 617793
🔄 Запрос #6748 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 104 спецификаций. Всего: 617897
🔄 Запрос #6749 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 116 спецификаций. Всего: 618013
🔄 Запрос #6750 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 123 спецификаций. Всего: 618136
🔄 Запрос #6751 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 87 спецификаций. Всего: 618223
🔄 Запрос #6752 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 124 спецификаций. Всего: 618347
🔄 Запрос #6753 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 108 спецификаций. Всего: 618455
🔄 Запрос #6754 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 119 спецификаций. Всего: 618574
🔄 Запрос #6755 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 120 спецификаций. Всего: 618694
🔄 Запрос #6756 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 112 спецификаций. Всего: 618806
🔄 Запрос #6757 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 92 спецификаций. Всего: 618898
🔄 Запрос #6758 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 135 спецификаций. Всего: 619033
🔄 Запрос #6759 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 126 спецификаций. Всего: 619159
🔄 Запрос #6760 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 122 спецификаций. Всего: 619281
🔄 Запрос #6761 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 120 спецификаций. Всего: 619401
🔄 Запрос #6762 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 124 спецификаций. Всего: 619525
🔄 Запрос #6763 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 110 спецификаций. Всего: 619635
🔄 Запрос #6764 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 104 спецификаций. Всего: 619739
🔄 Запрос #6765 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 102 спецификаций. Всего: 619841
🔄 Запрос #6766 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 122 спецификаций. Всего: 619963
🔄 Запрос #6767 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 106 спецификаций. Всего: 620069
🔄 Запрос #6768 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 101 спецификаций. Всего: 620170
🔄 Запрос #6769 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 88 спецификаций. Всего: 620258
🔄 Запрос #6770 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 100 спецификаций. Всего: 620358
🔄 Запрос #6771 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 125 спецификаций. Всего: 620483
🔄 Запрос #6772 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 96 спецификаций. Всего: 620579
🔄 Запрос #6773 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 89 спецификаций. Всего: 620668
🔄 Запрос #6774 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 117 спецификаций. Всего: 620785
🔄 Запрос #6775 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 109 спецификаций. Всего: 620894
🔄 Запрос #6776 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 97 спецификаций. Всего: 620991
🔄 Запрос #6777 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 97 спецификаций. Всего: 621088
🔄 Запрос #6778 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 93 спецификаций. Всего: 621181
🔄 Запрос #6779 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 84 спецификаций. Всего: 621265
🔄 Запрос #6780 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 84 спецификаций. Всего: 621349
🔄 Запрос #6781 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 103 спецификаций. Всего: 621452
🔄 Запрос #6782 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 117 спецификаций. Всего: 621569
🔄 Запрос #6783 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 110 спецификаций. Всего: 621679
🔄 Запрос #6784 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 128 спецификаций. Всего: 621807
🔄 Запрос #6785 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 119 спецификаций. Всего: 621926
🔄 Запрос #6786 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 126 спецификаций. Всего: 622052
🔄 Запрос #6787 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 125 спецификаций. Всего: 622177
🔄 Запрос #6788 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 126 спецификаций. Всего: 622303
🔄 Запрос #6789 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 141 спецификаций. Всего: 622444
🔄 Запрос #6790 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 155 спецификаций. Всего: 622599
🔄 Запрос #6791 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 138 спецификаций. Всего: 622737
🔄 Запрос #6792 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 131 спецификаций. Всего: 622868
🔄 Запрос #6793 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 145 спецификаций. Всего: 623013
🔄 Запрос #6794 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 148 спецификаций. Всего: 623161
🔄 Запрос #6795 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 123 спецификаций. Всего: 623284
📤 Сохранено 10115 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #6796 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 109 спецификаций. Всего: 623393
🔄 Запрос #6797 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 159 спецификаций. Всего: 623552
🔄 Запрос #6798 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 126 спецификаций. Всего: 623678
🔄 Запрос #6799 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 137 спецификаций. Всего: 623815
🔄 Запрос #6800 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 162 спецификаций. Всего: 623977
🔄 Запрос #6801 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 143 спецификаций. Всего: 624120
🔄 Запрос #6802 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 143 спецификаций. Всего: 624263
🔄 Запрос #6803 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 150 спецификаций. Всего: 624413
🔄 Запрос #6804 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 159 спецификаций. Всего: 624572
🔄 Запрос #6805 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09

📥 Загружено 164 спецификаций. Всего: 624736
🔄 Запрос #6806 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 107 спецификаций. Всего: 624843
🔄 Запрос #6807 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 156 спецификаций. Всего: 624999
🔄 Запрос #6808 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 162 спецификаций. Всего: 625161
🔄 Запрос #6809 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 107 спецификаций. Всего: 625268
🔄 Запрос #6810 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 148 спецификаций. Всего: 625416
🔄 Запрос #6811 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 96 спецификаций. Всего: 625512
🔄 Запрос #6812 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 186 спецификаций. Всего: 625698
🔄 Запрос #6813 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 141 спецификаций. Всего: 625839
🔄 Запрос #6814 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 156 спецификаций. Всего: 625995
🔄 Запрос #6815 для 2024-10-24 20:44:09 - 2024-10-31 20:44:09
📥 Загружено 132 спецификаций. Всего: 626127
📅 Обрабатываем диапазон 2024-10-17 20:44:09 - 2024-10-24 20:44:09 (попытка 1/5)
🔄 Запрос #6816 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 103 спецификаций. Всего: 626230
🔄 Запрос #6817 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 171 спецификаций. Всего: 626401
🔄 Запрос #6818 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 144 спецификаций. Всего: 626545
🔄 Запрос #6819 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 129 спецификаций. Всего: 626674
🔄 Запрос #6820 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 137 спецификаций. Всего: 626811
🔄 Запрос #6821 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 111 спецификаций. Всего: 626922
🔄 Запрос #6822 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 125 спецификаций. Всего: 627047
🔄 Запрос #6823 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 115 спецификаций. Всего: 627162
🔄 Запрос #6824 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 131 спецификаций. Всего: 627293
🔄 Запрос #6825 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 121 спецификаций. Всего: 627414
🔄 Запрос #6826 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 114 спецификаций. Всего: 627528
🔄 Запрос #6827 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 129 спецификаций. Всего: 627657
🔄 Запрос #6828 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 117 спецификаций. Всего: 627774
🔄 Запрос #6829 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 122 спецификаций. Всего: 627896
🔄 Запрос #6830 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 97 спецификаций. Всего: 627993
🔄 Запрос #6831 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 124 спецификаций. Всего: 628117
🔄 Запрос #6832 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 108 спецификаций. Всего: 628225
🔄 Запрос #6833 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 101 спецификаций. Всего: 628326
🔄 Запрос #6834 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 88 спецификаций. Всего: 628414
🔄 Запрос #6835 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 107 спецификаций. Всего: 628521
🔄 Запрос #6836 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 108 спецификаций. Всего: 628629
🔄 Запрос #6837 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 110 спецификаций. Всего: 628739
🔄 Запрос #6838 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 131 спецификаций. Всего: 628870
🔄 Запрос #6839 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 104 спецификаций. Всего: 628974
🔄 Запрос #6840 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 94 спецификаций. Всего: 629068
🔄 Запрос #6841 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 94 спецификаций. Всего: 629162
🔄 Запрос #6842 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 89 спецификаций. Всего: 629251
🔄 Запрос #6843 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 135 спецификаций. Всего: 629386
🔄 Запрос #6844 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 126 спецификаций. Всего: 629512
🔄 Запрос #6845 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 119 спецификаций. Всего: 629631
🔄 Запрос #6846 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 107 спецификаций. Всего: 629738
🔄 Запрос #6847 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 112 спецификаций. Всего: 629850
🔄 Запрос #6848 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 99 спецификаций. Всего: 629949
🔄 Запрос #6849 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 111 спецификаций. Всего: 630060
🔄 Запрос #6850 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 90 спецификаций. Всего: 630150
🔄 Запрос #6851 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 114 спецификаций. Всего: 630264
🔄 Запрос #6852 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 95 спецификаций. Всего: 630359
🔄 Запрос #6853 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 101 спецификаций. Всего: 630460
🔄 Запрос #6854 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 96 спецификаций. Всего: 630556
🔄 Запрос #6855 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 134 спецификаций. Всего: 630690
🔄 Запрос #6856 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 186 спецификаций. Всего: 630876
🔄 Запрос #6857 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 152 спецификаций. Всего: 631028
🔄 Запрос #6858 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 119 спецификаций. Всего: 631147
🔄 Запрос #6859 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 163 спецификаций. Всего: 631310
🔄 Запрос #6860 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 99 спецификаций. Всего: 631409
🔄 Запрос #6861 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 116 спецификаций. Всего: 631525
🔄 Запрос #6862 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 156 спецификаций. Всего: 631681
🔄 Запрос #6863 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 121 спецификаций. Всего: 631802
🔄 Запрос #6864 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 97 спецификаций. Всего: 631899
🔄 Запрос #6865 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 99 спецификаций. Всего: 631998
🔄 Запрос #6866 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 126 спецификаций. Всего: 632124
🔄 Запрос #6867 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 107 спецификаций. Всего: 632231
🔄 Запрос #6868 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 114 спецификаций. Всего: 632345
🔄 Запрос #6869 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 114 спецификаций. Всего: 632459
🔄 Запрос #6870 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 129 спецификаций. Всего: 632588
🔄 Запрос #6871 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 103 спецификаций. Всего: 632691
🔄 Запрос #6872 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 106 спецификаций. Всего: 632797
🔄 Запрос #6873 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 115 спецификаций. Всего: 632912
🔄 Запрос #6874 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 103 спецификаций. Всего: 633015
🔄 Запрос #6875 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 115 спецификаций. Всего: 633130
🔄 Запрос #6876 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 102 спецификаций. Всего: 633232
🔄 Запрос #6877 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 83 спецификаций. Всего: 633315
📤 Сохранено 10031 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #6878 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 94 спецификаций. Всего: 633409
🔄 Запрос #6879 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 88 спецификаций. Всего: 633497
🔄 Запрос #6880 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 81 спецификаций. Всего: 633578

🔄 Запрос #6881 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 95 спецификаций. Всего: 633673
🔄 Запрос #6882 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 98 спецификаций. Всего: 633771
🔄 Запрос #6883 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 96 спецификаций. Всего: 633867
🔄 Запрос #6884 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 105 спецификаций. Всего: 633972
🔄 Запрос #6885 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 113 спецификаций. Всего: 634085
🔄 Запрос #6886 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 69 спецификаций. Всего: 634154
🔄 Запрос #6887 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 129 спецификаций. Всего: 634283
🔄 Запрос #6888 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 113 спецификаций. Всего: 634396
🔄 Запрос #6889 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 88 спецификаций. Всего: 634484
🔄 Запрос #6890 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 115 спецификаций. Всего: 634599
🔄 Запрос #6891 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 116 спецификаций. Всего: 634715
🔄 Запрос #6892 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 126 спецификаций. Всего: 634841
🔄 Запрос #6893 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 117 спецификаций. Всего: 634958
🔄 Запрос #6894 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 99 спецификаций. Всего: 635057
🔄 Запрос #6895 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 110 спецификаций. Всего: 635167
🔄 Запрос #6896 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 123 спецификаций. Всего: 635290
🔄 Запрос #6897 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 123 спецификаций. Всего: 635413
🔄 Запрос #6898 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 114 спецификаций. Всего: 635527
🔄 Запрос #6899 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 109 спецификаций. Всего: 635636
🔄 Запрос #6900 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 127 спецификаций. Всего: 635763
🔄 Запрос #6901 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 107 спецификаций. Всего: 635870
🔄 Запрос #6902 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 98 спецификаций. Всего: 635968
🔄 Запрос #6903 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 101 спецификаций. Всего: 636069
🔄 Запрос #6904 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 173 спецификаций. Всего: 636242
🔄 Запрос #6905 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 85 спецификаций. Всего: 636327
🔄 Запрос #6906 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 7 спецификаций. Всего: 636334
🔄 Запрос #6907 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 1 спецификаций. Всего: 636335
🔄 Запрос #6908 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 41 спецификаций. Всего: 636376
🔄 Запрос #6909 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 145 спецификаций. Всего: 636521
🔄 Запрос #6910 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 125 спецификаций. Всего: 636646
🔄 Запрос #6911 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 119 спецификаций. Всего: 636765
🔄 Запрос #6912 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 121 спецификаций. Всего: 636886
🔄 Запрос #6913 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 136 спецификаций. Всего: 637022
🔄 Запрос #6914 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 130 спецификаций. Всего: 637152
🔄 Запрос #6915 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 125 спецификаций. Всего: 637277
🔄 Запрос #6916 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 142 спецификаций. Всего: 637419
🔄 Запрос #6917 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 133 спецификаций. Всего: 637552
🔄 Запрос #6918 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 139 спецификаций. Всего: 637691
🔄 Запрос #6919 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 123 спецификаций. Всего: 637814
🔄 Запрос #6920 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 113 спецификаций. Всего: 637927
🔄 Запрос #6921 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 134 спецификаций. Всего: 638061
🔄 Запрос #6922 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 119 спецификаций. Всего: 638180
🔄 Запрос #6923 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 99 спецификаций. Всего: 638279
🔄 Запрос #6924 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 99 спецификаций. Всего: 638378
🔄 Запрос #6925 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 114 спецификаций. Всего: 638492
🔄 Запрос #6926 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 102 спецификаций. Всего: 638594
🔄 Запрос #6927 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 111 спецификаций. Всего: 638705
🔄 Запрос #6928 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 127 спецификаций. Всего: 638832
🔄 Запрос #6929 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 114 спецификаций. Всего: 638946
🔄 Запрос #6930 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 110 спецификаций. Всего: 639056
🔄 Запрос #6931 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 78 спецификаций. Всего: 639134
🔄 Запрос #6932 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 79 спецификаций. Всего: 639213
🔄 Запрос #6933 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 122 спецификаций. Всего: 639335
🔄 Запрос #6934 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 107 спецификаций. Всего: 639442
🔄 Запрос #6935 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 104 спецификаций. Всего: 639546
🔄 Запрос #6936 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 112 спецификаций. Всего: 639658
🔄 Запрос #6937 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 71 спецификаций. Всего: 639729
🔄 Запрос #6938 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 74 спецификаций. Всего: 639803
🔄 Запрос #6939 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 71 спецификаций. Всего: 639874
🔄 Запрос #6940 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 103 спецификаций. Всего: 639977
🔄 Запрос #6941 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 93 спецификаций. Всего: 640070
🔄 Запрос #6942 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 90 спецификаций. Всего: 640160
🔄 Запрос #6943 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 94 спецификаций. Всего: 640254
🔄 Запрос #6944 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 113 спецификаций. Всего: 640367
🔄 Запрос #6945 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 110 спецификаций. Всего: 640477
🔄 Запрос #6946 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 105 спецификаций. Всего: 640582
🔄 Запрос #6947 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 106 спецификаций. Всего: 640688
🔄 Запрос #6948 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 110 спецификаций. Всего: 640798
🔄 Запрос #6949 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 111 спецификаций. Всего: 640909
🔄 Запрос #6950 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 108 спецификаций. Всего: 641017
🔄 Запрос #6951 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 111 спецификаций. Всего: 641128
🔄 Запрос #6952 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 109 спецификаций. Всего: 641237
🔄 Запрос #6953 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 97 спецификаций. Всего: 641334
🔄 Запрос #6954 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 107 спецификаций. Всего: 641441
🔄 Запрос #6955 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 120 спецификаций. Всего: 641561
🔄 Запрос #6956 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 115 спецификаций. Всего: 641676

🔄 Запрос #6957 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 103 спецификаций. Всего: 641779
🔄 Запрос #6958 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 122 спецификаций. Всего: 641901
🔄 Запрос #6959 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 114 спецификаций. Всего: 642015
🔄 Запрос #6960 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 123 спецификаций. Всего: 642138
🔄 Запрос #6961 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 124 спецификаций. Всего: 642262
🔄 Запрос #6962 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 111 спецификаций. Всего: 642373
🔄 Запрос #6963 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 111 спецификаций. Всего: 642484
🔄 Запрос #6964 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 120 спецификаций. Всего: 642604
🔄 Запрос #6965 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 103 спецификаций. Всего: 642707
🔄 Запрос #6966 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 103 спецификаций. Всего: 642810
🔄 Запрос #6967 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 94 спецификаций. Всего: 642904
🔄 Запрос #6968 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 83 спецификаций. Всего: 642987
🔄 Запрос #6969 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 144 спецификаций. Всего: 643131
🔄 Запрос #6970 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 133 спецификаций. Всего: 643264
🔄 Запрос #6971 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 83 спецификаций. Всего: 643347
📤 Сохранено 10032 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #6972 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 81 спецификаций. Всего: 643428
🔄 Запрос #6973 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 126 спецификаций. Всего: 643554
🔄 Запрос #6974 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 643679
🔄 Запрос #6975 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 84 спецификаций. Всего: 643763
🔄 Запрос #6976 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 100 спецификаций. Всего: 643863
🔄 Запрос #6977 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 643978
🔄 Запрос #6978 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 141 спецификаций. Всего: 644119
🔄 Запрос #6979 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 124 спецификаций. Всего: 644243
🔄 Запрос #6980 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 137 спецификаций. Всего: 644380
🔄 Запрос #6981 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 125 спецификаций. Всего: 644505
🔄 Запрос #6982 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 127 спецификаций. Всего: 644632
🔄 Запрос #6983 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 133 спецификаций. Всего: 644765
🔄 Запрос #6984 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 123 спецификаций. Всего: 644888
🔄 Запрос #6985 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 123 спецификаций. Всего: 645011
🔄 Запрос #6986 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 110 спецификаций. Всего: 645121
🔄 Запрос #6987 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 101 спецификаций. Всего: 645222
🔄 Запрос #6988 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 32 спецификаций. Всего: 645254
🔄 Запрос #6989 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 93 спецификаций. Всего: 645347
🔄 Запрос #6990 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 103 спецификаций. Всего: 645450
🔄 Запрос #6991 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 96 спецификаций. Всего: 645546
🔄 Запрос #6992 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 98 спецификаций. Всего: 645644
🔄 Запрос #6993 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 101 спецификаций. Всего: 645745
🔄 Запрос #6994 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 108 спецификаций. Всего: 645853
🔄 Запрос #6995 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 88 спецификаций. Всего: 645941
🔄 Запрос #6996 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 108 спецификаций. Всего: 646049
🔄 Запрос #6997 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 121 спецификаций. Всего: 646170
🔄 Запрос #6998 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 58 спецификаций. Всего: 646228
🔄 Запрос #6999 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 107 спецификаций. Всего: 646335
🔄 Запрос #7000 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 115 спецификаций. Всего: 646450
🔄 Запрос #7001 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 107 спецификаций. Всего: 646557
🔄 Запрос #7002 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 112 спецификаций. Всего: 646669
🔄 Запрос #7003 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 113 спецификаций. Всего: 646782
🔄 Запрос #7004 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 139 спецификаций. Всего: 646921
🔄 Запрос #7005 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 112 спецификаций. Всего: 647033
🔄 Запрос #7006 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 133 спецификаций. Всего: 647166
🔄 Запрос #7007 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 128 спецификаций. Всего: 647294
🔄 Запрос #7008 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 112 спецификаций. Всего: 647406
🔄 Запрос #7009 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 103 спецификаций. Всего: 647509
🔄 Запрос #7010 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 110 спецификаций. Всего: 647619
🔄 Запрос #7011 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 103 спецификаций. Всего: 647722
🔄 Запрос #7012 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 118 спецификаций. Всего: 647840
🔄 Запрос #7013 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 92 спецификаций. Всего: 647932
🔄 Запрос #7014 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 90 спецификаций. Всего: 648022
🔄 Запрос #7015 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 122 спецификаций. Всего: 648144
🔄 Запрос #7016 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 106 спецификаций. Всего: 648250
🔄 Запрос #7017 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 113 спецификаций. Всего: 648363
🔄 Запрос #7018 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 102 спецификаций. Всего: 648465
🔄 Запрос #7019 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 96 спецификаций. Всего: 648561
🔄 Запрос #7020 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 104 спецификаций. Всего: 648665
🔄 Запрос #7021 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 114 спецификаций. Всего: 648779
🔄 Запрос #7022 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 112 спецификаций. Всего: 648891
🔄 Запрос #7023 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 128 спецификаций. Всего: 649019
🔄 Запрос #7024 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 135 спецификаций. Всего: 649154
🔄 Запрос #7025 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 120 спецификаций. Всего: 649274
🔄 Запрос #7026 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 113 спецификаций. Всего: 649387
🔄 Запрос #7027 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 166 спецификаций. Всего: 649553
🔄 Запрос #7028 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 143 спецификаций. Всего: 649696
🔄 Запрос #7029 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 149 спецификаций. Всего: 649845
🔄 Запрос #7030 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 138 спецификаций. Всего: 649983
🔄 Запрос #7031 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09

📥 Загружено 120 спецификаций. Всего: 650103
🔄 Запрос #7032 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 20 спецификаций. Всего: 650123
🔄 Запрос #7033 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 8 спецификаций. Всего: 650131
🔄 Запрос #7034 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 24 спецификаций. Всего: 650155
🔄 Запрос #7035 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 46 спецификаций. Всего: 650201
🔄 Запрос #7036 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 43 спецификаций. Всего: 650244
🔄 Запрос #7037 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 89 спецификаций. Всего: 650333
🔄 Запрос #7038 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 80 спецификаций. Всего: 650413
🔄 Запрос #7039 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 52 спецификаций. Всего: 650465
🔄 Запрос #7040 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 42 спецификаций. Всего: 650507
🔄 Запрос #7041 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 60 спецификаций. Всего: 650567
🔄 Запрос #7042 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 76 спецификаций. Всего: 650643
🔄 Запрос #7043 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 197 спецификаций. Всего: 650840
🔄 Запрос #7044 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 79 спецификаций. Всего: 650919
🔄 Запрос #7045 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 138 спецификаций. Всего: 651057
🔄 Запрос #7046 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 125 спецификаций. Всего: 651182
🔄 Запрос #7047 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 125 спецификаций. Всего: 651307
🔄 Запрос #7048 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 132 спецификаций. Всего: 651439
🔄 Запрос #7049 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 103 спецификаций. Всего: 651542
🔄 Запрос #7050 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 101 спецификаций. Всего: 651643
🔄 Запрос #7051 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 127 спецификаций. Всего: 651770
🔄 Запрос #7052 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 113 спецификаций. Всего: 651883
🔄 Запрос #7053 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 112 спецификаций. Всего: 651995
🔄 Запрос #7054 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 121 спецификаций. Всего: 652116
🔄 Запрос #7055 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 121 спецификаций. Всего: 652237
🔄 Запрос #7056 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 128 спецификаций. Всего: 652365
🔄 Запрос #7057 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 127 спецификаций. Всего: 652492
🔄 Запрос #7058 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 109 спецификаций. Всего: 652601
🔄 Запрос #7059 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 111 спецификаций. Всего: 652712
🔄 Запрос #7060 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 119 спецификаций. Всего: 652831
🔄 Запрос #7061 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 136 спецификаций. Всего: 652967
🔄 Запрос #7062 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 140 спецификаций. Всего: 653107
🔄 Запрос #7063 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 101 спецификаций. Всего: 653208
🔄 Запрос #7064 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 98 спецификаций. Всего: 653306
🔄 Запрос #7065 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 122 спецификаций. Всего: 653428
📤 Сохранено 10081 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #7066 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 86 спецификаций. Всего: 653514
🔄 Запрос #7067 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 83 спецификаций. Всего: 653597
🔄 Запрос #7068 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 111 спецификаций. Всего: 653708
🔄 Запрос #7069 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 119 спецификаций. Всего: 653827
🔄 Запрос #7070 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 119 спецификаций. Всего: 653946
🔄 Запрос #7071 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 86 спецификаций. Всего: 654032
🔄 Запрос #7072 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 126 спецификаций. Всего: 654158
🔄 Запрос #7073 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 127 спецификаций. Всего: 654285
🔄 Запрос #7074 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 140 спецификаций. Всего: 654425
🔄 Запрос #7075 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 131 спецификаций. Всего: 654556
🔄 Запрос #7076 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 105 спецификаций. Всего: 654661
🔄 Запрос #7077 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 107 спецификаций. Всего: 654768
🔄 Запрос #7078 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 654889
🔄 Запрос #7079 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 112 спецификаций. Всего: 655001
🔄 Запрос #7080 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 119 спецификаций. Всего: 655120
🔄 Запрос #7081 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 111 спецификаций. Всего: 655231
🔄 Запрос #7082 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 135 спецификаций. Всего: 655366
🔄 Запрос #7083 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 112 спецификаций. Всего: 655478
🔄 Запрос #7084 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 110 спецификаций. Всего: 655588
🔄 Запрос #7085 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 104 спецификаций. Всего: 655692
🔄 Запрос #7086 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 124 спецификаций. Всего: 655816
🔄 Запрос #7087 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 106 спецификаций. Всего: 655922
🔄 Запрос #7088 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 95 спецификаций. Всего: 656017
🔄 Запрос #7089 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 123 спецификаций. Всего: 656140
🔄 Запрос #7090 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 166 спецификаций. Всего: 656306
🔄 Запрос #7091 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 145 спецификаций. Всего: 656451
🔄 Запрос #7092 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 156 спецификаций. Всего: 656607
🔄 Запрос #7093 для 2024-10-17 20:44:09 - 2024-10-24 20:44:09
📥 Загружено 58 спецификаций. Всего: 656665
📅 Обрабатываем диапазон 2024-10-10 20:44:09 - 2024-10-17 20:44:09 (попытка 1/5)
🔄 Запрос #7094 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 125 спецификаций. Всего: 656790
🔄 Запрос #7095 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 130 спецификаций. Всего: 656920
🔄 Запрос #7096 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 146 спецификаций. Всего: 657066
🔄 Запрос #7097 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 117 спецификаций. Всего: 657183
🔄 Запрос #7098 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 115 спецификаций. Всего: 657298
🔄 Запрос #7099 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 104 спецификаций. Всего: 657402
🔄 Запрос #7100 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 108 спецификаций. Всего: 657510
🔄 Запрос #7101 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 109 спецификаций. Всего: 657619
🔄 Запрос #7102 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 119 спецификаций. Всего: 657738
🔄 Запрос #7103 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 154 спецификаций. Всего: 657892
🔄 Запрос #7104 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 171 спецификаций. Всего: 658063
🔄 Запрос #7105 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 134 спецификаций. Всего: 658197

🔄 Запрос #7106 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 95 спецификаций. Всего: 658292
🔄 Запрос #7107 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 91 спецификаций. Всего: 658383
🔄 Запрос #7108 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 101 спецификаций. Всего: 658484
🔄 Запрос #7109 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 93 спецификаций. Всего: 658577
🔄 Запрос #7110 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 90 спецификаций. Всего: 658667
🔄 Запрос #7111 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 102 спецификаций. Всего: 658769
🔄 Запрос #7112 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 105 спецификаций. Всего: 658874
🔄 Запрос #7113 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 108 спецификаций. Всего: 658982
🔄 Запрос #7114 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 120 спецификаций. Всего: 659102
🔄 Запрос #7115 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 118 спецификаций. Всего: 659220
🔄 Запрос #7116 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 109 спецификаций. Всего: 659329
🔄 Запрос #7117 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 97 спецификаций. Всего: 659426
🔄 Запрос #7118 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 97 спецификаций. Всего: 659523
🔄 Запрос #7119 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 659623
🔄 Запрос #7120 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 102 спецификаций. Всего: 659725
🔄 Запрос #7121 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 101 спецификаций. Всего: 659826
🔄 Запрос #7122 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 93 спецификаций. Всего: 659919
🔄 Запрос #7123 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 106 спецификаций. Всего: 660025
🔄 Запрос #7124 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 95 спецификаций. Всего: 660120
🔄 Запрос #7125 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 105 спецификаций. Всего: 660225
🔄 Запрос #7126 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 102 спецификаций. Всего: 660327
🔄 Запрос #7127 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 107 спецификаций. Всего: 660434
🔄 Запрос #7128 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 97 спецификаций. Всего: 660531
🔄 Запрос #7129 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 105 спецификаций. Всего: 660636
🔄 Запрос #7130 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 81 спецификаций. Всего: 660717
🔄 Запрос #7131 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 80 спецификаций. Всего: 660797
🔄 Запрос #7132 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 105 спецификаций. Всего: 660902
🔄 Запрос #7133 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 124 спецификаций. Всего: 661026
🔄 Запрос #7134 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 71 спецификаций. Всего: 661097
🔄 Запрос #7135 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 18 спецификаций. Всего: 661115
🔄 Запрос #7136 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 41 спецификаций. Всего: 661156
🔄 Запрос #7137 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 111 спецификаций. Всего: 661267
🔄 Запрос #7138 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 124 спецификаций. Всего: 661391
🔄 Запрос #7139 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 118 спецификаций. Всего: 661509
🔄 Запрос #7140 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 114 спецификаций. Всего: 661623
🔄 Запрос #7141 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 95 спецификаций. Всего: 661718
🔄 Запрос #7142 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 94 спецификаций. Всего: 661812
🔄 Запрос #7143 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 99 спецификаций. Всего: 661911
🔄 Запрос #7144 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 102 спецификаций. Всего: 662013
🔄 Запрос #7145 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 118 спецификаций. Всего: 662131
🔄 Запрос #7146 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 105 спецификаций. Всего: 662236
🔄 Запрос #7147 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 130 спецификаций. Всего: 662366
🔄 Запрос #7148 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 140 спецификаций. Всего: 662506
🔄 Запрос #7149 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 63 спецификаций. Всего: 662569
🔄 Запрос #7150 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 97 спецификаций. Всего: 662666
🔄 Запрос #7151 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 145 спецификаций. Всего: 662811
🔄 Запрос #7152 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 85 спецификаций. Всего: 662896
🔄 Запрос #7153 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 86 спецификаций. Всего: 662982
🔄 Запрос #7154 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 663093
🔄 Запрос #7155 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 110 спецификаций. Всего: 663203
🔄 Запрос #7156 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 663312
🔄 Запрос #7157 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 117 спецификаций. Всего: 663429
📤 Сохранено 10001 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #7158 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 137 спецификаций. Всего: 663566
🔄 Запрос #7159 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 116 спецификаций. Всего: 663682
🔄 Запрос #7160 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 113 спецификаций. Всего: 663795
🔄 Запрос #7161 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 115 спецификаций. Всего: 663910
🔄 Запрос #7162 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 664024
🔄 Запрос #7163 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 664135
🔄 Запрос #7164 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 109 спецификаций. Всего: 664244
🔄 Запрос #7165 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 116 спецификаций. Всего: 664360
🔄 Запрос #7166 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 122 спецификаций. Всего: 664482
🔄 Запрос #7167 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 86 спецификаций. Всего: 664568
🔄 Запрос #7168 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 101 спецификаций. Всего: 664669
🔄 Запрос #7169 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 71 спецификаций. Всего: 664740
🔄 Запрос #7170 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 98 спецификаций. Всего: 664838
🔄 Запрос #7171 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 108 спецификаций. Всего: 664946
🔄 Запрос #7172 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 114 спецификаций. Всего: 665060
🔄 Запрос #7173 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 117 спецификаций. Всего: 665177
🔄 Запрос #7174 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 113 спецификаций. Всего: 665290
🔄 Запрос #7175 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 109 спецификаций. Всего: 665399
🔄 Запрос #7176 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 114 спецификаций. Всего: 665513
🔄 Запрос #7177 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 101 спецификаций. Всего: 665614
🔄 Запрос #7178 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09

📥 Загружено 90 спецификаций. Всего: 665704
🔄 Запрос #7179 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 104 спецификаций. Всего: 665808
🔄 Запрос #7180 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 107 спецификаций. Всего: 665915
🔄 Запрос #7181 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 95 спецификаций. Всего: 666010
🔄 Запрос #7182 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 92 спецификаций. Всего: 666102
🔄 Запрос #7183 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 107 спецификаций. Всего: 666209
🔄 Запрос #7184 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 105 спецификаций. Всего: 666314
🔄 Запрос #7185 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 137 спецификаций. Всего: 666451
🔄 Запрос #7186 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 135 спецификаций. Всего: 666586
🔄 Запрос #7187 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 118 спецификаций. Всего: 666704
🔄 Запрос #7188 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 666815
🔄 Запрос #7189 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 120 спецификаций. Всего: 666935
🔄 Запрос #7190 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 121 спецификаций. Всего: 667056
🔄 Запрос #7191 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 121 спецификаций. Всего: 667177
🔄 Запрос #7192 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 117 спецификаций. Всего: 667294
🔄 Запрос #7193 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 667405
🔄 Запрос #7194 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 116 спецификаций. Всего: 667521
🔄 Запрос #7195 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 107 спецификаций. Всего: 667628
🔄 Запрос #7196 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 115 спецификаций. Всего: 667743
🔄 Запрос #7197 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 108 спецификаций. Всего: 667851
🔄 Запрос #7198 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 121 спецификаций. Всего: 667972
🔄 Запрос #7199 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 129 спецификаций. Всего: 668101
🔄 Запрос #7200 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 107 спецификаций. Всего: 668208
🔄 Запрос #7201 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 105 спецификаций. Всего: 668313
🔄 Запрос #7202 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 129 спецификаций. Всего: 668442
🔄 Запрос #7203 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 91 спецификаций. Всего: 668533
🔄 Запрос #7204 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 101 спецификаций. Всего: 668634
🔄 Запрос #7205 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 139 спецификаций. Всего: 668773
🔄 Запрос #7206 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 123 спецификаций. Всего: 668896
🔄 Запрос #7207 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 120 спецификаций. Всего: 669016
🔄 Запрос #7208 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 149 спецификаций. Всего: 669165
🔄 Запрос #7209 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 126 спецификаций. Всего: 669291
🔄 Запрос #7210 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 125 спецификаций. Всего: 669416
🔄 Запрос #7211 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 134 спецификаций. Всего: 669550
🔄 Запрос #7212 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 669661
🔄 Запрос #7213 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 139 спецификаций. Всего: 669800
🔄 Запрос #7214 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 126 спецификаций. Всего: 669926
🔄 Запрос #7215 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 149 спецификаций. Всего: 670075
🔄 Запрос #7216 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 143 спецификаций. Всего: 670218
🔄 Запрос #7217 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 147 спецификаций. Всего: 670365
🔄 Запрос #7218 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 116 спецификаций. Всего: 670481
🔄 Запрос #7219 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 145 спецификаций. Всего: 670626
🔄 Запрос #7220 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 126 спецификаций. Всего: 670752
🔄 Запрос #7221 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 121 спецификаций. Всего: 670873
🔄 Запрос #7222 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 147 спецификаций. Всего: 671020
🔄 Запрос #7223 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 144 спецификаций. Всего: 671164
🔄 Запрос #7224 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 135 спецификаций. Всего: 671299
🔄 Запрос #7225 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 117 спецификаций. Всего: 671416
🔄 Запрос #7226 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 115 спецификаций. Всего: 671531
🔄 Запрос #7227 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 118 спецификаций. Всего: 671649
🔄 Запрос #7228 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 122 спецификаций. Всего: 671771
🔄 Запрос #7229 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 124 спецификаций. Всего: 671895
🔄 Запрос #7230 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 123 спецификаций. Всего: 672018
🔄 Запрос #7231 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 125 спецификаций. Всего: 672143
🔄 Запрос #7232 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 101 спецификаций. Всего: 672244
🔄 Запрос #7233 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 91 спецификаций. Всего: 672335
🔄 Запрос #7234 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 84 спецификаций. Всего: 672419
🔄 Запрос #7235 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 74 спецификаций. Всего: 672493
🔄 Запрос #7236 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 75 спецификаций. Всего: 672568
🔄 Запрос #7237 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 76 спецификаций. Всего: 672644
🔄 Запрос #7238 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 51 спецификаций. Всего: 672695
🔄 Запрос #7239 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 98 спецификаций. Всего: 672793
🔄 Запрос #7240 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 125 спецификаций. Всего: 672918
🔄 Запрос #7241 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 132 спецификаций. Всего: 673050
🔄 Запрос #7242 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 135 спецификаций. Всего: 673185
🔄 Запрос #7243 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 98 спецификаций. Всего: 673283
🔄 Запрос #7244 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 104 спецификаций. Всего: 673387
🔄 Запрос #7245 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 129 спецификаций. Всего: 673516
📤 Сохранено 10087 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #7246 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 131 спецификаций. Всего: 673647
🔄 Запрос #7247 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 113 спецификаций. Всего: 673760
🔄 Запрос #7248 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 673871
🔄 Запрос #7249 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 96 спецификаций. Всего: 673967
🔄 Запрос #7250 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 114 спецификаций. Всего: 674081
🔄 Запрос #7251 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 108 спецификаций. Всего: 674189
🔄 Запрос #7252 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 113 спецификаций. Всего: 674302
🔄 Запрос #7253 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 118 спецификаций. Всего: 674420
🔄 Запрос #7254 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 97 спецификаций. Всего: 674517

🔄 Запрос #7255 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 99 спецификаций. Всего: 674616
🔄 Запрос #7256 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 109 спецификаций. Всего: 674725
🔄 Запрос #7257 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 96 спецификаций. Всего: 674821
🔄 Запрос #7258 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 101 спецификаций. Всего: 674922
🔄 Запрос #7259 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 113 спецификаций. Всего: 675035
🔄 Запрос #7260 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 117 спецификаций. Всего: 675152
🔄 Запрос #7261 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 129 спецификаций. Всего: 675281
🔄 Запрос #7262 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 122 спецификаций. Всего: 675403
🔄 Запрос #7263 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 58 спецификаций. Всего: 675461
🔄 Запрос #7264 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 65 спецификаций. Всего: 675526
🔄 Запрос #7265 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 115 спецификаций. Всего: 675641
🔄 Запрос #7266 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 178 спецификаций. Всего: 675819
🔄 Запрос #7267 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 116 спецификаций. Всего: 675935
🔄 Запрос #7268 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 80 спецификаций. Всего: 676015
🔄 Запрос #7269 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 120 спецификаций. Всего: 676135
🔄 Запрос #7270 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 168 спецификаций. Всего: 676303
🔄 Запрос #7271 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 146 спецификаций. Всего: 676449
🔄 Запрос #7272 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 141 спецификаций. Всего: 676590
🔄 Запрос #7273 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 130 спецификаций. Всего: 676720
🔄 Запрос #7274 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 109 спецификаций. Всего: 676829
🔄 Запрос #7275 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 108 спецификаций. Всего: 676937
🔄 Запрос #7276 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 112 спецификаций. Всего: 677049
🔄 Запрос #7277 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 120 спецификаций. Всего: 677169
🔄 Запрос #7278 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 119 спецификаций. Всего: 677288
🔄 Запрос #7279 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 102 спецификаций. Всего: 677390
🔄 Запрос #7280 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 115 спецификаций. Всего: 677505
🔄 Запрос #7281 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 116 спецификаций. Всего: 677621
🔄 Запрос #7282 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 113 спецификаций. Всего: 677734
🔄 Запрос #7283 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 677845
🔄 Запрос #7284 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 114 спецификаций. Всего: 677959
🔄 Запрос #7285 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 121 спецификаций. Всего: 678080
🔄 Запрос #7286 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 136 спецификаций. Всего: 678216
🔄 Запрос #7287 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 125 спецификаций. Всего: 678341
🔄 Запрос #7288 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 107 спецификаций. Всего: 678448
🔄 Запрос #7289 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 106 спецификаций. Всего: 678554
🔄 Запрос #7290 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 109 спецификаций. Всего: 678663
🔄 Запрос #7291 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 107 спецификаций. Всего: 678770
🔄 Запрос #7292 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 115 спецификаций. Всего: 678885
🔄 Запрос #7293 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 87 спецификаций. Всего: 678972
🔄 Запрос #7294 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 126 спецификаций. Всего: 679098
🔄 Запрос #7295 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 679213
🔄 Запрос #7296 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 679324
🔄 Запрос #7297 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 100 спецификаций. Всего: 679424
🔄 Запрос #7298 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 100 спецификаций. Всего: 679524
🔄 Запрос #7299 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 105 спецификаций. Всего: 679629
🔄 Запрос #7300 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 145 спецификаций. Всего: 679774
🔄 Запрос #7301 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 157 спецификаций. Всего: 679931
🔄 Запрос #7302 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 163 спецификаций. Всего: 680094
🔄 Запрос #7303 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 146 спецификаций. Всего: 680240
🔄 Запрос #7304 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 131 спецификаций. Всего: 680371
🔄 Запрос #7305 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 119 спецификаций. Всего: 680490
🔄 Запрос #7306 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 126 спецификаций. Всего: 680616
🔄 Запрос #7307 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 109 спецификаций. Всего: 680725
🔄 Запрос #7308 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 680836
🔄 Запрос #7309 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 102 спецификаций. Всего: 680938
🔄 Запрос #7310 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 681038
🔄 Запрос #7311 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 100 спецификаций. Всего: 681138
🔄 Запрос #7312 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 96 спецификаций. Всего: 681234
🔄 Запрос #7313 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 101 спецификаций. Всего: 681335
🔄 Запрос #7314 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 92 спецификаций. Всего: 681427
🔄 Запрос #7315 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 94 спецификаций. Всего: 681521
🔄 Запрос #7316 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 107 спецификаций. Всего: 681628
🔄 Запрос #7317 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 107 спецификаций. Всего: 681735
🔄 Запрос #7318 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 118 спецификаций. Всего: 681853
🔄 Запрос #7319 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 123 спецификаций. Всего: 681976
🔄 Запрос #7320 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 682087
🔄 Запрос #7321 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 105 спецификаций. Всего: 682192
🔄 Запрос #7322 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 108 спецификаций. Всего: 682300
🔄 Запрос #7323 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 81 спецификаций. Всего: 682381
🔄 Запрос #7324 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 117 спецификаций. Всего: 682498
🔄 Запрос #7325 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 160 спецификаций. Всего: 682658
🔄 Запрос #7326 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 157 спецификаций. Всего: 682815
🔄 Запрос #7327 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 116 спецификаций. Всего: 682931

🔄 Запрос #7328 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 134 спецификаций. Всего: 683065
🔄 Запрос #7329 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 154 спецификаций. Всего: 683219
🔄 Запрос #7330 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 122 спецификаций. Всего: 683341
🔄 Запрос #7331 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 157 спецификаций. Всего: 683498
🔄 Запрос #7332 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 112 спецификаций. Всего: 683610
📤 Сохранено 10094 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #7333 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 189 спецификаций. Всего: 683799
🔄 Запрос #7334 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 179 спецификаций. Всего: 683978
🔄 Запрос #7335 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 100 спецификаций. Всего: 684078
🔄 Запрос #7336 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 684189
🔄 Запрос #7337 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 140 спецификаций. Всего: 684329
🔄 Запрос #7338 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 108 спецификаций. Всего: 684437
🔄 Запрос #7339 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 118 спецификаций. Всего: 684555
🔄 Запрос #7340 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 155 спецификаций. Всего: 684710
🔄 Запрос #7341 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 94 спецификаций. Всего: 684804
🔄 Запрос #7342 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 0 спецификаций. Всего: 684804
🔄 Запрос #7343 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 1 спецификаций. Всего: 684805
🔄 Запрос #7344 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 0 спецификаций. Всего: 684805
🔄 Запрос #7345 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 1 спецификаций. Всего: 684806
🔄 Запрос #7346 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 1 спецификаций. Всего: 684807
🔄 Запрос #7347 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 39 спецификаций. Всего: 684846
🔄 Запрос #7348 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 140 спецификаций. Всего: 684986
🔄 Запрос #7349 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 150 спецификаций. Всего: 685136
🔄 Запрос #7350 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 135 спецификаций. Всего: 685271
🔄 Запрос #7351 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 129 спецификаций. Всего: 685400
🔄 Запрос #7352 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 109 спецификаций. Всего: 685509
🔄 Запрос #7353 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 101 спецификаций. Всего: 685610
🔄 Запрос #7354 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 81 спецификаций. Всего: 685691
🔄 Запрос #7355 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 86 спецификаций. Всего: 685777
🔄 Запрос #7356 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 90 спецификаций. Всего: 685867
🔄 Запрос #7357 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 115 спецификаций. Всего: 685982
🔄 Запрос #7358 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 124 спецификаций. Всего: 686106
🔄 Запрос #7359 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 87 спецификаций. Всего: 686193
🔄 Запрос #7360 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 103 спецификаций. Всего: 686296
🔄 Запрос #7361 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 108 спецификаций. Всего: 686404
🔄 Запрос #7362 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 116 спецификаций. Всего: 686520
🔄 Запрос #7363 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 106 спецификаций. Всего: 686626
🔄 Запрос #7364 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 119 спецификаций. Всего: 686745
🔄 Запрос #7365 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 95 спецификаций. Всего: 686840
🔄 Запрос #7366 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 131 спецификаций. Всего: 686971
🔄 Запрос #7367 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 153 спецификаций. Всего: 687124
🔄 Запрос #7368 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 90 спецификаций. Всего: 687214
🔄 Запрос #7369 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 87 спецификаций. Всего: 687301
🔄 Запрос #7370 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 74 спецификаций. Всего: 687375
🔄 Запрос #7371 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 92 спецификаций. Всего: 687467
🔄 Запрос #7372 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 113 спецификаций. Всего: 687580
🔄 Запрос #7373 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 111 спецификаций. Всего: 687691
🔄 Запрос #7374 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 83 спецификаций. Всего: 687774
🔄 Запрос #7375 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 95 спецификаций. Всего: 687869
🔄 Запрос #7376 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 85 спецификаций. Всего: 687954
🔄 Запрос #7377 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 83 спецификаций. Всего: 688037
🔄 Запрос #7378 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 82 спецификаций. Всего: 688119
🔄 Запрос #7379 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 98 спецификаций. Всего: 688217
🔄 Запрос #7380 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 95 спецификаций. Всего: 688312
🔄 Запрос #7381 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 104 спецификаций. Всего: 688416
🔄 Запрос #7382 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 96 спецификаций. Всего: 688512
🔄 Запрос #7383 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 103 спецификаций. Всего: 688615
🔄 Запрос #7384 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 104 спецификаций. Всего: 688719
🔄 Запрос #7385 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 115 спецификаций. Всего: 688834
🔄 Запрос #7386 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 120 спецификаций. Всего: 688954
🔄 Запрос #7387 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 115 спецификаций. Всего: 689069
🔄 Запрос #7388 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 115 спецификаций. Всего: 689184
🔄 Запрос #7389 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 123 спецификаций. Всего: 689307
🔄 Запрос #7390 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 125 спецификаций. Всего: 689432
🔄 Запрос #7391 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 109 спецификаций. Всего: 689541
🔄 Запрос #7392 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 100 спецификаций. Всего: 689641
🔄 Запрос #7393 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 95 спецификаций. Всего: 689736
🔄 Запрос #7394 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 31 спецификаций. Всего: 689767
🔄 Запрос #7395 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 94 спецификаций. Всего: 689861
🔄 Запрос #7396 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 123 спецификаций. Всего: 689984
🔄 Запрос #7397 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 89 спецификаций. Всего: 690073
🔄 Запрос #7398 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 90 спецификаций. Всего: 690163
🔄 Запрос #7399 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 121 спецификаций. Всего: 690284
🔄 Запрос #7400 для 2024-10-10 20:44:09 - 2024-10-17 20:44:09
📥 Загружено 79 спецификаций. Всего: 690363
📅 Обрабатываем диапазон 2024-10-03 20:44:09 - 2024-10-10 20:44:09 (попытка 1/5)
🔄 Запрос #7401 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 146 спецификаций. Всего: 690509
🔄 Запрос #7402 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09

📥 Загружено 83 спецификаций. Всего: 690592
🔄 Запрос #7403 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 131 спецификаций. Всего: 690723
🔄 Запрос #7404 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 150 спецификаций. Всего: 690873
🔄 Запрос #7405 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 150 спецификаций. Всего: 691023
🔄 Запрос #7406 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 132 спецификаций. Всего: 691155
🔄 Запрос #7407 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 108 спецификаций. Всего: 691263
🔄 Запрос #7408 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 118 спецификаций. Всего: 691381
🔄 Запрос #7409 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 691509
🔄 Запрос #7410 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 145 спецификаций. Всего: 691654
🔄 Запрос #7411 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 131 спецификаций. Всего: 691785
🔄 Запрос #7412 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 691913
🔄 Запрос #7413 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 139 спецификаций. Всего: 692052
🔄 Запрос #7414 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 138 спецификаций. Всего: 692190
🔄 Запрос #7415 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 109 спецификаций. Всего: 692299
🔄 Запрос #7416 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 108 спецификаций. Всего: 692407
🔄 Запрос #7417 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 102 спецификаций. Всего: 692509
🔄 Запрос #7418 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 144 спецификаций. Всего: 692653
🔄 Запрос #7419 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 128 спецификаций. Всего: 692781
🔄 Запрос #7420 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 123 спецификаций. Всего: 692904
🔄 Запрос #7421 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 129 спецификаций. Всего: 693033
🔄 Запрос #7422 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 119 спецификаций. Всего: 693152
🔄 Запрос #7423 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 126 спецификаций. Всего: 693278
🔄 Запрос #7424 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 142 спецификаций. Всего: 693420
🔄 Запрос #7425 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 116 спецификаций. Всего: 693536
🔄 Запрос #7426 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 118 спецификаций. Всего: 693654
📤 Сохранено 10044 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #7427 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 693759
🔄 Запрос #7428 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 103 спецификаций. Всего: 693862
🔄 Запрос #7429 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 112 спецификаций. Всего: 693974
🔄 Запрос #7430 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 102 спецификаций. Всего: 694076
🔄 Запрос #7431 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 694184
🔄 Запрос #7432 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 113 спецификаций. Всего: 694297
🔄 Запрос #7433 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 127 спецификаций. Всего: 694424
🔄 Запрос #7434 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 121 спецификаций. Всего: 694545
🔄 Запрос #7435 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 122 спецификаций. Всего: 694667
🔄 Запрос #7436 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 103 спецификаций. Всего: 694770
🔄 Запрос #7437 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 694880
🔄 Запрос #7438 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 103 спецификаций. Всего: 694983
🔄 Запрос #7439 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 103 спецификаций. Всего: 695086
🔄 Запрос #7440 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 126 спецификаций. Всего: 695212
🔄 Запрос #7441 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 109 спецификаций. Всего: 695321
🔄 Запрос #7442 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 112 спецификаций. Всего: 695433
🔄 Запрос #7443 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 124 спецификаций. Всего: 695557
🔄 Запрос #7444 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 133 спецификаций. Всего: 695690
🔄 Запрос #7445 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 123 спецификаций. Всего: 695813
🔄 Запрос #7446 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 118 спецификаций. Всего: 695931
🔄 Запрос #7447 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 126 спецификаций. Всего: 696057
🔄 Запрос #7448 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 117 спецификаций. Всего: 696174
🔄 Запрос #7449 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 129 спецификаций. Всего: 696303
🔄 Запрос #7450 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 134 спецификаций. Всего: 696437
🔄 Запрос #7451 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 124 спецификаций. Всего: 696561
🔄 Запрос #7452 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 94 спецификаций. Всего: 696655
🔄 Запрос #7453 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 115 спецификаций. Всего: 696770
🔄 Запрос #7454 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 89 спецификаций. Всего: 696859
🔄 Запрос #7455 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 119 спецификаций. Всего: 696978
🔄 Запрос #7456 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 84 спецификаций. Всего: 697062
🔄 Запрос #7457 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 697172
🔄 Запрос #7458 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 137 спецификаций. Всего: 697309
🔄 Запрос #7459 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 697414
🔄 Запрос #7460 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 118 спецификаций. Всего: 697532
🔄 Запрос #7461 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 151 спецификаций. Всего: 697683
🔄 Запрос #7462 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 97 спецификаций. Всего: 697780
🔄 Запрос #7463 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 150 спецификаций. Всего: 697930
🔄 Запрос #7464 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 137 спецификаций. Всего: 698067
🔄 Запрос #7465 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 126 спецификаций. Всего: 698193
🔄 Запрос #7466 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 138 спецификаций. Всего: 698331
🔄 Запрос #7467 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 112 спецификаций. Всего: 698443
🔄 Запрос #7468 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 115 спецификаций. Всего: 698558
🔄 Запрос #7469 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 698669
🔄 Запрос #7470 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 100 спецификаций. Всего: 698769
🔄 Запрос #7471 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 88 спецификаций. Всего: 698857
🔄 Запрос #7472 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 101 спецификаций. Всего: 698958
🔄 Запрос #7473 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 109 спецификаций. Всего: 699067

🔄 Запрос #7474 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 127 спецификаций. Всего: 699194
🔄 Запрос #7475 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 699299
🔄 Запрос #7476 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 107 спецификаций. Всего: 699406
🔄 Запрос #7477 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 115 спецификаций. Всего: 699521
🔄 Запрос #7478 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 121 спецификаций. Всего: 699642
🔄 Запрос #7479 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 104 спецификаций. Всего: 699746
🔄 Запрос #7480 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 113 спецификаций. Всего: 699859
🔄 Запрос #7481 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 97 спецификаций. Всего: 699956
🔄 Запрос #7482 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 109 спецификаций. Всего: 700065
🔄 Запрос #7483 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 117 спецификаций. Всего: 700182
🔄 Запрос #7484 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 98 спецификаций. Всего: 700280
🔄 Запрос #7485 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 95 спецификаций. Всего: 700375
🔄 Запрос #7486 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 106 спецификаций. Всего: 700481
🔄 Запрос #7487 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 111 спецификаций. Всего: 700592
🔄 Запрос #7488 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 144 спецификаций. Всего: 700736
🔄 Запрос #7489 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 106 спецификаций. Всего: 700842
🔄 Запрос #7490 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 131 спецификаций. Всего: 700973
🔄 Запрос #7491 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 145 спецификаций. Всего: 701118
🔄 Запрос #7492 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 99 спецификаций. Всего: 701217
🔄 Запрос #7493 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 122 спецификаций. Всего: 701339
🔄 Запрос #7494 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 115 спецификаций. Всего: 701454
🔄 Запрос #7495 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 114 спецификаций. Всего: 701568
🔄 Запрос #7496 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 115 спецификаций. Всего: 701683
🔄 Запрос #7497 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 135 спецификаций. Всего: 701818
🔄 Запрос #7498 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 109 спецификаций. Всего: 701927
🔄 Запрос #7499 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 101 спецификаций. Всего: 702028
🔄 Запрос #7500 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 123 спецификаций. Всего: 702151
🔄 Запрос #7501 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 102 спецификаций. Всего: 702253
🔄 Запрос #7502 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 115 спецификаций. Всего: 702368
🔄 Запрос #7503 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 92 спецификаций. Всего: 702460
🔄 Запрос #7504 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 93 спецификаций. Всего: 702553
🔄 Запрос #7505 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 122 спецификаций. Всего: 702675
🔄 Запрос #7506 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 702780
🔄 Запрос #7507 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 702885
🔄 Запрос #7508 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 104 спецификаций. Всего: 702989
🔄 Запрос #7509 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 106 спецификаций. Всего: 703095
🔄 Запрос #7510 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 703205
🔄 Запрос #7511 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 112 спецификаций. Всего: 703317
🔄 Запрос #7512 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 99 спецификаций. Всего: 703416
🔄 Запрос #7513 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 116 спецификаций. Всего: 703532
🔄 Запрос #7514 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 109 спецификаций. Всего: 703641
🔄 Запрос #7515 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 129 спецификаций. Всего: 703770
📤 Сохранено 10116 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #7516 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 123 спецификаций. Всего: 703893
🔄 Запрос #7517 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 138 спецификаций. Всего: 704031
🔄 Запрос #7518 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 134 спецификаций. Всего: 704165
🔄 Запрос #7519 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 128 спецификаций. Всего: 704293
🔄 Запрос #7520 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 162 спецификаций. Всего: 704455
🔄 Запрос #7521 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 117 спецификаций. Всего: 704572
🔄 Запрос #7522 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 704682
🔄 Запрос #7523 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 127 спецификаций. Всего: 704809
🔄 Запрос #7524 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 143 спецификаций. Всего: 704952
🔄 Запрос #7525 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 125 спецификаций. Всего: 705077
🔄 Запрос #7526 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 113 спецификаций. Всего: 705190
🔄 Запрос #7527 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 129 спецификаций. Всего: 705319
🔄 Запрос #7528 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 121 спецификаций. Всего: 705440
🔄 Запрос #7529 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 113 спецификаций. Всего: 705553
🔄 Запрос #7530 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 65 спецификаций. Всего: 705618
🔄 Запрос #7531 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 12 спецификаций. Всего: 705630
🔄 Запрос #7532 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 137 спецификаций. Всего: 705767
🔄 Запрос #7533 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 107 спецификаций. Всего: 705874
🔄 Запрос #7534 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 705979
🔄 Запрос #7535 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 706089
🔄 Запрос #7536 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 706194
🔄 Запрос #7537 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 103 спецификаций. Всего: 706297
🔄 Запрос #7538 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 112 спецификаций. Всего: 706409
🔄 Запрос #7539 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 706519
🔄 Запрос #7540 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 706624
🔄 Запрос #7541 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 706729
🔄 Запрос #7542 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 87 спецификаций. Всего: 706816
🔄 Запрос #7543 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 82 спецификаций. Всего: 706898
🔄 Запрос #7544 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 87 спецификаций. Всего: 706985
🔄 Запрос #7545 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 90 спецификаций. Всего: 707075
🔄 Запрос #7546 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 72 спецификаций. Всего: 707147
🔄 Запрос #7547 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 74 спецификаций. Всего: 707221
🔄 Запрос #7548 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 707331
🔄 Запрос #7549 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 114 спецификаций. Всего: 707445
🔄 Запрос #7550 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09

📥 Загружено 107 спецификаций. Всего: 707552
🔄 Запрос #7551 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 124 спецификаций. Всего: 707676
🔄 Запрос #7552 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 129 спецификаций. Всего: 707805
🔄 Запрос #7553 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 115 спецификаций. Всего: 707920
🔄 Запрос #7554 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 125 спецификаций. Всего: 708045
🔄 Запрос #7555 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 106 спецификаций. Всего: 708151
🔄 Запрос #7556 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 708261
🔄 Запрос #7557 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 107 спецификаций. Всего: 708368
🔄 Запрос #7558 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 117 спецификаций. Всего: 708485
🔄 Запрос #7559 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 108 спецификаций. Всего: 708593
🔄 Запрос #7560 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 108 спецификаций. Всего: 708701
🔄 Запрос #7561 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 111 спецификаций. Всего: 708812
🔄 Запрос #7562 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 95 спецификаций. Всего: 708907
🔄 Запрос #7563 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 108 спецификаций. Всего: 709015
🔄 Запрос #7564 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 111 спецификаций. Всего: 709126
🔄 Запрос #7565 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 101 спецификаций. Всего: 709227
🔄 Запрос #7566 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 709337
🔄 Запрос #7567 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 113 спецификаций. Всего: 709450
🔄 Запрос #7568 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 130 спецификаций. Всего: 709580
🔄 Запрос #7569 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 107 спецификаций. Всего: 709687
🔄 Запрос #7570 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 128 спецификаций. Всего: 709815
🔄 Запрос #7571 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 109 спецификаций. Всего: 709924
🔄 Запрос #7572 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 116 спецификаций. Всего: 710040
🔄 Запрос #7573 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 85 спецификаций. Всего: 710125
🔄 Запрос #7574 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 174 спецификаций. Всего: 710299
🔄 Запрос #7575 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 710409
🔄 Запрос #7576 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 140 спецификаций. Всего: 710549
🔄 Запрос #7577 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 137 спецификаций. Всего: 710686
🔄 Запрос #7578 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 140 спецификаций. Всего: 710826
🔄 Запрос #7579 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 134 спецификаций. Всего: 710960
🔄 Запрос #7580 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 164 спецификаций. Всего: 711124
🔄 Запрос #7581 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 156 спецификаций. Всего: 711280
🔄 Запрос #7582 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 145 спецификаций. Всего: 711425
🔄 Запрос #7583 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 144 спецификаций. Всего: 711569
🔄 Запрос #7584 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 126 спецификаций. Всего: 711695
🔄 Запрос #7585 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 118 спецификаций. Всего: 711813
🔄 Запрос #7586 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 116 спецификаций. Всего: 711929
🔄 Запрос #7587 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 103 спецификаций. Всего: 712032
🔄 Запрос #7588 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 107 спецификаций. Всего: 712139
🔄 Запрос #7589 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 101 спецификаций. Всего: 712240
🔄 Запрос #7590 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 54 спецификаций. Всего: 712294
🔄 Запрос #7591 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 107 спецификаций. Всего: 712401
🔄 Запрос #7592 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 67 спецификаций. Всего: 712468
🔄 Запрос #7593 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 58 спецификаций. Всего: 712526
🔄 Запрос #7594 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 96 спецификаций. Всего: 712622
🔄 Запрос #7595 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 112 спецификаций. Всего: 712734
🔄 Запрос #7596 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 116 спецификаций. Всего: 712850
🔄 Запрос #7597 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 103 спецификаций. Всего: 712953
🔄 Запрос #7598 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 107 спецификаций. Всего: 713060
🔄 Запрос #7599 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 125 спецификаций. Всего: 713185
🔄 Запрос #7600 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 713295
🔄 Запрос #7601 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 125 спецификаций. Всего: 713420
🔄 Запрос #7602 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 92 спецификаций. Всего: 713512
🔄 Запрос #7603 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 116 спецификаций. Всего: 713628
🔄 Запрос #7604 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 114 спецификаций. Всего: 713742
🔄 Запрос #7605 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 111 спецификаций. Всего: 713853
📤 Сохранено 10083 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #7606 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 97 спецификаций. Всего: 713950
🔄 Запрос #7607 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 130 спецификаций. Всего: 714080
🔄 Запрос #7608 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 139 спецификаций. Всего: 714219
🔄 Запрос #7609 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 140 спецификаций. Всего: 714359
🔄 Запрос #7610 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 125 спецификаций. Всего: 714484
🔄 Запрос #7611 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 142 спецификаций. Всего: 714626
🔄 Запрос #7612 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 141 спецификаций. Всего: 714767
🔄 Запрос #7613 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 110 спецификаций. Всего: 714877
🔄 Запрос #7614 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 113 спецификаций. Всего: 714990
🔄 Запрос #7615 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 715095
🔄 Запрос #7616 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 108 спецификаций. Всего: 715203
🔄 Запрос #7617 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 106 спецификаций. Всего: 715309
🔄 Запрос #7618 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 88 спецификаций. Всего: 715397
🔄 Запрос #7619 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 107 спецификаций. Всего: 715504
🔄 Запрос #7620 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 100 спецификаций. Всего: 715604
🔄 Запрос #7621 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 90 спецификаций. Всего: 715694
🔄 Запрос #7622 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 124 спецификаций. Всего: 715818
🔄 Запрос #7623 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 715923
🔄 Запрос #7624 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 120 спецификаций. Всего: 716043
🔄 Запрос #7625 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 119 спецификаций. Всего: 716162
🔄 Запрос #7626 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09

📥 Загружено 101 спецификаций. Всего: 716263
🔄 Запрос #7627 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 102 спецификаций. Всего: 716365
🔄 Запрос #7628 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 121 спецификаций. Всего: 716486
🔄 Запрос #7629 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 150 спецификаций. Всего: 716636
🔄 Запрос #7630 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 97 спецификаций. Всего: 716733
🔄 Запрос #7631 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 125 спецификаций. Всего: 716858
🔄 Запрос #7632 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 147 спецификаций. Всего: 717005
🔄 Запрос #7633 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 139 спецификаций. Всего: 717144
🔄 Запрос #7634 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 101 спецификаций. Всего: 717245
🔄 Запрос #7635 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 92 спецификаций. Всего: 717337
🔄 Запрос #7636 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 109 спецификаций. Всего: 717446
🔄 Запрос #7637 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 79 спецификаций. Всего: 717525
🔄 Запрос #7638 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 153 спецификаций. Всего: 717678
🔄 Запрос #7639 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 158 спецификаций. Всего: 717836
🔄 Запрос #7640 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 86 спецификаций. Всего: 717922
🔄 Запрос #7641 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 86 спецификаций. Всего: 718008
🔄 Запрос #7642 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 153 спецификаций. Всего: 718161
🔄 Запрос #7643 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 119 спецификаций. Всего: 718280
🔄 Запрос #7644 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 140 спецификаций. Всего: 718420
🔄 Запрос #7645 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 136 спецификаций. Всего: 718556
🔄 Запрос #7646 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 115 спецификаций. Всего: 718671
🔄 Запрос #7647 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 129 спецификаций. Всего: 718800
🔄 Запрос #7648 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 114 спецификаций. Всего: 718914
🔄 Запрос #7649 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 137 спецификаций. Всего: 719051
🔄 Запрос #7650 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 138 спецификаций. Всего: 719189
🔄 Запрос #7651 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 149 спецификаций. Всего: 719338
🔄 Запрос #7652 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 139 спецификаций. Всего: 719477
🔄 Запрос #7653 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 142 спецификаций. Всего: 719619
🔄 Запрос #7654 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 120 спецификаций. Всего: 719739
🔄 Запрос #7655 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 108 спецификаций. Всего: 719847
🔄 Запрос #7656 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 59 спецификаций. Всего: 719906
🔄 Запрос #7657 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 84 спецификаций. Всего: 719990
🔄 Запрос #7658 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 84 спецификаций. Всего: 720074
🔄 Запрос #7659 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 105 спецификаций. Всего: 720179
🔄 Запрос #7660 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 100 спецификаций. Всего: 720279
🔄 Запрос #7661 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 49 спецификаций. Всего: 720328
🔄 Запрос #7662 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 31 спецификаций. Всего: 720359
🔄 Запрос #7663 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 59 спецификаций. Всего: 720418
🔄 Запрос #7664 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 122 спецификаций. Всего: 720540
🔄 Запрос #7665 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 85 спецификаций. Всего: 720625
🔄 Запрос #7666 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 117 спецификаций. Всего: 720742
🔄 Запрос #7667 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 90 спецификаций. Всего: 720832
🔄 Запрос #7668 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 50 спецификаций. Всего: 720882
🔄 Запрос #7669 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 31 спецификаций. Всего: 720913
🔄 Запрос #7670 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 26 спецификаций. Всего: 720939
🔄 Запрос #7671 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 83 спецификаций. Всего: 721022
🔄 Запрос #7672 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 46 спецификаций. Всего: 721068
🔄 Запрос #7673 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 53 спецификаций. Всего: 721121
🔄 Запрос #7674 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 64 спецификаций. Всего: 721185
🔄 Запрос #7675 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 40 спецификаций. Всего: 721225
🔄 Запрос #7676 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 40 спецификаций. Всего: 721265
🔄 Запрос #7677 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 52 спецификаций. Всего: 721317
🔄 Запрос #7678 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 47 спецификаций. Всего: 721364
🔄 Запрос #7679 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 25 спецификаций. Всего: 721389
🔄 Запрос #7680 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 2 спецификаций. Всего: 721391
🔄 Запрос #7681 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 1 спецификаций. Всего: 721392
🔄 Запрос #7682 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 53 спецификаций. Всего: 721445
🔄 Запрос #7683 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 62 спецификаций. Всего: 721507
🔄 Запрос #7684 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 54 спецификаций. Всего: 721561
🔄 Запрос #7685 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 54 спецификаций. Всего: 721615
🔄 Запрос #7686 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 49 спецификаций. Всего: 721664
🔄 Запрос #7687 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 83 спецификаций. Всего: 721747
🔄 Запрос #7688 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 71 спецификаций. Всего: 721818
🔄 Запрос #7689 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 42 спецификаций. Всего: 721860
🔄 Запрос #7690 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 48 спецификаций. Всего: 721908
🔄 Запрос #7691 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 57 спецификаций. Всего: 721965
🔄 Запрос #7692 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 96 спецификаций. Всего: 722061
🔄 Запрос #7693 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 97 спецификаций. Всего: 722158
🔄 Запрос #7694 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 81 спецификаций. Всего: 722239
🔄 Запрос #7695 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 74 спецификаций. Всего: 722313
🔄 Запрос #7696 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 99 спецификаций. Всего: 722412
🔄 Запрос #7697 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 66 спецификаций. Всего: 722478
🔄 Запрос #7698 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 96 спецификаций. Всего: 722574
🔄 Запрос #7699 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 124 спецификаций. Всего: 722698
🔄 Запрос #7700 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 74 спецификаций. Всего: 722772
🔄 Запрос #7701 для 2024-10-03 20:44:09 - 2024-10-10 20:44:09
📥 Загружено 61 спецификаций. Всего: 722833
📅 Обрабатываем диапазон 2024-09-26 20:44:09 - 2024-10-03 20:44:09 (попытка 1/5)
🔄 Запрос #7702 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 115 спецификаций. Всего: 722948

🔄 Запрос #7703 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 124 спецификаций. Всего: 723072
🔄 Запрос #7704 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 115 спецификаций. Всего: 723187
🔄 Запрос #7705 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 132 спецификаций. Всего: 723319
🔄 Запрос #7706 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 134 спецификаций. Всего: 723453
🔄 Запрос #7707 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 142 спецификаций. Всего: 723595
🔄 Запрос #7708 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 117 спецификаций. Всего: 723712
🔄 Запрос #7709 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 123 спецификаций. Всего: 723835
🔄 Запрос #7710 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 129 спецификаций. Всего: 723964
📤 Сохранено 10111 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #7711 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 121 спецификаций. Всего: 724085
🔄 Запрос #7712 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 103 спецификаций. Всего: 724188
🔄 Запрос #7713 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 104 спецификаций. Всего: 724292
🔄 Запрос #7714 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 114 спецификаций. Всего: 724406
🔄 Запрос #7715 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 88 спецификаций. Всего: 724494
🔄 Запрос #7716 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 85 спецификаций. Всего: 724579
🔄 Запрос #7717 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 724669
🔄 Запрос #7718 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 118 спецификаций. Всего: 724787
🔄 Запрос #7719 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 110 спецификаций. Всего: 724897
🔄 Запрос #7720 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 101 спецификаций. Всего: 724998
🔄 Запрос #7721 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 101 спецификаций. Всего: 725099
🔄 Запрос #7722 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 118 спецификаций. Всего: 725217
🔄 Запрос #7723 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 121 спецификаций. Всего: 725338
🔄 Запрос #7724 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 111 спецификаций. Всего: 725449
🔄 Запрос #7725 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 118 спецификаций. Всего: 725567
🔄 Запрос #7726 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 95 спецификаций. Всего: 725662
🔄 Запрос #7727 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 100 спецификаций. Всего: 725762
🔄 Запрос #7728 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 107 спецификаций. Всего: 725869
🔄 Запрос #7729 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 108 спецификаций. Всего: 725977
🔄 Запрос #7730 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 103 спецификаций. Всего: 726080
🔄 Запрос #7731 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 109 спецификаций. Всего: 726189
🔄 Запрос #7732 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 127 спецификаций. Всего: 726316
🔄 Запрос #7733 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 108 спецификаций. Всего: 726424
🔄 Запрос #7734 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 133 спецификаций. Всего: 726557
🔄 Запрос #7735 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 115 спецификаций. Всего: 726672
🔄 Запрос #7736 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 131 спецификаций. Всего: 726803
🔄 Запрос #7737 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 114 спецификаций. Всего: 726917
🔄 Запрос #7738 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 106 спецификаций. Всего: 727023
🔄 Запрос #7739 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 114 спецификаций. Всего: 727137
🔄 Запрос #7740 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 113 спецификаций. Всего: 727250
🔄 Запрос #7741 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 112 спецификаций. Всего: 727362
🔄 Запрос #7742 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 121 спецификаций. Всего: 727483
🔄 Запрос #7743 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 117 спецификаций. Всего: 727600
🔄 Запрос #7744 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 112 спецификаций. Всего: 727712
🔄 Запрос #7745 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 119 спецификаций. Всего: 727831
🔄 Запрос #7746 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 132 спецификаций. Всего: 727963
🔄 Запрос #7747 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 133 спецификаций. Всего: 728096
🔄 Запрос #7748 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 126 спецификаций. Всего: 728222
🔄 Запрос #7749 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 136 спецификаций. Всего: 728358
🔄 Запрос #7750 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 133 спецификаций. Всего: 728491
🔄 Запрос #7751 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 125 спецификаций. Всего: 728616
🔄 Запрос #7752 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 133 спецификаций. Всего: 728749
🔄 Запрос #7753 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 134 спецификаций. Всего: 728883
🔄 Запрос #7754 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 124 спецификаций. Всего: 729007
🔄 Запрос #7755 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 143 спецификаций. Всего: 729150
🔄 Запрос #7756 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 125 спецификаций. Всего: 729275
🔄 Запрос #7757 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 130 спецификаций. Всего: 729405
🔄 Запрос #7758 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 79 спецификаций. Всего: 729484
🔄 Запрос #7759 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 99 спецификаций. Всего: 729583
🔄 Запрос #7760 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 106 спецификаций. Всего: 729689
🔄 Запрос #7761 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 143 спецификаций. Всего: 729832
🔄 Запрос #7762 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 123 спецификаций. Всего: 729955
🔄 Запрос #7763 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 94 спецификаций. Всего: 730049
🔄 Запрос #7764 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 112 спецификаций. Всего: 730161
🔄 Запрос #7765 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 116 спецификаций. Всего: 730277
🔄 Запрос #7766 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 100 спецификаций. Всего: 730377
🔄 Запрос #7767 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 131 спецификаций. Всего: 730508
🔄 Запрос #7768 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 96 спецификаций. Всего: 730604
🔄 Запрос #7769 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 134 спецификаций. Всего: 730738
🔄 Запрос #7770 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 98 спецификаций. Всего: 730836
🔄 Запрос #7771 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 120 спецификаций. Всего: 730956
🔄 Запрос #7772 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 118 спецификаций. Всего: 731074
🔄 Запрос #7773 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 112 спецификаций. Всего: 731186
🔄 Запрос #7774 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 111 спецификаций. Всего: 731297
🔄 Запрос #7775 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 82 спецификаций. Всего: 731379
🔄 Запрос #7776 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 91 спецификаций. Всего: 731470
🔄 Запрос #7777 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 124 спецификаций. Всего: 731594
🔄 Запрос #7778 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09

📥 Загружено 117 спецификаций. Всего: 731711
🔄 Запрос #7779 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 96 спецификаций. Всего: 731807
🔄 Запрос #7780 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 99 спецификаций. Всего: 731906
🔄 Запрос #7781 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 98 спецификаций. Всего: 732004
🔄 Запрос #7782 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 110 спецификаций. Всего: 732114
🔄 Запрос #7783 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 107 спецификаций. Всего: 732221
🔄 Запрос #7784 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 117 спецификаций. Всего: 732338
🔄 Запрос #7785 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 97 спецификаций. Всего: 732435
🔄 Запрос #7786 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 99 спецификаций. Всего: 732534
🔄 Запрос #7787 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 94 спецификаций. Всего: 732628
🔄 Запрос #7788 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 91 спецификаций. Всего: 732719
🔄 Запрос #7789 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 86 спецификаций. Всего: 732805
🔄 Запрос #7790 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 79 спецификаций. Всего: 732884
🔄 Запрос #7791 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 89 спецификаций. Всего: 732973
🔄 Запрос #7792 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 87 спецификаций. Всего: 733060
🔄 Запрос #7793 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 92 спецификаций. Всего: 733152
🔄 Запрос #7794 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 89 спецификаций. Всего: 733241
🔄 Запрос #7795 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 112 спецификаций. Всего: 733353
🔄 Запрос #7796 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 117 спецификаций. Всего: 733470
🔄 Запрос #7797 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 116 спецификаций. Всего: 733586
🔄 Запрос #7798 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 106 спецификаций. Всего: 733692
🔄 Запрос #7799 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 105 спецификаций. Всего: 733797
🔄 Запрос #7800 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 102 спецификаций. Всего: 733899
🔄 Запрос #7801 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 112 спецификаций. Всего: 734011
📤 Сохранено 10047 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #7802 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 102 спецификаций. Всего: 734113
🔄 Запрос #7803 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 107 спецификаций. Всего: 734220
🔄 Запрос #7804 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 110 спецификаций. Всего: 734330
🔄 Запрос #7805 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 101 спецификаций. Всего: 734431
🔄 Запрос #7806 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 103 спецификаций. Всего: 734534
🔄 Запрос #7807 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 131 спецификаций. Всего: 734665
🔄 Запрос #7808 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 85 спецификаций. Всего: 734750
🔄 Запрос #7809 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 102 спецификаций. Всего: 734852
🔄 Запрос #7810 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 123 спецификаций. Всего: 734975
🔄 Запрос #7811 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 125 спецификаций. Всего: 735100
🔄 Запрос #7812 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 163 спецификаций. Всего: 735263
🔄 Запрос #7813 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 108 спецификаций. Всего: 735371
🔄 Запрос #7814 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 104 спецификаций. Всего: 735475
🔄 Запрос #7815 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 136 спецификаций. Всего: 735611
🔄 Запрос #7816 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 127 спецификаций. Всего: 735738
🔄 Запрос #7817 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 109 спецификаций. Всего: 735847
🔄 Запрос #7818 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 143 спецификаций. Всего: 735990
🔄 Запрос #7819 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 88 спецификаций. Всего: 736078
🔄 Запрос #7820 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 103 спецификаций. Всего: 736181
🔄 Запрос #7821 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 104 спецификаций. Всего: 736285
🔄 Запрос #7822 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 128 спецификаций. Всего: 736413
🔄 Запрос #7823 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 148 спецификаций. Всего: 736561
🔄 Запрос #7824 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 134 спецификаций. Всего: 736695
🔄 Запрос #7825 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 736822
🔄 Запрос #7826 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 118 спецификаций. Всего: 736940
🔄 Запрос #7827 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 118 спецификаций. Всего: 737058
🔄 Запрос #7828 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 106 спецификаций. Всего: 737164
🔄 Запрос #7829 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 114 спецификаций. Всего: 737278
🔄 Запрос #7830 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 194 спецификаций. Всего: 737472
🔄 Запрос #7831 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 111 спецификаций. Всего: 737583
🔄 Запрос #7832 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 94 спецификаций. Всего: 737677
🔄 Запрос #7833 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 110 спецификаций. Всего: 737787
🔄 Запрос #7834 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 109 спецификаций. Всего: 737896
🔄 Запрос #7835 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 99 спецификаций. Всего: 737995
🔄 Запрос #7836 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 83 спецификаций. Всего: 738078
🔄 Запрос #7837 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 94 спецификаций. Всего: 738172
🔄 Запрос #7838 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 106 спецификаций. Всего: 738278
🔄 Запрос #7839 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 90 спецификаций. Всего: 738368
🔄 Запрос #7840 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 106 спецификаций. Всего: 738474
🔄 Запрос #7841 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 97 спецификаций. Всего: 738571
🔄 Запрос #7842 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 74 спецификаций. Всего: 738645
🔄 Запрос #7843 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 94 спецификаций. Всего: 738739
🔄 Запрос #7844 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 64 спецификаций. Всего: 738803
🔄 Запрос #7845 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 86 спецификаций. Всего: 738889
🔄 Запрос #7846 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 86 спецификаций. Всего: 738975
🔄 Запрос #7847 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 22 спецификаций. Всего: 738997
🔄 Запрос #7848 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 95 спецификаций. Всего: 739092
🔄 Запрос #7849 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 91 спецификаций. Всего: 739183
🔄 Запрос #7850 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 114 спецификаций. Всего: 739297
🔄 Запрос #7851 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 109 спецификаций. Всего: 739406
🔄 Запрос #7852 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 128 спецификаций. Всего: 739534
🔄 Запрос #7853 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 137 спецификаций. Всего: 739671
🔄 Запрос #7854 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 104 спецификаций. Всего: 739775
🔄 Запрос #7855 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 134 спецификаций. Всего: 739909
🔄 Запрос #7856 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 137 спецификаций. Всего: 740046
🔄 Запрос #7857 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 129 спецификаций. Всего: 740175
🔄 Запрос #7858 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 108 спецификаций. Всего: 740283
🔄 Запрос #7859 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 100 спецификаций. Всего: 740383
🔄 Запрос #7860 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 105 спецификаций. Всего: 740488
🔄 Запрос #7861 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 113 спецификаций. Всего: 740601
🔄 Запрос #7862 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 119 спецификаций. Всего: 740720
🔄 Запрос #7863 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 118 спецификаций. Всего: 740838
🔄 Запрос #7864 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 111 спецификаций. Всего: 740949
🔄 Запрос #7865 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 127 спецификаций. Всего: 741076
🔄 Запрос #7866 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 128 спецификаций. Всего: 741204
🔄 Запрос #7867 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 113 спецификаций. Всего: 741317
🔄 Запрос #7868 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 118 спецификаций. Всего: 741435
🔄 Запрос #7869 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 109 спецификаций. Всего: 741544
🔄 Запрос #7870 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 108 спецификаций. Всего: 741652
🔄 Запрос #7871 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 90 спецификаций. Всего: 741742
🔄 Запрос #7872 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 76 спецификаций. Всего: 741818
🔄 Запрос #7873 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 151 спецификаций. Всего: 741969
🔄 Запрос #7874 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 110 спецификаций. Всего: 742079
🔄 Запрос #7875 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 90 спецификаций. Всего: 742169
🔄 Запрос #7876 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 99 спецификаций. Всего: 742268
🔄 Запрос #7877 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 133 спецификаций. Всего: 742401
🔄 Запрос #7878 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 131 спецификаций. Всего: 742532
🔄 Запрос #7879 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 145 спецификаций. Всего: 742677
🔄 Запрос #7880 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 135 спецификаций. Всего: 742812
🔄 Запрос #7881 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 142 спецификаций. Всего: 742954
🔄 Запрос #7882 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 135 спецификаций. Всего: 743089
🔄 Запрос #7883 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 126 спецификаций. Всего: 743215
🔄 Запрос #7884 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 139 спецификаций. Всего: 743354
🔄 Запрос #7885 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 155 спецификаций. Всего: 743509
🔄 Запрос #7886 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 130 спецификаций. Всего: 743639
🔄 Запрос #7887 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 106 спецификаций. Всего: 743745
🔄 Запрос #7888 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 121 спецификаций. Всего: 743866
🔄 Запрос #7889 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 100 спецификаций. Всего: 743966
🔄 Запрос #7890 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 115 спецификаций. Всего: 744081
📤 Сохранено 10070 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #7891 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 99 спецификаций. Всего: 744180
🔄 Запрос #7892 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 125 спецификаций. Всего: 744305
🔄 Запрос #7893 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 105 спецификаций. Всего: 744410
🔄 Запрос #7894 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 108 спецификаций. Всего: 744518
🔄 Запрос #7895 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 102 спецификаций. Всего: 744620
🔄 Запрос #7896 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 109 спецификаций. Всего: 744729
🔄 Запрос #7897 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 90 спецификаций. Всего: 744819
🔄 Запрос #7898 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 103 спецификаций. Всего: 744922
🔄 Запрос #7899 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 89 спецификаций. Всего: 745011
🔄 Запрос #7900 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 121 спецификаций. Всего: 745132
🔄 Запрос #7901 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 88 спецификаций. Всего: 745220
🔄 Запрос #7902 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 81 спецификаций. Всего: 745301
🔄 Запрос #7903 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 93 спецификаций. Всего: 745394
🔄 Запрос #7904 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 105 спецификаций. Всего: 745499
🔄 Запрос #7905 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 745593
🔄 Запрос #7906 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 124 спецификаций. Всего: 745717
🔄 Запрос #7907 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 128 спецификаций. Всего: 745845
🔄 Запрос #7908 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 120 спецификаций. Всего: 745965
🔄 Запрос #7909 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 95 спецификаций. Всего: 746060
🔄 Запрос #7910 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 130 спецификаций. Всего: 746190
🔄 Запрос #7911 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 101 спецификаций. Всего: 746291
🔄 Запрос #7912 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 66 спецификаций. Всего: 746357
🔄 Запрос #7913 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 55 спецификаций. Всего: 746412
🔄 Запрос #7914 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 85 спецификаций. Всего: 746497
🔄 Запрос #7915 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 156 спецификаций. Всего: 746653
🔄 Запрос #7916 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 115 спецификаций. Всего: 746768
🔄 Запрос #7917 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 126 спецификаций. Всего: 746894
🔄 Запрос #7918 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 111 спецификаций. Всего: 747005
🔄 Запрос #7919 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 90 спецификаций. Всего: 747095
🔄 Запрос #7920 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 144 спецификаций. Всего: 747239
🔄 Запрос #7921 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 70 спецификаций. Всего: 747309
🔄 Запрос #7922 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 133 спецификаций. Всего: 747442
🔄 Запрос #7923 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 128 спецификаций. Всего: 747570
🔄 Запрос #7924 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 140 спецификаций. Всего: 747710
🔄 Запрос #7925 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 110 спецификаций. Всего: 747820
🔄 Запрос #7926 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 106 спецификаций. Всего: 747926
🔄 Запрос #7927 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 91 спецификаций. Всего: 748017

🔄 Запрос #7928 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 92 спецификаций. Всего: 748109
🔄 Запрос #7929 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 93 спецификаций. Всего: 748202
🔄 Запрос #7930 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 97 спецификаций. Всего: 748299
🔄 Запрос #7931 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 98 спецификаций. Всего: 748397
🔄 Запрос #7932 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 70 спецификаций. Всего: 748467
🔄 Запрос #7933 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 101 спецификаций. Всего: 748568
🔄 Запрос #7934 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 100 спецификаций. Всего: 748668
🔄 Запрос #7935 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 94 спецификаций. Всего: 748762
🔄 Запрос #7936 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 90 спецификаций. Всего: 748852
🔄 Запрос #7937 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 83 спецификаций. Всего: 748935
🔄 Запрос #7938 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 110 спецификаций. Всего: 749045
🔄 Запрос #7939 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 128 спецификаций. Всего: 749173
🔄 Запрос #7940 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 123 спецификаций. Всего: 749296
🔄 Запрос #7941 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 105 спецификаций. Всего: 749401
🔄 Запрос #7942 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 91 спецификаций. Всего: 749492
🔄 Запрос #7943 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 106 спецификаций. Всего: 749598
🔄 Запрос #7944 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 109 спецификаций. Всего: 749707
🔄 Запрос #7945 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 110 спецификаций. Всего: 749817
🔄 Запрос #7946 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 109 спецификаций. Всего: 749926
🔄 Запрос #7947 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 122 спецификаций. Всего: 750048
🔄 Запрос #7948 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 100 спецификаций. Всего: 750148
🔄 Запрос #7949 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 95 спецификаций. Всего: 750243
🔄 Запрос #7950 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 115 спецификаций. Всего: 750358
🔄 Запрос #7951 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 107 спецификаций. Всего: 750465
🔄 Запрос #7952 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 100 спецификаций. Всего: 750565
🔄 Запрос #7953 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 105 спецификаций. Всего: 750670
🔄 Запрос #7954 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 74 спецификаций. Всего: 750744
🔄 Запрос #7955 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 124 спецификаций. Всего: 750868
🔄 Запрос #7956 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 116 спецификаций. Всего: 750984
🔄 Запрос #7957 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 146 спецификаций. Всего: 751130
🔄 Запрос #7958 для 2024-09-26 20:44:09 - 2024-10-03 20:44:09
📥 Загружено 125 спецификаций. Всего: 751255
📅 Обрабатываем диапазон 2024-09-19 20:44:09 - 2024-09-26 20:44:09 (попытка 1/5)
🔄 Запрос #7959 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 129 спецификаций. Всего: 751384
🔄 Запрос #7960 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 117 спецификаций. Всего: 751501
🔄 Запрос #7961 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 132 спецификаций. Всего: 751633
🔄 Запрос #7962 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 751729
🔄 Запрос #7963 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 123 спецификаций. Всего: 751852
🔄 Запрос #7964 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 751964
🔄 Запрос #7965 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 111 спецификаций. Всего: 752075
🔄 Запрос #7966 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 752193
🔄 Запрос #7967 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 109 спецификаций. Всего: 752302
🔄 Запрос #7968 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 120 спецификаций. Всего: 752422
🔄 Запрос #7969 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 752538
🔄 Запрос #7970 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 115 спецификаций. Всего: 752653
🔄 Запрос #7971 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 752757
🔄 Запрос #7972 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 752858
🔄 Запрос #7973 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 752964
🔄 Запрос #7974 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 753056
🔄 Запрос #7975 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 753149
🔄 Запрос #7976 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 753248
🔄 Запрос #7977 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 81 спецификаций. Всего: 753329
🔄 Запрос #7978 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 69 спецификаций. Всего: 753398
🔄 Запрос #7979 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 91 спецификаций. Всего: 753489
🔄 Запрос #7980 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 152 спецификаций. Всего: 753641
🔄 Запрос #7981 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 111 спецификаций. Всего: 753752
🔄 Запрос #7982 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 753841
🔄 Запрос #7983 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 753954
🔄 Запрос #7984 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 123 спецификаций. Всего: 754077
🔄 Запрос #7985 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 135 спецификаций. Всего: 754212
📤 Сохранено 10131 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #7986 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 754319
🔄 Запрос #7987 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 122 спецификаций. Всего: 754441
🔄 Запрос #7988 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 120 спецификаций. Всего: 754561
🔄 Запрос #7989 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 114 спецификаций. Всего: 754675
🔄 Запрос #7990 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 102 спецификаций. Всего: 754777
🔄 Запрос #7991 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 754861
🔄 Запрос #7992 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 754960
🔄 Запрос #7993 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 755039
🔄 Запрос #7994 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 131 спецификаций. Всего: 755170
🔄 Запрос #7995 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 755283
🔄 Запрос #7996 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 755387
🔄 Запрос #7997 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 755485
🔄 Запрос #7998 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 115 спецификаций. Всего: 755600
🔄 Запрос #7999 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 165 спецификаций. Всего: 755765
🔄 Запрос #8000 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 167 спецификаций. Всего: 755932
🔄 Запрос #8001 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 171 спецификаций. Всего: 756103
🔄 Запрос #8002 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09

📥 Загружено 117 спецификаций. Всего: 756220
🔄 Запрос #8003 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 134 спецификаций. Всего: 756354
🔄 Запрос #8004 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 137 спецификаций. Всего: 756491
🔄 Запрос #8005 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 125 спецификаций. Всего: 756616
🔄 Запрос #8006 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 122 спецификаций. Всего: 756738
🔄 Запрос #8007 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 756834
🔄 Запрос #8008 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 756938
🔄 Запрос #8009 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 757030
🔄 Запрос #8010 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 757127
🔄 Запрос #8011 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 109 спецификаций. Всего: 757236
🔄 Запрос #8012 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 120 спецификаций. Всего: 757356
🔄 Запрос #8013 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 757459
🔄 Запрос #8014 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 757558
🔄 Запрос #8015 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 757655
🔄 Запрос #8016 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 757745
🔄 Запрос #8017 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 757844
🔄 Запрос #8018 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 757922
🔄 Запрос #8019 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 758015
🔄 Запрос #8020 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 78 спецификаций. Всего: 758093
🔄 Запрос #8021 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 73 спецификаций. Всего: 758166
🔄 Запрос #8022 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 52 спецификаций. Всего: 758218
🔄 Запрос #8023 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 758326
🔄 Запрос #8024 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 124 спецификаций. Всего: 758450
🔄 Запрос #8025 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 758558
🔄 Запрос #8026 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 758661
🔄 Запрос #8027 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 758745
🔄 Запрос #8028 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 82 спецификаций. Всего: 758827
🔄 Запрос #8029 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 758926
🔄 Запрос #8030 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 759034
🔄 Запрос #8031 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 122 спецификаций. Всего: 759156
🔄 Запрос #8032 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 124 спецификаций. Всего: 759280
🔄 Запрос #8033 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 123 спецификаций. Всего: 759403
🔄 Запрос #8034 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 759506
🔄 Запрос #8035 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 123 спецификаций. Всего: 759629
🔄 Запрос #8036 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 759735
🔄 Запрос #8037 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 759842
🔄 Запрос #8038 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 759948
🔄 Запрос #8039 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 760032
🔄 Запрос #8040 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 760137
🔄 Запрос #8041 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 760229
🔄 Запрос #8042 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 70 спецификаций. Всего: 760299
🔄 Запрос #8043 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 760406
🔄 Запрос #8044 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 760485
🔄 Запрос #8045 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 136 спецификаций. Всего: 760621
🔄 Запрос #8046 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 122 спецификаций. Всего: 760743
🔄 Запрос #8047 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 149 спецификаций. Всего: 760892
🔄 Запрос #8048 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 114 спецификаций. Всего: 761006
🔄 Запрос #8049 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 150 спецификаций. Всего: 761156
🔄 Запрос #8050 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 157 спецификаций. Всего: 761313
🔄 Запрос #8051 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 179 спецификаций. Всего: 761492
🔄 Запрос #8052 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 170 спецификаций. Всего: 761662
🔄 Запрос #8053 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 148 спецификаций. Всего: 761810
🔄 Запрос #8054 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 149 спецификаций. Всего: 761959
🔄 Запрос #8055 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 130 спецификаций. Всего: 762089
🔄 Запрос #8056 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 762201
🔄 Запрос #8057 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 762296
🔄 Запрос #8058 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 762408
🔄 Запрос #8059 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 762505
🔄 Запрос #8060 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 762613
🔄 Запрос #8061 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 762726
🔄 Запрос #8062 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 762839
🔄 Запрос #8063 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 762955
🔄 Запрос #8064 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 763061
🔄 Запрос #8065 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 763154
🔄 Запрос #8066 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 763254
🔄 Запрос #8067 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 763360
🔄 Запрос #8068 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 111 спецификаций. Всего: 763471
🔄 Запрос #8069 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 763572
🔄 Запрос #8070 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 763672
🔄 Запрос #8071 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 763788
🔄 Запрос #8072 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 763886
🔄 Запрос #8073 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 114 спецификаций. Всего: 764000
🔄 Запрос #8074 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 764088
🔄 Запрос #8075 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 764181
🔄 Запрос #8076 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 764285
📤 Сохранено 10073 записей в plans_data_spec\plans_combined_spec.parquet

🔄 Запрос #8077 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 764391
🔄 Запрос #8078 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 764496
🔄 Запрос #8079 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 764596
🔄 Запрос #8080 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 764692
🔄 Запрос #8081 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 764791
🔄 Запрос #8082 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 764879
🔄 Запрос #8083 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 764973
🔄 Запрос #8084 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 765081
🔄 Запрос #8085 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 105 спецификаций. Всего: 765186
🔄 Запрос #8086 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 765283
🔄 Запрос #8087 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 765380
🔄 Запрос #8088 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 765487
🔄 Запрос #8089 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 765594
🔄 Запрос #8090 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 765706
🔄 Запрос #8091 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 765809
🔄 Запрос #8092 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 765898
🔄 Запрос #8093 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 65 спецификаций. Всего: 765963
🔄 Запрос #8094 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 766060
🔄 Запрос #8095 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 130 спецификаций. Всего: 766190
🔄 Запрос #8096 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 144 спецификаций. Всего: 766334
🔄 Запрос #8097 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 155 спецификаций. Всего: 766489
🔄 Запрос #8098 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 157 спецификаций. Всего: 766646
🔄 Запрос #8099 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 113 спецификаций. Всего: 766759
🔄 Запрос #8100 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 174 спецификаций. Всего: 766933
🔄 Запрос #8101 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 767041
🔄 Запрос #8102 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 172 спецификаций. Всего: 767213
🔄 Запрос #8103 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 124 спецификаций. Всего: 767337
🔄 Запрос #8104 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 767455
🔄 Запрос #8105 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 767567
🔄 Запрос #8106 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 111 спецификаций. Всего: 767678
🔄 Запрос #8107 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 767774
🔄 Запрос #8108 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 767872
🔄 Запрос #8109 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 767979
🔄 Запрос #8110 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 768086
🔄 Запрос #8111 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 768187
🔄 Запрос #8112 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 768282
🔄 Запрос #8113 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 121 спецификаций. Всего: 768403
🔄 Запрос #8114 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 768515
🔄 Запрос #8115 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 111 спецификаций. Всего: 768626
🔄 Запрос #8116 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 768711
🔄 Запрос #8117 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 111 спецификаций. Всего: 768822
🔄 Запрос #8118 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 95 спецификаций. Всего: 768917
🔄 Запрос #8119 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 769004
🔄 Запрос #8120 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 769094
🔄 Запрос #8121 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 769184
🔄 Запрос #8122 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 769276
🔄 Запрос #8123 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 769368
🔄 Запрос #8124 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 84 спецификаций. Всего: 769452
🔄 Запрос #8125 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 68 спецификаций. Всего: 769520
🔄 Запрос #8126 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 60 спецификаций. Всего: 769580
🔄 Запрос #8127 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 769673
🔄 Запрос #8128 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 769785
🔄 Запрос #8129 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 124 спецификаций. Всего: 769909
🔄 Запрос #8130 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 770006
🔄 Запрос #8131 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 770091
🔄 Запрос #8132 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 770194
🔄 Запрос #8133 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 122 спецификаций. Всего: 770316
🔄 Запрос #8134 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 770416
🔄 Запрос #8135 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 770501
🔄 Запрос #8136 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 117 спецификаций. Всего: 770618
🔄 Запрос #8137 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 101 спецификаций. Всего: 770719
🔄 Запрос #8138 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 770819
🔄 Запрос #8139 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 111 спецификаций. Всего: 770930
🔄 Запрос #8140 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 771042
🔄 Запрос #8141 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 771154
🔄 Запрос #8142 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 771270
🔄 Запрос #8143 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 94 спецификаций. Всего: 771364
🔄 Запрос #8144 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 89 спецификаций. Всего: 771453
🔄 Запрос #8145 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 141 спецификаций. Всего: 771594
🔄 Запрос #8146 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 119 спецификаций. Всего: 771713
🔄 Запрос #8147 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 771820
🔄 Запрос #8148 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 109 спецификаций. Всего: 771929
🔄 Запрос #8149 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 144 спецификаций. Всего: 772073
🔄 Запрос #8150 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 85 спецификаций. Всего: 772158
🔄 Запрос #8151 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 111 спецификаций. Всего: 772269
🔄 Запрос #8152 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 141 спецификаций. Всего: 772410

🔄 Запрос #8153 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 71 спецификаций. Всего: 772481
🔄 Запрос #8154 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 125 спецификаций. Всего: 772606
🔄 Запрос #8155 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 129 спецификаций. Всего: 772735
🔄 Запрос #8156 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 772832
🔄 Запрос #8157 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 772928
🔄 Запрос #8158 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 142 спецификаций. Всего: 773070
🔄 Запрос #8159 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 139 спецификаций. Всего: 773209
🔄 Запрос #8160 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 129 спецификаций. Всего: 773338
🔄 Запрос #8161 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 148 спецификаций. Всего: 773486
🔄 Запрос #8162 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 133 спецификаций. Всего: 773619
🔄 Запрос #8163 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 135 спецификаций. Всего: 773754
🔄 Запрос #8164 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 114 спецификаций. Всего: 773868
🔄 Запрос #8165 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 773993
🔄 Запрос #8166 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 115 спецификаций. Всего: 774108
🔄 Запрос #8167 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 774215
🔄 Запрос #8168 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 109 спецификаций. Всего: 774324
📤 Сохранено 10039 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #8169 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 774436
🔄 Запрос #8170 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 96 спецификаций. Всего: 774532
🔄 Запрос #8171 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 774630
🔄 Запрос #8172 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 99 спецификаций. Всего: 774729
🔄 Запрос #8173 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 116 спецификаций. Всего: 774845
🔄 Запрос #8174 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 107 спецификаций. Всего: 774952
🔄 Запрос #8175 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 775049
🔄 Запрос #8176 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 120 спецификаций. Всего: 775169
🔄 Запрос #8177 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 118 спецификаций. Всего: 775287
🔄 Запрос #8178 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 775393
🔄 Запрос #8179 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 92 спецификаций. Всего: 775485
🔄 Запрос #8180 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 775585
🔄 Запрос #8181 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 97 спецификаций. Всего: 775682
🔄 Запрос #8182 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 119 спецификаций. Всего: 775801
🔄 Запрос #8183 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 110 спецификаций. Всего: 775911
🔄 Запрос #8184 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 87 спецификаций. Всего: 775998
🔄 Запрос #8185 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 88 спецификаций. Всего: 776086
🔄 Запрос #8186 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 117 спецификаций. Всего: 776203
🔄 Запрос #8187 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 776307
🔄 Запрос #8188 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 776397
🔄 Запрос #8189 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 104 спецификаций. Всего: 776501
🔄 Запрос #8190 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 142 спецификаций. Всего: 776643
🔄 Запрос #8191 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 93 спецификаций. Всего: 776736
🔄 Запрос #8192 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 103 спецификаций. Всего: 776839
🔄 Запрос #8193 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 776939
🔄 Запрос #8194 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 777051
🔄 Запрос #8195 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 117 спецификаций. Всего: 777168
🔄 Запрос #8196 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 777274
🔄 Запрос #8197 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 112 спецификаций. Всего: 777386
🔄 Запрос #8198 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 98 спецификаций. Всего: 777484
🔄 Запрос #8199 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 777595
🔄 Запрос #8200 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 79 спецификаций. Всего: 777674
🔄 Запрос #8201 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 90 спецификаций. Всего: 777764
🔄 Запрос #8202 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 106 спецификаций. Всего: 777870
🔄 Запрос #8203 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 117 спецификаций. Всего: 777987
🔄 Запрос #8204 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 108 спецификаций. Всего: 778095
🔄 Запрос #8205 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 132 спецификаций. Всего: 778227
🔄 Запрос #8206 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 100 спецификаций. Всего: 778327
🔄 Запрос #8207 для 2024-09-19 20:44:09 - 2024-09-26 20:44:09
📥 Загружено 37 спецификаций. Всего: 778364
📅 Обрабатываем диапазон 2024-09-12 20:44:09 - 2024-09-19 20:44:09 (попытка 1/5)
🔄 Запрос #8208 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 778475
🔄 Запрос #8209 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 157 спецификаций. Всего: 778632
🔄 Запрос #8210 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 140 спецификаций. Всего: 778772
🔄 Запрос #8211 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 115 спецификаций. Всего: 778887
🔄 Запрос #8212 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 118 спецификаций. Всего: 779005
🔄 Запрос #8213 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 125 спецификаций. Всего: 779130
🔄 Запрос #8214 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 779235
🔄 Запрос #8215 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 88 спецификаций. Всего: 779323
🔄 Запрос #8216 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 779421
🔄 Запрос #8217 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 118 спецификаций. Всего: 779539
🔄 Запрос #8218 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 779641
🔄 Запрос #8219 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 779740
🔄 Запрос #8220 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 779854
🔄 Запрос #8221 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 779945
🔄 Запрос #8222 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 780054
🔄 Запрос #8223 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 128 спецификаций. Всего: 780182
🔄 Запрос #8224 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 780290
🔄 Запрос #8225 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09

📥 Загружено 103 спецификаций. Всего: 780393
🔄 Запрос #8226 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 113 спецификаций. Всего: 780506
🔄 Запрос #8227 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 780616
🔄 Запрос #8228 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 780718
🔄 Запрос #8229 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 780803
🔄 Запрос #8230 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 71 спецификаций. Всего: 780874
🔄 Запрос #8231 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 780975
🔄 Запрос #8232 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 781072
🔄 Запрос #8233 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 781191
🔄 Запрос #8234 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 781318
🔄 Запрос #8235 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 781427
🔄 Запрос #8236 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 121 спецификаций. Всего: 781548
🔄 Запрос #8237 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 112 спецификаций. Всего: 781660
🔄 Запрос #8238 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 781768
🔄 Запрос #8239 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 781882
🔄 Запрос #8240 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 93 спецификаций. Всего: 781975
🔄 Запрос #8241 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 120 спецификаций. Всего: 782095
🔄 Запрос #8242 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 782198
🔄 Запрос #8243 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 92 спецификаций. Всего: 782290
🔄 Запрос #8244 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 782380
🔄 Запрос #8245 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 782491
🔄 Запрос #8246 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 782590
🔄 Запрос #8247 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 782689
🔄 Запрос #8248 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 84 спецификаций. Всего: 782773
🔄 Запрос #8249 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 782875
🔄 Запрос #8250 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 782989
🔄 Запрос #8251 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 125 спецификаций. Всего: 783114
🔄 Запрос #8252 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 89 спецификаций. Всего: 783203
🔄 Запрос #8253 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 70 спецификаций. Всего: 783273
🔄 Запрос #8254 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 67 спецификаций. Всего: 783340
🔄 Запрос #8255 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 783446
🔄 Запрос #8256 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 121 спецификаций. Всего: 783567
🔄 Запрос #8257 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 783683
🔄 Запрос #8258 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 120 спецификаций. Всего: 783803
🔄 Запрос #8259 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 137 спецификаций. Всего: 783940
🔄 Запрос #8260 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 146 спецификаций. Всего: 784086
🔄 Запрос #8261 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 142 спецификаций. Всего: 784228
🔄 Запрос #8262 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 107 спецификаций. Всего: 784335
📤 Сохранено 10011 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #8263 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 784434
🔄 Запрос #8264 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 784533
🔄 Запрос #8265 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 784624
🔄 Запрос #8266 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 784723
🔄 Запрос #8267 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 117 спецификаций. Всего: 784840
🔄 Запрос #8268 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 88 спецификаций. Всего: 784928
🔄 Запрос #8269 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 785034
🔄 Запрос #8270 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 785131
🔄 Запрос #8271 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 81 спецификаций. Всего: 785212
🔄 Запрос #8272 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 785321
🔄 Запрос #8273 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 785431
🔄 Запрос #8274 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 785558
🔄 Запрос #8275 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 785674
🔄 Запрос #8276 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 785777
🔄 Запрос #8277 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 785883
🔄 Запрос #8278 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 89 спецификаций. Всего: 785972
🔄 Запрос #8279 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 115 спецификаций. Всего: 786087
🔄 Запрос #8280 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 786178
🔄 Запрос #8281 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 59 спецификаций. Всего: 786237
🔄 Запрос #8282 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 64 спецификаций. Всего: 786301
🔄 Запрос #8283 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 72 спецификаций. Всего: 786373
🔄 Запрос #8284 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 66 спецификаций. Всего: 786439
🔄 Запрос #8285 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 67 спецификаций. Всего: 786506
🔄 Запрос #8286 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 96 спецификаций. Всего: 786602
🔄 Запрос #8287 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 786699
🔄 Запрос #8288 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 786800
🔄 Запрос #8289 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 786899
🔄 Запрос #8290 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 787018
🔄 Запрос #8291 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 787132
🔄 Запрос #8292 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 787222
🔄 Запрос #8293 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 86 спецификаций. Всего: 787308
🔄 Запрос #8294 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 787403
🔄 Запрос #8295 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 787500
🔄 Запрос #8296 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 787616
🔄 Запрос #8297 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 787713
🔄 Запрос #8298 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 787803
🔄 Запрос #8299 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 787914
🔄 Запрос #8300 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 788004

🔄 Запрос #8301 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 100 спецификаций. Всего: 788104
🔄 Запрос #8302 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 788203
🔄 Запрос #8303 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 86 спецификаций. Всего: 788289
🔄 Запрос #8304 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 83 спецификаций. Всего: 788372
🔄 Запрос #8305 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 788481
🔄 Запрос #8306 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 788586
🔄 Запрос #8307 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 788685
🔄 Запрос #8308 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 788786
🔄 Запрос #8309 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 126 спецификаций. Всего: 788912
🔄 Запрос #8310 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 78 спецификаций. Всего: 788990
🔄 Запрос #8311 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 66 спецификаций. Всего: 789056
🔄 Запрос #8312 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 80 спецификаций. Всего: 789136
🔄 Запрос #8313 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 789246
🔄 Запрос #8314 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 112 спецификаций. Всего: 789358
🔄 Запрос #8315 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 134 спецификаций. Всего: 789492
🔄 Запрос #8316 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 151 спецификаций. Всего: 789643
🔄 Запрос #8317 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 143 спецификаций. Всего: 789786
🔄 Запрос #8318 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 126 спецификаций. Всего: 789912
🔄 Запрос #8319 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 122 спецификаций. Всего: 790034
🔄 Запрос #8320 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 130 спецификаций. Всего: 790164
🔄 Запрос #8321 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 123 спецификаций. Всего: 790287
🔄 Запрос #8322 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 138 спецификаций. Всего: 790425
🔄 Запрос #8323 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 790539
🔄 Запрос #8324 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 790648
🔄 Запрос #8325 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 790751
🔄 Запрос #8326 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 790854
🔄 Запрос #8327 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 105 спецификаций. Всего: 790959
🔄 Запрос #8328 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 791069
🔄 Запрос #8329 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 791177
🔄 Запрос #8330 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 104 спецификаций. Всего: 791281
🔄 Запрос #8331 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 125 спецификаций. Всего: 791406
🔄 Запрос #8332 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 128 спецификаций. Всего: 791534
🔄 Запрос #8333 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 115 спецификаций. Всего: 791649
🔄 Запрос #8334 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 791757
🔄 Запрос #8335 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 791863
🔄 Запрос #8336 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 113 спецификаций. Всего: 791976
🔄 Запрос #8337 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 96 спецификаций. Всего: 792072
🔄 Запрос #8338 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 136 спецификаций. Всего: 792208
🔄 Запрос #8339 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 130 спецификаций. Всего: 792338
🔄 Запрос #8340 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 77 спецификаций. Всего: 792415
🔄 Запрос #8341 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 82 спецификаций. Всего: 792497
🔄 Запрос #8342 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 82 спецификаций. Всего: 792579
🔄 Запрос #8343 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 147 спецификаций. Всего: 792726
🔄 Запрос #8344 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 177 спецификаций. Всего: 792903
🔄 Запрос #8345 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 136 спецификаций. Всего: 793039
🔄 Запрос #8346 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 793166
🔄 Запрос #8347 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 793285
🔄 Запрос #8348 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 793380
🔄 Запрос #8349 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 1 спецификаций. Всего: 793381
🔄 Запрос #8350 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 2 спецификаций. Всего: 793383
🔄 Запрос #8351 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 1 спецификаций. Всего: 793384
🔄 Запрос #8352 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 62 спецификаций. Всего: 793446
🔄 Запрос #8353 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 793573
🔄 Запрос #8354 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 793700
🔄 Запрос #8355 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 129 спецификаций. Всего: 793829
🔄 Запрос #8356 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 793940
🔄 Запрос #8357 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 794046
🔄 Запрос #8358 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 125 спецификаций. Всего: 794171
🔄 Запрос #8359 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 133 спецификаций. Всего: 794304
🔄 Запрос #8360 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 794413
📤 Сохранено 10078 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #8361 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 130 спецификаций. Всего: 794543
🔄 Запрос #8362 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 794670
🔄 Запрос #8363 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 794778
🔄 Запрос #8364 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 61 спецификаций. Всего: 794839
🔄 Запрос #8365 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 794942
🔄 Запрос #8366 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 120 спецификаций. Всего: 795062
🔄 Запрос #8367 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 122 спецификаций. Всего: 795184
🔄 Запрос #8368 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 795303
🔄 Запрос #8369 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 795411
🔄 Запрос #8370 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 795530
🔄 Запрос #8371 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 795621
🔄 Запрос #8372 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 795718
🔄 Запрос #8373 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 132 спецификаций. Всего: 795850
🔄 Запрос #8374 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 140 спецификаций. Всего: 795990
🔄 Запрос #8375 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 796104

🔄 Запрос #8376 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 796220
🔄 Запрос #8377 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 149 спецификаций. Всего: 796369
🔄 Запрос #8378 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 161 спецификаций. Всего: 796530
🔄 Запрос #8379 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 127 спецификаций. Всего: 796657
🔄 Запрос #8380 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 796765
🔄 Запрос #8381 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 79 спецификаций. Всего: 796844
🔄 Запрос #8382 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 796954
🔄 Запрос #8383 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 797065
🔄 Запрос #8384 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 115 спецификаций. Всего: 797180
🔄 Запрос #8385 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 94 спецификаций. Всего: 797274
🔄 Запрос #8386 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 797385
🔄 Запрос #8387 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 797488
🔄 Запрос #8388 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 118 спецификаций. Всего: 797606
🔄 Запрос #8389 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 135 спецификаций. Всего: 797741
🔄 Запрос #8390 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 137 спецификаций. Всего: 797878
🔄 Запрос #8391 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 797979
🔄 Запрос #8392 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 798089
🔄 Запрос #8393 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 798192
🔄 Запрос #8394 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 117 спецификаций. Всего: 798309
🔄 Запрос #8395 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 100 спецификаций. Всего: 798409
🔄 Запрос #8396 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 104 спецификаций. Всего: 798513
🔄 Запрос #8397 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 112 спецификаций. Всего: 798625
🔄 Запрос #8398 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 88 спецификаций. Всего: 798713
🔄 Запрос #8399 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 81 спецификаций. Всего: 798794
🔄 Запрос #8400 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 66 спецификаций. Всего: 798860
🔄 Запрос #8401 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 63 спецификаций. Всего: 798923
🔄 Запрос #8402 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 112 спецификаций. Всего: 799035
🔄 Запрос #8403 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 799138
🔄 Запрос #8404 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 100 спецификаций. Всего: 799238
🔄 Запрос #8405 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 90 спецификаций. Всего: 799328
🔄 Запрос #8406 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 799426
🔄 Запрос #8407 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 799537
🔄 Запрос #8408 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 120 спецификаций. Всего: 799657
🔄 Запрос #8409 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 799771
🔄 Запрос #8410 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 124 спецификаций. Всего: 799895
🔄 Запрос #8411 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 119 спецификаций. Всего: 800014
🔄 Запрос #8412 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 800124
🔄 Запрос #8413 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 117 спецификаций. Всего: 800241
🔄 Запрос #8414 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 96 спецификаций. Всего: 800337
🔄 Запрос #8415 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 800447
🔄 Запрос #8416 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 800558
🔄 Запрос #8417 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 800669
🔄 Запрос #8418 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 99 спецификаций. Всего: 800768
🔄 Запрос #8419 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 153 спецификаций. Всего: 800921
🔄 Запрос #8420 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 94 спецификаций. Всего: 801015
🔄 Запрос #8421 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 112 спецификаций. Всего: 801127
🔄 Запрос #8422 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 801230
🔄 Запрос #8423 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 141 спецификаций. Всего: 801371
🔄 Запрос #8424 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 104 спецификаций. Всего: 801475
🔄 Запрос #8425 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 144 спецификаций. Всего: 801619
🔄 Запрос #8426 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 801717
🔄 Запрос #8427 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 133 спецификаций. Всего: 801850
🔄 Запрос #8428 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 18 спецификаций. Всего: 801868
🔄 Запрос #8429 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 126 спецификаций. Всего: 801994
🔄 Запрос #8430 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 103 спецификаций. Всего: 802097
🔄 Запрос #8431 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 802194
🔄 Запрос #8432 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 139 спецификаций. Всего: 802333
🔄 Запрос #8433 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 139 спецификаций. Всего: 802472
🔄 Запрос #8434 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 150 спецификаций. Всего: 802622
🔄 Запрос #8435 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 2 спецификаций. Всего: 802624
🔄 Запрос #8436 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 28 спецификаций. Всего: 802652
🔄 Запрос #8437 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 144 спецификаций. Всего: 802796
🔄 Запрос #8438 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 138 спецификаций. Всего: 802934
🔄 Запрос #8439 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 803028
🔄 Запрос #8440 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 803144
🔄 Запрос #8441 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 125 спецификаций. Всего: 803269
🔄 Запрос #8442 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 112 спецификаций. Всего: 803381
🔄 Запрос #8443 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 85 спецификаций. Всего: 803466
🔄 Запрос #8444 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 93 спецификаций. Всего: 803559
🔄 Запрос #8445 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 113 спецификаций. Всего: 803672
🔄 Запрос #8446 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 170 спецификаций. Всего: 803842
🔄 Запрос #8447 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 123 спецификаций. Всего: 803965
🔄 Запрос #8448 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 128 спецификаций. Всего: 804093
🔄 Запрос #8449 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 804184
🔄 Запрос #8450 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 77 спецификаций. Всего: 804261
🔄 Запрос #8451 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 101 спецификаций. Всего: 804362

🔄 Запрос #8452 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 804453
📤 Сохранено 10040 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #8453 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 110 спецификаций. Всего: 804563
🔄 Запрос #8454 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 804669
🔄 Запрос #8455 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 804785
🔄 Запрос #8456 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 89 спецификаций. Всего: 804874
🔄 Запрос #8457 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 48 спецификаций. Всего: 804922
🔄 Запрос #8458 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 62 спецификаций. Всего: 804984
🔄 Запрос #8459 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 97 спецификаций. Всего: 805081
🔄 Запрос #8460 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 805179
🔄 Запрос #8461 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 109 спецификаций. Всего: 805288
🔄 Запрос #8462 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 122 спецификаций. Всего: 805410
🔄 Запрос #8463 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 805508
🔄 Запрос #8464 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 805624
🔄 Запрос #8465 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 112 спецификаций. Всего: 805736
🔄 Запрос #8466 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 115 спецификаций. Всего: 805851
🔄 Запрос #8467 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 137 спецификаций. Всего: 805988
🔄 Запрос #8468 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 112 спецификаций. Всего: 806100
🔄 Запрос #8469 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 91 спецификаций. Всего: 806191
🔄 Запрос #8470 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 95 спецификаций. Всего: 806286
🔄 Запрос #8471 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 98 спецификаций. Всего: 806384
🔄 Запрос #8472 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 102 спецификаций. Всего: 806486
🔄 Запрос #8473 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 806597
🔄 Запрос #8474 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 122 спецификаций. Всего: 806719
🔄 Запрос #8475 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 114 спецификаций. Всего: 806833
🔄 Запрос #8476 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 83 спецификаций. Всего: 806916
🔄 Запрос #8477 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 807027
🔄 Запрос #8478 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 108 спецификаций. Всего: 807135
🔄 Запрос #8479 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 106 спецификаций. Всего: 807241
🔄 Запрос #8480 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 75 спецификаций. Всего: 807316
🔄 Запрос #8481 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 71 спецификаций. Всего: 807387
🔄 Запрос #8482 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 111 спецификаций. Всего: 807498
🔄 Запрос #8483 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 116 спецификаций. Всего: 807614
🔄 Запрос #8484 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 121 спецификаций. Всего: 807735
🔄 Запрос #8485 для 2024-09-12 20:44:09 - 2024-09-19 20:44:09
📥 Загружено 71 спецификаций. Всего: 807806
📅 Обрабатываем диапазон 2024-09-05 20:44:09 - 2024-09-12 20:44:09 (попытка 1/5)
🔄 Запрос #8486 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 121 спецификаций. Всего: 807927
🔄 Запрос #8487 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 213 спецификаций. Всего: 808140
🔄 Запрос #8488 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 156 спецификаций. Всего: 808296
🔄 Запрос #8489 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 120 спецификаций. Всего: 808416
🔄 Запрос #8490 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 808527
🔄 Запрос #8491 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 127 спецификаций. Всего: 808654
🔄 Запрос #8492 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 129 спецификаций. Всего: 808783
🔄 Запрос #8493 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 118 спецификаций. Всего: 808901
🔄 Запрос #8494 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 118 спецификаций. Всего: 809019
🔄 Запрос #8495 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 132 спецификаций. Всего: 809151
🔄 Запрос #8496 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 809274
🔄 Запрос #8497 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 809400
🔄 Запрос #8498 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 95 спецификаций. Всего: 809495
🔄 Запрос #8499 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 809605
🔄 Запрос #8500 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 809716
🔄 Запрос #8501 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 809824
🔄 Запрос #8502 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 809934
🔄 Запрос #8503 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 92 спецификаций. Всего: 810026
🔄 Запрос #8504 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 810128
🔄 Запрос #8505 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 810222
🔄 Запрос #8506 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 117 спецификаций. Всего: 810339
🔄 Запрос #8507 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 99 спецификаций. Всего: 810438
🔄 Запрос #8508 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 810548
🔄 Запрос #8509 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 99 спецификаций. Всего: 810647
🔄 Запрос #8510 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 810740
🔄 Запрос #8511 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 155 спецификаций. Всего: 810895
🔄 Запрос #8512 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 148 спецификаций. Всего: 811043
🔄 Запрос #8513 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 811149
🔄 Запрос #8514 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 811251
🔄 Запрос #8515 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 811362
🔄 Запрос #8516 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 811456
🔄 Запрос #8517 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 811543
🔄 Запрос #8518 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 811650
🔄 Запрос #8519 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 811751
🔄 Запрос #8520 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 811844
🔄 Запрос #8521 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 811942
🔄 Запрос #8522 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 812048
🔄 Запрос #8523 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 117 спецификаций. Всего: 812165
🔄 Запрос #8524 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 812272
🔄 Запрос #8525 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09

📥 Загружено 107 спецификаций. Всего: 812379
🔄 Запрос #8526 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 104 спецификаций. Всего: 812483
🔄 Запрос #8527 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 812593
🔄 Запрос #8528 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 812705
🔄 Запрос #8529 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 812814
🔄 Запрос #8530 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 812923
🔄 Запрос #8531 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 100 спецификаций. Всего: 813023
🔄 Запрос #8532 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 813142
🔄 Запрос #8533 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 813266
🔄 Запрос #8534 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 813381
🔄 Запрос #8535 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 97 спецификаций. Всего: 813478
🔄 Запрос #8536 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 77 спецификаций. Всего: 813555
🔄 Запрос #8537 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 55 спецификаций. Всего: 813610
🔄 Запрос #8538 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 69 спецификаций. Всего: 813679
🔄 Запрос #8539 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 813792
🔄 Запрос #8540 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 813902
🔄 Запрос #8541 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 121 спецификаций. Всего: 814023
🔄 Запрос #8542 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 814124
🔄 Запрос #8543 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 142 спецификаций. Всего: 814266
🔄 Запрос #8544 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 135 спецификаций. Всего: 814401
🔄 Запрос #8545 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 132 спецификаций. Всего: 814533
📤 Сохранено 10080 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #8546 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 120 спецификаций. Всего: 814653
🔄 Запрос #8547 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 129 спецификаций. Всего: 814782
🔄 Запрос #8548 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 125 спецификаций. Всего: 814907
🔄 Запрос #8549 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 815018
🔄 Запрос #8550 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 121 спецификаций. Всего: 815139
🔄 Запрос #8551 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 117 спецификаций. Всего: 815256
🔄 Запрос #8552 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 815375
🔄 Запрос #8553 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 815501
🔄 Запрос #8554 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 129 спецификаций. Всего: 815630
🔄 Запрос #8555 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 815744
🔄 Запрос #8556 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 138 спецификаций. Всего: 815882
🔄 Запрос #8557 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 118 спецификаций. Всего: 816000
🔄 Запрос #8558 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 816106
🔄 Запрос #8559 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 816212
🔄 Запрос #8560 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 816323
🔄 Запрос #8561 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 816435
🔄 Запрос #8562 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 49 спецификаций. Всего: 816484
🔄 Запрос #8563 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 120 спецификаций. Всего: 816604
🔄 Запрос #8564 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 816723
🔄 Запрос #8565 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 133 спецификаций. Всего: 816856
🔄 Запрос #8566 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 816980
🔄 Запрос #8567 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 121 спецификаций. Всего: 817101
🔄 Запрос #8568 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 817214
🔄 Запрос #8569 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 817320
🔄 Запрос #8570 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 87 спецификаций. Всего: 817407
🔄 Запрос #8571 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 817508
🔄 Запрос #8572 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 817609
🔄 Запрос #8573 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 817697
🔄 Запрос #8574 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 817802
🔄 Запрос #8575 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 817926
🔄 Запрос #8576 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 818042
🔄 Запрос #8577 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 818158
🔄 Запрос #8578 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 818264
🔄 Запрос #8579 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 818388
🔄 Запрос #8580 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 120 спецификаций. Всего: 818508
🔄 Запрос #8581 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 818622
🔄 Запрос #8582 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 128 спецификаций. Всего: 818750
🔄 Запрос #8583 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 188 спецификаций. Всего: 818938
🔄 Запрос #8584 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 118 спецификаций. Всего: 819056
🔄 Запрос #8585 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 122 спецификаций. Всего: 819178
🔄 Запрос #8586 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 819304
🔄 Запрос #8587 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 120 спецификаций. Всего: 819424
🔄 Запрос #8588 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 128 спецификаций. Всего: 819552
🔄 Запрос #8589 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 131 спецификаций. Всего: 819683
🔄 Запрос #8590 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 819809
🔄 Запрос #8591 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 819935
🔄 Запрос #8592 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 120 спецификаций. Всего: 820055
🔄 Запрос #8593 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 820156
🔄 Запрос #8594 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 820258
🔄 Запрос #8595 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 820349
🔄 Запрос #8596 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 99 спецификаций. Всего: 820448
🔄 Запрос #8597 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 77 спецификаций. Всего: 820525
🔄 Запрос #8598 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 54 спецификаций. Всего: 820579
🔄 Запрос #8599 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 820703

🔄 Запрос #8600 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 38 спецификаций. Всего: 820741
🔄 Запрос #8601 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 65 спецификаций. Всего: 820806
🔄 Запрос #8602 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 820925
🔄 Запрос #8603 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 146 спецификаций. Всего: 821071
🔄 Запрос #8604 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 80 спецификаций. Всего: 821151
🔄 Запрос #8605 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 128 спецификаций. Всего: 821279
🔄 Запрос #8606 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 133 спецификаций. Всего: 821412
🔄 Запрос #8607 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 135 спецификаций. Всего: 821547
🔄 Запрос #8608 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 151 спецификаций. Всего: 821698
🔄 Запрос #8609 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 125 спецификаций. Всего: 821823
🔄 Запрос #8610 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 125 спецификаций. Всего: 821948
🔄 Запрос #8611 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 131 спецификаций. Всего: 822079
🔄 Запрос #8612 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 822205
🔄 Запрос #8613 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 822328
🔄 Запрос #8614 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 822447
🔄 Запрос #8615 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 822563
🔄 Запрос #8616 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 822674
🔄 Запрос #8617 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 822782
🔄 Запрос #8618 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 92 спецификаций. Всего: 822874
🔄 Запрос #8619 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 822968
🔄 Запрос #8620 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 823075
🔄 Запрос #8621 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 823185
🔄 Запрос #8622 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 823311
🔄 Запрос #8623 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 823421
🔄 Запрос #8624 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 823531
🔄 Запрос #8625 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 823637
🔄 Запрос #8626 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 823743
🔄 Запрос #8627 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 823859
🔄 Запрос #8628 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 823985
🔄 Запрос #8629 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 824094
🔄 Запрос #8630 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 824197
🔄 Запрос #8631 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 824290
🔄 Запрос #8632 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 824401
🔄 Запрос #8633 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 71 спецификаций. Всего: 824472
🔄 Запрос #8634 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 89 спецификаций. Всего: 824561
📤 Сохранено 10028 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #8635 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 76 спецификаций. Всего: 824637
🔄 Запрос #8636 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 824728
🔄 Запрос #8637 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 76 спецификаций. Всего: 824804
🔄 Запрос #8638 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 824895
🔄 Запрос #8639 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 825005
🔄 Запрос #8640 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 825120
🔄 Запрос #8641 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 825233
🔄 Запрос #8642 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 825338
🔄 Запрос #8643 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 122 спецификаций. Всего: 825460
🔄 Запрос #8644 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 825586
🔄 Запрос #8645 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 130 спецификаций. Всего: 825716
🔄 Запрос #8646 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 121 спецификаций. Всего: 825837
🔄 Запрос #8647 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 825928
🔄 Запрос #8648 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 96 спецификаций. Всего: 826024
🔄 Запрос #8649 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 826126
🔄 Запрос #8650 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 104 спецификаций. Всего: 826230
🔄 Запрос #8651 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 826342
🔄 Запрос #8652 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 130 спецификаций. Всего: 826472
🔄 Запрос #8653 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 826580
🔄 Запрос #8654 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 826682
🔄 Запрос #8655 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 826794
🔄 Запрос #8656 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 826904
🔄 Запрос #8657 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 827030
🔄 Запрос #8658 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 827142
🔄 Запрос #8659 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 130 спецификаций. Всего: 827272
🔄 Запрос #8660 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 142 спецификаций. Всего: 827414
🔄 Запрос #8661 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 127 спецификаций. Всего: 827541
🔄 Запрос #8662 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 827655
🔄 Запрос #8663 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 69 спецификаций. Всего: 827724
🔄 Запрос #8664 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 827835
🔄 Запрос #8665 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 827943
🔄 Запрос #8666 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 828058
🔄 Запрос #8667 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 92 спецификаций. Всего: 828150
🔄 Запрос #8668 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 828251
🔄 Запрос #8669 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 76 спецификаций. Всего: 828327
🔄 Запрос #8670 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 828440
🔄 Запрос #8671 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 828558
🔄 Запрос #8672 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 137 спецификаций. Всего: 828695
🔄 Запрос #8673 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09

📥 Загружено 127 спецификаций. Всего: 828822
🔄 Запрос #8674 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 132 спецификаций. Всего: 828954
🔄 Запрос #8675 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 129 спецификаций. Всего: 829083
🔄 Запрос #8676 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 128 спецификаций. Всего: 829211
🔄 Запрос #8677 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 829320
🔄 Запрос #8678 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 829422
🔄 Запрос #8679 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 829532
🔄 Запрос #8680 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 829644
🔄 Запрос #8681 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 129 спецификаций. Всего: 829773
🔄 Запрос #8682 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 829892
🔄 Запрос #8683 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 118 спецификаций. Всего: 830010
🔄 Запрос #8684 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 830124
🔄 Запрос #8685 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 129 спецификаций. Всего: 830253
🔄 Запрос #8686 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 125 спецификаций. Всего: 830378
🔄 Запрос #8687 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 139 спецификаций. Всего: 830517
🔄 Запрос #8688 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 830636
🔄 Запрос #8689 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 139 спецификаций. Всего: 830775
🔄 Запрос #8690 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 122 спецификаций. Всего: 830897
🔄 Запрос #8691 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 831002
🔄 Запрос #8692 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 831107
🔄 Запрос #8693 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 831223
🔄 Запрос #8694 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 831329
🔄 Запрос #8695 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 831439
🔄 Запрос #8696 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 71 спецификаций. Всего: 831510
🔄 Запрос #8697 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 99 спецификаций. Всего: 831609
🔄 Запрос #8698 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 831716
🔄 Запрос #8699 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 81 спецификаций. Всего: 831797
🔄 Запрос #8700 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 831908
🔄 Запрос #8701 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 97 спецификаций. Всего: 832005
🔄 Запрос #8702 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 85 спецификаций. Всего: 832090
🔄 Запрос #8703 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 832184
🔄 Запрос #8704 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 101 спецификаций. Всего: 832285
🔄 Запрос #8705 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 832393
🔄 Запрос #8706 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 832491
🔄 Запрос #8707 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 832589
🔄 Запрос #8708 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 832696
🔄 Запрос #8709 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 832811
🔄 Запрос #8710 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 832927
🔄 Запрос #8711 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 833042
🔄 Запрос #8712 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 833148
🔄 Запрос #8713 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 833253
🔄 Запрос #8714 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 833355
🔄 Запрос #8715 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 833460
🔄 Запрос #8716 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 98 спецификаций. Всего: 833558
🔄 Запрос #8717 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 102 спецификаций. Всего: 833660
🔄 Запрос #8718 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 94 спецификаций. Всего: 833754
🔄 Запрос #8719 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 121 спецификаций. Всего: 833875
🔄 Запрос #8720 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 833990
🔄 Запрос #8721 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 834098
🔄 Запрос #8722 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 834212
🔄 Запрос #8723 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 86 спецификаций. Всего: 834298
🔄 Запрос #8724 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 78 спецификаций. Всего: 834376
🔄 Запрос #8725 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 69 спецификаций. Всего: 834445
🔄 Запрос #8726 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 105 спецификаций. Всего: 834550
🔄 Запрос #8727 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 834658
📤 Сохранено 10097 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #8728 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 834772
🔄 Запрос #8729 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 40 спецификаций. Всего: 834812
🔄 Запрос #8730 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 100 спецификаций. Всего: 834912
🔄 Запрос #8731 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 72 спецификаций. Всего: 834984
🔄 Запрос #8732 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 161 спецификаций. Всего: 835145
🔄 Запрос #8733 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 835268
🔄 Запрос #8734 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 835383
🔄 Запрос #8735 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 179 спецификаций. Всего: 835562
🔄 Запрос #8736 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 835677
🔄 Запрос #8737 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 835783
🔄 Запрос #8738 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 136 спецификаций. Всего: 835919
🔄 Запрос #8739 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 125 спецификаций. Всего: 836044
🔄 Запрос #8740 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 135 спецификаций. Всего: 836179
🔄 Запрос #8741 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 836270
🔄 Запрос #8742 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 137 спецификаций. Всего: 836407
🔄 Запрос #8743 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 133 спецификаций. Всего: 836540
🔄 Запрос #8744 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 111 спецификаций. Всего: 836651
🔄 Запрос #8745 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 836775
🔄 Запрос #8746 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 836881
🔄 Запрос #8747 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 126 спецификаций. Всего: 837007
🔄 Запрос #8748 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 123 спецификаций. Всего: 837130

🔄 Запрос #8749 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 837239
🔄 Запрос #8750 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 95 спецификаций. Всего: 837334
🔄 Запрос #8751 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 837427
🔄 Запрос #8752 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 837535
🔄 Запрос #8753 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 88 спецификаций. Всего: 837623
🔄 Запрос #8754 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 108 спецификаций. Всего: 837731
🔄 Запрос #8755 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 837829
🔄 Запрос #8756 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 837920
🔄 Запрос #8757 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 97 спецификаций. Всего: 838017
🔄 Запрос #8758 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 112 спецификаций. Всего: 838129
🔄 Запрос #8759 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 103 спецификаций. Всего: 838232
🔄 Запрос #8760 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 838338
🔄 Запрос #8761 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 106 спецификаций. Всего: 838444
🔄 Запрос #8762 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 838568
🔄 Запрос #8763 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 838687
🔄 Запрос #8764 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 67 спецификаций. Всего: 838754
🔄 Запрос #8765 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 91 спецификаций. Всего: 838845
🔄 Запрос #8766 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 838961
🔄 Запрос #8767 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 839080
🔄 Запрос #8768 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 127 спецификаций. Всего: 839207
🔄 Запрос #8769 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 104 спецификаций. Всего: 839311
🔄 Запрос #8770 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 113 спецификаций. Всего: 839424
🔄 Запрос #8771 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 839550
🔄 Запрос #8772 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 839664
🔄 Запрос #8773 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 128 спецификаций. Всего: 839792
🔄 Запрос #8774 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 93 спецификаций. Всего: 839885
🔄 Запрос #8775 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 78 спецификаций. Всего: 839963
🔄 Запрос #8776 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 840079
🔄 Запрос #8777 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 107 спецификаций. Всего: 840186
🔄 Запрос #8778 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 840300
🔄 Запрос #8779 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 116 спецификаций. Всего: 840416
🔄 Запрос #8780 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 117 спецификаций. Всего: 840533
🔄 Запрос #8781 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 114 спецификаций. Всего: 840647
🔄 Запрос #8782 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 115 спецификаций. Всего: 840762
🔄 Запрос #8783 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 840886
🔄 Запрос #8784 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 109 спецификаций. Всего: 840995
🔄 Запрос #8785 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 841119
🔄 Запрос #8786 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 128 спецификаций. Всего: 841247
🔄 Запрос #8787 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 119 спецификаций. Всего: 841366
🔄 Запрос #8788 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 124 спецификаций. Всего: 841490
🔄 Запрос #8789 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 110 спецификаций. Всего: 841600
🔄 Запрос #8790 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 84 спецификаций. Всего: 841684
🔄 Запрос #8791 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 89 спецификаций. Всего: 841773
🔄 Запрос #8792 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 42 спецификаций. Всего: 841815
🔄 Запрос #8793 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 73 спецификаций. Всего: 841888
🔄 Запрос #8794 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 86 спецификаций. Всего: 841974
🔄 Запрос #8795 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 122 спецификаций. Всего: 842096
🔄 Запрос #8796 для 2024-09-05 20:44:09 - 2024-09-12 20:44:09
📥 Загружено 71 спецификаций. Всего: 842167
📅 Обрабатываем диапазон 2024-08-29 20:44:09 - 2024-09-05 20:44:09 (попытка 1/5)
🔄 Запрос #8797 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 81 спецификаций. Всего: 842248
🔄 Запрос #8798 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 97 спецификаций. Всего: 842345
🔄 Запрос #8799 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 115 спецификаций. Всего: 842460
🔄 Запрос #8800 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 150 спецификаций. Всего: 842610
🔄 Запрос #8801 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 122 спецификаций. Всего: 842732
🔄 Запрос #8802 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 132 спецификаций. Всего: 842864
🔄 Запрос #8803 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 120 спецификаций. Всего: 842984
🔄 Запрос #8804 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 119 спецификаций. Всего: 843103
🔄 Запрос #8805 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 843220
🔄 Запрос #8806 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 105 спецификаций. Всего: 843325
🔄 Запрос #8807 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 125 спецификаций. Всего: 843450
🔄 Запрос #8808 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 116 спецификаций. Всего: 843566
🔄 Запрос #8809 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 843670
🔄 Запрос #8810 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 843765
🔄 Запрос #8811 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 843864
🔄 Запрос #8812 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 843970
🔄 Запрос #8813 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 96 спецификаций. Всего: 844066
🔄 Запрос #8814 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 122 спецификаций. Всего: 844188
🔄 Запрос #8815 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 844306
🔄 Запрос #8816 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 116 спецификаций. Всего: 844422
🔄 Запрос #8817 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 129 спецификаций. Всего: 844551
🔄 Запрос #8818 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 134 спецификаций. Всего: 844685
📤 Сохранено 10027 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #8819 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 112 спецификаций. Всего: 844797
🔄 Запрос #8820 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 844903
🔄 Запрос #8821 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09

📥 Загружено 111 спецификаций. Всего: 845014
🔄 Запрос #8822 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 845116
🔄 Запрос #8823 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 105 спецификаций. Всего: 845221
🔄 Запрос #8824 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 93 спецификаций. Всего: 845314
🔄 Запрос #8825 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 68 спецификаций. Всего: 845382
🔄 Запрос #8826 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 75 спецификаций. Всего: 845457
🔄 Запрос #8827 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 85 спецификаций. Всего: 845542
🔄 Запрос #8828 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 845649
🔄 Запрос #8829 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 137 спецификаций. Всего: 845786
🔄 Запрос #8830 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 147 спецификаций. Всего: 845933
🔄 Запрос #8831 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 141 спецификаций. Всего: 846074
🔄 Запрос #8832 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 133 спецификаций. Всего: 846207
🔄 Запрос #8833 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 69 спецификаций. Всего: 846276
🔄 Запрос #8834 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 93 спецификаций. Всего: 846369
🔄 Запрос #8835 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 846478
🔄 Запрос #8836 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 846591
🔄 Запрос #8837 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 131 спецификаций. Всего: 846722
🔄 Запрос #8838 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 127 спецификаций. Всего: 846849
🔄 Запрос #8839 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 124 спецификаций. Всего: 846973
🔄 Запрос #8840 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 847082
🔄 Запрос #8841 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 847200
🔄 Запрос #8842 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 847318
🔄 Запрос #8843 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 131 спецификаций. Всего: 847449
🔄 Запрос #8844 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 129 спецификаций. Всего: 847578
🔄 Запрос #8845 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 121 спецификаций. Всего: 847699
🔄 Запрос #8846 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 116 спецификаций. Всего: 847815
🔄 Запрос #8847 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 129 спецификаций. Всего: 847944
🔄 Запрос #8848 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 121 спецификаций. Всего: 848065
🔄 Запрос #8849 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 848171
🔄 Запрос #8850 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 111 спецификаций. Всего: 848282
🔄 Запрос #8851 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 848399
🔄 Запрос #8852 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 848498
🔄 Запрос #8853 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 848597
🔄 Запрос #8854 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 131 спецификаций. Всего: 848728
🔄 Запрос #8855 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 848835
🔄 Запрос #8856 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 848949
🔄 Запрос #8857 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 131 спецификаций. Всего: 849080
🔄 Запрос #8858 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 849184
🔄 Запрос #8859 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 136 спецификаций. Всего: 849320
🔄 Запрос #8860 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 140 спецификаций. Всего: 849460
🔄 Запрос #8861 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 146 спецификаций. Всего: 849606
🔄 Запрос #8862 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 849719
🔄 Запрос #8863 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 137 спецификаций. Всего: 849856
🔄 Запрос #8864 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 132 спецификаций. Всего: 849988
🔄 Запрос #8865 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 123 спецификаций. Всего: 850111
🔄 Запрос #8866 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 143 спецификаций. Всего: 850254
🔄 Запрос #8867 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 160 спецификаций. Всего: 850414
🔄 Запрос #8868 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 170 спецификаций. Всего: 850584
🔄 Запрос #8869 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 850709
🔄 Запрос #8870 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 110 спецификаций. Всего: 850819
🔄 Запрос #8871 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 92 спецификаций. Всего: 850911
🔄 Запрос #8872 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 108 спецификаций. Всего: 851019
🔄 Запрос #8873 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 112 спецификаций. Всего: 851131
🔄 Запрос #8874 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 125 спецификаций. Всего: 851256
🔄 Запрос #8875 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 851363
🔄 Запрос #8876 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 851466
🔄 Запрос #8877 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 851569
🔄 Запрос #8878 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 120 спецификаций. Всего: 851689
🔄 Запрос #8879 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 851796
🔄 Запрос #8880 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 100 спецификаций. Всего: 851896
🔄 Запрос #8881 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 108 спецификаций. Всего: 852004
🔄 Запрос #8882 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 852105
🔄 Запрос #8883 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 87 спецификаций. Всего: 852192
🔄 Запрос #8884 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 98 спецификаций. Всего: 852290
🔄 Запрос #8885 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 127 спецификаций. Всего: 852417
🔄 Запрос #8886 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 132 спецификаций. Всего: 852549
🔄 Запрос #8887 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 126 спецификаций. Всего: 852675
🔄 Запрос #8888 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 136 спецификаций. Всего: 852811
🔄 Запрос #8889 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 134 спецификаций. Всего: 852945
🔄 Запрос #8890 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 121 спецификаций. Всего: 853066
🔄 Запрос #8891 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 110 спецификаций. Всего: 853176
🔄 Запрос #8892 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 110 спецификаций. Всего: 853286
🔄 Запрос #8893 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 121 спецификаций. Всего: 853407
🔄 Запрос #8894 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 853521
🔄 Запрос #8895 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 108 спецификаций. Всего: 853629
🔄 Запрос #8896 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 853746
🔄 Запрос #8897 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 130 спецификаций. Всего: 853876
🔄 Запрос #8898 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 127 спецификаций. Всего: 854003
🔄 Запрос #8899 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 122 спецификаций. Всего: 854125
🔄 Запрос #8900 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 127 спецификаций. Всего: 854252
🔄 Запрос #8901 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 119 спецификаций. Всего: 854371
🔄 Запрос #8902 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 119 спецификаций. Всего: 854490
🔄 Запрос #8903 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 110 спецификаций. Всего: 854600
🔄 Запрос #8904 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 854718
📤 Сохранено 10033 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #8905 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 111 спецификаций. Всего: 854829
🔄 Запрос #8906 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 854943
🔄 Запрос #8907 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 90 спецификаций. Всего: 855033
🔄 Запрос #8908 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 855119
🔄 Запрос #8909 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 79 спецификаций. Всего: 855198
🔄 Запрос #8910 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 85 спецификаций. Всего: 855283
🔄 Запрос #8911 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 55 спецификаций. Всего: 855338
🔄 Запрос #8912 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 120 спецификаций. Всего: 855458
🔄 Запрос #8913 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 855564
🔄 Запрос #8914 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 855682
🔄 Запрос #8915 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 129 спецификаций. Всего: 855811
🔄 Запрос #8916 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 87 спецификаций. Всего: 855898
🔄 Запрос #8917 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 110 спецификаций. Всего: 856008
🔄 Запрос #8918 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 98 спецификаций. Всего: 856106
🔄 Запрос #8919 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 128 спецификаций. Всего: 856234
🔄 Запрос #8920 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 160 спецификаций. Всего: 856394
🔄 Запрос #8921 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 148 спецификаций. Всего: 856542
🔄 Запрос #8922 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 128 спецификаций. Всего: 856670
🔄 Запрос #8923 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 130 спецификаций. Всего: 856800
🔄 Запрос #8924 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 115 спецификаций. Всего: 856915
🔄 Запрос #8925 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 857033
🔄 Запрос #8926 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 123 спецификаций. Всего: 857156
🔄 Запрос #8927 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 126 спецификаций. Всего: 857282
🔄 Запрос #8928 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 127 спецификаций. Всего: 857409
🔄 Запрос #8929 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 102 спецификаций. Всего: 857511
🔄 Запрос #8930 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 115 спецификаций. Всего: 857626
🔄 Запрос #8931 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 857735
🔄 Запрос #8932 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 857836
🔄 Запрос #8933 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 857927
🔄 Запрос #8934 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 858030
🔄 Запрос #8935 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 95 спецификаций. Всего: 858125
🔄 Запрос #8936 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 88 спецификаций. Всего: 858213
🔄 Запрос #8937 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 89 спецификаций. Всего: 858302
🔄 Запрос #8938 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 858406
🔄 Запрос #8939 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 88 спецификаций. Всего: 858494
🔄 Запрос #8940 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 99 спецификаций. Всего: 858593
🔄 Запрос #8941 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 94 спецификаций. Всего: 858687
🔄 Запрос #8942 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 100 спецификаций. Всего: 858787
🔄 Запрос #8943 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 100 спецификаций. Всего: 858887
🔄 Запрос #8944 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 98 спецификаций. Всего: 858985
🔄 Запрос #8945 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 87 спецификаций. Всего: 859072
🔄 Запрос #8946 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 96 спецификаций. Всего: 859168
🔄 Запрос #8947 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 80 спецификаций. Всего: 859248
🔄 Запрос #8948 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 859352
🔄 Запрос #8949 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 80 спецификаций. Всего: 859432
🔄 Запрос #8950 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 116 спецификаций. Всего: 859548
🔄 Запрос #8951 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 105 спецификаций. Всего: 859653
🔄 Запрос #8952 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 859766
🔄 Запрос #8953 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 105 спецификаций. Всего: 859871
🔄 Запрос #8954 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 115 спецификаций. Всего: 859986
🔄 Запрос #8955 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 860089
🔄 Запрос #8956 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 860195
🔄 Запрос #8957 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 88 спецификаций. Всего: 860283
🔄 Запрос #8958 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 114 спецификаций. Всего: 860397
🔄 Запрос #8959 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 86 спецификаций. Всего: 860483
🔄 Запрос #8960 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 96 спецификаций. Всего: 860579
🔄 Запрос #8961 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 111 спецификаций. Всего: 860690
🔄 Запрос #8962 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 104 спецификаций. Всего: 860794
🔄 Запрос #8963 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 860911
🔄 Запрос #8964 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 90 спецификаций. Всего: 861001
🔄 Запрос #8965 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 861107
🔄 Запрос #8966 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 861220
🔄 Запрос #8967 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 106 спецификаций. Всего: 861326
🔄 Запрос #8968 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 123 спецификаций. Всего: 861449
🔄 Запрос #8969 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 861562
🔄 Запрос #8970 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 861665
🔄 Запрос #8971 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 101 спецификаций. Всего: 861766
🔄 Запрос #8972 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 119 спецификаций. Всего: 861885
🔄 Запрос #8973 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 98 спецификаций. Всего: 861983
🔄 Запрос #8974 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 78 спецификаций. Всего: 862061
🔄 Запрос #8975 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 119 спецификаций. Всего: 862180
🔄 Запрос #8976 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 137 спецификаций. Всего: 862317
🔄 Запрос #8977 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 147 спецификаций. Всего: 862464
🔄 Запрос #8978 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 143 спецификаций. Всего: 862607
🔄 Запрос #8979 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 135 спецификаций. Всего: 862742
🔄 Запрос #8980 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 112 спецификаций. Всего: 862854
🔄 Запрос #8981 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 120 спецификаций. Всего: 862974
🔄 Запрос #8982 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 118 спецификаций. Всего: 863092
🔄 Запрос #8983 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 863205
🔄 Запрос #8984 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 89 спецификаций. Всего: 863294
🔄 Запрос #8985 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 96 спецификаций. Всего: 863390
🔄 Запрос #8986 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 100 спецификаций. Всего: 863490
🔄 Запрос #8987 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 90 спецификаций. Всего: 863580
🔄 Запрос #8988 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 863687
🔄 Запрос #8989 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 116 спецификаций. Всего: 863803
🔄 Запрос #8990 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 123 спецификаций. Всего: 863926
🔄 Запрос #8991 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 864027
🔄 Запрос #8992 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 103 спецификаций. Всего: 864130
🔄 Запрос #8993 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 84 спецификаций. Всего: 864214
🔄 Запрос #8994 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 864305
🔄 Запрос #8995 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 864396
🔄 Запрос #8996 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 96 спецификаций. Всего: 864492
🔄 Запрос #8997 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 95 спецификаций. Всего: 864587
🔄 Запрос #8998 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 101 спецификаций. Всего: 864688
🔄 Запрос #8999 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 91 спецификаций. Всего: 864779
📤 Сохранено 10061 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #9000 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 84 спецификаций. Всего: 864863
🔄 Запрос #9001 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 111 спецификаций. Всего: 864974
🔄 Запрос #9002 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 128 спецификаций. Всего: 865102
🔄 Запрос #9003 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 109 спецификаций. Всего: 865211
🔄 Запрос #9004 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 865328
🔄 Запрос #9005 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 112 спецификаций. Всего: 865440
🔄 Запрос #9006 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 120 спецификаций. Всего: 865560
🔄 Запрос #9007 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 122 спецификаций. Всего: 865682
🔄 Запрос #9008 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 865810
🔄 Запрос #9009 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 111 спецификаций. Всего: 865921
🔄 Запрос #9010 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 113 спецификаций. Всего: 866034
🔄 Запрос #9011 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 120 спецификаций. Всего: 866154
🔄 Запрос #9012 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 119 спецификаций. Всего: 866273
🔄 Запрос #9013 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 140 спецификаций. Всего: 866413
🔄 Запрос #9014 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 133 спецификаций. Всего: 866546
🔄 Запрос #9015 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 137 спецификаций. Всего: 866683
🔄 Запрос #9016 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 117 спецификаций. Всего: 866800
🔄 Запрос #9017 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 77 спецификаций. Всего: 866877
🔄 Запрос #9018 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 87 спецификаций. Всего: 866964
🔄 Запрос #9019 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 62 спецификаций. Всего: 867026
🔄 Запрос #9020 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 144 спецификаций. Всего: 867170
🔄 Запрос #9021 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 150 спецификаций. Всего: 867320
🔄 Запрос #9022 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 181 спецификаций. Всего: 867501
🔄 Запрос #9023 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 170 спецификаций. Всего: 867671
🔄 Запрос #9024 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 152 спецификаций. Всего: 867823
🔄 Запрос #9025 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 142 спецификаций. Всего: 867965
🔄 Запрос #9026 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 149 спецификаций. Всего: 868114
🔄 Запрос #9027 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 154 спецификаций. Всего: 868268
🔄 Запрос #9028 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 150 спецификаций. Всего: 868418
🔄 Запрос #9029 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 90 спецификаций. Всего: 868508
🔄 Запрос #9030 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 107 спецификаций. Всего: 868615
🔄 Запрос #9031 для 2024-08-29 20:44:09 - 2024-09-05 20:44:09
📥 Загружено 73 спецификаций. Всего: 868688
📅 Обрабатываем диапазон 2024-08-22 20:44:09 - 2024-08-29 20:44:09 (попытка 1/5)
🔄 Запрос #9032 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 146 спецификаций. Всего: 868834
🔄 Запрос #9033 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 139 спецификаций. Всего: 868973
🔄 Запрос #9034 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 125 спецификаций. Всего: 869098
🔄 Запрос #9035 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 129 спецификаций. Всего: 869227
🔄 Запрос #9036 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 139 спецификаций. Всего: 869366
🔄 Запрос #9037 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 122 спецификаций. Всего: 869488
🔄 Запрос #9038 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 869586
🔄 Запрос #9039 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 109 спецификаций. Всего: 869695
🔄 Запрос #9040 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 103 спецификаций. Всего: 869798
🔄 Запрос #9041 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 119 спецификаций. Всего: 869917
🔄 Запрос #9042 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 870021
🔄 Запрос #9043 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 116 спецификаций. Всего: 870137
🔄 Запрос #9044 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 117 спецификаций. Всего: 870254
🔄 Запрос #9045 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09

📥 Загружено 113 спецификаций. Всего: 870367
🔄 Запрос #9046 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 114 спецификаций. Всего: 870481
🔄 Запрос #9047 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 118 спецификаций. Всего: 870599
🔄 Запрос #9048 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 92 спецификаций. Всего: 870691
🔄 Запрос #9049 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 105 спецификаций. Всего: 870796
🔄 Запрос #9050 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 870897
🔄 Запрос #9051 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 870995
🔄 Запрос #9052 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 132 спецификаций. Всего: 871127
🔄 Запрос #9053 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 112 спецификаций. Всего: 871239
🔄 Запрос #9054 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 138 спецификаций. Всего: 871377
🔄 Запрос #9055 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 116 спецификаций. Всего: 871493
🔄 Запрос #9056 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 871600
🔄 Запрос #9057 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 112 спецификаций. Всего: 871712
🔄 Запрос #9058 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 111 спецификаций. Всего: 871823
🔄 Запрос #9059 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 871923
🔄 Запрос #9060 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 112 спецификаций. Всего: 872035
🔄 Запрос #9061 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 872133
🔄 Запрос #9062 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 103 спецификаций. Всего: 872236
🔄 Запрос #9063 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 872323
🔄 Запрос #9064 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 872431
🔄 Запрос #9065 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 103 спецификаций. Всего: 872534
🔄 Запрос #9066 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 112 спецификаций. Всего: 872646
🔄 Запрос #9067 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 130 спецификаций. Всего: 872776
🔄 Запрос #9068 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 127 спецификаций. Всего: 872903
🔄 Запрос #9069 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 118 спецификаций. Всего: 873021
🔄 Запрос #9070 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 140 спецификаций. Всего: 873161
🔄 Запрос #9071 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 873268
🔄 Запрос #9072 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 109 спецификаций. Всего: 873377
🔄 Запрос #9073 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 144 спецификаций. Всего: 873521
🔄 Запрос #9074 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 119 спецификаций. Всего: 873640
🔄 Запрос #9075 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 110 спецификаций. Всего: 873750
🔄 Запрос #9076 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 873857
🔄 Запрос #9077 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 118 спецификаций. Всего: 873975
🔄 Запрос #9078 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 116 спецификаций. Всего: 874091
🔄 Запрос #9079 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 874189
🔄 Запрос #9080 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 874289
🔄 Запрос #9081 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 109 спецификаций. Всего: 874398
🔄 Запрос #9082 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 103 спецификаций. Всего: 874501
🔄 Запрос #9083 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 874602
🔄 Запрос #9084 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 104 спецификаций. Всего: 874706
🔄 Запрос #9085 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 96 спецификаций. Всего: 874802
📤 Сохранено 10023 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #9086 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 91 спецификаций. Всего: 874893
🔄 Запрос #9087 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 874991
🔄 Запрос #9088 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 96 спецификаций. Всего: 875087
🔄 Запрос #9089 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 77 спецификаций. Всего: 875164
🔄 Запрос #9090 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 82 спецификаций. Всего: 875246
🔄 Запрос #9091 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 132 спецификаций. Всего: 875378
🔄 Запрос #9092 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 145 спецификаций. Всего: 875523
🔄 Запрос #9093 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 130 спецификаций. Всего: 875653
🔄 Запрос #9094 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 129 спецификаций. Всего: 875782
🔄 Запрос #9095 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 122 спецификаций. Всего: 875904
🔄 Запрос #9096 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 137 спецификаций. Всего: 876041
🔄 Запрос #9097 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 139 спецификаций. Всего: 876180
🔄 Запрос #9098 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 115 спецификаций. Всего: 876295
🔄 Запрос #9099 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 876389
🔄 Запрос #9100 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 82 спецификаций. Всего: 876471
🔄 Запрос #9101 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 876568
🔄 Запрос #9102 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 876668
🔄 Запрос #9103 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 876763
🔄 Запрос #9104 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 90 спецификаций. Всего: 876853
🔄 Запрос #9105 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 876954
🔄 Запрос #9106 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 104 спецификаций. Всего: 877058
🔄 Запрос #9107 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 71 спецификаций. Всего: 877129
🔄 Запрос #9108 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 90 спецификаций. Всего: 877219
🔄 Запрос #9109 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 80 спецификаций. Всего: 877299
🔄 Запрос #9110 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 53 спецификаций. Всего: 877352
🔄 Запрос #9111 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 877453
🔄 Запрос #9112 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 132 спецификаций. Всего: 877585
🔄 Запрос #9113 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 173 спецификаций. Всего: 877758
🔄 Запрос #9114 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 143 спецификаций. Всего: 877901
🔄 Запрос #9115 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 141 спецификаций. Всего: 878042
🔄 Запрос #9116 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 878140
🔄 Запрос #9117 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 88 спецификаций. Всего: 878228
🔄 Запрос #9118 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 878326
🔄 Запрос #9119 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 878423

🔄 Запрос #9120 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 99 спецификаций. Всего: 878522
🔄 Запрос #9121 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 92 спецификаций. Всего: 878614
🔄 Запрос #9122 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 878715
🔄 Запрос #9123 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 110 спецификаций. Всего: 878825
🔄 Запрос #9124 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 89 спецификаций. Всего: 878914
🔄 Запрос #9125 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 879014
🔄 Запрос #9126 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 879112
🔄 Запрос #9127 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 118 спецификаций. Всего: 879230
🔄 Запрос #9128 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 116 спецификаций. Всего: 879346
🔄 Запрос #9129 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 120 спецификаций. Всего: 879466
🔄 Запрос #9130 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 111 спецификаций. Всего: 879577
🔄 Запрос #9131 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 90 спецификаций. Всего: 879667
🔄 Запрос #9132 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 96 спецификаций. Всего: 879763
🔄 Запрос #9133 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 879861
🔄 Запрос #9134 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 89 спецификаций. Всего: 879950
🔄 Запрос #9135 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 105 спецификаций. Всего: 880055
🔄 Запрос #9136 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 880162
🔄 Запрос #9137 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 880262
🔄 Запрос #9138 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 880360
🔄 Запрос #9139 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 880467
🔄 Запрос #9140 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 106 спецификаций. Всего: 880573
🔄 Запрос #9141 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 127 спецификаций. Всего: 880700
🔄 Запрос #9142 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 105 спецификаций. Всего: 880805
🔄 Запрос #9143 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 118 спецификаций. Всего: 880923
🔄 Запрос #9144 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 90 спецификаций. Всего: 881013
🔄 Запрос #9145 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 881114
🔄 Запрос #9146 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 112 спецификаций. Всего: 881226
🔄 Запрос #9147 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 111 спецификаций. Всего: 881337
🔄 Запрос #9148 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 99 спецификаций. Всего: 881436
🔄 Запрос #9149 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 84 спецификаций. Всего: 881520
🔄 Запрос #9150 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 96 спецификаций. Всего: 881616
🔄 Запрос #9151 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 105 спецификаций. Всего: 881721
🔄 Запрос #9152 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 110 спецификаций. Всего: 881831
🔄 Запрос #9153 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 881929
🔄 Запрос #9154 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 92 спецификаций. Всего: 882021
🔄 Запрос #9155 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 93 спецификаций. Всего: 882114
🔄 Запрос #9156 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 141 спецификаций. Всего: 882255
🔄 Запрос #9157 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 96 спецификаций. Всего: 882351
🔄 Запрос #9158 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 133 спецификаций. Всего: 882484
🔄 Запрос #9159 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 136 спецификаций. Всего: 882620
🔄 Запрос #9160 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 882707
🔄 Запрос #9161 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 882815
🔄 Запрос #9162 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 122 спецификаций. Всего: 882937
🔄 Запрос #9163 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 883035
🔄 Запрос #9164 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 106 спецификаций. Всего: 883141
🔄 Запрос #9165 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 90 спецификаций. Всего: 883231
🔄 Запрос #9166 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 102 спецификаций. Всего: 883333
🔄 Запрос #9167 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 883434
🔄 Запрос #9168 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 127 спецификаций. Всего: 883561
🔄 Запрос #9169 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 883661
🔄 Запрос #9170 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 883758
🔄 Запрос #9171 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 91 спецификаций. Всего: 883849
🔄 Запрос #9172 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 93 спецификаций. Всего: 883942
🔄 Запрос #9173 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 121 спецификаций. Всего: 884063
🔄 Запрос #9174 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 884170
🔄 Запрос #9175 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 136 спецификаций. Всего: 884306
🔄 Запрос #9176 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 102 спецификаций. Всего: 884408
🔄 Запрос #9177 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 104 спецификаций. Всего: 884512
🔄 Запрос #9178 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 78 спецификаций. Всего: 884590
🔄 Запрос #9179 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 84 спецификаций. Всего: 884674
🔄 Запрос #9180 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 93 спецификаций. Всего: 884767
🔄 Запрос #9181 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 105 спецификаций. Всего: 884872
📤 Сохранено 10070 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #9182 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 136 спецификаций. Всего: 885008
🔄 Запрос #9183 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 885108
🔄 Запрос #9184 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 885208
🔄 Запрос #9185 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 885316
🔄 Запрос #9186 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 90 спецификаций. Всего: 885406
🔄 Запрос #9187 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 885500
🔄 Запрос #9188 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 93 спецификаций. Всего: 885593
🔄 Запрос #9189 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 88 спецификаций. Всего: 885681
🔄 Запрос #9190 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 106 спецификаций. Всего: 885787
🔄 Запрос #9191 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 75 спецификаций. Всего: 885862
🔄 Запрос #9192 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 885960
🔄 Запрос #9193 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 886046
🔄 Запрос #9194 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 886144
🔄 Запрос #9195 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 109 спецификаций. Всего: 886253
🔄 Запрос #9196 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09

📥 Загружено 96 спецификаций. Всего: 886349
🔄 Запрос #9197 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 886436
🔄 Запрос #9198 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 112 спецификаций. Всего: 886548
🔄 Запрос #9199 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 82 спецификаций. Всего: 886630
🔄 Запрос #9200 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 146 спецификаций. Всего: 886776
🔄 Запрос #9201 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 149 спецификаций. Всего: 886925
🔄 Запрос #9202 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 887012
🔄 Запрос #9203 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 141 спецификаций. Всего: 887153
🔄 Запрос #9204 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 102 спецификаций. Всего: 887255
🔄 Запрос #9205 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 68 спецификаций. Всего: 887323
🔄 Запрос #9206 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 76 спецификаций. Всего: 887399
🔄 Запрос #9207 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 136 спецификаций. Всего: 887535
🔄 Запрос #9208 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 136 спецификаций. Всего: 887671
🔄 Запрос #9209 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 121 спецификаций. Всего: 887792
🔄 Запрос #9210 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 120 спецификаций. Всего: 887912
🔄 Запрос #9211 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 888019
🔄 Запрос #9212 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 109 спецификаций. Всего: 888128
🔄 Запрос #9213 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 888228
🔄 Запрос #9214 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 888325
🔄 Запрос #9215 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 103 спецификаций. Всего: 888428
🔄 Запрос #9216 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 67 спецификаций. Всего: 888495
🔄 Запрос #9217 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 84 спецификаций. Всего: 888579
🔄 Запрос #9218 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 47 спецификаций. Всего: 888626
🔄 Запрос #9219 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 5 спецификаций. Всего: 888631
🔄 Запрос #9220 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 16 спецификаций. Всего: 888647
🔄 Запрос #9221 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 69 спецификаций. Всего: 888716
🔄 Запрос #9222 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 81 спецификаций. Всего: 888797
🔄 Запрос #9223 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 50 спецификаций. Всего: 888847
🔄 Запрос #9224 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 888930
🔄 Запрос #9225 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 36 спецификаций. Всего: 888966
🔄 Запрос #9226 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 88 спецификаций. Всего: 889054
🔄 Запрос #9227 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 66 спецификаций. Всего: 889120
🔄 Запрос #9228 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 889217
🔄 Запрос #9229 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 889312
🔄 Запрос #9230 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 125 спецификаций. Всего: 889437
🔄 Запрос #9231 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 889524
🔄 Запрос #9232 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 106 спецификаций. Всего: 889630
🔄 Запрос #9233 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 118 спецификаций. Всего: 889748
🔄 Запрос #9234 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 120 спецификаций. Всего: 889868
🔄 Запрос #9235 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 125 спецификаций. Всего: 889993
🔄 Запрос #9236 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 51 спецификаций. Всего: 890044
🔄 Запрос #9237 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 40 спецификаций. Всего: 890084
🔄 Запрос #9238 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 890185
🔄 Запрос #9239 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 890292
🔄 Запрос #9240 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 890392
🔄 Запрос #9241 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 103 спецификаций. Всего: 890495
🔄 Запрос #9242 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 110 спецификаций. Всего: 890605
🔄 Запрос #9243 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 890705
🔄 Запрос #9244 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 91 спецификаций. Всего: 890796
🔄 Запрос #9245 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 74 спецификаций. Всего: 890870
🔄 Запрос #9246 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 84 спецификаций. Всего: 890954
🔄 Запрос #9247 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 96 спецификаций. Всего: 891050
🔄 Запрос #9248 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 111 спецификаций. Всего: 891161
🔄 Запрос #9249 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 117 спецификаций. Всего: 891278
🔄 Запрос #9250 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 104 спецификаций. Всего: 891382
🔄 Запрос #9251 для 2024-08-22 20:44:09 - 2024-08-29 20:44:09
📥 Загружено 68 спецификаций. Всего: 891450
📅 Обрабатываем диапазон 2024-08-15 20:44:09 - 2024-08-22 20:44:09 (попытка 1/5)
🔄 Запрос #9252 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 126 спецификаций. Всего: 891576
🔄 Запрос #9253 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 144 спецификаций. Всего: 891720
🔄 Запрос #9254 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 137 спецификаций. Всего: 891857
🔄 Запрос #9255 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 127 спецификаций. Всего: 891984
🔄 Запрос #9256 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 892101
🔄 Запрос #9257 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 892212
🔄 Запрос #9258 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 892310
🔄 Запрос #9259 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 116 спецификаций. Всего: 892426
🔄 Запрос #9260 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 113 спецификаций. Всего: 892539
🔄 Запрос #9261 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 121 спецификаций. Всего: 892660
🔄 Запрос #9262 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 96 спецификаций. Всего: 892756
🔄 Запрос #9263 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 892854
🔄 Запрос #9264 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 892957
🔄 Запрос #9265 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 893060
🔄 Запрос #9266 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 893166
🔄 Запрос #9267 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 118 спецификаций. Всего: 893284
🔄 Запрос #9268 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 89 спецификаций. Всего: 893373
🔄 Запрос #9269 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 56 спецификаций. Всего: 893429
🔄 Запрос #9270 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 2 спецификаций. Всего: 893431

🔄 Запрос #9271 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 72 спецификаций. Всего: 893503
🔄 Запрос #9272 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 893602
🔄 Запрос #9273 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 83 спецификаций. Всего: 893685
🔄 Запрос #9274 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 90 спецификаций. Всего: 893775
🔄 Запрос #9275 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 138 спецификаций. Всего: 893913
🔄 Запрос #9276 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 139 спецификаций. Всего: 894052
🔄 Запрос #9277 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 124 спецификаций. Всего: 894176
🔄 Запрос #9278 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 894282
🔄 Запрос #9279 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 115 спецификаций. Всего: 894397
🔄 Запрос #9280 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 120 спецификаций. Всего: 894517
🔄 Запрос #9281 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 93 спецификаций. Всего: 894610
🔄 Запрос #9282 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 115 спецификаций. Всего: 894725
🔄 Запрос #9283 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 894831
🔄 Запрос #9284 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 118 спецификаций. Всего: 894949
📤 Сохранено 10077 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #9285 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 133 спецификаций. Всего: 895082
🔄 Запрос #9286 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 895188
🔄 Запрос #9287 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 102 спецификаций. Всего: 895290
🔄 Запрос #9288 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 895384
🔄 Запрос #9289 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 96 спецификаций. Всего: 895480
🔄 Запрос #9290 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 125 спецификаций. Всего: 895605
🔄 Запрос #9291 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 895708
🔄 Запрос #9292 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 895819
🔄 Запрос #9293 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 895930
🔄 Запрос #9294 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 128 спецификаций. Всего: 896058
🔄 Запрос #9295 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 149 спецификаций. Всего: 896207
🔄 Запрос #9296 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 166 спецификаций. Всего: 896373
🔄 Запрос #9297 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 148 спецификаций. Всего: 896521
🔄 Запрос #9298 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 163 спецификаций. Всего: 896684
🔄 Запрос #9299 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 122 спецификаций. Всего: 896806
🔄 Запрос #9300 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 896923
🔄 Запрос #9301 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 897040
🔄 Запрос #9302 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 139 спецификаций. Всего: 897179
🔄 Запрос #9303 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 132 спецификаций. Всего: 897311
🔄 Запрос #9304 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 154 спецификаций. Всего: 897465
🔄 Запрос #9305 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 157 спецификаций. Всего: 897622
🔄 Запрос #9306 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 131 спецификаций. Всего: 897753
🔄 Запрос #9307 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 897856
🔄 Запрос #9308 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 122 спецификаций. Всего: 897978
🔄 Запрос #9309 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 64 спецификаций. Всего: 898042
🔄 Запрос #9310 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 120 спецификаций. Всего: 898162
🔄 Запрос #9311 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 120 спецификаций. Всего: 898282
🔄 Запрос #9312 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 135 спецификаций. Всего: 898417
🔄 Запрос #9313 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 133 спецификаций. Всего: 898550
🔄 Запрос #9314 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 130 спецификаций. Всего: 898680
🔄 Запрос #9315 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 898797
🔄 Запрос #9316 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 898907
🔄 Запрос #9317 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 93 спецификаций. Всего: 899000
🔄 Запрос #9318 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 899105
🔄 Запрос #9319 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 70 спецификаций. Всего: 899175
🔄 Запрос #9320 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 899269
🔄 Запрос #9321 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 85 спецификаций. Всего: 899354
🔄 Запрос #9322 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 899459
🔄 Запрос #9323 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 899567
🔄 Запрос #9324 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 101 спецификаций. Всего: 899668
🔄 Запрос #9325 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 899785
🔄 Запрос #9326 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 85 спецификаций. Всего: 899870
🔄 Запрос #9327 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 93 спецификаций. Всего: 899963
🔄 Запрос #9328 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 100 спецификаций. Всего: 900063
🔄 Запрос #9329 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 115 спецификаций. Всего: 900178
🔄 Запрос #9330 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 900291
🔄 Запрос #9331 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 121 спецификаций. Всего: 900412
🔄 Запрос #9332 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 149 спецификаций. Всего: 900561
🔄 Запрос #9333 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 900675
🔄 Запрос #9334 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 100 спецификаций. Всего: 900775
🔄 Запрос #9335 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 89 спецификаций. Всего: 900864
🔄 Запрос #9336 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 97 спецификаций. Всего: 900961
🔄 Запрос #9337 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 85 спецификаций. Всего: 901046
🔄 Запрос #9338 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 67 спецификаций. Всего: 901113
🔄 Запрос #9339 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 96 спецификаций. Всего: 901209
🔄 Запрос #9340 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 145 спецификаций. Всего: 901354
🔄 Запрос #9341 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 146 спецификаций. Всего: 901500
🔄 Запрос #9342 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 147 спецификаций. Всего: 901647
🔄 Запрос #9343 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 66 спецификаций. Всего: 901713
🔄 Запрос #9344 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09

📥 Загружено 83 спецификаций. Всего: 901796
🔄 Запрос #9345 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 142 спецификаций. Всего: 901938
🔄 Запрос #9346 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 902044
🔄 Запрос #9347 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 902152
🔄 Запрос #9348 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 90 спецификаций. Всего: 902242
🔄 Запрос #9349 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 134 спецификаций. Всего: 902376
🔄 Запрос #9350 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 123 спецификаций. Всего: 902499
🔄 Запрос #9351 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 82 спецификаций. Всего: 902581
🔄 Запрос #9352 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 116 спецификаций. Всего: 902697
🔄 Запрос #9353 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 902814
🔄 Запрос #9354 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 119 спецификаций. Всего: 902933
🔄 Запрос #9355 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 121 спецификаций. Всего: 903054
🔄 Запрос #9356 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 903162
🔄 Запрос #9357 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 101 спецификаций. Всего: 903263
🔄 Запрос #9358 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 903373
🔄 Запрос #9359 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 127 спецификаций. Всего: 903500
🔄 Запрос #9360 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 109 спецификаций. Всего: 903609
🔄 Запрос #9361 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 95 спецификаций. Всего: 903704
🔄 Запрос #9362 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 903798
🔄 Запрос #9363 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 903896
🔄 Запрос #9364 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 116 спецификаций. Всего: 904012
🔄 Запрос #9365 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 904115
🔄 Запрос #9366 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 104 спецификаций. Всего: 904219
🔄 Запрос #9367 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 101 спецификаций. Всего: 904320
🔄 Запрос #9368 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 95 спецификаций. Всего: 904415
🔄 Запрос #9369 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 90 спецификаций. Всего: 904505
🔄 Запрос #9370 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 904599
🔄 Запрос #9371 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 87 спецификаций. Всего: 904686
🔄 Запрос #9372 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 904784
🔄 Запрос #9373 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 904896
🔄 Запрос #9374 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 905003
📤 Сохранено 10054 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #9375 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 124 спецификаций. Всего: 905127
🔄 Запрос #9376 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 905237
🔄 Запрос #9377 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 119 спецификаций. Всего: 905356
🔄 Запрос #9378 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 125 спецификаций. Всего: 905481
🔄 Запрос #9379 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 124 спецификаций. Всего: 905605
🔄 Запрос #9380 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 905717
🔄 Запрос #9381 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 126 спецификаций. Всего: 905843
🔄 Запрос #9382 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 102 спецификаций. Всего: 905945
🔄 Запрос #9383 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 109 спецификаций. Всего: 906054
🔄 Запрос #9384 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 101 спецификаций. Всего: 906155
🔄 Запрос #9385 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 906253
🔄 Запрос #9386 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 906358
🔄 Запрос #9387 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 148 спецификаций. Всего: 906506
🔄 Запрос #9388 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 115 спецификаций. Всего: 906621
🔄 Запрос #9389 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 906726
🔄 Запрос #9390 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 906821
🔄 Запрос #9391 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 906927
🔄 Запрос #9392 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 907033
🔄 Запрос #9393 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 80 спецификаций. Всего: 907113
🔄 Запрос #9394 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 104 спецификаций. Всего: 907217
🔄 Запрос #9395 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 109 спецификаций. Всего: 907326
🔄 Запрос #9396 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 125 спецификаций. Всего: 907451
🔄 Запрос #9397 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 907557
🔄 Запрос #9398 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 129 спецификаций. Всего: 907686
🔄 Запрос #9399 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 142 спецификаций. Всего: 907828
🔄 Запрос #9400 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 172 спецификаций. Всего: 908000
🔄 Запрос #9401 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 131 спецификаций. Всего: 908131
🔄 Запрос #9402 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 102 спецификаций. Всего: 908233
🔄 Запрос #9403 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 150 спецификаций. Всего: 908383
🔄 Запрос #9404 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 140 спецификаций. Всего: 908523
🔄 Запрос #9405 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 95 спецификаций. Всего: 908618
🔄 Запрос #9406 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 908729
🔄 Запрос #9407 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 100 спецификаций. Всего: 908829
🔄 Запрос #9408 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 121 спецификаций. Всего: 908950
🔄 Запрос #9409 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 909064
🔄 Запрос #9410 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 100 спецификаций. Всего: 909164
🔄 Запрос #9411 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 909267
🔄 Запрос #9412 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 83 спецификаций. Всего: 909350
🔄 Запрос #9413 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 909457
🔄 Запрос #9414 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 68 спецификаций. Всего: 909525
🔄 Запрос #9415 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 71 спецификаций. Всего: 909596
🔄 Запрос #9416 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 86 спецификаций. Всего: 909682
🔄 Запрос #9417 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 87 спецификаций. Всего: 909769

🔄 Запрос #9418 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 909867
🔄 Запрос #9419 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 909974
🔄 Запрос #9420 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 91 спецификаций. Всего: 910065
🔄 Запрос #9421 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 910149
🔄 Запрос #9422 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 910252
🔄 Запрос #9423 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 910366
🔄 Запрос #9424 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 136 спецификаций. Всего: 910502
🔄 Запрос #9425 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 138 спецификаций. Всего: 910640
🔄 Запрос #9426 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 131 спецификаций. Всего: 910771
🔄 Запрос #9427 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 129 спецификаций. Всего: 910900
🔄 Запрос #9428 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 911006
🔄 Запрос #9429 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 911116
🔄 Запрос #9430 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 911220
🔄 Запрос #9431 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 142 спецификаций. Всего: 911362
🔄 Запрос #9432 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 142 спецификаций. Всего: 911504
🔄 Запрос #9433 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 911616
🔄 Запрос #9434 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 116 спецификаций. Всего: 911732
🔄 Запрос #9435 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 911838
🔄 Запрос #9436 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 911936
🔄 Запрос #9437 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 77 спецификаций. Всего: 912013
🔄 Запрос #9438 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 118 спецификаций. Всего: 912131
🔄 Запрос #9439 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 141 спецификаций. Всего: 912272
🔄 Запрос #9440 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 151 спецификаций. Всего: 912423
🔄 Запрос #9441 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 121 спецификаций. Всего: 912544
🔄 Запрос #9442 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 119 спецификаций. Всего: 912663
🔄 Запрос #9443 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 59 спецификаций. Всего: 912722
🔄 Запрос #9444 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 912821
🔄 Запрос #9445 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 63 спецификаций. Всего: 912884
🔄 Запрос #9446 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 158 спецификаций. Всего: 913042
🔄 Запрос #9447 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 255 спецификаций. Всего: 913297
🔄 Запрос #9448 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 78 спецификаций. Всего: 913375
🔄 Запрос #9449 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 146 спецификаций. Всего: 913521
🔄 Запрос #9450 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 135 спецификаций. Всего: 913656
🔄 Запрос #9451 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 162 спецификаций. Всего: 913818
🔄 Запрос #9452 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 139 спецификаций. Всего: 913957
🔄 Запрос #9453 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 136 спецификаций. Всего: 914093
🔄 Запрос #9454 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 131 спецификаций. Всего: 914224
🔄 Запрос #9455 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 135 спецификаций. Всего: 914359
🔄 Запрос #9456 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 119 спецификаций. Всего: 914478
🔄 Запрос #9457 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 104 спецификаций. Всего: 914582
🔄 Запрос #9458 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 120 спецификаций. Всего: 914702
🔄 Запрос #9459 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 914816
🔄 Запрос #9460 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 914915
🔄 Запрос #9461 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 97 спецификаций. Всего: 915012
📤 Сохранено 10009 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #9462 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 96 спецификаций. Всего: 915108
🔄 Запрос #9463 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 77 спецификаций. Всего: 915185
🔄 Запрос #9464 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 77 спецификаций. Всего: 915262
🔄 Запрос #9465 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 61 спецификаций. Всего: 915323
🔄 Запрос #9466 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 90 спецификаций. Всего: 915413
🔄 Запрос #9467 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 915519
🔄 Запрос #9468 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 915630
🔄 Запрос #9469 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 104 спецификаций. Всего: 915734
🔄 Запрос #9470 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 915848
🔄 Запрос #9471 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 119 спецификаций. Всего: 915967
🔄 Запрос #9472 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 916075
🔄 Запрос #9473 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 96 спецификаций. Всего: 916171
🔄 Запрос #9474 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 91 спецификаций. Всего: 916262
🔄 Запрос #9475 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 916361
🔄 Запрос #9476 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 109 спецификаций. Всего: 916470
🔄 Запрос #9477 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 123 спецификаций. Всего: 916593
🔄 Запрос #9478 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 129 спецификаций. Всего: 916722
🔄 Запрос #9479 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 124 спецификаций. Всего: 916846
🔄 Запрос #9480 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 127 спецификаций. Всего: 916973
🔄 Запрос #9481 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 155 спецификаций. Всего: 917128
🔄 Запрос #9482 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 168 спецификаций. Всего: 917296
🔄 Запрос #9483 для 2024-08-15 20:44:09 - 2024-08-22 20:44:09
📥 Загружено 73 спецификаций. Всего: 917369
📅 Обрабатываем диапазон 2024-08-08 20:44:09 - 2024-08-15 20:44:09 (попытка 1/5)
🔄 Запрос #9484 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 142 спецификаций. Всего: 917511
🔄 Запрос #9485 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 125 спецификаций. Всего: 917636
🔄 Запрос #9486 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 917746
🔄 Запрос #9487 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 105 спецификаций. Всего: 917851
🔄 Запрос #9488 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 917967
🔄 Запрос #9489 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 140 спецификаций. Всего: 918107
🔄 Запрос #9490 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 132 спецификаций. Всего: 918239
🔄 Запрос #9491 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 85 спецификаций. Всего: 918324
🔄 Запрос #9492 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 77 спецификаций. Всего: 918401
🔄 Запрос #9493 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 81 спецификаций. Всего: 918482
🔄 Запрос #9494 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 918582
🔄 Запрос #9495 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 123 спецификаций. Всего: 918705
🔄 Запрос #9496 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 918801
🔄 Запрос #9497 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 120 спецификаций. Всего: 918921
🔄 Запрос #9498 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 94 спецификаций. Всего: 919015
🔄 Запрос #9499 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 76 спецификаций. Всего: 919091
🔄 Запрос #9500 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 87 спецификаций. Всего: 919178
🔄 Запрос #9501 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 81 спецификаций. Всего: 919259
🔄 Запрос #9502 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 919361
🔄 Запрос #9503 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 919469
🔄 Запрос #9504 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 86 спецификаций. Всего: 919555
🔄 Запрос #9505 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 95 спецификаций. Всего: 919650
🔄 Запрос #9506 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 76 спецификаций. Всего: 919726
🔄 Запрос #9507 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 114 спецификаций. Всего: 919840
🔄 Запрос #9508 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 122 спецификаций. Всего: 919962
🔄 Запрос #9509 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 126 спецификаций. Всего: 920088
🔄 Запрос #9510 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 117 спецификаций. Всего: 920205
🔄 Запрос #9511 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 920316
🔄 Запрос #9512 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 920413
🔄 Запрос #9513 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 920515
🔄 Запрос #9514 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 920622
🔄 Запрос #9515 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 131 спецификаций. Всего: 920753
🔄 Запрос #9516 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 135 спецификаций. Всего: 920888
🔄 Запрос #9517 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 920987
🔄 Запрос #9518 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 119 спецификаций. Всего: 921106
🔄 Запрос #9519 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 114 спецификаций. Всего: 921220
🔄 Запрос #9520 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 921339
🔄 Запрос #9521 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 921450
🔄 Запрос #9522 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 921553
🔄 Запрос #9523 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 80 спецификаций. Всего: 921633
🔄 Запрос #9524 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 921730
🔄 Запрос #9525 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 158 спецификаций. Всего: 921888
🔄 Запрос #9526 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 126 спецификаций. Всего: 922014
🔄 Запрос #9527 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 922113
🔄 Запрос #9528 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 137 спецификаций. Всего: 922250
🔄 Запрос #9529 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 127 спецификаций. Всего: 922377
🔄 Запрос #9530 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 922487
🔄 Запрос #9531 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 922602
🔄 Запрос #9532 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 146 спецификаций. Всего: 922748
🔄 Запрос #9533 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 128 спецификаций. Всего: 922876
🔄 Запрос #9534 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 122 спецификаций. Всего: 922998
🔄 Запрос #9535 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 116 спецификаций. Всего: 923114
🔄 Запрос #9536 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 120 спецификаций. Всего: 923234
🔄 Запрос #9537 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 923347
🔄 Запрос #9538 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 923465
🔄 Запрос #9539 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 136 спецификаций. Всего: 923601
🔄 Запрос #9540 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 138 спецификаций. Всего: 923739
🔄 Запрос #9541 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 119 спецификаций. Всего: 923858
🔄 Запрос #9542 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 120 спецификаций. Всего: 923978
🔄 Запрос #9543 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 94 спецификаций. Всего: 924072
🔄 Запрос #9544 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 91 спецификаций. Всего: 924163
🔄 Запрос #9545 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 72 спецификаций. Всего: 924235
🔄 Запрос #9546 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 924343
🔄 Запрос #9547 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 924446
🔄 Запрос #9548 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 124 спецификаций. Всего: 924570
🔄 Запрос #9549 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 924683
🔄 Запрос #9550 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 121 спецификаций. Всего: 924804
🔄 Запрос #9551 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 924900
🔄 Запрос #9552 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 925007
🔄 Запрос #9553 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 925120
📤 Сохранено 10108 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #9554 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 114 спецификаций. Всего: 925234
🔄 Запрос #9555 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 147 спецификаций. Всего: 925381
🔄 Запрос #9556 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 136 спецификаций. Всего: 925517
🔄 Запрос #9557 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 105 спецификаций. Всего: 925622
🔄 Запрос #9558 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 138 спецификаций. Всего: 925760
🔄 Запрос #9559 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 106 спецификаций. Всего: 925866
🔄 Запрос #9560 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 126 спецификаций. Всего: 925992
🔄 Запрос #9561 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 926110
🔄 Запрос #9562 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 926221
🔄 Запрос #9563 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 130 спецификаций. Всего: 926351
🔄 Запрос #9564 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 155 спецификаций. Всего: 926506
🔄 Запрос #9565 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 129 спецификаций. Всего: 926635
🔄 Запрос #9566 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 133 спецификаций. Всего: 926768
🔄 Запрос #9567 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 926870
🔄 Запрос #9568 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 926988
🔄 Запрос #9569 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 927080
🔄 Запрос #9570 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 927188
🔄 Запрос #9571 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 927286
🔄 Запрос #9572 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 129 спецификаций. Всего: 927415
🔄 Запрос #9573 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 155 спецификаций. Всего: 927570
🔄 Запрос #9574 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 138 спецификаций. Всего: 927708
🔄 Запрос #9575 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 125 спецификаций. Всего: 927833
🔄 Запрос #9576 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 119 спецификаций. Всего: 927952
🔄 Запрос #9577 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 130 спецификаций. Всего: 928082
🔄 Запрос #9578 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 135 спецификаций. Всего: 928217
🔄 Запрос #9579 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 928321
🔄 Запрос #9580 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 80 спецификаций. Всего: 928401
🔄 Запрос #9581 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 928499
🔄 Запрос #9582 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 95 спецификаций. Всего: 928594
🔄 Запрос #9583 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 126 спецификаций. Всего: 928720
🔄 Запрос #9584 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 928818
🔄 Запрос #9585 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 928928
🔄 Запрос #9586 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 929029
🔄 Запрос #9587 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 929121
🔄 Запрос #9588 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 929223
🔄 Запрос #9589 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 83 спецификаций. Всего: 929306
🔄 Запрос #9590 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 80 спецификаций. Всего: 929386
🔄 Запрос #9591 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 75 спецификаций. Всего: 929461
🔄 Запрос #9592 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 929553
🔄 Запрос #9593 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 929650
🔄 Запрос #9594 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 929759
🔄 Запрос #9595 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 89 спецификаций. Всего: 929848
🔄 Запрос #9596 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 929949
🔄 Запрос #9597 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 93 спецификаций. Всего: 930042
🔄 Запрос #9598 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 930146
🔄 Запрос #9599 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 930257
🔄 Запрос #9600 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 930365
🔄 Запрос #9601 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 930483
🔄 Запрос #9602 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 159 спецификаций. Всего: 930642
🔄 Запрос #9603 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 119 спецификаций. Всего: 930761
🔄 Запрос #9604 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 930862
🔄 Запрос #9605 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 88 спецификаций. Всего: 930950
🔄 Запрос #9606 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 931058
🔄 Запрос #9607 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 931155
🔄 Запрос #9608 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 931270
🔄 Запрос #9609 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 931377
🔄 Запрос #9610 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 122 спецификаций. Всего: 931499
🔄 Запрос #9611 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 127 спецификаций. Всего: 931626
🔄 Запрос #9612 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 121 спецификаций. Всего: 931747
🔄 Запрос #9613 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 931855
🔄 Запрос #9614 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 112 спецификаций. Всего: 931967
🔄 Запрос #9615 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 932085
🔄 Запрос #9616 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 142 спецификаций. Всего: 932227
🔄 Запрос #9617 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 155 спецификаций. Всего: 932382
🔄 Запрос #9618 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 127 спецификаций. Всего: 932509
🔄 Запрос #9619 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 156 спецификаций. Всего: 932665
🔄 Запрос #9620 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 130 спецификаций. Всего: 932795
🔄 Запрос #9621 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 106 спецификаций. Всего: 932901
🔄 Запрос #9622 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 133 спецификаций. Всего: 933034
🔄 Запрос #9623 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 124 спецификаций. Всего: 933158
🔄 Запрос #9624 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 142 спецификаций. Всего: 933300
🔄 Запрос #9625 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 134 спецификаций. Всего: 933434
🔄 Запрос #9626 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 933552
🔄 Запрос #9627 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 933659
🔄 Запрос #9628 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 933758
🔄 Запрос #9629 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 105 спецификаций. Всего: 933863
🔄 Запрос #9630 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 126 спецификаций. Всего: 933989
🔄 Запрос #9631 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 135 спецификаций. Всего: 934124
🔄 Запрос #9632 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 120 спецификаций. Всего: 934244
🔄 Запрос #9633 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 117 спецификаций. Всего: 934361
🔄 Запрос #9634 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 934463
🔄 Запрос #9635 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 934566
🔄 Запрос #9636 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 81 спецификаций. Всего: 934647
🔄 Запрос #9637 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 934739
🔄 Запрос #9638 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 124 спецификаций. Всего: 934863
🔄 Запрос #9639 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09

📥 Загружено 155 спецификаций. Всего: 935018
🔄 Запрос #9640 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 149 спецификаций. Всего: 935167
📤 Сохранено 10047 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #9641 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 129 спецификаций. Всего: 935296
🔄 Запрос #9642 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 133 спецификаций. Всего: 935429
🔄 Запрос #9643 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 935540
🔄 Запрос #9644 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 935655
🔄 Запрос #9645 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 85 спецификаций. Всего: 935740
🔄 Запрос #9646 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 935855
🔄 Запрос #9647 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 935965
🔄 Запрос #9648 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 936074
🔄 Запрос #9649 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 936183
🔄 Запрос #9650 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 936296
🔄 Запрос #9651 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 936403
🔄 Запрос #9652 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 936510
🔄 Запрос #9653 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 58 спецификаций. Всего: 936568
🔄 Запрос #9654 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 84 спецификаций. Всего: 936652
🔄 Запрос #9655 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 131 спецификаций. Всего: 936783
🔄 Запрос #9656 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 140 спецификаций. Всего: 936923
🔄 Запрос #9657 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 937030
🔄 Запрос #9658 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 132 спецификаций. Всего: 937162
🔄 Запрос #9659 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 158 спецификаций. Всего: 937320
🔄 Запрос #9660 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 937431
🔄 Запрос #9661 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 937529
🔄 Запрос #9662 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 138 спецификаций. Всего: 937667
🔄 Запрос #9663 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 116 спецификаций. Всего: 937783
🔄 Запрос #9664 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 125 спецификаций. Всего: 937908
🔄 Запрос #9665 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 158 спецификаций. Всего: 938066
🔄 Запрос #9666 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 125 спецификаций. Всего: 938191
🔄 Запрос #9667 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 154 спецификаций. Всего: 938345
🔄 Запрос #9668 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 127 спецификаций. Всего: 938472
🔄 Запрос #9669 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 938587
🔄 Запрос #9670 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 938683
🔄 Запрос #9671 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 938792
🔄 Запрос #9672 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 128 спецификаций. Всего: 938920
🔄 Запрос #9673 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 106 спецификаций. Всего: 939026
🔄 Запрос #9674 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 939145
🔄 Запрос #9675 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 939248
🔄 Запрос #9676 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 939356
🔄 Запрос #9677 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 939460
🔄 Запрос #9678 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 939578
🔄 Запрос #9679 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 119 спецификаций. Всего: 939697
🔄 Запрос #9680 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 125 спецификаций. Всего: 939822
🔄 Запрос #9681 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 123 спецификаций. Всего: 939945
🔄 Запрос #9682 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 72 спецификаций. Всего: 940017
🔄 Запрос #9683 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 940114
🔄 Запрос #9684 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 145 спецификаций. Всего: 940259
🔄 Запрос #9685 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 146 спецификаций. Всего: 940405
🔄 Запрос #9686 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 940531
🔄 Запрос #9687 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 940640
🔄 Запрос #9688 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 130 спецификаций. Всего: 940770
🔄 Запрос #9689 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 116 спецификаций. Всего: 940886
🔄 Запрос #9690 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 940988
🔄 Запрос #9691 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 941092
🔄 Запрос #9692 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 941207
🔄 Запрос #9693 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 941322
🔄 Запрос #9694 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 941421
🔄 Запрос #9695 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 941529
🔄 Запрос #9696 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 119 спецификаций. Всего: 941648
🔄 Запрос #9697 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 941751
🔄 Запрос #9698 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 75 спецификаций. Всего: 941826
🔄 Запрос #9699 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 74 спецификаций. Всего: 941900
🔄 Запрос #9700 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 145 спецификаций. Всего: 942045
🔄 Запрос #9701 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 157 спецификаций. Всего: 942202
🔄 Запрос #9702 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 163 спецификаций. Всего: 942365
🔄 Запрос #9703 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 140 спецификаций. Всего: 942505
🔄 Запрос #9704 для 2024-08-08 20:44:09 - 2024-08-15 20:44:09
📥 Загружено 8 спецификаций. Всего: 942513
📅 Обрабатываем диапазон 2024-08-01 20:44:09 - 2024-08-08 20:44:09 (попытка 1/5)
🔄 Запрос #9705 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 138 спецификаций. Всего: 942651
🔄 Запрос #9706 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 129 спецификаций. Всего: 942780
🔄 Запрос #9707 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 135 спецификаций. Всего: 942915
🔄 Запрос #9708 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 943031
🔄 Запрос #9709 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 119 спецификаций. Всего: 943150
🔄 Запрос #9710 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 943263
🔄 Запрос #9711 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09

📥 Загружено 110 спецификаций. Всего: 943373
🔄 Запрос #9712 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 943478
🔄 Запрос #9713 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 943595
🔄 Запрос #9714 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 943713
🔄 Запрос #9715 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 124 спецификаций. Всего: 943837
🔄 Запрос #9716 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 943949
🔄 Запрос #9717 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 944069
🔄 Запрос #9718 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 944180
🔄 Запрос #9719 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 944282
🔄 Запрос #9720 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 944393
🔄 Запрос #9721 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 84 спецификаций. Всего: 944477
🔄 Запрос #9722 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 78 спецификаций. Всего: 944555
🔄 Запрос #9723 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 96 спецификаций. Всего: 944651
🔄 Запрос #9724 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 84 спецификаций. Всего: 944735
🔄 Запрос #9725 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 97 спецификаций. Всего: 944832
🔄 Запрос #9726 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 98 спецификаций. Всего: 944930
🔄 Запрос #9727 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 945038
🔄 Запрос #9728 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 85 спецификаций. Всего: 945123
🔄 Запрос #9729 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 79 спецификаций. Всего: 945202
📤 Сохранено 10035 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #9730 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 87 спецификаций. Всего: 945289
🔄 Запрос #9731 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 94 спецификаций. Всего: 945383
🔄 Запрос #9732 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 82 спецификаций. Всего: 945465
🔄 Запрос #9733 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 94 спецификаций. Всего: 945559
🔄 Запрос #9734 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 82 спецификаций. Всего: 945641
🔄 Запрос #9735 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 86 спецификаций. Всего: 945727
🔄 Запрос #9736 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 87 спецификаций. Всего: 945814
🔄 Запрос #9737 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 92 спецификаций. Всего: 945906
🔄 Запрос #9738 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 103 спецификаций. Всего: 946009
🔄 Запрос #9739 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 946111
🔄 Запрос #9740 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 93 спецификаций. Всего: 946204
🔄 Запрос #9741 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 946315
🔄 Запрос #9742 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 946426
🔄 Запрос #9743 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 946539
🔄 Запрос #9744 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 946653
🔄 Запрос #9745 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 98 спецификаций. Всего: 946751
🔄 Запрос #9746 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 109 спецификаций. Всего: 946860
🔄 Запрос #9747 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 946968
🔄 Запрос #9748 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 90 спецификаций. Всего: 947058
🔄 Запрос #9749 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 148 спецификаций. Всего: 947206
🔄 Запрос #9750 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 103 спецификаций. Всего: 947309
🔄 Запрос #9751 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 89 спецификаций. Всего: 947398
🔄 Запрос #9752 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 65 спецификаций. Всего: 947463
🔄 Запрос #9753 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 65 спецификаций. Всего: 947528
🔄 Запрос #9754 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 947654
🔄 Запрос #9755 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 94 спецификаций. Всего: 947748
🔄 Запрос #9756 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 947859
🔄 Запрос #9757 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 947992
🔄 Запрос #9758 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 948097
🔄 Запрос #9759 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 109 спецификаций. Всего: 948206
🔄 Запрос #9760 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 948320
🔄 Запрос #9761 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 85 спецификаций. Всего: 948405
🔄 Запрос #9762 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 948519
🔄 Запрос #9763 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 948605
🔄 Запрос #9764 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 948717
🔄 Запрос #9765 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 948822
🔄 Запрос #9766 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 99 спецификаций. Всего: 948921
🔄 Запрос #9767 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 949031
🔄 Запрос #9768 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 89 спецификаций. Всего: 949120
🔄 Запрос #9769 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 87 спецификаций. Всего: 949207
🔄 Запрос #9770 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 949322
🔄 Запрос #9771 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 949430
🔄 Запрос #9772 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 949534
🔄 Запрос #9773 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 97 спецификаций. Всего: 949631
🔄 Запрос #9774 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 88 спецификаций. Всего: 949719
🔄 Запрос #9775 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 949839
🔄 Запрос #9776 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 97 спецификаций. Всего: 949936
🔄 Запрос #9777 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 80 спецификаций. Всего: 950016
🔄 Запрос #9778 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 93 спецификаций. Всего: 950109
🔄 Запрос #9779 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 950219
🔄 Запрос #9780 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 144 спецификаций. Всего: 950363
🔄 Запрос #9781 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 950476
🔄 Запрос #9782 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 950586
🔄 Запрос #9783 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 950700
🔄 Запрос #9784 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 950816
🔄 Запрос #9785 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 950916

🔄 Запрос #9786 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 99 спецификаций. Всего: 951015
🔄 Запрос #9787 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 951117
🔄 Запрос #9788 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 951228
🔄 Запрос #9789 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 107 спецификаций. Всего: 951335
🔄 Запрос #9790 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 129 спецификаций. Всего: 951464
🔄 Запрос #9791 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 99 спецификаций. Всего: 951563
🔄 Запрос #9792 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 98 спецификаций. Всего: 951661
🔄 Запрос #9793 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 129 спецификаций. Всего: 951790
🔄 Запрос #9794 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 951913
🔄 Запрос #9795 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 952039
🔄 Запрос #9796 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 952162
🔄 Запрос #9797 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 93 спецификаций. Всего: 952255
🔄 Запрос #9798 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 952370
🔄 Запрос #9799 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 53 спецификаций. Всего: 952423
🔄 Запрос #9800 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 119 спецификаций. Всего: 952542
🔄 Запрос #9801 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 76 спецификаций. Всего: 952618
🔄 Запрос #9802 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 952728
🔄 Запрос #9803 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 119 спецификаций. Всего: 952847
🔄 Запрос #9804 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 165 спецификаций. Всего: 953012
🔄 Запрос #9805 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 165 спецификаций. Всего: 953177
🔄 Запрос #9806 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 138 спецификаций. Всего: 953315
🔄 Запрос #9807 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 180 спецификаций. Всего: 953495
🔄 Запрос #9808 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 141 спецификаций. Всего: 953636
🔄 Запрос #9809 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 143 спецификаций. Всего: 953779
🔄 Запрос #9810 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 128 спецификаций. Всего: 953907
🔄 Запрос #9811 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 99 спецификаций. Всего: 954006
🔄 Запрос #9812 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 954112
🔄 Запрос #9813 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 91 спецификаций. Всего: 954203
🔄 Запрос #9814 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 96 спецификаций. Всего: 954299
🔄 Запрос #9815 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 84 спецификаций. Всего: 954383
🔄 Запрос #9816 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 83 спецификаций. Всего: 954466
🔄 Запрос #9817 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 954574
🔄 Запрос #9818 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 954689
🔄 Запрос #9819 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 954799
🔄 Запрос #9820 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 954910
🔄 Запрос #9821 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 955025
🔄 Запрос #9822 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 131 спецификаций. Всего: 955156
🔄 Запрос #9823 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 955257
📤 Сохранено 10055 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #9824 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 955363
🔄 Запрос #9825 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 70 спецификаций. Всего: 955433
🔄 Запрос #9826 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 955543
🔄 Запрос #9827 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 99 спецификаций. Всего: 955642
🔄 Запрос #9828 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 955747
🔄 Запрос #9829 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 68 спецификаций. Всего: 955815
🔄 Запрос #9830 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 58 спецификаций. Всего: 955873
🔄 Запрос #9831 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 88 спецификаций. Всего: 955961
🔄 Запрос #9832 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 956065
🔄 Запрос #9833 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 93 спецификаций. Всего: 956158
🔄 Запрос #9834 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 956263
🔄 Запрос #9835 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 956367
🔄 Запрос #9836 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 956482
🔄 Запрос #9837 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 103 спецификаций. Всего: 956585
🔄 Запрос #9838 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 96 спецификаций. Всего: 956681
🔄 Запрос #9839 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 956781
🔄 Запрос #9840 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 99 спецификаций. Всего: 956880
🔄 Запрос #9841 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 94 спецификаций. Всего: 956974
🔄 Запрос #9842 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 957076
🔄 Запрос #9843 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 957193
🔄 Запрос #9844 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 957294
🔄 Запрос #9845 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 94 спецификаций. Всего: 957388
🔄 Запрос #9846 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 98 спецификаций. Всего: 957486
🔄 Запрос #9847 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 96 спецификаций. Всего: 957582
🔄 Запрос #9848 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 82 спецификаций. Всего: 957664
🔄 Запрос #9849 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 957782
🔄 Запрос #9850 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 957893
🔄 Запрос #9851 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 124 спецификаций. Всего: 958017
🔄 Запрос #9852 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 958132
🔄 Запрос #9853 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 958244
🔄 Запрос #9854 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 138 спецификаций. Всего: 958382
🔄 Запрос #9855 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 85 спецификаций. Всего: 958467
🔄 Запрос #9856 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 81 спецификаций. Всего: 958548
🔄 Запрос #9857 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 958654
🔄 Запрос #9858 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 958766
🔄 Запрос #9859 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 98 спецификаций. Всего: 958864
🔄 Запрос #9860 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 958964
🔄 Запрос #9861 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09

📥 Загружено 132 спецификаций. Всего: 959096
🔄 Запрос #9862 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 195 спецификаций. Всего: 959291
🔄 Запрос #9863 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 195 спецификаций. Всего: 959486
🔄 Запрос #9864 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 196 спецификаций. Всего: 959682
🔄 Запрос #9865 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 217 спецификаций. Всего: 959899
🔄 Запрос #9866 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 189 спецификаций. Всего: 960088
🔄 Запрос #9867 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 164 спецификаций. Всего: 960252
🔄 Запрос #9868 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 156 спецификаций. Всего: 960408
🔄 Запрос #9869 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 960528
🔄 Запрос #9870 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 960661
🔄 Запрос #9871 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 960777
🔄 Запрос #9872 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 119 спецификаций. Всего: 960896
🔄 Запрос #9873 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 76 спецификаций. Всего: 960972
🔄 Запрос #9874 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 97 спецификаций. Всего: 961069
🔄 Запрос #9875 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 961181
🔄 Запрос #9876 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 961281
🔄 Запрос #9877 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 135 спецификаций. Всего: 961416
🔄 Запрос #9878 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 961522
🔄 Запрос #9879 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 961643
🔄 Запрос #9880 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 961764
🔄 Запрос #9881 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 158 спецификаций. Всего: 961922
🔄 Запрос #9882 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 137 спецификаций. Всего: 962059
🔄 Запрос #9883 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 89 спецификаций. Всего: 962148
🔄 Запрос #9884 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 89 спецификаций. Всего: 962237
🔄 Запрос #9885 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 962339
🔄 Запрос #9886 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 138 спецификаций. Всего: 962477
🔄 Запрос #9887 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 962584
🔄 Запрос #9888 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 122 спецификаций. Всего: 962706
🔄 Запрос #9889 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 962818
🔄 Запрос #9890 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 149 спецификаций. Всего: 962967
🔄 Запрос #9891 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 963079
🔄 Запрос #9892 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 963196
🔄 Запрос #9893 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 963321
🔄 Запрос #9894 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 156 спецификаций. Всего: 963477
🔄 Запрос #9895 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 137 спецификаций. Всего: 963614
🔄 Запрос #9896 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 963740
🔄 Запрос #9897 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 963865
🔄 Запрос #9898 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 138 спецификаций. Всего: 964003
🔄 Запрос #9899 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 964104
🔄 Запрос #9900 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 964217
🔄 Запрос #9901 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 119 спецификаций. Всего: 964336
🔄 Запрос #9902 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 964451
🔄 Запрос #9903 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 129 спецификаций. Всего: 964580
🔄 Запрос #9904 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 964692
🔄 Запрос #9905 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 964794
🔄 Запрос #9906 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 107 спецификаций. Всего: 964901
🔄 Запрос #9907 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 965007
🔄 Запрос #9908 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 89 спецификаций. Всего: 965096
🔄 Запрос #9909 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 86 спецификаций. Всего: 965182
🔄 Запрос #9910 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 84 спецификаций. Всего: 965266
📤 Сохранено 10009 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #9911 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 76 спецификаций. Всего: 965342
🔄 Запрос #9912 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 131 спецификаций. Всего: 965473
🔄 Запрос #9913 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 965579
🔄 Запрос #9914 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 965699
🔄 Запрос #9915 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 965812
🔄 Запрос #9916 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 131 спецификаций. Всего: 965943
🔄 Запрос #9917 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 966048
🔄 Запрос #9918 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 124 спецификаций. Всего: 966172
🔄 Запрос #9919 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 966290
🔄 Запрос #9920 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 966391
🔄 Запрос #9921 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 966491
🔄 Запрос #9922 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 966602
🔄 Запрос #9923 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 966714
🔄 Запрос #9924 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 97 спецификаций. Всего: 966811
🔄 Запрос #9925 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 98 спецификаций. Всего: 966909
🔄 Запрос #9926 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 97 спецификаций. Всего: 967006
🔄 Запрос #9927 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 967118
🔄 Запрос #9928 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 134 спецификаций. Всего: 967252
🔄 Запрос #9929 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 96 спецификаций. Всего: 967348
🔄 Запрос #9930 для 2024-08-01 20:44:09 - 2024-08-08 20:44:09
📥 Загружено 20 спецификаций. Всего: 967368
📅 Обрабатываем диапазон 2024-07-25 20:44:09 - 2024-08-01 20:44:09 (попытка 1/5)
🔄 Запрос #9931 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 967466
🔄 Запрос #9932 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 967577
🔄 Запрос #9933 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 137 спецификаций. Всего: 967714
🔄 Запрос #9934 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 116 спецификаций. Всего: 967830
🔄 Запрос #9935 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 967928
🔄 Запрос #9936 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 116 спецификаций. Всего: 968044
🔄 Запрос #9937 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 100 спецификаций. Всего: 968144
🔄 Запрос #9938 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 109 спецификаций. Всего: 968253
🔄 Запрос #9939 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 118 спецификаций. Всего: 968371
🔄 Запрос #9940 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 968474
🔄 Запрос #9941 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 93 спецификаций. Всего: 968567
🔄 Запрос #9942 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 110 спецификаций. Всего: 968677
🔄 Запрос #9943 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 90 спецификаций. Всего: 968767
🔄 Запрос #9944 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 96 спецификаций. Всего: 968863
🔄 Запрос #9945 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 92 спецификаций. Всего: 968955
🔄 Запрос #9946 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 969050
🔄 Запрос #9947 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 85 спецификаций. Всего: 969135
🔄 Запрос #9948 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 106 спецификаций. Всего: 969241
🔄 Запрос #9949 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 80 спецификаций. Всего: 969321
🔄 Запрос #9950 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 90 спецификаций. Всего: 969411
🔄 Запрос #9951 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 81 спецификаций. Всего: 969492
🔄 Запрос #9952 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 72 спецификаций. Всего: 969564
🔄 Запрос #9953 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 70 спецификаций. Всего: 969634
🔄 Запрос #9954 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 93 спецификаций. Всего: 969727
🔄 Запрос #9955 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 125 спецификаций. Всего: 969852
🔄 Запрос #9956 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 121 спецификаций. Всего: 969973
🔄 Запрос #9957 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 129 спецификаций. Всего: 970102
🔄 Запрос #9958 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 970210
🔄 Запрос #9959 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 93 спецификаций. Всего: 970303
🔄 Запрос #9960 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 101 спецификаций. Всего: 970404
🔄 Запрос #9961 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 99 спецификаций. Всего: 970503
🔄 Запрос #9962 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 970618
🔄 Запрос #9963 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 94 спецификаций. Всего: 970712
🔄 Запрос #9964 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 99 спецификаций. Всего: 970811
🔄 Запрос #9965 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 122 спецификаций. Всего: 970933
🔄 Запрос #9966 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 109 спецификаций. Всего: 971042
🔄 Запрос #9967 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 91 спецификаций. Всего: 971133
🔄 Запрос #9968 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 971248
🔄 Запрос #9969 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 107 спецификаций. Всего: 971355
🔄 Запрос #9970 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 93 спецификаций. Всего: 971448
🔄 Запрос #9971 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 47 спецификаций. Всего: 971495
🔄 Запрос #9972 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 139 спецификаций. Всего: 971634
🔄 Запрос #9973 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 971749
🔄 Запрос #9974 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 143 спецификаций. Всего: 971892
🔄 Запрос #9975 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 138 спецификаций. Всего: 972030
🔄 Запрос #9976 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 135 спецификаций. Всего: 972165
🔄 Запрос #9977 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 134 спецификаций. Всего: 972299
🔄 Запрос #9978 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 113 спецификаций. Всего: 972412
🔄 Запрос #9979 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 118 спецификаций. Всего: 972530
🔄 Запрос #9980 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 163 спецификаций. Всего: 972693
🔄 Запрос #9981 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 194 спецификаций. Всего: 972887
🔄 Запрос #9982 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 140 спецификаций. Всего: 973027
🔄 Запрос #9983 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 167 спецификаций. Всего: 973194
🔄 Запрос #9984 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 973302
🔄 Запрос #9985 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 973397
🔄 Запрос #9986 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 93 спецификаций. Всего: 973490
🔄 Запрос #9987 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 973592
🔄 Запрос #9988 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 973690
🔄 Запрос #9989 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 87 спецификаций. Всего: 973777
🔄 Запрос #9990 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 973872
🔄 Запрос #9991 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 84 спецификаций. Всего: 973956
🔄 Запрос #9992 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 78 спецификаций. Всего: 974034
🔄 Запрос #9993 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 76 спецификаций. Всего: 974110
🔄 Запрос #9994 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 72 спецификаций. Всего: 974182
🔄 Запрос #9995 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 100 спецификаций. Всего: 974282
🔄 Запрос #9996 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 79 спецификаций. Всего: 974361
🔄 Запрос #9997 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 97 спецификаций. Всего: 974458
🔄 Запрос #9998 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 80 спецификаций. Всего: 974538
🔄 Запрос #9999 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 113 спецификаций. Всего: 974651
🔄 Запрос #10000 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 974762
🔄 Запрос #10001 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 105 спецификаций. Всего: 974867
🔄 Запрос #10002 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 106 спецификаций. Всего: 974973
🔄 Запрос #10003 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 96 спецификаций. Всего: 975069
🔄 Запрос #10004 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 124 спецификаций. Всего: 975193
🔄 Запрос #10005 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 122 спецификаций. Всего: 975315
📤 Сохранено 10049 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #10006 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 975417
🔄 Запрос #10007 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 975512

🔄 Запрос #10008 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 975616
🔄 Запрос #10009 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 116 спецификаций. Всего: 975732
🔄 Запрос #10010 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 975844
🔄 Запрос #10011 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 110 спецификаций. Всего: 975954
🔄 Запрос #10012 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 96 спецификаций. Всего: 976050
🔄 Запрос #10013 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 976154
🔄 Запрос #10014 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 81 спецификаций. Всего: 976235
🔄 Запрос #10015 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 114 спецификаций. Всего: 976349
🔄 Запрос #10016 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 142 спецификаций. Всего: 976491
🔄 Запрос #10017 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 114 спецификаций. Всего: 976605
🔄 Запрос #10018 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 123 спецификаций. Всего: 976728
🔄 Запрос #10019 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 127 спецификаций. Всего: 976855
🔄 Запрос #10020 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 145 спецификаций. Всего: 977000
🔄 Запрос #10021 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 977095
🔄 Запрос #10022 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 80 спецификаций. Всего: 977175
🔄 Запрос #10023 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 96 спецификаций. Всего: 977271
🔄 Запрос #10024 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 88 спецификаций. Всего: 977359
🔄 Запрос #10025 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 90 спецификаций. Всего: 977449
🔄 Запрос #10026 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 88 спецификаций. Всего: 977537
🔄 Запрос #10027 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 76 спецификаций. Всего: 977613
🔄 Запрос #10028 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 90 спецификаций. Всего: 977703
🔄 Запрос #10029 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 977805
🔄 Запрос #10030 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 977908
🔄 Запрос #10031 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 978023
🔄 Запрос #10032 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 116 спецификаций. Всего: 978139
🔄 Запрос #10033 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 96 спецификаций. Всего: 978235
🔄 Запрос #10034 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 101 спецификаций. Всего: 978336
🔄 Запрос #10035 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 85 спецификаций. Всего: 978421
🔄 Запрос #10036 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 101 спецификаций. Всего: 978522
🔄 Запрос #10037 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 978620
🔄 Запрос #10038 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 71 спецификаций. Всего: 978691
🔄 Запрос #10039 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 46 спецификаций. Всего: 978737
🔄 Запрос #10040 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 978832
🔄 Запрос #10041 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 978927
🔄 Запрос #10042 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 96 спецификаций. Всего: 979023
🔄 Запрос #10043 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 114 спецификаций. Всего: 979137
🔄 Запрос #10044 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 979248
🔄 Запрос #10045 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 109 спецификаций. Всего: 979357
🔄 Запрос #10046 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 979478
🔄 Запрос #10047 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 101 спецификаций. Всего: 979579
🔄 Запрос #10048 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 979687
🔄 Запрос #10049 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 979791
🔄 Запрос #10050 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 979893
🔄 Запрос #10051 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 121 спецификаций. Всего: 980014
🔄 Запрос #10052 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 113 спецификаций. Всего: 980127
🔄 Запрос #10053 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 130 спецификаций. Всего: 980257
🔄 Запрос #10054 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 68 спецификаций. Всего: 980325
🔄 Запрос #10055 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 105 спецификаций. Всего: 980430
🔄 Запрос #10056 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 133 спецификаций. Всего: 980563
🔄 Запрос #10057 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 106 спецификаций. Всего: 980669
🔄 Запрос #10058 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 131 спецификаций. Всего: 980800
🔄 Запрос #10059 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 165 спецификаций. Всего: 980965
🔄 Запрос #10060 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 981073
🔄 Запрос #10061 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 106 спецификаций. Всего: 981179
🔄 Запрос #10062 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 138 спецификаций. Всего: 981317
🔄 Запрос #10063 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 92 спецификаций. Всего: 981409
🔄 Запрос #10064 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 91 спецификаций. Всего: 981500
🔄 Запрос #10065 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 93 спецификаций. Всего: 981593
🔄 Запрос #10066 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 981705
🔄 Запрос #10067 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 981817
🔄 Запрос #10068 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 114 спецификаций. Всего: 981931
🔄 Запрос #10069 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 982043
🔄 Запрос #10070 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 982158
🔄 Запрос #10071 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 982260
🔄 Запрос #10072 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 86 спецификаций. Всего: 982346
🔄 Запрос #10073 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 78 спецификаций. Всего: 982424
🔄 Запрос #10074 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 92 спецификаций. Всего: 982516
🔄 Запрос #10075 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 982611
🔄 Запрос #10076 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 982709
🔄 Запрос #10077 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 107 спецификаций. Всего: 982816
🔄 Запрос #10078 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 118 спецификаций. Всего: 982934
🔄 Запрос #10079 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 97 спецификаций. Всего: 983031
🔄 Запрос #10080 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 82 спецификаций. Всего: 983113
🔄 Запрос #10081 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09

📥 Загружено 81 спецификаций. Всего: 983194
🔄 Запрос #10082 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 93 спецификаций. Всего: 983287
🔄 Запрос #10083 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 82 спецификаций. Всего: 983369
🔄 Запрос #10084 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 983467
🔄 Запрос #10085 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 983571
🔄 Запрос #10086 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 100 спецификаций. Всего: 983671
🔄 Запрос #10087 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 88 спецификаций. Всего: 983759
🔄 Запрос #10088 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 84 спецификаций. Всего: 983843
🔄 Запрос #10089 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 84 спецификаций. Всего: 983927
🔄 Запрос #10090 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 165 спецификаций. Всего: 984092
🔄 Запрос #10091 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 124 спецификаций. Всего: 984216
🔄 Запрос #10092 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 153 спецификаций. Всего: 984369
🔄 Запрос #10093 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 81 спецификаций. Всего: 984450
🔄 Запрос #10094 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 88 спецификаций. Всего: 984538
🔄 Запрос #10095 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 180 спецификаций. Всего: 984718
🔄 Запрос #10096 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 153 спецификаций. Всего: 984871
🔄 Запрос #10097 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 179 спецификаций. Всего: 985050
🔄 Запрос #10098 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 186 спецификаций. Всего: 985236
🔄 Запрос #10099 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 142 спецификаций. Всего: 985378
📤 Сохранено 10063 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #10100 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 166 спецификаций. Всего: 985544
🔄 Запрос #10101 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 85 спецификаций. Всего: 985629
🔄 Запрос #10102 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 138 спецификаций. Всего: 985767
🔄 Запрос #10103 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 126 спецификаций. Всего: 985893
🔄 Запрос #10104 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 117 спецификаций. Всего: 986010
🔄 Запрос #10105 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 121 спецификаций. Всего: 986131
🔄 Запрос #10106 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 110 спецификаций. Всего: 986241
🔄 Запрос #10107 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 986343
🔄 Запрос #10108 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 986455
🔄 Запрос #10109 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 986566
🔄 Запрос #10110 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 123 спецификаций. Всего: 986689
🔄 Запрос #10111 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 986797
🔄 Запрос #10112 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 113 спецификаций. Всего: 986910
🔄 Запрос #10113 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 106 спецификаций. Всего: 987016
🔄 Запрос #10114 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 97 спецификаций. Всего: 987113
🔄 Запрос #10115 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 57 спецификаций. Всего: 987170
🔄 Запрос #10116 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 89 спецификаций. Всего: 987259
🔄 Запрос #10117 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 113 спецификаций. Всего: 987372
🔄 Запрос #10118 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 987475
🔄 Запрос #10119 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 126 спецификаций. Всего: 987601
🔄 Запрос #10120 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 154 спецификаций. Всего: 987755
🔄 Запрос #10121 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 117 спецификаций. Всего: 987872
🔄 Запрос #10122 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 129 спецификаций. Всего: 988001
🔄 Запрос #10123 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 137 спецификаций. Всего: 988138
🔄 Запрос #10124 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 988249
🔄 Запрос #10125 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 988364
🔄 Запрос #10126 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 107 спецификаций. Всего: 988471
🔄 Запрос #10127 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 988579
🔄 Запрос #10128 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 128 спецификаций. Всего: 988707
🔄 Запрос #10129 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 117 спецификаций. Всего: 988824
🔄 Запрос #10130 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 988926
🔄 Запрос #10131 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 75 спецификаций. Всего: 989001
🔄 Запрос #10132 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 99 спецификаций. Всего: 989100
🔄 Запрос #10133 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 152 спецификаций. Всего: 989252
🔄 Запрос #10134 для 2024-07-25 20:44:09 - 2024-08-01 20:44:09
📥 Загружено 31 спецификаций. Всего: 989283
📅 Обрабатываем диапазон 2024-07-18 20:44:09 - 2024-07-25 20:44:09 (попытка 1/5)
🔄 Запрос #10135 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 141 спецификаций. Всего: 989424
🔄 Запрос #10136 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 141 спецификаций. Всего: 989565
🔄 Запрос #10137 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 989677
🔄 Запрос #10138 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 989779
🔄 Запрос #10139 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 989883
🔄 Запрос #10140 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 989977
🔄 Запрос #10141 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 53 спецификаций. Всего: 990030
🔄 Запрос #10142 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 73 спецификаций. Всего: 990103
🔄 Запрос #10143 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 990217
🔄 Запрос #10144 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 990322
🔄 Запрос #10145 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 990425
🔄 Запрос #10146 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 990532
🔄 Запрос #10147 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 990616
🔄 Запрос #10148 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 990713
🔄 Запрос #10149 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 990834
🔄 Запрос #10150 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 64 спецификаций. Всего: 990898
🔄 Запрос #10151 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 991018
🔄 Запрос #10152 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 991112
🔄 Запрос #10153 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 991222
🔄 Запрос #10154 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 991339
🔄 Запрос #10155 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09

📥 Загружено 138 спецификаций. Всего: 991477
🔄 Запрос #10156 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 991595
🔄 Запрос #10157 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 991691
🔄 Запрос #10158 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 991803
🔄 Запрос #10159 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 991910
🔄 Запрос #10160 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 992029
🔄 Запрос #10161 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 992148
🔄 Запрос #10162 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 992258
🔄 Запрос #10163 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 992357
🔄 Запрос #10164 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 992471
🔄 Запрос #10165 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 131 спецификаций. Всего: 992602
🔄 Запрос #10166 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 992720
🔄 Запрос #10167 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 992808
🔄 Запрос #10168 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 992898
🔄 Запрос #10169 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 157 спецификаций. Всего: 993055
🔄 Запрос #10170 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 149 спецификаций. Всего: 993204
🔄 Запрос #10171 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 993323
🔄 Запрос #10172 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 133 спецификаций. Всего: 993456
🔄 Запрос #10173 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 158 спецификаций. Всего: 993614
🔄 Запрос #10174 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 128 спецификаций. Всего: 993742
🔄 Запрос #10175 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 138 спецификаций. Всего: 993880
🔄 Запрос #10176 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 993994
🔄 Запрос #10177 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 994112
🔄 Запрос #10178 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 132 спецификаций. Всего: 994244
🔄 Запрос #10179 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 994354
🔄 Запрос #10180 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 994461
🔄 Запрос #10181 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 994568
🔄 Запрос #10182 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 123 спецификаций. Всего: 994691
🔄 Запрос #10183 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 994815
🔄 Запрос #10184 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 145 спецификаций. Всего: 994960
🔄 Запрос #10185 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 995069
🔄 Запрос #10186 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 131 спецификаций. Всего: 995200
🔄 Запрос #10187 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 134 спецификаций. Всего: 995334
🔄 Запрос #10188 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 134 спецификаций. Всего: 995468
📤 Сохранено 10090 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #10189 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 995575
🔄 Запрос #10190 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 995666
🔄 Запрос #10191 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 995781
🔄 Запрос #10192 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 132 спецификаций. Всего: 995913
🔄 Запрос #10193 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 164 спецификаций. Всего: 996077
🔄 Запрос #10194 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 134 спецификаций. Всего: 996211
🔄 Запрос #10195 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 146 спецификаций. Всего: 996357
🔄 Запрос #10196 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 127 спецификаций. Всего: 996484
🔄 Запрос #10197 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 996603
🔄 Запрос #10198 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 996724
🔄 Запрос #10199 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 996831
🔄 Запрос #10200 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 100 спецификаций. Всего: 996931
🔄 Запрос #10201 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 997036
🔄 Запрос #10202 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 997147
🔄 Запрос #10203 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 997237
🔄 Запрос #10204 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 997329
🔄 Запрос #10205 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 78 спецификаций. Всего: 997407
🔄 Запрос #10206 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 997495
🔄 Запрос #10207 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 997587
🔄 Запрос #10208 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 80 спецификаций. Всего: 997667
🔄 Запрос #10209 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 59 спецификаций. Всего: 997726
🔄 Запрос #10210 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 76 спецификаций. Всего: 997802
🔄 Запрос #10211 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 140 спецификаций. Всего: 997942
🔄 Запрос #10212 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 187 спецификаций. Всего: 998129
🔄 Запрос #10213 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 181 спецификаций. Всего: 998310
🔄 Запрос #10214 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 142 спецификаций. Всего: 998452
🔄 Запрос #10215 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 998562
🔄 Запрос #10216 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 998686
🔄 Запрос #10217 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 132 спецификаций. Всего: 998818
🔄 Запрос #10218 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 998939
🔄 Запрос #10219 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 999055
🔄 Запрос #10220 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 999164
🔄 Запрос #10221 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 999267
🔄 Запрос #10222 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 999389
🔄 Запрос #10223 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 130 спецификаций. Всего: 999519
🔄 Запрос #10224 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 150 спецификаций. Всего: 999669
🔄 Запрос #10225 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 130 спецификаций. Всего: 999799
🔄 Запрос #10226 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 999924
🔄 Запрос #10227 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09

📥 Загружено 115 спецификаций. Всего: 1000039
🔄 Запрос #10228 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1000164
🔄 Запрос #10229 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1000275
🔄 Запрос #10230 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1000371
🔄 Запрос #10231 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 82 спецификаций. Всего: 1000453
🔄 Запрос #10232 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1000564
🔄 Запрос #10233 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1000673
🔄 Запрос #10234 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1000780
🔄 Запрос #10235 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1000886
🔄 Запрос #10236 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 1000977
🔄 Запрос #10237 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1001095
🔄 Запрос #10238 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1001208
🔄 Запрос #10239 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1001321
🔄 Запрос #10240 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 1001445
🔄 Запрос #10241 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1001560
🔄 Запрос #10242 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1001676
🔄 Запрос #10243 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1001775
🔄 Запрос #10244 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1001889
🔄 Запрос #10245 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1001997
🔄 Запрос #10246 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1002108
🔄 Запрос #10247 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1002225
🔄 Запрос #10248 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1002323
🔄 Запрос #10249 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1002429
🔄 Запрос #10250 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1002547
🔄 Запрос #10251 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1002649
🔄 Запрос #10252 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 71 спецификаций. Всего: 1002720
🔄 Запрос #10253 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1002819
🔄 Запрос #10254 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 139 спецификаций. Всего: 1002958
🔄 Запрос #10255 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 145 спецификаций. Всего: 1003103
🔄 Запрос #10256 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 153 спецификаций. Всего: 1003256
🔄 Запрос #10257 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 172 спецификаций. Всего: 1003428
🔄 Запрос #10258 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 183 спецификаций. Всего: 1003611
🔄 Запрос #10259 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 160 спецификаций. Всего: 1003771
🔄 Запрос #10260 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 126 спецификаций. Всего: 1003897
🔄 Запрос #10261 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1004012
🔄 Запрос #10262 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 1004136
🔄 Запрос #10263 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1004251
🔄 Запрос #10264 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1004347
🔄 Запрос #10265 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 93 спецификаций. Всего: 1004440
🔄 Запрос #10266 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1004526
🔄 Запрос #10267 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1004631
🔄 Запрос #10268 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1004748
🔄 Запрос #10269 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1004851
🔄 Запрос #10270 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1004949
🔄 Запрос #10271 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1005040
🔄 Запрос #10272 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1005128
🔄 Запрос #10273 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 83 спецификаций. Всего: 1005211
🔄 Запрос #10274 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 75 спецификаций. Всего: 1005286
🔄 Запрос #10275 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 1005370
🔄 Запрос #10276 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1005471
📤 Сохранено 10003 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #10277 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 95 спецификаций. Всего: 1005566
🔄 Запрос #10278 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1005684
🔄 Запрос #10279 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1005809
🔄 Запрос #10280 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1005928
🔄 Запрос #10281 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1006034
🔄 Запрос #10282 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1006142
🔄 Запрос #10283 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 95 спецификаций. Всего: 1006237
🔄 Запрос #10284 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1006334
🔄 Запрос #10285 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 127 спецификаций. Всего: 1006461
🔄 Запрос #10286 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1006555
🔄 Запрос #10287 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1006656
🔄 Запрос #10288 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 1006747
🔄 Запрос #10289 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1006839
🔄 Запрос #10290 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 93 спецификаций. Всего: 1006932
🔄 Запрос #10291 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 81 спецификаций. Всего: 1007013
🔄 Запрос #10292 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 1007099
🔄 Запрос #10293 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1007203
🔄 Запрос #10294 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 1007324
🔄 Запрос #10295 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 83 спецификаций. Всего: 1007407
🔄 Запрос #10296 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 142 спецификаций. Всего: 1007549

🔄 Запрос #10297 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 190 спецификаций. Всего: 1007739
🔄 Запрос #10298 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1007864
🔄 Запрос #10299 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 156 спецификаций. Всего: 1008020
🔄 Запрос #10300 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 142 спецификаций. Всего: 1008162
🔄 Запрос #10301 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 169 спецификаций. Всего: 1008331
🔄 Запрос #10302 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1008432
🔄 Запрос #10303 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1008557
🔄 Запрос #10304 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1008671
🔄 Запрос #10305 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 131 спецификаций. Всего: 1008802
🔄 Запрос #10306 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1008911
🔄 Запрос #10307 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1009031
🔄 Запрос #10308 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1009149
🔄 Запрос #10309 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1009261
🔄 Запрос #10310 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1009363
🔄 Запрос #10311 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1009479
🔄 Запрос #10312 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 1009563
🔄 Запрос #10313 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 83 спецификаций. Всего: 1009646
🔄 Запрос #10314 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 87 спецификаций. Всего: 1009733
🔄 Запрос #10315 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1009850
🔄 Запрос #10316 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1009942
🔄 Запрос #10317 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1010054
🔄 Запрос #10318 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1010163
🔄 Запрос #10319 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 131 спецификаций. Всего: 1010294
🔄 Запрос #10320 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1010395
🔄 Запрос #10321 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1010489
🔄 Запрос #10322 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1010604
🔄 Запрос #10323 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1010703
🔄 Запрос #10324 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1010805
🔄 Запрос #10325 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1010895
🔄 Запрос #10326 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1010989
🔄 Запрос #10327 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 82 спецификаций. Всего: 1011071
🔄 Запрос #10328 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1011160
🔄 Запрос #10329 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1011282
🔄 Запрос #10330 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1011394
🔄 Запрос #10331 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1011483
🔄 Запрос #10332 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1011584
🔄 Запрос #10333 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 140 спецификаций. Всего: 1011724
🔄 Запрос #10334 для 2024-07-18 20:44:09 - 2024-07-25 20:44:09
📥 Загружено 43 спецификаций. Всего: 1011767
📅 Обрабатываем диапазон 2024-07-11 20:44:09 - 2024-07-18 20:44:09 (попытка 1/5)
🔄 Запрос #10335 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1011872
🔄 Запрос #10336 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 163 спецификаций. Всего: 1012035
🔄 Запрос #10337 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 160 спецификаций. Всего: 1012195
🔄 Запрос #10338 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 143 спецификаций. Всего: 1012338
🔄 Запрос #10339 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 127 спецификаций. Всего: 1012465
🔄 Запрос #10340 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1012578
🔄 Запрос #10341 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1012694
🔄 Запрос #10342 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 1012785
🔄 Запрос #10343 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1012892
🔄 Запрос #10344 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1012988
🔄 Запрос #10345 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1013074
🔄 Запрос #10346 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1013183
🔄 Запрос #10347 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1013276
🔄 Запрос #10348 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1013395
🔄 Запрос #10349 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 79 спецификаций. Всего: 1013474
🔄 Запрос #10350 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1013582
🔄 Запрос #10351 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1013677
🔄 Запрос #10352 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1013790
🔄 Запрос #10353 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1013886
🔄 Запрос #10354 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 74 спецификаций. Всего: 1013960
🔄 Запрос #10355 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 133 спецификаций. Всего: 1014093
🔄 Запрос #10356 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1014190
🔄 Запрос #10357 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1014286
🔄 Запрос #10358 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1014400
🔄 Запрос #10359 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1014512
🔄 Запрос #10360 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1014617
🔄 Запрос #10361 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 1014709
🔄 Запрос #10362 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1014796
🔄 Запрос #10363 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 1014919
🔄 Запрос #10364 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1015044
🔄 Запрос #10365 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1015151
🔄 Запрос #10366 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 1015269
🔄 Запрос #10367 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1015371
🔄 Запрос #10368 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1015483
📤 Сохранено 10012 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #10369 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1015596
🔄 Запрос #10370 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1015692
🔄 Запрос #10371 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 94 спецификаций. Всего: 1015786
🔄 Запрос #10372 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1015876
🔄 Запрос #10373 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 145 спецификаций. Всего: 1016021
🔄 Запрос #10374 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 138 спецификаций. Всего: 1016159
🔄 Запрос #10375 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 124 спецификаций. Всего: 1016283
🔄 Запрос #10376 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 1016415
🔄 Запрос #10377 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1016529
🔄 Запрос #10378 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 1016655
🔄 Запрос #10379 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 1016776
🔄 Запрос #10380 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1016882
🔄 Запрос #10381 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1016979
🔄 Запрос #10382 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 1017094
🔄 Запрос #10383 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1017219
🔄 Запрос #10384 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1017314
🔄 Запрос #10385 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1017417
🔄 Запрос #10386 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1017513
🔄 Запрос #10387 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 94 спецификаций. Всего: 1017607
🔄 Запрос #10388 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 83 спецификаций. Всего: 1017690
🔄 Запрос #10389 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1017804
🔄 Запрос #10390 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 1017896
🔄 Запрос #10391 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 1018022
🔄 Запрос #10392 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1018118
🔄 Запрос #10393 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 84 спецификаций. Всего: 1018202
🔄 Запрос #10394 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 76 спецификаций. Всего: 1018278
🔄 Запрос #10395 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 88 спецификаций. Всего: 1018366
🔄 Запрос #10396 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 79 спецификаций. Всего: 1018445
🔄 Запрос #10397 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 64 спецификаций. Всего: 1018509
🔄 Запрос #10398 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1018621
🔄 Запрос #10399 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1018725
🔄 Запрос #10400 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1018818
🔄 Запрос #10401 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1018920
🔄 Запрос #10402 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1019027
🔄 Запрос #10403 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1019152
🔄 Запрос #10404 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1019254
🔄 Запрос #10405 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1019360
🔄 Запрос #10406 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 1019475
🔄 Запрос #10407 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1019571
🔄 Запрос #10408 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 82 спецификаций. Всего: 1019653
🔄 Запрос #10409 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1019765
🔄 Запрос #10410 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 1019888
🔄 Запрос #10411 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 76 спецификаций. Всего: 1019964
🔄 Запрос #10412 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1020062
🔄 Запрос #10413 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1020148
🔄 Запрос #10414 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 83 спецификаций. Всего: 1020231
🔄 Запрос #10415 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1020327
🔄 Запрос #10416 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1020428
🔄 Запрос #10417 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 62 спецификаций. Всего: 1020490
🔄 Запрос #10418 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 59 спецификаций. Всего: 1020549
🔄 Запрос #10419 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1020639
🔄 Запрос #10420 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1020740
🔄 Запрос #10421 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 146 спецификаций. Всего: 1020886
🔄 Запрос #10422 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1021016
🔄 Запрос #10423 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1021117
🔄 Запрос #10424 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 1021192
🔄 Запрос #10425 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1021294
🔄 Запрос #10426 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1021403
🔄 Запрос #10427 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1021508
🔄 Запрос #10428 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1021612
🔄 Запрос #10429 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1021719
🔄 Запрос #10430 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 94 спецификаций. Всего: 1021813
🔄 Запрос #10431 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1021910
🔄 Запрос #10432 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 94 спецификаций. Всего: 1022004
🔄 Запрос #10433 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 76 спецификаций. Всего: 1022080
🔄 Запрос #10434 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1022196
🔄 Запрос #10435 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 94 спецификаций. Всего: 1022290
🔄 Запрос #10436 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1022407
🔄 Запрос #10437 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 120 спецификаций. Всего: 1022527
🔄 Запрос #10438 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1022639
🔄 Запрос #10439 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1022747
🔄 Запрос #10440 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1022845
🔄 Запрос #10441 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1022934
🔄 Запрос #10442 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 1023009
🔄 Запрос #10443 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 72 спецификаций. Всего: 1023081
🔄 Запрос #10444 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09

📥 Загружено 90 спецификаций. Всего: 1023171
🔄 Запрос #10445 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1023287
🔄 Запрос #10446 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1023385
🔄 Запрос #10447 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1023497
🔄 Запрос #10448 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1023614
🔄 Запрос #10449 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1023727
🔄 Запрос #10450 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1023827
🔄 Запрос #10451 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1023928
🔄 Запрос #10452 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1024027
🔄 Запрос #10453 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 80 спецификаций. Всего: 1024107
🔄 Запрос #10454 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1024202
🔄 Запрос #10455 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1024315
🔄 Запрос #10456 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1024402
🔄 Запрос #10457 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1024508
🔄 Запрос #10458 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1024606
🔄 Запрос #10459 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 68 спецификаций. Всего: 1024674
🔄 Запрос #10460 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 55 спецификаций. Всего: 1024729
🔄 Запрос #10461 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 20 спецификаций. Всего: 1024749
🔄 Запрос #10462 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 67 спецификаций. Всего: 1024816
🔄 Запрос #10463 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1024930
🔄 Запрос #10464 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 1025053
🔄 Запрос #10465 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 85 спецификаций. Всего: 1025138
🔄 Запрос #10466 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 133 спецификаций. Всего: 1025271
🔄 Запрос #10467 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 1025389
🔄 Запрос #10468 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 1025515
📤 Сохранено 10032 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #10469 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1025628
🔄 Запрос #10470 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1025726
🔄 Запрос #10471 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 84 спецификаций. Всего: 1025810
🔄 Запрос #10472 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1025896
🔄 Запрос #10473 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1025992
🔄 Запрос #10474 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1026089
🔄 Запрос #10475 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1026199
🔄 Запрос #10476 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1026315
🔄 Запрос #10477 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1026411
🔄 Запрос #10478 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 1026502
🔄 Запрос #10479 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1026603
🔄 Запрос #10480 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 94 спецификаций. Всего: 1026697
🔄 Запрос #10481 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1026809
🔄 Запрос #10482 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 83 спецификаций. Всего: 1026892
🔄 Запрос #10483 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1026989
🔄 Запрос #10484 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 85 спецификаций. Всего: 1027074
🔄 Запрос #10485 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 47 спецификаций. Всего: 1027121
🔄 Запрос #10486 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 35 спецификаций. Всего: 1027156
🔄 Запрос #10487 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 59 спецификаций. Всего: 1027215
🔄 Запрос #10488 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 62 спецификаций. Всего: 1027277
🔄 Запрос #10489 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1027389
🔄 Запрос #10490 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1027478
🔄 Запрос #10491 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1027576
🔄 Запрос #10492 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 89 спецификаций. Всего: 1027665
🔄 Запрос #10493 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1027767
🔄 Запрос #10494 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1027862
🔄 Запрос #10495 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1027972
🔄 Запрос #10496 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1028059
🔄 Запрос #10497 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1028145
🔄 Запрос #10498 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 78 спецификаций. Всего: 1028223
🔄 Запрос #10499 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 1028298
🔄 Запрос #10500 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1028407
🔄 Запрос #10501 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1028513
🔄 Запрос #10502 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1028619
🔄 Запрос #10503 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1028724
🔄 Запрос #10504 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 1028816
🔄 Запрос #10505 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 61 спецификаций. Всего: 1028877
🔄 Запрос #10506 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 79 спецификаций. Всего: 1028956
🔄 Запрос #10507 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1029045
🔄 Запрос #10508 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 94 спецификаций. Всего: 1029139
🔄 Запрос #10509 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1029235
🔄 Запрос #10510 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 153 спецификаций. Всего: 1029388
🔄 Запрос #10511 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1029488
🔄 Запрос #10512 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 129 спецификаций. Всего: 1029617
🔄 Запрос #10513 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 163 спецификаций. Всего: 1029780
🔄 Запрос #10514 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 129 спецификаций. Всего: 1029909

🔄 Запрос #10515 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 140 спецификаций. Всего: 1030049
🔄 Запрос #10516 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 124 спецификаций. Всего: 1030173
🔄 Запрос #10517 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1030268
🔄 Запрос #10518 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1030369
🔄 Запрос #10519 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1030491
🔄 Запрос #10520 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1030608
🔄 Запрос #10521 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1030708
🔄 Запрос #10522 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 84 спецификаций. Всего: 1030792
🔄 Запрос #10523 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1030903
🔄 Запрос #10524 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1031008
🔄 Запрос #10525 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 84 спецификаций. Всего: 1031092
🔄 Запрос #10526 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 58 спецификаций. Всего: 1031150
🔄 Запрос #10527 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 78 спецификаций. Всего: 1031228
🔄 Запрос #10528 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 73 спецификаций. Всего: 1031301
🔄 Запрос #10529 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 70 спецификаций. Всего: 1031371
🔄 Запрос #10530 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 71 спецификаций. Всего: 1031442
🔄 Запрос #10531 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 51 спецификаций. Всего: 1031493
🔄 Запрос #10532 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 83 спецификаций. Всего: 1031576
🔄 Запрос #10533 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 50 спецификаций. Всего: 1031626
🔄 Запрос #10534 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 55 спецификаций. Всего: 1031681
🔄 Запрос #10535 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 1031799
🔄 Запрос #10536 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1031910
🔄 Запрос #10537 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1032032
🔄 Запрос #10538 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1032143
🔄 Запрос #10539 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1032242
🔄 Запрос #10540 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1032358
🔄 Запрос #10541 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1032460
🔄 Запрос #10542 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1032560
🔄 Запрос #10543 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 1032663
🔄 Запрос #10544 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1032770
🔄 Запрос #10545 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1032860
🔄 Запрос #10546 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1032960
🔄 Запрос #10547 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1033053
🔄 Запрос #10548 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 175 спецификаций. Всего: 1033228
🔄 Запрос #10549 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
📥 Загружено 140 спецификаций. Всего: 1033368
🔄 Запрос #10550 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 1033488
🔄 Запрос #10551 для 2024-07-11 20:44:09 - 2024-07-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1033590
📅 Обрабатываем диапазон 2024-07-04 20:44:09 - 2024-07-11 20:44:09 (попытка 1/5)
🔄 Запрос #10552 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 1033723
🔄 Запрос #10553 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 126 спецификаций. Всего: 1033849
🔄 Запрос #10554 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 1033974
🔄 Запрос #10555 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 1034092
🔄 Запрос #10556 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 1034191
🔄 Запрос #10557 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1034294
🔄 Запрос #10558 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1034402
🔄 Запрос #10559 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1034497
🔄 Запрос #10560 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1034610
🔄 Запрос #10561 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 1034726
🔄 Запрос #10562 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 1034847
🔄 Запрос #10563 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1034950
🔄 Запрос #10564 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 89 спецификаций. Всего: 1035039
🔄 Запрос #10565 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 1035139
🔄 Запрос #10566 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1035240
🔄 Запрос #10567 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 74 спецификаций. Всего: 1035314
🔄 Запрос #10568 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1035408
🔄 Запрос #10569 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1035503
🔄 Запрос #10570 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 79 спецификаций. Всего: 1035582
📤 Сохранено 10067 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #10571 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 81 спецификаций. Всего: 1035663
🔄 Запрос #10572 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 1035782
🔄 Запрос #10573 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 1035901
🔄 Запрос #10574 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1036011
🔄 Запрос #10575 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1036122
🔄 Запрос #10576 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 1036209
🔄 Запрос #10577 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1036310
🔄 Запрос #10578 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1036418
🔄 Запрос #10579 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1036512
🔄 Запрос #10580 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 1036611
🔄 Запрос #10581 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1036723
🔄 Запрос #10582 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 1036813
🔄 Запрос #10583 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1036906
🔄 Запрос #10584 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1037009
🔄 Запрос #10585 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1037107
🔄 Запрос #10586 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09

📥 Загружено 101 спецификаций. Всего: 1037208
🔄 Запрос #10587 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 69 спецификаций. Всего: 1037277
🔄 Запрос #10588 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 1037386
🔄 Запрос #10589 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 89 спецификаций. Всего: 1037475
🔄 Запрос #10590 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1037582
🔄 Запрос #10591 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 126 спецификаций. Всего: 1037708
🔄 Запрос #10592 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 126 спецификаций. Всего: 1037834
🔄 Запрос #10593 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 1037970
🔄 Запрос #10594 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 163 спецификаций. Всего: 1038133
🔄 Запрос #10595 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 149 спецификаций. Всего: 1038282
🔄 Запрос #10596 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 1038409
🔄 Запрос #10597 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 140 спецификаций. Всего: 1038549
🔄 Запрос #10598 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 1038677
🔄 Запрос #10599 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1038771
🔄 Запрос #10600 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1038875
🔄 Запрос #10601 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 1039010
🔄 Запрос #10602 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 1039130
🔄 Запрос #10603 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1039252
🔄 Запрос #10604 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 1039368
🔄 Запрос #10605 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1039478
🔄 Запрос #10606 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 1039600
🔄 Запрос #10607 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 1039733
🔄 Запрос #10608 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1039836
🔄 Запрос #10609 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1039937
🔄 Запрос #10610 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1040035
🔄 Запрос #10611 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1040133
🔄 Запрос #10612 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1040234
🔄 Запрос #10613 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 72 спецификаций. Всего: 1040306
🔄 Запрос #10614 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 66 спецификаций. Всего: 1040372
🔄 Запрос #10615 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1040478
🔄 Запрос #10616 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 150 спецификаций. Всего: 1040628
🔄 Запрос #10617 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 1040753
🔄 Запрос #10618 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 1040886
🔄 Запрос #10619 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 1041004
🔄 Запрос #10620 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1041131
🔄 Запрос #10621 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 1041251
🔄 Запрос #10622 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 1041366
🔄 Запрос #10623 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 1041494
🔄 Запрос #10624 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 149 спецификаций. Всего: 1041643
🔄 Запрос #10625 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 1041773
🔄 Запрос #10626 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 1041897
🔄 Запрос #10627 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1042003
🔄 Запрос #10628 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 1042102
🔄 Запрос #10629 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1042213
🔄 Запрос #10630 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 1042315
🔄 Запрос #10631 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 1042439
🔄 Запрос #10632 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1042549
🔄 Запрос #10633 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1042657
🔄 Запрос #10634 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 1042772
🔄 Запрос #10635 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1042878
🔄 Запрос #10636 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 142 спецификаций. Всего: 1043020
🔄 Запрос #10637 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1043130
🔄 Запрос #10638 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 1043253
🔄 Запрос #10639 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 152 спецификаций. Всего: 1043405
🔄 Запрос #10640 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 140 спецификаций. Всего: 1043545
🔄 Запрос #10641 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1043638
🔄 Запрос #10642 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1043736
🔄 Запрос #10643 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1043849
🔄 Запрос #10644 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 1043974
🔄 Запрос #10645 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 1044105
🔄 Запрос #10646 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 1044224
🔄 Запрос #10647 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1044340
🔄 Запрос #10648 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 141 спецификаций. Всего: 1044481
🔄 Запрос #10649 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 1044601
🔄 Запрос #10650 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 1044720
🔄 Запрос #10651 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 1044852
🔄 Запрос #10652 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 1044967
🔄 Запрос #10653 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 1045069
🔄 Запрос #10654 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1045181
🔄 Запрос #10655 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 89 спецификаций. Всего: 1045270
🔄 Запрос #10656 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 1045357
🔄 Запрос #10657 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 1045440
🔄 Запрос #10658 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 79 спецификаций. Всего: 1045519
🔄 Запрос #10659 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09

📥 Загружено 97 спецификаций. Всего: 1045616
📤 Сохранено 10034 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #10660 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1045711
🔄 Запрос #10661 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 1045827
🔄 Запрос #10662 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 77 спецификаций. Всего: 1045904
🔄 Запрос #10663 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1046015
🔄 Запрос #10664 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 1046114
🔄 Запрос #10665 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 66 спецификаций. Всего: 1046180
🔄 Запрос #10666 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1046278
🔄 Запрос #10667 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 1046403
🔄 Запрос #10668 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1046514
🔄 Запрос #10669 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1046625
🔄 Запрос #10670 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 1046764
🔄 Запрос #10671 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 141 спецификаций. Всего: 1046905
🔄 Запрос #10672 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1047016
🔄 Запрос #10673 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1047111
🔄 Запрос #10674 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1047204
🔄 Запрос #10675 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 1047289
🔄 Запрос #10676 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 1047385
🔄 Запрос #10677 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 1047470
🔄 Запрос #10678 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 1047587
🔄 Запрос #10679 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 35 спецификаций. Всего: 1047622
🔄 Запрос #10680 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1047732
🔄 Запрос #10681 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 178 спецификаций. Всего: 1047910
🔄 Запрос #10682 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 1048029
🔄 Запрос #10683 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 1048147
🔄 Запрос #10684 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 1048267
🔄 Запрос #10685 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 1048354
🔄 Запрос #10686 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 153 спецификаций. Всего: 1048507
🔄 Запрос #10687 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 1048589
🔄 Запрос #10688 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 1048710
🔄 Запрос #10689 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 146 спецификаций. Всего: 1048856
🔄 Запрос #10690 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 144 спецификаций. Всего: 1049000
🔄 Запрос #10691 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 74 спецификаций. Всего: 1049074
🔄 Запрос #10692 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 156 спецификаций. Всего: 1049230
🔄 Запрос #10693 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 1049353
🔄 Запрос #10694 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 1049478
🔄 Запрос #10695 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 1049599
🔄 Запрос #10696 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 1049730
🔄 Запрос #10697 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 1049850
🔄 Запрос #10698 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1049963
🔄 Запрос #10699 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1050056
🔄 Запрос #10700 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1050161
🔄 Запрос #10701 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 80 спецификаций. Всего: 1050241
🔄 Запрос #10702 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 1050338
🔄 Запрос #10703 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1050445
🔄 Запрос #10704 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1050558
🔄 Запрос #10705 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 1050657
🔄 Запрос #10706 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1050750
🔄 Запрос #10707 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 1050840
🔄 Запрос #10708 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 69 спецификаций. Всего: 1050909
🔄 Запрос #10709 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1051010
🔄 Запрос #10710 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 1051100
🔄 Запрос #10711 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1051204
🔄 Запрос #10712 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1051312
🔄 Запрос #10713 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1051416
🔄 Запрос #10714 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1051523
🔄 Запрос #10715 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1051628
🔄 Запрос #10716 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1051738
🔄 Запрос #10717 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1051844
🔄 Запрос #10718 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1051950
🔄 Запрос #10719 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1052061
🔄 Запрос #10720 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 84 спецификаций. Всего: 1052145
🔄 Запрос #10721 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1052253
🔄 Запрос #10722 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1052354
🔄 Запрос #10723 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1052457
🔄 Запрос #10724 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 1052585
🔄 Запрос #10725 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 1052682
🔄 Запрос #10726 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 1052765
🔄 Запрос #10727 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 1052851
🔄 Запрос #10728 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 160 спецификаций. Всего: 1053011

🔄 Запрос #10729 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 1053140
🔄 Запрос #10730 для 2024-07-04 20:44:09 - 2024-07-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 1053223
📅 Обрабатываем диапазон 2024-06-27 20:44:09 - 2024-07-04 20:44:09 (попытка 1/5)
🔄 Запрос #10731 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 69 спецификаций. Всего: 1053292
🔄 Запрос #10732 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 1053409
🔄 Запрос #10733 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 135 спецификаций. Всего: 1053544
🔄 Запрос #10734 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 136 спецификаций. Всего: 1053680
🔄 Запрос #10735 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 1053775
🔄 Запрос #10736 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1053879
🔄 Запрос #10737 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 1053966
🔄 Запрос #10738 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 1054083
🔄 Запрос #10739 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 1054206
🔄 Запрос #10740 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1054302
🔄 Запрос #10741 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 100 спецификаций. Всего: 1054402
🔄 Запрос #10742 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1054514
🔄 Запрос #10743 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1054620
🔄 Запрос #10744 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1054725
🔄 Запрос #10745 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 1054842
🔄 Запрос #10746 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 1054942
🔄 Запрос #10747 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1055056
🔄 Запрос #10748 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 130 спецификаций. Всего: 1055186
🔄 Запрос #10749 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1055282
🔄 Запрос #10750 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1055381
🔄 Запрос #10751 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1055491
🔄 Запрос #10752 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1055603
🔄 Запрос #10753 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 76 спецификаций. Всего: 1055679
📤 Сохранено 10063 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #10754 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 1055765
🔄 Запрос #10755 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 66 спецификаций. Всего: 1055831
🔄 Запрос #10756 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 41 спецификаций. Всего: 1055872
🔄 Запрос #10757 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 68 спецификаций. Всего: 1055940
🔄 Запрос #10758 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 1056064
🔄 Запрос #10759 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 1056182
🔄 Запрос #10760 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 90 спецификаций. Всего: 1056272
🔄 Запрос #10761 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 83 спецификаций. Всего: 1056355
🔄 Запрос #10762 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1056470
🔄 Запрос #10763 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 1056577
🔄 Запрос #10764 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 99 спецификаций. Всего: 1056676
🔄 Запрос #10765 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1056775
🔄 Запрос #10766 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 1056869
🔄 Запрос #10767 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1056967
🔄 Запрос #10768 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1057079
🔄 Запрос #10769 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1057187
🔄 Запрос #10770 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 92 спецификаций. Всего: 1057279
🔄 Запрос #10771 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 90 спецификаций. Всего: 1057369
🔄 Запрос #10772 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 83 спецификаций. Всего: 1057452
🔄 Запрос #10773 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1057545
🔄 Запрос #10774 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 1057639
🔄 Запрос #10775 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1057751
🔄 Запрос #10776 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1057856
🔄 Запрос #10777 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1057955
🔄 Запрос #10778 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1058069
🔄 Запрос #10779 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 81 спецификаций. Всего: 1058150
🔄 Запрос #10780 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 81 спецификаций. Всего: 1058231
🔄 Запрос #10781 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 143 спецификаций. Всего: 1058374
🔄 Запрос #10782 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 135 спецификаций. Всего: 1058509
🔄 Запрос #10783 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 130 спецификаций. Всего: 1058639
🔄 Запрос #10784 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 125 спецификаций. Всего: 1058764
🔄 Запрос #10785 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 157 спецификаций. Всего: 1058921
🔄 Запрос #10786 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 135 спецификаций. Всего: 1059056
🔄 Запрос #10787 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 146 спецификаций. Всего: 1059202
🔄 Запрос #10788 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 129 спецификаций. Всего: 1059331
🔄 Запрос #10789 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1059446
🔄 Запрос #10790 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1059557
🔄 Запрос #10791 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1059668
🔄 Запрос #10792 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 1059759
🔄 Запрос #10793 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 1059853
🔄 Запрос #10794 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1059951
🔄 Запрос #10795 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 1060070
🔄 Запрос #10796 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 1060193
🔄 Запрос #10797 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 1060300
🔄 Запрос #10798 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1060414

🔄 Запрос #10799 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1060527
🔄 Запрос #10800 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1060643
🔄 Запрос #10801 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 92 спецификаций. Всего: 1060735
🔄 Запрос #10802 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 1060832
🔄 Запрос #10803 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1060940
🔄 Запрос #10804 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 1061031
🔄 Запрос #10805 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 1061120
🔄 Запрос #10806 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1061231
🔄 Запрос #10807 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 1061319
🔄 Запрос #10808 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 80 спецификаций. Всего: 1061399
🔄 Запрос #10809 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 83 спецификаций. Всего: 1061482
🔄 Запрос #10810 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 1061577
🔄 Запрос #10811 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1061675
🔄 Запрос #10812 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1061774
🔄 Запрос #10813 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 90 спецификаций. Всего: 1061864
🔄 Запрос #10814 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 1061959
🔄 Запрос #10815 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1062052
🔄 Запрос #10816 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1062158
🔄 Запрос #10817 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1062271
🔄 Запрос #10818 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 80 спецификаций. Всего: 1062351
🔄 Запрос #10819 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1062459
🔄 Запрос #10820 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 1062546
🔄 Запрос #10821 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 1062647
🔄 Запрос #10822 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 1062747
🔄 Запрос #10823 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 1062857
🔄 Запрос #10824 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1062961
🔄 Запрос #10825 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1063060
🔄 Запрос #10826 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 1063187
🔄 Запрос #10827 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 128 спецификаций. Всего: 1063315
🔄 Запрос #10828 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 76 спецификаций. Всего: 1063391
🔄 Запрос #10829 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1063496
🔄 Запрос #10830 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 90 спецификаций. Всего: 1063586
🔄 Запрос #10831 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 80 спецификаций. Всего: 1063666
🔄 Запрос #10832 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 1063790
🔄 Запрос #10833 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1063911
🔄 Запрос #10834 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1064026
🔄 Запрос #10835 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1064130
🔄 Запрос #10836 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1064243
🔄 Запрос #10837 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1064347
🔄 Запрос #10838 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 1064454
🔄 Запрос #10839 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1064559
🔄 Запрос #10840 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1064655
🔄 Запрос #10841 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 1064746
🔄 Запрос #10842 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 82 спецификаций. Всего: 1064828
🔄 Запрос #10843 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 1064917
🔄 Запрос #10844 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1065025
🔄 Запрос #10845 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1065146
🔄 Запрос #10846 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 1065234
🔄 Запрос #10847 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 83 спецификаций. Всего: 1065317
🔄 Запрос #10848 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1065423
🔄 Запрос #10849 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1065535
🔄 Запрос #10850 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 1065637
🔄 Запрос #10851 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1065733
📤 Сохранено 10054 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #10852 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1065829
🔄 Запрос #10853 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1065917
🔄 Запрос #10854 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 69 спецификаций. Всего: 1065986
🔄 Запрос #10855 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 57 спецификаций. Всего: 1066043
🔄 Запрос #10856 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 1066132
🔄 Запрос #10857 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 1066223
🔄 Запрос #10858 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 1066311
🔄 Запрос #10859 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 84 спецификаций. Всего: 1066395
🔄 Запрос #10860 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 90 спецификаций. Всего: 1066485
🔄 Запрос #10861 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1066598
🔄 Запрос #10862 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 131 спецификаций. Всего: 1066729
🔄 Запрос #10863 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1066841
🔄 Запрос #10864 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1066952
🔄 Запрос #10865 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 1067073
🔄 Запрос #10866 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1067194
🔄 Запрос #10867 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1067300
🔄 Запрос #10868 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1067411
🔄 Запрос #10869 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 1067533
🔄 Запрос #10870 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09

📥 Загружено 114 спецификаций. Всего: 1067647
🔄 Запрос #10871 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 125 спецификаций. Всего: 1067772
🔄 Запрос #10872 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1067871
🔄 Запрос #10873 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1067970
🔄 Запрос #10874 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1068075
🔄 Запрос #10875 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 45 спецификаций. Всего: 1068120
🔄 Запрос #10876 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1068218
🔄 Запрос #10877 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 70 спецификаций. Всего: 1068288
🔄 Запрос #10878 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 1068415
🔄 Запрос #10879 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1068528
🔄 Запрос #10880 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 132 спецификаций. Всего: 1068660
🔄 Запрос #10881 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 139 спецификаций. Всего: 1068799
🔄 Запрос #10882 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 166 спецификаций. Всего: 1068965
🔄 Запрос #10883 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 140 спецификаций. Всего: 1069105
🔄 Запрос #10884 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 1069228
🔄 Запрос #10885 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 1069347
🔄 Запрос #10886 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 1069466
🔄 Запрос #10887 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1069582
🔄 Запрос #10888 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1069678
🔄 Запрос #10889 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1069774
🔄 Запрос #10890 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1069870
🔄 Запрос #10891 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 71 спецификаций. Всего: 1069941
🔄 Запрос #10892 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 67 спецификаций. Всего: 1070008
🔄 Запрос #10893 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 83 спецификаций. Всего: 1070091
🔄 Запрос #10894 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 1070182
🔄 Запрос #10895 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 90 спецификаций. Всего: 1070272
🔄 Запрос #10896 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 1070367
🔄 Запрос #10897 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 79 спецификаций. Всего: 1070446
🔄 Запрос #10898 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 74 спецификаций. Всего: 1070520
🔄 Запрос #10899 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 1070615
🔄 Запрос #10900 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1070708
🔄 Запрос #10901 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 72 спецификаций. Всего: 1070780
🔄 Запрос #10902 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 1070868
🔄 Запрос #10903 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1070967
🔄 Запрос #10904 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1071073
🔄 Запрос #10905 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 1071168
🔄 Запрос #10906 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1071267
🔄 Запрос #10907 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 63 спецификаций. Всего: 1071330
🔄 Запрос #10908 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 1071417
🔄 Запрос #10909 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1071525
🔄 Запрос #10910 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1071630
🔄 Запрос #10911 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1071742
🔄 Запрос #10912 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 1071833
🔄 Запрос #10913 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 1071920
🔄 Запрос #10914 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 1072007
🔄 Запрос #10915 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 1072095
🔄 Запрос #10916 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 1072184
🔄 Запрос #10917 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 82 спецификаций. Всего: 1072266
🔄 Запрос #10918 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 1072354
🔄 Запрос #10919 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1072465
🔄 Запрос #10920 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1072581
🔄 Запрос #10921 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1072680
🔄 Запрос #10922 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 128 спецификаций. Всего: 1072808
🔄 Запрос #10923 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 72 спецификаций. Всего: 1072880
🔄 Запрос #10924 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 48 спецификаций. Всего: 1072928
🔄 Запрос #10925 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1073044
🔄 Запрос #10926 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1073140
🔄 Запрос #10927 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 134 спецификаций. Всего: 1073274
🔄 Запрос #10928 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 28 спецификаций. Всего: 1073302
🔄 Запрос #10929 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 1073389
🔄 Запрос #10930 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 1073483
🔄 Запрос #10931 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1073597
🔄 Запрос #10932 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 1073684
🔄 Запрос #10933 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 1073810
🔄 Запрос #10934 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1073916
🔄 Запрос #10935 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 92 спецификаций. Всего: 1074008
🔄 Запрос #10936 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 68 спецификаций. Всего: 1074076
🔄 Запрос #10937 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 1074163
🔄 Запрос #10938 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 1074252
🔄 Запрос #10939 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1074358
🔄 Запрос #10940 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1074451
🔄 Запрос #10941 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 77 спецификаций. Всего: 1074528
🔄 Запрос #10942 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 92 спецификаций. Всего: 1074620
🔄 Запрос #10943 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 70 спецификаций. Всего: 1074690
🔄 Запрос #10944 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 69 спецификаций. Всего: 1074759
🔄 Запрос #10945 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09

📥 Загружено 59 спецификаций. Всего: 1074818
🔄 Запрос #10946 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 44 спецификаций. Всего: 1074862
🔄 Запрос #10947 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 45 спецификаций. Всего: 1074907
🔄 Запрос #10948 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 23 спецификаций. Всего: 1074930
🔄 Запрос #10949 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 35 спецификаций. Всего: 1074965
🔄 Запрос #10950 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 1075059
🔄 Запрос #10951 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 68 спецификаций. Всего: 1075127
🔄 Запрос #10952 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 78 спецификаций. Всего: 1075205
🔄 Запрос #10953 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 62 спецификаций. Всего: 1075267
🔄 Запрос #10954 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 64 спецификаций. Всего: 1075331
🔄 Запрос #10955 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 67 спецификаций. Всего: 1075398
🔄 Запрос #10956 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 81 спецификаций. Всего: 1075479
🔄 Запрос #10957 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 80 спецификаций. Всего: 1075559
🔄 Запрос #10958 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 76 спецификаций. Всего: 1075635
🔄 Запрос #10959 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 71 спецификаций. Всего: 1075706
🔄 Запрос #10960 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 70 спецификаций. Всего: 1075776
📤 Сохранено 10043 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #10961 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 64 спецификаций. Всего: 1075840
🔄 Запрос #10962 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 1075928
🔄 Запрос #10963 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 1076014
🔄 Запрос #10964 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 83 спецификаций. Всего: 1076097
🔄 Запрос #10965 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1076203
🔄 Запрос #10966 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1076304
🔄 Запрос #10967 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 73 спецификаций. Всего: 1076377
🔄 Запрос #10968 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1076492
🔄 Запрос #10969 для 2024-06-27 20:44:09 - 2024-07-04 20:44:09
📥 Загружено 46 спецификаций. Всего: 1076538
📅 Обрабатываем диапазон 2024-06-20 20:44:09 - 2024-06-27 20:44:09 (попытка 1/5)
🔄 Запрос #10970 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 76 спецификаций. Всего: 1076614
🔄 Запрос #10971 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 94 спецификаций. Всего: 1076708
🔄 Запрос #10972 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 84 спецификаций. Всего: 1076792
🔄 Запрос #10973 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 143 спецификаций. Всего: 1076935
🔄 Запрос #10974 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 127 спецификаций. Всего: 1077062
🔄 Запрос #10975 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 134 спецификаций. Всего: 1077196
🔄 Запрос #10976 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 111 спецификаций. Всего: 1077307
🔄 Запрос #10977 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 96 спецификаций. Всего: 1077403
🔄 Запрос #10978 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 109 спецификаций. Всего: 1077512
🔄 Запрос #10979 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 105 спецификаций. Всего: 1077617
🔄 Запрос #10980 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 104 спецификаций. Всего: 1077721
🔄 Запрос #10981 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 123 спецификаций. Всего: 1077844
🔄 Запрос #10982 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 119 спецификаций. Всего: 1077963
🔄 Запрос #10983 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 89 спецификаций. Всего: 1078052
🔄 Запрос #10984 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 102 спецификаций. Всего: 1078154
🔄 Запрос #10985 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 73 спецификаций. Всего: 1078227
🔄 Запрос #10986 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 74 спецификаций. Всего: 1078301
🔄 Запрос #10987 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 98 спецификаций. Всего: 1078399
🔄 Запрос #10988 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 87 спецификаций. Всего: 1078486
🔄 Запрос #10989 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 53 спецификаций. Всего: 1078539
🔄 Запрос #10990 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 76 спецификаций. Всего: 1078615
🔄 Запрос #10991 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 43 спецификаций. Всего: 1078658
🔄 Запрос #10992 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 70 спецификаций. Всего: 1078728
🔄 Запрос #10993 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 1078827
🔄 Запрос #10994 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 87 спецификаций. Всего: 1078914
🔄 Запрос #10995 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 98 спецификаций. Всего: 1079012
🔄 Запрос #10996 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 106 спецификаций. Всего: 1079118
🔄 Запрос #10997 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 61 спецификаций. Всего: 1079179
🔄 Запрос #10998 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 80 спецификаций. Всего: 1079259
🔄 Запрос #10999 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 93 спецификаций. Всего: 1079352
🔄 Запрос #11000 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 80 спецификаций. Всего: 1079432
🔄 Запрос #11001 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 80 спецификаций. Всего: 1079512
🔄 Запрос #11002 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 103 спецификаций. Всего: 1079615
🔄 Запрос #11003 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 97 спецификаций. Всего: 1079712
🔄 Запрос #11004 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 1079811
🔄 Запрос #11005 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 108 спецификаций. Всего: 1079919
🔄 Запрос #11006 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 90 спецификаций. Всего: 1080009
🔄 Запрос #11007 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 111 спецификаций. Всего: 1080120
🔄 Запрос #11008 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 143 спецификаций. Всего: 1080263
🔄 Запрос #11009 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 101 спецификаций. Всего: 1080364
🔄 Запрос #11010 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 151 спецификаций. Всего: 1080515
🔄 Запрос #11011 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 61 спецификаций. Всего: 1080576
🔄 Запрос #11012 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 92 спецификаций. Всего: 1080668
🔄 Запрос #11013 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 83 спецификаций. Всего: 1080751
🔄 Запрос #11014 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 157 спецификаций. Всего: 1080908
🔄 Запрос #11015 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 121 спецификаций. Всего: 1081029
🔄 Запрос #11016 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 139 спецификаций. Всего: 1081168
🔄 Запрос #11017 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 125 спецификаций. Всего: 1081293
🔄 Запрос #11018 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 108 спецификаций. Всего: 1081401
🔄 Запрос #11019 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 109 спецификаций. Всего: 1081510
🔄 Запрос #11020 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 128 спецификаций. Всего: 1081638
🔄 Запрос #11021 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 133 спецификаций. Всего: 1081771
🔄 Запрос #11022 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 125 спецификаций. Всего: 1081896
🔄 Запрос #11023 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 112 спецификаций. Всего: 1082008
🔄 Запрос #11024 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 106 спецификаций. Всего: 1082114
🔄 Запрос #11025 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 101 спецификаций. Всего: 1082215
🔄 Запрос #11026 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 91 спецификаций. Всего: 1082306
🔄 Запрос #11027 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 96 спецификаций. Всего: 1082402
🔄 Запрос #11028 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 91 спецификаций. Всего: 1082493
🔄 Запрос #11029 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 80 спецификаций. Всего: 1082573
🔄 Запрос #11030 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 79 спецификаций. Всего: 1082652
🔄 Запрос #11031 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 73 спецификаций. Всего: 1082725
🔄 Запрос #11032 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 1082809
🔄 Запрос #11033 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 83 спецификаций. Всего: 1082892
🔄 Запрос #11034 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 100 спецификаций. Всего: 1082992
🔄 Запрос #11035 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 110 спецификаций. Всего: 1083102
🔄 Запрос #11036 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 119 спецификаций. Всего: 1083221
🔄 Запрос #11037 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 103 спецификаций. Всего: 1083324
🔄 Запрос #11038 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 97 спецификаций. Всего: 1083421
🔄 Запрос #11039 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 67 спецификаций. Всего: 1083488
🔄 Запрос #11040 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 72 спецификаций. Всего: 1083560
🔄 Запрос #11041 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 106 спецификаций. Всего: 1083666
🔄 Запрос #11042 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 100 спецификаций. Всего: 1083766
🔄 Запрос #11043 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 110 спецификаций. Всего: 1083876
🔄 Запрос #11044 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 64 спецификаций. Всего: 1083940
🔄 Запрос #11045 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 90 спецификаций. Всего: 1084030
🔄 Запрос #11046 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 90 спецификаций. Всего: 1084120
🔄 Запрос #11047 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 84 спецификаций. Всего: 1084204
🔄 Запрос #11048 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 98 спецификаций. Всего: 1084302
🔄 Запрос #11049 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 71 спецификаций. Всего: 1084373
🔄 Запрос #11050 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 91 спецификаций. Всего: 1084464
🔄 Запрос #11051 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 74 спецификаций. Всего: 1084538
🔄 Запрос #11052 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 125 спецификаций. Всего: 1084663
🔄 Запрос #11053 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 115 спецификаций. Всего: 1084778
🔄 Запрос #11054 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 117 спецификаций. Всего: 1084895
🔄 Запрос #11055 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 128 спецификаций. Всего: 1085023
🔄 Запрос #11056 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 118 спецификаций. Всего: 1085141
🔄 Запрос #11057 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 109 спецификаций. Всего: 1085250
🔄 Запрос #11058 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 119 спецификаций. Всего: 1085369
🔄 Запрос #11059 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 109 спецификаций. Всего: 1085478
🔄 Запрос #11060 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 105 спецификаций. Всего: 1085583
🔄 Запрос #11061 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 101 спецификаций. Всего: 1085684
🔄 Запрос #11062 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 111 спецификаций. Всего: 1085795
📤 Сохранено 10019 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #11063 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 100 спецификаций. Всего: 1085895
🔄 Запрос #11064 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 95 спецификаций. Всего: 1085990
🔄 Запрос #11065 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 1086093
🔄 Запрос #11066 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 94 спецификаций. Всего: 1086187
🔄 Запрос #11067 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 132 спецификаций. Всего: 1086319
🔄 Запрос #11068 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 103 спецификаций. Всего: 1086422
🔄 Запрос #11069 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 105 спецификаций. Всего: 1086527
🔄 Запрос #11070 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 104 спецификаций. Всего: 1086631
🔄 Запрос #11071 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 94 спецификаций. Всего: 1086725
🔄 Запрос #11072 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 100 спецификаций. Всего: 1086825
🔄 Запрос #11073 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 85 спецификаций. Всего: 1086910
🔄 Запрос #11074 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 1087009
🔄 Запрос #11075 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 87 спецификаций. Всего: 1087096
🔄 Запрос #11076 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 123 спецификаций. Всего: 1087219
🔄 Запрос #11077 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 104 спецификаций. Всего: 1087323
🔄 Запрос #11078 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 74 спецификаций. Всего: 1087397
🔄 Запрос #11079 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 88 спецификаций. Всего: 1087485
🔄 Запрос #11080 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 112 спецификаций. Всего: 1087597
🔄 Запрос #11081 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 111 спецификаций. Всего: 1087708
🔄 Запрос #11082 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 95 спецификаций. Всего: 1087803
🔄 Запрос #11083 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09

📥 Загружено 88 спецификаций. Всего: 1087891
🔄 Запрос #11084 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 103 спецификаций. Всего: 1087994
🔄 Запрос #11085 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 101 спецификаций. Всего: 1088095
🔄 Запрос #11086 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 117 спецификаций. Всего: 1088212
🔄 Запрос #11087 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 106 спецификаций. Всего: 1088318
🔄 Запрос #11088 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 105 спецификаций. Всего: 1088423
🔄 Запрос #11089 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 128 спецификаций. Всего: 1088551
🔄 Запрос #11090 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 99 спецификаций. Всего: 1088650
🔄 Запрос #11091 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 83 спецификаций. Всего: 1088733
🔄 Запрос #11092 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 109 спецификаций. Всего: 1088842
🔄 Запрос #11093 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 111 спецификаций. Всего: 1088953
🔄 Запрос #11094 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 101 спецификаций. Всего: 1089054
🔄 Запрос #11095 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 136 спецификаций. Всего: 1089190
🔄 Запрос #11096 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 39 спецификаций. Всего: 1089229
🔄 Запрос #11097 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 0 спецификаций. Всего: 1089229
🔄 Запрос #11098 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 0 спецификаций. Всего: 1089229
🔄 Запрос #11099 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 1 спецификаций. Всего: 1089230
🔄 Запрос #11100 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 0 спецификаций. Всего: 1089230
🔄 Запрос #11101 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 0 спецификаций. Всего: 1089230
🔄 Запрос #11102 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 38 спецификаций. Всего: 1089268
🔄 Запрос #11103 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 101 спецификаций. Всего: 1089369
🔄 Запрос #11104 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 82 спецификаций. Всего: 1089451
🔄 Запрос #11105 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 131 спецификаций. Всего: 1089582
🔄 Запрос #11106 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 137 спецификаций. Всего: 1089719
🔄 Запрос #11107 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 120 спецификаций. Всего: 1089839
🔄 Запрос #11108 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 94 спецификаций. Всего: 1089933
🔄 Запрос #11109 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 137 спецификаций. Всего: 1090070
🔄 Запрос #11110 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 122 спецификаций. Всего: 1090192
🔄 Запрос #11111 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 116 спецификаций. Всего: 1090308
🔄 Запрос #11112 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 106 спецификаций. Всего: 1090414
🔄 Запрос #11113 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 103 спецификаций. Всего: 1090517
🔄 Запрос #11114 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 77 спецификаций. Всего: 1090594
🔄 Запрос #11115 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 87 спецификаций. Всего: 1090681
🔄 Запрос #11116 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 85 спецификаций. Всего: 1090766
🔄 Запрос #11117 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 78 спецификаций. Всего: 1090844
🔄 Запрос #11118 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 90 спецификаций. Всего: 1090934
🔄 Запрос #11119 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 77 спецификаций. Всего: 1091011
🔄 Запрос #11120 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 85 спецификаций. Всего: 1091096
🔄 Запрос #11121 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 75 спецификаций. Всего: 1091171
🔄 Запрос #11122 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 107 спецификаций. Всего: 1091278
🔄 Запрос #11123 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 92 спецификаций. Всего: 1091370
🔄 Запрос #11124 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 83 спецификаций. Всего: 1091453
🔄 Запрос #11125 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 81 спецификаций. Всего: 1091534
🔄 Запрос #11126 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 52 спецификаций. Всего: 1091586
🔄 Запрос #11127 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 89 спецификаций. Всего: 1091675
🔄 Запрос #11128 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 96 спецификаций. Всего: 1091771
🔄 Запрос #11129 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 117 спецификаций. Всего: 1091888
🔄 Запрос #11130 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 90 спецификаций. Всего: 1091978
🔄 Запрос #11131 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 99 спецификаций. Всего: 1092077
🔄 Запрос #11132 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 120 спецификаций. Всего: 1092197
🔄 Запрос #11133 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 121 спецификаций. Всего: 1092318
🔄 Запрос #11134 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 85 спецификаций. Всего: 1092403
🔄 Запрос #11135 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 96 спецификаций. Всего: 1092499
🔄 Запрос #11136 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 87 спецификаций. Всего: 1092586
🔄 Запрос #11137 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 90 спецификаций. Всего: 1092676
🔄 Запрос #11138 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 85 спецификаций. Всего: 1092761
🔄 Запрос #11139 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 92 спецификаций. Всего: 1092853
🔄 Запрос #11140 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1092946
🔄 Запрос #11141 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 95 спецификаций. Всего: 1093041
🔄 Запрос #11142 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 111 спецификаций. Всего: 1093152
🔄 Запрос #11143 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 95 спецификаций. Всего: 1093247
🔄 Запрос #11144 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 116 спецификаций. Всего: 1093363
🔄 Запрос #11145 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 89 спецификаций. Всего: 1093452
🔄 Запрос #11146 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 105 спецификаций. Всего: 1093557
🔄 Запрос #11147 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 63 спецификаций. Всего: 1093620
🔄 Запрос #11148 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 61 спецификаций. Всего: 1093681
🔄 Запрос #11149 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 51 спецификаций. Всего: 1093732
🔄 Запрос #11150 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 54 спецификаций. Всего: 1093786
🔄 Запрос #11151 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 104 спецификаций. Всего: 1093890
🔄 Запрос #11152 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 69 спецификаций. Всего: 1093959
🔄 Запрос #11153 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 134 спецификаций. Всего: 1094093
🔄 Запрос #11154 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 78 спецификаций. Всего: 1094171
🔄 Запрос #11155 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 91 спецификаций. Всего: 1094262
🔄 Запрос #11156 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 133 спецификаций. Всего: 1094395
🔄 Запрос #11157 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 118 спецификаций. Всего: 1094513
🔄 Запрос #11158 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09

📥 Загружено 135 спецификаций. Всего: 1094648
🔄 Запрос #11159 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 97 спецификаций. Всего: 1094745
🔄 Запрос #11160 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 82 спецификаций. Всего: 1094827
🔄 Запрос #11161 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 68 спецификаций. Всего: 1094895
🔄 Запрос #11162 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 76 спецификаций. Всего: 1094971
🔄 Запрос #11163 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 83 спецификаций. Всего: 1095054
🔄 Запрос #11164 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 63 спецификаций. Всего: 1095117
🔄 Запрос #11165 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 75 спецификаций. Всего: 1095192
🔄 Запрос #11166 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 63 спецификаций. Всего: 1095255
🔄 Запрос #11167 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 82 спецификаций. Всего: 1095337
🔄 Запрос #11168 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 74 спецификаций. Всего: 1095411
🔄 Запрос #11169 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 82 спецификаций. Всего: 1095493
🔄 Запрос #11170 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 69 спецификаций. Всего: 1095562
🔄 Запрос #11171 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 70 спецификаций. Всего: 1095632
🔄 Запрос #11172 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 86 спецификаций. Всего: 1095718
🔄 Запрос #11173 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 60 спецификаций. Всего: 1095778
🔄 Запрос #11174 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 66 спецификаций. Всего: 1095844
📤 Сохранено 10049 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #11175 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 63 спецификаций. Всего: 1095907
🔄 Запрос #11176 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 67 спецификаций. Всего: 1095974
🔄 Запрос #11177 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 80 спецификаций. Всего: 1096054
🔄 Запрос #11178 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 93 спецификаций. Всего: 1096147
🔄 Запрос #11179 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 78 спецификаций. Всего: 1096225
🔄 Запрос #11180 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 84 спецификаций. Всего: 1096309
🔄 Запрос #11181 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 96 спецификаций. Всего: 1096405
🔄 Запрос #11182 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 96 спецификаций. Всего: 1096501
🔄 Запрос #11183 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 116 спецификаций. Всего: 1096617
🔄 Запрос #11184 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 93 спецификаций. Всего: 1096710
🔄 Запрос #11185 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 103 спецификаций. Всего: 1096813
🔄 Запрос #11186 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 99 спецификаций. Всего: 1096912
🔄 Запрос #11187 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 103 спецификаций. Всего: 1097015
🔄 Запрос #11188 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 100 спецификаций. Всего: 1097115
🔄 Запрос #11189 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 104 спецификаций. Всего: 1097219
🔄 Запрос #11190 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 99 спецификаций. Всего: 1097318
🔄 Запрос #11191 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 111 спецификаций. Всего: 1097429
🔄 Запрос #11192 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 108 спецификаций. Всего: 1097537
🔄 Запрос #11193 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 139 спецификаций. Всего: 1097676
🔄 Запрос #11194 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 99 спецификаций. Всего: 1097775
🔄 Запрос #11195 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 86 спецификаций. Всего: 1097861
🔄 Запрос #11196 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 93 спецификаций. Всего: 1097954
🔄 Запрос #11197 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 149 спецификаций. Всего: 1098103
🔄 Запрос #11198 для 2024-06-20 20:44:09 - 2024-06-27 20:44:09
📥 Загружено 44 спецификаций. Всего: 1098147
📅 Обрабатываем диапазон 2024-06-13 20:44:09 - 2024-06-20 20:44:09 (попытка 1/5)
🔄 Запрос #11199 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 88 спецификаций. Всего: 1098235
🔄 Запрос #11200 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 117 спецификаций. Всего: 1098352
🔄 Запрос #11201 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 138 спецификаций. Всего: 1098490
🔄 Запрос #11202 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 137 спецификаций. Всего: 1098627
🔄 Запрос #11203 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 135 спецификаций. Всего: 1098762
🔄 Запрос #11204 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 133 спецификаций. Всего: 1098895
🔄 Запрос #11205 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 112 спецификаций. Всего: 1099007
🔄 Запрос #11206 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 92 спецификаций. Всего: 1099099
🔄 Запрос #11207 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 90 спецификаций. Всего: 1099189
🔄 Запрос #11208 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 107 спецификаций. Всего: 1099296
🔄 Запрос #11209 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 97 спецификаций. Всего: 1099393
🔄 Запрос #11210 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 88 спецификаций. Всего: 1099481
🔄 Запрос #11211 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 92 спецификаций. Всего: 1099573
🔄 Запрос #11212 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 87 спецификаций. Всего: 1099660
🔄 Запрос #11213 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 111 спецификаций. Всего: 1099771
🔄 Запрос #11214 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 117 спецификаций. Всего: 1099888
🔄 Запрос #11215 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 86 спецификаций. Всего: 1099974
🔄 Запрос #11216 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 90 спецификаций. Всего: 1100064
🔄 Запрос #11217 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 81 спецификаций. Всего: 1100145
🔄 Запрос #11218 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 77 спецификаций. Всего: 1100222
🔄 Запрос #11219 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 80 спецификаций. Всего: 1100302
🔄 Запрос #11220 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 61 спецификаций. Всего: 1100363
🔄 Запрос #11221 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 64 спецификаций. Всего: 1100427
🔄 Запрос #11222 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 113 спецификаций. Всего: 1100540
🔄 Запрос #11223 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 111 спецификаций. Всего: 1100651
🔄 Запрос #11224 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 108 спецификаций. Всего: 1100759
🔄 Запрос #11225 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 117 спецификаций. Всего: 1100876
🔄 Запрос #11226 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 93 спецификаций. Всего: 1100969
🔄 Запрос #11227 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 127 спецификаций. Всего: 1101096
🔄 Запрос #11228 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 121 спецификаций. Всего: 1101217
🔄 Запрос #11229 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 102 спецификаций. Всего: 1101319
🔄 Запрос #11230 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 110 спецификаций. Всего: 1101429
🔄 Запрос #11231 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 95 спецификаций. Всего: 1101524
🔄 Запрос #11232 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 105 спецификаций. Всего: 1101629

🔄 Запрос #11233 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 85 спецификаций. Всего: 1101714
🔄 Запрос #11234 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 61 спецификаций. Всего: 1101775
🔄 Запрос #11235 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 95 спецификаций. Всего: 1101870
🔄 Запрос #11236 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 99 спецификаций. Всего: 1101969
🔄 Запрос #11237 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 110 спецификаций. Всего: 1102079
🔄 Запрос #11238 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 106 спецификаций. Всего: 1102185
🔄 Запрос #11239 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 109 спецификаций. Всего: 1102294
🔄 Запрос #11240 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 118 спецификаций. Всего: 1102412
🔄 Запрос #11241 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 122 спецификаций. Всего: 1102534
🔄 Запрос #11242 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 114 спецификаций. Всего: 1102648
🔄 Запрос #11243 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1102761
🔄 Запрос #11244 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 110 спецификаций. Всего: 1102871
🔄 Запрос #11245 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 127 спецификаций. Всего: 1102998
🔄 Запрос #11246 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 128 спецификаций. Всего: 1103126
🔄 Запрос #11247 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 139 спецификаций. Всего: 1103265
🔄 Запрос #11248 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 157 спецификаций. Всего: 1103422
🔄 Запрос #11249 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 178 спецификаций. Всего: 1103600
🔄 Запрос #11250 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 145 спецификаций. Всего: 1103745
🔄 Запрос #11251 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 131 спецификаций. Всего: 1103876
🔄 Запрос #11252 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1104002
🔄 Запрос #11253 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 128 спецификаций. Всего: 1104130
🔄 Запрос #11254 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 110 спецификаций. Всего: 1104240
🔄 Запрос #11255 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 103 спецификаций. Всего: 1104343
🔄 Запрос #11256 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 125 спецификаций. Всего: 1104468
🔄 Запрос #11257 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 117 спецификаций. Всего: 1104585
🔄 Запрос #11258 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 105 спецификаций. Всего: 1104690
🔄 Запрос #11259 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 127 спецификаций. Всего: 1104817
🔄 Запрос #11260 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 100 спецификаций. Всего: 1104917
🔄 Запрос #11261 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 110 спецификаций. Всего: 1105027
🔄 Запрос #11262 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 120 спецификаций. Всего: 1105147
🔄 Запрос #11263 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 106 спецификаций. Всего: 1105253
🔄 Запрос #11264 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 106 спецификаций. Всего: 1105359
🔄 Запрос #11265 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 89 спецификаций. Всего: 1105448
🔄 Запрос #11266 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 111 спецификаций. Всего: 1105559
🔄 Запрос #11267 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 123 спецификаций. Всего: 1105682
🔄 Запрос #11268 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 92 спецификаций. Всего: 1105774
🔄 Запрос #11269 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 62 спецификаций. Всего: 1105836
🔄 Запрос #11270 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 102 спецификаций. Всего: 1105938
📤 Сохранено 10094 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #11271 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1106045
🔄 Запрос #11272 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 105 спецификаций. Всего: 1106150
🔄 Запрос #11273 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 109 спецификаций. Всего: 1106259
🔄 Запрос #11274 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 101 спецификаций. Всего: 1106360
🔄 Запрос #11275 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 102 спецификаций. Всего: 1106462
🔄 Запрос #11276 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 108 спецификаций. Всего: 1106570
🔄 Запрос #11277 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 97 спецификаций. Всего: 1106667
🔄 Запрос #11278 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 97 спецификаций. Всего: 1106764
🔄 Запрос #11279 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 108 спецификаций. Всего: 1106872
🔄 Запрос #11280 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 104 спецификаций. Всего: 1106976
🔄 Запрос #11281 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 108 спецификаций. Всего: 1107084
🔄 Запрос #11282 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 94 спецификаций. Всего: 1107178
🔄 Запрос #11283 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 89 спецификаций. Всего: 1107267
🔄 Запрос #11284 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 98 спецификаций. Всего: 1107365
🔄 Запрос #11285 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 71 спецификаций. Всего: 1107436
🔄 Запрос #11286 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 78 спецификаций. Всего: 1107514
🔄 Запрос #11287 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 75 спецификаций. Всего: 1107589
🔄 Запрос #11288 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 92 спецификаций. Всего: 1107681
🔄 Запрос #11289 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 91 спецификаций. Всего: 1107772
🔄 Запрос #11290 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 83 спецификаций. Всего: 1107855
🔄 Запрос #11291 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 79 спецификаций. Всего: 1107934
🔄 Запрос #11292 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 63 спецификаций. Всего: 1107997
🔄 Запрос #11293 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 143 спецификаций. Всего: 1108140
🔄 Запрос #11294 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 151 спецификаций. Всего: 1108291
🔄 Запрос #11295 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 129 спецификаций. Всего: 1108420
🔄 Запрос #11296 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 81 спецификаций. Всего: 1108501
🔄 Запрос #11297 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 109 спецификаций. Всего: 1108610
🔄 Запрос #11298 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 138 спецификаций. Всего: 1108748
🔄 Запрос #11299 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 158 спецификаций. Всего: 1108906
🔄 Запрос #11300 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 147 спецификаций. Всего: 1109053
🔄 Запрос #11301 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 132 спецификаций. Всего: 1109185
🔄 Запрос #11302 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 139 спецификаций. Всего: 1109324
🔄 Запрос #11303 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 108 спецификаций. Всего: 1109432

🔄 Запрос #11304 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 101 спецификаций. Всего: 1109533
🔄 Запрос #11305 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 128 спецификаций. Всего: 1109661
🔄 Запрос #11306 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 112 спецификаций. Всего: 1109773
🔄 Запрос #11307 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 108 спецификаций. Всего: 1109881
🔄 Запрос #11308 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 116 спецификаций. Всего: 1109997
🔄 Запрос #11309 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 107 спецификаций. Всего: 1110104
🔄 Запрос #11310 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 104 спецификаций. Всего: 1110208
🔄 Запрос #11311 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 85 спецификаций. Всего: 1110293
🔄 Запрос #11312 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 99 спецификаций. Всего: 1110392
🔄 Запрос #11313 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 105 спецификаций. Всего: 1110497
🔄 Запрос #11314 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 83 спецификаций. Всего: 1110580
🔄 Запрос #11315 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 105 спецификаций. Всего: 1110685
🔄 Запрос #11316 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 78 спецификаций. Всего: 1110763
🔄 Запрос #11317 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 97 спецификаций. Всего: 1110860
🔄 Запрос #11318 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 47 спецификаций. Всего: 1110907
🔄 Запрос #11319 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 86 спецификаций. Всего: 1110993
🔄 Запрос #11320 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 67 спецификаций. Всего: 1111060
🔄 Запрос #11321 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 104 спецификаций. Всего: 1111164
🔄 Запрос #11322 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 120 спецификаций. Всего: 1111284
🔄 Запрос #11323 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 118 спецификаций. Всего: 1111402
🔄 Запрос #11324 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 99 спецификаций. Всего: 1111501
🔄 Запрос #11325 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 119 спецификаций. Всего: 1111620
🔄 Запрос #11326 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 95 спецификаций. Всего: 1111715
🔄 Запрос #11327 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 117 спецификаций. Всего: 1111832
🔄 Запрос #11328 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 109 спецификаций. Всего: 1111941
🔄 Запрос #11329 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 87 спецификаций. Всего: 1112028
🔄 Запрос #11330 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 105 спецификаций. Всего: 1112133
🔄 Запрос #11331 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 88 спецификаций. Всего: 1112221
🔄 Запрос #11332 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 91 спецификаций. Всего: 1112312
🔄 Запрос #11333 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 105 спецификаций. Всего: 1112417
🔄 Запрос #11334 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 103 спецификаций. Всего: 1112520
🔄 Запрос #11335 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 110 спецификаций. Всего: 1112630
🔄 Запрос #11336 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 115 спецификаций. Всего: 1112745
🔄 Запрос #11337 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 81 спецификаций. Всего: 1112826
🔄 Запрос #11338 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 99 спецификаций. Всего: 1112925
🔄 Запрос #11339 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 110 спецификаций. Всего: 1113035
🔄 Запрос #11340 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 66 спецификаций. Всего: 1113101
🔄 Запрос #11341 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 118 спецификаций. Всего: 1113219
🔄 Запрос #11342 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 166 спецификаций. Всего: 1113385
🔄 Запрос #11343 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 138 спецификаций. Всего: 1113523
🔄 Запрос #11344 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 96 спецификаций. Всего: 1113619
🔄 Запрос #11345 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 66 спецификаций. Всего: 1113685
🔄 Запрос #11346 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 109 спецификаций. Всего: 1113794
🔄 Запрос #11347 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 137 спецификаций. Всего: 1113931
🔄 Запрос #11348 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 147 спецификаций. Всего: 1114078
🔄 Запрос #11349 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 122 спецификаций. Всего: 1114200
🔄 Запрос #11350 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 128 спецификаций. Всего: 1114328
🔄 Запрос #11351 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 122 спецификаций. Всего: 1114450
🔄 Запрос #11352 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 129 спецификаций. Всего: 1114579
🔄 Запрос #11353 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 130 спецификаций. Всего: 1114709
🔄 Запрос #11354 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 127 спецификаций. Всего: 1114836
🔄 Запрос #11355 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 135 спецификаций. Всего: 1114971
🔄 Запрос #11356 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 119 спецификаций. Всего: 1115090
🔄 Запрос #11357 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 108 спецификаций. Всего: 1115198
🔄 Запрос #11358 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 112 спецификаций. Всего: 1115310
🔄 Запрос #11359 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 130 спецификаций. Всего: 1115440
🔄 Запрос #11360 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 116 спецификаций. Всего: 1115556
🔄 Запрос #11361 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 110 спецификаций. Всего: 1115666
🔄 Запрос #11362 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 100 спецификаций. Всего: 1115766
🔄 Запрос #11363 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 94 спецификаций. Всего: 1115860
🔄 Запрос #11364 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 103 спецификаций. Всего: 1115963
📤 Сохранено 10025 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #11365 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 100 спецификаций. Всего: 1116063
🔄 Запрос #11366 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 102 спецификаций. Всего: 1116165
🔄 Запрос #11367 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 125 спецификаций. Всего: 1116290
🔄 Запрос #11368 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1116416
🔄 Запрос #11369 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 114 спецификаций. Всего: 1116530
🔄 Запрос #11370 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1116626
🔄 Запрос #11371 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 95 спецификаций. Всего: 1116721
🔄 Запрос #11372 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 98 спецификаций. Всего: 1116819
🔄 Запрос #11373 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 104 спецификаций. Всего: 1116923
🔄 Запрос #11374 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 105 спецификаций. Всего: 1117028
🔄 Запрос #11375 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 101 спецификаций. Всего: 1117129

🔄 Запрос #11376 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 86 спецификаций. Всего: 1117215
🔄 Запрос #11377 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 99 спецификаций. Всего: 1117314
🔄 Запрос #11378 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 100 спецификаций. Всего: 1117414
🔄 Запрос #11379 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 87 спецификаций. Всего: 1117501
🔄 Запрос #11380 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 107 спецификаций. Всего: 1117608
🔄 Запрос #11381 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 97 спецификаций. Всего: 1117705
🔄 Запрос #11382 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 116 спецификаций. Всего: 1117821
🔄 Запрос #11383 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 115 спецификаций. Всего: 1117936
🔄 Запрос #11384 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 90 спецификаций. Всего: 1118026
🔄 Запрос #11385 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 101 спецификаций. Всего: 1118127
🔄 Запрос #11386 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 66 спецификаций. Всего: 1118193
🔄 Запрос #11387 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 132 спецификаций. Всего: 1118325
🔄 Запрос #11388 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 157 спецификаций. Всего: 1118482
🔄 Запрос #11389 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 120 спецификаций. Всего: 1118602
🔄 Запрос #11390 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 170 спецификаций. Всего: 1118772
🔄 Запрос #11391 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 129 спецификаций. Всего: 1118901
🔄 Запрос #11392 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 139 спецификаций. Всего: 1119040
🔄 Запрос #11393 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 161 спецификаций. Всего: 1119201
🔄 Запрос #11394 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 93 спецификаций. Всего: 1119294
🔄 Запрос #11395 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 167 спецификаций. Всего: 1119461
🔄 Запрос #11396 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 166 спецификаций. Всего: 1119627
🔄 Запрос #11397 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 128 спецификаций. Всего: 1119755
🔄 Запрос #11398 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 118 спецификаций. Всего: 1119873
🔄 Запрос #11399 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 117 спецификаций. Всего: 1119990
🔄 Запрос #11400 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 137 спецификаций. Всего: 1120127
🔄 Запрос #11401 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 134 спецификаций. Всего: 1120261
🔄 Запрос #11402 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 122 спецификаций. Всего: 1120383
🔄 Запрос #11403 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 103 спецификаций. Всего: 1120486
🔄 Запрос #11404 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 98 спецификаций. Всего: 1120584
🔄 Запрос #11405 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 106 спецификаций. Всего: 1120690
🔄 Запрос #11406 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 96 спецификаций. Всего: 1120786
🔄 Запрос #11407 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 100 спецификаций. Всего: 1120886
🔄 Запрос #11408 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 97 спецификаций. Всего: 1120983
🔄 Запрос #11409 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 93 спецификаций. Всего: 1121076
🔄 Запрос #11410 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 121 спецификаций. Всего: 1121197
🔄 Запрос #11411 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 110 спецификаций. Всего: 1121307
🔄 Запрос #11412 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 122 спецификаций. Всего: 1121429
🔄 Запрос #11413 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 66 спецификаций. Всего: 1121495
🔄 Запрос #11414 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 90 спецификаций. Всего: 1121585
🔄 Запрос #11415 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 122 спецификаций. Всего: 1121707
🔄 Запрос #11416 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 133 спецификаций. Всего: 1121840
🔄 Запрос #11417 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 124 спецификаций. Всего: 1121964
🔄 Запрос #11418 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 124 спецификаций. Всего: 1122088
🔄 Запрос #11419 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 101 спецификаций. Всего: 1122189
🔄 Запрос #11420 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 104 спецификаций. Всего: 1122293
🔄 Запрос #11421 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 117 спецификаций. Всего: 1122410
🔄 Запрос #11422 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 91 спецификаций. Всего: 1122501
🔄 Запрос #11423 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 96 спецификаций. Всего: 1122597
🔄 Запрос #11424 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 91 спецификаций. Всего: 1122688
🔄 Запрос #11425 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 88 спецификаций. Всего: 1122776
🔄 Запрос #11426 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1122886
🔄 Запрос #11427 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 96 спецификаций. Всего: 1122982
🔄 Запрос #11428 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 126 спецификаций. Всего: 1123108
🔄 Запрос #11429 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 107 спецификаций. Всего: 1123215
🔄 Запрос #11430 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 78 спецификаций. Всего: 1123293
🔄 Запрос #11431 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 91 спецификаций. Всего: 1123384
🔄 Запрос #11432 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 97 спецификаций. Всего: 1123481
🔄 Запрос #11433 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 83 спецификаций. Всего: 1123564
🔄 Запрос #11434 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 99 спецификаций. Всего: 1123663
🔄 Запрос #11435 для 2024-06-13 20:44:09 - 2024-06-20 20:44:09
📥 Загружено 72 спецификаций. Всего: 1123735
📅 Обрабатываем диапазон 2024-06-06 20:44:09 - 2024-06-13 20:44:09 (попытка 1/5)
🔄 Запрос #11436 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 122 спецификаций. Всего: 1123857
🔄 Запрос #11437 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1123964
🔄 Запрос #11438 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 100 спецификаций. Всего: 1124064
🔄 Запрос #11439 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 120 спецификаций. Всего: 1124184
🔄 Запрос #11440 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 145 спецификаций. Всего: 1124329
🔄 Запрос #11441 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 99 спецификаций. Всего: 1124428
🔄 Запрос #11442 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 112 спецификаций. Всего: 1124540
🔄 Запрос #11443 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 109 спецификаций. Всего: 1124649
🔄 Запрос #11444 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 99 спецификаций. Всего: 1124748
🔄 Запрос #11445 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 98 спецификаций. Всего: 1124846
🔄 Запрос #11446 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 81 спецификаций. Всего: 1124927
🔄 Запрос #11447 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09

📥 Загружено 93 спецификаций. Всего: 1125020
🔄 Запрос #11448 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1125127
🔄 Запрос #11449 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 111 спецификаций. Всего: 1125238
🔄 Запрос #11450 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 56 спецификаций. Всего: 1125294
🔄 Запрос #11451 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 73 спецификаций. Всего: 1125367
🔄 Запрос #11452 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 110 спецификаций. Всего: 1125477
🔄 Запрос #11453 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 132 спецификаций. Всего: 1125609
🔄 Запрос #11454 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 112 спецификаций. Всего: 1125721
🔄 Запрос #11455 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 118 спецификаций. Всего: 1125839
🔄 Запрос #11456 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 114 спецификаций. Всего: 1125953
🔄 Запрос #11457 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 104 спецификаций. Всего: 1126057
📤 Сохранено 10094 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #11458 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1126176
🔄 Запрос #11459 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 100 спецификаций. Всего: 1126276
🔄 Запрос #11460 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 119 спецификаций. Всего: 1126395
🔄 Запрос #11461 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 100 спецификаций. Всего: 1126495
🔄 Запрос #11462 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 92 спецификаций. Всего: 1126587
🔄 Запрос #11463 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 88 спецификаций. Всего: 1126675
🔄 Запрос #11464 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 82 спецификаций. Всего: 1126757
🔄 Запрос #11465 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1126864
🔄 Запрос #11466 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 117 спецификаций. Всего: 1126981
🔄 Запрос #11467 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 132 спецификаций. Всего: 1127113
🔄 Запрос #11468 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 99 спецификаций. Всего: 1127212
🔄 Запрос #11469 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 90 спецификаций. Всего: 1127302
🔄 Запрос #11470 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 96 спецификаций. Всего: 1127398
🔄 Запрос #11471 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 106 спецификаций. Всего: 1127504
🔄 Запрос #11472 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 111 спецификаций. Всего: 1127615
🔄 Запрос #11473 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 102 спецификаций. Всего: 1127717
🔄 Запрос #11474 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 103 спецификаций. Всего: 1127820
🔄 Запрос #11475 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 109 спецификаций. Всего: 1127929
🔄 Запрос #11476 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 101 спецификаций. Всего: 1128030
🔄 Запрос #11477 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 93 спецификаций. Всего: 1128123
🔄 Запрос #11478 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 114 спецификаций. Всего: 1128237
🔄 Запрос #11479 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 144 спецификаций. Всего: 1128381
🔄 Запрос #11480 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 132 спецификаций. Всего: 1128513
🔄 Запрос #11481 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1128628
🔄 Запрос #11482 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 92 спецификаций. Всего: 1128720
🔄 Запрос #11483 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 111 спецификаций. Всего: 1128831
🔄 Запрос #11484 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 101 спецификаций. Всего: 1128932
🔄 Запрос #11485 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 78 спецификаций. Всего: 1129010
🔄 Запрос #11486 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 64 спецификаций. Всего: 1129074
🔄 Запрос #11487 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 66 спецификаций. Всего: 1129140
🔄 Запрос #11488 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 111 спецификаций. Всего: 1129251
🔄 Запрос #11489 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 77 спецификаций. Всего: 1129328
🔄 Запрос #11490 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 93 спецификаций. Всего: 1129421
🔄 Запрос #11491 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 133 спецификаций. Всего: 1129554
🔄 Запрос #11492 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 115 спецификаций. Всего: 1129669
🔄 Запрос #11493 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 127 спецификаций. Всего: 1129796
🔄 Запрос #11494 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 140 спецификаций. Всего: 1129936
🔄 Запрос #11495 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 127 спецификаций. Всего: 1130063
🔄 Запрос #11496 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 126 спецификаций. Всего: 1130189
🔄 Запрос #11497 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 119 спецификаций. Всего: 1130308
🔄 Запрос #11498 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 119 спецификаций. Всего: 1130427
🔄 Запрос #11499 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 102 спецификаций. Всего: 1130529
🔄 Запрос #11500 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 111 спецификаций. Всего: 1130640
🔄 Запрос #11501 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 119 спецификаций. Всего: 1130759
🔄 Запрос #11502 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 112 спецификаций. Всего: 1130871
🔄 Запрос #11503 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 96 спецификаций. Всего: 1130967
🔄 Запрос #11504 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 97 спецификаций. Всего: 1131064
🔄 Запрос #11505 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 109 спецификаций. Всего: 1131173
🔄 Запрос #11506 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 98 спецификаций. Всего: 1131271
🔄 Запрос #11507 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 100 спецификаций. Всего: 1131371
🔄 Запрос #11508 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 90 спецификаций. Всего: 1131461
🔄 Запрос #11509 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 94 спецификаций. Всего: 1131555
🔄 Запрос #11510 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 80 спецификаций. Всего: 1131635
🔄 Запрос #11511 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 84 спецификаций. Всего: 1131719
🔄 Запрос #11512 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 109 спецификаций. Всего: 1131828
🔄 Запрос #11513 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 123 спецификаций. Всего: 1131951
🔄 Запрос #11514 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 115 спецификаций. Всего: 1132066
🔄 Запрос #11515 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1132173
🔄 Запрос #11516 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 120 спецификаций. Всего: 1132293
🔄 Запрос #11517 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 131 спецификаций. Всего: 1132424
🔄 Запрос #11518 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 117 спецификаций. Всего: 1132541
🔄 Запрос #11519 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09

📥 Загружено 102 спецификаций. Всего: 1132643
🔄 Запрос #11520 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 103 спецификаций. Всего: 1132746
🔄 Запрос #11521 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1132853
🔄 Запрос #11522 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 129 спецификаций. Всего: 1132982
🔄 Запрос #11523 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 82 спецификаций. Всего: 1133064
🔄 Запрос #11524 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 109 спецификаций. Всего: 1133173
🔄 Запрос #11525 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 117 спецификаций. Всего: 1133290
🔄 Запрос #11526 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 94 спецификаций. Всего: 1133384
🔄 Запрос #11527 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 104 спецификаций. Всего: 1133488
🔄 Запрос #11528 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 88 спецификаций. Всего: 1133576
🔄 Запрос #11529 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 87 спецификаций. Всего: 1133663
🔄 Запрос #11530 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 92 спецификаций. Всего: 1133755
🔄 Запрос #11531 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 87 спецификаций. Всего: 1133842
🔄 Запрос #11532 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 89 спецификаций. Всего: 1133931
🔄 Запрос #11533 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 78 спецификаций. Всего: 1134009
🔄 Запрос #11534 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 95 спецификаций. Всего: 1134104
🔄 Запрос #11535 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 58 спецификаций. Всего: 1134162
🔄 Запрос #11536 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 75 спецификаций. Всего: 1134237
🔄 Запрос #11537 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 96 спецификаций. Всего: 1134333
🔄 Запрос #11538 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 91 спецификаций. Всего: 1134424
🔄 Запрос #11539 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1134541
🔄 Запрос #11540 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 117 спецификаций. Всего: 1134658
🔄 Запрос #11541 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 92 спецификаций. Всего: 1134750
🔄 Запрос #11542 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 60 спецификаций. Всего: 1134810
🔄 Запрос #11543 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1134918
🔄 Запрос #11544 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 100 спецификаций. Всего: 1135018
🔄 Запрос #11545 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 105 спецификаций. Всего: 1135123
🔄 Запрос #11546 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1135216
🔄 Запрос #11547 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 132 спецификаций. Всего: 1135348
🔄 Запрос #11548 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 109 спецификаций. Всего: 1135457
🔄 Запрос #11549 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 102 спецификаций. Всего: 1135559
🔄 Запрос #11550 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 144 спецификаций. Всего: 1135703
🔄 Запрос #11551 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 82 спецификаций. Всего: 1135785
🔄 Запрос #11552 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 125 спецификаций. Всего: 1135910
🔄 Запрос #11553 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 141 спецификаций. Всего: 1136051
🔄 Запрос #11554 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 151 спецификаций. Всего: 1136202
📤 Сохранено 10145 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #11555 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 119 спецификаций. Всего: 1136321
🔄 Запрос #11556 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 129 спецификаций. Всего: 1136450
🔄 Запрос #11557 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 112 спецификаций. Всего: 1136562
🔄 Запрос #11558 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 103 спецификаций. Всего: 1136665
🔄 Запрос #11559 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 104 спецификаций. Всего: 1136769
🔄 Запрос #11560 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 97 спецификаций. Всего: 1136866
🔄 Запрос #11561 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 126 спецификаций. Всего: 1136992
🔄 Запрос #11562 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 121 спецификаций. Всего: 1137113
🔄 Запрос #11563 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 122 спецификаций. Всего: 1137235
🔄 Запрос #11564 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 118 спецификаций. Всего: 1137353
🔄 Запрос #11565 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 109 спецификаций. Всего: 1137462
🔄 Запрос #11566 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1137569
🔄 Запрос #11567 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 106 спецификаций. Всего: 1137675
🔄 Запрос #11568 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 93 спецификаций. Всего: 1137768
🔄 Запрос #11569 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 97 спецификаций. Всего: 1137865
🔄 Запрос #11570 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 95 спецификаций. Всего: 1137960
🔄 Запрос #11571 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 93 спецификаций. Всего: 1138053
🔄 Запрос #11572 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 114 спецификаций. Всего: 1138167
🔄 Запрос #11573 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1138280
🔄 Запрос #11574 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 80 спецификаций. Всего: 1138360
🔄 Запрос #11575 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 70 спецификаций. Всего: 1138430
🔄 Запрос #11576 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 79 спецификаций. Всего: 1138509
🔄 Запрос #11577 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 93 спецификаций. Всего: 1138602
🔄 Запрос #11578 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 98 спецификаций. Всего: 1138700
🔄 Запрос #11579 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 106 спецификаций. Всего: 1138806
🔄 Запрос #11580 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 108 спецификаций. Всего: 1138914
🔄 Запрос #11581 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 101 спецификаций. Всего: 1139015
🔄 Запрос #11582 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 95 спецификаций. Всего: 1139110
🔄 Запрос #11583 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 99 спецификаций. Всего: 1139209
🔄 Запрос #11584 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 76 спецификаций. Всего: 1139285
🔄 Запрос #11585 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 100 спецификаций. Всего: 1139385
🔄 Запрос #11586 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 80 спецификаций. Всего: 1139465
🔄 Запрос #11587 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09

📥 Загружено 85 спецификаций. Всего: 1139550
🔄 Запрос #11588 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 85 спецификаций. Всего: 1139635
🔄 Запрос #11589 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 98 спецификаций. Всего: 1139733
🔄 Запрос #11590 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 97 спецификаций. Всего: 1139830
🔄 Запрос #11591 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 117 спецификаций. Всего: 1139947
🔄 Запрос #11592 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1140054
🔄 Запрос #11593 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 105 спецификаций. Всего: 1140159
🔄 Запрос #11594 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 98 спецификаций. Всего: 1140257
🔄 Запрос #11595 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 98 спецификаций. Всего: 1140355
🔄 Запрос #11596 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 102 спецификаций. Всего: 1140457
🔄 Запрос #11597 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 101 спецификаций. Всего: 1140558
🔄 Запрос #11598 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 80 спецификаций. Всего: 1140638
🔄 Запрос #11599 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 101 спецификаций. Всего: 1140739
🔄 Запрос #11600 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 65 спецификаций. Всего: 1140804
🔄 Запрос #11601 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 113 спецификаций. Всего: 1140917
🔄 Запрос #11602 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 149 спецификаций. Всего: 1141066
🔄 Запрос #11603 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 139 спецификаций. Всего: 1141205
🔄 Запрос #11604 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 155 спецификаций. Всего: 1141360
🔄 Запрос #11605 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 149 спецификаций. Всего: 1141509
🔄 Запрос #11606 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 152 спецификаций. Всего: 1141661
🔄 Запрос #11607 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 137 спецификаций. Всего: 1141798
🔄 Запрос #11608 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 121 спецификаций. Всего: 1141919
🔄 Запрос #11609 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 100 спецификаций. Всего: 1142019
🔄 Запрос #11610 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 105 спецификаций. Всего: 1142124
🔄 Запрос #11611 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1142231
🔄 Запрос #11612 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1142343
🔄 Запрос #11613 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 90 спецификаций. Всего: 1142433
🔄 Запрос #11614 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 84 спецификаций. Всего: 1142517
🔄 Запрос #11615 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 102 спецификаций. Всего: 1142619
🔄 Запрос #11616 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 115 спецификаций. Всего: 1142734
🔄 Запрос #11617 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 123 спецификаций. Всего: 1142857
🔄 Запрос #11618 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 123 спецификаций. Всего: 1142980
🔄 Запрос #11619 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 120 спецификаций. Всего: 1143100
🔄 Запрос #11620 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 122 спецификаций. Всего: 1143222
🔄 Запрос #11621 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 120 спецификаций. Всего: 1143342
🔄 Запрос #11622 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 128 спецификаций. Всего: 1143470
🔄 Запрос #11623 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1143575
🔄 Запрос #11624 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 98 спецификаций. Всего: 1143673
🔄 Запрос #11625 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 94 спецификаций. Всего: 1143767
🔄 Запрос #11626 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 112 спецификаций. Всего: 1143879
🔄 Запрос #11627 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 121 спецификаций. Всего: 1144000
🔄 Запрос #11628 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 108 спецификаций. Всего: 1144108
🔄 Запрос #11629 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 95 спецификаций. Всего: 1144203
🔄 Запрос #11630 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 75 спецификаций. Всего: 1144278
🔄 Запрос #11631 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 102 спецификаций. Всего: 1144380
🔄 Запрос #11632 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 83 спецификаций. Всего: 1144463
🔄 Запрос #11633 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 100 спецификаций. Всего: 1144563
🔄 Запрос #11634 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 151 спецификаций. Всего: 1144714
🔄 Запрос #11635 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 112 спецификаций. Всего: 1144826
🔄 Запрос #11636 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 123 спецификаций. Всего: 1144949
🔄 Запрос #11637 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 104 спецификаций. Всего: 1145053
🔄 Запрос #11638 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 106 спецификаций. Всего: 1145159
🔄 Запрос #11639 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 91 спецификаций. Всего: 1145250
🔄 Запрос #11640 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 96 спецификаций. Всего: 1145346
🔄 Запрос #11641 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 95 спецификаций. Всего: 1145441
🔄 Запрос #11642 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 83 спецификаций. Всего: 1145524
🔄 Запрос #11643 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 100 спецификаций. Всего: 1145624
🔄 Запрос #11644 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 89 спецификаций. Всего: 1145713
🔄 Запрос #11645 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 91 спецификаций. Всего: 1145804
🔄 Запрос #11646 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 71 спецификаций. Всего: 1145875
🔄 Запрос #11647 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 88 спецификаций. Всего: 1145963
🔄 Запрос #11648 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 85 спецификаций. Всего: 1146048
🔄 Запрос #11649 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 94 спецификаций. Всего: 1146142
🔄 Запрос #11650 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 104 спецификаций. Всего: 1146246
📤 Сохранено 10044 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #11651 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 124 спецификаций. Всего: 1146370
🔄 Запрос #11652 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 93 спецификаций. Всего: 1146463
🔄 Запрос #11653 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 64 спецификаций. Всего: 1146527
🔄 Запрос #11654 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 102 спецификаций. Всего: 1146629
🔄 Запрос #11655 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1146736
🔄 Запрос #11656 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 117 спецификаций. Всего: 1146853
🔄 Запрос #11657 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 111 спецификаций. Всего: 1146964
🔄 Запрос #11658 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 100 спецификаций. Всего: 1147064
🔄 Запрос #11659 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09

📥 Загружено 89 спецификаций. Всего: 1147153
🔄 Запрос #11660 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 129 спецификаций. Всего: 1147282
🔄 Запрос #11661 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 86 спецификаций. Всего: 1147368
🔄 Запрос #11662 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 90 спецификаций. Всего: 1147458
🔄 Запрос #11663 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 130 спецификаций. Всего: 1147588
🔄 Запрос #11664 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 151 спецификаций. Всего: 1147739
🔄 Запрос #11665 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 128 спецификаций. Всего: 1147867
🔄 Запрос #11666 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 99 спецификаций. Всего: 1147966
🔄 Запрос #11667 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 116 спецификаций. Всего: 1148082
🔄 Запрос #11668 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 131 спецификаций. Всего: 1148213
🔄 Запрос #11669 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 148 спецификаций. Всего: 1148361
🔄 Запрос #11670 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 117 спецификаций. Всего: 1148478
🔄 Запрос #11671 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 126 спецификаций. Всего: 1148604
🔄 Запрос #11672 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 129 спецификаций. Всего: 1148733
🔄 Запрос #11673 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 123 спецификаций. Всего: 1148856
🔄 Запрос #11674 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 130 спецификаций. Всего: 1148986
🔄 Запрос #11675 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 123 спецификаций. Всего: 1149109
🔄 Запрос #11676 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 108 спецификаций. Всего: 1149217
🔄 Запрос #11677 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1149324
🔄 Запрос #11678 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 101 спецификаций. Всего: 1149425
🔄 Запрос #11679 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 103 спецификаций. Всего: 1149528
🔄 Запрос #11680 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 96 спецификаций. Всего: 1149624
🔄 Запрос #11681 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 120 спецификаций. Всего: 1149744
🔄 Запрос #11682 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 111 спецификаций. Всего: 1149855
🔄 Запрос #11683 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1149966
🔄 Запрос #11684 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 113 спецификаций. Всего: 1150079
🔄 Запрос #11685 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 133 спецификаций. Всего: 1150212
🔄 Запрос #11686 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 127 спецификаций. Всего: 1150339
🔄 Запрос #11687 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 124 спецификаций. Всего: 1150463
🔄 Запрос #11688 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 102 спецификаций. Всего: 1150565
🔄 Запрос #11689 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 172 спецификаций. Всего: 1150737
🔄 Запрос #11690 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 103 спецификаций. Всего: 1150840
🔄 Запрос #11691 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 75 спецификаций. Всего: 1150915
🔄 Запрос #11692 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 86 спецификаций. Всего: 1151001
🔄 Запрос #11693 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 125 спецификаций. Всего: 1151126
🔄 Запрос #11694 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 104 спецификаций. Всего: 1151230
🔄 Запрос #11695 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1151337
🔄 Запрос #11696 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 99 спецификаций. Всего: 1151436
🔄 Запрос #11697 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 87 спецификаций. Всего: 1151523
🔄 Запрос #11698 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 95 спецификаций. Всего: 1151618
🔄 Запрос #11699 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 104 спецификаций. Всего: 1151722
🔄 Запрос #11700 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 101 спецификаций. Всего: 1151823
🔄 Запрос #11701 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 113 спецификаций. Всего: 1151936
🔄 Запрос #11702 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 96 спецификаций. Всего: 1152032
🔄 Запрос #11703 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 100 спецификаций. Всего: 1152132
🔄 Запрос #11704 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 86 спецификаций. Всего: 1152218
🔄 Запрос #11705 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 100 спецификаций. Всего: 1152318
🔄 Запрос #11706 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 107 спецификаций. Всего: 1152425
🔄 Запрос #11707 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 103 спецификаций. Всего: 1152528
🔄 Запрос #11708 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 106 спецификаций. Всего: 1152634
🔄 Запрос #11709 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 128 спецификаций. Всего: 1152762
🔄 Запрос #11710 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 121 спецификаций. Всего: 1152883
🔄 Запрос #11711 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 124 спецификаций. Всего: 1153007
🔄 Запрос #11712 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 109 спецификаций. Всего: 1153116
🔄 Запрос #11713 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 115 спецификаций. Всего: 1153231
🔄 Запрос #11714 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 112 спецификаций. Всего: 1153343
🔄 Запрос #11715 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 123 спецификаций. Всего: 1153466
🔄 Запрос #11716 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 83 спецификаций. Всего: 1153549
🔄 Запрос #11717 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 74 спецификаций. Всего: 1153623
🔄 Запрос #11718 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 148 спецификаций. Всего: 1153771
🔄 Запрос #11719 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 141 спецификаций. Всего: 1153912
🔄 Запрос #11720 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 88 спецификаций. Всего: 1154000
🔄 Запрос #11721 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 153 спецификаций. Всего: 1154153
🔄 Запрос #11722 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 120 спецификаций. Всего: 1154273
🔄 Запрос #11723 для 2024-06-06 20:44:09 - 2024-06-13 20:44:09
📥 Загружено 32 спецификаций. Всего: 1154305
📅 Обрабатываем диапазон 2024-05-30 20:44:09 - 2024-06-06 20:44:09 (попытка 1/5)
🔄 Запрос #11724 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 100 спецификаций. Всего: 1154405
🔄 Запрос #11725 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 130 спецификаций. Всего: 1154535
🔄 Запрос #11726 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 157 спецификаций. Всего: 1154692
🔄 Запрос #11727 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 137 спецификаций. Всего: 1154829
🔄 Запрос #11728 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 124 спецификаций. Всего: 1154953
🔄 Запрос #11729 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 119 спецификаций. Всего: 1155072
🔄 Запрос #11730 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09

📥 Загружено 114 спецификаций. Всего: 1155186
🔄 Запрос #11731 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 109 спецификаций. Всего: 1155295
🔄 Запрос #11732 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 107 спецификаций. Всего: 1155402
🔄 Запрос #11733 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 118 спецификаций. Всего: 1155520
🔄 Запрос #11734 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 114 спецификаций. Всего: 1155634
🔄 Запрос #11735 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 111 спецификаций. Всего: 1155745
🔄 Запрос #11736 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 109 спецификаций. Всего: 1155854
🔄 Запрос #11737 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 95 спецификаций. Всего: 1155949
🔄 Запрос #11738 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 90 спецификаций. Всего: 1156039
🔄 Запрос #11739 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 105 спецификаций. Всего: 1156144
🔄 Запрос #11740 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1156237
🔄 Запрос #11741 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 97 спецификаций. Всего: 1156334
📤 Сохранено 10088 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #11742 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 105 спецификаций. Всего: 1156439
🔄 Запрос #11743 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 109 спецификаций. Всего: 1156548
🔄 Запрос #11744 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 97 спецификаций. Всего: 1156645
🔄 Запрос #11745 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 95 спецификаций. Всего: 1156740
🔄 Запрос #11746 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1156842
🔄 Запрос #11747 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 93 спецификаций. Всего: 1156935
🔄 Запрос #11748 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 1157025
🔄 Запрос #11749 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1157120
🔄 Запрос #11750 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 100 спецификаций. Всего: 1157220
🔄 Запрос #11751 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 90 спецификаций. Всего: 1157310
🔄 Запрос #11752 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 74 спецификаций. Всего: 1157384
🔄 Запрос #11753 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 123 спецификаций. Всего: 1157507
🔄 Запрос #11754 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 135 спецификаций. Всего: 1157642
🔄 Запрос #11755 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 91 спецификаций. Всего: 1157733
🔄 Запрос #11756 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 111 спецификаций. Всего: 1157844
🔄 Запрос #11757 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 104 спецификаций. Всего: 1157948
🔄 Запрос #11758 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 90 спецификаций. Всего: 1158038
🔄 Запрос #11759 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 103 спецификаций. Всего: 1158141
🔄 Запрос #11760 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 107 спецификаций. Всего: 1158248
🔄 Запрос #11761 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 84 спецификаций. Всего: 1158332
🔄 Запрос #11762 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 110 спецификаций. Всего: 1158442
🔄 Запрос #11763 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 103 спецификаций. Всего: 1158545
🔄 Запрос #11764 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 105 спецификаций. Всего: 1158650
🔄 Запрос #11765 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 120 спецификаций. Всего: 1158770
🔄 Запрос #11766 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 101 спецификаций. Всего: 1158871
🔄 Запрос #11767 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 121 спецификаций. Всего: 1158992
🔄 Запрос #11768 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1159099
🔄 Запрос #11769 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 88 спецификаций. Всего: 1159187
🔄 Запрос #11770 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 92 спецификаций. Всего: 1159279
🔄 Запрос #11771 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 96 спецификаций. Всего: 1159375
🔄 Запрос #11772 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 100 спецификаций. Всего: 1159475
🔄 Запрос #11773 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 113 спецификаций. Всего: 1159588
🔄 Запрос #11774 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 105 спецификаций. Всего: 1159693
🔄 Запрос #11775 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 102 спецификаций. Всего: 1159795
🔄 Запрос #11776 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 69 спецификаций. Всего: 1159864
🔄 Запрос #11777 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 81 спецификаций. Всего: 1159945
🔄 Запрос #11778 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 86 спецификаций. Всего: 1160031
🔄 Запрос #11779 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 96 спецификаций. Всего: 1160127
🔄 Запрос #11780 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 113 спецификаций. Всего: 1160240
🔄 Запрос #11781 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 142 спецификаций. Всего: 1160382
🔄 Запрос #11782 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 142 спецификаций. Всего: 1160524
🔄 Запрос #11783 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 133 спецификаций. Всего: 1160657
🔄 Запрос #11784 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 83 спецификаций. Всего: 1160740
🔄 Запрос #11785 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 113 спецификаций. Всего: 1160853
🔄 Запрос #11786 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 1160956
🔄 Запрос #11787 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 161 спецификаций. Всего: 1161117
🔄 Запрос #11788 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 121 спецификаций. Всего: 1161238
🔄 Запрос #11789 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 141 спецификаций. Всего: 1161379
🔄 Запрос #11790 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 138 спецификаций. Всего: 1161517
🔄 Запрос #11791 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 116 спецификаций. Всего: 1161633
🔄 Запрос #11792 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 123 спецификаций. Всего: 1161756
🔄 Запрос #11793 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 135 спецификаций. Всего: 1161891
🔄 Запрос #11794 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 107 спецификаций. Всего: 1161998
🔄 Запрос #11795 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 113 спецификаций. Всего: 1162111
🔄 Запрос #11796 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 92 спецификаций. Всего: 1162203
🔄 Запрос #11797 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 130 спецификаций. Всего: 1162333
🔄 Запрос #11798 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 115 спецификаций. Всего: 1162448
🔄 Запрос #11799 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 119 спецификаций. Всего: 1162567

🔄 Запрос #11800 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 109 спецификаций. Всего: 1162676
🔄 Запрос #11801 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 117 спецификаций. Всего: 1162793
🔄 Запрос #11802 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 114 спецификаций. Всего: 1162907
🔄 Запрос #11803 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 103 спецификаций. Всего: 1163010
🔄 Запрос #11804 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 110 спецификаций. Всего: 1163120
🔄 Запрос #11805 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 122 спецификаций. Всего: 1163242
🔄 Запрос #11806 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 108 спецификаций. Всего: 1163350
🔄 Запрос #11807 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 114 спецификаций. Всего: 1163464
🔄 Запрос #11808 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 105 спецификаций. Всего: 1163569
🔄 Запрос #11809 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 98 спецификаций. Всего: 1163667
🔄 Запрос #11810 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 86 спецификаций. Всего: 1163753
🔄 Запрос #11811 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 94 спецификаций. Всего: 1163847
🔄 Запрос #11812 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 100 спецификаций. Всего: 1163947
🔄 Запрос #11813 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 90 спецификаций. Всего: 1164037
🔄 Запрос #11814 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 114 спецификаций. Всего: 1164151
🔄 Запрос #11815 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 123 спецификаций. Всего: 1164274
🔄 Запрос #11816 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 113 спецификаций. Всего: 1164387
🔄 Запрос #11817 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 156 спецификаций. Всего: 1164543
🔄 Запрос #11818 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 165 спецификаций. Всего: 1164708
🔄 Запрос #11819 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 138 спецификаций. Всего: 1164846
🔄 Запрос #11820 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 116 спецификаций. Всего: 1164962
🔄 Запрос #11821 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 108 спецификаций. Всего: 1165070
🔄 Запрос #11822 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 89 спецификаций. Всего: 1165159
🔄 Запрос #11823 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 99 спецификаций. Всего: 1165258
🔄 Запрос #11824 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 112 спецификаций. Всего: 1165370
🔄 Запрос #11825 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 114 спецификаций. Всего: 1165484
🔄 Запрос #11826 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1165608
🔄 Запрос #11827 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 120 спецификаций. Всего: 1165728
🔄 Запрос #11828 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 125 спецификаций. Всего: 1165853
🔄 Запрос #11829 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 106 спецификаций. Всего: 1165959
🔄 Запрос #11830 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 122 спецификаций. Всего: 1166081
🔄 Запрос #11831 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 111 спецификаций. Всего: 1166192
🔄 Запрос #11832 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 114 спецификаций. Всего: 1166306
🔄 Запрос #11833 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 127 спецификаций. Всего: 1166433
📤 Сохранено 10099 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #11834 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 118 спецификаций. Всего: 1166551
🔄 Запрос #11835 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 111 спецификаций. Всего: 1166662
🔄 Запрос #11836 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 94 спецификаций. Всего: 1166756
🔄 Запрос #11837 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 86 спецификаций. Всего: 1166842
🔄 Запрос #11838 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 98 спецификаций. Всего: 1166940
🔄 Запрос #11839 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 56 спецификаций. Всего: 1166996
🔄 Запрос #11840 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 56 спецификаций. Всего: 1167052
🔄 Запрос #11841 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 61 спецификаций. Всего: 1167113
🔄 Запрос #11842 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 122 спецификаций. Всего: 1167235
🔄 Запрос #11843 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 102 спецификаций. Всего: 1167337
🔄 Запрос #11844 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 144 спецификаций. Всего: 1167481
🔄 Запрос #11845 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 151 спецификаций. Всего: 1167632
🔄 Запрос #11846 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 126 спецификаций. Всего: 1167758
🔄 Запрос #11847 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 122 спецификаций. Всего: 1167880
🔄 Запрос #11848 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 162 спецификаций. Всего: 1168042
🔄 Запрос #11849 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 103 спецификаций. Всего: 1168145
🔄 Запрос #11850 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 113 спецификаций. Всего: 1168258
🔄 Запрос #11851 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 129 спецификаций. Всего: 1168387
🔄 Запрос #11852 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 125 спецификаций. Всего: 1168512
🔄 Запрос #11853 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 125 спецификаций. Всего: 1168637
🔄 Запрос #11854 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 121 спецификаций. Всего: 1168758
🔄 Запрос #11855 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 123 спецификаций. Всего: 1168881
🔄 Запрос #11856 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 123 спецификаций. Всего: 1169004
🔄 Запрос #11857 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 106 спецификаций. Всего: 1169110
🔄 Запрос #11858 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 106 спецификаций. Всего: 1169216
🔄 Запрос #11859 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 103 спецификаций. Всего: 1169319
🔄 Запрос #11860 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 103 спецификаций. Всего: 1169422
🔄 Запрос #11861 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 113 спецификаций. Всего: 1169535
🔄 Запрос #11862 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 118 спецификаций. Всего: 1169653
🔄 Запрос #11863 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 115 спецификаций. Всего: 1169768
🔄 Запрос #11864 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 110 спецификаций. Всего: 1169878
🔄 Запрос #11865 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1169983
🔄 Запрос #11866 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 100 спецификаций. Всего: 1170083
🔄 Запрос #11867 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 103 спецификаций. Всего: 1170186
🔄 Запрос #11868 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 96 спецификаций. Всего: 1170282
🔄 Запрос #11869 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 96 спецификаций. Всего: 1170378
🔄 Запрос #11870 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 117 спецификаций. Всего: 1170495

🔄 Запрос #11871 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1170593
🔄 Запрос #11872 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 98 спецификаций. Всего: 1170691
🔄 Запрос #11873 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 94 спецификаций. Всего: 1170785
🔄 Запрос #11874 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 97 спецификаций. Всего: 1170882
🔄 Запрос #11875 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 92 спецификаций. Всего: 1170974
🔄 Запрос #11876 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 93 спецификаций. Всего: 1171067
🔄 Запрос #11877 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 120 спецификаций. Всего: 1171187
🔄 Запрос #11878 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 94 спецификаций. Всего: 1171281
🔄 Запрос #11879 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 142 спецификаций. Всего: 1171423
🔄 Запрос #11880 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 123 спецификаций. Всего: 1171546
🔄 Запрос #11881 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 130 спецификаций. Всего: 1171676
🔄 Запрос #11882 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 126 спецификаций. Всего: 1171802
🔄 Запрос #11883 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 141 спецификаций. Всего: 1171943
🔄 Запрос #11884 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 150 спецификаций. Всего: 1172093
🔄 Запрос #11885 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 132 спецификаций. Всего: 1172225
🔄 Запрос #11886 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 145 спецификаций. Всего: 1172370
🔄 Запрос #11887 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 136 спецификаций. Всего: 1172506
🔄 Запрос #11888 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 126 спецификаций. Всего: 1172632
🔄 Запрос #11889 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 119 спецификаций. Всего: 1172751
🔄 Запрос #11890 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 124 спецификаций. Всего: 1172875
🔄 Запрос #11891 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 126 спецификаций. Всего: 1173001
🔄 Запрос #11892 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 115 спецификаций. Всего: 1173116
🔄 Запрос #11893 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 110 спецификаций. Всего: 1173226
🔄 Запрос #11894 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 131 спецификаций. Всего: 1173357
🔄 Запрос #11895 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 110 спецификаций. Всего: 1173467
🔄 Запрос #11896 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 118 спецификаций. Всего: 1173585
🔄 Запрос #11897 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 138 спецификаций. Всего: 1173723
🔄 Запрос #11898 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 145 спецификаций. Всего: 1173868
🔄 Запрос #11899 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 113 спецификаций. Всего: 1173981
🔄 Запрос #11900 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 111 спецификаций. Всего: 1174092
🔄 Запрос #11901 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 110 спецификаций. Всего: 1174202
🔄 Запрос #11902 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 124 спецификаций. Всего: 1174326
🔄 Запрос #11903 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 128 спецификаций. Всего: 1174454
🔄 Запрос #11904 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 154 спецификаций. Всего: 1174608
🔄 Запрос #11905 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 132 спецификаций. Всего: 1174740
🔄 Запрос #11906 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 139 спецификаций. Всего: 1174879
🔄 Запрос #11907 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 144 спецификаций. Всего: 1175023
🔄 Запрос #11908 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 116 спецификаций. Всего: 1175139
🔄 Запрос #11909 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 87 спецификаций. Всего: 1175226
🔄 Запрос #11910 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 145 спецификаций. Всего: 1175371
🔄 Запрос #11911 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 158 спецификаций. Всего: 1175529
🔄 Запрос #11912 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 139 спецификаций. Всего: 1175668
🔄 Запрос #11913 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 158 спецификаций. Всего: 1175826
🔄 Запрос #11914 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 132 спецификаций. Всего: 1175958
🔄 Запрос #11915 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 136 спецификаций. Всего: 1176094
🔄 Запрос #11916 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 119 спецификаций. Всего: 1176213
🔄 Запрос #11917 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1176340
🔄 Запрос #11918 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 130 спецификаций. Всего: 1176470
📤 Сохранено 10037 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #11919 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 116 спецификаций. Всего: 1176586
🔄 Запрос #11920 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 117 спецификаций. Всего: 1176703
🔄 Запрос #11921 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 129 спецификаций. Всего: 1176832
🔄 Запрос #11922 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 113 спецификаций. Всего: 1176945
🔄 Запрос #11923 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 84 спецификаций. Всего: 1177029
🔄 Запрос #11924 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 104 спецификаций. Всего: 1177133
🔄 Запрос #11925 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 110 спецификаций. Всего: 1177243
🔄 Запрос #11926 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 118 спецификаций. Всего: 1177361
🔄 Запрос #11927 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 129 спецификаций. Всего: 1177490
🔄 Запрос #11928 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 115 спецификаций. Всего: 1177605
🔄 Запрос #11929 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1177722
🔄 Запрос #11930 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 114 спецификаций. Всего: 1177836
🔄 Запрос #11931 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 110 спецификаций. Всего: 1177946
🔄 Запрос #11932 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 89 спецификаций. Всего: 1178035
🔄 Запрос #11933 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 84 спецификаций. Всего: 1178119
🔄 Запрос #11934 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 82 спецификаций. Всего: 1178201
🔄 Запрос #11935 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 92 спецификаций. Всего: 1178293
🔄 Запрос #11936 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 65 спецификаций. Всего: 1178358
🔄 Запрос #11937 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 110 спецификаций. Всего: 1178468
🔄 Запрос #11938 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 115 спецификаций. Всего: 1178583
🔄 Запрос #11939 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 113 спецификаций. Всего: 1178696

🔄 Запрос #11940 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 104 спецификаций. Всего: 1178800
🔄 Запрос #11941 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 112 спецификаций. Всего: 1178912
🔄 Запрос #11942 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 114 спецификаций. Всего: 1179026
🔄 Запрос #11943 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 107 спецификаций. Всего: 1179133
🔄 Запрос #11944 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 101 спецификаций. Всего: 1179234
🔄 Запрос #11945 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 112 спецификаций. Всего: 1179346
🔄 Запрос #11946 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 140 спецификаций. Всего: 1179486
🔄 Запрос #11947 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 122 спецификаций. Всего: 1179608
🔄 Запрос #11948 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 121 спецификаций. Всего: 1179729
🔄 Запрос #11949 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 113 спецификаций. Всего: 1179842
🔄 Запрос #11950 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 130 спецификаций. Всего: 1179972
🔄 Запрос #11951 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 112 спецификаций. Всего: 1180084
🔄 Запрос #11952 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 117 спецификаций. Всего: 1180201
🔄 Запрос #11953 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 114 спецификаций. Всего: 1180315
🔄 Запрос #11954 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 118 спецификаций. Всего: 1180433
🔄 Запрос #11955 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 111 спецификаций. Всего: 1180544
🔄 Запрос #11956 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 68 спецификаций. Всего: 1180612
🔄 Запрос #11957 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 86 спецификаций. Всего: 1180698
🔄 Запрос #11958 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 107 спецификаций. Всего: 1180805
🔄 Запрос #11959 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 122 спецификаций. Всего: 1180927
🔄 Запрос #11960 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 158 спецификаций. Всего: 1181085
🔄 Запрос #11961 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 160 спецификаций. Всего: 1181245
🔄 Запрос #11962 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 110 спецификаций. Всего: 1181355
🔄 Запрос #11963 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 102 спецификаций. Всего: 1181457
🔄 Запрос #11964 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 33 спецификаций. Всего: 1181490
🔄 Запрос #11965 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 131 спецификаций. Всего: 1181621
🔄 Запрос #11966 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 144 спецификаций. Всего: 1181765
🔄 Запрос #11967 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 88 спецификаций. Всего: 1181853
🔄 Запрос #11968 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 47 спецификаций. Всего: 1181900
🔄 Запрос #11969 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 59 спецификаций. Всего: 1181959
🔄 Запрос #11970 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 127 спецификаций. Всего: 1182086
🔄 Запрос #11971 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 134 спецификаций. Всего: 1182220
🔄 Запрос #11972 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 122 спецификаций. Всего: 1182342
🔄 Запрос #11973 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 112 спецификаций. Всего: 1182454
🔄 Запрос #11974 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 148 спецификаций. Всего: 1182602
🔄 Запрос #11975 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 143 спецификаций. Всего: 1182745
🔄 Запрос #11976 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 112 спецификаций. Всего: 1182857
🔄 Запрос #11977 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 105 спецификаций. Всего: 1182962
🔄 Запрос #11978 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 88 спецификаций. Всего: 1183050
🔄 Запрос #11979 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 76 спецификаций. Всего: 1183126
🔄 Запрос #11980 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 79 спецификаций. Всего: 1183205
🔄 Запрос #11981 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 85 спецификаций. Всего: 1183290
🔄 Запрос #11982 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 80 спецификаций. Всего: 1183370
🔄 Запрос #11983 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 87 спецификаций. Всего: 1183457
🔄 Запрос #11984 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 87 спецификаций. Всего: 1183544
🔄 Запрос #11985 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1183632
🔄 Запрос #11986 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 73 спецификаций. Всего: 1183705
🔄 Запрос #11987 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 81 спецификаций. Всего: 1183786
🔄 Запрос #11988 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 94 спецификаций. Всего: 1183880
🔄 Запрос #11989 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 75 спецификаций. Всего: 1183955
🔄 Запрос #11990 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1184070
🔄 Запрос #11991 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1184178
🔄 Запрос #11992 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 104 спецификаций. Всего: 1184282
🔄 Запрос #11993 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 107 спецификаций. Всего: 1184389
🔄 Запрос #11994 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 99 спецификаций. Всего: 1184488
🔄 Запрос #11995 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 97 спецификаций. Всего: 1184585
🔄 Запрос #11996 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 85 спецификаций. Всего: 1184670
🔄 Запрос #11997 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 98 спецификаций. Всего: 1184768
🔄 Запрос #11998 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 94 спецификаций. Всего: 1184862
🔄 Запрос #11999 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 71 спецификаций. Всего: 1184933
🔄 Запрос #12000 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 96 спецификаций. Всего: 1185029
🔄 Запрос #12001 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 64 спецификаций. Всего: 1185093
🔄 Запрос #12002 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 112 спецификаций. Всего: 1185205
🔄 Запрос #12003 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 93 спецификаций. Всего: 1185298
🔄 Запрос #12004 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 69 спецификаций. Всего: 1185367
🔄 Запрос #12005 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 88 спецификаций. Всего: 1185455
🔄 Запрос #12006 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 43 спецификаций. Всего: 1185498
🔄 Запрос #12007 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 64 спецификаций. Всего: 1185562
🔄 Запрос #12008 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1185650
🔄 Запрос #12009 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
📥 Загружено 111 спецификаций. Всего: 1185761
🔄 Запрос #12010 для 2024-05-30 20:44:09 - 2024-06-06 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 69 спецификаций. Всего: 1185830
📅 Обрабатываем диапазон 2024-05-23 20:44:09 - 2024-05-30 20:44:09 (попытка 1/5)
🔄 Запрос #12011 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 93 спецификаций. Всего: 1185923
🔄 Запрос #12012 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 92 спецификаций. Всего: 1186015
🔄 Запрос #12013 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 109 спецификаций. Всего: 1186124
🔄 Запрос #12014 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 111 спецификаций. Всего: 1186235
🔄 Запрос #12015 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 113 спецификаций. Всего: 1186348
🔄 Запрос #12016 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 125 спецификаций. Всего: 1186473
📤 Сохранено 10003 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #12017 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 102 спецификаций. Всего: 1186575
🔄 Запрос #12018 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 108 спецификаций. Всего: 1186683
🔄 Запрос #12019 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 94 спецификаций. Всего: 1186777
🔄 Запрос #12020 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 99 спецификаций. Всего: 1186876
🔄 Запрос #12021 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 95 спецификаций. Всего: 1186971
🔄 Запрос #12022 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 97 спецификаций. Всего: 1187068
🔄 Запрос #12023 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 104 спецификаций. Всего: 1187172
🔄 Запрос #12024 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 88 спецификаций. Всего: 1187260
🔄 Запрос #12025 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 109 спецификаций. Всего: 1187369
🔄 Запрос #12026 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1187479
🔄 Запрос #12027 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 83 спецификаций. Всего: 1187562
🔄 Запрос #12028 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 100 спецификаций. Всего: 1187662
🔄 Запрос #12029 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 84 спецификаций. Всего: 1187746
🔄 Запрос #12030 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 91 спецификаций. Всего: 1187837
🔄 Запрос #12031 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 91 спецификаций. Всего: 1187928
🔄 Запрос #12032 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 66 спецификаций. Всего: 1187994
🔄 Запрос #12033 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 82 спецификаций. Всего: 1188076
🔄 Запрос #12034 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 99 спецификаций. Всего: 1188175
🔄 Запрос #12035 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 91 спецификаций. Всего: 1188266
🔄 Запрос #12036 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 116 спецификаций. Всего: 1188382
🔄 Запрос #12037 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 130 спецификаций. Всего: 1188512
🔄 Запрос #12038 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 106 спецификаций. Всего: 1188618
🔄 Запрос #12039 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 103 спецификаций. Всего: 1188721
🔄 Запрос #12040 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1188829
🔄 Запрос #12041 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 84 спецификаций. Всего: 1188913
🔄 Запрос #12042 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 100 спецификаций. Всего: 1189013
🔄 Запрос #12043 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 106 спецификаций. Всего: 1189119
🔄 Запрос #12044 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 103 спецификаций. Всего: 1189222
🔄 Запрос #12045 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 82 спецификаций. Всего: 1189304
🔄 Запрос #12046 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 95 спецификаций. Всего: 1189399
🔄 Запрос #12047 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 94 спецификаций. Всего: 1189493
🔄 Запрос #12048 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 92 спецификаций. Всего: 1189585
🔄 Запрос #12049 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1189707
🔄 Запрос #12050 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 128 спецификаций. Всего: 1189835
🔄 Запрос #12051 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 113 спецификаций. Всего: 1189948
🔄 Запрос #12052 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 108 спецификаций. Всего: 1190056
🔄 Запрос #12053 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 96 спецификаций. Всего: 1190152
🔄 Запрос #12054 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 89 спецификаций. Всего: 1190241
🔄 Запрос #12055 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 78 спецификаций. Всего: 1190319
🔄 Запрос #12056 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 83 спецификаций. Всего: 1190402
🔄 Запрос #12057 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 131 спецификаций. Всего: 1190533
🔄 Запрос #12058 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 96 спецификаций. Всего: 1190629
🔄 Запрос #12059 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 1190713
🔄 Запрос #12060 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 131 спецификаций. Всего: 1190844
🔄 Запрос #12061 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 132 спецификаций. Всего: 1190976
🔄 Запрос #12062 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 73 спецификаций. Всего: 1191049
🔄 Запрос #12063 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1191163
🔄 Запрос #12064 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 118 спецификаций. Всего: 1191281
🔄 Запрос #12065 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 126 спецификаций. Всего: 1191407
🔄 Запрос #12066 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 117 спецификаций. Всего: 1191524
🔄 Запрос #12067 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 115 спецификаций. Всего: 1191639
🔄 Запрос #12068 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 111 спецификаций. Всего: 1191750
🔄 Запрос #12069 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09

📥 Загружено 110 спецификаций. Всего: 1191860
🔄 Запрос #12070 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 113 спецификаций. Всего: 1191973
🔄 Запрос #12071 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 107 спецификаций. Всего: 1192080
🔄 Запрос #12072 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 112 спецификаций. Всего: 1192192
🔄 Запрос #12073 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 118 спецификаций. Всего: 1192310
🔄 Запрос #12074 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 110 спецификаций. Всего: 1192420
🔄 Запрос #12075 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 102 спецификаций. Всего: 1192522
🔄 Запрос #12076 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 103 спецификаций. Всего: 1192625
🔄 Запрос #12077 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 66 спецификаций. Всего: 1192691
🔄 Запрос #12078 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 89 спецификаций. Всего: 1192780
🔄 Запрос #12079 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 109 спецификаций. Всего: 1192889
🔄 Запрос #12080 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 85 спецификаций. Всего: 1192974
🔄 Запрос #12081 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 57 спецификаций. Всего: 1193031
🔄 Запрос #12082 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 79 спецификаций. Всего: 1193110
🔄 Запрос #12083 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 1193193
🔄 Запрос #12084 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 81 спецификаций. Всего: 1193274
🔄 Запрос #12085 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 101 спецификаций. Всего: 1193375
🔄 Запрос #12086 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 70 спецификаций. Всего: 1193445
🔄 Запрос #12087 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 78 спецификаций. Всего: 1193523
🔄 Запрос #12088 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 77 спецификаций. Всего: 1193600
🔄 Запрос #12089 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 67 спецификаций. Всего: 1193667
🔄 Запрос #12090 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 58 спецификаций. Всего: 1193725
🔄 Запрос #12091 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 82 спецификаций. Всего: 1193807
🔄 Запрос #12092 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 99 спецификаций. Всего: 1193906
🔄 Запрос #12093 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 1193992
🔄 Запрос #12094 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 95 спецификаций. Всего: 1194087
🔄 Запрос #12095 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 113 спецификаций. Всего: 1194200
🔄 Запрос #12096 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 117 спецификаций. Всего: 1194317
🔄 Запрос #12097 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 99 спецификаций. Всего: 1194416
🔄 Запрос #12098 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 96 спецификаций. Всего: 1194512
🔄 Запрос #12099 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 96 спецификаций. Всего: 1194608
🔄 Запрос #12100 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1194701
🔄 Запрос #12101 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 96 спецификаций. Всего: 1194797
🔄 Запрос #12102 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 95 спецификаций. Всего: 1194892
🔄 Запрос #12103 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 73 спецификаций. Всего: 1194965
🔄 Запрос #12104 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 113 спецификаций. Всего: 1195078
🔄 Запрос #12105 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 100 спецификаций. Всего: 1195178
🔄 Запрос #12106 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 104 спецификаций. Всего: 1195282
🔄 Запрос #12107 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 73 спецификаций. Всего: 1195355
🔄 Запрос #12108 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 125 спецификаций. Всего: 1195480
🔄 Запрос #12109 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1195578
🔄 Запрос #12110 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 72 спецификаций. Всего: 1195650
🔄 Запрос #12111 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 88 спецификаций. Всего: 1195738
🔄 Запрос #12112 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 71 спецификаций. Всего: 1195809
🔄 Запрос #12113 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 93 спецификаций. Всего: 1195902
🔄 Запрос #12114 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 109 спецификаций. Всего: 1196011
🔄 Запрос #12115 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 131 спецификаций. Всего: 1196142
🔄 Запрос #12116 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 136 спецификаций. Всего: 1196278
🔄 Запрос #12117 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 112 спецификаций. Всего: 1196390
🔄 Запрос #12118 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 126 спецификаций. Всего: 1196516
📤 Сохранено 10043 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #12119 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 118 спецификаций. Всего: 1196634
🔄 Запрос #12120 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 117 спецификаций. Всего: 1196751
🔄 Запрос #12121 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 112 спецификаций. Всего: 1196863
🔄 Запрос #12122 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 110 спецификаций. Всего: 1196973
🔄 Запрос #12123 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 103 спецификаций. Всего: 1197076
🔄 Запрос #12124 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 113 спецификаций. Всего: 1197189
🔄 Запрос #12125 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 106 спецификаций. Всего: 1197295
🔄 Запрос #12126 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 72 спецификаций. Всего: 1197367
🔄 Запрос #12127 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 112 спецификаций. Всего: 1197479
🔄 Запрос #12128 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 96 спецификаций. Всего: 1197575
🔄 Запрос #12129 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 57 спецификаций. Всего: 1197632
🔄 Запрос #12130 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 95 спецификаций. Всего: 1197727
🔄 Запрос #12131 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 110 спецификаций. Всего: 1197837
🔄 Запрос #12132 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 97 спецификаций. Всего: 1197934
🔄 Запрос #12133 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1198034
🔄 Запрос #12134 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 75 спецификаций. Всего: 1198109
🔄 Запрос #12135 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1198202
🔄 Запрос #12136 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 93 спецификаций. Всего: 1198295
🔄 Запрос #12137 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 97 спецификаций. Всего: 1198392

🔄 Запрос #12138 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 77 спецификаций. Всего: 1198469
🔄 Запрос #12139 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 69 спецификаций. Всего: 1198538
🔄 Запрос #12140 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 66 спецификаций. Всего: 1198604
🔄 Запрос #12141 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 88 спецификаций. Всего: 1198692
🔄 Запрос #12142 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 91 спецификаций. Всего: 1198783
🔄 Запрос #12143 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 121 спецификаций. Всего: 1198904
🔄 Запрос #12144 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 126 спецификаций. Всего: 1199030
🔄 Запрос #12145 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 118 спецификаций. Всего: 1199148
🔄 Запрос #12146 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 117 спецификаций. Всего: 1199265
🔄 Запрос #12147 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 128 спецификаций. Всего: 1199393
🔄 Запрос #12148 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 117 спецификаций. Всего: 1199510
🔄 Запрос #12149 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 126 спецификаций. Всего: 1199636
🔄 Запрос #12150 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 142 спецификаций. Всего: 1199778
🔄 Запрос #12151 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 128 спецификаций. Всего: 1199906
🔄 Запрос #12152 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 119 спецификаций. Всего: 1200025
🔄 Запрос #12153 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1200116
🔄 Запрос #12154 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 92 спецификаций. Всего: 1200208
🔄 Запрос #12155 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 109 спецификаций. Всего: 1200317
🔄 Запрос #12156 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 75 спецификаций. Всего: 1200392
🔄 Запрос #12157 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 96 спецификаций. Всего: 1200488
🔄 Запрос #12158 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 111 спецификаций. Всего: 1200599
🔄 Запрос #12159 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 112 спецификаций. Всего: 1200711
🔄 Запрос #12160 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 85 спецификаций. Всего: 1200796
🔄 Запрос #12161 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 65 спецификаций. Всего: 1200861
🔄 Запрос #12162 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 146 спецификаций. Всего: 1201007
🔄 Запрос #12163 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 150 спецификаций. Всего: 1201157
🔄 Запрос #12164 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 101 спецификаций. Всего: 1201258
🔄 Запрос #12165 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 104 спецификаций. Всего: 1201362
🔄 Запрос #12166 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 74 спецификаций. Всего: 1201436
🔄 Запрос #12167 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 122 спецификаций. Всего: 1201558
🔄 Запрос #12168 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 127 спецификаций. Всего: 1201685
🔄 Запрос #12169 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 143 спецификаций. Всего: 1201828
🔄 Запрос #12170 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 116 спецификаций. Всего: 1201944
🔄 Запрос #12171 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 132 спецификаций. Всего: 1202076
🔄 Запрос #12172 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 108 спецификаций. Всего: 1202184
🔄 Запрос #12173 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 122 спецификаций. Всего: 1202306
🔄 Запрос #12174 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 108 спецификаций. Всего: 1202414
🔄 Запрос #12175 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 113 спецификаций. Всего: 1202527
🔄 Запрос #12176 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 104 спецификаций. Всего: 1202631
🔄 Запрос #12177 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 116 спецификаций. Всего: 1202747
🔄 Запрос #12178 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 113 спецификаций. Всего: 1202860
🔄 Запрос #12179 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 119 спецификаций. Всего: 1202979
🔄 Запрос #12180 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 118 спецификаций. Всего: 1203097
🔄 Запрос #12181 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 111 спецификаций. Всего: 1203208
🔄 Запрос #12182 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 133 спецификаций. Всего: 1203341
🔄 Запрос #12183 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 110 спецификаций. Всего: 1203451
🔄 Запрос #12184 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 122 спецификаций. Всего: 1203573
🔄 Запрос #12185 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 122 спецификаций. Всего: 1203695
🔄 Запрос #12186 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 95 спецификаций. Всего: 1203790
🔄 Запрос #12187 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 92 спецификаций. Всего: 1203882
🔄 Запрос #12188 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 70 спецификаций. Всего: 1203952
🔄 Запрос #12189 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 71 спецификаций. Всего: 1204023
🔄 Запрос #12190 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 77 спецификаций. Всего: 1204100
🔄 Запрос #12191 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 82 спецификаций. Всего: 1204182
🔄 Запрос #12192 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 72 спецификаций. Всего: 1204254
🔄 Запрос #12193 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 101 спецификаций. Всего: 1204355
🔄 Запрос #12194 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 104 спецификаций. Всего: 1204459
🔄 Запрос #12195 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1204578
🔄 Запрос #12196 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 111 спецификаций. Всего: 1204689
🔄 Запрос #12197 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 93 спецификаций. Всего: 1204782
🔄 Запрос #12198 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 107 спецификаций. Всего: 1204889
🔄 Запрос #12199 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1204995
🔄 Запрос #12200 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 105 спецификаций. Всего: 1205100
🔄 Запрос #12201 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 99 спецификаций. Всего: 1205199
🔄 Запрос #12202 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 93 спецификаций. Всего: 1205292
🔄 Запрос #12203 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 81 спецификаций. Всего: 1205373
🔄 Запрос #12204 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 102 спецификаций. Всего: 1205475
🔄 Запрос #12205 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 99 спецификаций. Всего: 1205574

🔄 Запрос #12206 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 103 спецификаций. Всего: 1205677
🔄 Запрос #12207 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 121 спецификаций. Всего: 1205798
🔄 Запрос #12208 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 95 спецификаций. Всего: 1205893
🔄 Запрос #12209 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 88 спецификаций. Всего: 1205981
🔄 Запрос #12210 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 137 спецификаций. Всего: 1206118
🔄 Запрос #12211 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 124 спецификаций. Всего: 1206242
🔄 Запрос #12212 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 108 спецификаций. Всего: 1206350
🔄 Запрос #12213 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 118 спецификаций. Всего: 1206468
🔄 Запрос #12214 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 106 спецификаций. Всего: 1206574
📤 Сохранено 10058 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #12215 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 100 спецификаций. Всего: 1206674
🔄 Запрос #12216 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 79 спецификаций. Всего: 1206753
🔄 Запрос #12217 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 133 спецификаций. Всего: 1206886
🔄 Запрос #12218 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 105 спецификаций. Всего: 1206991
🔄 Запрос #12219 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 131 спецификаций. Всего: 1207122
🔄 Запрос #12220 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 82 спецификаций. Всего: 1207204
🔄 Запрос #12221 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 54 спецификаций. Всего: 1207258
🔄 Запрос #12222 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 87 спецификаций. Всего: 1207345
🔄 Запрос #12223 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 146 спецификаций. Всего: 1207491
🔄 Запрос #12224 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 128 спецификаций. Всего: 1207619
🔄 Запрос #12225 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 106 спецификаций. Всего: 1207725
🔄 Запрос #12226 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 101 спецификаций. Всего: 1207826
🔄 Запрос #12227 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1207926
🔄 Запрос #12228 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 77 спецификаций. Всего: 1208003
🔄 Запрос #12229 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 153 спецификаций. Всего: 1208156
🔄 Запрос #12230 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 239 спецификаций. Всего: 1208395
🔄 Запрос #12231 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 144 спецификаций. Всего: 1208539
🔄 Запрос #12232 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 104 спецификаций. Всего: 1208643
🔄 Запрос #12233 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1208761
🔄 Запрос #12234 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 135 спецификаций. Всего: 1208896
🔄 Запрос #12235 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 100 спецификаций. Всего: 1208996
🔄 Запрос #12236 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 66 спецификаций. Всего: 1209062
🔄 Запрос #12237 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 81 спецификаций. Всего: 1209143
🔄 Запрос #12238 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 78 спецификаций. Всего: 1209221
🔄 Запрос #12239 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 87 спецификаций. Всего: 1209308
🔄 Запрос #12240 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 83 спецификаций. Всего: 1209391
🔄 Запрос #12241 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 110 спецификаций. Всего: 1209501
🔄 Запрос #12242 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 113 спецификаций. Всего: 1209614
🔄 Запрос #12243 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1209710
🔄 Запрос #12244 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 117 спецификаций. Всего: 1209827
🔄 Запрос #12245 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 117 спецификаций. Всего: 1209944
🔄 Запрос #12246 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 108 спецификаций. Всего: 1210052
🔄 Запрос #12247 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 74 спецификаций. Всего: 1210126
🔄 Запрос #12248 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 105 спецификаций. Всего: 1210231
🔄 Запрос #12249 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 80 спецификаций. Всего: 1210311
🔄 Запрос #12250 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 89 спецификаций. Всего: 1210400
🔄 Запрос #12251 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 66 спецификаций. Всего: 1210466
🔄 Запрос #12252 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 73 спецификаций. Всего: 1210539
🔄 Запрос #12253 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 64 спецификаций. Всего: 1210603
🔄 Запрос #12254 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 89 спецификаций. Всего: 1210692
🔄 Запрос #12255 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 114 спецификаций. Всего: 1210806
🔄 Запрос #12256 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 104 спецификаций. Всего: 1210910
🔄 Запрос #12257 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 152 спецификаций. Всего: 1211062
🔄 Запрос #12258 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 146 спецификаций. Всего: 1211208
🔄 Запрос #12259 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 102 спецификаций. Всего: 1211310
🔄 Запрос #12260 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 113 спецификаций. Всего: 1211423
🔄 Запрос #12261 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 110 спецификаций. Всего: 1211533
🔄 Запрос #12262 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 111 спецификаций. Всего: 1211644
🔄 Запрос #12263 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 112 спецификаций. Всего: 1211756
🔄 Запрос #12264 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 129 спецификаций. Всего: 1211885
🔄 Запрос #12265 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 129 спецификаций. Всего: 1212014
🔄 Запрос #12266 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 119 спецификаций. Всего: 1212133
🔄 Запрос #12267 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 96 спецификаций. Всего: 1212229
🔄 Запрос #12268 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 95 спецификаций. Всего: 1212324
🔄 Запрос #12269 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 101 спецификаций. Всего: 1212425
🔄 Запрос #12270 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 98 спецификаций. Всего: 1212523
🔄 Запрос #12271 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 91 спецификаций. Всего: 1212614
🔄 Запрос #12272 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 87 спецификаций. Всего: 1212701
🔄 Запрос #12273 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 96 спецификаций. Всего: 1212797
🔄 Запрос #12274 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09

📥 Загружено 100 спецификаций. Всего: 1212897
🔄 Запрос #12275 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 60 спецификаций. Всего: 1212957
🔄 Запрос #12276 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 97 спецификаций. Всего: 1213054
🔄 Запрос #12277 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1213167
🔄 Запрос #12278 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 110 спецификаций. Всего: 1213277
🔄 Запрос #12279 для 2024-05-23 20:44:09 - 2024-05-30 20:44:09
📥 Загружено 22 спецификаций. Всего: 1213299
📅 Обрабатываем диапазон 2024-05-16 20:44:09 - 2024-05-23 20:44:09 (попытка 1/5)
🔄 Запрос #12280 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 144 спецификаций. Всего: 1213443
🔄 Запрос #12281 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 153 спецификаций. Всего: 1213596
🔄 Запрос #12282 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 146 спецификаций. Всего: 1213742
🔄 Запрос #12283 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 151 спецификаций. Всего: 1213893
🔄 Запрос #12284 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 158 спецификаций. Всего: 1214051
🔄 Запрос #12285 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 116 спецификаций. Всего: 1214167
🔄 Запрос #12286 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 111 спецификаций. Всего: 1214278
🔄 Запрос #12287 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 100 спецификаций. Всего: 1214378
🔄 Запрос #12288 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 105 спецификаций. Всего: 1214483
🔄 Запрос #12289 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 109 спецификаций. Всего: 1214592
🔄 Запрос #12290 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 112 спецификаций. Всего: 1214704
🔄 Запрос #12291 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 113 спецификаций. Всего: 1214817
🔄 Запрос #12292 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 119 спецификаций. Всего: 1214936
🔄 Запрос #12293 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 110 спецификаций. Всего: 1215046
🔄 Запрос #12294 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1215153
🔄 Запрос #12295 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 103 спецификаций. Всего: 1215256
🔄 Запрос #12296 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 101 спецификаций. Всего: 1215357
🔄 Запрос #12297 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 118 спецификаций. Всего: 1215475
🔄 Запрос #12298 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 93 спецификаций. Всего: 1215568
🔄 Запрос #12299 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 101 спецификаций. Всего: 1215669
🔄 Запрос #12300 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 105 спецификаций. Всего: 1215774
🔄 Запрос #12301 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 98 спецификаций. Всего: 1215872
🔄 Запрос #12302 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 106 спецификаций. Всего: 1215978
🔄 Запрос #12303 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 96 спецификаций. Всего: 1216074
🔄 Запрос #12304 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 98 спецификаций. Всего: 1216172
🔄 Запрос #12305 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 114 спецификаций. Всего: 1216286
🔄 Запрос #12306 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 139 спецификаций. Всего: 1216425
🔄 Запрос #12307 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 122 спецификаций. Всего: 1216547
🔄 Запрос #12308 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 113 спецификаций. Всего: 1216660
📤 Сохранено 10086 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #12309 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 97 спецификаций. Всего: 1216757
🔄 Запрос #12310 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1216864
🔄 Запрос #12311 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 112 спецификаций. Всего: 1216976
🔄 Запрос #12312 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 106 спецификаций. Всего: 1217082
🔄 Запрос #12313 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 103 спецификаций. Всего: 1217185
🔄 Запрос #12314 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1217291
🔄 Запрос #12315 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 112 спецификаций. Всего: 1217403
🔄 Запрос #12316 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 108 спецификаций. Всего: 1217511
🔄 Запрос #12317 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 101 спецификаций. Всего: 1217612
🔄 Запрос #12318 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 99 спецификаций. Всего: 1217711
🔄 Запрос #12319 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 90 спецификаций. Всего: 1217801
🔄 Запрос #12320 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 80 спецификаций. Всего: 1217881
🔄 Запрос #12321 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 73 спецификаций. Всего: 1217954
🔄 Запрос #12322 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 103 спецификаций. Всего: 1218057
🔄 Запрос #12323 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 97 спецификаций. Всего: 1218154
🔄 Запрос #12324 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 106 спецификаций. Всего: 1218260
🔄 Запрос #12325 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 106 спецификаций. Всего: 1218366
🔄 Запрос #12326 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1218473
🔄 Запрос #12327 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 74 спецификаций. Всего: 1218547
🔄 Запрос #12328 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 75 спецификаций. Всего: 1218622
🔄 Запрос #12329 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 67 спецификаций. Всего: 1218689
🔄 Запрос #12330 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 95 спецификаций. Всего: 1218784
🔄 Запрос #12331 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 92 спецификаций. Всего: 1218876
🔄 Запрос #12332 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 116 спецификаций. Всего: 1218992
🔄 Запрос #12333 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 127 спецификаций. Всего: 1219119
🔄 Запрос #12334 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 114 спецификаций. Всего: 1219233
🔄 Запрос #12335 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 148 спецификаций. Всего: 1219381
🔄 Запрос #12336 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 127 спецификаций. Всего: 1219508
🔄 Запрос #12337 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 125 спецификаций. Всего: 1219633
🔄 Запрос #12338 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 141 спецификаций. Всего: 1219774
🔄 Запрос #12339 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1219900

🔄 Запрос #12340 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 109 спецификаций. Всего: 1220009
🔄 Запрос #12341 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1220131
🔄 Запрос #12342 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 112 спецификаций. Всего: 1220243
🔄 Запрос #12343 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1220350
🔄 Запрос #12344 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 127 спецификаций. Всего: 1220477
🔄 Запрос #12345 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 106 спецификаций. Всего: 1220583
🔄 Запрос #12346 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 104 спецификаций. Всего: 1220687
🔄 Запрос #12347 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 98 спецификаций. Всего: 1220785
🔄 Запрос #12348 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 105 спецификаций. Всего: 1220890
🔄 Запрос #12349 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 148 спецификаций. Всего: 1221038
🔄 Запрос #12350 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 126 спецификаций. Всего: 1221164
🔄 Запрос #12351 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 105 спецификаций. Всего: 1221269
🔄 Запрос #12352 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1221371
🔄 Запрос #12353 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 103 спецификаций. Всего: 1221474
🔄 Запрос #12354 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 91 спецификаций. Всего: 1221565
🔄 Запрос #12355 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 92 спецификаций. Всего: 1221657
🔄 Запрос #12356 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1221745
🔄 Запрос #12357 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 89 спецификаций. Всего: 1221834
🔄 Запрос #12358 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 80 спецификаций. Всего: 1221914
🔄 Запрос #12359 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 75 спецификаций. Всего: 1221989
🔄 Запрос #12360 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 72 спецификаций. Всего: 1222061
🔄 Запрос #12361 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 74 спецификаций. Всего: 1222135
🔄 Запрос #12362 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 71 спецификаций. Всего: 1222206
🔄 Запрос #12363 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 71 спецификаций. Всего: 1222277
🔄 Запрос #12364 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 97 спецификаций. Всего: 1222374
🔄 Запрос #12365 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 101 спецификаций. Всего: 1222475
🔄 Запрос #12366 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 94 спецификаций. Всего: 1222569
🔄 Запрос #12367 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 92 спецификаций. Всего: 1222661
🔄 Запрос #12368 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 113 спецификаций. Всего: 1222774
🔄 Запрос #12369 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1222880
🔄 Запрос #12370 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 104 спецификаций. Всего: 1222984
🔄 Запрос #12371 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 120 спецификаций. Всего: 1223104
🔄 Запрос #12372 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 105 спецификаций. Всего: 1223209
🔄 Запрос #12373 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 118 спецификаций. Всего: 1223327
🔄 Запрос #12374 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 116 спецификаций. Всего: 1223443
🔄 Запрос #12375 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1223545
🔄 Запрос #12376 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 112 спецификаций. Всего: 1223657
🔄 Запрос #12377 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 108 спецификаций. Всего: 1223765
🔄 Запрос #12378 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 113 спецификаций. Всего: 1223878
🔄 Запрос #12379 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 93 спецификаций. Всего: 1223971
🔄 Запрос #12380 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 102 спецификаций. Всего: 1224073
🔄 Запрос #12381 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 102 спецификаций. Всего: 1224175
🔄 Запрос #12382 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 96 спецификаций. Всего: 1224271
🔄 Запрос #12383 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 104 спецификаций. Всего: 1224375
🔄 Запрос #12384 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 92 спецификаций. Всего: 1224467
🔄 Запрос #12385 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 138 спецификаций. Всего: 1224605
🔄 Запрос #12386 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 133 спецификаций. Всего: 1224738
🔄 Запрос #12387 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 128 спецификаций. Всего: 1224866
🔄 Запрос #12388 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 120 спецификаций. Всего: 1224986
🔄 Запрос #12389 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 81 спецификаций. Всего: 1225067
🔄 Запрос #12390 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 120 спецификаций. Всего: 1225187
🔄 Запрос #12391 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 149 спецификаций. Всего: 1225336
🔄 Запрос #12392 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 151 спецификаций. Всего: 1225487
🔄 Запрос #12393 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 131 спецификаций. Всего: 1225618
🔄 Запрос #12394 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 121 спецификаций. Всего: 1225739
🔄 Запрос #12395 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 155 спецификаций. Всего: 1225894
🔄 Запрос #12396 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 177 спецификаций. Всего: 1226071
🔄 Запрос #12397 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 154 спецификаций. Всего: 1226225
🔄 Запрос #12398 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 149 спецификаций. Всего: 1226374
🔄 Запрос #12399 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 155 спецификаций. Всего: 1226529
🔄 Запрос #12400 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 168 спецификаций. Всего: 1226697
📤 Сохранено 10037 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #12401 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 141 спецификаций. Всего: 1226838
🔄 Запрос #12402 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 134 спецификаций. Всего: 1226972
🔄 Запрос #12403 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 121 спецификаций. Всего: 1227093
🔄 Запрос #12404 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 101 спецификаций. Всего: 1227194
🔄 Запрос #12405 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1227298
🔄 Запрос #12406 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 111 спецификаций. Всего: 1227409
🔄 Запрос #12407 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 86 спецификаций. Всего: 1227495
🔄 Запрос #12408 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1227590
🔄 Запрос #12409 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 116 спецификаций. Всего: 1227706
🔄 Запрос #12410 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 121 спецификаций. Всего: 1227827
🔄 Запрос #12411 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1227934
🔄 Запрос #12412 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 111 спецификаций. Всего: 1228045
🔄 Запрос #12413 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1228154
🔄 Запрос #12414 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 109 спецификаций. Всего: 1228263
🔄 Запрос #12415 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 123 спецификаций. Всего: 1228386
🔄 Запрос #12416 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 105 спецификаций. Всего: 1228491
🔄 Запрос #12417 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 104 спецификаций. Всего: 1228595
🔄 Запрос #12418 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 110 спецификаций. Всего: 1228705
🔄 Запрос #12419 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 120 спецификаций. Всего: 1228825
🔄 Запрос #12420 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 131 спецификаций. Всего: 1228956
🔄 Запрос #12421 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 103 спецификаций. Всего: 1229059
🔄 Запрос #12422 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 92 спецификаций. Всего: 1229151
🔄 Запрос #12423 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 77 спецификаций. Всего: 1229228
🔄 Запрос #12424 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 90 спецификаций. Всего: 1229318
🔄 Запрос #12425 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 90 спецификаций. Всего: 1229408
🔄 Запрос #12426 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 81 спецификаций. Всего: 1229489
🔄 Запрос #12427 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 66 спецификаций. Всего: 1229555
🔄 Запрос #12428 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 70 спецификаций. Всего: 1229625
🔄 Запрос #12429 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 116 спецификаций. Всего: 1229741
🔄 Запрос #12430 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1229848
🔄 Запрос #12431 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 125 спецификаций. Всего: 1229973
🔄 Запрос #12432 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 105 спецификаций. Всего: 1230078
🔄 Запрос #12433 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 119 спецификаций. Всего: 1230197
🔄 Запрос #12434 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 136 спецификаций. Всего: 1230333
🔄 Запрос #12435 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 122 спецификаций. Всего: 1230455
🔄 Запрос #12436 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 116 спецификаций. Всего: 1230571
🔄 Запрос #12437 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 108 спецификаций. Всего: 1230679
🔄 Запрос #12438 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 121 спецификаций. Всего: 1230800
🔄 Запрос #12439 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 103 спецификаций. Всего: 1230903
🔄 Запрос #12440 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 88 спецификаций. Всего: 1230991
🔄 Запрос #12441 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1231098
🔄 Запрос #12442 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 113 спецификаций. Всего: 1231211
🔄 Запрос #12443 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 112 спецификаций. Всего: 1231323
🔄 Запрос #12444 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 106 спецификаций. Всего: 1231429
🔄 Запрос #12445 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 101 спецификаций. Всего: 1231530
🔄 Запрос #12446 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 100 спецификаций. Всего: 1231630
🔄 Запрос #12447 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 103 спецификаций. Всего: 1231733
🔄 Запрос #12448 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 111 спецификаций. Всего: 1231844
🔄 Запрос #12449 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1231951
🔄 Запрос #12450 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 106 спецификаций. Всего: 1232057
🔄 Запрос #12451 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 79 спецификаций. Всего: 1232136
🔄 Запрос #12452 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 95 спецификаций. Всего: 1232231
🔄 Запрос #12453 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 105 спецификаций. Всего: 1232336
🔄 Запрос #12454 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 97 спецификаций. Всего: 1232433
🔄 Запрос #12455 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 156 спецификаций. Всего: 1232589
🔄 Запрос #12456 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 132 спецификаций. Всего: 1232721
🔄 Запрос #12457 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 124 спецификаций. Всего: 1232845
🔄 Запрос #12458 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 118 спецификаций. Всего: 1232963
🔄 Запрос #12459 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 123 спецификаций. Всего: 1233086
🔄 Запрос #12460 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 108 спецификаций. Всего: 1233194
🔄 Запрос #12461 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 124 спецификаций. Всего: 1233318
🔄 Запрос #12462 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 104 спецификаций. Всего: 1233422
🔄 Запрос #12463 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 132 спецификаций. Всего: 1233554
🔄 Запрос #12464 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 110 спецификаций. Всего: 1233664
🔄 Запрос #12465 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 115 спецификаций. Всего: 1233779
🔄 Запрос #12466 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 126 спецификаций. Всего: 1233905
🔄 Запрос #12467 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 125 спецификаций. Всего: 1234030
🔄 Запрос #12468 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 113 спецификаций. Всего: 1234143
🔄 Запрос #12469 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 111 спецификаций. Всего: 1234254
🔄 Запрос #12470 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 132 спецификаций. Всего: 1234386
🔄 Запрос #12471 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 109 спецификаций. Всего: 1234495
🔄 Запрос #12472 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 123 спецификаций. Всего: 1234618
🔄 Запрос #12473 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 121 спецификаций. Всего: 1234739
🔄 Запрос #12474 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09

📥 Загружено 115 спецификаций. Всего: 1234854
🔄 Запрос #12475 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 112 спецификаций. Всего: 1234966
🔄 Запрос #12476 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1235084
🔄 Запрос #12477 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 118 спецификаций. Всего: 1235202
🔄 Запрос #12478 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 109 спецификаций. Всего: 1235311
🔄 Запрос #12479 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 113 спецификаций. Всего: 1235424
🔄 Запрос #12480 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 121 спецификаций. Всего: 1235545
🔄 Запрос #12481 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 101 спецификаций. Всего: 1235646
🔄 Запрос #12482 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 96 спецификаций. Всего: 1235742
🔄 Запрос #12483 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 73 спецификаций. Всего: 1235815
🔄 Запрос #12484 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 98 спецификаций. Всего: 1235913
🔄 Запрос #12485 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 106 спецификаций. Всего: 1236019
🔄 Запрос #12486 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 108 спецификаций. Всего: 1236127
🔄 Запрос #12487 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 97 спецификаций. Всего: 1236224
🔄 Запрос #12488 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 96 спецификаций. Всего: 1236320
🔄 Запрос #12489 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 102 спецификаций. Всего: 1236422
🔄 Запрос #12490 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 128 спецификаций. Всего: 1236550
🔄 Запрос #12491 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 101 спецификаций. Всего: 1236651
🔄 Запрос #12492 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 91 спецификаций. Всего: 1236742
📤 Сохранено 10045 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #12493 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 119 спецификаций. Всего: 1236861
🔄 Запрос #12494 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 113 спецификаций. Всего: 1236974
🔄 Запрос #12495 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 130 спецификаций. Всего: 1237104
🔄 Запрос #12496 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 83 спецификаций. Всего: 1237187
🔄 Запрос #12497 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 111 спецификаций. Всего: 1237298
🔄 Запрос #12498 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 122 спецификаций. Всего: 1237420
🔄 Запрос #12499 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 121 спецификаций. Всего: 1237541
🔄 Запрос #12500 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 108 спецификаций. Всего: 1237649
🔄 Запрос #12501 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1237756
🔄 Запрос #12502 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 92 спецификаций. Всего: 1237848
🔄 Запрос #12503 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 93 спецификаций. Всего: 1237941
🔄 Запрос #12504 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 106 спецификаций. Всего: 1238047
🔄 Запрос #12505 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 109 спецификаций. Всего: 1238156
🔄 Запрос #12506 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 87 спецификаций. Всего: 1238243
🔄 Запрос #12507 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 81 спецификаций. Всего: 1238324
🔄 Запрос #12508 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 85 спецификаций. Всего: 1238409
🔄 Запрос #12509 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 103 спецификаций. Всего: 1238512
🔄 Запрос #12510 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 99 спецификаций. Всего: 1238611
🔄 Запрос #12511 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1238718
🔄 Запрос #12512 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 108 спецификаций. Всего: 1238826
🔄 Запрос #12513 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 101 спецификаций. Всего: 1238927
🔄 Запрос #12514 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 103 спецификаций. Всего: 1239030
🔄 Запрос #12515 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 100 спецификаций. Всего: 1239130
🔄 Запрос #12516 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 104 спецификаций. Всего: 1239234
🔄 Запрос #12517 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 100 спецификаций. Всего: 1239334
🔄 Запрос #12518 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 92 спецификаций. Всего: 1239426
🔄 Запрос #12519 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 84 спецификаций. Всего: 1239510
🔄 Запрос #12520 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 96 спецификаций. Всего: 1239606
🔄 Запрос #12521 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 121 спецификаций. Всего: 1239727
🔄 Запрос #12522 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 111 спецификаций. Всего: 1239838
🔄 Запрос #12523 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 126 спецификаций. Всего: 1239964
🔄 Запрос #12524 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 119 спецификаций. Всего: 1240083
🔄 Запрос #12525 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 110 спецификаций. Всего: 1240193
🔄 Запрос #12526 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1240307
🔄 Запрос #12527 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 160 спецификаций. Всего: 1240467
🔄 Запрос #12528 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 136 спецификаций. Всего: 1240603
🔄 Запрос #12529 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 123 спецификаций. Всего: 1240726
🔄 Запрос #12530 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 137 спецификаций. Всего: 1240863
🔄 Запрос #12531 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 102 спецификаций. Всего: 1240965
🔄 Запрос #12532 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 94 спецификаций. Всего: 1241059
🔄 Запрос #12533 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 89 спецификаций. Всего: 1241148
🔄 Запрос #12534 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 1241247
🔄 Запрос #12535 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 103 спецификаций. Всего: 1241350
🔄 Запрос #12536 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 108 спецификаций. Всего: 1241458
🔄 Запрос #12537 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 79 спецификаций. Всего: 1241537
🔄 Запрос #12538 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 61 спецификаций. Всего: 1241598
🔄 Запрос #12539 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 70 спецификаций. Всего: 1241668
🔄 Запрос #12540 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 85 спецификаций. Всего: 1241753
🔄 Запрос #12541 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 105 спецификаций. Всего: 1241858
🔄 Запрос #12542 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 88 спецификаций. Всего: 1241946
🔄 Запрос #12543 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 97 спецификаций. Всего: 1242043
🔄 Запрос #12544 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 1242127
🔄 Запрос #12545 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 94 спецификаций. Всего: 1242221
🔄 Запрос #12546 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1242309
🔄 Запрос #12547 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 78 спецификаций. Всего: 1242387
🔄 Запрос #12548 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 78 спецификаций. Всего: 1242465
🔄 Запрос #12549 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 72 спецификаций. Всего: 1242537
🔄 Запрос #12550 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 82 спецификаций. Всего: 1242619
🔄 Запрос #12551 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 78 спецификаций. Всего: 1242697
🔄 Запрос #12552 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 74 спецификаций. Всего: 1242771
🔄 Запрос #12553 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 57 спецификаций. Всего: 1242828
🔄 Запрос #12554 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 86 спецификаций. Всего: 1242914
🔄 Запрос #12555 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1243021
🔄 Запрос #12556 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 111 спецификаций. Всего: 1243132
🔄 Запрос #12557 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 107 спецификаций. Всего: 1243239
🔄 Запрос #12558 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 100 спецификаций. Всего: 1243339
🔄 Запрос #12559 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 90 спецификаций. Всего: 1243429
🔄 Запрос #12560 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 119 спецификаций. Всего: 1243548
🔄 Запрос #12561 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 123 спецификаций. Всего: 1243671
🔄 Запрос #12562 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 130 спецификаций. Всего: 1243801
🔄 Запрос #12563 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 118 спецификаций. Всего: 1243919
🔄 Запрос #12564 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1244026
🔄 Запрос #12565 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 104 спецификаций. Всего: 1244130
🔄 Запрос #12566 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 99 спецификаций. Всего: 1244229
🔄 Запрос #12567 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 126 спецификаций. Всего: 1244355
🔄 Запрос #12568 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 107 спецификаций. Всего: 1244462
🔄 Запрос #12569 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 93 спецификаций. Всего: 1244555
🔄 Запрос #12570 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 94 спецификаций. Всего: 1244649
🔄 Запрос #12571 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 95 спецификаций. Всего: 1244744
🔄 Запрос #12572 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 101 спецификаций. Всего: 1244845
🔄 Запрос #12573 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 105 спецификаций. Всего: 1244950
🔄 Запрос #12574 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 96 спецификаций. Всего: 1245046
🔄 Запрос #12575 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 95 спецификаций. Всего: 1245141
🔄 Запрос #12576 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 85 спецификаций. Всего: 1245226
🔄 Запрос #12577 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 99 спецификаций. Всего: 1245325
🔄 Запрос #12578 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 93 спецификаций. Всего: 1245418
🔄 Запрос #12579 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 1245502
🔄 Запрос #12580 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 90 спецификаций. Всего: 1245592
🔄 Запрос #12581 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 99 спецификаций. Всего: 1245691
🔄 Запрос #12582 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 91 спецификаций. Всего: 1245782
🔄 Запрос #12583 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 151 спецификаций. Всего: 1245933
🔄 Запрос #12584 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 1246023
🔄 Запрос #12585 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 56 спецификаций. Всего: 1246079
🔄 Запрос #12586 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 119 спецификаций. Всего: 1246198
🔄 Запрос #12587 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 109 спецификаций. Всего: 1246307
🔄 Запрос #12588 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
📥 Загружено 109 спецификаций. Всего: 1246416
🔄 Запрос #12589 для 2024-05-16 20:44:09 - 2024-05-23 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 34 спецификаций. Всего: 1246450
📅 Обрабатываем диапазон 2024-05-09 20:44:09 - 2024-05-16 20:44:09 (попытка 1/5)
🔄 Запрос #12590 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 119 спецификаций. Всего: 1246569
🔄 Запрос #12591 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1246687
🔄 Запрос #12592 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 137 спецификаций. Всего: 1246824
📤 Сохранено 10082 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #12593 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 141 спецификаций. Всего: 1246965
🔄 Запрос #12594 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 107 спецификаций. Всего: 1247072
🔄 Запрос #12595 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 124 спецификаций. Всего: 1247196
🔄 Запрос #12596 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 115 спецификаций. Всего: 1247311
🔄 Запрос #12597 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 128 спецификаций. Всего: 1247439
🔄 Запрос #12598 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 122 спецификаций. Всего: 1247561
🔄 Запрос #12599 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 116 спецификаций. Всего: 1247677
🔄 Запрос #12600 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 122 спецификаций. Всего: 1247799
🔄 Запрос #12601 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 117 спецификаций. Всего: 1247916
🔄 Запрос #12602 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1248022
🔄 Запрос #12603 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 111 спецификаций. Всего: 1248133
🔄 Запрос #12604 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 93 спецификаций. Всего: 1248226
🔄 Запрос #12605 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 91 спецификаций. Всего: 1248317
🔄 Запрос #12606 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 90 спецификаций. Всего: 1248407
🔄 Запрос #12607 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 1248491

🔄 Запрос #12608 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 89 спецификаций. Всего: 1248580
🔄 Запрос #12609 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 96 спецификаций. Всего: 1248676
🔄 Запрос #12610 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 140 спецификаций. Всего: 1248816
🔄 Запрос #12611 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 90 спецификаций. Всего: 1248906
🔄 Запрос #12612 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 89 спецификаций. Всего: 1248995
🔄 Запрос #12613 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 102 спецификаций. Всего: 1249097
🔄 Запрос #12614 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1249201
🔄 Запрос #12615 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 107 спецификаций. Всего: 1249308
🔄 Запрос #12616 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 86 спецификаций. Всего: 1249394
🔄 Запрос #12617 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 1249480
🔄 Запрос #12618 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 96 спецификаций. Всего: 1249576
🔄 Запрос #12619 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 84 спецификаций. Всего: 1249660
🔄 Запрос #12620 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 82 спецификаций. Всего: 1249742
🔄 Запрос #12621 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 68 спецификаций. Всего: 1249810
🔄 Запрос #12622 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 54 спецификаций. Всего: 1249864
🔄 Запрос #12623 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 53 спецификаций. Всего: 1249917
🔄 Запрос #12624 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 64 спецификаций. Всего: 1249981
🔄 Запрос #12625 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 76 спецификаций. Всего: 1250057
🔄 Запрос #12626 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 93 спецификаций. Всего: 1250150
🔄 Запрос #12627 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 109 спецификаций. Всего: 1250259
🔄 Запрос #12628 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 102 спецификаций. Всего: 1250361
🔄 Запрос #12629 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 96 спецификаций. Всего: 1250457
🔄 Запрос #12630 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 99 спецификаций. Всего: 1250556
🔄 Запрос #12631 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 108 спецификаций. Всего: 1250664
🔄 Запрос #12632 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 89 спецификаций. Всего: 1250753
🔄 Запрос #12633 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 102 спецификаций. Всего: 1250855
🔄 Запрос #12634 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 98 спецификаций. Всего: 1250953
🔄 Запрос #12635 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1251049
🔄 Запрос #12636 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 89 спецификаций. Всего: 1251138
🔄 Запрос #12637 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 89 спецификаций. Всего: 1251227
🔄 Запрос #12638 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 113 спецификаций. Всего: 1251340
🔄 Запрос #12639 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 97 спецификаций. Всего: 1251437
🔄 Запрос #12640 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 113 спецификаций. Всего: 1251550
🔄 Запрос #12641 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1251656
🔄 Запрос #12642 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 122 спецификаций. Всего: 1251778
🔄 Запрос #12643 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 110 спецификаций. Всего: 1251888
🔄 Запрос #12644 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 105 спецификаций. Всего: 1251993
🔄 Запрос #12645 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 100 спецификаций. Всего: 1252093
🔄 Запрос #12646 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 90 спецификаций. Всего: 1252183
🔄 Запрос #12647 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 98 спецификаций. Всего: 1252281
🔄 Запрос #12648 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 103 спецификаций. Всего: 1252384
🔄 Запрос #12649 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 109 спецификаций. Всего: 1252493
🔄 Запрос #12650 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 116 спецификаций. Всего: 1252609
🔄 Запрос #12651 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 140 спецификаций. Всего: 1252749
🔄 Запрос #12652 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 121 спецификаций. Всего: 1252870
🔄 Запрос #12653 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 103 спецификаций. Всего: 1252973
🔄 Запрос #12654 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 97 спецификаций. Всего: 1253070
🔄 Запрос #12655 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1253176
🔄 Запрос #12656 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 71 спецификаций. Всего: 1253247
🔄 Запрос #12657 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 60 спецификаций. Всего: 1253307
🔄 Запрос #12658 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 87 спецификаций. Всего: 1253394
🔄 Запрос #12659 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 114 спецификаций. Всего: 1253508
🔄 Запрос #12660 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 97 спецификаций. Всего: 1253605
🔄 Запрос #12661 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1253709
🔄 Запрос #12662 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 119 спецификаций. Всего: 1253828
🔄 Запрос #12663 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 128 спецификаций. Всего: 1253956
🔄 Запрос #12664 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 123 спецификаций. Всего: 1254079
🔄 Запрос #12665 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1254189
🔄 Запрос #12666 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 129 спецификаций. Всего: 1254318
🔄 Запрос #12667 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 143 спецификаций. Всего: 1254461
🔄 Запрос #12668 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 129 спецификаций. Всего: 1254590
🔄 Запрос #12669 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 111 спецификаций. Всего: 1254701
🔄 Запрос #12670 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 103 спецификаций. Всего: 1254804
🔄 Запрос #12671 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 96 спецификаций. Всего: 1254900
🔄 Запрос #12672 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 84 спецификаций. Всего: 1254984
🔄 Запрос #12673 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 105 спецификаций. Всего: 1255089
🔄 Запрос #12674 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 104 спецификаций. Всего: 1255193
🔄 Запрос #12675 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 116 спецификаций. Всего: 1255309
🔄 Запрос #12676 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 126 спецификаций. Всего: 1255435
🔄 Запрос #12677 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 124 спецификаций. Всего: 1255559

🔄 Запрос #12678 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 126 спецификаций. Всего: 1255685
🔄 Запрос #12679 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 124 спецификаций. Всего: 1255809
🔄 Запрос #12680 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 65 спецификаций. Всего: 1255874
🔄 Запрос #12681 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1255980
🔄 Запрос #12682 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 113 спецификаций. Всего: 1256093
🔄 Запрос #12683 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 112 спецификаций. Всего: 1256205
🔄 Запрос #12684 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 102 спецификаций. Всего: 1256307
🔄 Запрос #12685 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 111 спецификаций. Всего: 1256418
🔄 Запрос #12686 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 101 спецификаций. Всего: 1256519
🔄 Запрос #12687 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1256625
🔄 Запрос #12688 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 122 спецификаций. Всего: 1256747
🔄 Запрос #12689 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 115 спецификаций. Всего: 1256862
📤 Сохранено 10038 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #12690 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 109 спецификаций. Всего: 1256971
🔄 Запрос #12691 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 83 спецификаций. Всего: 1257054
🔄 Запрос #12692 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 93 спецификаций. Всего: 1257147
🔄 Запрос #12693 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 89 спецификаций. Всего: 1257236
🔄 Запрос #12694 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 78 спецификаций. Всего: 1257314
🔄 Запрос #12695 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 70 спецификаций. Всего: 1257384
🔄 Запрос #12696 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 56 спецификаций. Всего: 1257440
🔄 Запрос #12697 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 74 спецификаций. Всего: 1257514
🔄 Запрос #12698 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 91 спецификаций. Всего: 1257605
🔄 Запрос #12699 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 88 спецификаций. Всего: 1257693
🔄 Запрос #12700 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 103 спецификаций. Всего: 1257796
🔄 Запрос #12701 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 110 спецификаций. Всего: 1257906
🔄 Запрос #12702 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 92 спецификаций. Всего: 1257998
🔄 Запрос #12703 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 84 спецификаций. Всего: 1258082
🔄 Запрос #12704 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 93 спецификаций. Всего: 1258175
🔄 Запрос #12705 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 98 спецификаций. Всего: 1258273
🔄 Запрос #12706 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 123 спецификаций. Всего: 1258396
🔄 Запрос #12707 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 81 спецификаций. Всего: 1258477
🔄 Запрос #12708 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 80 спецификаций. Всего: 1258557
🔄 Запрос #12709 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 96 спецификаций. Всего: 1258653
🔄 Запрос #12710 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 99 спецификаций. Всего: 1258752
🔄 Запрос #12711 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1258848
🔄 Запрос #12712 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 99 спецификаций. Всего: 1258947
🔄 Запрос #12713 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 110 спецификаций. Всего: 1259057
🔄 Запрос #12714 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 114 спецификаций. Всего: 1259171
🔄 Запрос #12715 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 112 спецификаций. Всего: 1259283
🔄 Запрос #12716 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 93 спецификаций. Всего: 1259376
🔄 Запрос #12717 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 119 спецификаций. Всего: 1259495
🔄 Запрос #12718 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 92 спецификаций. Всего: 1259587
🔄 Запрос #12719 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 98 спецификаций. Всего: 1259685
🔄 Запрос #12720 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 88 спецификаций. Всего: 1259773
🔄 Запрос #12721 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 79 спецификаций. Всего: 1259852
🔄 Запрос #12722 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 92 спецификаций. Всего: 1259944
🔄 Запрос #12723 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 1260033
🔄 Запрос #12724 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 75 спецификаций. Всего: 1260108
🔄 Запрос #12725 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 133 спецификаций. Всего: 1260241
🔄 Запрос #12726 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 88 спецификаций. Всего: 1260329
🔄 Запрос #12727 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 150 спецификаций. Всего: 1260479
🔄 Запрос #12728 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 101 спецификаций. Всего: 1260580
🔄 Запрос #12729 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 96 спецификаций. Всего: 1260676
🔄 Запрос #12730 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 100 спецификаций. Всего: 1260776
🔄 Запрос #12731 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 83 спецификаций. Всего: 1260859
🔄 Запрос #12732 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 1260944
🔄 Запрос #12733 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 104 спецификаций. Всего: 1261048
🔄 Запрос #12734 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 103 спецификаций. Всего: 1261151
🔄 Запрос #12735 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 108 спецификаций. Всего: 1261259
🔄 Запрос #12736 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 119 спецификаций. Всего: 1261378
🔄 Запрос #12737 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 86 спецификаций. Всего: 1261464
🔄 Запрос #12738 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 93 спецификаций. Всего: 1261557
🔄 Запрос #12739 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 108 спецификаций. Всего: 1261665
🔄 Запрос #12740 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 112 спецификаций. Всего: 1261777
🔄 Запрос #12741 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 127 спецификаций. Всего: 1261904
🔄 Запрос #12742 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 101 спецификаций. Всего: 1262005
🔄 Запрос #12743 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 104 спецификаций. Всего: 1262109
🔄 Запрос #12744 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 110 спецификаций. Всего: 1262219
🔄 Запрос #12745 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 1262304
🔄 Запрос #12746 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 1262401
🔄 Запрос #12747 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 88 спецификаций. Всего: 1262489
🔄 Запрос #12748 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 1262586
🔄 Запрос #12749 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1262692
🔄 Запрос #12750 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 120 спецификаций. Всего: 1262812
🔄 Запрос #12751 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 113 спецификаций. Всего: 1262925
🔄 Запрос #12752 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 109 спецификаций. Всего: 1263034
🔄 Запрос #12753 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1263149
🔄 Запрос #12754 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 88 спецификаций. Всего: 1263237
🔄 Запрос #12755 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 88 спецификаций. Всего: 1263325
🔄 Запрос #12756 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 107 спецификаций. Всего: 1263432
🔄 Запрос #12757 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 118 спецификаций. Всего: 1263550
🔄 Запрос #12758 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 80 спецификаций. Всего: 1263630
🔄 Запрос #12759 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 72 спецификаций. Всего: 1263702
🔄 Запрос #12760 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 81 спецификаций. Всего: 1263783
🔄 Запрос #12761 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 82 спецификаций. Всего: 1263865
🔄 Запрос #12762 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 1263954
🔄 Запрос #12763 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 89 спецификаций. Всего: 1264043
🔄 Запрос #12764 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 82 спецификаций. Всего: 1264125
🔄 Запрос #12765 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 81 спецификаций. Всего: 1264206
🔄 Запрос #12766 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 91 спецификаций. Всего: 1264297
🔄 Запрос #12767 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 107 спецификаций. Всего: 1264404
🔄 Запрос #12768 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 100 спецификаций. Всего: 1264504
🔄 Запрос #12769 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 87 спецификаций. Всего: 1264591
🔄 Запрос #12770 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 100 спецификаций. Всего: 1264691
🔄 Запрос #12771 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 1264794
🔄 Запрос #12772 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 124 спецификаций. Всего: 1264918
🔄 Запрос #12773 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 107 спецификаций. Всего: 1265025
🔄 Запрос #12774 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 112 спецификаций. Всего: 1265137
🔄 Запрос #12775 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 110 спецификаций. Всего: 1265247
🔄 Запрос #12776 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 116 спецификаций. Всего: 1265363
🔄 Запрос #12777 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 82 спецификаций. Всего: 1265445
🔄 Запрос #12778 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 90 спецификаций. Всего: 1265535
🔄 Запрос #12779 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 86 спецификаций. Всего: 1265621
🔄 Запрос #12780 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 113 спецификаций. Всего: 1265734
🔄 Запрос #12781 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1265825
🔄 Запрос #12782 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1265931
🔄 Запрос #12783 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 98 спецификаций. Всего: 1266029
🔄 Запрос #12784 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 115 спецификаций. Всего: 1266144
🔄 Запрос #12785 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 97 спецификаций. Всего: 1266241
🔄 Запрос #12786 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 103 спецификаций. Всего: 1266344
🔄 Запрос #12787 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 113 спецификаций. Всего: 1266457
🔄 Запрос #12788 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 1266554
🔄 Запрос #12789 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 120 спецификаций. Всего: 1266674
🔄 Запрос #12790 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 96 спецификаций. Всего: 1266770
🔄 Запрос #12791 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 93 спецификаций. Всего: 1266863
📤 Сохранено 10001 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #12792 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 88 спецификаций. Всего: 1266951
🔄 Запрос #12793 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 87 спецификаций. Всего: 1267038
🔄 Запрос #12794 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 86 спецификаций. Всего: 1267124
🔄 Запрос #12795 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1267232
🔄 Запрос #12796 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 81 спецификаций. Всего: 1267313
🔄 Запрос #12797 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 94 спецификаций. Всего: 1267407
🔄 Запрос #12798 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 82 спецификаций. Всего: 1267489
🔄 Запрос #12799 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 60 спецификаций. Всего: 1267549
🔄 Запрос #12800 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 71 спецификаций. Всего: 1267620
🔄 Запрос #12801 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 71 спецификаций. Всего: 1267691
🔄 Запрос #12802 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09

📥 Загружено 34 спецификаций. Всего: 1267725
🔄 Запрос #12803 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 57 спецификаций. Всего: 1267782
🔄 Запрос #12804 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 78 спецификаций. Всего: 1267860
🔄 Запрос #12805 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 58 спецификаций. Всего: 1267918
🔄 Запрос #12806 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 59 спецификаций. Всего: 1267977
🔄 Запрос #12807 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 0 спецификаций. Всего: 1267977
🔄 Запрос #12808 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 43 спецификаций. Всего: 1268020
🔄 Запрос #12809 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 99 спецификаций. Всего: 1268119
🔄 Запрос #12810 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 138 спецификаций. Всего: 1268257
🔄 Запрос #12811 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 146 спецификаций. Всего: 1268403
🔄 Запрос #12812 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 148 спецификаций. Всего: 1268551
🔄 Запрос #12813 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 128 спецификаций. Всего: 1268679
🔄 Запрос #12814 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 87 спецификаций. Всего: 1268766
🔄 Запрос #12815 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 117 спецификаций. Всего: 1268883
🔄 Запрос #12816 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1268992
🔄 Запрос #12817 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 102 спецификаций. Всего: 1269094
🔄 Запрос #12818 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 108 спецификаций. Всего: 1269202
🔄 Запрос #12819 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 111 спецификаций. Всего: 1269313
🔄 Запрос #12820 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 99 спецификаций. Всего: 1269412
🔄 Запрос #12821 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 96 спецификаций. Всего: 1269508
🔄 Запрос #12822 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 117 спецификаций. Всего: 1269625
🔄 Запрос #12823 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 1269745
🔄 Запрос #12824 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 118 спецификаций. Всего: 1269863
🔄 Запрос #12825 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 98 спецификаций. Всего: 1269961
🔄 Запрос #12826 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 91 спецификаций. Всего: 1270052
🔄 Запрос #12827 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 91 спецификаций. Всего: 1270143
🔄 Запрос #12828 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 108 спецификаций. Всего: 1270251
🔄 Запрос #12829 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1270358
🔄 Запрос #12830 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 103 спецификаций. Всего: 1270461
🔄 Запрос #12831 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 93 спецификаций. Всего: 1270554
🔄 Запрос #12832 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 90 спецификаций. Всего: 1270644
🔄 Запрос #12833 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1270750
🔄 Запрос #12834 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 101 спецификаций. Всего: 1270851
🔄 Запрос #12835 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 114 спецификаций. Всего: 1270965
🔄 Запрос #12836 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 99 спецификаций. Всего: 1271064
🔄 Запрос #12837 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 125 спецификаций. Всего: 1271189
🔄 Запрос #12838 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 99 спецификаций. Всего: 1271288
🔄 Запрос #12839 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 93 спецификаций. Всего: 1271381
🔄 Запрос #12840 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1271487
🔄 Запрос #12841 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 63 спецификаций. Всего: 1271550
🔄 Запрос #12842 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 89 спецификаций. Всего: 1271639
🔄 Запрос #12843 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 111 спецификаций. Всего: 1271750
🔄 Запрос #12844 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 123 спецификаций. Всего: 1271873
🔄 Запрос #12845 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 107 спецификаций. Всего: 1271980
🔄 Запрос #12846 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 85 спецификаций. Всего: 1272065
🔄 Запрос #12847 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 140 спецификаций. Всего: 1272205
🔄 Запрос #12848 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1272319
🔄 Запрос #12849 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 78 спецификаций. Всего: 1272397
🔄 Запрос #12850 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 97 спецификаций. Всего: 1272494
🔄 Запрос #12851 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 94 спецификаций. Всего: 1272588
🔄 Запрос #12852 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1272682
🔄 Запрос #12853 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 97 спецификаций. Всего: 1272779
🔄 Запрос #12854 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 103 спецификаций. Всего: 1272882
🔄 Запрос #12855 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 117 спецификаций. Всего: 1272999
🔄 Запрос #12856 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 108 спецификаций. Всего: 1273107
🔄 Запрос #12857 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 111 спецификаций. Всего: 1273218
🔄 Запрос #12858 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1273324
🔄 Запрос #12859 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1273437
🔄 Запрос #12860 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 108 спецификаций. Всего: 1273545
🔄 Запрос #12861 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 107 спецификаций. Всего: 1273652
🔄 Запрос #12862 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 103 спецификаций. Всего: 1273755
🔄 Запрос #12863 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 115 спецификаций. Всего: 1273870
🔄 Запрос #12864 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 123 спецификаций. Всего: 1273993
🔄 Запрос #12865 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1274109
🔄 Запрос #12866 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 111 спецификаций. Всего: 1274220
🔄 Запрос #12867 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09

📥 Загружено 115 спецификаций. Всего: 1274335
🔄 Запрос #12868 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 99 спецификаций. Всего: 1274434
🔄 Запрос #12869 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 92 спецификаций. Всего: 1274526
🔄 Запрос #12870 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 73 спецификаций. Всего: 1274599
🔄 Запрос #12871 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 105 спецификаций. Всего: 1274704
🔄 Запрос #12872 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 90 спецификаций. Всего: 1274794
🔄 Запрос #12873 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1274882
🔄 Запрос #12874 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 87 спецификаций. Всего: 1274969
🔄 Запрос #12875 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1275075
🔄 Запрос #12876 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1275199
🔄 Запрос #12877 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 134 спецификаций. Всего: 1275333
🔄 Запрос #12878 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 43 спецификаций. Всего: 1275376
🔄 Запрос #12879 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 50 спецификаций. Всего: 1275426
🔄 Запрос #12880 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 90 спецификаций. Всего: 1275516
🔄 Запрос #12881 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 123 спецификаций. Всего: 1275639
🔄 Запрос #12882 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 98 спецификаций. Всего: 1275737
🔄 Запрос #12883 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 118 спецификаций. Всего: 1275855
🔄 Запрос #12884 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 152 спецификаций. Всего: 1276007
🔄 Запрос #12885 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 134 спецификаций. Всего: 1276141
🔄 Запрос #12886 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 77 спецификаций. Всего: 1276218
🔄 Запрос #12887 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 164 спецификаций. Всего: 1276382
🔄 Запрос #12888 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 132 спецификаций. Всего: 1276514
🔄 Запрос #12889 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 103 спецификаций. Всего: 1276617
🔄 Запрос #12890 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 81 спецификаций. Всего: 1276698
🔄 Запрос #12891 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 116 спецификаций. Всего: 1276814
🔄 Запрос #12892 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 75 спецификаций. Всего: 1276889
📤 Сохранено 10026 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #12893 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 149 спецификаций. Всего: 1277038
🔄 Запрос #12894 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 119 спецификаций. Всего: 1277157
🔄 Запрос #12895 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 156 спецификаций. Всего: 1277313
🔄 Запрос #12896 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 46 спецификаций. Всего: 1277359
🔄 Запрос #12897 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 58 спецификаций. Всего: 1277417
🔄 Запрос #12898 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 98 спецификаций. Всего: 1277515
🔄 Запрос #12899 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1277621
🔄 Запрос #12900 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 134 спецификаций. Всего: 1277755
🔄 Запрос #12901 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 111 спецификаций. Всего: 1277866
🔄 Запрос #12902 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 124 спецификаций. Всего: 1277990
🔄 Запрос #12903 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 96 спецификаций. Всего: 1278086
🔄 Запрос #12904 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1278199
🔄 Запрос #12905 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 128 спецификаций. Всего: 1278327
🔄 Запрос #12906 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 122 спецификаций. Всего: 1278449
🔄 Запрос #12907 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 116 спецификаций. Всего: 1278565
🔄 Запрос #12908 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 71 спецификаций. Всего: 1278636
🔄 Запрос #12909 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 109 спецификаций. Всего: 1278745
🔄 Запрос #12910 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 113 спецификаций. Всего: 1278858
🔄 Запрос #12911 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 93 спецификаций. Всего: 1278951
🔄 Запрос #12912 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 81 спецификаций. Всего: 1279032
🔄 Запрос #12913 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 81 спецификаций. Всего: 1279113
🔄 Запрос #12914 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 100 спецификаций. Всего: 1279213
🔄 Запрос #12915 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 101 спецификаций. Всего: 1279314
🔄 Запрос #12916 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1279420
🔄 Запрос #12917 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 96 спецификаций. Всего: 1279516
🔄 Запрос #12918 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 90 спецификаций. Всего: 1279606
🔄 Запрос #12919 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 102 спецификаций. Всего: 1279708
🔄 Запрос #12920 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 95 спецификаций. Всего: 1279803
🔄 Запрос #12921 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 87 спецификаций. Всего: 1279890
🔄 Запрос #12922 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 91 спецификаций. Всего: 1279981
🔄 Запрос #12923 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 1280065
🔄 Запрос #12924 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 79 спецификаций. Всего: 1280144
🔄 Запрос #12925 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 68 спецификаций. Всего: 1280212
🔄 Запрос #12926 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 70 спецификаций. Всего: 1280282
🔄 Запрос #12927 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 79 спецификаций. Всего: 1280361
🔄 Запрос #12928 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 84 спецификаций. Всего: 1280445
🔄 Запрос #12929 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1280558
🔄 Запрос #12930 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 111 спецификаций. Всего: 1280669
🔄 Запрос #12931 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 104 спецификаций. Всего: 1280773
🔄 Запрос #12932 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 86 спецификаций. Всего: 1280859
🔄 Запрос #12933 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 79 спецификаций. Всего: 1280938

🔄 Запрос #12934 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 88 спецификаций. Всего: 1281026
🔄 Запрос #12935 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 102 спецификаций. Всего: 1281128
🔄 Запрос #12936 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 81 спецификаций. Всего: 1281209
🔄 Запрос #12937 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 104 спецификаций. Всего: 1281313
🔄 Запрос #12938 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 98 спецификаций. Всего: 1281411
🔄 Запрос #12939 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1281507
🔄 Запрос #12940 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 84 спецификаций. Всего: 1281591
🔄 Запрос #12941 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 93 спецификаций. Всего: 1281684
🔄 Запрос #12942 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 120 спецификаций. Всего: 1281804
🔄 Запрос #12943 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1281906
🔄 Запрос #12944 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 74 спецификаций. Всего: 1281980
🔄 Запрос #12945 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 107 спецификаций. Всего: 1282087
🔄 Запрос #12946 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 106 спецификаций. Всего: 1282193
🔄 Запрос #12947 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 101 спецификаций. Всего: 1282294
🔄 Запрос #12948 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 78 спецификаций. Всего: 1282372
🔄 Запрос #12949 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 147 спецификаций. Всего: 1282519
🔄 Запрос #12950 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 131 спецификаций. Всего: 1282650
🔄 Запрос #12951 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 107 спецификаций. Всего: 1282757
🔄 Запрос #12952 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 79 спецификаций. Всего: 1282836
🔄 Запрос #12953 для 2024-05-09 20:44:09 - 2024-05-16 20:44:09
📥 Загружено 40 спецификаций. Всего: 1282876
📅 Обрабатываем диапазон 2024-05-02 20:44:09 - 2024-05-09 20:44:09 (попытка 1/5)
🔄 Запрос #12954 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 60 спецификаций. Всего: 1282936
🔄 Запрос #12955 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 151 спецификаций. Всего: 1283087
🔄 Запрос #12956 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 1283165
🔄 Запрос #12957 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 1283251
🔄 Запрос #12958 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 61 спецификаций. Всего: 1283312
🔄 Запрос #12959 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 87 спецификаций. Всего: 1283399
🔄 Запрос #12960 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 59 спецификаций. Всего: 1283458
🔄 Запрос #12961 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 1283591
🔄 Запрос #12962 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 130 спецификаций. Всего: 1283721
🔄 Запрос #12963 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 1283839
🔄 Запрос #12964 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 1283967
🔄 Запрос #12965 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 141 спецификаций. Всего: 1284108
🔄 Запрос #12966 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1284233
🔄 Запрос #12967 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 1284324
🔄 Запрос #12968 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 1284420
🔄 Запрос #12969 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 1284511
🔄 Запрос #12970 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 55 спецификаций. Всего: 1284566
🔄 Запрос #12971 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 1284677
🔄 Запрос #12972 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 1284763
🔄 Запрос #12973 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 1284883
🔄 Запрос #12974 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 1284993
🔄 Запрос #12975 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 1285100
🔄 Запрос #12976 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 1285209
🔄 Запрос #12977 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 1285303
🔄 Запрос #12978 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 1285415
🔄 Запрос #12979 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 1285529
🔄 Запрос #12980 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 1285646
🔄 Запрос #12981 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 1285739
🔄 Запрос #12982 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 1285852
🔄 Запрос #12983 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 1285958
🔄 Запрос #12984 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 1286055
🔄 Запрос #12985 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 1286156
🔄 Запрос #12986 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 1286252
🔄 Запрос #12987 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 1286355
🔄 Запрос #12988 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 129 спецификаций. Всего: 1286484
🔄 Запрос #12989 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 1286598
🔄 Запрос #12990 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1286712
🔄 Запрос #12991 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 1286828
🔄 Запрос #12992 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1286955
📤 Сохранено 10066 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #12993 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 104 спецификаций. Всего: 1287059
🔄 Запрос #12994 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 1287173
🔄 Запрос #12995 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 1287274
🔄 Запрос #12996 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1287384

🔄 Запрос #12997 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 1287496
🔄 Запрос #12998 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1287596
🔄 Запрос #12999 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 1287699
🔄 Запрос #13000 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 84 спецификаций. Всего: 1287783
🔄 Запрос #13001 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 80 спецификаций. Всего: 1287863
🔄 Запрос #13002 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 1287976
🔄 Запрос #13003 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1288086
🔄 Запрос #13004 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 1288213
🔄 Запрос #13005 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 1288332
🔄 Запрос #13006 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 1288454
🔄 Запрос #13007 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 1288543
🔄 Запрос #13008 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 1288642
🔄 Запрос #13009 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 1288739
🔄 Запрос #13010 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 77 спецификаций. Всего: 1288816
🔄 Запрос #13011 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 1288922
🔄 Запрос #13012 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 74 спецификаций. Всего: 1288996
🔄 Запрос #13013 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 78 спецификаций. Всего: 1289074
🔄 Запрос #13014 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 1289170
🔄 Запрос #13015 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 92 спецификаций. Всего: 1289262
🔄 Запрос #13016 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 1289345
🔄 Запрос #13017 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 1289433
🔄 Запрос #13018 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 1289541
🔄 Запрос #13019 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 1289666
🔄 Запрос #13020 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 1289751
🔄 Запрос #13021 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1289851
🔄 Запрос #13022 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 104 спецификаций. Всего: 1289955
🔄 Запрос #13023 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 1290044
🔄 Запрос #13024 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 73 спецификаций. Всего: 1290117
🔄 Запрос #13025 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 137 спецификаций. Всего: 1290254
🔄 Запрос #13026 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 1290362
🔄 Запрос #13027 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 163 спецификаций. Всего: 1290525
🔄 Запрос #13028 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 1290625
🔄 Запрос #13029 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 1290729
🔄 Запрос #13030 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 150 спецификаций. Всего: 1290879
🔄 Запрос #13031 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 1291001
🔄 Запрос #13032 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 1291124
🔄 Запрос #13033 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 1291244
🔄 Запрос #13034 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 69 спецификаций. Всего: 1291313
🔄 Запрос #13035 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 1291414
🔄 Запрос #13036 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 122 спецификаций. Всего: 1291536
🔄 Запрос #13037 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 151 спецификаций. Всего: 1291687
🔄 Запрос #13038 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 132 спецификаций. Всего: 1291819
🔄 Запрос #13039 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 1291917
🔄 Запрос #13040 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 1292021
🔄 Запрос #13041 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 1292097
🔄 Запрос #13042 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1292185
🔄 Запрос #13043 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 1292304
🔄 Запрос #13044 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 153 спецификаций. Всего: 1292457
🔄 Запрос #13045 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 151 спецификаций. Всего: 1292608
🔄 Запрос #13046 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 134 спецификаций. Всего: 1292742
🔄 Запрос #13047 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 1292860
🔄 Запрос #13048 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 1292980
🔄 Запрос #13049 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 1293096
🔄 Запрос #13050 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 1293214
🔄 Запрос #13051 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 121 спецификаций. Всего: 1293335
🔄 Запрос #13052 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 147 спецификаций. Всего: 1293482
🔄 Запрос #13053 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 1293605
🔄 Запрос #13054 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 136 спецификаций. Всего: 1293741
🔄 Запрос #13055 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 1293868
🔄 Запрос #13056 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 1293988
🔄 Запрос #13057 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09

📥 Загружено 97 спецификаций. Всего: 1294085
🔄 Запрос #13058 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 1294192
🔄 Запрос #13059 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1294305
🔄 Запрос #13060 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 114 спецификаций. Всего: 1294419
🔄 Запрос #13061 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 1294519
🔄 Запрос #13062 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 1294624
🔄 Запрос #13063 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 1294735
🔄 Запрос #13064 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 1294863
🔄 Запрос #13065 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 124 спецификаций. Всего: 1294987
🔄 Запрос #13066 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 86 спецификаций. Всего: 1295073
🔄 Запрос #13067 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 83 спецификаций. Всего: 1295156
🔄 Запрос #13068 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 69 спецификаций. Всего: 1295225
🔄 Запрос #13069 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 1295301
🔄 Запрос #13070 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 1295419
🔄 Запрос #13071 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 1295513
🔄 Запрос #13072 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 1295613
🔄 Запрос #13073 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 1295725
🔄 Запрос #13074 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 93 спецификаций. Всего: 1295818
🔄 Запрос #13075 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 1295912
🔄 Запрос #13076 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 1296020
🔄 Запрос #13077 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 1296105
🔄 Запрос #13078 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 1296206
🔄 Запрос #13079 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 1296315
🔄 Запрос #13080 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 109 спецификаций. Всего: 1296424
🔄 Запрос #13081 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 1296538
🔄 Запрос #13082 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 132 спецификаций. Всего: 1296670
🔄 Запрос #13083 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 1296795
🔄 Запрос #13084 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1296911
🔄 Запрос #13085 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 1297022
📤 Сохранено 10067 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #13086 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 1297135
🔄 Запрос #13087 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 1297249
🔄 Запрос #13088 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 1297352
🔄 Запрос #13089 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1297452
🔄 Запрос #13090 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 105 спецификаций. Всего: 1297557
🔄 Запрос #13091 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 1297665
🔄 Запрос #13092 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 91 спецификаций. Всего: 1297756
🔄 Запрос #13093 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 1297856
🔄 Запрос #13094 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 1297959
🔄 Запрос #13095 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 1298074
🔄 Запрос #13096 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 1298182
🔄 Запрос #13097 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 1298302
🔄 Запрос #13098 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 1298409
🔄 Запрос #13099 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 76 спецификаций. Всего: 1298485
🔄 Запрос #13100 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 58 спецификаций. Всего: 1298543
🔄 Запрос #13101 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 1298640
🔄 Запрос #13102 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 1298728
🔄 Запрос #13103 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 94 спецификаций. Всего: 1298822
🔄 Запрос #13104 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 1298933
🔄 Запрос #13105 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 1299026
🔄 Запрос #13106 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1299128
🔄 Запрос #13107 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1299244
🔄 Запрос #13108 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 1299367
🔄 Запрос #13109 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 1299485
🔄 Запрос #13110 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 128 спецификаций. Всего: 1299613
🔄 Запрос #13111 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 133 спецификаций. Всего: 1299746
🔄 Запрос #13112 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 110 спецификаций. Всего: 1299856
🔄 Запрос #13113 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 1299960
🔄 Запрос #13114 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 107 спецификаций. Всего: 1300067
🔄 Запрос #13115 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 1300166
🔄 Запрос #13116 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 112 спецификаций. Всего: 1300278
🔄 Запрос #13117 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 1300380
🔄 Запрос #13118 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)

⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1300492
🔄 Запрос #13119 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 118 спецификаций. Всего: 1300610
🔄 Запрос #13120 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 1300725
🔄 Запрос #13121 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 1300836
🔄 Запрос #13122 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 1300950
🔄 Запрос #13123 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 1301048
🔄 Запрос #13124 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 1301146
🔄 Запрос #13125 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 1301253
🔄 Запрос #13126 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1301367
🔄 Запрос #13127 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 1301487
🔄 Запрос #13128 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 115 спецификаций. Всего: 1301602
🔄 Запрос #13129 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 1301710
🔄 Запрос #13130 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 1301833
🔄 Запрос #13131 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 1301946
🔄 Запрос #13132 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 1302073
🔄 Запрос #13133 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 117 спецификаций. Всего: 1302190
🔄 Запрос #13134 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 119 спецификаций. Всего: 1302309
🔄 Запрос #13135 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 99 спецификаций. Всего: 1302408
🔄 Запрос #13136 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 53 спецификаций. Всего: 1302461
🔄 Запрос #13137 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 3 спецификаций. Всего: 1302464
🔄 Запрос #13138 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 2 спецификаций. Всего: 1302466
🔄 Запрос #13139 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 2 спецификаций. Всего: 1302468
🔄 Запрос #13140 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 4 спецификаций. Всего: 1302472
🔄 Запрос #13141 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 0 спецификаций. Всего: 1302472
🔄 Запрос #13142 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 36 спецификаций. Всего: 1302508
🔄 Запрос #13143 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 111 спецификаций. Всего: 1302619
🔄 Запрос #13144 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 106 спецификаций. Всего: 1302725
🔄 Запрос #13145 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 98 спецификаций. Всего: 1302823
🔄 Запрос #13146 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 1302913
🔄 Запрос #13147 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 1303001
🔄 Запрос #13148 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 1303102
🔄 Запрос #13149 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 79 спецификаций. Всего: 1303181
🔄 Запрос #13150 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 1303271
🔄 Запрос #13151 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 1303384
🔄 Запрос #13152 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 78 спецификаций. Всего: 1303462
🔄 Запрос #13153 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 1303564
🔄 Запрос #13154 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 116 спецификаций. Всего: 1303680
🔄 Запрос #13155 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 112 спецификаций. Всего: 1303792
🔄 Запрос #13156 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 101 спецификаций. Всего: 1303893
🔄 Запрос #13157 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 1303990
🔄 Запрос #13158 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1304103
🔄 Запрос #13159 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 125 спецификаций. Всего: 1304228
🔄 Запрос #13160 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 126 спецификаций. Всего: 1304354
🔄 Запрос #13161 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 1304462
🔄 Запрос #13162 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 1304575
🔄 Запрос #13163 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1304677
🔄 Запрос #13164 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 100 спецификаций. Всего: 1304777
🔄 Запрос #13165 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 1304873
🔄 Запрос #13166 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 107 спецификаций. Всего: 1304980
🔄 Запрос #13167 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 1305083
🔄 Запрос #13168 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 1305176
🔄 Запрос #13169 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 1305272
🔄 Запрос #13170 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 90 спецификаций. Всего: 1305362
🔄 Запрос #13171 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 88 спецификаций. Всего: 1305450
🔄 Запрос #13172 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 104 спецификаций. Всего: 1305554
🔄 Запрос #13173 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 97 спецификаций. Всего: 1305651
🔄 Запрос #13174 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 96 спецификаций. Всего: 1305747
🔄 Запрос #13175 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 108 спецификаций. Всего: 1305855
🔄 Запрос #13176 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 93 спецификаций. Всего: 1305948
🔄 Запрос #13177 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 120 спецификаций. Всего: 1306068
🔄 Запрос #13178 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 1306195
🔄 Запрос #13179 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 1306326
🔄 Запрос #13180 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 102 спецификаций. Всего: 1306428
🔄 Запрос #13181 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 1306542
🔄 Запрос #13182 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 113 спецификаций. Всего: 1306655
🔄 Запрос #13183 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 114 спецификаций. Всего: 1306769
🔄 Запрос #13184 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 127 спецификаций. Всего: 1306896
🔄 Запрос #13185 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 131 спецификаций. Всего: 1307027
📤 Сохранено 10005 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #13186 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 123 спецификаций. Всего: 1307150
🔄 Запрос #13187 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 89 спецификаций. Всего: 1307239
🔄 Запрос #13188 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 82 спецификаций. Всего: 1307321

🔄 Запрос #13189 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 103 спецификаций. Всего: 1307424
🔄 Запрос #13190 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 85 спецификаций. Всего: 1307509
🔄 Запрос #13191 для 2024-05-02 20:44:09 - 2024-05-09 20:44:09
📥 Загружено 53 спецификаций. Всего: 1307562
📅 Обрабатываем диапазон 2024-04-25 20:44:09 - 2024-05-02 20:44:09 (попытка 1/5)
🔄 Запрос #13192 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 98 спецификаций. Всего: 1307660
🔄 Запрос #13193 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 119 спецификаций. Всего: 1307779
🔄 Запрос #13194 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 130 спецификаций. Всего: 1307909
🔄 Запрос #13195 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 130 спецификаций. Всего: 1308039
🔄 Запрос #13196 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 130 спецификаций. Всего: 1308169
🔄 Запрос #13197 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 1308272
🔄 Запрос #13198 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 124 спецификаций. Всего: 1308396
🔄 Запрос #13199 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 124 спецификаций. Всего: 1308520
🔄 Запрос #13200 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 118 спецификаций. Всего: 1308638
🔄 Запрос #13201 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 122 спецификаций. Всего: 1308760
🔄 Запрос #13202 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1308868
🔄 Запрос #13203 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 1308971
🔄 Запрос #13204 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 1309076
🔄 Запрос #13205 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 1309182
🔄 Запрос #13206 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 1309285
🔄 Запрос #13207 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 1309393
🔄 Запрос #13208 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 95 спецификаций. Всего: 1309488
🔄 Запрос #13209 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 1309596
🔄 Запрос #13210 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 1309699
🔄 Запрос #13211 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 1309804
🔄 Запрос #13212 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 1309912
🔄 Запрос #13213 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 111 спецификаций. Всего: 1310023
🔄 Запрос #13214 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 1310122
🔄 Запрос #13215 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 1310211
🔄 Запрос #13216 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 102 спецификаций. Всего: 1310313
🔄 Запрос #13217 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 104 спецификаций. Всего: 1310417
🔄 Запрос #13218 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 102 спецификаций. Всего: 1310519
🔄 Запрос #13219 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 1310627
🔄 Запрос #13220 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1310725
🔄 Запрос #13221 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 1310822
🔄 Запрос #13222 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 1310911
🔄 Запрос #13223 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 1311014
🔄 Запрос #13224 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 1311101
🔄 Запрос #13225 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 1311191
🔄 Запрос #13226 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 109 спецификаций. Всего: 1311300
🔄 Запрос #13227 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 113 спецификаций. Всего: 1311413
🔄 Запрос #13228 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 92 спецификаций. Всего: 1311505
🔄 Запрос #13229 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 1311584
🔄 Запрос #13230 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 67 спецификаций. Всего: 1311651
🔄 Запрос #13231 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 64 спецификаций. Всего: 1311715
🔄 Запрос #13232 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 1311715
🔄 Запрос #13233 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 1311715
🔄 Запрос #13234 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 1311715
🔄 Запрос #13235 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 0 спецификаций. Всего: 1311715
🔄 Запрос #13236 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 1 спецификаций. Всего: 1311716
🔄 Запрос #13237 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 4 спецификаций. Всего: 1311720
🔄 Запрос #13238 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 98 спецификаций. Всего: 1311818
🔄 Запрос #13239 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 114 спецификаций. Всего: 1311932
🔄 Запрос #13240 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 118 спецификаций. Всего: 1312050
🔄 Запрос #13241 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 1312151
🔄 Запрос #13242 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 1312242
🔄 Запрос #13243 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 116 спецификаций. Всего: 1312358
🔄 Запрос #13244 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 119 спецификаций. Всего: 1312477
🔄 Запрос #13245 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 1312582
🔄 Запрос #13246 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 137 спецификаций. Всего: 1312719
🔄 Запрос #13247 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1312821
🔄 Запрос #13248 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 98 спецификаций. Всего: 1312919
🔄 Запрос #13249 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 1313024
🔄 Запрос #13250 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 74 спецификаций. Всего: 1313098
🔄 Запрос #13251 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 1313185
🔄 Запрос #13252 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 93 спецификаций. Всего: 1313278
🔄 Запрос #13253 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 1313365
🔄 Запрос #13254 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 102 спецификаций. Всего: 1313467
🔄 Запрос #13255 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 1313564
🔄 Запрос #13256 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 1313650
🔄 Запрос #13257 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 1313742
🔄 Запрос #13258 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 1313836
🔄 Запрос #13259 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09

📥 Загружено 101 спецификаций. Всего: 1313937
🔄 Запрос #13260 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 95 спецификаций. Всего: 1314032
🔄 Запрос #13261 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 1314129
🔄 Запрос #13262 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 80 спецификаций. Всего: 1314209
🔄 Запрос #13263 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 98 спецификаций. Всего: 1314307
🔄 Запрос #13264 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 84 спецификаций. Всего: 1314391
🔄 Запрос #13265 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 100 спецификаций. Всего: 1314491
🔄 Запрос #13266 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 1314582
🔄 Запрос #13267 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 1314668
🔄 Запрос #13268 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 1314750
🔄 Запрос #13269 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 115 спецификаций. Всего: 1314865
🔄 Запрос #13270 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 1314948
🔄 Запрос #13271 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 102 спецификаций. Всего: 1315050
🔄 Запрос #13272 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1315159
🔄 Запрос #13273 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 1315238
🔄 Запрос #13274 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 1315321
🔄 Запрос #13275 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 46 спецификаций. Всего: 1315367
🔄 Запрос #13276 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 53 спецификаций. Всего: 1315420
🔄 Запрос #13277 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 1315498
🔄 Запрос #13278 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 33 спецификаций. Всего: 1315531
🔄 Запрос #13279 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 44 спецификаций. Всего: 1315575
🔄 Запрос #13280 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 73 спецификаций. Всего: 1315648
🔄 Запрос #13281 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 168 спецификаций. Всего: 1315816
🔄 Запрос #13282 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 93 спецификаций. Всего: 1315909
🔄 Запрос #13283 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 54 спецификаций. Всего: 1315963
🔄 Запрос #13284 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 110 спецификаций. Всего: 1316073
🔄 Запрос #13285 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 135 спецификаций. Всего: 1316208
🔄 Запрос #13286 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 155 спецификаций. Всего: 1316363
🔄 Запрос #13287 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 131 спецификаций. Всего: 1316494
🔄 Запрос #13288 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 131 спецификаций. Всего: 1316625
🔄 Запрос #13289 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 153 спецификаций. Всего: 1316778
🔄 Запрос #13290 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 129 спецификаций. Всего: 1316907
🔄 Запрос #13291 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 142 спецификаций. Всего: 1317049
📤 Сохранено 10022 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #13292 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 1317154
🔄 Запрос #13293 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 127 спецификаций. Всего: 1317281
🔄 Запрос #13294 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 1317382
🔄 Запрос #13295 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 102 спецификаций. Всего: 1317484
🔄 Запрос #13296 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 1317562
🔄 Запрос #13297 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 1317644
🔄 Запрос #13298 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 1317726
🔄 Запрос #13299 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 81 спецификаций. Всего: 1317807
🔄 Запрос #13300 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 70 спецификаций. Всего: 1317877
🔄 Запрос #13301 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 95 спецификаций. Всего: 1317972
🔄 Запрос #13302 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 1318064
🔄 Запрос #13303 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 81 спецификаций. Всего: 1318145
🔄 Запрос #13304 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 88 спецификаций. Всего: 1318233
🔄 Запрос #13305 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 1318323
🔄 Запрос #13306 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 1318401
🔄 Запрос #13307 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 1318491
🔄 Запрос #13308 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 1318581
🔄 Запрос #13309 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 68 спецификаций. Всего: 1318649
🔄 Запрос #13310 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 82 спецификаций. Всего: 1318731
🔄 Запрос #13311 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 70 спецификаций. Всего: 1318801
🔄 Запрос #13312 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 56 спецификаций. Всего: 1318857
🔄 Запрос #13313 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 58 спецификаций. Всего: 1318915
🔄 Запрос #13314 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 1318997
🔄 Запрос #13315 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 1319075
🔄 Запрос #13316 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 1319154
🔄 Запрос #13317 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 1319262
🔄 Запрос #13318 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 104 спецификаций. Всего: 1319366
🔄 Запрос #13319 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 1319458
🔄 Запрос #13320 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 1319557
🔄 Запрос #13321 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 84 спецификаций. Всего: 1319641
🔄 Запрос #13322 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 80 спецификаций. Всего: 1319721
🔄 Запрос #13323 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 1319824
🔄 Запрос #13324 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 98 спецификаций. Всего: 1319922
🔄 Запрос #13325 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 1320012

🔄 Запрос #13326 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 87 спецификаций. Всего: 1320099
🔄 Запрос #13327 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 1320186
🔄 Запрос #13328 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 69 спецификаций. Всего: 1320255
🔄 Запрос #13329 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 98 спецификаций. Всего: 1320353
🔄 Запрос #13330 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 1320461
🔄 Запрос #13331 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 1320562
🔄 Запрос #13332 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 76 спецификаций. Всего: 1320638
🔄 Запрос #13333 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 1320724
🔄 Запрос #13334 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 1320799
🔄 Запрос #13335 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 1320893
🔄 Запрос #13336 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 1320994
🔄 Запрос #13337 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 1321083
🔄 Запрос #13338 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 100 спецификаций. Всего: 1321183
🔄 Запрос #13339 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 1321277
🔄 Запрос #13340 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 1321362
🔄 Запрос #13341 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 84 спецификаций. Всего: 1321446
🔄 Запрос #13342 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 111 спецификаций. Всего: 1321557
🔄 Запрос #13343 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 121 спецификаций. Всего: 1321678
🔄 Запрос #13344 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 46 спецификаций. Всего: 1321724
🔄 Запрос #13345 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 1321786
🔄 Запрос #13346 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 77 спецификаций. Всего: 1321863
🔄 Запрос #13347 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 141 спецификаций. Всего: 1322004
🔄 Запрос #13348 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1322118
🔄 Запрос #13349 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 146 спецификаций. Всего: 1322264
🔄 Запрос #13350 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 120 спецификаций. Всего: 1322384
🔄 Запрос #13351 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1322480
🔄 Запрос #13352 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1322595
🔄 Запрос #13353 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 131 спецификаций. Всего: 1322726
🔄 Запрос #13354 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 114 спецификаций. Всего: 1322840
🔄 Запрос #13355 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 133 спецификаций. Всего: 1322973
🔄 Запрос #13356 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 125 спецификаций. Всего: 1323098
🔄 Запрос #13357 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 113 спецификаций. Всего: 1323211
🔄 Запрос #13358 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 102 спецификаций. Всего: 1323313
🔄 Запрос #13359 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 85 спецификаций. Всего: 1323398
🔄 Запрос #13360 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 1323499
🔄 Запрос #13361 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 1323588
🔄 Запрос #13362 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 79 спецификаций. Всего: 1323667
🔄 Запрос #13363 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 1323761
🔄 Запрос #13364 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 1323850
🔄 Запрос #13365 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 1323940
🔄 Запрос #13366 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 1324041
🔄 Запрос #13367 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 92 спецификаций. Всего: 1324133
🔄 Запрос #13368 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 101 спецификаций. Всего: 1324234
🔄 Запрос #13369 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1324343
🔄 Запрос #13370 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 100 спецификаций. Всего: 1324443
🔄 Запрос #13371 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 1324542
🔄 Запрос #13372 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1324650
🔄 Запрос #13373 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 109 спецификаций. Всего: 1324759
🔄 Запрос #13374 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 108 спецификаций. Всего: 1324867
🔄 Запрос #13375 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 1324950
🔄 Запрос #13376 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 91 спецификаций. Всего: 1325041
🔄 Запрос #13377 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 104 спецификаций. Всего: 1325145
🔄 Запрос #13378 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 1325237
🔄 Запрос #13379 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 60 спецификаций. Всего: 1325297
🔄 Запрос #13380 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 49 спецификаций. Всего: 1325346
🔄 Запрос #13381 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 60 спецификаций. Всего: 1325406
🔄 Запрос #13382 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 1325498
🔄 Запрос #13383 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 129 спецификаций. Всего: 1325627
🔄 Запрос #13384 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 115 спецификаций. Всего: 1325742
🔄 Запрос #13385 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 100 спецификаций. Всего: 1325842
🔄 Запрос #13386 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 104 спецификаций. Всего: 1325946
🔄 Запрос #13387 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 1326045
🔄 Запрос #13388 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 113 спецификаций. Всего: 1326158
🔄 Запрос #13389 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09

📥 Загружено 122 спецификаций. Всего: 1326280
🔄 Запрос #13390 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 1326379
🔄 Запрос #13391 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1326488
🔄 Запрос #13392 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 1326585
🔄 Запрос #13393 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 1326688
🔄 Запрос #13394 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 98 спецификаций. Всего: 1326786
🔄 Запрос #13395 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 107 спецификаций. Всего: 1326893
🔄 Запрос #13396 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 96 спецификаций. Всего: 1326989
🔄 Запрос #13397 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 92 спецификаций. Всего: 1327081
📤 Сохранено 10032 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #13398 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 84 спецификаций. Всего: 1327165
🔄 Запрос #13399 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 1327254
🔄 Запрос #13400 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 1327337
🔄 Запрос #13401 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 114 спецификаций. Всего: 1327451
🔄 Запрос #13402 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 117 спецификаций. Всего: 1327568
🔄 Запрос #13403 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1327693
🔄 Запрос #13404 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 132 спецификаций. Всего: 1327825
🔄 Запрос #13405 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 172 спецификаций. Всего: 1327997
🔄 Запрос #13406 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 123 спецификаций. Всего: 1328120
🔄 Запрос #13407 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 116 спецификаций. Всего: 1328236
🔄 Запрос #13408 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 145 спецификаций. Всего: 1328381
🔄 Запрос #13409 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 111 спецификаций. Всего: 1328492
🔄 Запрос #13410 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 120 спецификаций. Всего: 1328612
🔄 Запрос #13411 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 122 спецификаций. Всего: 1328734
🔄 Запрос #13412 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 80 спецификаций. Всего: 1328814
🔄 Запрос #13413 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 1328919
🔄 Запрос #13414 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 113 спецификаций. Всего: 1329032
🔄 Запрос #13415 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 66 спецификаций. Всего: 1329098
🔄 Запрос #13416 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 1329204
🔄 Запрос #13417 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 170 спецификаций. Всего: 1329374
🔄 Запрос #13418 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 171 спецификаций. Всего: 1329545
🔄 Запрос #13419 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 87 спецификаций. Всего: 1329632
🔄 Запрос #13420 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 102 спецификаций. Всего: 1329734
🔄 Запрос #13421 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 1329840
🔄 Запрос #13422 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 116 спецификаций. Всего: 1329956
🔄 Запрос #13423 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 1330053
🔄 Запрос #13424 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 1330124
🔄 Запрос #13425 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 106 спецификаций. Всего: 1330230
🔄 Запрос #13426 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 1330312
🔄 Запрос #13427 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 1330406
🔄 Запрос #13428 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 80 спецификаций. Всего: 1330486
🔄 Запрос #13429 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 1330580
🔄 Запрос #13430 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 1330663
🔄 Запрос #13431 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 100 спецификаций. Всего: 1330763
🔄 Запрос #13432 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 116 спецификаций. Всего: 1330879
🔄 Запрос #13433 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 98 спецификаций. Всего: 1330977
🔄 Запрос #13434 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 1331066
🔄 Запрос #13435 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 1331153
🔄 Запрос #13436 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 1331258
🔄 Запрос #13437 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 103 спецификаций. Всего: 1331361
🔄 Запрос #13438 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 1331447
🔄 Запрос #13439 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 1331552
🔄 Запрос #13440 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 86 спецификаций. Всего: 1331638
🔄 Запрос #13441 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 62 спецификаций. Всего: 1331700
🔄 Запрос #13442 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 76 спецификаций. Всего: 1331776
🔄 Запрос #13443 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 80 спецификаций. Всего: 1331856
🔄 Запрос #13444 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 1331938
🔄 Запрос #13445 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 112 спецификаций. Всего: 1332050
🔄 Запрос #13446 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 98 спецификаций. Всего: 1332148
🔄 Запрос #13447 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 97 спецификаций. Всего: 1332245
🔄 Запрос #13448 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 1332339
🔄 Запрос #13449 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 83 спецификаций. Всего: 1332422
🔄 Запрос #13450 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 75 спецификаций. Всего: 1332497
🔄 Запрос #13451 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 78 спецификаций. Всего: 1332575
🔄 Запрос #13452 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 82 спецификаций. Всего: 1332657
🔄 Запрос #13453 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 76 спецификаций. Всего: 1332733
🔄 Запрос #13454 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 67 спецификаций. Всего: 1332800
🔄 Запрос #13455 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 71 спецификаций. Всего: 1332871
🔄 Запрос #13456 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09

📥 Загружено 74 спецификаций. Всего: 1332945
🔄 Запрос #13457 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 89 спецификаций. Всего: 1333034
🔄 Запрос #13458 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 99 спецификаций. Всего: 1333133
🔄 Запрос #13459 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 108 спецификаций. Всего: 1333241
🔄 Запрос #13460 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 87 спецификаций. Всего: 1333328
🔄 Запрос #13461 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 1333422
🔄 Запрос #13462 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 107 спецификаций. Всего: 1333529
🔄 Запрос #13463 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 90 спецификаций. Всего: 1333619
🔄 Запрос #13464 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 93 спецификаций. Всего: 1333712
🔄 Запрос #13465 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1333831
🔄 Запрос #13466 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 128 спецификаций. Всего: 1333959
🔄 Запрос #13467 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 144 спецификаций. Всего: 1334103
🔄 Запрос #13468 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 154 спецификаций. Всего: 1334257
🔄 Запрос #13469 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 170 спецификаций. Всего: 1334427
🔄 Запрос #13470 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 155 спецификаций. Всего: 1334582
🔄 Запрос #13471 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 152 спецификаций. Всего: 1334734
🔄 Запрос #13472 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 105 спецификаций. Всего: 1334839
🔄 Запрос #13473 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 94 спецификаций. Всего: 1334933
🔄 Запрос #13474 для 2024-04-25 20:44:09 - 2024-05-02 20:44:09
📥 Загружено 50 спецификаций. Всего: 1334983
📅 Обрабатываем диапазон 2024-04-18 20:44:09 - 2024-04-25 20:44:09 (попытка 1/5)
🔄 Запрос #13475 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 87 спецификаций. Всего: 1335070
🔄 Запрос #13476 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 127 спецификаций. Всего: 1335197
🔄 Запрос #13477 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 136 спецификаций. Всего: 1335333
🔄 Запрос #13478 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 140 спецификаций. Всего: 1335473
🔄 Запрос #13479 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1335581
🔄 Запрос #13480 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1335701
🔄 Запрос #13481 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 100 спецификаций. Всего: 1335801
🔄 Запрос #13482 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 1335904
🔄 Запрос #13483 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1335998
🔄 Запрос #13484 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1336107
🔄 Запрос #13485 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1336226
🔄 Запрос #13486 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1336324
🔄 Запрос #13487 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1336415
🔄 Запрос #13488 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 82 спецификаций. Всего: 1336497
🔄 Запрос #13489 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1336606
🔄 Запрос #13490 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1336703
🔄 Запрос #13491 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1336816
🔄 Запрос #13492 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1336931
🔄 Запрос #13493 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1337034
🔄 Запрос #13494 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1337142
📤 Сохранено 10061 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #13495 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1337248
🔄 Запрос #13496 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1337346
🔄 Запрос #13497 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1337453
🔄 Запрос #13498 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1337543
🔄 Запрос #13499 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1337658
🔄 Запрос #13500 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1337759
🔄 Запрос #13501 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1337862
🔄 Запрос #13502 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 68 спецификаций. Всего: 1337930
🔄 Запрос #13503 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 62 спецификаций. Всего: 1337992
🔄 Запрос #13504 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1338081
🔄 Запрос #13505 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 133 спецификаций. Всего: 1338214
🔄 Запрос #13506 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 87 спецификаций. Всего: 1338301
🔄 Запрос #13507 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1338402
🔄 Запрос #13508 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1338507
🔄 Запрос #13509 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1338612
🔄 Запрос #13510 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1338724
🔄 Запрос #13511 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1338818
🔄 Запрос #13512 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1338924
🔄 Запрос #13513 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1339037
🔄 Запрос #13514 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1339133
🔄 Запрос #13515 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 1339217
🔄 Запрос #13516 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1339335
🔄 Запрос #13517 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1339434
🔄 Запрос #13518 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1339526
🔄 Запрос #13519 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1339639
🔄 Запрос #13520 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1339752
🔄 Запрос #13521 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 105 спецификаций. Всего: 1339857
🔄 Запрос #13522 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 93 спецификаций. Всего: 1339950
🔄 Запрос #13523 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 1340041
🔄 Запрос #13524 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1340144
🔄 Запрос #13525 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 83 спецификаций. Всего: 1340227
🔄 Запрос #13526 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1340349
🔄 Запрос #13527 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 123 спецификаций. Всего: 1340472
🔄 Запрос #13528 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 78 спецификаций. Всего: 1340550
🔄 Запрос #13529 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 157 спецификаций. Всего: 1340707
🔄 Запрос #13530 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 144 спецификаций. Всего: 1340851
🔄 Запрос #13531 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1340949
🔄 Запрос #13532 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1341045
🔄 Запрос #13533 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 1341166
🔄 Запрос #13534 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 159 спецификаций. Всего: 1341325
🔄 Запрос #13535 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 139 спецификаций. Всего: 1341464
🔄 Запрос #13536 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 160 спецификаций. Всего: 1341624
🔄 Запрос #13537 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 131 спецификаций. Всего: 1341755
🔄 Запрос #13538 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 135 спецификаций. Всего: 1341890
🔄 Запрос #13539 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1342004
🔄 Запрос #13540 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1342123
🔄 Запрос #13541 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 130 спецификаций. Всего: 1342253
🔄 Запрос #13542 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 134 спецификаций. Всего: 1342387
🔄 Запрос #13543 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 147 спецификаций. Всего: 1342534
🔄 Запрос #13544 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1342646
🔄 Запрос #13545 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1342762
🔄 Запрос #13546 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1342867
🔄 Запрос #13547 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1342956
🔄 Запрос #13548 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1343053
🔄 Запрос #13549 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1343142
🔄 Запрос #13550 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1343244
🔄 Запрос #13551 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1343343
🔄 Запрос #13552 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1343463
🔄 Запрос #13553 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1343574
🔄 Запрос #13554 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1343678
🔄 Запрос #13555 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 134 спецификаций. Всего: 1343812
🔄 Запрос #13556 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1343915
🔄 Запрос #13557 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 71 спецификаций. Всего: 1343986
🔄 Запрос #13558 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 81 спецификаций. Всего: 1344067
🔄 Запрос #13559 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1344161
🔄 Запрос #13560 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1344262
🔄 Запрос #13561 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 1344346
🔄 Запрос #13562 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 93 спецификаций. Всего: 1344439
🔄 Запрос #13563 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1344550
🔄 Запрос #13564 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1344654
🔄 Запрос #13565 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1344764
🔄 Запрос #13566 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 93 спецификаций. Всего: 1344857
🔄 Запрос #13567 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1344954
🔄 Запрос #13568 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1345069
🔄 Запрос #13569 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 149 спецификаций. Всего: 1345218
🔄 Запрос #13570 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1345336
🔄 Запрос #13571 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1345441
🔄 Запрос #13572 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1345547
🔄 Запрос #13573 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1345664
🔄 Запрос #13574 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1345790
🔄 Запрос #13575 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 138 спецификаций. Всего: 1345928
🔄 Запрос #13576 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 147 спецификаций. Всего: 1346075
🔄 Запрос #13577 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 145 спецификаций. Всего: 1346220
🔄 Запрос #13578 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1346327
🔄 Запрос #13579 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1346445
🔄 Запрос #13580 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1346554
🔄 Запрос #13581 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1346679
🔄 Запрос #13582 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1346794
🔄 Запрос #13583 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1346908
🔄 Запрос #13584 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1347021
🔄 Запрос #13585 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 93 спецификаций. Всего: 1347114
🔄 Запрос #13586 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1347208
📤 Сохранено 10066 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #13587 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 1347299
🔄 Запрос #13588 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1347401

🔄 Запрос #13589 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1347497
🔄 Запрос #13590 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1347583
🔄 Запрос #13591 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1347673
🔄 Запрос #13592 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1347783
🔄 Запрос #13593 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 150 спецификаций. Всего: 1347933
🔄 Запрос #13594 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1348039
🔄 Запрос #13595 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1348131
🔄 Запрос #13596 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1348223
🔄 Запрос #13597 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1348325
🔄 Запрос #13598 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 95 спецификаций. Всего: 1348420
🔄 Запрос #13599 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 83 спецификаций. Всего: 1348503
🔄 Запрос #13600 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1348623
🔄 Запрос #13601 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1348743
🔄 Запрос #13602 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1348853
🔄 Запрос #13603 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 87 спецификаций. Всего: 1348940
🔄 Запрос #13604 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 76 спецификаций. Всего: 1349016
🔄 Запрос #13605 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1349133
🔄 Запрос #13606 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 139 спецификаций. Всего: 1349272
🔄 Запрос #13607 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 161 спецификаций. Всего: 1349433
🔄 Запрос #13608 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 132 спецификаций. Всего: 1349565
🔄 Запрос #13609 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1349683
🔄 Запрос #13610 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1349797
🔄 Запрос #13611 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 123 спецификаций. Всего: 1349920
🔄 Запрос #13612 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 130 спецификаций. Всего: 1350050
🔄 Запрос #13613 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 1350183
🔄 Запрос #13614 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 150 спецификаций. Всего: 1350333
🔄 Запрос #13615 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1350441
🔄 Запрос #13616 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1350547
🔄 Запрос #13617 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1350660
🔄 Запрос #13618 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 95 спецификаций. Всего: 1350755
🔄 Запрос #13619 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1350860
🔄 Запрос #13620 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1350968
🔄 Запрос #13621 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1351069
🔄 Запрос #13622 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1351158
🔄 Запрос #13623 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 85 спецификаций. Всего: 1351243
🔄 Запрос #13624 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 83 спецификаций. Всего: 1351326
🔄 Запрос #13625 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1351418
🔄 Запрос #13626 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1351522
🔄 Запрос #13627 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1351628
🔄 Запрос #13628 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1351731
🔄 Запрос #13629 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1351842
🔄 Запрос #13630 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 100 спецификаций. Всего: 1351942
🔄 Запрос #13631 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1352060
🔄 Запрос #13632 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 133 спецификаций. Всего: 1352193
🔄 Запрос #13633 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1352318
🔄 Запрос #13634 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1352437
🔄 Запрос #13635 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1352540
🔄 Запрос #13636 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1352639
🔄 Запрос #13637 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1352740
🔄 Запрос #13638 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 187 спецификаций. Всего: 1352927
🔄 Запрос #13639 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 164 спецификаций. Всего: 1353091
🔄 Запрос #13640 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1353194
🔄 Запрос #13641 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1353308
🔄 Запрос #13642 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1353430
🔄 Запрос #13643 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 126 спецификаций. Всего: 1353556
🔄 Запрос #13644 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1353681
🔄 Запрос #13645 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 142 спецификаций. Всего: 1353823
🔄 Запрос #13646 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1353940
🔄 Запрос #13647 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1354065
🔄 Запрос #13648 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 1354189
🔄 Запрос #13649 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1354302
🔄 Запрос #13650 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1354421
🔄 Запрос #13651 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1354524
🔄 Запрос #13652 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1354636
🔄 Запрос #13653 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1354737
🔄 Запрос #13654 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1354859
🔄 Запрос #13655 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1354964
🔄 Запрос #13656 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1355080
🔄 Запрос #13657 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1355198
🔄 Запрос #13658 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 137 спецификаций. Всего: 1355335
🔄 Запрос #13659 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Max retries exceeded with url: /v3/graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026BAF75E810>, 'Connection to ows.goszakup.gov.kz timed out. (connect timeout=15)'))
📥 Загружено 108 спецификаций. Всего: 1355443
🔄 Запрос #13660 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1355547
🔄 Запрос #13661 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1355655
🔄 Запрос #13662 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1355764
🔄 Запрос #13663 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1355869
🔄 Запрос #13664 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1355974
🔄 Запрос #13665 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1356093
🔄 Запрос #13666 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1356210
🔄 Запрос #13667 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 87 спецификаций. Всего: 1356297
🔄 Запрос #13668 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 81 спецификаций. Всего: 1356378
🔄 Запрос #13669 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1356480
🔄 Запрос #13670 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 73 спецификаций. Всего: 1356553
🔄 Запрос #13671 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 128 спецификаций. Всего: 1356681
🔄 Запрос #13672 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 1356802
🔄 Запрос #13673 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1356914
🔄 Запрос #13674 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1357004
🔄 Запрос #13675 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1357112
🔄 Запрос #13676 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 122 спецификаций. Всего: 1357234
📤 Сохранено 10026 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #13677 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 137 спецификаций. Всего: 1357371
🔄 Запрос #13678 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 147 спецификаций. Всего: 1357518
🔄 Запрос #13679 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1357630
🔄 Запрос #13680 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 1357751
🔄 Запрос #13681 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1357876
🔄 Запрос #13682 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 134 спецификаций. Всего: 1358010
🔄 Запрос #13683 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1358130
🔄 Запрос #13684 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 123 спецификаций. Всего: 1358253
🔄 Запрос #13685 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1358365
🔄 Запрос #13686 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1358475
🔄 Запрос #13687 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1358579
🔄 Запрос #13688 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1358678
🔄 Запрос #13689 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1358775
🔄 Запрос #13690 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1358874
🔄 Запрос #13691 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1358970
🔄 Запрос #13692 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1359059
🔄 Запрос #13693 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1359169
🔄 Запрос #13694 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1359266
🔄 Запрос #13695 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1359356
🔄 Запрос #13696 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1359454
🔄 Запрос #13697 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1359551
🔄 Запрос #13698 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1359660
🔄 Запрос #13699 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 95 спецификаций. Всего: 1359755
🔄 Запрос #13700 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1359847
🔄 Запрос #13701 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1359951
🔄 Запрос #13702 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1360049
🔄 Запрос #13703 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1360155
🔄 Запрос #13704 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 78 спецификаций. Всего: 1360233
🔄 Запрос #13705 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 81 спецификаций. Всего: 1360314
🔄 Запрос #13706 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 77 спецификаций. Всего: 1360391
🔄 Запрос #13707 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1360479
🔄 Запрос #13708 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 87 спецификаций. Всего: 1360566
🔄 Запрос #13709 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1360671
🔄 Запрос #13710 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 68 спецификаций. Всего: 1360739
🔄 Запрос #13711 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1360831
🔄 Запрос #13712 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1360938
🔄 Запрос #13713 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1361026
🔄 Запрос #13714 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 1361117
🔄 Запрос #13715 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1361224

🔄 Запрос #13716 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1361333
🔄 Запрос #13717 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 128 спецификаций. Всего: 1361461
🔄 Запрос #13718 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1361574
🔄 Запрос #13719 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 131 спецификаций. Всего: 1361705
🔄 Запрос #13720 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1361814
🔄 Запрос #13721 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1361930
🔄 Запрос #13722 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1362055
🔄 Запрос #13723 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1362175
🔄 Запрос #13724 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 127 спецификаций. Всего: 1362302
🔄 Запрос #13725 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1362412
🔄 Запрос #13726 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 79 спецификаций. Всего: 1362491
🔄 Запрос #13727 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 76 спецификаций. Всего: 1362567
🔄 Запрос #13728 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 66 спецификаций. Всего: 1362633
🔄 Запрос #13729 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1362737
🔄 Запрос #13730 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1362846
🔄 Запрос #13731 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1362932
🔄 Запрос #13732 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 1363023
🔄 Запрос #13733 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 100 спецификаций. Всего: 1363123
🔄 Запрос #13734 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1363218
🔄 Запрос #13735 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1363322
🔄 Запрос #13736 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 72 спецификаций. Всего: 1363394
🔄 Запрос #13737 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1363510
🔄 Запрос #13738 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 1363601
🔄 Запрос #13739 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1363687
🔄 Запрос #13740 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 71 спецификаций. Всего: 1363758
🔄 Запрос #13741 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1363873
🔄 Запрос #13742 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 100 спецификаций. Всего: 1363973
🔄 Запрос #13743 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 93 спецификаций. Всего: 1364066
🔄 Запрос #13744 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 159 спецификаций. Всего: 1364225
🔄 Запрос #13745 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1364324
🔄 Запрос #13746 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1364439
🔄 Запрос #13747 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1364527
🔄 Запрос #13748 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1364647
🔄 Запрос #13749 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 156 спецификаций. Всего: 1364803
🔄 Запрос #13750 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 76 спецификаций. Всего: 1364879
🔄 Запрос #13751 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 80 спецификаций. Всего: 1364959
🔄 Запрос #13752 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 73 спецификаций. Всего: 1365032
🔄 Запрос #13753 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1365151
🔄 Запрос #13754 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 148 спецификаций. Всего: 1365299
🔄 Запрос #13755 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 161 спецификаций. Всего: 1365460
🔄 Запрос #13756 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 134 спецификаций. Всего: 1365594
🔄 Запрос #13757 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 1365718
🔄 Запрос #13758 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1365837
🔄 Запрос #13759 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1365962
🔄 Запрос #13760 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1366064
🔄 Запрос #13761 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1366158
🔄 Запрос #13762 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 102 спецификаций. Всего: 1366260
🔄 Запрос #13763 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1366374
🔄 Запрос #13764 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1366475
🔄 Запрос #13765 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1366579
🔄 Запрос #13766 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1366701
🔄 Запрос #13767 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1366820
🔄 Запрос #13768 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 1366941
🔄 Запрос #13769 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1367049
🔄 Запрос #13770 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1367168
🔄 Запрос #13771 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1367273
📤 Сохранено 10039 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #13772 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1367361
🔄 Запрос #13773 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1367447
🔄 Запрос #13774 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 100 спецификаций. Всего: 1367547
🔄 Запрос #13775 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 83 спецификаций. Всего: 1367630
🔄 Запрос #13776 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 80 спецификаций. Всего: 1367710
🔄 Запрос #13777 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 76 спецификаций. Всего: 1367786
🔄 Запрос #13778 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 77 спецификаций. Всего: 1367863
🔄 Запрос #13779 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 95 спецификаций. Всего: 1367958
🔄 Запрос #13780 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 83 спецификаций. Всего: 1368041
🔄 Запрос #13781 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 79 спецификаций. Всего: 1368120
🔄 Запрос #13782 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1368209
🔄 Запрос #13783 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1368321
🔄 Запрос #13784 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 129 спецификаций. Всего: 1368450
🔄 Запрос #13785 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1368554
🔄 Запрос #13786 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1368674

🔄 Запрос #13787 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1368779
🔄 Запрос #13788 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1368886
🔄 Запрос #13789 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 95 спецификаций. Всего: 1368981
🔄 Запрос #13790 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1369070
🔄 Запрос #13791 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1369159
🔄 Запрос #13792 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 93 спецификаций. Всего: 1369252
🔄 Запрос #13793 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1369354
🔄 Запрос #13794 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1369443
🔄 Запрос #13795 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1369546
🔄 Запрос #13796 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 79 спецификаций. Всего: 1369625
🔄 Запрос #13797 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 1369709
🔄 Запрос #13798 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1369801
🔄 Запрос #13799 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1369910
🔄 Запрос #13800 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1370004
🔄 Запрос #13801 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1370093
🔄 Запрос #13802 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1370189
🔄 Запрос #13803 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 1370280
🔄 Запрос #13804 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 69 спецификаций. Всего: 1370349
🔄 Запрос #13805 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1370459
🔄 Запрос #13806 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1370584
🔄 Запрос #13807 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 128 спецификаций. Всего: 1370712
🔄 Запрос #13808 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1370830
🔄 Запрос #13809 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 0 спецификаций. Всего: 1370830
🔄 Запрос #13810 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 1 спецификаций. Всего: 1370831
🔄 Запрос #13811 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 0 спецификаций. Всего: 1370831
🔄 Запрос #13812 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 1 спецификаций. Всего: 1370832
🔄 Запрос #13813 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 0 спецификаций. Всего: 1370832
🔄 Запрос #13814 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 46 спецификаций. Всего: 1370878
🔄 Запрос #13815 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 154 спецификаций. Всего: 1371032
🔄 Запрос #13816 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 152 спецификаций. Всего: 1371184
🔄 Запрос #13817 для 2024-04-18 20:44:09 - 2024-04-25 20:44:09
📥 Загружено 47 спецификаций. Всего: 1371231
📅 Обрабатываем диапазон 2024-04-11 20:44:09 - 2024-04-18 20:44:09 (попытка 1/5)
🔄 Запрос #13818 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 170 спецификаций. Всего: 1371401
🔄 Запрос #13819 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 176 спецификаций. Всего: 1371577
🔄 Запрос #13820 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 129 спецификаций. Всего: 1371706
🔄 Запрос #13821 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 157 спецификаций. Всего: 1371863
🔄 Запрос #13822 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 137 спецификаций. Всего: 1372000
🔄 Запрос #13823 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 1372121
🔄 Запрос #13824 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 129 спецификаций. Всего: 1372250
🔄 Запрос #13825 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1372375
🔄 Запрос #13826 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 134 спецификаций. Всего: 1372509
🔄 Запрос #13827 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 124 спецификаций. Всего: 1372633
🔄 Запрос #13828 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 1372748
🔄 Запрос #13829 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1372864
🔄 Запрос #13830 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 116 спецификаций. Всего: 1372980
🔄 Запрос #13831 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1373076
🔄 Запрос #13832 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 105 спецификаций. Всего: 1373181
🔄 Запрос #13833 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1373268
🔄 Запрос #13834 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1373372
🔄 Запрос #13835 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1373465
🔄 Запрос #13836 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1373555
🔄 Запрос #13837 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1373665
🔄 Запрос #13838 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1373762
🔄 Запрос #13839 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1373887
🔄 Запрос #13840 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1374009
🔄 Запрос #13841 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1374116
🔄 Запрос #13842 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1374213
🔄 Запрос #13843 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1374316
🔄 Запрос #13844 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1374415
🔄 Запрос #13845 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1374514
🔄 Запрос #13846 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1374617
🔄 Запрос #13847 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1374716
🔄 Запрос #13848 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1374816
🔄 Запрос #13849 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 1374907
🔄 Запрос #13850 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1375010
🔄 Запрос #13851 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09

📥 Загружено 88 спецификаций. Всего: 1375098
🔄 Запрос #13852 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 85 спецификаций. Всего: 1375183
🔄 Запрос #13853 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1375273
🔄 Запрос #13854 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1375384
🔄 Запрос #13855 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1375514
🔄 Запрос #13856 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1375641
🔄 Запрос #13857 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1375751
🔄 Запрос #13858 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1375846
🔄 Запрос #13859 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1375954
🔄 Запрос #13860 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1376059
🔄 Запрос #13861 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1376165
🔄 Запрос #13862 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1376284
🔄 Запрос #13863 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1376389
🔄 Запрос #13864 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 1376481
🔄 Запрос #13865 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1376585
🔄 Запрос #13866 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 79 спецификаций. Всего: 1376664
🔄 Запрос #13867 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1376751
🔄 Запрос #13868 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1376847
🔄 Запрос #13869 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1376964
🔄 Запрос #13870 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1377083
🔄 Запрос #13871 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 85 спецификаций. Всего: 1377168
🔄 Запрос #13872 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 83 спецификаций. Всего: 1377251
🔄 Запрос #13873 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 73 спецификаций. Всего: 1377324
📤 Сохранено 10051 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #13874 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 83 спецификаций. Всего: 1377407
🔄 Запрос #13875 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1377508
🔄 Запрос #13876 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1377621
🔄 Запрос #13877 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1377726
🔄 Запрос #13878 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1377815
🔄 Запрос #13879 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1377910
🔄 Запрос #13880 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1378022
🔄 Запрос #13881 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1378125
🔄 Запрос #13882 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1378218
🔄 Запрос #13883 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1378331
🔄 Запрос #13884 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 149 спецификаций. Всего: 1378480
🔄 Запрос #13885 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 1378579
🔄 Запрос #13886 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 88 спецификаций. Всего: 1378667
🔄 Запрос #13887 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1378772
🔄 Запрос #13888 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1378876
🔄 Запрос #13889 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1378981
🔄 Запрос #13890 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 120 спецификаций. Всего: 1379101
🔄 Запрос #13891 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 1379176
🔄 Запрос #13892 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1379292
🔄 Запрос #13893 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 1379425
🔄 Запрос #13894 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 1379545
🔄 Запрос #13895 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1379635
🔄 Запрос #13896 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1379737
🔄 Запрос #13897 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1379841
🔄 Запрос #13898 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 1379962
🔄 Запрос #13899 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1380061
🔄 Запрос #13900 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1380154
🔄 Запрос #13901 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1380273
🔄 Запрос #13902 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1380359
🔄 Запрос #13903 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 78 спецификаций. Всего: 1380437
🔄 Запрос #13904 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 94 спецификаций. Всего: 1380531
🔄 Запрос #13905 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1380641
🔄 Запрос #13906 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 83 спецификаций. Всего: 1380724
🔄 Запрос #13907 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 1380815
🔄 Запрос #13908 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 76 спецификаций. Всего: 1380891
🔄 Запрос #13909 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 84 спецификаций. Всего: 1380975
🔄 Запрос #13910 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1381075
🔄 Запрос #13911 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1381170
🔄 Запрос #13912 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 88 спецификаций. Всего: 1381258
🔄 Запрос #13913 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1381356
🔄 Запрос #13914 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1381450
🔄 Запрос #13915 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09

📥 Загружено 76 спецификаций. Всего: 1381526
🔄 Запрос #13916 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1381622
🔄 Запрос #13917 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1381709
🔄 Запрос #13918 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 80 спецификаций. Всего: 1381789
🔄 Запрос #13919 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1381875
🔄 Запрос #13920 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1381961
🔄 Запрос #13921 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1382054
🔄 Запрос #13922 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 1382172
🔄 Запрос #13923 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1382274
🔄 Запрос #13924 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1382380
🔄 Запрос #13925 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1382488
🔄 Запрос #13926 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 79 спецификаций. Всего: 1382567
🔄 Запрос #13927 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 73 спецификаций. Всего: 1382640
🔄 Запрос #13928 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1382745
🔄 Запрос #13929 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1382843
🔄 Запрос #13930 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1382944
🔄 Запрос #13931 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 1383062
🔄 Запрос #13932 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1383179
🔄 Запрос #13933 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 1383262
🔄 Запрос #13934 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1383367
🔄 Запрос #13935 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1383485
🔄 Запрос #13936 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1383595
🔄 Запрос #13937 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1383712
🔄 Запрос #13938 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 1383827
🔄 Запрос #13939 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1383936
🔄 Запрос #13940 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1384053
🔄 Запрос #13941 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 108 спецификаций. Всего: 1384161
🔄 Запрос #13942 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1384250
🔄 Запрос #13943 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1384361
🔄 Запрос #13944 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1384471
🔄 Запрос #13945 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1384584
🔄 Запрос #13946 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1384694
🔄 Запрос #13947 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1384805
🔄 Запрос #13948 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 131 спецификаций. Всего: 1384936
🔄 Запрос #13949 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 133 спецификаций. Всего: 1385069
🔄 Запрос #13950 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1385185
🔄 Запрос #13951 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 139 спецификаций. Всего: 1385324
🔄 Запрос #13952 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 127 спецификаций. Всего: 1385451
🔄 Запрос #13953 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 1385574
🔄 Запрос #13954 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1385677
🔄 Запрос #13955 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1385790
🔄 Запрос #13956 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1385903
🔄 Запрос #13957 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 140 спецификаций. Всего: 1386043
🔄 Запрос #13958 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 175 спецификаций. Всего: 1386218
🔄 Запрос #13959 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 151 спецификаций. Всего: 1386369
🔄 Запрос #13960 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1386496
🔄 Запрос #13961 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1386608
🔄 Запрос #13962 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 135 спецификаций. Всего: 1386743
🔄 Запрос #13963 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 82 спецификаций. Всего: 1386825
🔄 Запрос #13964 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1386931
🔄 Запрос #13965 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1387056
🔄 Запрос #13966 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 1387177
🔄 Запрос #13967 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 137 спецификаций. Всего: 1387314
🔄 Запрос #13968 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1387436
📤 Сохранено 10112 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #13969 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 120 спецификаций. Всего: 1387556
🔄 Запрос #13970 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 127 спецификаций. Всего: 1387683
🔄 Запрос #13971 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1387808
🔄 Запрос #13972 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 135 спецификаций. Всего: 1387943
🔄 Запрос #13973 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 1388075
🔄 Запрос #13974 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1388205
🔄 Запрос #13975 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1388314
🔄 Запрос #13976 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 1388435
🔄 Запрос #13977 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 1388561
🔄 Запрос #13978 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 1388636
🔄 Запрос #13979 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09

📥 Загружено 90 спецификаций. Всего: 1388726
🔄 Запрос #13980 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1388837
🔄 Запрос #13981 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1388950
🔄 Запрос #13982 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 1389068
🔄 Запрос #13983 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 1389189
🔄 Запрос #13984 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1389302
🔄 Запрос #13985 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1389414
🔄 Запрос #13986 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1389520
🔄 Запрос #13987 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1389623
🔄 Запрос #13988 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 1389738
🔄 Запрос #13989 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 120 спецификаций. Всего: 1389858
🔄 Запрос #13990 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1389966
🔄 Запрос #13991 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1390068
🔄 Запрос #13992 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1390172
🔄 Запрос #13993 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1390277
🔄 Запрос #13994 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1390376
🔄 Запрос #13995 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1390483
🔄 Запрос #13996 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 1390558
🔄 Запрос #13997 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 69 спецификаций. Всего: 1390627
🔄 Запрос #13998 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 1390716
🔄 Запрос #13999 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1390817
🔄 Запрос #14000 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1390931
🔄 Запрос #14001 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1391038
🔄 Запрос #14002 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1391142
🔄 Запрос #14003 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1391243
🔄 Запрос #14004 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1391350
🔄 Запрос #14005 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1391456
🔄 Запрос #14006 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1391553
🔄 Запрос #14007 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1391663
🔄 Запрос #14008 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1391768
🔄 Запрос #14009 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1391876
🔄 Запрос #14010 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1391981
🔄 Запрос #14011 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1392086
🔄 Запрос #14012 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1392202
🔄 Запрос #14013 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1392310
🔄 Запрос #14014 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1392414
🔄 Запрос #14015 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1392500
🔄 Запрос #14016 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1392600
🔄 Запрос #14017 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1392705
🔄 Запрос #14018 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1392803
🔄 Запрос #14019 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1392905
🔄 Запрос #14020 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1392995
🔄 Запрос #14021 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 81 спецификаций. Всего: 1393076
🔄 Запрос #14022 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1393183
🔄 Запрос #14023 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1393281
🔄 Запрос #14024 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 1393373
🔄 Запрос #14025 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 1393470
🔄 Запрос #14026 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1393574
🔄 Запрос #14027 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 1393659
🔄 Запрос #14028 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1393765
🔄 Запрос #14029 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1393864
🔄 Запрос #14030 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 1393956
🔄 Запрос #14031 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1394063
🔄 Запрос #14032 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1394164
🔄 Запрос #14033 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 58 спецификаций. Всего: 1394222
🔄 Запрос #14034 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 67 спецификаций. Всего: 1394289
🔄 Запрос #14035 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 82 спецификаций. Всего: 1394371
🔄 Запрос #14036 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1394472
🔄 Запрос #14037 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 94 спецификаций. Всего: 1394566
🔄 Запрос #14038 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 1394657
🔄 Запрос #14039 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 124 спецификаций. Всего: 1394781
🔄 Запрос #14040 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1394884
🔄 Запрос #14041 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 72 спецификаций. Всего: 1394956
🔄 Запрос #14042 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1395057
🔄 Запрос #14043 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 131 спецификаций. Всего: 1395188
🔄 Запрос #14044 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 128 спецификаций. Всего: 1395316

🔄 Запрос #14045 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 1395448
🔄 Запрос #14046 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1395541
🔄 Запрос #14047 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1395638
🔄 Запрос #14048 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1395734
🔄 Запрос #14049 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1395843
🔄 Запрос #14050 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 113 спецификаций. Всего: 1395956
🔄 Запрос #14051 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 1396077
🔄 Запрос #14052 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1396199
🔄 Запрос #14053 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1396305
🔄 Запрос #14054 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1396429
🔄 Запрос #14055 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 1396549
🔄 Запрос #14056 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 1396672
🔄 Запрос #14057 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1396781
🔄 Запрос #14058 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1396896
🔄 Запрос #14059 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1397010
🔄 Запрос #14060 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1397115
🔄 Запрос #14061 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 1397236
🔄 Запрос #14062 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1397332
🔄 Запрос #14063 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1397443
📤 Сохранено 10007 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #14064 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 1397566
🔄 Запрос #14065 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 94 спецификаций. Всего: 1397660
🔄 Запрос #14066 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1397756
🔄 Запрос #14067 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1397854
🔄 Запрос #14068 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1397950
🔄 Запрос #14069 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1398057
🔄 Запрос #14070 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1398169
🔄 Запрос #14071 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1398280
🔄 Запрос #14072 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1398399
🔄 Запрос #14073 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1398511
🔄 Запрос #14074 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1398617
🔄 Запрос #14075 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1398731
🔄 Запрос #14076 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 81 спецификаций. Всего: 1398812
🔄 Запрос #14077 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 1398903
🔄 Запрос #14078 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 77 спецификаций. Всего: 1398980
🔄 Запрос #14079 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1399069
🔄 Запрос #14080 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 80 спецификаций. Всего: 1399149
🔄 Запрос #14081 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1399249
🔄 Запрос #14082 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1399362
🔄 Запрос #14083 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1399487
🔄 Запрос #14084 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1399598
🔄 Запрос #14085 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1399705
🔄 Запрос #14086 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1399805
🔄 Запрос #14087 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1399902
🔄 Запрос #14088 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1399995
🔄 Запрос #14089 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1400100
🔄 Запрос #14090 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 103 спецификаций. Всего: 1400203
🔄 Запрос #14091 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1400301
🔄 Запрос #14092 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 1400398
🔄 Запрос #14093 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1400502
🔄 Запрос #14094 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1400618
🔄 Запрос #14095 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1400707
🔄 Запрос #14096 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1400810
🔄 Запрос #14097 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1400907
🔄 Запрос #14098 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1401029
🔄 Запрос #14099 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1401132
🔄 Запрос #14100 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1401221
🔄 Запрос #14101 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1401340
🔄 Запрос #14102 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1401459
🔄 Запрос #14103 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1401578
🔄 Запрос #14104 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 1401704
🔄 Запрос #14105 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1401823
🔄 Запрос #14106 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1401945
🔄 Запрос #14107 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1402057
🔄 Запрос #14108 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1402169
🔄 Запрос #14109 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1402299
🔄 Запрос #14110 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1402413

🔄 Запрос #14111 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1402521
🔄 Запрос #14112 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 124 спецификаций. Всего: 1402645
🔄 Запрос #14113 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1402735
🔄 Запрос #14114 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 79 спецификаций. Всего: 1402814
🔄 Запрос #14115 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 1402932
🔄 Запрос #14116 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1403037
🔄 Запрос #14117 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1403145
🔄 Запрос #14118 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1403255
🔄 Запрос #14119 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 68 спецификаций. Всего: 1403323
🔄 Запрос #14120 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1403429
🔄 Запрос #14121 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1403548
🔄 Запрос #14122 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1403652
🔄 Запрос #14123 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1403751
🔄 Запрос #14124 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1403868
🔄 Запрос #14125 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1403973
🔄 Запрос #14126 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1404083
🔄 Запрос #14127 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1404199
🔄 Запрос #14128 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 1404322
🔄 Запрос #14129 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 120 спецификаций. Всего: 1404442
🔄 Запрос #14130 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 35 спецификаций. Всего: 1404477
🔄 Запрос #14131 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 168 спецификаций. Всего: 1404645
🔄 Запрос #14132 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 165 спецификаций. Всего: 1404810
🔄 Запрос #14133 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1404912
🔄 Запрос #14134 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 65 спецификаций. Всего: 1404977
🔄 Запрос #14135 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1405070
🔄 Запрос #14136 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 166 спецификаций. Всего: 1405236
🔄 Запрос #14137 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 153 спецификаций. Всего: 1405389
🔄 Запрос #14138 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 1405521
🔄 Запрос #14139 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1405634
🔄 Запрос #14140 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1405759
🔄 Запрос #14141 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 34 спецификаций. Всего: 1405793
🔄 Запрос #14142 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 1 спецификаций. Всего: 1405794
🔄 Запрос #14143 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 1405920
🔄 Запрос #14144 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1406021
🔄 Запрос #14145 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1406122
🔄 Запрос #14146 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1406227
🔄 Запрос #14147 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1406332
🔄 Запрос #14148 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1406435
🔄 Запрос #14149 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 73 спецификаций. Всего: 1406508
🔄 Запрос #14150 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 128 спецификаций. Всего: 1406636
🔄 Запрос #14151 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 186 спецификаций. Всего: 1406822
🔄 Запрос #14152 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1406944
🔄 Запрос #14153 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1407058
🔄 Запрос #14154 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1407171
🔄 Запрос #14155 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1407271
🔄 Запрос #14156 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1407368
🔄 Запрос #14157 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1407477
📤 Сохранено 10034 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #14158 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1407581
🔄 Запрос #14159 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 84 спецификаций. Всего: 1407665
🔄 Запрос #14160 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1407763
🔄 Запрос #14161 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1407858
🔄 Запрос #14162 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1407955
🔄 Запрос #14163 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 78 спецификаций. Всего: 1408033
🔄 Запрос #14164 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1408129
🔄 Запрос #14165 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1408216
🔄 Запрос #14166 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1408311
🔄 Запрос #14167 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1408422
🔄 Запрос #14168 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1408511
🔄 Запрос #14169 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1408598
🔄 Запрос #14170 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 88 спецификаций. Всего: 1408686
🔄 Запрос #14171 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 120 спецификаций. Всего: 1408806
🔄 Запрос #14172 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1408914
🔄 Запрос #14173 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1409041
🔄 Запрос #14174 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1409153
🔄 Запрос #14175 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1409267
🔄 Запрос #14176 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09

📥 Загружено 107 спецификаций. Всего: 1409374
🔄 Запрос #14177 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 94 спецификаций. Всего: 1409468
🔄 Запрос #14178 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 73 спецификаций. Всего: 1409541
🔄 Запрос #14179 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1409651
🔄 Запрос #14180 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1409768
🔄 Запрос #14181 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1409872
🔄 Запрос #14182 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1409967
🔄 Запрос #14183 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1410065
🔄 Запрос #14184 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1410178
🔄 Запрос #14185 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 78 спецификаций. Всего: 1410256
🔄 Запрос #14186 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1410343
🔄 Запрос #14187 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1410431
🔄 Запрос #14188 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 1410506
🔄 Запрос #14189 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 61 спецификаций. Всего: 1410567
🔄 Запрос #14190 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 85 спецификаций. Всего: 1410652
🔄 Запрос #14191 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1410754
🔄 Запрос #14192 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1410843
🔄 Запрос #14193 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1410943
🔄 Запрос #14194 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 144 спецификаций. Всего: 1411087
🔄 Запрос #14195 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1411177
🔄 Запрос #14196 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1411286
🔄 Запрос #14197 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1411384
🔄 Запрос #14198 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 120 спецификаций. Всего: 1411504
🔄 Запрос #14199 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 1411596
🔄 Запрос #14200 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1411709
🔄 Запрос #14201 для 2024-04-11 20:44:09 - 2024-04-18 20:44:09
📥 Загружено 35 спецификаций. Всего: 1411744
📅 Обрабатываем диапазон 2024-04-04 20:44:09 - 2024-04-11 20:44:09 (попытка 1/5)
🔄 Запрос #14202 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1411839
🔄 Запрос #14203 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1411961
🔄 Запрос #14204 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 138 спецификаций. Всего: 1412099
🔄 Запрос #14205 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 1412230
🔄 Запрос #14206 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 153 спецификаций. Всего: 1412383
🔄 Запрос #14207 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 1412519
🔄 Запрос #14208 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 1412637
🔄 Запрос #14209 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1412761
🔄 Запрос #14210 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 1412886
🔄 Запрос #14211 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 135 спецификаций. Всего: 1413021
🔄 Запрос #14212 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 1413144
🔄 Запрос #14213 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1413253
🔄 Запрос #14214 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 1413370
🔄 Запрос #14215 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 1413485
🔄 Запрос #14216 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 1413612
🔄 Запрос #14217 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 1413743
🔄 Запрос #14218 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1413855
🔄 Запрос #14219 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1413966
🔄 Запрос #14220 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1414070
🔄 Запрос #14221 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 114 спецификаций. Всего: 1414184
🔄 Запрос #14222 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1414295
🔄 Запрос #14223 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 1414416
🔄 Запрос #14224 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1414522
🔄 Запрос #14225 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 1414611
🔄 Запрос #14226 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1414709
🔄 Запрос #14227 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1414804
🔄 Запрос #14228 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 1414900
🔄 Запрос #14229 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 1415019
🔄 Запрос #14230 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 1415142
🔄 Запрос #14231 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 1415262
🔄 Запрос #14232 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1415356
🔄 Запрос #14233 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 1415452
🔄 Запрос #14234 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 84 спецификаций. Всего: 1415536
🔄 Запрос #14235 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1415630
🔄 Запрос #14236 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 79 спецификаций. Всего: 1415709

🔄 Запрос #14237 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 1415806
🔄 Запрос #14238 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 1415891
🔄 Запрос #14239 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1415997
🔄 Запрос #14240 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1416105
🔄 Запрос #14241 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1416217
🔄 Запрос #14242 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 1416331
🔄 Запрос #14243 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1416441
🔄 Запрос #14244 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 1416568
🔄 Запрос #14245 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1416687
🔄 Запрос #14246 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 1416796
🔄 Запрос #14247 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 1416895
🔄 Запрос #14248 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1417001
🔄 Запрос #14249 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1417113
🔄 Запрос #14250 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1417221
🔄 Запрос #14251 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1417333
🔄 Запрос #14252 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 1417433
🔄 Запрос #14253 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1417544
📤 Сохранено 10067 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #14254 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 1417644
🔄 Запрос #14255 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 1417729
🔄 Запрос #14256 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1417834
🔄 Запрос #14257 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 1417933
🔄 Запрос #14258 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1418041
🔄 Запрос #14259 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 1418141
🔄 Запрос #14260 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 1418243
🔄 Запрос #14261 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 1418357
🔄 Запрос #14262 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1418451
🔄 Запрос #14263 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1418549
🔄 Запрос #14264 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1418655
🔄 Запрос #14265 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 1418757
🔄 Запрос #14266 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 1418876
🔄 Запрос #14267 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 1419008
🔄 Запрос #14268 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1419124
🔄 Запрос #14269 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1419227
🔄 Запрос #14270 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 1419356
🔄 Запрос #14271 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 1419480
🔄 Запрос #14272 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 57 спецификаций. Всего: 1419537
🔄 Запрос #14273 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 1419654
🔄 Запрос #14274 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 78 спецификаций. Всего: 1419732
🔄 Запрос #14275 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1419835
🔄 Запрос #14276 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 73 спецификаций. Всего: 1419908
🔄 Запрос #14277 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 1419999
🔄 Запрос #14278 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1420106
🔄 Запрос #14279 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1420207
🔄 Запрос #14280 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1420302
🔄 Запрос #14281 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 50 спецификаций. Всего: 1420352
🔄 Запрос #14282 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 1420448
🔄 Запрос #14283 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 1420573
🔄 Запрос #14284 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 140 спецификаций. Всего: 1420713
🔄 Запрос #14285 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 1420822
🔄 Запрос #14286 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1420930
🔄 Запрос #14287 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1421033
🔄 Запрос #14288 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 1421161
🔄 Запрос #14289 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 1421294
🔄 Запрос #14290 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 131 спецификаций. Всего: 1421425
🔄 Запрос #14291 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 1421541
🔄 Запрос #14292 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1421646
🔄 Запрос #14293 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 1421762
🔄 Запрос #14294 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1421875
🔄 Запрос #14295 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1421982
🔄 Запрос #14296 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 1422074
🔄 Запрос #14297 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1422179
🔄 Запрос #14298 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 1422275
🔄 Запрос #14299 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1422381
🔄 Запрос #14300 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 112 спецификаций. Всего: 1422493
🔄 Запрос #14301 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1422598
🔄 Запрос #14302 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1422710
🔄 Запрос #14303 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09

📥 Загружено 114 спецификаций. Всего: 1422824
🔄 Запрос #14304 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1422937
🔄 Запрос #14305 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1423041
🔄 Запрос #14306 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1423153
🔄 Запрос #14307 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1423258
🔄 Запрос #14308 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 1423349
🔄 Запрос #14309 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 80 спецификаций. Всего: 1423429
🔄 Запрос #14310 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1423524
🔄 Запрос #14311 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 1423624
🔄 Запрос #14312 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1423722
🔄 Запрос #14313 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 1423824
🔄 Запрос #14314 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1423931
🔄 Запрос #14315 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1424034
🔄 Запрос #14316 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 1424121
🔄 Запрос #14317 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 74 спецификаций. Всего: 1424195
🔄 Запрос #14318 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 1424278
🔄 Запрос #14319 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1424381
🔄 Запрос #14320 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 1424466
🔄 Запрос #14321 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1424561
🔄 Запрос #14322 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1424662
🔄 Запрос #14323 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 1424779
🔄 Запрос #14324 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 1424870
🔄 Запрос #14325 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1424983
🔄 Запрос #14326 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 1425071
🔄 Запрос #14327 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1425169
🔄 Запрос #14328 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1425272
🔄 Запрос #14329 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1425380
🔄 Запрос #14330 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1425483
🔄 Запрос #14331 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1425587
🔄 Запрос #14332 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 1425684
🔄 Запрос #14333 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 1425784
🔄 Запрос #14334 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1425889
🔄 Запрос #14335 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1425997
🔄 Запрос #14336 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 1426082
🔄 Запрос #14337 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1426194
🔄 Запрос #14338 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1426302
🔄 Запрос #14339 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1426413
🔄 Запрос #14340 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 1426516
🔄 Запрос #14341 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1426628
🔄 Запрос #14342 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1426739
🔄 Запрос #14343 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1426840
🔄 Запрос #14344 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1426934
🔄 Запрос #14345 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1427045
🔄 Запрос #14346 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 1427137
🔄 Запрос #14347 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 1427223
🔄 Запрос #14348 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1427335
🔄 Запрос #14349 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 1427420
🔄 Запрос #14350 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1427513
🔄 Запрос #14351 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 61 спецификаций. Всего: 1427574
📤 Сохранено 10030 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #14352 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 1427698
🔄 Запрос #14353 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 1427826
🔄 Запрос #14354 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 145 спецификаций. Всего: 1427971
🔄 Запрос #14355 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 154 спецификаций. Всего: 1428125
🔄 Запрос #14356 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 1428248
🔄 Запрос #14357 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 147 спецификаций. Всего: 1428395
🔄 Запрос #14358 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 140 спецификаций. Всего: 1428535
🔄 Запрос #14359 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 1428666
🔄 Запрос #14360 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 1428775
🔄 Запрос #14361 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 1428897
🔄 Запрос #14362 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 140 спецификаций. Всего: 1429037
🔄 Запрос #14363 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 151 спецификаций. Всего: 1429188
🔄 Запрос #14364 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1429292
🔄 Запрос #14365 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1429397
🔄 Запрос #14366 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1429508
🔄 Запрос #14367 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 137 спецификаций. Всего: 1429645
🔄 Запрос #14368 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 1429759
🔄 Запрос #14369 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1429865
🔄 Запрос #14370 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 1429965

🔄 Запрос #14371 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1430078
🔄 Запрос #14372 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1430171
🔄 Запрос #14373 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 80 спецификаций. Всего: 1430251
🔄 Запрос #14374 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 1430334
🔄 Запрос #14375 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1430428
🔄 Запрос #14376 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 1430510
🔄 Запрос #14377 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 1430597
🔄 Запрос #14378 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1430690
🔄 Запрос #14379 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1430783
🔄 Запрос #14380 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 84 спецификаций. Всего: 1430867
🔄 Запрос #14381 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1430960
🔄 Запрос #14382 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1431067
🔄 Запрос #14383 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1431174
🔄 Запрос #14384 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1431272
🔄 Запрос #14385 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 76 спецификаций. Всего: 1431348
🔄 Запрос #14386 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1431443
🔄 Запрос #14387 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 70 спецификаций. Всего: 1431513
🔄 Запрос #14388 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 92 спецификаций. Всего: 1431605
🔄 Запрос #14389 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1431715
🔄 Запрос #14390 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1431822
🔄 Запрос #14391 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 1431918
🔄 Запрос #14392 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 89 спецификаций. Всего: 1432007
🔄 Запрос #14393 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1432102
🔄 Запрос #14394 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 1432204
🔄 Запрос #14395 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1432317
🔄 Запрос #14396 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1432428
🔄 Запрос #14397 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 129 спецификаций. Всего: 1432557
🔄 Запрос #14398 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 1432672
🔄 Запрос #14399 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 1432774
🔄 Запрос #14400 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 111 спецификаций. Всего: 1432885
🔄 Запрос #14401 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 1433000
🔄 Запрос #14402 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 1433090
🔄 Запрос #14403 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 1433182
🔄 Запрос #14404 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1433276
🔄 Запрос #14405 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 89 спецификаций. Всего: 1433365
🔄 Запрос #14406 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 1433480
🔄 Запрос #14407 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 1433589
🔄 Запрос #14408 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1433682
🔄 Запрос #14409 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 94 спецификаций. Всего: 1433776
🔄 Запрос #14410 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 1433858
🔄 Запрос #14411 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1433962
🔄 Запрос #14412 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 98 спецификаций. Всего: 1434060
🔄 Запрос #14413 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 1434148
🔄 Запрос #14414 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 89 спецификаций. Всего: 1434237
🔄 Запрос #14415 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1434330
🔄 Запрос #14416 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1434426
🔄 Запрос #14417 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 73 спецификаций. Всего: 1434499
🔄 Запрос #14418 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1434605
🔄 Запрос #14419 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 1434722
🔄 Запрос #14420 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 103 спецификаций. Всего: 1434825
🔄 Запрос #14421 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1434938
🔄 Запрос #14422 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 118 спецификаций. Всего: 1435056
🔄 Запрос #14423 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1435158
🔄 Запрос #14424 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1435252
🔄 Запрос #14425 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1435363
🔄 Запрос #14426 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 1435485
🔄 Запрос #14427 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 1435585
🔄 Запрос #14428 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 1435702
🔄 Запрос #14429 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 1435804
🔄 Запрос #14430 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 1435906
🔄 Запрос #14431 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1436017
🔄 Запрос #14432 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 81 спецификаций. Всего: 1436098

🔄 Запрос #14433 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 1436186
🔄 Запрос #14434 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 1436311
🔄 Запрос #14435 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 84 спецификаций. Всего: 1436395
🔄 Запрос #14436 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 1436481
🔄 Запрос #14437 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 145 спецификаций. Всего: 1436626
🔄 Запрос #14438 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1436724
🔄 Запрос #14439 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 160 спецификаций. Всего: 1436884
🔄 Запрос #14440 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 147 спецификаций. Всего: 1437031
🔄 Запрос #14441 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 156 спецификаций. Всего: 1437187
🔄 Запрос #14442 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 1437326
🔄 Запрос #14443 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1437431
🔄 Запрос #14444 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 158 спецификаций. Всего: 1437589
📤 Сохранено 10015 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #14445 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 1437705
🔄 Запрос #14446 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1437832
🔄 Запрос #14447 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1437951
🔄 Запрос #14448 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 1438080
🔄 Запрос #14449 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 1438195
🔄 Запрос #14450 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 1438320
🔄 Запрос #14451 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1438428
🔄 Запрос #14452 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 1438514
🔄 Запрос #14453 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 1438635
🔄 Запрос #14454 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 1438767
🔄 Запрос #14455 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 1438892
🔄 Запрос #14456 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1439011
🔄 Запрос #14457 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 1439130
🔄 Запрос #14458 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1439242
🔄 Запрос #14459 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 74 спецификаций. Всего: 1439316
🔄 Запрос #14460 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1439417
🔄 Запрос #14461 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 1439541
🔄 Запрос #14462 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 1439657
🔄 Запрос #14463 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1439770
🔄 Запрос #14464 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1439874
🔄 Запрос #14465 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1439979
🔄 Запрос #14466 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 1440093
🔄 Запрос #14467 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1440203
🔄 Запрос #14468 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 1440322
🔄 Запрос #14469 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 1440446
🔄 Запрос #14470 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1440551
🔄 Запрос #14471 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1440659
🔄 Запрос #14472 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 1440755
🔄 Запрос #14473 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 1440854
🔄 Запрос #14474 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 1440944
🔄 Запрос #14475 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1441049
🔄 Запрос #14476 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1441143
🔄 Запрос #14477 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1441256
🔄 Запрос #14478 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 1441355
🔄 Запрос #14479 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1441467
🔄 Запрос #14480 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1441577
🔄 Запрос #14481 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 104 спецификаций. Всего: 1441681
🔄 Запрос #14482 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 1441766
🔄 Запрос #14483 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 1441858
🔄 Запрос #14484 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 1441941
🔄 Запрос #14485 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1442042
🔄 Запрос #14486 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 1442172
🔄 Запрос #14487 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1442283
🔄 Запрос #14488 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 105 спецификаций. Всего: 1442388
🔄 Запрос #14489 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1442498
🔄 Запрос #14490 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1442610
🔄 Запрос #14491 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 1442727
🔄 Запрос #14492 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1442822
🔄 Запрос #14493 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1442916
🔄 Запрос #14494 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1443017
🔄 Запрос #14495 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1443128
🔄 Запрос #14496 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1443229
🔄 Запрос #14497 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 1443326
🔄 Запрос #14498 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1443424
🔄 Запрос #14499 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 1443510

🔄 Запрос #14500 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 1443592
🔄 Запрос #14501 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 1443674
🔄 Запрос #14502 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 1443757
🔄 Запрос #14503 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 1443866
🔄 Запрос #14504 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1443983
🔄 Запрос #14505 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1444087
🔄 Запрос #14506 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1444192
🔄 Запрос #14507 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1444296
🔄 Запрос #14508 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 122 спецификаций. Всего: 1444418
🔄 Запрос #14509 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 1444545
🔄 Запрос #14510 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 1444677
🔄 Запрос #14511 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 1444808
🔄 Запрос #14512 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 1444926
🔄 Запрос #14513 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1445029
🔄 Запрос #14514 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 1445149
🔄 Запрос #14515 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1445260
🔄 Запрос #14516 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 1445383
🔄 Запрос #14517 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1445491
🔄 Запрос #14518 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 1445585
🔄 Запрос #14519 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 1445702
🔄 Запрос #14520 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1445829
🔄 Запрос #14521 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 1445925
🔄 Запрос #14522 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1446028
🔄 Запрос #14523 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 81 спецификаций. Всего: 1446109
🔄 Запрос #14524 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 1446196
🔄 Запрос #14525 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1446308
🔄 Запрос #14526 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1446412
🔄 Запрос #14527 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 143 спецификаций. Всего: 1446555
🔄 Запрос #14528 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1446662
🔄 Запрос #14529 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 145 спецификаций. Всего: 1446807
🔄 Запрос #14530 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 73 спецификаций. Всего: 1446880
🔄 Запрос #14531 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 1447007
🔄 Запрос #14532 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 149 спецификаций. Всего: 1447156
🔄 Запрос #14533 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 144 спецификаций. Всего: 1447300
🔄 Запрос #14534 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 1447410
🔄 Запрос #14535 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 1447541
🔄 Запрос #14536 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 1447663
📤 Сохранено 10074 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #14537 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 67 спецификаций. Всего: 1447730
🔄 Запрос #14538 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 1447817
🔄 Запрос #14539 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1447924
🔄 Запрос #14540 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 1448020
🔄 Запрос #14541 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 77 спецификаций. Всего: 1448097
🔄 Запрос #14542 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 1448179
🔄 Запрос #14543 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 157 спецификаций. Всего: 1448336
🔄 Запрос #14544 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 123 спецификаций. Всего: 1448459
🔄 Запрос #14545 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 71 спецификаций. Всего: 1448530
🔄 Запрос #14546 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 73 спецификаций. Всего: 1448603
🔄 Запрос #14547 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 61 спецификаций. Всего: 1448664
🔄 Запрос #14548 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 80 спецификаций. Всего: 1448744
🔄 Запрос #14549 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 1448869
🔄 Запрос #14550 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 152 спецификаций. Всего: 1449021
🔄 Запрос #14551 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 1449121
🔄 Запрос #14552 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1449228
🔄 Запрос #14553 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 66 спецификаций. Всего: 1449294
🔄 Запрос #14554 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 1449411
🔄 Запрос #14555 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1449524
🔄 Запрос #14556 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 141 спецификаций. Всего: 1449665
🔄 Запрос #14557 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1449789
🔄 Запрос #14558 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 138 спецификаций. Всего: 1449927
🔄 Запрос #14559 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 140 спецификаций. Всего: 1450067
🔄 Запрос #14560 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 138 спецификаций. Всего: 1450205
🔄 Запрос #14561 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 1450314
🔄 Запрос #14562 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 1450418
🔄 Запрос #14563 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 97 спецификаций. Всего: 1450515
🔄 Запрос #14564 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 1450605
🔄 Запрос #14565 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09

📥 Загружено 95 спецификаций. Всего: 1450700
🔄 Запрос #14566 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1450802
🔄 Запрос #14567 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1450909
🔄 Запрос #14568 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 1451005
🔄 Запрос #14569 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 1451104
🔄 Запрос #14570 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 84 спецификаций. Всего: 1451188
🔄 Запрос #14571 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 1451297
🔄 Запрос #14572 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1451400
🔄 Запрос #14573 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 1451502
🔄 Запрос #14574 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1451608
🔄 Запрос #14575 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 1451711
🔄 Запрос #14576 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 1451833
🔄 Запрос #14577 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1451944
🔄 Запрос #14578 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1452051
🔄 Запрос #14579 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 1452160
🔄 Запрос #14580 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 1452275
🔄 Запрос #14581 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1452388
🔄 Запрос #14582 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1452497
🔄 Запрос #14583 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 1452594
🔄 Запрос #14584 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 1452703
🔄 Запрос #14585 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 1452818
🔄 Запрос #14586 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 1452920
🔄 Запрос #14587 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 1453019
🔄 Запрос #14588 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1453131
🔄 Запрос #14589 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1453235
🔄 Запрос #14590 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1453342
🔄 Запрос #14591 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1453459
🔄 Запрос #14592 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1453566
🔄 Запрос #14593 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1453667
🔄 Запрос #14594 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 1453781
🔄 Запрос #14595 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1453879
🔄 Запрос #14596 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 1453996
🔄 Запрос #14597 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 1454124
🔄 Запрос #14598 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 1454247
🔄 Запрос #14599 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 1454360
🔄 Запрос #14600 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1454468
🔄 Запрос #14601 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1454573
🔄 Запрос #14602 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1454674
🔄 Запрос #14603 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 1454760
🔄 Запрос #14604 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1454865
🔄 Запрос #14605 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1454976
🔄 Запрос #14606 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1455083
🔄 Запрос #14607 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 1455204
🔄 Запрос #14608 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 1455320
🔄 Запрос #14609 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1455432
🔄 Запрос #14610 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1455538
🔄 Запрос #14611 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 1455646
🔄 Запрос #14612 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 1455744
🔄 Запрос #14613 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1455844
🔄 Запрос #14614 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1455945
🔄 Запрос #14615 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 1456027
🔄 Запрос #14616 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 1456122
🔄 Запрос #14617 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 1456227
🔄 Запрос #14618 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 1456344
🔄 Запрос #14619 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1456455
🔄 Запрос #14620 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 1456570
🔄 Запрос #14621 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1456686
🔄 Запрос #14622 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 1456792
🔄 Запрос #14623 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1456903
🔄 Запрос #14624 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 1456996
🔄 Запрос #14625 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 70 спецификаций. Всего: 1457066
🔄 Запрос #14626 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 77 спецификаций. Всего: 1457143
🔄 Запрос #14627 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 1457244
🔄 Запрос #14628 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1457351
🔄 Запрос #14629 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 1457462
🔄 Запрос #14630 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 1457574

🔄 Запрос #14631 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 64 спецификаций. Всего: 1457638
🔄 Запрос #14632 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 1457726
📤 Сохранено 10063 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #14633 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 1457835
🔄 Запрос #14634 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 1457923
🔄 Запрос #14635 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 1458037
🔄 Запрос #14636 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 1458134
🔄 Запрос #14637 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 1458256
🔄 Запрос #14638 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 1458370
🔄 Запрос #14639 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 1458500
🔄 Запрос #14640 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 1458591
🔄 Запрос #14641 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 1458698
🔄 Запрос #14642 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 1458831
🔄 Запрос #14643 для 2024-04-04 20:44:09 - 2024-04-11 20:44:09
📥 Загружено 11 спецификаций. Всего: 1458842
📅 Обрабатываем диапазон 2024-03-28 20:44:09 - 2024-04-04 20:44:09 (попытка 1/5)
🔄 Запрос #14644 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1458935
🔄 Запрос #14645 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 0 спецификаций. Всего: 1458935
🔄 Запрос #14646 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 0 спецификаций. Всего: 1458935
🔄 Запрос #14647 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 2 спецификаций. Всего: 1458937
🔄 Запрос #14648 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 0 спецификаций. Всего: 1458937
🔄 Запрос #14649 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 0 спецификаций. Всего: 1458937
🔄 Запрос #14650 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 21 спецификаций. Всего: 1458958
🔄 Запрос #14651 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 1459081
🔄 Запрос #14652 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1459205
🔄 Запрос #14653 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 136 спецификаций. Всего: 1459341
🔄 Запрос #14654 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1459455
🔄 Запрос #14655 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Max retries exceeded with url: /v3/graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026BB3FE7A90>, 'Connection to ows.goszakup.gov.kz timed out. (connect timeout=15)'))
📥 Загружено 102 спецификаций. Всего: 1459557
🔄 Запрос #14656 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1459653
🔄 Запрос #14657 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1459751
🔄 Запрос #14658 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1459864
🔄 Запрос #14659 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 1459988
🔄 Запрос #14660 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 1460109
🔄 Запрос #14661 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 107 спецификаций. Всего: 1460216
🔄 Запрос #14662 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1460321
🔄 Запрос #14663 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1460425
🔄 Запрос #14664 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 1460527
🔄 Запрос #14665 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 85 спецификаций. Всего: 1460612
🔄 Запрос #14666 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 1460719
🔄 Запрос #14667 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 63 спецификаций. Всего: 1460782
🔄 Запрос #14668 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 1460885
🔄 Запрос #14669 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 102 спецификаций. Всего: 1460987
🔄 Запрос #14670 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1461095
🔄 Запрос #14671 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1461200
🔄 Запрос #14672 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1461314
🔄 Запрос #14673 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 1461415
🔄 Запрос #14674 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 1461524
🔄 Запрос #14675 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1461629
🔄 Запрос #14676 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1461728
🔄 Запрос #14677 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 57 спецификаций. Всего: 1461785
🔄 Запрос #14678 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 1461888
🔄 Запрос #14679 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1461989
🔄 Запрос #14680 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 1462099
🔄 Запрос #14681 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1462195
🔄 Запрос #14682 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1462316
🔄 Запрос #14683 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 1462425
🔄 Запрос #14684 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1462530
🔄 Запрос #14685 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1462644
🔄 Запрос #14686 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1462746
🔄 Запрос #14687 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 1462848
🔄 Запрос #14688 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1462964
🔄 Запрос #14689 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1463078
🔄 Запрос #14690 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1463184
🔄 Запрос #14691 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1463292
🔄 Запрос #14692 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 70 спецификаций. Всего: 1463362
🔄 Запрос #14693 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09

📥 Загружено 91 спецификаций. Всего: 1463453
🔄 Запрос #14694 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 1463562
🔄 Запрос #14695 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1463667
🔄 Запрос #14696 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 1463755
🔄 Запрос #14697 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 1463864
🔄 Запрос #14698 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1463963
🔄 Запрос #14699 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 92 спецификаций. Всего: 1464055
🔄 Запрос #14700 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 1464157
🔄 Запрос #14701 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1464258
🔄 Запрос #14702 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 82 спецификаций. Всего: 1464340
🔄 Запрос #14703 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1464445
🔄 Запрос #14704 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1464544
🔄 Запрос #14705 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1464648
🔄 Запрос #14706 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1464747
🔄 Запрос #14707 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1464851
🔄 Запрос #14708 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 103 спецификаций. Всего: 1464954
🔄 Запрос #14709 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1465065
🔄 Запрос #14710 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1465170
🔄 Запрос #14711 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1465286
🔄 Запрос #14712 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1465402
🔄 Запрос #14713 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1465515
🔄 Запрос #14714 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 1465624
🔄 Запрос #14715 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 1465751
🔄 Запрос #14716 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 134 спецификаций. Всего: 1465885
🔄 Запрос #14717 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1465998
🔄 Запрос #14718 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1466104
🔄 Запрос #14719 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1466210
🔄 Запрос #14720 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1466316
🔄 Запрос #14721 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1466427
🔄 Запрос #14722 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 1466513
🔄 Запрос #14723 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1466609
🔄 Запрос #14724 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 1466726
🔄 Запрос #14725 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1466837
🔄 Запрос #14726 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1466935
🔄 Запрос #14727 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 129 спецификаций. Всего: 1467064
🔄 Запрос #14728 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1467168
🔄 Запрос #14729 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 1467252
🔄 Запрос #14730 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1467358
🔄 Запрос #14731 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1467466
🔄 Запрос #14732 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 130 спецификаций. Всего: 1467596
🔄 Запрос #14733 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 1467716
🔄 Запрос #14734 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1467831
📤 Сохранено 10105 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #14735 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 1467953
🔄 Запрос #14736 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1468068
🔄 Запрос #14737 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 137 спецификаций. Всего: 1468205
🔄 Запрос #14738 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 128 спецификаций. Всего: 1468333
🔄 Запрос #14739 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1468426
🔄 Запрос #14740 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 164 спецификаций. Всего: 1468590
🔄 Запрос #14741 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1468698
🔄 Запрос #14742 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 1468807
🔄 Запрос #14743 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 139 спецификаций. Всего: 1468946
🔄 Запрос #14744 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1469062
🔄 Запрос #14745 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1469183
🔄 Запрос #14746 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 131 спецификаций. Всего: 1469314
🔄 Запрос #14747 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 131 спецификаций. Всего: 1469445
🔄 Запрос #14748 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 137 спецификаций. Всего: 1469582
🔄 Запрос #14749 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1469687
🔄 Запрос #14750 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1469814
🔄 Запрос #14751 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 1469903
🔄 Запрос #14752 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 1470023
🔄 Запрос #14753 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 125 спецификаций. Всего: 1470148
🔄 Запрос #14754 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 130 спецификаций. Всего: 1470278
🔄 Запрос #14755 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1470405
🔄 Запрос #14756 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 1470524
🔄 Запрос #14757 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 1470647
🔄 Запрос #14758 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1470759
🔄 Запрос #14759 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1470880
🔄 Запрос #14760 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 1470999
🔄 Запрос #14761 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 137 спецификаций. Всего: 1471136
🔄 Запрос #14762 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 134 спецификаций. Всего: 1471270
🔄 Запрос #14763 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 1471394
🔄 Запрос #14764 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 140 спецификаций. Всего: 1471534
🔄 Запрос #14765 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1471649
🔄 Запрос #14766 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1471754
🔄 Запрос #14767 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1471868
🔄 Запрос #14768 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1471984
🔄 Запрос #14769 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 1472107
🔄 Запрос #14770 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1472220
🔄 Запрос #14771 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 1472330
🔄 Запрос #14772 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 1472430
🔄 Запрос #14773 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 78 спецификаций. Всего: 1472508
🔄 Запрос #14774 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 1472610
🔄 Запрос #14775 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 1472699
🔄 Запрос #14776 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 1472788
🔄 Запрос #14777 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 1472889
🔄 Запрос #14778 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1472993
🔄 Запрос #14779 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1473092
🔄 Запрос #14780 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 1473181
🔄 Запрос #14781 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 1473276
🔄 Запрос #14782 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1473392
🔄 Запрос #14783 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 1473494
🔄 Запрос #14784 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 1473604
🔄 Запрос #14785 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 1473707
🔄 Запрос #14786 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1473822
🔄 Запрос #14787 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1473927
🔄 Запрос #14788 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1474022
🔄 Запрос #14789 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1474126
🔄 Запрос #14790 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1474224
🔄 Запрос #14791 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 60 спецификаций. Всего: 1474284
🔄 Запрос #14792 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1474396
🔄 Запрос #14793 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 1474516
🔄 Запрос #14794 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 92 спецификаций. Всего: 1474608
🔄 Запрос #14795 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 1474694
🔄 Запрос #14796 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 53 спецификаций. Всего: 1474747
🔄 Запрос #14797 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 68 спецификаций. Всего: 1474815
🔄 Запрос #14798 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 1474901
🔄 Запрос #14799 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 82 спецификаций. Всего: 1474983
🔄 Запрос #14800 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 102 спецификаций. Всего: 1475085
🔄 Запрос #14801 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1475190
🔄 Запрос #14802 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1475305
🔄 Запрос #14803 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1475417
🔄 Запрос #14804 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 131 спецификаций. Всего: 1475548
🔄 Запрос #14805 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 1475667
🔄 Запрос #14806 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1475782
🔄 Запрос #14807 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 1475899
🔄 Запрос #14808 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1476020
🔄 Запрос #14809 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 1476137
🔄 Запрос #14810 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1476248
🔄 Запрос #14811 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 1476366
🔄 Запрос #14812 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 1476488
🔄 Запрос #14813 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1476593
🔄 Запрос #14814 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 1476695
🔄 Запрос #14815 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 118 спецификаций. Всего: 1476813
🔄 Запрос #14816 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09

📥 Загружено 126 спецификаций. Всего: 1476939
🔄 Запрос #14817 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1477054
🔄 Запрос #14818 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 1477177
🔄 Запрос #14819 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1477285
🔄 Запрос #14820 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 1477394
🔄 Запрос #14821 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 77 спецификаций. Всего: 1477471
🔄 Запрос #14822 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1477585
🔄 Запрос #14823 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1477683
🔄 Запрос #14824 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 1477792
🔄 Запрос #14825 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1477905
📤 Сохранено 10074 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #14826 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1478011
🔄 Запрос #14827 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1478125
🔄 Запрос #14828 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 1478244
🔄 Запрос #14829 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1478365
🔄 Запрос #14830 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 1478482
🔄 Запрос #14831 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 1478589
🔄 Запрос #14832 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 89 спецификаций. Всего: 1478678
🔄 Запрос #14833 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1478793
🔄 Запрос #14834 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1478904
🔄 Запрос #14835 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1479003
🔄 Запрос #14836 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 95 спецификаций. Всего: 1479098
🔄 Запрос #14837 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 61 спецификаций. Всего: 1479159
🔄 Запрос #14838 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 1479276
🔄 Запрос #14839 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1479384
🔄 Запрос #14840 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1479497
🔄 Запрос #14841 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 85 спецификаций. Всего: 1479582
🔄 Запрос #14842 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 1479684
🔄 Запрос #14843 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 1479807
🔄 Запрос #14844 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 1479894
🔄 Запрос #14845 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1479987
🔄 Запрос #14846 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 1480107
🔄 Запрос #14847 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 1480225
🔄 Запрос #14848 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 1480343
🔄 Запрос #14849 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1480449
🔄 Запрос #14850 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 150 спецификаций. Всего: 1480599
🔄 Запрос #14851 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 141 спецификаций. Всего: 1480740
🔄 Запрос #14852 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 1480862
🔄 Запрос #14853 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 125 спецификаций. Всего: 1480987
🔄 Запрос #14854 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1481098
🔄 Запрос #14855 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 1481224
🔄 Запрос #14856 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 1481346
🔄 Запрос #14857 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1481445
🔄 Запрос #14858 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1481562
🔄 Запрос #14859 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1481674
🔄 Запрос #14860 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1481785
🔄 Запрос #14861 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 1481905
🔄 Запрос #14862 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1482020
🔄 Запрос #14863 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1482116
🔄 Запрос #14864 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1482227
🔄 Запрос #14865 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1482333
🔄 Запрос #14866 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1482440
🔄 Запрос #14867 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 1482537
🔄 Запрос #14868 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1482649
🔄 Запрос #14869 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1482747
🔄 Запрос #14870 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1482859
🔄 Запрос #14871 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1482974
🔄 Запрос #14872 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 1483093
🔄 Запрос #14873 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 1483213
🔄 Запрос #14874 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 1483331
🔄 Запрос #14875 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 125 спецификаций. Всего: 1483456
🔄 Запрос #14876 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1483577
🔄 Запрос #14877 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 129 спецификаций. Всего: 1483706
🔄 Запрос #14878 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 1483828
🔄 Запрос #14879 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1483944
🔄 Запрос #14880 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 1484071
🔄 Запрос #14881 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 1484189
🔄 Запрос #14882 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 1484306
🔄 Запрос #14883 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09

📥 Загружено 114 спецификаций. Всего: 1484420
🔄 Запрос #14884 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 1484527
🔄 Запрос #14885 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 1484637
🔄 Запрос #14886 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1484730
🔄 Запрос #14887 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1484826
🔄 Запрос #14888 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 1484923
🔄 Запрос #14889 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 1485014
🔄 Запрос #14890 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 77 спецификаций. Всего: 1485091
🔄 Запрос #14891 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1485187
🔄 Запрос #14892 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1485299
🔄 Запрос #14893 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1485404
🔄 Запрос #14894 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 1485530
🔄 Запрос #14895 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 1485637
🔄 Запрос #14896 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 1485737
🔄 Запрос #14897 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1485851
🔄 Запрос #14898 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1485965
🔄 Запрос #14899 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1486084
🔄 Запрос #14900 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 112 спецификаций. Всего: 1486196
🔄 Запрос #14901 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 131 спецификаций. Всего: 1486327
🔄 Запрос #14902 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1486446
🔄 Запрос #14903 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1486552
🔄 Запрос #14904 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 1486671
🔄 Запрос #14905 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 132 спецификаций. Всего: 1486803
🔄 Запрос #14906 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 1486920
🔄 Запрос #14907 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1487032
🔄 Запрос #14908 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 1487152
🔄 Запрос #14909 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1487258
🔄 Запрос #14910 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 1487359
🔄 Запрос #14911 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1487472
🔄 Запрос #14912 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 1487594
🔄 Запрос #14913 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 1487689
🔄 Запрос #14914 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 1487816
🔄 Запрос #14915 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1487927
📤 Сохранено 10022 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #14916 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1488038
🔄 Запрос #14917 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1488143
🔄 Запрос #14918 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 1488245
🔄 Запрос #14919 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 1488346
🔄 Запрос #14920 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1488450
🔄 Запрос #14921 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1488558
🔄 Запрос #14922 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 85 спецификаций. Всего: 1488643
🔄 Запрос #14923 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 1488740
🔄 Запрос #14924 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1488852
🔄 Запрос #14925 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1488973
🔄 Запрос #14926 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1489079
🔄 Запрос #14927 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1489200
🔄 Запрос #14928 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1489312
🔄 Запрос #14929 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 1489427
🔄 Запрос #14930 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1489525
🔄 Запрос #14931 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1489630
🔄 Запрос #14932 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1489734
🔄 Запрос #14933 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 62 спецификаций. Всего: 1489796
🔄 Запрос #14934 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 92 спецификаций. Всего: 1489888
🔄 Запрос #14935 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 73 спецификаций. Всего: 1489961
🔄 Запрос #14936 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 1490064
🔄 Запрос #14937 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1490172
🔄 Запрос #14938 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 1490258
🔄 Запрос #14939 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 83 спецификаций. Всего: 1490341
🔄 Запрос #14940 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 92 спецификаций. Всего: 1490433
🔄 Запрос #14941 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 1490520
🔄 Запрос #14942 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 132 спецификаций. Всего: 1490652
🔄 Запрос #14943 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 1490776
🔄 Запрос #14944 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1490892
🔄 Запрос #14945 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1491008
🔄 Запрос #14946 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 1491128
🔄 Запрос #14947 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 140 спецификаций. Всего: 1491268
🔄 Запрос #14948 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 144 спецификаций. Всего: 1491412
🔄 Запрос #14949 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 152 спецификаций. Всего: 1491564
🔄 Запрос #14950 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 130 спецификаций. Всего: 1491694
🔄 Запрос #14951 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 133 спецификаций. Всего: 1491827

🔄 Запрос #14952 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 129 спецификаций. Всего: 1491956
🔄 Запрос #14953 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 128 спецификаций. Всего: 1492084
🔄 Запрос #14954 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1492205
🔄 Запрос #14955 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1492304
🔄 Запрос #14956 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 1492414
🔄 Запрос #14957 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 125 спецификаций. Всего: 1492539
🔄 Запрос #14958 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 1492659
🔄 Запрос #14959 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 1492783
🔄 Запрос #14960 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1492894
🔄 Запрос #14961 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1493006
🔄 Запрос #14962 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 1493123
🔄 Запрос #14963 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 137 спецификаций. Всего: 1493260
🔄 Запрос #14964 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1493374
🔄 Запрос #14965 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1493485
🔄 Запрос #14966 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1493601
🔄 Запрос #14967 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1493700
🔄 Запрос #14968 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 1493803
🔄 Запрос #14969 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 1493910
🔄 Запрос #14970 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1494022
🔄 Запрос #14971 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1494127
🔄 Запрос #14972 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1494229
🔄 Запрос #14973 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1494340
🔄 Запрос #14974 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 90 спецификаций. Всего: 1494430
🔄 Запрос #14975 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 1494531
🔄 Запрос #14976 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1494629
🔄 Запрос #14977 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 1494730
🔄 Запрос #14978 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 84 спецификаций. Всего: 1494814
🔄 Запрос #14979 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 61 спецификаций. Всего: 1494875
🔄 Запрос #14980 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 81 спецификаций. Всего: 1494956
🔄 Запрос #14981 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1495049
🔄 Запрос #14982 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 76 спецификаций. Всего: 1495125
🔄 Запрос #14983 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 1495214
🔄 Запрос #14984 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 80 спецификаций. Всего: 1495294
🔄 Запрос #14985 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1495405
🔄 Запрос #14986 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 1495529
🔄 Запрос #14987 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 134 спецификаций. Всего: 1495663
🔄 Запрос #14988 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1495777
🔄 Запрос #14989 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1495891
🔄 Запрос #14990 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1496003
🔄 Запрос #14991 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 1496110
🔄 Запрос #14992 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1496214
🔄 Запрос #14993 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 1496316
🔄 Запрос #14994 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 1496419
🔄 Запрос #14995 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 1496529
🔄 Запрос #14996 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 1496616
🔄 Запрос #14997 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1496709
🔄 Запрос #14998 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 1496800
🔄 Запрос #14999 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1496916
🔄 Запрос #15000 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 1497036
🔄 Запрос #15001 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1497140
🔄 Запрос #15002 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 1497264
🔄 Запрос #15003 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 1497390
🔄 Запрос #15004 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 1497500
🔄 Запрос #15005 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1497599
🔄 Запрос #15006 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1497697
🔄 Запрос #15007 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 1497800
🔄 Запрос #15008 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 77 спецификаций. Всего: 1497877
🔄 Запрос #15009 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 1497965
📤 Сохранено 10038 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #15010 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1498063
🔄 Запрос #15011 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1498169
🔄 Запрос #15012 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 75 спецификаций. Всего: 1498244
🔄 Запрос #15013 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 1498341
🔄 Запрос #15014 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 76 спецификаций. Всего: 1498417
🔄 Запрос #15015 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 70 спецификаций. Всего: 1498487
🔄 Запрос #15016 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 70 спецификаций. Всего: 1498557
🔄 Запрос #15017 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1498663
🔄 Запрос #15018 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1498774
🔄 Запрос #15019 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09

📥 Загружено 82 спецификаций. Всего: 1498856
🔄 Запрос #15020 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 1498957
🔄 Запрос #15021 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 1499057
🔄 Запрос #15022 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1499163
🔄 Запрос #15023 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 152 спецификаций. Всего: 1499315
🔄 Запрос #15024 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 82 спецификаций. Всего: 1499397
🔄 Запрос #15025 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 74 спецификаций. Всего: 1499471
🔄 Запрос #15026 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 77 спецификаций. Всего: 1499548
🔄 Запрос #15027 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 69 спецификаций. Всего: 1499617
🔄 Запрос #15028 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1499713
🔄 Запрос #15029 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 67 спецификаций. Всего: 1499780
🔄 Запрос #15030 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 82 спецификаций. Всего: 1499862
🔄 Запрос #15031 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1499955
🔄 Запрос #15032 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 82 спецификаций. Всего: 1500037
🔄 Запрос #15033 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1500130
🔄 Запрос #15034 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1500236
🔄 Запрос #15035 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 1500357
🔄 Запрос #15036 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 141 спецификаций. Всего: 1500498
🔄 Запрос #15037 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 159 спецификаций. Всего: 1500657
🔄 Запрос #15038 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1500757
🔄 Запрос #15039 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 1500870
🔄 Запрос #15040 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1500978
🔄 Запрос #15041 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 1501098
🔄 Запрос #15042 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 131 спецификаций. Всего: 1501229
🔄 Запрос #15043 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1501335
🔄 Запрос #15044 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 1501462
🔄 Запрос #15045 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 132 спецификаций. Всего: 1501594
🔄 Запрос #15046 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 152 спецификаций. Всего: 1501746
🔄 Запрос #15047 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 1501869
🔄 Запрос #15048 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 142 спецификаций. Всего: 1502011
🔄 Запрос #15049 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1502119
🔄 Запрос #15050 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 1502242
🔄 Запрос #15051 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 76 спецификаций. Всего: 1502318
🔄 Запрос #15052 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 75 спецификаций. Всего: 1502393
🔄 Запрос #15053 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 32 спецификаций. Всего: 1502425
🔄 Запрос #15054 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 33 спецификаций. Всего: 1502458
🔄 Запрос #15055 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 130 спецификаций. Всего: 1502588
🔄 Запрос #15056 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 147 спецификаций. Всего: 1502735
🔄 Запрос #15057 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 1502859
🔄 Запрос #15058 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 1502981
🔄 Запрос #15059 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 1503072
🔄 Запрос #15060 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 1503172
🔄 Запрос #15061 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 1503283
🔄 Запрос #15062 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 1503409
🔄 Запрос #15063 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 1503535
🔄 Запрос #15064 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 1503657
🔄 Запрос #15065 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1503784
🔄 Запрос #15066 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1503892
🔄 Запрос #15067 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 1504011
🔄 Запрос #15068 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 1504114
🔄 Запрос #15069 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1504219
🔄 Запрос #15070 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1504324
🔄 Запрос #15071 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1504429
🔄 Запрос #15072 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 1504520
🔄 Запрос #15073 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1504616
🔄 Запрос #15074 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1504712
🔄 Запрос #15075 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 84 спецификаций. Всего: 1504796
🔄 Запрос #15076 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1504901
🔄 Запрос #15077 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 71 спецификаций. Всего: 1504972
🔄 Запрос #15078 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 78 спецификаций. Всего: 1505050
🔄 Запрос #15079 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 69 спецификаций. Всего: 1505119
🔄 Запрос #15080 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 76 спецификаций. Всего: 1505195
🔄 Запрос #15081 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1505288
🔄 Запрос #15082 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 1505373
🔄 Запрос #15083 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 80 спецификаций. Всего: 1505453
🔄 Запрос #15084 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 1505539
🔄 Запрос #15085 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1505635
🔄 Запрос #15086 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1505740
🔄 Запрос #15087 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 1505839
🔄 Запрос #15088 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1505945

🔄 Запрос #15089 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 1506061
🔄 Запрос #15090 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 1506183
🔄 Запрос #15091 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 1506286
🔄 Запрос #15092 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 1506390
🔄 Запрос #15093 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 1506493
🔄 Запрос #15094 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 1506586
🔄 Запрос #15095 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 1506672
🔄 Запрос #15096 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 1506767
🔄 Запрос #15097 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 1506863
🔄 Запрос #15098 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 1506975
🔄 Запрос #15099 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 183 спецификаций. Всего: 1507158
🔄 Запрос #15100 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 136 спецификаций. Всего: 1507294
🔄 Запрос #15101 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 1507402
🔄 Запрос #15102 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 1507508
🔄 Запрос #15103 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 3/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
Сервер недоступен. Ожидаем восстановления связи...
Проблема с запросом — повторяем диапазон.
Диапазон не завершен, повторяем через 30 секунд...
📅 Обрабатываем диапазон 2024-03-28 20:44:09 - 2024-04-04 20:44:09 (попытка 2/5)
🔄 Запрос #15104 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 1507634
🔄 Запрос #15105 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 1507743
🔄 Запрос #15106 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1507848
🔄 Запрос #15107 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 1507946
🔄 Запрос #15108 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 1508032
📤 Сохранено 10067 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #15109 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 1508134
🔄 Запрос #15110 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 82 спецификаций. Всего: 1508216
🔄 Запрос #15111 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 1508321
🔄 Запрос #15112 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 1508416
🔄 Запрос #15113 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 1508530
🔄 Запрос #15114 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 1508624
🔄 Запрос #15115 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 90 спецификаций. Всего: 1508714
🔄 Запрос #15116 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 47 спецификаций. Всего: 1508761
🔄 Запрос #15117 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 59 спецификаций. Всего: 1508820
🔄 Запрос #15118 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 63 спецификаций. Всего: 1508883
🔄 Запрос #15119 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 64 спецификаций. Всего: 1508947
🔄 Запрос #15120 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 55 спецификаций. Всего: 1509002
🔄 Запрос #15121 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 82 спецификаций. Всего: 1509084
🔄 Запрос #15122 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 96 спецификаций. Всего: 1509180
🔄 Запрос #15123 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 1509266
🔄 Запрос #15124 для 2024-03-28 20:44:09 - 2024-04-04 20:44:09
📥 Загружено 65 спецификаций. Всего: 1509331
📅 Обрабатываем диапазон 2024-03-21 20:44:09 - 2024-03-28 20:44:09 (попытка 1/5)
🔄 Запрос #15125 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 1509412
🔄 Запрос #15126 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 78 спецификаций. Всего: 1509490
🔄 Запрос #15127 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 115 спецификаций. Всего: 1509605
🔄 Запрос #15128 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 111 спецификаций. Всего: 1509716
🔄 Запрос #15129 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 129 спецификаций. Всего: 1509845
🔄 Запрос #15130 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 119 спецификаций. Всего: 1509964
🔄 Запрос #15131 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 106 спецификаций. Всего: 1510070
🔄 Запрос #15132 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1510196
🔄 Запрос #15133 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 113 спецификаций. Всего: 1510309
🔄 Запрос #15134 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 118 спецификаций. Всего: 1510427
🔄 Запрос #15135 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 124 спецификаций. Всего: 1510551
🔄 Запрос #15136 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 109 спецификаций. Всего: 1510660
🔄 Запрос #15137 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 118 спецификаций. Всего: 1510778
🔄 Запрос #15138 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1510883
🔄 Запрос #15139 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1510977
🔄 Запрос #15140 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 1511068
🔄 Запрос #15141 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 109 спецификаций. Всего: 1511177
🔄 Запрос #15142 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 1511278
🔄 Запрос #15143 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 1511366
🔄 Запрос #15144 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 70 спецификаций. Всего: 1511436
🔄 Запрос #15145 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 85 спецификаций. Всего: 1511521
🔄 Запрос #15146 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 84 спецификаций. Всего: 1511605
🔄 Запрос #15147 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 1511701
🔄 Запрос #15148 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 1511792
🔄 Запрос #15149 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 76 спецификаций. Всего: 1511868
🔄 Запрос #15150 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 114 спецификаций. Всего: 1511982
🔄 Запрос #15151 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 1512078
🔄 Запрос #15152 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09

📥 Загружено 74 спецификаций. Всего: 1512152
🔄 Запрос #15153 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 99 спецификаций. Всего: 1512251
🔄 Запрос #15154 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 110 спецификаций. Всего: 1512361
🔄 Запрос #15155 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 1512454
🔄 Запрос #15156 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 83 спецификаций. Всего: 1512537
🔄 Запрос #15157 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 80 спецификаций. Всего: 1512617
🔄 Запрос #15158 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 89 спецификаций. Всего: 1512706
🔄 Запрос #15159 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 78 спецификаций. Всего: 1512784
🔄 Запрос #15160 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 74 спецификаций. Всего: 1512858
🔄 Запрос #15161 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 87 спецификаций. Всего: 1512945
🔄 Запрос #15162 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 77 спецификаций. Всего: 1513022
🔄 Запрос #15163 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 86 спецификаций. Всего: 1513108
🔄 Запрос #15164 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 94 спецификаций. Всего: 1513202
🔄 Запрос #15165 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 1513290
🔄 Запрос #15166 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 1513386
🔄 Запрос #15167 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 111 спецификаций. Всего: 1513497
🔄 Запрос #15168 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 111 спецификаций. Всего: 1513608
🔄 Запрос #15169 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 100 спецификаций. Всего: 1513708
🔄 Запрос #15170 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 116 спецификаций. Всего: 1513824
🔄 Запрос #15171 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 118 спецификаций. Всего: 1513942
🔄 Запрос #15172 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 113 спецификаций. Всего: 1514055
🔄 Запрос #15173 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 111 спецификаций. Всего: 1514166
🔄 Запрос #15174 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 113 спецификаций. Всего: 1514279
🔄 Запрос #15175 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 94 спецификаций. Всего: 1514373
🔄 Запрос #15176 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 1514461
🔄 Запрос #15177 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 95 спецификаций. Всего: 1514556
🔄 Запрос #15178 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 89 спецификаций. Всего: 1514645
🔄 Запрос #15179 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 82 спецификаций. Всего: 1514727
🔄 Запрос #15180 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 1514818
🔄 Запрос #15181 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 1514909
🔄 Запрос #15182 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 108 спецификаций. Всего: 1515017
🔄 Запрос #15183 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 1515121
🔄 Запрос #15184 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 1515209
🔄 Запрос #15185 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 145 спецификаций. Всего: 1515354
🔄 Запрос #15186 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 171 спецификаций. Всего: 1515525
🔄 Запрос #15187 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 119 спецификаций. Всего: 1515644
🔄 Запрос #15188 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 1515745
🔄 Запрос #15189 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 1515842
🔄 Запрос #15190 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 1515933
🔄 Запрос #15191 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1516037
🔄 Запрос #15192 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 95 спецификаций. Всего: 1516132
🔄 Запрос #15193 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 1516213
🔄 Запрос #15194 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 94 спецификаций. Всего: 1516307
🔄 Запрос #15195 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 92 спецификаций. Всего: 1516399
🔄 Запрос #15196 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1516503
🔄 Запрос #15197 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 1516604
🔄 Запрос #15198 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 89 спецификаций. Всего: 1516693
🔄 Запрос #15199 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 1516781
🔄 Запрос #15200 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 63 спецификаций. Всего: 1516844
🔄 Запрос #15201 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 74 спецификаций. Всего: 1516918
🔄 Запрос #15202 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 58 спецификаций. Всего: 1516976
🔄 Запрос #15203 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 71 спецификаций. Всего: 1517047
🔄 Запрос #15204 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 140 спецификаций. Всего: 1517187
🔄 Запрос #15205 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 150 спецификаций. Всего: 1517337
🔄 Запрос #15206 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 119 спецификаций. Всего: 1517456
🔄 Запрос #15207 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 129 спецификаций. Всего: 1517585
🔄 Запрос #15208 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 123 спецификаций. Всего: 1517708
🔄 Запрос #15209 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 99 спецификаций. Всего: 1517807
🔄 Запрос #15210 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 117 спецификаций. Всего: 1517924
🔄 Запрос #15211 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 122 спецификаций. Всего: 1518046
📤 Сохранено 10014 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #15212 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 95 спецификаций. Всего: 1518141
🔄 Запрос #15213 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 118 спецификаций. Всего: 1518259
🔄 Запрос #15214 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 150 спецификаций. Всего: 1518409
🔄 Запрос #15215 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 146 спецификаций. Всего: 1518555
🔄 Запрос #15216 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 110 спецификаций. Всего: 1518665
🔄 Запрос #15217 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 90 спецификаций. Всего: 1518755
🔄 Запрос #15218 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 107 спецификаций. Всего: 1518862
🔄 Запрос #15219 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 1518965
🔄 Запрос #15220 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 105 спецификаций. Всего: 1519070
🔄 Запрос #15221 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 111 спецификаций. Всего: 1519181
🔄 Запрос #15222 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09

📥 Загружено 109 спецификаций. Всего: 1519290
🔄 Запрос #15223 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 114 спецификаций. Всего: 1519404
🔄 Запрос #15224 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 108 спецификаций. Всего: 1519512
🔄 Запрос #15225 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 1519605
🔄 Запрос #15226 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 105 спецификаций. Всего: 1519710
🔄 Запрос #15227 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 1519806
🔄 Запрос #15228 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 1519897
🔄 Запрос #15229 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 78 спецификаций. Всего: 1519975
🔄 Запрос #15230 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 72 спецификаций. Всего: 1520047
🔄 Запрос #15231 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 64 спецификаций. Всего: 1520111
🔄 Запрос #15232 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 75 спецификаций. Всего: 1520186
🔄 Запрос #15233 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 89 спецификаций. Всего: 1520275
🔄 Запрос #15234 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 113 спецификаций. Всего: 1520388
🔄 Запрос #15235 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 1520486
🔄 Запрос #15236 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 1520584
🔄 Запрос #15237 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 1520675
🔄 Запрос #15238 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 98 спецификаций. Всего: 1520773
🔄 Запрос #15239 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 94 спецификаций. Всего: 1520867
🔄 Запрос #15240 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 78 спецификаций. Всего: 1520945
🔄 Запрос #15241 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 101 спецификаций. Всего: 1521046
🔄 Запрос #15242 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 1521139
🔄 Запрос #15243 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 1521220
🔄 Запрос #15244 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 1521321
🔄 Запрос #15245 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 1521402
🔄 Запрос #15246 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 1521483
🔄 Запрос #15247 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 66 спецификаций. Всего: 1521549
🔄 Запрос #15248 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 77 спецификаций. Всего: 1521626
🔄 Запрос #15249 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 1521707
🔄 Запрос #15250 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 70 спецификаций. Всего: 1521777
🔄 Запрос #15251 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 66 спецификаций. Всего: 1521843
🔄 Запрос #15252 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 67 спецификаций. Всего: 1521910
🔄 Запрос #15253 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 63 спецификаций. Всего: 1521973
🔄 Запрос #15254 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 79 спецификаций. Всего: 1522052
🔄 Запрос #15255 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 1522155
🔄 Запрос #15256 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 99 спецификаций. Всего: 1522254
🔄 Запрос #15257 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 95 спецификаций. Всего: 1522349
🔄 Запрос #15258 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 90 спецификаций. Всего: 1522439
🔄 Запрос #15259 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 90 спецификаций. Всего: 1522529
🔄 Запрос #15260 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 97 спецификаций. Всего: 1522626
🔄 Запрос #15261 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 106 спецификаций. Всего: 1522732
🔄 Запрос #15262 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 110 спецификаций. Всего: 1522842
🔄 Запрос #15263 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 1522945
🔄 Запрос #15264 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 102 спецификаций. Всего: 1523047
🔄 Запрос #15265 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 1523150
🔄 Запрос #15266 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 107 спецификаций. Всего: 1523257
🔄 Запрос #15267 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 107 спецификаций. Всего: 1523364
🔄 Запрос #15268 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 120 спецификаций. Всего: 1523484
🔄 Запрос #15269 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 1523588
🔄 Запрос #15270 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 109 спецификаций. Всего: 1523697
🔄 Запрос #15271 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 90 спецификаций. Всего: 1523787
🔄 Запрос #15272 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 78 спецификаций. Всего: 1523865
🔄 Запрос #15273 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 71 спецификаций. Всего: 1523936
🔄 Запрос #15274 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 83 спецификаций. Всего: 1524019
🔄 Запрос #15275 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 1524107
🔄 Запрос #15276 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 92 спецификаций. Всего: 1524199
🔄 Запрос #15277 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 1524303
🔄 Запрос #15278 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 115 спецификаций. Всего: 1524418
🔄 Запрос #15279 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 82 спецификаций. Всего: 1524500
🔄 Запрос #15280 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 106 спецификаций. Всего: 1524606
🔄 Запрос #15281 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 75 спецификаций. Всего: 1524681
🔄 Запрос #15282 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 86 спецификаций. Всего: 1524767
🔄 Запрос #15283 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 63 спецификаций. Всего: 1524830
🔄 Запрос #15284 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 95 спецификаций. Всего: 1524925
🔄 Запрос #15285 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 75 спецификаций. Всего: 1525000
🔄 Запрос #15286 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 73 спецификаций. Всего: 1525073
🔄 Запрос #15287 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 72 спецификаций. Всего: 1525145
🔄 Запрос #15288 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 94 спецификаций. Всего: 1525239
🔄 Запрос #15289 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 113 спецификаций. Всего: 1525352
🔄 Запрос #15290 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 102 спецификаций. Всего: 1525454
🔄 Запрос #15291 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 1525550
🔄 Запрос #15292 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 137 спецификаций. Всего: 1525687
🔄 Запрос #15293 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 139 спецификаций. Всего: 1525826
🔄 Запрос #15294 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 129 спецификаций. Всего: 1525955
🔄 Запрос #15295 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09

📥 Загружено 151 спецификаций. Всего: 1526106
🔄 Запрос #15296 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 134 спецификаций. Всего: 1526240
🔄 Запрос #15297 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 121 спецификаций. Всего: 1526361
🔄 Запрос #15298 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 120 спецификаций. Всего: 1526481
🔄 Запрос #15299 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 132 спецификаций. Всего: 1526613
🔄 Запрос #15300 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 114 спецификаций. Всего: 1526727
🔄 Запрос #15301 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1526853
🔄 Запрос #15302 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1526959
🔄 Запрос #15303 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 147 спецификаций. Всего: 1527106
🔄 Запрос #15304 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 85 спецификаций. Всего: 1527191
🔄 Запрос #15305 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 1527295
🔄 Запрос #15306 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 95 спецификаций. Всего: 1527390
🔄 Запрос #15307 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 79 спецификаций. Всего: 1527469
🔄 Запрос #15308 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 92 спецификаций. Всего: 1527561
🔄 Запрос #15309 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 1527652
🔄 Запрос #15310 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 100 спецификаций. Всего: 1527752
🔄 Запрос #15311 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 1527845
🔄 Запрос #15312 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1527949
🔄 Запрос #15313 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 1528037
🔄 Запрос #15314 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 80 спецификаций. Всего: 1528117
📤 Сохранено 10071 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #15315 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 89 спецификаций. Всего: 1528206
🔄 Запрос #15316 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 1528299
🔄 Запрос #15317 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 78 спецификаций. Всего: 1528377
🔄 Запрос #15318 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 100 спецификаций. Всего: 1528477
🔄 Запрос #15319 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 1528560
🔄 Запрос #15320 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 1528664
🔄 Запрос #15321 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 97 спецификаций. Всего: 1528761
🔄 Запрос #15322 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 85 спецификаций. Всего: 1528846
🔄 Запрос #15323 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 77 спецификаций. Всего: 1528923
🔄 Запрос #15324 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 57 спецификаций. Всего: 1528980
🔄 Запрос #15325 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 97 спецификаций. Всего: 1529077
🔄 Запрос #15326 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 1529181
🔄 Запрос #15327 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 80 спецификаций. Всего: 1529261
🔄 Запрос #15328 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 99 спецификаций. Всего: 1529360
🔄 Запрос #15329 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 1529441
🔄 Запрос #15330 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 89 спецификаций. Всего: 1529530
🔄 Запрос #15331 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 1529621
🔄 Запрос #15332 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 102 спецификаций. Всего: 1529723
🔄 Запрос #15333 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 103 спецификаций. Всего: 1529826
🔄 Запрос #15334 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 101 спецификаций. Всего: 1529927
🔄 Запрос #15335 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 112 спецификаций. Всего: 1530039
🔄 Запрос #15336 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1530140
🔄 Запрос #15337 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 118 спецификаций. Всего: 1530258
🔄 Запрос #15338 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 111 спецификаций. Всего: 1530369
🔄 Запрос #15339 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 104 спецификаций. Всего: 1530473
🔄 Запрос #15340 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 79 спецификаций. Всего: 1530552
🔄 Запрос #15341 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 86 спецификаций. Всего: 1530638
🔄 Запрос #15342 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 90 спецификаций. Всего: 1530728
🔄 Запрос #15343 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 97 спецификаций. Всего: 1530825
🔄 Запрос #15344 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 102 спецификаций. Всего: 1530927
🔄 Запрос #15345 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 90 спецификаций. Всего: 1531017
🔄 Запрос #15346 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 78 спецификаций. Всего: 1531095
🔄 Запрос #15347 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 118 спецификаций. Всего: 1531213
🔄 Запрос #15348 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 115 спецификаций. Всего: 1531328
🔄 Запрос #15349 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1531422
🔄 Запрос #15350 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 1531518
🔄 Запрос #15351 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1531612
🔄 Запрос #15352 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 64 спецификаций. Всего: 1531676
🔄 Запрос #15353 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 111 спецификаций. Всего: 1531787
🔄 Запрос #15354 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 138 спецификаций. Всего: 1531925
🔄 Запрос #15355 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 81 спецификаций. Всего: 1532006
🔄 Запрос #15356 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 69 спецификаций. Всего: 1532075
🔄 Запрос #15357 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 105 спецификаций. Всего: 1532180
🔄 Запрос #15358 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 80 спецификаций. Всего: 1532260
🔄 Запрос #15359 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 102 спецификаций. Всего: 1532362
🔄 Запрос #15360 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 127 спецификаций. Всего: 1532489
🔄 Запрос #15361 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 64 спецификаций. Всего: 1532553
🔄 Запрос #15362 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09

📥 Загружено 93 спецификаций. Всего: 1532646
🔄 Запрос #15363 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 88 спецификаций. Всего: 1532734
🔄 Запрос #15364 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 137 спецификаций. Всего: 1532871
🔄 Запрос #15365 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 116 спецификаций. Всего: 1532987
🔄 Запрос #15366 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 97 спецификаций. Всего: 1533084
🔄 Запрос #15367 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1533180
🔄 Запрос #15368 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 128 спецификаций. Всего: 1533308
🔄 Запрос #15369 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 96 спецификаций. Всего: 1533404
🔄 Запрос #15370 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 109 спецификаций. Всего: 1533513
🔄 Запрос #15371 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 111 спецификаций. Всего: 1533624
🔄 Запрос #15372 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 159 спецификаций. Всего: 1533783
🔄 Запрос #15373 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 133 спецификаций. Всего: 1533916
🔄 Запрос #15374 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1534033
🔄 Запрос #15375 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 114 спецификаций. Всего: 1534147
🔄 Запрос #15376 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 155 спецификаций. Всего: 1534302
🔄 Запрос #15377 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 120 спецификаций. Всего: 1534422
🔄 Запрос #15378 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 74 спецификаций. Всего: 1534496
🔄 Запрос #15379 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 89 спецификаций. Всего: 1534585
🔄 Запрос #15380 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 130 спецификаций. Всего: 1534715
🔄 Запрос #15381 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 72 спецификаций. Всего: 1534787
🔄 Запрос #15382 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 134 спецификаций. Всего: 1534921
🔄 Запрос #15383 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1535029
🔄 Запрос #15384 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 137 спецификаций. Всего: 1535166
🔄 Запрос #15385 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 150 спецификаций. Всего: 1535316
🔄 Запрос #15386 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 152 спецификаций. Всего: 1535468
🔄 Запрос #15387 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 138 спецификаций. Всего: 1535606
🔄 Запрос #15388 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 93 спецификаций. Всего: 1535699
🔄 Запрос #15389 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1535816
🔄 Запрос #15390 для 2024-03-21 20:44:09 - 2024-03-28 20:44:09
📥 Загружено 91 спецификаций. Всего: 1535907
📅 Обрабатываем диапазон 2024-03-14 20:44:09 - 2024-03-21 20:44:09 (попытка 1/5)
🔄 Запрос #15391 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 68 спецификаций. Всего: 1535975
🔄 Запрос #15392 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 130 спецификаций. Всего: 1536105
🔄 Запрос #15393 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 87 спецификаций. Всего: 1536192
🔄 Запрос #15394 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 54 спецификаций. Всего: 1536246
🔄 Запрос #15395 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 84 спецификаций. Всего: 1536330
🔄 Запрос #15396 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 96 спецификаций. Всего: 1536426
🔄 Запрос #15397 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 1536539
🔄 Запрос #15398 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 132 спецификаций. Всего: 1536671
🔄 Запрос #15399 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 119 спецификаций. Всего: 1536790
🔄 Запрос #15400 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 99 спецификаций. Всего: 1536889
🔄 Запрос #15401 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 75 спецификаций. Всего: 1536964
🔄 Запрос #15402 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 1537049
🔄 Запрос #15403 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 99 спецификаций. Всего: 1537148
🔄 Запрос #15404 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 1537232
🔄 Запрос #15405 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 80 спецификаций. Всего: 1537312
🔄 Запрос #15406 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 65 спецификаций. Всего: 1537377
🔄 Запрос #15407 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 78 спецификаций. Всего: 1537455
🔄 Запрос #15408 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 91 спецификаций. Всего: 1537546
🔄 Запрос #15409 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 81 спецификаций. Всего: 1537627
🔄 Запрос #15410 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 1537710
🔄 Запрос #15411 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 69 спецификаций. Всего: 1537779
🔄 Запрос #15412 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 62 спецификаций. Всего: 1537841
🔄 Запрос #15413 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 84 спецификаций. Всего: 1537925
🔄 Запрос #15414 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 1538025
🔄 Запрос #15415 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 120 спецификаций. Всего: 1538145
📤 Сохранено 10028 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #15416 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 89 спецификаций. Всего: 1538234
🔄 Запрос #15417 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 78 спецификаций. Всего: 1538312
🔄 Запрос #15418 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 1538422
🔄 Запрос #15419 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 1538527
🔄 Запрос #15420 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 1538628
🔄 Запрос #15421 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 79 спецификаций. Всего: 1538707
🔄 Запрос #15422 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 87 спецификаций. Всего: 1538794
🔄 Запрос #15423 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 1538895
🔄 Запрос #15424 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 89 спецификаций. Всего: 1538984
🔄 Запрос #15425 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 1539073
🔄 Запрос #15426 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09

📥 Загружено 81 спецификаций. Всего: 1539154
🔄 Запрос #15427 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 1539264
🔄 Запрос #15428 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 119 спецификаций. Всего: 1539383
🔄 Запрос #15429 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 115 спецификаций. Всего: 1539498
🔄 Запрос #15430 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 117 спецификаций. Всего: 1539615
🔄 Запрос #15431 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 73 спецификаций. Всего: 1539688
🔄 Запрос #15432 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 1539800
🔄 Запрос #15433 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 116 спецификаций. Всего: 1539916
🔄 Запрос #15434 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 120 спецификаций. Всего: 1540036
🔄 Запрос #15435 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1540147
🔄 Запрос #15436 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 142 спецификаций. Всего: 1540289
🔄 Запрос #15437 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 1540399
🔄 Запрос #15438 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 92 спецификаций. Всего: 1540491
🔄 Запрос #15439 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 86 спецификаций. Всего: 1540577
🔄 Запрос #15440 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 86 спецификаций. Всего: 1540663
🔄 Запрос #15441 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 77 спецификаций. Всего: 1540740
🔄 Запрос #15442 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 76 спецификаций. Всего: 1540816
🔄 Запрос #15443 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 87 спецификаций. Всего: 1540903
🔄 Запрос #15444 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 103 спецификаций. Всего: 1541006
🔄 Запрос #15445 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 1541118
🔄 Запрос #15446 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 1541227
🔄 Запрос #15447 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 124 спецификаций. Всего: 1541351
🔄 Запрос #15448 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 126 спецификаций. Всего: 1541477
🔄 Запрос #15449 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 108 спецификаций. Всего: 1541585
🔄 Запрос #15450 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 1541703
🔄 Запрос #15451 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 103 спецификаций. Всего: 1541806
🔄 Запрос #15452 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 87 спецификаций. Всего: 1541893
🔄 Запрос #15453 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 133 спецификаций. Всего: 1542026
🔄 Запрос #15454 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 1542126
🔄 Запрос #15455 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 142 спецификаций. Всего: 1542268
🔄 Запрос #15456 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 1542374
🔄 Запрос #15457 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 165 спецификаций. Всего: 1542539
🔄 Запрос #15458 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 115 спецификаций. Всего: 1542654
🔄 Запрос #15459 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 126 спецификаций. Всего: 1542780
🔄 Запрос #15460 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1542905
🔄 Запрос #15461 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 141 спецификаций. Всего: 1543046
🔄 Запрос #15462 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 147 спецификаций. Всего: 1543193
🔄 Запрос #15463 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 1543298
🔄 Запрос #15464 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 133 спецификаций. Всего: 1543431
🔄 Запрос #15465 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 136 спецификаций. Всего: 1543567
🔄 Запрос #15466 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 134 спецификаций. Всего: 1543701
🔄 Запрос #15467 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 115 спецификаций. Всего: 1543816
🔄 Запрос #15468 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 1543917
🔄 Запрос #15469 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 1544017
🔄 Запрос #15470 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 1544128
🔄 Запрос #15471 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 1544237
🔄 Запрос #15472 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1544337
🔄 Запрос #15473 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 1544446
🔄 Запрос #15474 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 1544547
🔄 Запрос #15475 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1544664
🔄 Запрос #15476 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 1544778
🔄 Запрос #15477 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 1544896
🔄 Запрос #15478 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 96 спецификаций. Всего: 1544992
🔄 Запрос #15479 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1545096
🔄 Запрос #15480 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 98 спецификаций. Всего: 1545194
🔄 Запрос #15481 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 97 спецификаций. Всего: 1545291
🔄 Запрос #15482 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 1545386
🔄 Запрос #15483 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 1545481
🔄 Запрос #15484 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 119 спецификаций. Всего: 1545600
🔄 Запрос #15485 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 117 спецификаций. Всего: 1545717
🔄 Запрос #15486 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 1545817
🔄 Запрос #15487 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 81 спецификаций. Всего: 1545898
🔄 Запрос #15488 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 88 спецификаций. Всего: 1545986
🔄 Запрос #15489 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 91 спецификаций. Всего: 1546077
🔄 Запрос #15490 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 96 спецификаций. Всего: 1546173
🔄 Запрос #15491 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 79 спецификаций. Всего: 1546252
🔄 Запрос #15492 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 97 спецификаций. Всего: 1546349
🔄 Запрос #15493 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 1546444

🔄 Запрос #15494 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 1546551
🔄 Запрос #15495 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 85 спецификаций. Всего: 1546636
🔄 Запрос #15496 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 82 спецификаций. Всего: 1546718
🔄 Запрос #15497 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 84 спецификаций. Всего: 1546802
🔄 Запрос #15498 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 78 спецификаций. Всего: 1546880
🔄 Запрос #15499 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 1547001
🔄 Запрос #15500 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 130 спецификаций. Всего: 1547131
🔄 Запрос #15501 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 121 спецификаций. Всего: 1547252
🔄 Запрос #15502 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 134 спецификаций. Всего: 1547386
🔄 Запрос #15503 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 122 спецификаций. Всего: 1547508
🔄 Запрос #15504 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 1547608
🔄 Запрос #15505 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 104 спецификаций. Всего: 1547712
🔄 Запрос #15506 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 1547822
🔄 Запрос #15507 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 1547927
🔄 Запрос #15508 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 1548048
🔄 Запрос #15509 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 124 спецификаций. Всего: 1548172
📤 Сохранено 10027 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #15510 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 1548273
🔄 Запрос #15511 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 93 спецификаций. Всего: 1548366
🔄 Запрос #15512 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 97 спецификаций. Всего: 1548463
🔄 Запрос #15513 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 1548564
🔄 Запрос #15514 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 99 спецификаций. Всего: 1548663
🔄 Запрос #15515 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 1548775
🔄 Запрос #15516 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 129 спецификаций. Всего: 1548904
🔄 Запрос #15517 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1549032
🔄 Запрос #15518 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 117 спецификаций. Всего: 1549149
🔄 Запрос #15519 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 115 спецификаций. Всего: 1549264
🔄 Запрос #15520 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 1549375
🔄 Запрос #15521 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 1549485
🔄 Запрос #15522 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 1549599
🔄 Запрос #15523 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 1549711
🔄 Запрос #15524 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 1549825
🔄 Запрос #15525 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 1549935
🔄 Запрос #15526 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 1550035
🔄 Запрос #15527 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 88 спецификаций. Всего: 1550123
🔄 Запрос #15528 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 92 спецификаций. Всего: 1550215
🔄 Запрос #15529 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 1550327
🔄 Запрос #15530 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 104 спецификаций. Всего: 1550431
🔄 Запрос #15531 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 1550536
🔄 Запрос #15532 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 104 спецификаций. Всего: 1550640
🔄 Запрос #15533 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 75 спецификаций. Всего: 1550715
🔄 Запрос #15534 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 1550816
🔄 Запрос #15535 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 69 спецификаций. Всего: 1550885
🔄 Запрос #15536 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 77 спецификаций. Всего: 1550962
🔄 Запрос #15537 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 86 спецификаций. Всего: 1551048
🔄 Запрос #15538 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1551176
🔄 Запрос #15539 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 117 спецификаций. Всего: 1551293
🔄 Запрос #15540 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 117 спецификаций. Всего: 1551410
🔄 Запрос #15541 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 1551528
🔄 Запрос #15542 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 1551656
🔄 Запрос #15543 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 160 спецификаций. Всего: 1551816
🔄 Запрос #15544 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 131 спецификаций. Всего: 1551947
🔄 Запрос #15545 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 140 спецификаций. Всего: 1552087
🔄 Запрос #15546 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 1552201
🔄 Запрос #15547 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 119 спецификаций. Всего: 1552320
🔄 Запрос #15548 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 131 спецификаций. Всего: 1552451
🔄 Запрос #15549 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 1552562
🔄 Запрос #15550 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 87 спецификаций. Всего: 1552649
🔄 Запрос #15551 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 96 спецификаций. Всего: 1552745
🔄 Запрос #15552 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 1552828
🔄 Запрос #15553 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 1552911
🔄 Запрос #15554 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 1553001
🔄 Запрос #15555 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 1553114
🔄 Запрос #15556 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 103 спецификаций. Всего: 1553217
🔄 Запрос #15557 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 87 спецификаций. Всего: 1553304
🔄 Запрос #15558 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 1553403
🔄 Запрос #15559 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 1553509
🔄 Запрос #15560 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 132 спецификаций. Всего: 1553641
🔄 Запрос #15561 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 1553769
🔄 Запрос #15562 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09

📥 Загружено 125 спецификаций. Всего: 1553894
🔄 Запрос #15563 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 125 спецификаций. Всего: 1554019
🔄 Запрос #15564 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 1554124
🔄 Запрос #15565 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 1554235
🔄 Запрос #15566 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 3/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
Сервер недоступен. Ожидаем восстановления связи...
Проблема с запросом — повторяем диапазон.
Диапазон не завершен, повторяем через 30 секунд...
📅 Обрабатываем диапазон 2024-03-14 20:44:09 - 2024-03-21 20:44:09 (попытка 2/5)
🔄 Запрос #15567 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 125 спецификаций. Всего: 1554360
🔄 Запрос #15568 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1554485
🔄 Запрос #15569 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 1554586
🔄 Запрос #15570 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 1554680
🔄 Запрос #15571 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 84 спецификаций. Всего: 1554764
🔄 Запрос #15572 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 93 спецификаций. Всего: 1554857
🔄 Запрос #15573 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1554961
🔄 Запрос #15574 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 102 спецификаций. Всего: 1555063
🔄 Запрос #15575 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 1555172
🔄 Запрос #15576 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 115 спецификаций. Всего: 1555287
🔄 Запрос #15577 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 1555382
🔄 Запрос #15578 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 80 спецификаций. Всего: 1555462
🔄 Запрос #15579 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 80 спецификаций. Всего: 1555542
🔄 Запрос #15580 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 86 спецификаций. Всего: 1555628
🔄 Запрос #15581 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 82 спецификаций. Всего: 1555710
🔄 Запрос #15582 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 73 спецификаций. Всего: 1555783
🔄 Запрос #15583 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 1555866
🔄 Запрос #15584 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 43 спецификаций. Всего: 1555909
🔄 Запрос #15585 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 92 спецификаций. Всего: 1556001
🔄 Запрос #15586 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 101 спецификаций. Всего: 1556102
🔄 Запрос #15587 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 97 спецификаций. Всего: 1556199
🔄 Запрос #15588 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 1556311
🔄 Запрос #15589 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 125 спецификаций. Всего: 1556436
🔄 Запрос #15590 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 153 спецификаций. Всего: 1556589
🔄 Запрос #15591 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 154 спецификаций. Всего: 1556743
🔄 Запрос #15592 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1556871
🔄 Запрос #15593 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 137 спецификаций. Всего: 1557008
🔄 Запрос #15594 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 119 спецификаций. Всего: 1557127
🔄 Запрос #15595 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 130 спецификаций. Всего: 1557257
🔄 Запрос #15596 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 130 спецификаций. Всего: 1557387
🔄 Запрос #15597 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 125 спецификаций. Всего: 1557512
🔄 Запрос #15598 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 1557621
🔄 Запрос #15599 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 1557726
🔄 Запрос #15600 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 1557833
🔄 Запрос #15601 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 1557916
🔄 Запрос #15602 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 80 спецификаций. Всего: 1557996
🔄 Запрос #15603 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 92 спецификаций. Всего: 1558088
🔄 Запрос #15604 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 1558188
📤 Сохранено 10016 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #15605 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 104 спецификаций. Всего: 1558292
🔄 Запрос #15606 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 88 спецификаций. Всего: 1558380
🔄 Запрос #15607 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 98 спецификаций. Всего: 1558478
🔄 Запрос #15608 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 1558583
🔄 Запрос #15609 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 103 спецификаций. Всего: 1558686
🔄 Запрос #15610 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 1558798
🔄 Запрос #15611 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 104 спецификаций. Всего: 1558902
🔄 Запрос #15612 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1559020
🔄 Запрос #15613 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 1559114
🔄 Запрос #15614 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 1559227
🔄 Запрос #15615 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 118 спецификаций. Всего: 1559345
🔄 Запрос #15616 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 98 спецификаций. Всего: 1559443
🔄 Запрос #15617 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 1559553
🔄 Запрос #15618 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 1559660
🔄 Запрос #15619 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 1559754
🔄 Запрос #15620 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 81 спецификаций. Всего: 1559835
🔄 Запрос #15621 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 1559963
🔄 Запрос #15622 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 79 спецификаций. Всего: 1560042
🔄 Запрос #15623 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 137 спецификаций. Всего: 1560179
🔄 Запрос #15624 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 1560289
🔄 Запрос #15625 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 104 спецификаций. Всего: 1560393
🔄 Запрос #15626 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 75 спецификаций. Всего: 1560468
🔄 Запрос #15627 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09

📥 Загружено 78 спецификаций. Всего: 1560546
🔄 Запрос #15628 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 102 спецификаций. Всего: 1560648
🔄 Запрос #15629 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 47 спецификаций. Всего: 1560695
🔄 Запрос #15630 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 65 спецификаций. Всего: 1560760
🔄 Запрос #15631 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 1560866
🔄 Запрос #15632 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 98 спецификаций. Всего: 1560964
🔄 Запрос #15633 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 104 спецификаций. Всего: 1561068
🔄 Запрос #15634 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 1561163
🔄 Запрос #15635 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 62 спецификаций. Всего: 1561225
🔄 Запрос #15636 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 68 спецификаций. Всего: 1561293
🔄 Запрос #15637 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 61 спецификаций. Всего: 1561354
🔄 Запрос #15638 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 102 спецификаций. Всего: 1561456
🔄 Запрос #15639 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 1561569
🔄 Запрос #15640 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 128 спецификаций. Всего: 1561697
🔄 Запрос #15641 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 1561791
🔄 Запрос #15642 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 85 спецификаций. Всего: 1561876
🔄 Запрос #15643 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 59 спецификаций. Всего: 1561935
🔄 Запрос #15644 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 75 спецификаций. Всего: 1562010
🔄 Запрос #15645 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 50 спецификаций. Всего: 1562060
🔄 Запрос #15646 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 72 спецификаций. Всего: 1562132
🔄 Запрос #15647 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 78 спецификаций. Всего: 1562210
🔄 Запрос #15648 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 124 спецификаций. Всего: 1562334
🔄 Запрос #15649 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 75 спецификаций. Всего: 1562409
🔄 Запрос #15650 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 42 спецификаций. Всего: 1562451
🔄 Запрос #15651 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 56 спецификаций. Всего: 1562507
🔄 Запрос #15652 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 1562621
🔄 Запрос #15653 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 119 спецификаций. Всего: 1562740
🔄 Запрос #15654 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 59 спецификаций. Всего: 1562799
🔄 Запрос #15655 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 82 спецификаций. Всего: 1562881
🔄 Запрос #15656 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 91 спецификаций. Всего: 1562972
🔄 Запрос #15657 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 1563055
🔄 Запрос #15658 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 115 спецификаций. Всего: 1563170
🔄 Запрос #15659 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 182 спецификаций. Всего: 1563352
🔄 Запрос #15660 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 91 спецификаций. Всего: 1563443
🔄 Запрос #15661 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 127 спецификаций. Всего: 1563570
🔄 Запрос #15662 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 1563676
🔄 Запрос #15663 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 153 спецификаций. Всего: 1563829
🔄 Запрос #15664 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 120 спецификаций. Всего: 1563949
🔄 Запрос #15665 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 133 спецификаций. Всего: 1564082
🔄 Запрос #15666 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 82 спецификаций. Всего: 1564164
🔄 Запрос #15667 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 132 спецификаций. Всего: 1564296
🔄 Запрос #15668 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 99 спецификаций. Всего: 1564395
🔄 Запрос #15669 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 150 спецификаций. Всего: 1564545
🔄 Запрос #15670 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 130 спецификаций. Всего: 1564675
🔄 Запрос #15671 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 1564769
🔄 Запрос #15672 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 102 спецификаций. Всего: 1564871
🔄 Запрос #15673 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 117 спецификаций. Всего: 1564988
🔄 Запрос #15674 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 108 спецификаций. Всего: 1565096
🔄 Запрос #15675 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 1565186
🔄 Запрос #15676 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 85 спецификаций. Всего: 1565271
🔄 Запрос #15677 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 68 спецификаций. Всего: 1565339
🔄 Запрос #15678 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 96 спецификаций. Всего: 1565435
🔄 Запрос #15679 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 100 спецификаций. Всего: 1565535
🔄 Запрос #15680 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 96 спецификаций. Всего: 1565631
🔄 Запрос #15681 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 1565737
🔄 Запрос #15682 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 127 спецификаций. Всего: 1565864
🔄 Запрос #15683 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 113 спецификаций. Всего: 1565977
🔄 Запрос #15684 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 1566086
🔄 Запрос #15685 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 115 спецификаций. Всего: 1566201
🔄 Запрос #15686 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 1566291
🔄 Запрос #15687 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 83 спецификаций. Всего: 1566374
🔄 Запрос #15688 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 1566468
🔄 Запрос #15689 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 103 спецификаций. Всего: 1566571
🔄 Запрос #15690 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 92 спецификаций. Всего: 1566663
🔄 Запрос #15691 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 85 спецификаций. Всего: 1566748
🔄 Запрос #15692 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 85 спецификаций. Всего: 1566833
🔄 Запрос #15693 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 1566923
🔄 Запрос #15694 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 76 спецификаций. Всего: 1566999
🔄 Запрос #15695 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 86 спецификаций. Всего: 1567085
🔄 Запрос #15696 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 70 спецификаций. Всего: 1567155
🔄 Запрос #15697 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 1567245
🔄 Запрос #15698 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 81 спецификаций. Всего: 1567326
🔄 Запрос #15699 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 67 спецификаций. Всего: 1567393
🔄 Запрос #15700 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09

📥 Загружено 81 спецификаций. Всего: 1567474
🔄 Запрос #15701 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 75 спецификаций. Всего: 1567549
🔄 Запрос #15702 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 69 спецификаций. Всего: 1567618
🔄 Запрос #15703 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 74 спецификаций. Всего: 1567692
🔄 Запрос #15704 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 80 спецификаций. Всего: 1567772
🔄 Запрос #15705 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 1567886
🔄 Запрос #15706 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 157 спецификаций. Всего: 1568043
🔄 Запрос #15707 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1568160
🔄 Запрос #15708 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 129 спецификаций. Всего: 1568289
📤 Сохранено 10101 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #15709 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 147 спецификаций. Всего: 1568436
🔄 Запрос #15710 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1568561
🔄 Запрос #15711 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 80 спецификаций. Всего: 1568641
🔄 Запрос #15712 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 112 спецификаций. Всего: 1568753
🔄 Запрос #15713 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1568865
🔄 Запрос #15714 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1568980
🔄 Запрос #15715 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 95 спецификаций. Всего: 1569075
🔄 Запрос #15716 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 1569165
🔄 Запрос #15717 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 109 спецификаций. Всего: 1569274
🔄 Запрос #15718 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 104 спецификаций. Всего: 1569378
🔄 Запрос #15719 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 125 спецификаций. Всего: 1569503
🔄 Запрос #15720 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 122 спецификаций. Всего: 1569625
🔄 Запрос #15721 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 94 спецификаций. Всего: 1569719
🔄 Запрос #15722 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 1569809
🔄 Запрос #15723 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 107 спецификаций. Всего: 1569916
🔄 Запрос #15724 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 95 спецификаций. Всего: 1570011
🔄 Запрос #15725 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 93 спецификаций. Всего: 1570104
🔄 Запрос #15726 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 106 спецификаций. Всего: 1570210
🔄 Запрос #15727 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 125 спецификаций. Всего: 1570335
🔄 Запрос #15728 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 117 спецификаций. Всего: 1570452
🔄 Запрос #15729 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 96 спецификаций. Всего: 1570548
🔄 Запрос #15730 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 117 спецификаций. Всего: 1570665
🔄 Запрос #15731 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 108 спецификаций. Всего: 1570773
🔄 Запрос #15732 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 110 спецификаций. Всего: 1570883
🔄 Запрос #15733 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 1570994
🔄 Запрос #15734 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 116 спецификаций. Всего: 1571110
🔄 Запрос #15735 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 131 спецификаций. Всего: 1571241
🔄 Запрос #15736 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 108 спецификаций. Всего: 1571349
🔄 Запрос #15737 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 93 спецификаций. Всего: 1571442
🔄 Запрос #15738 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 105 спецификаций. Всего: 1571547
🔄 Запрос #15739 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 86 спецификаций. Всего: 1571633
🔄 Запрос #15740 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 79 спецификаций. Всего: 1571712
🔄 Запрос #15741 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 114 спецификаций. Всего: 1571826
🔄 Запрос #15742 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 119 спецификаций. Всего: 1571945
🔄 Запрос #15743 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 1572056
🔄 Запрос #15744 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 72 спецификаций. Всего: 1572128
🔄 Запрос #15745 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 85 спецификаций. Всего: 1572213
🔄 Запрос #15746 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 53 спецификаций. Всего: 1572266
🔄 Запрос #15747 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 80 спецификаций. Всего: 1572346
🔄 Запрос #15748 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 1572436
🔄 Запрос #15749 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 111 спецификаций. Всего: 1572547
🔄 Запрос #15750 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 67 спецификаций. Всего: 1572614
🔄 Запрос #15751 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 79 спецификаций. Всего: 1572693
🔄 Запрос #15752 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 90 спецификаций. Всего: 1572783
🔄 Запрос #15753 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 97 спецификаций. Всего: 1572880
🔄 Запрос #15754 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 126 спецификаций. Всего: 1573006
🔄 Запрос #15755 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 80 спецификаций. Всего: 1573086
🔄 Запрос #15756 для 2024-03-14 20:44:09 - 2024-03-21 20:44:09
📥 Загружено 17 спецификаций. Всего: 1573103
📅 Обрабатываем диапазон 2024-03-07 20:44:09 - 2024-03-14 20:44:09 (попытка 1/5)
🔄 Запрос #15757 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 135 спецификаций. Всего: 1573238
🔄 Запрос #15758 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 89 спецификаций. Всего: 1573327
🔄 Запрос #15759 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 134 спецификаций. Всего: 1573461
🔄 Запрос #15760 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 154 спецификаций. Всего: 1573615
🔄 Запрос #15761 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 161 спецификаций. Всего: 1573776
🔄 Запрос #15762 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 124 спецификаций. Всего: 1573900
🔄 Запрос #15763 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 1574004
🔄 Запрос #15764 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 90 спецификаций. Всего: 1574094
🔄 Запрос #15765 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09

📥 Загружено 101 спецификаций. Всего: 1574195
🔄 Запрос #15766 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 1574294
🔄 Запрос #15767 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 1574396
🔄 Запрос #15768 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1574492
🔄 Запрос #15769 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1574595
🔄 Запрос #15770 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 101 спецификаций. Всего: 1574696
🔄 Запрос #15771 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 95 спецификаций. Всего: 1574791
🔄 Запрос #15772 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 83 спецификаций. Всего: 1574874
🔄 Запрос #15773 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 1574965
🔄 Запрос #15774 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1575068
🔄 Запрос #15775 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 120 спецификаций. Всего: 1575188
🔄 Запрос #15776 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 1575296
🔄 Запрос #15777 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1575399
🔄 Запрос #15778 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 1575498
🔄 Запрос #15779 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1575601
🔄 Запрос #15780 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 82 спецификаций. Всего: 1575683
🔄 Запрос #15781 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 1575782
🔄 Запрос #15782 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 86 спецификаций. Всего: 1575868
🔄 Запрос #15783 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 84 спецификаций. Всего: 1575952
🔄 Запрос #15784 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 88 спецификаций. Всего: 1576040
🔄 Запрос #15785 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 1576123
🔄 Запрос #15786 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 95 спецификаций. Всего: 1576218
🔄 Запрос #15787 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 1576323
🔄 Запрос #15788 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 1576422
🔄 Запрос #15789 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 93 спецификаций. Всего: 1576515
🔄 Запрос #15790 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 88 спецификаций. Всего: 1576603
🔄 Запрос #15791 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1576714
🔄 Запрос #15792 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 86 спецификаций. Всего: 1576800
🔄 Запрос #15793 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 87 спецификаций. Всего: 1576887
🔄 Запрос #15794 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 82 спецификаций. Всего: 1576969
🔄 Запрос #15795 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 76 спецификаций. Всего: 1577045
🔄 Запрос #15796 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 81 спецификаций. Всего: 1577126
🔄 Запрос #15797 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 78 спецификаций. Всего: 1577204
🔄 Запрос #15798 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 87 спецификаций. Всего: 1577291
🔄 Запрос #15799 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 98 спецификаций. Всего: 1577389
🔄 Запрос #15800 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 1577495
🔄 Запрос #15801 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 101 спецификаций. Всего: 1577596
🔄 Запрос #15802 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 1577696
🔄 Запрос #15803 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1577799
🔄 Запрос #15804 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 90 спецификаций. Всего: 1577889
🔄 Запрос #15805 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 90 спецификаций. Всего: 1577979
🔄 Запрос #15806 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 1578093
🔄 Запрос #15807 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1578191
🔄 Запрос #15808 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 1578309
📤 Сохранено 10020 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #15809 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1578412
🔄 Запрос #15810 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1578520
🔄 Запрос #15811 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1578616
🔄 Запрос #15812 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 1578730
🔄 Запрос #15813 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 1578853
🔄 Запрос #15814 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1578960
🔄 Запрос #15815 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 1579073
🔄 Запрос #15816 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 1579173
🔄 Запрос #15817 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 1579289
🔄 Запрос #15818 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1579385
🔄 Запрос #15819 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 117 спецификаций. Всего: 1579502
🔄 Запрос #15820 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 132 спецификаций. Всего: 1579634
🔄 Запрос #15821 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 124 спецификаций. Всего: 1579758
🔄 Запрос #15822 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1579877
🔄 Запрос #15823 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1580003
🔄 Запрос #15824 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 1580121
🔄 Запрос #15825 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1580224
🔄 Запрос #15826 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1580331
🔄 Запрос #15827 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1580450
🔄 Запрос #15828 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 140 спецификаций. Всего: 1580590
🔄 Запрос #15829 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 135 спецификаций. Всего: 1580725
🔄 Запрос #15830 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1580844
🔄 Запрос #15831 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 1580957
🔄 Запрос #15832 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 128 спецификаций. Всего: 1581085
🔄 Запрос #15833 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 120 спецификаций. Всего: 1581205

🔄 Запрос #15834 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 1581318
🔄 Запрос #15835 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1581421
🔄 Запрос #15836 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 1581527
🔄 Запрос #15837 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 85 спецификаций. Всего: 1581612
🔄 Запрос #15838 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 55 спецификаций. Всего: 1581667
🔄 Запрос #15839 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 1581790
🔄 Запрос #15840 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 92 спецификаций. Всего: 1581882
🔄 Запрос #15841 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 53 спецификаций. Всего: 1581935
🔄 Запрос #15842 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 31 спецификаций. Всего: 1581966
🔄 Запрос #15843 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 52 спецификаций. Всего: 1582018
🔄 Запрос #15844 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 58 спецификаций. Всего: 1582076
🔄 Запрос #15845 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 75 спецификаций. Всего: 1582151
🔄 Запрос #15846 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 80 спецификаций. Всего: 1582231
🔄 Запрос #15847 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 97 спецификаций. Всего: 1582328
🔄 Запрос #15848 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 86 спецификаций. Всего: 1582414
🔄 Запрос #15849 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 143 спецификаций. Всего: 1582557
🔄 Запрос #15850 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 128 спецификаций. Всего: 1582685
🔄 Запрос #15851 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1582781
🔄 Запрос #15852 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 122 спецификаций. Всего: 1582903
🔄 Запрос #15853 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 1583012
🔄 Запрос #15854 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 1583123
🔄 Запрос #15855 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 110 спецификаций. Всего: 1583233
🔄 Запрос #15856 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 1583348
🔄 Запрос #15857 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 1583452
🔄 Запрос #15858 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 1583575
🔄 Запрос #15859 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 1583708
🔄 Запрос #15860 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 135 спецификаций. Всего: 1583843
🔄 Запрос #15861 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 1583961
🔄 Запрос #15862 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 1584086
🔄 Запрос #15863 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 146 спецификаций. Всего: 1584232
🔄 Запрос #15864 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1584350
🔄 Запрос #15865 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 125 спецификаций. Всего: 1584475
🔄 Запрос #15866 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 134 спецификаций. Всего: 1584609
🔄 Запрос #15867 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 122 спецификаций. Всего: 1584731
🔄 Запрос #15868 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 134 спецификаций. Всего: 1584865
🔄 Запрос #15869 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 1584977
🔄 Запрос #15870 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1585090
🔄 Запрос #15871 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 1585213
🔄 Запрос #15872 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 127 спецификаций. Всего: 1585340
🔄 Запрос #15873 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 134 спецификаций. Всего: 1585474
🔄 Запрос #15874 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 136 спецификаций. Всего: 1585610
🔄 Запрос #15875 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 56 спецификаций. Всего: 1585666
🔄 Запрос #15876 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 3 спецификаций. Всего: 1585669
🔄 Запрос #15877 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 7 спецификаций. Всего: 1585676
🔄 Запрос #15878 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 8 спецификаций. Всего: 1585684
🔄 Запрос #15879 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 7 спецификаций. Всего: 1585691
🔄 Запрос #15880 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 3 спецификаций. Всего: 1585694
🔄 Запрос #15881 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 32 спецификаций. Всего: 1585726
🔄 Запрос #15882 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 1585838
🔄 Запрос #15883 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 92 спецификаций. Всего: 1585930
🔄 Запрос #15884 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 1586032
🔄 Запрос #15885 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 1586123
🔄 Запрос #15886 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 101 спецификаций. Всего: 1586224
🔄 Запрос #15887 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1586331
🔄 Запрос #15888 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 1586435
🔄 Запрос #15889 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 98 спецификаций. Всего: 1586533
🔄 Запрос #15890 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 1586633
🔄 Запрос #15891 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 86 спецификаций. Всего: 1586719
🔄 Запрос #15892 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 1586823
🔄 Запрос #15893 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 1586922
🔄 Запрос #15894 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 94 спецификаций. Всего: 1587016
🔄 Запрос #15895 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 85 спецификаций. Всего: 1587101
🔄 Запрос #15896 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 98 спецификаций. Всего: 1587199
🔄 Запрос #15897 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 92 спецификаций. Всего: 1587291
🔄 Запрос #15898 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1587395
🔄 Запрос #15899 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 82 спецификаций. Всего: 1587477
🔄 Запрос #15900 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 99 спецификаций. Всего: 1587576
🔄 Запрос #15901 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 1587675
🔄 Запрос #15902 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 94 спецификаций. Всего: 1587769

🔄 Запрос #15903 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 79 спецификаций. Всего: 1587848
🔄 Запрос #15904 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1587944
🔄 Запрос #15905 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 86 спецификаций. Всего: 1588030
🔄 Запрос #15906 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 93 спецификаций. Всего: 1588123
🔄 Запрос #15907 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1588219
🔄 Запрос #15908 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 1588337
📤 Сохранено 10028 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #15909 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 1588428
🔄 Запрос #15910 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 1588534
🔄 Запрос #15911 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 1588649
🔄 Запрос #15912 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 1588763
🔄 Запрос #15913 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 128 спецификаций. Всего: 1588891
🔄 Запрос #15914 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 1588996
🔄 Запрос #15915 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 1589112
🔄 Запрос #15916 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 1589217
🔄 Запрос #15917 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1589336
🔄 Запрос #15918 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 1589452
🔄 Запрос #15919 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 1589560
🔄 Запрос #15920 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 3/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
Сервер недоступен. Ожидаем восстановления связи...
Проблема с запросом — повторяем диапазон.
Диапазон не завершен, повторяем через 30 секунд...
📅 Обрабатываем диапазон 2024-03-07 20:44:09 - 2024-03-14 20:44:09 (попытка 2/5)
🔄 Запрос #15921 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 1589678
🔄 Запрос #15922 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 1589786
🔄 Запрос #15923 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1589891
🔄 Запрос #15924 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 90 спецификаций. Всего: 1589981
🔄 Запрос #15925 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1590088
🔄 Запрос #15926 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1590184
🔄 Запрос #15927 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 1590296
🔄 Запрос #15928 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 1590405
🔄 Запрос #15929 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 1590511
🔄 Запрос #15930 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 101 спецификаций. Всего: 1590612
🔄 Запрос #15931 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1590719
🔄 Запрос #15932 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 107 спецификаций. Всего: 1590826
🔄 Запрос #15933 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 1590931
🔄 Запрос #15934 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1591027
🔄 Запрос #15935 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 1591127
🔄 Запрос #15936 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 1591226
🔄 Запрос #15937 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1591322
🔄 Запрос #15938 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 1591422
🔄 Запрос #15939 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 104 спецификаций. Всего: 1591526
🔄 Запрос #15940 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 100 спецификаций. Всего: 1591626
🔄 Запрос #15941 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1591719
🔄 Запрос #15942 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 1591810
🔄 Запрос #15943 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 76 спецификаций. Всего: 1591886
🔄 Запрос #15944 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1591993
🔄 Запрос #15945 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 80 спецификаций. Всего: 1592073
🔄 Запрос #15946 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 83 спецификаций. Всего: 1592156
🔄 Запрос #15947 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 78 спецификаций. Всего: 1592234
🔄 Запрос #15948 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 83 спецификаций. Всего: 1592317
🔄 Запрос #15949 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1592410
🔄 Запрос #15950 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 83 спецификаций. Всего: 1592493
🔄 Запрос #15951 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1592600
🔄 Запрос #15952 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 75 спецификаций. Всего: 1592675
🔄 Запрос #15953 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 88 спецификаций. Всего: 1592763
🔄 Запрос #15954 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 87 спецификаций. Всего: 1592850
🔄 Запрос #15955 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 63 спецификаций. Всего: 1592913
🔄 Запрос #15956 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 1593015
🔄 Запрос #15957 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 74 спецификаций. Всего: 1593089
🔄 Запрос #15958 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 85 спецификаций. Всего: 1593174
🔄 Запрос #15959 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 1593265
🔄 Запрос #15960 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 84 спецификаций. Всего: 1593349
🔄 Запрос #15961 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 87 спецификаций. Всего: 1593436
🔄 Запрос #15962 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1593543
🔄 Запрос #15963 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 88 спецификаций. Всего: 1593631
🔄 Запрос #15964 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1593734
🔄 Запрос #15965 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 62 спецификаций. Всего: 1593796
🔄 Запрос #15966 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09

📥 Загружено 86 спецификаций. Всего: 1593882
🔄 Запрос #15967 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 90 спецификаций. Всего: 1593972
🔄 Запрос #15968 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 73 спецификаций. Всего: 1594045
🔄 Запрос #15969 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 1594166
🔄 Запрос #15970 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1594285
🔄 Запрос #15971 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 1594396
🔄 Запрос #15972 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 97 спецификаций. Всего: 1594493
🔄 Запрос #15973 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 121 спецификаций. Всего: 1594614
🔄 Запрос #15974 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 132 спецификаций. Всего: 1594746
🔄 Запрос #15975 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1594865
🔄 Запрос #15976 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 107 спецификаций. Всего: 1594972
🔄 Запрос #15977 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 120 спецификаций. Всего: 1595092
🔄 Запрос #15978 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 124 спецификаций. Всего: 1595216
🔄 Запрос #15979 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 128 спецификаций. Всего: 1595344
🔄 Запрос #15980 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 1595460
🔄 Запрос #15981 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 1595571
🔄 Запрос #15982 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 78 спецификаций. Всего: 1595649
🔄 Запрос #15983 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 62 спецификаций. Всего: 1595711
🔄 Запрос #15984 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 98 спецификаций. Всего: 1595809
🔄 Запрос #15985 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 90 спецификаций. Всего: 1595899
🔄 Запрос #15986 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 97 спецификаций. Всего: 1595996
🔄 Запрос #15987 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1596091
🔄 Запрос #15988 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 70 спецификаций. Всего: 1596161
🔄 Запрос #15989 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 1596261
🔄 Запрос #15990 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 1596361
🔄 Запрос #15991 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 1596477
🔄 Запрос #15992 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 1596585
🔄 Запрос #15993 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1596696
🔄 Запрос #15994 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 1596798
🔄 Запрос #15995 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 98 спецификаций. Всего: 1596896
🔄 Запрос #15996 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 1596986
🔄 Запрос #15997 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 95 спецификаций. Всего: 1597081
🔄 Запрос #15998 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 1597199
🔄 Запрос #15999 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 1597298
🔄 Запрос #16000 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 101 спецификаций. Всего: 1597399
🔄 Запрос #16001 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1597501
🔄 Запрос #16002 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 110 спецификаций. Всего: 1597611
🔄 Запрос #16003 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 1597717
🔄 Запрос #16004 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 82 спецификаций. Всего: 1597799
🔄 Запрос #16005 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 97 спецификаций. Всего: 1597896
🔄 Запрос #16006 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 1598011
🔄 Запрос #16007 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 1598136
🔄 Запрос #16008 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 1598249
🔄 Запрос #16009 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 1598362
📤 Сохранено 10025 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #16010 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 117 спецификаций. Всего: 1598479
🔄 Запрос #16011 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 117 спецификаций. Всего: 1598596
🔄 Запрос #16012 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 1598701
🔄 Запрос #16013 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 101 спецификаций. Всего: 1598802
🔄 Запрос #16014 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1598909
🔄 Запрос #16015 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1599028
🔄 Запрос #16016 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 90 спецификаций. Всего: 1599118
🔄 Запрос #16017 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 80 спецификаций. Всего: 1599198
🔄 Запрос #16018 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 81 спецификаций. Всего: 1599279
🔄 Запрос #16019 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 84 спецификаций. Всего: 1599363
🔄 Запрос #16020 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 1599463
🔄 Запрос #16021 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 1599565
🔄 Запрос #16022 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 70 спецификаций. Всего: 1599635
🔄 Запрос #16023 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 1599740
🔄 Запрос #16024 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 90 спецификаций. Всего: 1599830
🔄 Запрос #16025 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 101 спецификаций. Всего: 1599931
🔄 Запрос #16026 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1600034
🔄 Запрос #16027 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1600137
🔄 Запрос #16028 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 136 спецификаций. Всего: 1600273
🔄 Запрос #16029 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 126 спецификаций. Всего: 1600399
🔄 Запрос #16030 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 136 спецификаций. Всего: 1600535
🔄 Запрос #16031 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 139 спецификаций. Всего: 1600674
🔄 Запрос #16032 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 155 спецификаций. Всего: 1600829
🔄 Запрос #16033 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 133 спецификаций. Всего: 1600962
🔄 Запрос #16034 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 131 спецификаций. Всего: 1601093
🔄 Запрос #16035 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 135 спецификаций. Всего: 1601228
🔄 Запрос #16036 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 1601351
🔄 Запрос #16037 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 126 спецификаций. Всего: 1601477
🔄 Запрос #16038 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 129 спецификаций. Всего: 1601606
🔄 Запрос #16039 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 129 спецификаций. Всего: 1601735
🔄 Запрос #16040 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 116 спецификаций. Всего: 1601851
🔄 Запрос #16041 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 1601963
🔄 Запрос #16042 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1602087
🔄 Запрос #16043 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1602206
🔄 Запрос #16044 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 110 спецификаций. Всего: 1602316
🔄 Запрос #16045 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1602423
🔄 Запрос #16046 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 1602534
🔄 Запрос #16047 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 1602634
🔄 Запрос #16048 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 1602743
🔄 Запрос #16049 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 101 спецификаций. Всего: 1602844
🔄 Запрос #16050 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 92 спецификаций. Всего: 1602936
🔄 Запрос #16051 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 50 спецификаций. Всего: 1602986
🔄 Запрос #16052 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 29 спецификаций. Всего: 1603015
🔄 Запрос #16053 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 60 спецификаций. Всего: 1603075
🔄 Запрос #16054 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 98 спецификаций. Всего: 1603173
🔄 Запрос #16055 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 1603273
🔄 Запрос #16056 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 1603379
🔄 Запрос #16057 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 1603487
🔄 Запрос #16058 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1603593
🔄 Запрос #16059 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 110 спецификаций. Всего: 1603703
🔄 Запрос #16060 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 82 спецификаций. Всего: 1603785
🔄 Запрос #16061 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 1 спецификаций. Всего: 1603786
🔄 Запрос #16062 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 33 спецификаций. Всего: 1603819
🔄 Запрос #16063 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 89 спецификаций. Всего: 1603908
🔄 Запрос #16064 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 1604014
🔄 Запрос #16065 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 1604105
🔄 Запрос #16066 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 81 спецификаций. Всего: 1604186
🔄 Запрос #16067 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 89 спецификаций. Всего: 1604275
🔄 Запрос #16068 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 99 спецификаций. Всего: 1604374
🔄 Запрос #16069 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 1604473
🔄 Запрос #16070 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 1604575
🔄 Запрос #16071 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1604682
🔄 Запрос #16072 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 117 спецификаций. Всего: 1604799
🔄 Запрос #16073 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 120 спецификаций. Всего: 1604919
🔄 Запрос #16074 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1605038
🔄 Запрос #16075 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 110 спецификаций. Всего: 1605148
🔄 Запрос #16076 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1605260
🔄 Запрос #16077 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 1605369
🔄 Запрос #16078 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 135 спецификаций. Всего: 1605504
🔄 Запрос #16079 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 58 спецификаций. Всего: 1605562
🔄 Запрос #16080 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 77 спецификаций. Всего: 1605639
🔄 Запрос #16081 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 144 спецификаций. Всего: 1605783
🔄 Запрос #16082 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 152 спецификаций. Всего: 1605935
🔄 Запрос #16083 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 1606060
🔄 Запрос #16084 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1606169
🔄 Запрос #16085 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1606283
🔄 Запрос #16086 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 1606408
🔄 Запрос #16087 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 129 спецификаций. Всего: 1606537
🔄 Запрос #16088 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 1606652
🔄 Запрос #16089 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 1606764
🔄 Запрос #16090 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 137 спецификаций. Всего: 1606901
🔄 Запрос #16091 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 150 спецификаций. Всего: 1607051
🔄 Запрос #16092 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 159 спецификаций. Всего: 1607210
🔄 Запрос #16093 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 148 спецификаций. Всего: 1607358
🔄 Запрос #16094 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 1607473
🔄 Запрос #16095 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 128 спецификаций. Всего: 1607601
🔄 Запрос #16096 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 1607719
🔄 Запрос #16097 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 151 спецификаций. Всего: 1607870
🔄 Запрос #16098 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 144 спецификаций. Всего: 1608014
🔄 Запрос #16099 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09

📥 Загружено 142 спецификаций. Всего: 1608156
🔄 Запрос #16100 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 147 спецификаций. Всего: 1608303
🔄 Запрос #16101 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 155 спецификаций. Всего: 1608458
📤 Сохранено 10096 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #16102 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 149 спецификаций. Всего: 1608607
🔄 Запрос #16103 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 139 спецификаций. Всего: 1608746
🔄 Запрос #16104 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1608873
🔄 Запрос #16105 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 1608991
🔄 Запрос #16106 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 1609103
🔄 Запрос #16107 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 1609226
🔄 Запрос #16108 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 115 спецификаций. Всего: 1609341
🔄 Запрос #16109 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 1609440
🔄 Запрос #16110 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 93 спецификаций. Всего: 1609533
🔄 Запрос #16111 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 1609642
🔄 Запрос #16112 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 1609753
🔄 Запрос #16113 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 126 спецификаций. Всего: 1609879
🔄 Запрос #16114 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 117 спецификаций. Всего: 1609996
🔄 Запрос #16115 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 1610108
🔄 Запрос #16116 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 1610217
🔄 Запрос #16117 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1610324
🔄 Запрос #16118 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1610420
🔄 Запрос #16119 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1610523
🔄 Запрос #16120 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 1610635
🔄 Запрос #16121 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 1610747
🔄 Запрос #16122 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 122 спецификаций. Всего: 1610869
🔄 Запрос #16123 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1610995
🔄 Запрос #16124 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 128 спецификаций. Всего: 1611123
🔄 Запрос #16125 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 136 спецификаций. Всего: 1611259
🔄 Запрос #16126 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 131 спецификаций. Всего: 1611390
🔄 Запрос #16127 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 137 спецификаций. Всего: 1611527
🔄 Запрос #16128 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 132 спецификаций. Всего: 1611659
🔄 Запрос #16129 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 1611784
🔄 Запрос #16130 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 3/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
Сервер недоступен. Ожидаем восстановления связи...
Проблема с запросом — повторяем диапазон.
Диапазон не завершен, повторяем через 30 секунд...
📅 Обрабатываем диапазон 2024-03-07 20:44:09 - 2024-03-14 20:44:09 (попытка 3/5)
🔄 Запрос #16131 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 124 спецификаций. Всего: 1611908
🔄 Запрос #16132 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 133 спецификаций. Всего: 1612041
🔄 Запрос #16133 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 106 спецификаций. Всего: 1612147
🔄 Запрос #16134 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 130 спецификаций. Всего: 1612277
🔄 Запрос #16135 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 120 спецификаций. Всего: 1612397
🔄 Запрос #16136 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 126 спецификаций. Всего: 1612523
🔄 Запрос #16137 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 1612635
🔄 Запрос #16138 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 1612753
🔄 Запрос #16139 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 1612867
🔄 Запрос #16140 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 1612992
🔄 Запрос #16141 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 122 спецификаций. Всего: 1613114
🔄 Запрос #16142 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 133 спецификаций. Всего: 1613247
🔄 Запрос #16143 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 124 спецификаций. Всего: 1613371
🔄 Запрос #16144 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 1613482
🔄 Запрос #16145 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 102 спецификаций. Всего: 1613584
🔄 Запрос #16146 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 136 спецификаций. Всего: 1613720
🔄 Запрос #16147 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1613839
🔄 Запрос #16148 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 147 спецификаций. Всего: 1613986
🔄 Запрос #16149 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1614089
🔄 Запрос #16150 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 1614197
🔄 Запрос #16151 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 1614305
🔄 Запрос #16152 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 79 спецификаций. Всего: 1614384
🔄 Запрос #16153 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 91 спецификаций. Всего: 1614475
🔄 Запрос #16154 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1614594
🔄 Запрос #16155 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 109 спецификаций. Всего: 1614703
🔄 Запрос #16156 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1614822
🔄 Запрос #16157 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 1614943
🔄 Запрос #16158 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 114 спецификаций. Всего: 1615057
🔄 Запрос #16159 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 120 спецификаций. Всего: 1615177
🔄 Запрос #16160 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 1615276
🔄 Запрос #16161 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 1615389
🔄 Запрос #16162 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 105 спецификаций. Всего: 1615494
🔄 Запрос #16163 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1615590
🔄 Запрос #16164 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09

📥 Загружено 96 спецификаций. Всего: 1615686
🔄 Запрос #16165 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 100 спецификаций. Всего: 1615786
🔄 Запрос #16166 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1615882
🔄 Запрос #16167 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 101 спецификаций. Всего: 1615983
🔄 Запрос #16168 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1616089
🔄 Запрос #16169 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 112 спецификаций. Всего: 1616201
🔄 Запрос #16170 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 107 спецификаций. Всего: 1616308
🔄 Запрос #16171 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 1616416
🔄 Запрос #16172 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 89 спецификаций. Всего: 1616505
🔄 Запрос #16173 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 100 спецификаций. Всего: 1616605
🔄 Запрос #16174 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 119 спецификаций. Всего: 1616724
🔄 Запрос #16175 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 118 спецификаций. Всего: 1616842
🔄 Запрос #16176 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 1616955
🔄 Запрос #16177 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 125 спецификаций. Всего: 1617080
🔄 Запрос #16178 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 1617191
🔄 Запрос #16179 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1617300
🔄 Запрос #16180 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 108 спецификаций. Всего: 1617408
🔄 Запрос #16181 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 96 спецификаций. Всего: 1617504
🔄 Запрос #16182 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 65 спецификаций. Всего: 1617569
🔄 Запрос #16183 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 40 спецификаций. Всего: 1617609
🔄 Запрос #16184 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 143 спецификаций. Всего: 1617752
🔄 Запрос #16185 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 159 спецификаций. Всего: 1617911
🔄 Запрос #16186 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 134 спецификаций. Всего: 1618045
🔄 Запрос #16187 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 148 спецификаций. Всего: 1618193
🔄 Запрос #16188 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 157 спецификаций. Всего: 1618350
🔄 Запрос #16189 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 129 спецификаций. Всего: 1618479
📤 Сохранено 10021 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #16190 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 1618602
🔄 Запрос #16191 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 113 спецификаций. Всего: 1618715
🔄 Запрос #16192 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 81 спецификаций. Всего: 1618796
🔄 Запрос #16193 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 145 спецификаций. Всего: 1618941
🔄 Запрос #16194 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 130 спецификаций. Всего: 1619071
🔄 Запрос #16195 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 103 спецификаций. Всего: 1619174
🔄 Запрос #16196 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 88 спецификаций. Всего: 1619262
🔄 Запрос #16197 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 77 спецификаций. Всего: 1619339
🔄 Запрос #16198 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 90 спецификаций. Всего: 1619429
🔄 Запрос #16199 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 130 спецификаций. Всего: 1619559
🔄 Запрос #16200 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 89 спецификаций. Всего: 1619648
🔄 Запрос #16201 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 111 спецификаций. Всего: 1619759
🔄 Запрос #16202 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 142 спецификаций. Всего: 1619901
🔄 Запрос #16203 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 140 спецификаций. Всего: 1620041
🔄 Запрос #16204 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 99 спецификаций. Всего: 1620140
🔄 Запрос #16205 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 122 спецификаций. Всего: 1620262
🔄 Запрос #16206 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 83 спецификаций. Всего: 1620345
🔄 Запрос #16207 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 121 спецификаций. Всего: 1620466
🔄 Запрос #16208 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 97 спецификаций. Всего: 1620563
🔄 Запрос #16209 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 75 спецификаций. Всего: 1620638
🔄 Запрос #16210 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 123 спецификаций. Всего: 1620761
🔄 Запрос #16211 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 139 спецификаций. Всего: 1620900
🔄 Запрос #16212 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 158 спецификаций. Всего: 1621058
🔄 Запрос #16213 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 122 спецификаций. Всего: 1621180
🔄 Запрос #16214 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 156 спецификаций. Всего: 1621336
🔄 Запрос #16215 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 166 спецификаций. Всего: 1621502
🔄 Запрос #16216 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 144 спецификаций. Всего: 1621646
🔄 Запрос #16217 для 2024-03-07 20:44:09 - 2024-03-14 20:44:09
📥 Загружено 85 спецификаций. Всего: 1621731
📅 Обрабатываем диапазон 2024-02-29 20:44:09 - 2024-03-07 20:44:09 (попытка 1/5)
🔄 Запрос #16218 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 153 спецификаций. Всего: 1621884
🔄 Запрос #16219 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 85 спецификаций. Всего: 1621969
🔄 Запрос #16220 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1622070
🔄 Запрос #16221 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 1622178
🔄 Запрос #16222 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 1622273
🔄 Запрос #16223 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 1622384
🔄 Запрос #16224 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 1622489
🔄 Запрос #16225 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 125 спецификаций. Всего: 1622614
🔄 Запрос #16226 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 125 спецификаций. Всего: 1622739
🔄 Запрос #16227 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 128 спецификаций. Всего: 1622867
🔄 Запрос #16228 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 1622977
🔄 Запрос #16229 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1623090
🔄 Запрос #16230 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1623191

🔄 Запрос #16231 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1623292
🔄 Запрос #16232 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 1623397
🔄 Запрос #16233 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 1623501
🔄 Запрос #16234 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 89 спецификаций. Всего: 1623590
🔄 Запрос #16235 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 73 спецификаций. Всего: 1623663
🔄 Запрос #16236 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1623777
🔄 Запрос #16237 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 1623881
🔄 Запрос #16238 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1623990
🔄 Запрос #16239 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 1624110
🔄 Запрос #16240 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 1624230
🔄 Запрос #16241 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 1624326
🔄 Запрос #16242 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 1624423
🔄 Запрос #16243 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 1624518
🔄 Запрос #16244 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 1624613
🔄 Запрос #16245 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1624727
🔄 Запрос #16246 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1624840
🔄 Запрос #16247 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 1624942
🔄 Запрос #16248 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 1625041
🔄 Запрос #16249 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 1625157
🔄 Запрос #16250 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1625271
🔄 Запрос #16251 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 1625374
🔄 Запрос #16252 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 1625473
🔄 Запрос #16253 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 1625577
🔄 Запрос #16254 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 1625670
🔄 Запрос #16255 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 1625789
🔄 Запрос #16256 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1625890
🔄 Запрос #16257 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 1625992
🔄 Запрос #16258 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 125 спецификаций. Всего: 1626117
🔄 Запрос #16259 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 1626239
🔄 Запрос #16260 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 1626362
🔄 Запрос #16261 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1626490
🔄 Запрос #16262 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 1626613
🔄 Запрос #16263 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 77 спецификаций. Всего: 1626690
🔄 Запрос #16264 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 84 спецификаций. Всего: 1626774
🔄 Запрос #16265 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1626887
🔄 Запрос #16266 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 1626990
🔄 Запрос #16267 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 158 спецификаций. Всего: 1627148
🔄 Запрос #16268 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 164 спецификаций. Всего: 1627312
🔄 Запрос #16269 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 143 спецификаций. Всего: 1627455
🔄 Запрос #16270 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 1627564
🔄 Запрос #16271 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 128 спецификаций. Всего: 1627692
🔄 Запрос #16272 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 1627797
🔄 Запрос #16273 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 127 спецификаций. Всего: 1627924
🔄 Запрос #16274 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 143 спецификаций. Всего: 1628067
🔄 Запрос #16275 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 145 спецификаций. Всего: 1628212
🔄 Запрос #16276 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 140 спецификаций. Всего: 1628352
🔄 Запрос #16277 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 149 спецификаций. Всего: 1628501
📤 Сохранено 10022 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #16278 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 141 спецификаций. Всего: 1628642
🔄 Запрос #16279 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 1628748
🔄 Запрос #16280 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 1628853
🔄 Запрос #16281 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1628967
🔄 Запрос #16282 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 1629082
🔄 Запрос #16283 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 1629205
🔄 Запрос #16284 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 132 спецификаций. Всего: 1629337
🔄 Запрос #16285 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 130 спецификаций. Всего: 1629467
🔄 Запрос #16286 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 1629590
🔄 Запрос #16287 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 126 спецификаций. Всего: 1629716
🔄 Запрос #16288 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 129 спецификаций. Всего: 1629845
🔄 Запрос #16289 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 134 спецификаций. Всего: 1629979
🔄 Запрос #16290 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1630090
🔄 Запрос #16291 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 1630211
🔄 Запрос #16292 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 151 спецификаций. Всего: 1630362
🔄 Запрос #16293 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 138 спецификаций. Всего: 1630500
🔄 Запрос #16294 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 1630595
🔄 Запрос #16295 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 92 спецификаций. Всего: 1630687
🔄 Запрос #16296 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 1630782
🔄 Запрос #16297 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 1630887
🔄 Запрос #16298 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 1630997
🔄 Запрос #16299 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 94 спецификаций. Всего: 1631091
🔄 Запрос #16300 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 1631209
🔄 Запрос #16301 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 109 спецификаций. Всего: 1631318
🔄 Запрос #16302 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 100 спецификаций. Всего: 1631418
🔄 Запрос #16303 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 1631523
🔄 Запрос #16304 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1631637
🔄 Запрос #16305 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 1631757
🔄 Запрос #16306 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 124 спецификаций. Всего: 1631881
🔄 Запрос #16307 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 1631986
🔄 Запрос #16308 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 1632085
🔄 Запрос #16309 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 88 спецификаций. Всего: 1632173
🔄 Запрос #16310 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 91 спецификаций. Всего: 1632264
🔄 Запрос #16311 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 86 спецификаций. Всего: 1632350
🔄 Запрос #16312 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 1632447
🔄 Запрос #16313 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 91 спецификаций. Всего: 1632538
🔄 Запрос #16314 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 87 спецификаций. Всего: 1632625
🔄 Запрос #16315 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 1632721
🔄 Запрос #16316 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 87 спецификаций. Всего: 1632808
🔄 Запрос #16317 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1632909
🔄 Запрос #16318 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 1633011
🔄 Запрос #16319 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 129 спецификаций. Всего: 1633140
🔄 Запрос #16320 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 1633244
🔄 Запрос #16321 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 1633363
🔄 Запрос #16322 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1633477
🔄 Запрос #16323 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 1633597
🔄 Запрос #16324 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 1633719
🔄 Запрос #16325 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 1633842
🔄 Запрос #16326 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 1633962
🔄 Запрос #16327 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 1634081
🔄 Запрос #16328 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 1634200
🔄 Запрос #16329 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1634314
🔄 Запрос #16330 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 1634430
🔄 Запрос #16331 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1634541
🔄 Запрос #16332 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 117 спецификаций. Всего: 1634658
🔄 Запрос #16333 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 1634774
🔄 Запрос #16334 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 111 спецификаций. Всего: 1634885
🔄 Запрос #16335 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 1634996
🔄 Запрос #16336 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1635110
🔄 Запрос #16337 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 1635206
🔄 Запрос #16338 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 1635301
🔄 Запрос #16339 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 1635398
🔄 Запрос #16340 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1635511
🔄 Запрос #16341 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 1635626
🔄 Запрос #16342 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 1635722
🔄 Запрос #16343 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1635823
🔄 Запрос #16344 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1635928
🔄 Запрос #16345 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 1636038
🔄 Запрос #16346 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 1636147
🔄 Запрос #16347 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1636257
🔄 Запрос #16348 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 127 спецификаций. Всего: 1636384
🔄 Запрос #16349 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 126 спецификаций. Всего: 1636510
🔄 Запрос #16350 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 1636621
🔄 Запрос #16351 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 1636728
🔄 Запрос #16352 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 1636818
🔄 Запрос #16353 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 1636920
🔄 Запрос #16354 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 1637030
🔄 Запрос #16355 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 1637138
🔄 Запрос #16356 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 100 спецификаций. Всего: 1637238
🔄 Запрос #16357 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 81 спецификаций. Всего: 1637319
🔄 Запрос #16358 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 79 спецификаций. Всего: 1637398
🔄 Запрос #16359 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 92 спецификаций. Всего: 1637490
🔄 Запрос #16360 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 126 спецификаций. Всего: 1637616
🔄 Запрос #16361 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 1637739
🔄 Запрос #16362 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 1637846
🔄 Запрос #16363 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 1637954
🔄 Запрос #16364 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 1638063
🔄 Запрос #16365 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 1638172
🔄 Запрос #16366 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 100 спецификаций. Всего: 1638272
🔄 Запрос #16367 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1638385
🔄 Запрос #16368 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 85 спецификаций. Всего: 1638470
🔄 Запрос #16369 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09

📥 Загружено 99 спецификаций. Всего: 1638569
📤 Сохранено 10068 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #16370 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 1638679
🔄 Запрос #16371 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 1638782
🔄 Запрос #16372 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 1638888
🔄 Запрос #16373 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1638994
🔄 Запрос #16374 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 1639103
🔄 Запрос #16375 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1639222
🔄 Запрос #16376 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 1639319
🔄 Запрос #16377 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 1639437
🔄 Запрос #16378 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 1639557
🔄 Запрос #16379 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 1639668
🔄 Запрос #16380 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 1639774
🔄 Запрос #16381 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 1639896
🔄 Запрос #16382 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 1640018
🔄 Запрос #16383 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1640119
🔄 Запрос #16384 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 125 спецификаций. Всего: 1640244
🔄 Запрос #16385 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1640356
🔄 Запрос #16386 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 1640473
🔄 Запрос #16387 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1640574
🔄 Запрос #16388 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 98 спецификаций. Всего: 1640672
🔄 Запрос #16389 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 1640782
🔄 Запрос #16390 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 98 спецификаций. Всего: 1640880
🔄 Запрос #16391 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 81 спецификаций. Всего: 1640961
🔄 Запрос #16392 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 1641054
🔄 Запрос #16393 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 90 спецификаций. Всего: 1641144
🔄 Запрос #16394 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 1641241
🔄 Запрос #16395 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1641342
🔄 Запрос #16396 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1641438
🔄 Запрос #16397 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1641539
🔄 Запрос #16398 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 1641634
🔄 Запрос #16399 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1641752
🔄 Запрос #16400 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 134 спецификаций. Всего: 1641886
🔄 Запрос #16401 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 1641992
🔄 Запрос #16402 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 1642111
🔄 Запрос #16403 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 1642218
🔄 Запрос #16404 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 1642339
🔄 Запрос #16405 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1642455
🔄 Запрос #16406 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 1642572
🔄 Запрос #16407 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 1642687
🔄 Запрос #16408 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1642800
🔄 Запрос #16409 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 1642916
🔄 Запрос #16410 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 94 спецификаций. Всего: 1643010
🔄 Запрос #16411 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 1643117
🔄 Запрос #16412 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1643231
🔄 Запрос #16413 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 1643340
🔄 Запрос #16414 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 1643447
🔄 Запрос #16415 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 1643551
🔄 Запрос #16416 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1643652
🔄 Запрос #16417 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 1643755
🔄 Запрос #16418 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 1643851
🔄 Запрос #16419 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 1643944
🔄 Запрос #16420 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 1644046
🔄 Запрос #16421 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 83 спецификаций. Всего: 1644129
🔄 Запрос #16422 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 1644225
🔄 Запрос #16423 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1644332
🔄 Запрос #16424 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 1644436
🔄 Запрос #16425 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 1644555
🔄 Запрос #16426 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 82 спецификаций. Всего: 1644637
🔄 Запрос #16427 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1644738
🔄 Запрос #16428 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 1644855
🔄 Запрос #16429 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 1644964
🔄 Запрос #16430 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 125 спецификаций. Всего: 1645089
🔄 Запрос #16431 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 135 спецификаций. Всего: 1645224
🔄 Запрос #16432 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 141 спецификаций. Всего: 1645365
🔄 Запрос #16433 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 1645486
🔄 Запрос #16434 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1645600

🔄 Запрос #16435 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 1645715
🔄 Запрос #16436 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 131 спецификаций. Всего: 1645846
🔄 Запрос #16437 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 1645969
🔄 Запрос #16438 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1646083
🔄 Запрос #16439 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 1646203
🔄 Запрос #16440 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 126 спецификаций. Всего: 1646329
🔄 Запрос #16441 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 1646422
🔄 Запрос #16442 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 91 спецификаций. Всего: 1646513
🔄 Запрос #16443 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 1646629
🔄 Запрос #16444 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 94 спецификаций. Всего: 1646723
🔄 Запрос #16445 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 1646831
🔄 Запрос #16446 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 1646940
🔄 Запрос #16447 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 133 спецификаций. Всего: 1647073
🔄 Запрос #16448 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 1647179
🔄 Запрос #16449 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1647301
🔄 Запрос #16450 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 139 спецификаций. Всего: 1647440
🔄 Запрос #16451 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 125 спецификаций. Всего: 1647565
🔄 Запрос #16452 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 130 спецификаций. Всего: 1647695
🔄 Запрос #16453 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 1647815
🔄 Запрос #16454 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 125 спецификаций. Всего: 1647940
🔄 Запрос #16455 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 126 спецификаций. Всего: 1648066
🔄 Запрос #16456 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 128 спецификаций. Всего: 1648194
🔄 Запрос #16457 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 1648314
🔄 Запрос #16458 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 1648431
🔄 Запрос #16459 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 138 спецификаций. Всего: 1648569
📤 Сохранено 10000 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #16460 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 1648692
🔄 Запрос #16461 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 131 спецификаций. Всего: 1648823
🔄 Запрос #16462 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 1648926
🔄 Запрос #16463 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 145 спецификаций. Всего: 1649071
🔄 Запрос #16464 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 1649191
🔄 Запрос #16465 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 153 спецификаций. Всего: 1649344
🔄 Запрос #16466 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 141 спецификаций. Всего: 1649485
🔄 Запрос #16467 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 155 спецификаций. Всего: 1649640
🔄 Запрос #16468 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 1649761
🔄 Запрос #16469 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 1649866
🔄 Запрос #16470 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 1649965
🔄 Запрос #16471 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 88 спецификаций. Всего: 1650053
🔄 Запрос #16472 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 59 спецификаций. Всего: 1650112
🔄 Запрос #16473 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 100 спецификаций. Всего: 1650212
🔄 Запрос #16474 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 92 спецификаций. Всего: 1650304
🔄 Запрос #16475 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 78 спецификаций. Всего: 1650382
🔄 Запрос #16476 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 68 спецификаций. Всего: 1650450
🔄 Запрос #16477 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 1650561
🔄 Запрос #16478 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 1650677
🔄 Запрос #16479 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 136 спецификаций. Всего: 1650813
🔄 Запрос #16480 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 1650935
🔄 Запрос #16481 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 140 спецификаций. Всего: 1651075
🔄 Запрос #16482 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 136 спецификаций. Всего: 1651211
🔄 Запрос #16483 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 130 спецификаций. Всего: 1651341
🔄 Запрос #16484 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 1651453
🔄 Запрос #16485 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 1651569
🔄 Запрос #16486 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 1651684
🔄 Запрос #16487 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1651798
🔄 Запрос #16488 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 1651920
🔄 Запрос #16489 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1652021
🔄 Запрос #16490 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 1652140
🔄 Запрос #16491 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 127 спецификаций. Всего: 1652267
🔄 Запрос #16492 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 136 спецификаций. Всего: 1652403
🔄 Запрос #16493 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 1652523
🔄 Запрос #16494 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 1652641
🔄 Запрос #16495 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 1652763
🔄 Запрос #16496 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1652876
🔄 Запрос #16497 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 1652992
🔄 Запрос #16498 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 1653112
🔄 Запрос #16499 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1653216
🔄 Запрос #16500 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 1653326
🔄 Запрос #16501 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 1653422
🔄 Запрос #16502 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 1653521
🔄 Запрос #16503 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 1653626
🔄 Запрос #16504 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 1653738
🔄 Запрос #16505 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 1653850

🔄 Запрос #16506 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 1653966
🔄 Запрос #16507 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 1654077
🔄 Запрос #16508 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 114 спецификаций. Всего: 1654191
🔄 Запрос #16509 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 1654294
🔄 Запрос #16510 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 86 спецификаций. Всего: 1654380
🔄 Запрос #16511 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 1654473
🔄 Запрос #16512 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 100 спецификаций. Всего: 1654573
🔄 Запрос #16513 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 1654679
🔄 Запрос #16514 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 1654781
🔄 Запрос #16515 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1654894
🔄 Запрос #16516 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 131 спецификаций. Всего: 1655025
🔄 Запрос #16517 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 1655137
🔄 Запрос #16518 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1655250
🔄 Запрос #16519 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 88 спецификаций. Всего: 1655338
🔄 Запрос #16520 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 76 спецификаций. Всего: 1655414
🔄 Запрос #16521 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 1655507
🔄 Запрос #16522 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 1655613
🔄 Запрос #16523 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 1655730
🔄 Запрос #16524 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 85 спецификаций. Всего: 1655815
🔄 Запрос #16525 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 91 спецификаций. Всего: 1655906
🔄 Запрос #16526 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 1656021
🔄 Запрос #16527 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 1656126
🔄 Запрос #16528 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 123 спецификаций. Всего: 1656249
🔄 Запрос #16529 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 137 спецификаций. Всего: 1656386
🔄 Запрос #16530 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1656508
🔄 Запрос #16531 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 118 спецификаций. Всего: 1656626
🔄 Запрос #16532 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 1656738
🔄 Запрос #16533 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 1656837
🔄 Запрос #16534 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 108 спецификаций. Всего: 1656945
🔄 Запрос #16535 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 1657055
🔄 Запрос #16536 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 124 спецификаций. Всего: 1657179
🔄 Запрос #16537 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1657298
🔄 Запрос #16538 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 1657401
🔄 Запрос #16539 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1657514
🔄 Запрос #16540 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 1657618
🔄 Запрос #16541 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 1657734
🔄 Запрос #16542 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1657847
🔄 Запрос #16543 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 1657958
🔄 Запрос #16544 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 1658075
🔄 Запрос #16545 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 1658186
🔄 Запрос #16546 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 98 спецификаций. Всего: 1658284
🔄 Запрос #16547 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 1658402
🔄 Запрос #16548 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 141 спецификаций. Всего: 1658543
🔄 Запрос #16549 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 132 спецификаций. Всего: 1658675
📤 Сохранено 10106 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #16550 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 145 спецификаций. Всего: 1658820
🔄 Запрос #16551 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 128 спецификаций. Всего: 1658948
🔄 Запрос #16552 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 127 спецификаций. Всего: 1659075
🔄 Запрос #16553 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 1659196
🔄 Запрос #16554 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 1659314
🔄 Запрос #16555 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 121 спецификаций. Всего: 1659435
🔄 Запрос #16556 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 1659531
🔄 Запрос #16557 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 110 спецификаций. Всего: 1659641
🔄 Запрос #16558 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 1659753
🔄 Запрос #16559 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1659854
🔄 Запрос #16560 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 1659969
🔄 Запрос #16561 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 1660068
🔄 Запрос #16562 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 119 спецификаций. Всего: 1660187
🔄 Запрос #16563 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 1660294
🔄 Запрос #16564 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1660388
🔄 Запрос #16565 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 1660484
🔄 Запрос #16566 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 77 спецификаций. Всего: 1660561
🔄 Запрос #16567 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 1660664
🔄 Запрос #16568 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 54 спецификаций. Всего: 1660718
🔄 Запрос #16569 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 76 спецификаций. Всего: 1660794
🔄 Запрос #16570 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 28 спецификаций. Всего: 1660822
🔄 Запрос #16571 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 49 спецификаций. Всего: 1660871
🔄 Запрос #16572 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 72 спецификаций. Всего: 1660943
🔄 Запрос #16573 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 65 спецификаций. Всего: 1661008
🔄 Запрос #16574 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 74 спецификаций. Всего: 1661082
🔄 Запрос #16575 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09

📥 Загружено 49 спецификаций. Всего: 1661131
🔄 Запрос #16576 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 92 спецификаций. Всего: 1661223
🔄 Запрос #16577 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 1661312
🔄 Запрос #16578 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 134 спецификаций. Всего: 1661446
🔄 Запрос #16579 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 150 спецификаций. Всего: 1661596
🔄 Запрос #16580 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 1661700
🔄 Запрос #16581 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 1661815
🔄 Запрос #16582 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 1661922
🔄 Запрос #16583 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 1662040
🔄 Запрос #16584 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 135 спецификаций. Всего: 1662175
🔄 Запрос #16585 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 1662271
🔄 Запрос #16586 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 42 спецификаций. Всего: 1662313
🔄 Запрос #16587 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 32 спецификаций. Всего: 1662345
🔄 Запрос #16588 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1662458
🔄 Запрос #16589 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 1662555
🔄 Запрос #16590 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 1662657
🔄 Запрос #16591 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 129 спецификаций. Всего: 1662786
🔄 Запрос #16592 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 138 спецификаций. Всего: 1662924
🔄 Запрос #16593 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 118 спецификаций. Всего: 1663042
🔄 Запрос #16594 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1663155
🔄 Запрос #16595 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 1663266
🔄 Запрос #16596 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 65 спецификаций. Всего: 1663331
🔄 Запрос #16597 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 77 спецификаций. Всего: 1663408
🔄 Запрос #16598 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 97 спецификаций. Всего: 1663505
🔄 Запрос #16599 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 1663614
🔄 Запрос #16600 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 102 спецификаций. Всего: 1663716
🔄 Запрос #16601 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 79 спецификаций. Всего: 1663795
🔄 Запрос #16602 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 85 спецификаций. Всего: 1663880
🔄 Запрос #16603 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 85 спецификаций. Всего: 1663965
🔄 Запрос #16604 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 85 спецификаций. Всего: 1664050
🔄 Запрос #16605 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1664151
🔄 Запрос #16606 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 1664254
🔄 Запрос #16607 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 90 спецификаций. Всего: 1664344
🔄 Запрос #16608 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 99 спецификаций. Всего: 1664443
🔄 Запрос #16609 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 1664549
🔄 Запрос #16610 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 36 спецификаций. Всего: 1664585
🔄 Запрос #16611 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 63 спецификаций. Всего: 1664648
🔄 Запрос #16612 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 1664751
🔄 Запрос #16613 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 100 спецификаций. Всего: 1664851
🔄 Запрос #16614 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 1664935
🔄 Запрос #16615 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 91 спецификаций. Всего: 1665026
🔄 Запрос #16616 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 81 спецификаций. Всего: 1665107
🔄 Запрос #16617 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 117 спецификаций. Всего: 1665224
🔄 Запрос #16618 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 122 спецификаций. Всего: 1665346
🔄 Запрос #16619 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 103 спецификаций. Всего: 1665449
🔄 Запрос #16620 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 115 спецификаций. Всего: 1665564
🔄 Запрос #16621 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 120 спецификаций. Всего: 1665684
🔄 Запрос #16622 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 100 спецификаций. Всего: 1665784
🔄 Запрос #16623 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 1665890
🔄 Запрос #16624 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 93 спецификаций. Всего: 1665983
🔄 Запрос #16625 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 96 спецификаций. Всего: 1666079
🔄 Запрос #16626 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 86 спецификаций. Всего: 1666165
🔄 Запрос #16627 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 81 спецификаций. Всего: 1666246
🔄 Запрос #16628 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 106 спецификаций. Всего: 1666352
🔄 Запрос #16629 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1666453
🔄 Запрос #16630 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 1666557
🔄 Запрос #16631 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 1666668
🔄 Запрос #16632 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 112 спецификаций. Всего: 1666780
🔄 Запрос #16633 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 111 спецификаций. Всего: 1666891
🔄 Запрос #16634 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 1666995
🔄 Запрос #16635 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 87 спецификаций. Всего: 1667082
🔄 Запрос #16636 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 71 спецификаций. Всего: 1667153
🔄 Запрос #16637 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 76 спецификаций. Всего: 1667229
🔄 Запрос #16638 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 85 спецификаций. Всего: 1667314
🔄 Запрос #16639 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 82 спецификаций. Всего: 1667396
🔄 Запрос #16640 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 91 спецификаций. Всего: 1667487
🔄 Запрос #16641 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 100 спецификаций. Всего: 1667587
🔄 Запрос #16642 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 116 спецификаций. Всего: 1667703
🔄 Запрос #16643 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 1667810
🔄 Запрос #16644 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 104 спецификаций. Всего: 1667914
🔄 Запрос #16645 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 1668009
🔄 Запрос #16646 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 95 спецификаций. Всего: 1668104
🔄 Запрос #16647 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 94 спецификаций. Всего: 1668198
🔄 Запрос #16648 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09

📥 Загружено 103 спецификаций. Всего: 1668301
🔄 Запрос #16649 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 107 спецификаций. Всего: 1668408
🔄 Запрос #16650 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 94 спецификаций. Всего: 1668502
🔄 Запрос #16651 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 113 спецификаций. Всего: 1668615
🔄 Запрос #16652 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 101 спецификаций. Всего: 1668716
📤 Сохранено 10041 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #16653 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 100 спецификаций. Всего: 1668816
🔄 Запрос #16654 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1668912
🔄 Запрос #16655 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 90 спецификаций. Всего: 1669002
🔄 Запрос #16656 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 86 спецификаций. Всего: 1669088
🔄 Запрос #16657 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 105 спецификаций. Всего: 1669193
🔄 Запрос #16658 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 109 спецификаций. Всего: 1669302
🔄 Запрос #16659 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 72 спецификаций. Всего: 1669374
🔄 Запрос #16660 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 67 спецификаций. Всего: 1669441
🔄 Запрос #16661 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 71 спецификаций. Всего: 1669512
🔄 Запрос #16662 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 41 спецификаций. Всего: 1669553
🔄 Запрос #16663 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 73 спецификаций. Всего: 1669626
🔄 Запрос #16664 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 58 спецификаций. Всего: 1669684
🔄 Запрос #16665 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 51 спецификаций. Всего: 1669735
🔄 Запрос #16666 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 74 спецификаций. Всего: 1669809
🔄 Запрос #16667 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 72 спецификаций. Всего: 1669881
🔄 Запрос #16668 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 68 спецификаций. Всего: 1669949
🔄 Запрос #16669 для 2024-02-29 20:44:09 - 2024-03-07 20:44:09
📥 Загружено 34 спецификаций. Всего: 1669983
📅 Обрабатываем диапазон 2024-02-22 20:44:09 - 2024-02-29 20:44:09 (попытка 1/5)
🔄 Запрос #16670 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 78 спецификаций. Всего: 1670061
🔄 Запрос #16671 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 113 спецификаций. Всего: 1670174
🔄 Запрос #16672 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1670260
🔄 Запрос #16673 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 87 спецификаций. Всего: 1670347
🔄 Запрос #16674 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 67 спецификаций. Всего: 1670414
🔄 Запрос #16675 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 78 спецификаций. Всего: 1670492
🔄 Запрос #16676 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1670583
🔄 Запрос #16677 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 60 спецификаций. Всего: 1670643
🔄 Запрос #16678 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1670716
🔄 Запрос #16679 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 116 спецификаций. Всего: 1670832
🔄 Запрос #16680 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 114 спецификаций. Всего: 1670946
🔄 Запрос #16681 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 117 спецификаций. Всего: 1671063
🔄 Запрос #16682 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1671181
🔄 Запрос #16683 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1671282
🔄 Запрос #16684 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 93 спецификаций. Всего: 1671375
🔄 Запрос #16685 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 99 спецификаций. Всего: 1671474
🔄 Запрос #16686 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 1671569
🔄 Запрос #16687 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 91 спецификаций. Всего: 1671660
🔄 Запрос #16688 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 90 спецификаций. Всего: 1671750
🔄 Запрос #16689 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 90 спецификаций. Всего: 1671840
🔄 Запрос #16690 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 1671924
🔄 Запрос #16691 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1672018
🔄 Запрос #16692 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 1672113
🔄 Запрос #16693 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 114 спецификаций. Всего: 1672227
🔄 Запрос #16694 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 84 спецификаций. Всего: 1672311
🔄 Запрос #16695 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 1672408
🔄 Запрос #16696 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 103 спецификаций. Всего: 1672511
🔄 Запрос #16697 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 99 спецификаций. Всего: 1672610
🔄 Запрос #16698 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 104 спецификаций. Всего: 1672714
🔄 Запрос #16699 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 96 спецификаций. Всего: 1672810
🔄 Запрос #16700 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 74 спецификаций. Всего: 1672884
🔄 Запрос #16701 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 105 спецификаций. Всего: 1672989
🔄 Запрос #16702 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 1673072
🔄 Запрос #16703 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 80 спецификаций. Всего: 1673152
🔄 Запрос #16704 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 92 спецификаций. Всего: 1673244
🔄 Запрос #16705 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 74 спецификаций. Всего: 1673318
🔄 Запрос #16706 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1673405
🔄 Запрос #16707 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1673488
🔄 Запрос #16708 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 64 спецификаций. Всего: 1673552
🔄 Запрос #16709 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 63 спецификаций. Всего: 1673615
🔄 Запрос #16710 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 73 спецификаций. Всего: 1673688
🔄 Запрос #16711 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 62 спецификаций. Всего: 1673750
🔄 Запрос #16712 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 80 спецификаций. Всего: 1673830
🔄 Запрос #16713 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 78 спецификаций. Всего: 1673908
🔄 Запрос #16714 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 93 спецификаций. Всего: 1674001
🔄 Запрос #16715 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09

📥 Загружено 98 спецификаций. Всего: 1674099
🔄 Запрос #16716 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 79 спецификаций. Всего: 1674178
🔄 Запрос #16717 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 82 спецификаций. Всего: 1674260
🔄 Запрос #16718 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 75 спецификаций. Всего: 1674335
🔄 Запрос #16719 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 76 спецификаций. Всего: 1674411
🔄 Запрос #16720 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 89 спецификаций. Всего: 1674500
🔄 Запрос #16721 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 88 спецификаций. Всего: 1674588
🔄 Запрос #16722 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 70 спецификаций. Всего: 1674658
🔄 Запрос #16723 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 81 спецификаций. Всего: 1674739
🔄 Запрос #16724 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 66 спецификаций. Всего: 1674805
🔄 Запрос #16725 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 89 спецификаций. Всего: 1674894
🔄 Запрос #16726 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 92 спецификаций. Всего: 1674986
🔄 Запрос #16727 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 89 спецификаций. Всего: 1675075
🔄 Запрос #16728 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 103 спецификаций. Всего: 1675178
🔄 Запрос #16729 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 91 спецификаций. Всего: 1675269
🔄 Запрос #16730 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 102 спецификаций. Всего: 1675371
🔄 Запрос #16731 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 91 спецификаций. Всего: 1675462
🔄 Запрос #16732 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 76 спецификаций. Всего: 1675538
🔄 Запрос #16733 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 64 спецификаций. Всего: 1675602
🔄 Запрос #16734 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 78 спецификаций. Всего: 1675680
🔄 Запрос #16735 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1675763
🔄 Запрос #16736 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 85 спецификаций. Всего: 1675848
🔄 Запрос #16737 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 85 спецификаций. Всего: 1675933
🔄 Запрос #16738 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 99 спецификаций. Всего: 1676032
🔄 Запрос #16739 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 102 спецификаций. Всего: 1676134
🔄 Запрос #16740 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 84 спецификаций. Всего: 1676218
🔄 Запрос #16741 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 76 спецификаций. Всего: 1676294
🔄 Запрос #16742 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 84 спецификаций. Всего: 1676378
🔄 Запрос #16743 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1676451
🔄 Запрос #16744 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1676537
🔄 Запрос #16745 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1676632
🔄 Запрос #16746 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 1676740
🔄 Запрос #16747 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 111 спецификаций. Всего: 1676851
🔄 Запрос #16748 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 1676951
🔄 Запрос #16749 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1677038
🔄 Запрос #16750 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 1677141
🔄 Запрос #16751 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 93 спецификаций. Всего: 1677234
🔄 Запрос #16752 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 88 спецификаций. Всего: 1677322
🔄 Запрос #16753 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1677405
🔄 Запрос #16754 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1677478
🔄 Запрос #16755 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1677561
🔄 Запрос #16756 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 67 спецификаций. Всего: 1677628
🔄 Запрос #16757 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 85 спецификаций. Всего: 1677713
🔄 Запрос #16758 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 1677820
🔄 Запрос #16759 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 122 спецификаций. Всего: 1677942
🔄 Запрос #16760 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 131 спецификаций. Всего: 1678073
🔄 Запрос #16761 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 160 спецификаций. Всего: 1678233
🔄 Запрос #16762 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 72 спецификаций. Всего: 1678305
🔄 Запрос #16763 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 72 спецификаций. Всего: 1678377
🔄 Запрос #16764 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 43 спецификаций. Всего: 1678420
🔄 Запрос #16765 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 26 спецификаций. Всего: 1678446
🔄 Запрос #16766 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 30 спецификаций. Всего: 1678476
🔄 Запрос #16767 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 35 спецификаций. Всего: 1678511
🔄 Запрос #16768 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 69 спецификаций. Всего: 1678580
🔄 Запрос #16769 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 50 спецификаций. Всего: 1678630
🔄 Запрос #16770 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 71 спецификаций. Всего: 1678701
🔄 Запрос #16771 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 135 спецификаций. Всего: 1678836
📤 Сохранено 10120 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #16772 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 1678943
🔄 Запрос #16773 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 1679041
🔄 Запрос #16774 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1679124
🔄 Запрос #16775 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 88 спецификаций. Всего: 1679212
🔄 Запрос #16776 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 93 спецификаций. Всего: 1679305
🔄 Запрос #16777 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 88 спецификаций. Всего: 1679393
🔄 Запрос #16778 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 109 спецификаций. Всего: 1679502
🔄 Запрос #16779 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1679589
🔄 Запрос #16780 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 89 спецификаций. Всего: 1679678
🔄 Запрос #16781 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 95 спецификаций. Всего: 1679773
🔄 Запрос #16782 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1679874
🔄 Запрос #16783 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 82 спецификаций. Всего: 1679956
🔄 Запрос #16784 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 85 спецификаций. Всего: 1680041
🔄 Запрос #16785 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 81 спецификаций. Всего: 1680122

🔄 Запрос #16786 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 105 спецификаций. Всего: 1680227
🔄 Запрос #16787 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 122 спецификаций. Всего: 1680349
🔄 Запрос #16788 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 1680444
🔄 Запрос #16789 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 88 спецификаций. Всего: 1680532
🔄 Запрос #16790 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 91 спецификаций. Всего: 1680623
🔄 Запрос #16791 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 104 спецификаций. Всего: 1680727
🔄 Запрос #16792 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 91 спецификаций. Всего: 1680818
🔄 Запрос #16793 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 88 спецификаций. Всего: 1680906
🔄 Запрос #16794 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1681000
🔄 Запрос #16795 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1681087
🔄 Запрос #16796 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1681173
🔄 Запрос #16797 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1681266
🔄 Запрос #16798 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1681352
🔄 Запрос #16799 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 1681452
🔄 Запрос #16800 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 88 спецификаций. Всего: 1681540
🔄 Запрос #16801 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 96 спецификаций. Всего: 1681636
🔄 Запрос #16802 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 99 спецификаций. Всего: 1681735
🔄 Запрос #16803 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 97 спецификаций. Всего: 1681832
🔄 Запрос #16804 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 1681930
🔄 Запрос #16805 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1682017
🔄 Запрос #16806 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 1682117
🔄 Запрос #16807 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1682211
🔄 Запрос #16808 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 105 спецификаций. Всего: 1682316
🔄 Запрос #16809 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 1682414
🔄 Запрос #16810 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 93 спецификаций. Всего: 1682507
🔄 Запрос #16811 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 85 спецификаций. Всего: 1682592
🔄 Запрос #16812 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1682693
🔄 Запрос #16813 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 81 спецификаций. Всего: 1682774
🔄 Запрос #16814 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1682861
🔄 Запрос #16815 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 72 спецификаций. Всего: 1682933
🔄 Запрос #16816 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 102 спецификаций. Всего: 1683035
🔄 Запрос #16817 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1683121
🔄 Запрос #16818 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 120 спецификаций. Всего: 1683241
🔄 Запрос #16819 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1683335
🔄 Запрос #16820 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 96 спецификаций. Всего: 1683431
🔄 Запрос #16821 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 1683526
🔄 Запрос #16822 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1683599
🔄 Запрос #16823 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 93 спецификаций. Всего: 1683692
🔄 Запрос #16824 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 1683789
🔄 Запрос #16825 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 1683886
🔄 Запрос #16826 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 92 спецификаций. Всего: 1683978
🔄 Запрос #16827 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 64 спецификаций. Всего: 1684042
🔄 Запрос #16828 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1684129
🔄 Запрос #16829 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 85 спецификаций. Всего: 1684214
🔄 Запрос #16830 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 103 спецификаций. Всего: 1684317
🔄 Запрос #16831 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 117 спецификаций. Всего: 1684434
🔄 Запрос #16832 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 114 спецификаций. Всего: 1684548
🔄 Запрос #16833 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 102 спецификаций. Всего: 1684650
🔄 Запрос #16834 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 81 спецификаций. Всего: 1684731
🔄 Запрос #16835 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 76 спецификаций. Всего: 1684807
🔄 Запрос #16836 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1684880
🔄 Запрос #16837 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 84 спецификаций. Всего: 1684964
🔄 Запрос #16838 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 75 спецификаций. Всего: 1685039
🔄 Запрос #16839 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 79 спецификаций. Всего: 1685118
🔄 Запрос #16840 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 138 спецификаций. Всего: 1685256
🔄 Запрос #16841 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 124 спецификаций. Всего: 1685380
🔄 Запрос #16842 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 146 спецификаций. Всего: 1685526
🔄 Запрос #16843 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1685627
🔄 Запрос #16844 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 78 спецификаций. Всего: 1685705
🔄 Запрос #16845 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 124 спецификаций. Всего: 1685829
🔄 Запрос #16846 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 132 спецификаций. Всего: 1685961
🔄 Запрос #16847 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 81 спецификаций. Всего: 1686042
🔄 Запрос #16848 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 55 спецификаций. Всего: 1686097
🔄 Запрос #16849 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 53 спецификаций. Всего: 1686150
🔄 Запрос #16850 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 68 спецификаций. Всего: 1686218
🔄 Запрос #16851 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 72 спецификаций. Всего: 1686290
🔄 Запрос #16852 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 47 спецификаций. Всего: 1686337
🔄 Запрос #16853 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 1686437
🔄 Запрос #16854 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1686520
🔄 Запрос #16855 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 76 спецификаций. Всего: 1686596
🔄 Запрос #16856 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 51 спецификаций. Всего: 1686647
🔄 Запрос #16857 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 54 спецификаций. Всего: 1686701
🔄 Запрос #16858 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1686802

🔄 Запрос #16859 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 126 спецификаций. Всего: 1686928
🔄 Запрос #16860 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 138 спецификаций. Всего: 1687066
🔄 Запрос #16861 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 129 спецификаций. Всего: 1687195
🔄 Запрос #16862 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 88 спецификаций. Всего: 1687283
🔄 Запрос #16863 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 91 спецификаций. Всего: 1687374
🔄 Запрос #16864 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 111 спецификаций. Всего: 1687485
🔄 Запрос #16865 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 1687588
🔄 Запрос #16866 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 116 спецификаций. Всего: 1687704
🔄 Запрос #16867 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 99 спецификаций. Всего: 1687803
🔄 Запрос #16868 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1687904
🔄 Запрос #16869 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 1688004
🔄 Запрос #16870 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 96 спецификаций. Всего: 1688100
🔄 Запрос #16871 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 99 спецификаций. Всего: 1688199
🔄 Запрос #16872 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1688282
🔄 Запрос #16873 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 67 спецификаций. Всего: 1688349
🔄 Запрос #16874 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 81 спецификаций. Всего: 1688430
🔄 Запрос #16875 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1688516
🔄 Запрос #16876 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 78 спецификаций. Всего: 1688594
🔄 Запрос #16877 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 99 спецификаций. Всего: 1688693
🔄 Запрос #16878 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1688794
🔄 Запрос #16879 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 117 спецификаций. Всего: 1688911
📤 Сохранено 10075 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #16880 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 1689019
🔄 Запрос #16881 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 110 спецификаций. Всего: 1689129
🔄 Запрос #16882 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1689243
🔄 Запрос #16883 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 1689338
🔄 Запрос #16884 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 106 спецификаций. Всего: 1689444
🔄 Запрос #16885 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 110 спецификаций. Всего: 1689554
🔄 Запрос #16886 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1689654
🔄 Запрос #16887 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 87 спецификаций. Всего: 1689741
🔄 Запрос #16888 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1689835
🔄 Запрос #16889 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 74 спецификаций. Всего: 1689909
🔄 Запрос #16890 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1689992
🔄 Запрос #16891 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1690078
🔄 Запрос #16892 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 90 спецификаций. Всего: 1690168
🔄 Запрос #16893 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 62 спецификаций. Всего: 1690230
🔄 Запрос #16894 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 60 спецификаций. Всего: 1690290
🔄 Запрос #16895 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 78 спецификаций. Всего: 1690368
🔄 Запрос #16896 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 1690465
🔄 Запрос #16897 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 72 спецификаций. Всего: 1690537
🔄 Запрос #16898 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 1690637
🔄 Запрос #16899 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 99 спецификаций. Всего: 1690736
🔄 Запрос #16900 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 131 спецификаций. Всего: 1690867
🔄 Запрос #16901 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 69 спецификаций. Всего: 1690936
🔄 Запрос #16902 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 85 спецификаций. Всего: 1691021
🔄 Запрос #16903 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1691108
🔄 Запрос #16904 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 1691205
🔄 Запрос #16905 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1691292
🔄 Запрос #16906 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1691402
🔄 Запрос #16907 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 106 спецификаций. Всего: 1691508
🔄 Запрос #16908 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 1691605
🔄 Запрос #16909 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1691692
🔄 Запрос #16910 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 1691799
🔄 Запрос #16911 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1691895
🔄 Запрос #16912 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 1691995
🔄 Запрос #16913 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 112 спецификаций. Всего: 1692107
🔄 Запрос #16914 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 1692207
🔄 Запрос #16915 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1692293
🔄 Запрос #16916 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 1692378
🔄 Запрос #16917 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1692464
🔄 Запрос #16918 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1692550
🔄 Запрос #16919 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 120 спецификаций. Всего: 1692670
🔄 Запрос #16920 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 118 спецификаций. Всего: 1692788
🔄 Запрос #16921 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 1692896
🔄 Запрос #16922 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 92 спецификаций. Всего: 1692988
🔄 Запрос #16923 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 84 спецификаций. Всего: 1693072
🔄 Запрос #16924 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 106 спецификаций. Всего: 1693178
🔄 Запрос #16925 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 102 спецификаций. Всего: 1693280
🔄 Запрос #16926 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09

📥 Загружено 93 спецификаций. Всего: 1693373
🔄 Запрос #16927 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1693467
🔄 Запрос #16928 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1693553
🔄 Запрос #16929 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1693647
🔄 Запрос #16930 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1693720
🔄 Запрос #16931 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 20 спецификаций. Всего: 1693740
🔄 Запрос #16932 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 122 спецификаций. Всего: 1693862
🔄 Запрос #16933 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 168 спецификаций. Всего: 1694030
🔄 Запрос #16934 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 134 спецификаций. Всего: 1694164
🔄 Запрос #16935 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 102 спецификаций. Всего: 1694266
🔄 Запрос #16936 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 69 спецификаций. Всего: 1694335
🔄 Запрос #16937 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 82 спецификаций. Всего: 1694417
🔄 Запрос #16938 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 70 спецификаций. Всего: 1694487
🔄 Запрос #16939 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 80 спецификаций. Всего: 1694567
🔄 Запрос #16940 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 74 спецификаций. Всего: 1694641
🔄 Запрос #16941 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 63 спецификаций. Всего: 1694704
🔄 Запрос #16942 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 71 спецификаций. Всего: 1694775
🔄 Запрос #16943 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1694886
🔄 Запрос #16944 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 123 спецификаций. Всего: 1695009
🔄 Запрос #16945 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 102 спецификаций. Всего: 1695111
🔄 Запрос #16946 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 89 спецификаций. Всего: 1695200
🔄 Запрос #16947 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 96 спецификаций. Всего: 1695296
🔄 Запрос #16948 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1695383
🔄 Запрос #16949 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 1695480
🔄 Запрос #16950 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1695594
🔄 Запрос #16951 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1695688
🔄 Запрос #16952 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 72 спецификаций. Всего: 1695760
🔄 Запрос #16953 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 1695868
🔄 Запрос #16954 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 1695963
🔄 Запрос #16955 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 1696070
🔄 Запрос #16956 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1696153
🔄 Запрос #16957 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 85 спецификаций. Всего: 1696238
🔄 Запрос #16958 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 110 спецификаций. Всего: 1696348
🔄 Запрос #16959 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1696446
🔄 Запрос #16960 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 106 спецификаций. Всего: 1696552
🔄 Запрос #16961 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1696646
🔄 Запрос #16962 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 93 спецификаций. Всего: 1696739
🔄 Запрос #16963 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 121 спецификаций. Всего: 1696860
🔄 Запрос #16964 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 144 спецификаций. Всего: 1697004
🔄 Запрос #16965 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 104 спецификаций. Всего: 1697108
🔄 Запрос #16966 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 128 спецификаций. Всего: 1697236
🔄 Запрос #16967 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 1697334
🔄 Запрос #16968 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 112 спецификаций. Всего: 1697446
🔄 Запрос #16969 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 105 спецификаций. Всего: 1697551
🔄 Запрос #16970 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1697645
🔄 Запрос #16971 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1697754
🔄 Запрос #16972 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 80 спецификаций. Всего: 1697834
🔄 Запрос #16973 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 76 спецификаций. Всего: 1697910
🔄 Запрос #16974 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 78 спецификаций. Всего: 1697988
🔄 Запрос #16975 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 82 спецификаций. Всего: 1698070
🔄 Запрос #16976 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 81 спецификаций. Всего: 1698151
🔄 Запрос #16977 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 80 спецификаций. Всего: 1698231
🔄 Запрос #16978 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 66 спецификаций. Всего: 1698297
🔄 Запрос #16979 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 79 спецификаций. Всего: 1698376
🔄 Запрос #16980 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1698449
🔄 Запрос #16981 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 62 спецификаций. Всего: 1698511
🔄 Запрос #16982 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 78 спецификаций. Всего: 1698589
🔄 Запрос #16983 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 98 спецификаций. Всего: 1698687
🔄 Запрос #16984 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 104 спецификаций. Всего: 1698791
🔄 Запрос #16985 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 109 спецификаций. Всего: 1698900
🔄 Запрос #16986 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1698994
📤 Сохранено 10083 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #16987 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1699088
🔄 Запрос #16988 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1699174
🔄 Запрос #16989 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 82 спецификаций. Всего: 1699256
🔄 Запрос #16990 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 87 спецификаций. Всего: 1699343
🔄 Запрос #16991 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1699430

🔄 Запрос #16992 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 81 спецификаций. Всего: 1699511
🔄 Запрос #16993 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1699584
🔄 Запрос #16994 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1699657
🔄 Запрос #16995 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 67 спецификаций. Всего: 1699724
🔄 Запрос #16996 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 67 спецификаций. Всего: 1699791
🔄 Запрос #16997 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 61 спецификаций. Всего: 1699852
🔄 Запрос #16998 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 1699949
🔄 Запрос #16999 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 117 спецификаций. Всего: 1700066
🔄 Запрос #17000 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 106 спецификаций. Всего: 1700172
🔄 Запрос #17001 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 113 спецификаций. Всего: 1700285
🔄 Запрос #17002 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 120 спецификаций. Всего: 1700405
🔄 Запрос #17003 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1700521
🔄 Запрос #17004 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 126 спецификаций. Всего: 1700647
🔄 Запрос #17005 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 1700754
🔄 Запрос #17006 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 116 спецификаций. Всего: 1700870
🔄 Запрос #17007 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1700956
🔄 Запрос #17008 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 104 спецификаций. Всего: 1701060
🔄 Запрос #17009 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1701147
🔄 Запрос #17010 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 149 спецификаций. Всего: 1701296
🔄 Запрос #17011 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 128 спецификаций. Всего: 1701424
🔄 Запрос #17012 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 93 спецификаций. Всего: 1701517
🔄 Запрос #17013 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 82 спецификаций. Всего: 1701599
🔄 Запрос #17014 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 77 спецификаций. Всего: 1701676
🔄 Запрос #17015 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1701759
🔄 Запрос #17016 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1701842
🔄 Запрос #17017 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1701915
🔄 Запрос #17018 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 126 спецификаций. Всего: 1702041
🔄 Запрос #17019 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 117 спецификаций. Всего: 1702158
🔄 Запрос #17020 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 117 спецификаций. Всего: 1702275
🔄 Запрос #17021 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 160 спецификаций. Всего: 1702435
🔄 Запрос #17022 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 182 спецификаций. Всего: 1702617
🔄 Запрос #17023 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 1702715
🔄 Запрос #17024 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 131 спецификаций. Всего: 1702846
🔄 Запрос #17025 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 1702941
🔄 Запрос #17026 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 1703048
🔄 Запрос #17027 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 145 спецификаций. Всего: 1703193
🔄 Запрос #17028 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 121 спецификаций. Всего: 1703314
🔄 Запрос #17029 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 93 спецификаций. Всего: 1703407
🔄 Запрос #17030 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 60 спецификаций. Всего: 1703467
🔄 Запрос #17031 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 72 спецификаций. Всего: 1703539
🔄 Запрос #17032 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 76 спецификаций. Всего: 1703615
🔄 Запрос #17033 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 72 спецификаций. Всего: 1703687
🔄 Запрос #17034 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 121 спецификаций. Всего: 1703808
🔄 Запрос #17035 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 148 спецификаций. Всего: 1703956
🔄 Запрос #17036 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 98 спецификаций. Всего: 1704054
🔄 Запрос #17037 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 56 спецификаций. Всего: 1704110
🔄 Запрос #17038 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 56 спецификаций. Всего: 1704166
🔄 Запрос #17039 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 36 спецификаций. Всего: 1704202
🔄 Запрос #17040 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1704296
🔄 Запрос #17041 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1704394
🔄 Запрос #17042 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 117 спецификаций. Всего: 1704511
🔄 Запрос #17043 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 1704606
🔄 Запрос #17044 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 130 спецификаций. Всего: 1704736
🔄 Запрос #17045 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 131 спецификаций. Всего: 1704867
🔄 Запрос #17046 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1704981
🔄 Запрос #17047 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 81 спецификаций. Всего: 1705062
🔄 Запрос #17048 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 75 спецификаций. Всего: 1705137
🔄 Запрос #17049 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 151 спецификаций. Всего: 1705288
🔄 Запрос #17050 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 139 спецификаций. Всего: 1705427
🔄 Запрос #17051 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 74 спецификаций. Всего: 1705501
🔄 Запрос #17052 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 83 спецификаций. Всего: 1705584
🔄 Запрос #17053 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 106 спецификаций. Всего: 1705690
🔄 Запрос #17054 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 92 спецификаций. Всего: 1705782
🔄 Запрос #17055 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 122 спецификаций. Всего: 1705904
🔄 Запрос #17056 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 110 спецификаций. Всего: 1706014
🔄 Запрос #17057 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 122 спецификаций. Всего: 1706136
🔄 Запрос #17058 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 1706244
🔄 Запрос #17059 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 105 спецификаций. Всего: 1706349
🔄 Запрос #17060 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 88 спецификаций. Всего: 1706437
🔄 Запрос #17061 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 68 спецификаций. Всего: 1706505

🔄 Запрос #17062 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 77 спецификаций. Всего: 1706582
🔄 Запрос #17063 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 103 спецификаций. Всего: 1706685
🔄 Запрос #17064 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 90 спецификаций. Всего: 1706775
🔄 Запрос #17065 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 84 спецификаций. Всего: 1706859
🔄 Запрос #17066 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 112 спецификаций. Всего: 1706971
🔄 Запрос #17067 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 75 спецификаций. Всего: 1707046
🔄 Запрос #17068 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 1707141
🔄 Запрос #17069 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 75 спецификаций. Всего: 1707216
🔄 Запрос #17070 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1707302
🔄 Запрос #17071 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 1707397
🔄 Запрос #17072 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 102 спецификаций. Всего: 1707499
🔄 Запрос #17073 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 1707599
🔄 Запрос #17074 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1707700
🔄 Запрос #17075 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 78 спецификаций. Всего: 1707778
🔄 Запрос #17076 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 102 спецификаций. Всего: 1707880
🔄 Запрос #17077 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1707981
🔄 Запрос #17078 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1708083
🔄 Запрос #17079 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 100 спецификаций. Всего: 1708183
🔄 Запрос #17080 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 95 спецификаций. Всего: 1708278
🔄 Запрос #17081 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 94 спецификаций. Всего: 1708372
🔄 Запрос #17082 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 1708480
🔄 Запрос #17083 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 1708588
🔄 Запрос #17084 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 89 спецификаций. Всего: 1708677
🔄 Запрос #17085 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 79 спецификаций. Всего: 1708756
🔄 Запрос #17086 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 86 спецификаций. Всего: 1708842
🔄 Запрос #17087 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 99 спецификаций. Всего: 1708941
🔄 Запрос #17088 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 75 спецификаций. Всего: 1709016
📤 Сохранено 10022 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #17089 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 66 спецификаций. Всего: 1709082
🔄 Запрос #17090 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 82 спецификаций. Всего: 1709164
🔄 Запрос #17091 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 66 спецификаций. Всего: 1709230
🔄 Запрос #17092 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 1709315
🔄 Запрос #17093 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 81 спецификаций. Всего: 1709396
🔄 Запрос #17094 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 97 спецификаций. Всего: 1709493
🔄 Запрос #17095 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 87 спецификаций. Всего: 1709580
🔄 Запрос #17096 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1709681
🔄 Запрос #17097 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 1709789
🔄 Запрос #17098 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1709890
🔄 Запрос #17099 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 89 спецификаций. Всего: 1709979
🔄 Запрос #17100 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 132 спецификаций. Всего: 1710111
🔄 Запрос #17101 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 107 спецификаций. Всего: 1710218
🔄 Запрос #17102 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 61 спецификаций. Всего: 1710279
🔄 Запрос #17103 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 42 спецификаций. Всего: 1710321
🔄 Запрос #17104 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 106 спецификаций. Всего: 1710427
🔄 Запрос #17105 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 41 спецификаций. Всего: 1710468
🔄 Запрос #17106 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 85 спецификаций. Всего: 1710553
🔄 Запрос #17107 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1710626
🔄 Запрос #17108 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 111 спецификаций. Всего: 1710737
🔄 Запрос #17109 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1710838
🔄 Запрос #17110 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 105 спецификаций. Всего: 1710943
🔄 Запрос #17111 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 126 спецификаций. Всего: 1711069
🔄 Запрос #17112 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 77 спецификаций. Всего: 1711146
🔄 Запрос #17113 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 108 спецификаций. Всего: 1711254
🔄 Запрос #17114 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 59 спецификаций. Всего: 1711313
🔄 Запрос #17115 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 73 спецификаций. Всего: 1711386
🔄 Запрос #17116 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 101 спецификаций. Всего: 1711487
🔄 Запрос #17117 для 2024-02-22 20:44:09 - 2024-02-29 20:44:09
📥 Загружено 44 спецификаций. Всего: 1711531
📅 Обрабатываем диапазон 2024-02-15 20:44:09 - 2024-02-22 20:44:09 (попытка 1/5)
🔄 Запрос #17118 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 94 спецификаций. Всего: 1711625
🔄 Запрос #17119 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 132 спецификаций. Всего: 1711757
🔄 Запрос #17120 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 134 спецификаций. Всего: 1711891
🔄 Запрос #17121 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 123 спецификаций. Всего: 1712014
🔄 Запрос #17122 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 1712125
🔄 Запрос #17123 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 134 спецификаций. Всего: 1712259
🔄 Запрос #17124 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 1712373
🔄 Запрос #17125 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1712498
🔄 Запрос #17126 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 127 спецификаций. Всего: 1712625
🔄 Запрос #17127 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09

📥 Загружено 113 спецификаций. Всего: 1712738
🔄 Запрос #17128 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 95 спецификаций. Всего: 1712833
🔄 Запрос #17129 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 1712944
🔄 Запрос #17130 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 104 спецификаций. Всего: 1713048
🔄 Запрос #17131 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 104 спецификаций. Всего: 1713152
🔄 Запрос #17132 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 1713257
🔄 Запрос #17133 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1713357
🔄 Запрос #17134 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 1713455
🔄 Запрос #17135 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1713562
🔄 Запрос #17136 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 130 спецификаций. Всего: 1713692
🔄 Запрос #17137 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 120 спецификаций. Всего: 1713812
🔄 Запрос #17138 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 1713945
🔄 Запрос #17139 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 127 спецификаций. Всего: 1714072
🔄 Запрос #17140 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 119 спецификаций. Всего: 1714191
🔄 Запрос #17141 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 125 спецификаций. Всего: 1714316
🔄 Запрос #17142 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 1714428
🔄 Запрос #17143 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 1714545
🔄 Запрос #17144 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 1714662
🔄 Запрос #17145 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 1714779
🔄 Запрос #17146 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 116 спецификаций. Всего: 1714895
🔄 Запрос #17147 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 124 спецификаций. Всего: 1715019
🔄 Запрос #17148 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 120 спецификаций. Всего: 1715139
🔄 Запрос #17149 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 121 спецификаций. Всего: 1715260
🔄 Запрос #17150 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 115 спецификаций. Всего: 1715375
🔄 Запрос #17151 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 92 спецификаций. Всего: 1715467
🔄 Запрос #17152 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 1715556
🔄 Запрос #17153 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 1715646
🔄 Запрос #17154 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 1715745
🔄 Запрос #17155 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 1715839
🔄 Запрос #17156 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 88 спецификаций. Всего: 1715927
🔄 Запрос #17157 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 70 спецификаций. Всего: 1715997
🔄 Запрос #17158 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 68 спецификаций. Всего: 1716065
🔄 Запрос #17159 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 74 спецификаций. Всего: 1716139
🔄 Запрос #17160 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 69 спецификаций. Всего: 1716208
🔄 Запрос #17161 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 1716302
🔄 Запрос #17162 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 1716410
🔄 Запрос #17163 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 95 спецификаций. Всего: 1716505
🔄 Запрос #17164 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 1716610
🔄 Запрос #17165 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 121 спецификаций. Всего: 1716731
🔄 Запрос #17166 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 1716845
🔄 Запрос #17167 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1716952
🔄 Запрос #17168 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 1717051
🔄 Запрос #17169 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 115 спецификаций. Всего: 1717166
🔄 Запрос #17170 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 1717278
🔄 Запрос #17171 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 1717377
🔄 Запрос #17172 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 101 спецификаций. Всего: 1717478
🔄 Запрос #17173 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 97 спецификаций. Всего: 1717575
🔄 Запрос #17174 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 1717673
🔄 Запрос #17175 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 100 спецификаций. Всего: 1717773
🔄 Запрос #17176 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 97 спецификаций. Всего: 1717870
🔄 Запрос #17177 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 1717980
🔄 Запрос #17178 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1718087
🔄 Запрос #17179 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 96 спецификаций. Всего: 1718183
🔄 Запрос #17180 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 1718295
🔄 Запрос #17181 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 123 спецификаций. Всего: 1718418
🔄 Запрос #17182 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 1718523
🔄 Запрос #17183 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 109 спецификаций. Всего: 1718632
🔄 Запрос #17184 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1718716
🔄 Запрос #17185 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 1718819
🔄 Запрос #17186 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 91 спецификаций. Всего: 1718910
🔄 Запрос #17187 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 89 спецификаций. Всего: 1718999
🔄 Запрос #17188 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1719109
📤 Сохранено 10093 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #17189 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1719216
🔄 Запрос #17190 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 1719326
🔄 Запрос #17191 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 119 спецификаций. Всего: 1719445
🔄 Запрос #17192 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09

📥 Загружено 81 спецификаций. Всего: 1719526
🔄 Запрос #17193 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 82 спецификаций. Всего: 1719608
🔄 Запрос #17194 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 67 спецификаций. Всего: 1719675
🔄 Запрос #17195 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 54 спецификаций. Всего: 1719729
🔄 Запрос #17196 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 46 спецификаций. Всего: 1719775
🔄 Запрос #17197 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 92 спецификаций. Всего: 1719867
🔄 Запрос #17198 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1719976
🔄 Запрос #17199 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 139 спецификаций. Всего: 1720115
🔄 Запрос #17200 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 1720225
🔄 Запрос #17201 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 125 спецификаций. Всего: 1720350
🔄 Запрос #17202 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 122 спецификаций. Всего: 1720472
🔄 Запрос #17203 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 1720583
🔄 Запрос #17204 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 101 спецификаций. Всего: 1720684
🔄 Запрос #17205 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 100 спецификаций. Всего: 1720784
🔄 Запрос #17206 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 119 спецификаций. Всего: 1720903
🔄 Запрос #17207 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 118 спецификаций. Всего: 1721021
🔄 Запрос #17208 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 1721131
🔄 Запрос #17209 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1721232
🔄 Запрос #17210 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 96 спецификаций. Всего: 1721328
🔄 Запрос #17211 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 89 спецификаций. Всего: 1721417
🔄 Запрос #17212 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 1721529
🔄 Запрос #17213 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 1721639
🔄 Запрос #17214 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 1721747
🔄 Запрос #17215 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1721831
🔄 Запрос #17216 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 92 спецификаций. Всего: 1721923
🔄 Запрос #17217 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 95 спецификаций. Всего: 1722018
🔄 Запрос #17218 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 81 спецификаций. Всего: 1722099
🔄 Запрос #17219 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 87 спецификаций. Всего: 1722186
🔄 Запрос #17220 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 90 спецификаций. Всего: 1722276
🔄 Запрос #17221 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 78 спецификаций. Всего: 1722354
🔄 Запрос #17222 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 88 спецификаций. Всего: 1722442
🔄 Запрос #17223 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 97 спецификаций. Всего: 1722539
🔄 Запрос #17224 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 1722633
🔄 Запрос #17225 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 1722731
🔄 Запрос #17226 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 92 спецификаций. Всего: 1722823
🔄 Запрос #17227 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 96 спецификаций. Всего: 1722919
🔄 Запрос #17228 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1723032
🔄 Запрос #17229 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 115 спецификаций. Всего: 1723147
🔄 Запрос #17230 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 1723246
🔄 Запрос #17231 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 77 спецификаций. Всего: 1723323
🔄 Запрос #17232 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 1723426
🔄 Запрос #17233 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 121 спецификаций. Всего: 1723547
🔄 Запрос #17234 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 1723645
🔄 Запрос #17235 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 74 спецификаций. Всего: 1723719
🔄 Запрос #17236 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1723803
🔄 Запрос #17237 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 55 спецификаций. Всего: 1723858
🔄 Запрос #17238 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1723942
🔄 Запрос #17239 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 102 спецификаций. Всего: 1724044
🔄 Запрос #17240 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 95 спецификаций. Всего: 1724139
🔄 Запрос #17241 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 80 спецификаций. Всего: 1724219
🔄 Запрос #17242 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 1724327
🔄 Запрос #17243 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 115 спецификаций. Всего: 1724442
🔄 Запрос #17244 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 90 спецификаций. Всего: 1724532
🔄 Запрос #17245 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 100 спецификаций. Всего: 1724632
🔄 Запрос #17246 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1724739
🔄 Запрос #17247 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 1724853
🔄 Запрос #17248 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 88 спецификаций. Всего: 1724941
🔄 Запрос #17249 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 88 спецификаций. Всего: 1725029
🔄 Запрос #17250 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 87 спецификаций. Всего: 1725116
🔄 Запрос #17251 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 101 спецификаций. Всего: 1725217
🔄 Запрос #17252 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1725305
🔄 Запрос #17253 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 66 спецификаций. Всего: 1725371
🔄 Запрос #17254 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1725459
🔄 Запрос #17255 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 1725570
🔄 Запрос #17256 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1725654
🔄 Запрос #17257 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 73 спецификаций. Всего: 1725727
🔄 Запрос #17258 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 89 спецификаций. Всего: 1725816
🔄 Запрос #17259 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 88 спецификаций. Всего: 1725904
🔄 Запрос #17260 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 87 спецификаций. Всего: 1725991
🔄 Запрос #17261 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 1726102
🔄 Запрос #17262 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 1726208
🔄 Запрос #17263 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 1726316
🔄 Запрос #17264 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 1726430
🔄 Запрос #17265 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 1726541
🔄 Запрос #17266 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 124 спецификаций. Всего: 1726665
🔄 Запрос #17267 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 119 спецификаций. Всего: 1726784
🔄 Запрос #17268 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 1726894
🔄 Запрос #17269 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1726978
🔄 Запрос #17270 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 88 спецификаций. Всего: 1727066
🔄 Запрос #17271 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 97 спецификаций. Всего: 1727163
🔄 Запрос #17272 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 81 спецификаций. Всего: 1727244
🔄 Запрос #17273 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 100 спецификаций. Всего: 1727344
🔄 Запрос #17274 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 59 спецификаций. Всего: 1727403
🔄 Запрос #17275 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 88 спецификаций. Всего: 1727491
🔄 Запрос #17276 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 78 спецификаций. Всего: 1727569
🔄 Запрос #17277 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1727653
🔄 Запрос #17278 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1727737
🔄 Запрос #17279 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 81 спецификаций. Всего: 1727818
🔄 Запрос #17280 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 75 спецификаций. Всего: 1727893
🔄 Запрос #17281 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 1727999
🔄 Запрос #17282 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 109 спецификаций. Всего: 1728108
🔄 Запрос #17283 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 137 спецификаций. Всего: 1728245
🔄 Запрос #17284 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 96 спецификаций. Всего: 1728341
🔄 Запрос #17285 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 1728449
🔄 Запрос #17286 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 126 спецификаций. Всего: 1728575
🔄 Запрос #17287 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 140 спецификаций. Всего: 1728715
🔄 Запрос #17288 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 1728827
🔄 Запрос #17289 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 73 спецификаций. Всего: 1728900
🔄 Запрос #17290 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 83 спецификаций. Всего: 1728983
🔄 Запрос #17291 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 97 спецификаций. Всего: 1729080
🔄 Запрос #17292 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 100 спецификаций. Всего: 1729180
📤 Сохранено 10071 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #17293 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1729284
🔄 Запрос #17294 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 1729401
🔄 Запрос #17295 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 1729509
🔄 Запрос #17296 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 102 спецификаций. Всего: 1729611
🔄 Запрос #17297 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 113 спецификаций. Всего: 1729724
🔄 Запрос #17298 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 1729836
🔄 Запрос #17299 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 123 спецификаций. Всего: 1729959
🔄 Запрос #17300 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 122 спецификаций. Всего: 1730081
🔄 Запрос #17301 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 129 спецификаций. Всего: 1730210
🔄 Запрос #17302 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 102 спецификаций. Всего: 1730312
🔄 Запрос #17303 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 80 спецификаций. Всего: 1730392
🔄 Запрос #17304 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 91 спецификаций. Всего: 1730483
🔄 Запрос #17305 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 92 спецификаций. Всего: 1730575
🔄 Запрос #17306 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 124 спецификаций. Всего: 1730699
🔄 Запрос #17307 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 1730811
🔄 Запрос #17308 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 1730921
🔄 Запрос #17309 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1731023
🔄 Запрос #17310 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 91 спецификаций. Всего: 1731114
🔄 Запрос #17311 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 86 спецификаций. Всего: 1731200
🔄 Запрос #17312 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 87 спецификаций. Всего: 1731287
🔄 Запрос #17313 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 83 спецификаций. Всего: 1731370
🔄 Запрос #17314 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1731454
🔄 Запрос #17315 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 77 спецификаций. Всего: 1731531
🔄 Запрос #17316 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1731615
🔄 Запрос #17317 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 82 спецификаций. Всего: 1731697
🔄 Запрос #17318 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 83 спецификаций. Всего: 1731780
🔄 Запрос #17319 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 72 спецификаций. Всего: 1731852
🔄 Запрос #17320 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 1731946
🔄 Запрос #17321 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 120 спецификаций. Всего: 1732066
🔄 Запрос #17322 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 127 спецификаций. Всего: 1732193
🔄 Запрос #17323 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 120 спецификаций. Всего: 1732313
🔄 Запрос #17324 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 1732424
🔄 Запрос #17325 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 123 спецификаций. Всего: 1732547
🔄 Запрос #17326 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 118 спецификаций. Всего: 1732665
🔄 Запрос #17327 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 104 спецификаций. Всего: 1732769
🔄 Запрос #17328 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 1732883
🔄 Запрос #17329 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 1732997
🔄 Запрос #17330 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 126 спецификаций. Всего: 1733123

🔄 Запрос #17331 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 1733221
🔄 Запрос #17332 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 86 спецификаций. Всего: 1733307
🔄 Запрос #17333 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1733429
🔄 Запрос #17334 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 1733534
🔄 Запрос #17335 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 97 спецификаций. Всего: 1733631
🔄 Запрос #17336 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 102 спецификаций. Всего: 1733733
🔄 Запрос #17337 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 1733841
🔄 Запрос #17338 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1733948
🔄 Запрос #17339 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 1734046
🔄 Запрос #17340 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1734153
🔄 Запрос #17341 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1734260
🔄 Запрос #17342 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 1734363
🔄 Запрос #17343 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1734470
🔄 Запрос #17344 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1734577
🔄 Запрос #17345 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 1734691
🔄 Запрос #17346 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 109 спецификаций. Всего: 1734800
🔄 Запрос #17347 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 120 спецификаций. Всего: 1734920
🔄 Запрос #17348 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 1735031
🔄 Запрос #17349 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 95 спецификаций. Всего: 1735126
🔄 Запрос #17350 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 78 спецификаций. Всего: 1735204
🔄 Запрос #17351 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 113 спецификаций. Всего: 1735317
🔄 Запрос #17352 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 97 спецификаций. Всего: 1735414
🔄 Запрос #17353 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 1735519
🔄 Запрос #17354 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 88 спецификаций. Всего: 1735607
🔄 Запрос #17355 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 125 спецификаций. Всего: 1735732
🔄 Запрос #17356 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 128 спецификаций. Всего: 1735860
🔄 Запрос #17357 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 127 спецификаций. Всего: 1735987
🔄 Запрос #17358 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 109 спецификаций. Всего: 1736096
🔄 Запрос #17359 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 75 спецификаций. Всего: 1736171
🔄 Запрос #17360 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1736255
🔄 Запрос #17361 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 78 спецификаций. Всего: 1736333
🔄 Запрос #17362 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1736417
🔄 Запрос #17363 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 86 спецификаций. Всего: 1736503
🔄 Запрос #17364 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 56 спецификаций. Всего: 1736559
🔄 Запрос #17365 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 1736657
🔄 Запрос #17366 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 109 спецификаций. Всего: 1736766
🔄 Запрос #17367 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 1736878
🔄 Запрос #17368 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 90 спецификаций. Всего: 1736968
🔄 Запрос #17369 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 101 спецификаций. Всего: 1737069
🔄 Запрос #17370 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 1737181
🔄 Запрос #17371 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 124 спецификаций. Всего: 1737305
🔄 Запрос #17372 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 113 спецификаций. Всего: 1737418
🔄 Запрос #17373 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 113 спецификаций. Всего: 1737531
🔄 Запрос #17374 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 113 спецификаций. Всего: 1737644
🔄 Запрос #17375 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 126 спецификаций. Всего: 1737770
🔄 Запрос #17376 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 1737891
🔄 Запрос #17377 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 122 спецификаций. Всего: 1738013
🔄 Запрос #17378 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 101 спецификаций. Всего: 1738114
🔄 Запрос #17379 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 1738228
🔄 Запрос #17380 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 109 спецификаций. Всего: 1738337
🔄 Запрос #17381 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 71 спецификаций. Всего: 1738408
🔄 Запрос #17382 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 95 спецификаций. Всего: 1738503
🔄 Запрос #17383 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 136 спецификаций. Всего: 1738639
🔄 Запрос #17384 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 1738738
🔄 Запрос #17385 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 1738841
🔄 Запрос #17386 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 82 спецификаций. Всего: 1738923
🔄 Запрос #17387 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1739021
🔄 Запрос #17388 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 97 спецификаций. Всего: 1739118
🔄 Запрос #17389 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 89 спецификаций. Всего: 1739207
📤 Сохранено 10027 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #17390 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 82 спецификаций. Всего: 1739289
🔄 Запрос #17391 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 77 спецификаций. Всего: 1739366
🔄 Запрос #17392 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 87 спецификаций. Всего: 1739453
🔄 Запрос #17393 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 91 спецификаций. Всего: 1739544
🔄 Запрос #17394 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 78 спецификаций. Всего: 1739622
🔄 Запрос #17395 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 87 спецификаций. Всего: 1739709
🔄 Запрос #17396 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 76 спецификаций. Всего: 1739785
🔄 Запрос #17397 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 63 спецификаций. Всего: 1739848
🔄 Запрос #17398 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 71 спецификаций. Всего: 1739919
🔄 Запрос #17399 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 87 спецификаций. Всего: 1740006
🔄 Запрос #17400 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 80 спецификаций. Всего: 1740086
🔄 Запрос #17401 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09

📥 Загружено 84 спецификаций. Всего: 1740170
🔄 Запрос #17402 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 90 спецификаций. Всего: 1740260
🔄 Запрос #17403 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 78 спецификаций. Всего: 1740338
🔄 Запрос #17404 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 82 спецификаций. Всего: 1740420
🔄 Запрос #17405 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 67 спецификаций. Всего: 1740487
🔄 Запрос #17406 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 81 спецификаций. Всего: 1740568
🔄 Запрос #17407 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 92 спецификаций. Всего: 1740660
🔄 Запрос #17408 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1740744
🔄 Запрос #17409 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1740853
🔄 Запрос #17410 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 84 спецификаций. Всего: 1740937
🔄 Запрос #17411 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 73 спецификаций. Всего: 1741010
🔄 Запрос #17412 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 92 спецификаций. Всего: 1741102
🔄 Запрос #17413 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 1741196
🔄 Запрос #17414 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 1741290
🔄 Запрос #17415 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 95 спецификаций. Всего: 1741385
🔄 Запрос #17416 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 1741479
🔄 Запрос #17417 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 87 спецификаций. Всего: 1741566
🔄 Запрос #17418 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 92 спецификаций. Всего: 1741658
🔄 Запрос #17419 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 85 спецификаций. Всего: 1741743
🔄 Запрос #17420 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 70 спецификаций. Всего: 1741813
🔄 Запрос #17421 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 79 спецификаций. Всего: 1741892
🔄 Запрос #17422 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 80 спецификаций. Всего: 1741972
🔄 Запрос #17423 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 1742080
🔄 Запрос #17424 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1742187
🔄 Запрос #17425 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 114 спецификаций. Всего: 1742301
🔄 Запрос #17426 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1742418
🔄 Запрос #17427 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 113 спецификаций. Всего: 1742531
🔄 Запрос #17428 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 1742639
🔄 Запрос #17429 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 1742742
🔄 Запрос #17430 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 80 спецификаций. Всего: 1742822
🔄 Запрос #17431 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 1742916
🔄 Запрос #17432 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 1743024
🔄 Запрос #17433 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 1743134
🔄 Запрос #17434 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 65 спецификаций. Всего: 1743199
🔄 Запрос #17435 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 50 спецификаций. Всего: 1743249
🔄 Запрос #17436 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 71 спецификаций. Всего: 1743320
🔄 Запрос #17437 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 1743437
🔄 Запрос #17438 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 120 спецификаций. Всего: 1743557
🔄 Запрос #17439 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 1743655
🔄 Запрос #17440 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 135 спецификаций. Всего: 1743790
🔄 Запрос #17441 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 1743889
🔄 Запрос #17442 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 1744006
🔄 Запрос #17443 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 138 спецификаций. Всего: 1744144
🔄 Запрос #17444 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 63 спецификаций. Всего: 1744207
🔄 Запрос #17445 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 57 спецификаций. Всего: 1744264
🔄 Запрос #17446 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 79 спецификаций. Всего: 1744343
🔄 Запрос #17447 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 88 спецификаций. Всего: 1744431
🔄 Запрос #17448 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1744532
🔄 Запрос #17449 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 156 спецификаций. Всего: 1744688
🔄 Запрос #17450 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 78 спецификаций. Всего: 1744766
🔄 Запрос #17451 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 76 спецификаций. Всего: 1744842
🔄 Запрос #17452 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 1744945
🔄 Запрос #17453 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 119 спецификаций. Всего: 1745064
🔄 Запрос #17454 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 127 спецификаций. Всего: 1745191
🔄 Запрос #17455 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 101 спецификаций. Всего: 1745292
🔄 Запрос #17456 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1745394
🔄 Запрос #17457 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 77 спецификаций. Всего: 1745471
🔄 Запрос #17458 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 60 спецификаций. Всего: 1745531
🔄 Запрос #17459 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1745638
🔄 Запрос #17460 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 1745758
🔄 Запрос #17461 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 120 спецификаций. Всего: 1745878
🔄 Запрос #17462 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 1745981
🔄 Запрос #17463 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1746106
🔄 Запрос #17464 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1746197
🔄 Запрос #17465 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 1746302
🔄 Запрос #17466 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 1746405

🔄 Запрос #17467 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 1746515
🔄 Запрос #17468 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 95 спецификаций. Всего: 1746610
🔄 Запрос #17469 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 121 спецификаций. Всего: 1746731
🔄 Запрос #17470 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 130 спецификаций. Всего: 1746861
🔄 Запрос #17471 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1746987
🔄 Запрос #17472 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 131 спецификаций. Всего: 1747118
🔄 Запрос #17473 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 124 спецификаций. Всего: 1747242
🔄 Запрос #17474 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 139 спецификаций. Всего: 1747381
🔄 Запрос #17475 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 112 спецификаций. Всего: 1747493
🔄 Запрос #17476 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1747604
🔄 Запрос #17477 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 125 спецификаций. Всего: 1747729
🔄 Запрос #17478 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 119 спецификаций. Всего: 1747848
🔄 Запрос #17479 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 115 спецификаций. Всего: 1747963
🔄 Запрос #17480 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 128 спецификаций. Всего: 1748091
🔄 Запрос #17481 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 113 спецификаций. Всего: 1748204
🔄 Запрос #17482 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 103 спецификаций. Всего: 1748307
🔄 Запрос #17483 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 117 спецификаций. Всего: 1748424
🔄 Запрос #17484 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 1748535
🔄 Запрос #17485 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 111 спецификаций. Всего: 1748646
🔄 Запрос #17486 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1748758
🔄 Запрос #17487 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 1748856
🔄 Запрос #17488 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 109 спецификаций. Всего: 1748965
🔄 Запрос #17489 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 113 спецификаций. Всего: 1749078
🔄 Запрос #17490 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1749185
🔄 Запрос #17491 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1749292
📤 Сохранено 10085 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #17492 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 100 спецификаций. Всего: 1749392
🔄 Запрос #17493 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 1749491
🔄 Запрос #17494 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 94 спецификаций. Всего: 1749585
🔄 Запрос #17495 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 1749688
🔄 Запрос #17496 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 80 спецификаций. Всего: 1749768
🔄 Запрос #17497 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 83 спецификаций. Всего: 1749851
🔄 Запрос #17498 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 1749940
🔄 Запрос #17499 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 72 спецификаций. Всего: 1750012
🔄 Запрос #17500 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 71 спецификаций. Всего: 1750083
🔄 Запрос #17501 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 91 спецификаций. Всего: 1750174
🔄 Запрос #17502 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 1750273
🔄 Запрос #17503 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 109 спецификаций. Всего: 1750382
🔄 Запрос #17504 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1750473
🔄 Запрос #17505 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 97 спецификаций. Всего: 1750570
🔄 Запрос #17506 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 1750680
🔄 Запрос #17507 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 96 спецификаций. Всего: 1750776
🔄 Запрос #17508 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 90 спецификаций. Всего: 1750866
🔄 Запрос #17509 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1750973
🔄 Запрос #17510 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 1751078
🔄 Запрос #17511 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 1751177
🔄 Запрос #17512 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 102 спецификаций. Всего: 1751279
🔄 Запрос #17513 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 77 спецификаций. Всего: 1751356
🔄 Запрос #17514 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 91 спецификаций. Всего: 1751447
🔄 Запрос #17515 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 105 спецификаций. Всего: 1751552
🔄 Запрос #17516 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 94 спецификаций. Всего: 1751646
🔄 Запрос #17517 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 129 спецификаций. Всего: 1751775
🔄 Запрос #17518 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 107 спецификаций. Всего: 1751882
🔄 Запрос #17519 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 118 спецификаций. Всего: 1752000
🔄 Запрос #17520 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 125 спецификаций. Всего: 1752125
🔄 Запрос #17521 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 110 спецификаций. Всего: 1752235
🔄 Запрос #17522 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1752330
🔄 Запрос #17523 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 86 спецификаций. Всего: 1752416
🔄 Запрос #17524 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 86 спецификаций. Всего: 1752502
🔄 Запрос #17525 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 102 спецификаций. Всего: 1752604
🔄 Запрос #17526 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 100 спецификаций. Всего: 1752704
🔄 Запрос #17527 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 101 спецификаций. Всего: 1752805
🔄 Запрос #17528 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 108 спецификаций. Всего: 1752913
🔄 Запрос #17529 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09

📥 Загружено 109 спецификаций. Всего: 1753022
🔄 Запрос #17530 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 99 спецификаций. Всего: 1753121
🔄 Запрос #17531 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 79 спецификаций. Всего: 1753200
🔄 Запрос #17532 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 71 спецификаций. Всего: 1753271
🔄 Запрос #17533 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 1753369
🔄 Запрос #17534 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 123 спецификаций. Всего: 1753492
🔄 Запрос #17535 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 76 спецификаций. Всего: 1753568
🔄 Запрос #17536 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 95 спецификаций. Всего: 1753663
🔄 Запрос #17537 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 77 спецификаций. Всего: 1753740
🔄 Запрос #17538 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 109 спецификаций. Всего: 1753849
🔄 Запрос #17539 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 98 спецификаций. Всего: 1753947
🔄 Запрос #17540 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 76 спецификаций. Всего: 1754023
🔄 Запрос #17541 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 106 спецификаций. Всего: 1754129
🔄 Запрос #17542 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 103 спецификаций. Всего: 1754232
🔄 Запрос #17543 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 92 спецификаций. Всего: 1754324
🔄 Запрос #17544 для 2024-02-15 20:44:09 - 2024-02-22 20:44:09
📥 Загружено 10 спецификаций. Всего: 1754334
📅 Обрабатываем диапазон 2024-02-08 20:44:09 - 2024-02-15 20:44:09 (попытка 1/5)
🔄 Запрос #17545 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 1754442
🔄 Запрос #17546 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 1754551
🔄 Запрос #17547 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 128 спецификаций. Всего: 1754679
🔄 Запрос #17548 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1754801
🔄 Запрос #17549 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 1754910
🔄 Запрос #17550 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 128 спецификаций. Всего: 1755038
🔄 Запрос #17551 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 139 спецификаций. Всего: 1755177
🔄 Запрос #17552 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 114 спецификаций. Всего: 1755291
🔄 Запрос #17553 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 121 спецификаций. Всего: 1755412
🔄 Запрос #17554 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 135 спецификаций. Всего: 1755547
🔄 Запрос #17555 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1755661
🔄 Запрос #17556 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 123 спецификаций. Всего: 1755784
🔄 Запрос #17557 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 123 спецификаций. Всего: 1755907
🔄 Запрос #17558 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 116 спецификаций. Всего: 1756023
🔄 Запрос #17559 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1756148
🔄 Запрос #17560 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 1756248
🔄 Запрос #17561 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 1756346
🔄 Запрос #17562 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 81 спецификаций. Всего: 1756427
🔄 Запрос #17563 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 95 спецификаций. Всего: 1756522
🔄 Запрос #17564 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 90 спецификаций. Всего: 1756612
🔄 Запрос #17565 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 1756710
🔄 Запрос #17566 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 95 спецификаций. Всего: 1756805
🔄 Запрос #17567 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 81 спецификаций. Всего: 1756886
🔄 Запрос #17568 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1756977
🔄 Запрос #17569 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 1757085
🔄 Запрос #17570 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1757185
🔄 Запрос #17571 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 1757288
🔄 Запрос #17572 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1757402
🔄 Запрос #17573 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 1757501
🔄 Запрос #17574 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 1757601
🔄 Запрос #17575 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 1757714
🔄 Запрос #17576 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 1757835
🔄 Запрос #17577 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 105 спецификаций. Всего: 1757940
🔄 Запрос #17578 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 124 спецификаций. Всего: 1758064
🔄 Запрос #17579 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 1758167
🔄 Запрос #17580 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 91 спецификаций. Всего: 1758258
🔄 Запрос #17581 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 1758350
🔄 Запрос #17582 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1758451
🔄 Запрос #17583 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 94 спецификаций. Всего: 1758545
🔄 Запрос #17584 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 1758653
🔄 Запрос #17585 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 1758755
🔄 Запрос #17586 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 1758855
🔄 Запрос #17587 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 75 спецификаций. Всего: 1758930
🔄 Запрос #17588 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 84 спецификаций. Всего: 1759014
🔄 Запрос #17589 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 1759124
🔄 Запрос #17590 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 1759234
🔄 Запрос #17591 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 122 спецификаций. Всего: 1759356
📤 Сохранено 10064 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #17592 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 122 спецификаций. Всего: 1759478
🔄 Запрос #17593 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 131 спецификаций. Всего: 1759609
🔄 Запрос #17594 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09

📥 Загружено 114 спецификаций. Всего: 1759723
🔄 Запрос #17595 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 1759820
🔄 Запрос #17596 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 93 спецификаций. Всего: 1759913
🔄 Запрос #17597 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 1760028
🔄 Запрос #17598 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1760123
🔄 Запрос #17599 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 88 спецификаций. Всего: 1760211
🔄 Запрос #17600 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 89 спецификаций. Всего: 1760300
🔄 Запрос #17601 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 1760399
🔄 Запрос #17602 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 87 спецификаций. Всего: 1760486
🔄 Запрос #17603 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 94 спецификаций. Всего: 1760580
🔄 Запрос #17604 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 89 спецификаций. Всего: 1760669
🔄 Запрос #17605 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 85 спецификаций. Всего: 1760754
🔄 Запрос #17606 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 84 спецификаций. Всего: 1760838
🔄 Запрос #17607 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1760934
🔄 Запрос #17608 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1761030
🔄 Запрос #17609 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 1761122
🔄 Запрос #17610 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 1761232
🔄 Запрос #17611 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 1761341
🔄 Запрос #17612 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 116 спецификаций. Всего: 1761457
🔄 Запрос #17613 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 74 спецификаций. Всего: 1761531
🔄 Запрос #17614 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 95 спецификаций. Всего: 1761626
🔄 Запрос #17615 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 87 спецификаций. Всего: 1761713
🔄 Запрос #17616 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 95 спецификаций. Всего: 1761808
🔄 Запрос #17617 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1761904
🔄 Запрос #17618 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 1762013
🔄 Запрос #17619 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 94 спецификаций. Всего: 1762107
🔄 Запрос #17620 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 1762215
🔄 Запрос #17621 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 1762319
🔄 Запрос #17622 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 1762427
🔄 Запрос #17623 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 1762535
🔄 Запрос #17624 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 1762635
🔄 Запрос #17625 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 1762725
🔄 Запрос #17626 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 1762822
🔄 Запрос #17627 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 1762921
🔄 Запрос #17628 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 1763023
🔄 Запрос #17629 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1763119
🔄 Запрос #17630 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 1763217
🔄 Запрос #17631 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 79 спецификаций. Всего: 1763296
🔄 Запрос #17632 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 88 спецификаций. Всего: 1763384
🔄 Запрос #17633 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 58 спецификаций. Всего: 1763442
🔄 Запрос #17634 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 81 спецификаций. Всего: 1763523
🔄 Запрос #17635 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 83 спецификаций. Всего: 1763606
🔄 Запрос #17636 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 91 спецификаций. Всего: 1763697
🔄 Запрос #17637 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 1763789
🔄 Запрос #17638 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 86 спецификаций. Всего: 1763875
🔄 Запрос #17639 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1763963
🔄 Запрос #17640 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 91 спецификаций. Всего: 1764054
🔄 Запрос #17641 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 1764151
🔄 Запрос #17642 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 86 спецификаций. Всего: 1764237
🔄 Запрос #17643 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 79 спецификаций. Всего: 1764316
🔄 Запрос #17644 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 69 спецификаций. Всего: 1764385
🔄 Запрос #17645 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 67 спецификаций. Всего: 1764452
🔄 Запрос #17646 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 70 спецификаций. Всего: 1764522
🔄 Запрос #17647 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 114 спецификаций. Всего: 1764636
🔄 Запрос #17648 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 95 спецификаций. Всего: 1764731
🔄 Запрос #17649 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 85 спецификаций. Всего: 1764816
🔄 Запрос #17650 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 94 спецификаций. Всего: 1764910
🔄 Запрос #17651 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 94 спецификаций. Всего: 1765004
🔄 Запрос #17652 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 127 спецификаций. Всего: 1765131
🔄 Запрос #17653 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 1765228
🔄 Запрос #17654 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 93 спецификаций. Всего: 1765321
🔄 Запрос #17655 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 1765413
🔄 Запрос #17656 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 106 спецификаций. Всего: 1765519
🔄 Запрос #17657 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 82 спецификаций. Всего: 1765601
🔄 Запрос #17658 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 87 спецификаций. Всего: 1765688
🔄 Запрос #17659 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 1765780
🔄 Запрос #17660 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 87 спецификаций. Всего: 1765867
🔄 Запрос #17661 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 91 спецификаций. Всего: 1765958
🔄 Запрос #17662 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 1766055
🔄 Запрос #17663 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 1766152
🔄 Запрос #17664 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 1766259

🔄 Запрос #17665 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 121 спецификаций. Всего: 1766380
🔄 Запрос #17666 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1766476
🔄 Запрос #17667 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1766593
🔄 Запрос #17668 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 1766711
🔄 Запрос #17669 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 124 спецификаций. Всего: 1766835
🔄 Запрос #17670 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 129 спецификаций. Всего: 1766964
🔄 Запрос #17671 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 1767082
🔄 Запрос #17672 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 123 спецификаций. Всего: 1767205
🔄 Запрос #17673 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 126 спецификаций. Всего: 1767331
🔄 Запрос #17674 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 131 спецификаций. Всего: 1767462
🔄 Запрос #17675 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 126 спецификаций. Всего: 1767588
🔄 Запрос #17676 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 151 спецификаций. Всего: 1767739
🔄 Запрос #17677 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 1767852
🔄 Запрос #17678 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 133 спецификаций. Всего: 1767985
🔄 Запрос #17679 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 105 спецификаций. Всего: 1768090
🔄 Запрос #17680 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 90 спецификаций. Всего: 1768180
🔄 Запрос #17681 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1768296
🔄 Запрос #17682 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 67 спецификаций. Всего: 1768363
🔄 Запрос #17683 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 106 спецификаций. Всего: 1768469
🔄 Запрос #17684 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 135 спецификаций. Всего: 1768604
🔄 Запрос #17685 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 93 спецификаций. Всего: 1768697
🔄 Запрос #17686 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 116 спецификаций. Всего: 1768813
🔄 Запрос #17687 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 76 спецификаций. Всего: 1768889
🔄 Запрос #17688 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 72 спецификаций. Всего: 1768961
🔄 Запрос #17689 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 139 спецификаций. Всего: 1769100
🔄 Запрос #17690 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 125 спецификаций. Всего: 1769225
🔄 Запрос #17691 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 123 спецификаций. Всего: 1769348
🔄 Запрос #17692 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 122 спецификаций. Всего: 1769470
📤 Сохранено 10114 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #17693 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 1769572
🔄 Запрос #17694 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1769670
🔄 Запрос #17695 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 105 спецификаций. Всего: 1769775
🔄 Запрос #17696 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 1769879
🔄 Запрос #17697 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 143 спецификаций. Всего: 1770022
🔄 Запрос #17698 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 135 спецификаций. Всего: 1770157
🔄 Запрос #17699 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 123 спецификаций. Всего: 1770280
🔄 Запрос #17700 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 127 спецификаций. Всего: 1770407
🔄 Запрос #17701 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1770523
🔄 Запрос #17702 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 103 спецификаций. Всего: 1770626
🔄 Запрос #17703 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 1770723
🔄 Запрос #17704 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 1770833
🔄 Запрос #17705 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 105 спецификаций. Всего: 1770938
🔄 Запрос #17706 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 91 спецификаций. Всего: 1771029
🔄 Запрос #17707 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 1771130
🔄 Запрос #17708 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1771226
🔄 Запрос #17709 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1771336
🔄 Запрос #17710 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 117 спецификаций. Всего: 1771453
🔄 Запрос #17711 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 105 спецификаций. Всего: 1771558
🔄 Запрос #17712 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1771660
🔄 Запрос #17713 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1771756
🔄 Запрос #17714 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1771852
🔄 Запрос #17715 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 1771953
🔄 Запрос #17716 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 1772052
🔄 Запрос #17717 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 81 спецификаций. Всего: 1772133
🔄 Запрос #17718 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 83 спецификаций. Всего: 1772216
🔄 Запрос #17719 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 95 спецификаций. Всего: 1772311
🔄 Запрос #17720 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 89 спецификаций. Всего: 1772400
🔄 Запрос #17721 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 79 спецификаций. Всего: 1772479
🔄 Запрос #17722 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 87 спецификаций. Всего: 1772566
🔄 Запрос #17723 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 72 спецификаций. Всего: 1772638
🔄 Запрос #17724 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 75 спецификаций. Всего: 1772713
🔄 Запрос #17725 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 1772817
🔄 Запрос #17726 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 1772914
🔄 Запрос #17727 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 1773025
🔄 Запрос #17728 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 1773124
🔄 Запрос #17729 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 1773235
🔄 Запрос #17730 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 1773343
🔄 Запрос #17731 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09

📥 Загружено 114 спецификаций. Всего: 1773457
🔄 Запрос #17732 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 1773566
🔄 Запрос #17733 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 1773663
🔄 Запрос #17734 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 96 спецификаций. Всего: 1773759
🔄 Запрос #17735 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 1773858
🔄 Запрос #17736 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 1773967
🔄 Запрос #17737 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 106 спецификаций. Всего: 1774073
🔄 Запрос #17738 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 120 спецификаций. Всего: 1774193
🔄 Запрос #17739 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1774315
🔄 Запрос #17740 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 1774433
🔄 Запрос #17741 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 1774544
🔄 Запрос #17742 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 1774651
🔄 Запрос #17743 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 1774758
🔄 Запрос #17744 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1774854
🔄 Запрос #17745 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 1774962
🔄 Запрос #17746 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 93 спецификаций. Всего: 1775055
🔄 Запрос #17747 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 95 спецификаций. Всего: 1775150
🔄 Запрос #17748 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 1775258
🔄 Запрос #17749 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 1775367
🔄 Запрос #17750 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 1775467
🔄 Запрос #17751 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 1775580
🔄 Запрос #17752 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 117 спецификаций. Всего: 1775697
🔄 Запрос #17753 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 122 спецификаций. Всего: 1775819
🔄 Запрос #17754 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 1775923
🔄 Запрос #17755 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 1776026
🔄 Запрос #17756 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 1776130
🔄 Запрос #17757 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 112 спецификаций. Всего: 1776242
🔄 Запрос #17758 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 1776334
🔄 Запрос #17759 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 1776445
🔄 Запрос #17760 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1776552
🔄 Запрос #17761 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 117 спецификаций. Всего: 1776669
🔄 Запрос #17762 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 91 спецификаций. Всего: 1776760
🔄 Запрос #17763 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 112 спецификаций. Всего: 1776872
🔄 Запрос #17764 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 1776987
🔄 Запрос #17765 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1777104
🔄 Запрос #17766 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 126 спецификаций. Всего: 1777230
🔄 Запрос #17767 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 144 спецификаций. Всего: 1777374
🔄 Запрос #17768 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 120 спецификаций. Всего: 1777494
🔄 Запрос #17769 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 142 спецификаций. Всего: 1777636
🔄 Запрос #17770 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 123 спецификаций. Всего: 1777759
🔄 Запрос #17771 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 86 спецификаций. Всего: 1777845
🔄 Запрос #17772 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 78 спецификаций. Всего: 1777923
🔄 Запрос #17773 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 74 спецификаций. Всего: 1777997
🔄 Запрос #17774 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 1778095
🔄 Запрос #17775 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 122 спецификаций. Всего: 1778217
🔄 Запрос #17776 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 1778332
🔄 Запрос #17777 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 114 спецификаций. Всего: 1778446
🔄 Запрос #17778 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 1778547
🔄 Запрос #17779 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1778643
🔄 Запрос #17780 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 127 спецификаций. Всего: 1778770
🔄 Запрос #17781 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 125 спецификаций. Всего: 1778895
🔄 Запрос #17782 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1778990
🔄 Запрос #17783 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 117 спецификаций. Всего: 1779107
🔄 Запрос #17784 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 112 спецификаций. Всего: 1779219
🔄 Запрос #17785 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1779331
🔄 Запрос #17786 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 1779432
🔄 Запрос #17787 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 80 спецификаций. Всего: 1779512
📤 Сохранено 10042 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #17788 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 117 спецификаций. Всего: 1779629
🔄 Запрос #17789 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1779741
🔄 Запрос #17790 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 106 спецификаций. Всего: 1779847
🔄 Запрос #17791 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 1779949
🔄 Запрос #17792 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 95 спецификаций. Всего: 1780044
🔄 Запрос #17793 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 1780154
🔄 Запрос #17794 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 1780264
🔄 Запрос #17795 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09

📥 Загружено 117 спецификаций. Всего: 1780381
🔄 Запрос #17796 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 1780490
🔄 Запрос #17797 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 1780590
🔄 Запрос #17798 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 129 спецификаций. Всего: 1780719
🔄 Запрос #17799 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 1780820
🔄 Запрос #17800 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1780916
🔄 Запрос #17801 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1781012
🔄 Запрос #17802 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 93 спецификаций. Всего: 1781105
🔄 Запрос #17803 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 1781195
🔄 Запрос #17804 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 105 спецификаций. Всего: 1781300
🔄 Запрос #17805 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 106 спецификаций. Всего: 1781406
🔄 Запрос #17806 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 1781505
🔄 Запрос #17807 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 1781605
🔄 Запрос #17808 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 1781718
🔄 Запрос #17809 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 1781822
🔄 Запрос #17810 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 108 спецификаций. Всего: 1781930
🔄 Запрос #17811 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 1782034
🔄 Запрос #17812 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 1782147
🔄 Запрос #17813 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 1782250
🔄 Запрос #17814 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 122 спецификаций. Всего: 1782372
🔄 Запрос #17815 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 1782475
🔄 Запрос #17816 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 84 спецификаций. Всего: 1782559
🔄 Запрос #17817 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 85 спецификаций. Всего: 1782644
🔄 Запрос #17818 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 88 спецификаций. Всего: 1782732
🔄 Запрос #17819 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 1782833
🔄 Запрос #17820 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 1782944
🔄 Запрос #17821 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 109 спецификаций. Всего: 1783053
🔄 Запрос #17822 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 1783155
🔄 Запрос #17823 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1783270
🔄 Запрос #17824 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 1783380
🔄 Запрос #17825 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 1783498
🔄 Запрос #17826 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 117 спецификаций. Всего: 1783615
🔄 Запрос #17827 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 1783726
🔄 Запрос #17828 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 1783841
🔄 Запрос #17829 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 117 спецификаций. Всего: 1783958
🔄 Запрос #17830 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 1784073
🔄 Запрос #17831 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 1784183
🔄 Запрос #17832 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 121 спецификаций. Всего: 1784304
🔄 Запрос #17833 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 126 спецификаций. Всего: 1784430
🔄 Запрос #17834 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 116 спецификаций. Всего: 1784546
🔄 Запрос #17835 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 1784650
🔄 Запрос #17836 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1784744
🔄 Запрос #17837 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 94 спецификаций. Всего: 1784838
🔄 Запрос #17838 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1784933
🔄 Запрос #17839 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 95 спецификаций. Всего: 1785028
🔄 Запрос #17840 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 89 спецификаций. Всего: 1785117
🔄 Запрос #17841 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1785208
🔄 Запрос #17842 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 121 спецификаций. Всего: 1785329
🔄 Запрос #17843 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 1785430
🔄 Запрос #17844 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 112 спецификаций. Всего: 1785542
🔄 Запрос #17845 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 1785642
🔄 Запрос #17846 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 125 спецификаций. Всего: 1785767
🔄 Запрос #17847 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 1785878
🔄 Запрос #17848 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1785972
🔄 Запрос #17849 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 85 спецификаций. Всего: 1786057
🔄 Запрос #17850 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1786176
🔄 Запрос #17851 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 1786279
🔄 Запрос #17852 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 79 спецификаций. Всего: 1786358
🔄 Запрос #17853 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 1786469
🔄 Запрос #17854 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 136 спецификаций. Всего: 1786605
🔄 Запрос #17855 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 1786723
🔄 Запрос #17856 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 73 спецификаций. Всего: 1786796
🔄 Запрос #17857 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 1786895
🔄 Запрос #17858 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 121 спецификаций. Всего: 1787016
🔄 Запрос #17859 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 93 спецификаций. Всего: 1787109
🔄 Запрос #17860 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 90 спецификаций. Всего: 1787199
🔄 Запрос #17861 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 127 спецификаций. Всего: 1787326
🔄 Запрос #17862 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 1787433
🔄 Запрос #17863 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 128 спецификаций. Всего: 1787561

🔄 Запрос #17864 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 119 спецификаций. Всего: 1787680
🔄 Запрос #17865 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 135 спецификаций. Всего: 1787815
🔄 Запрос #17866 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 82 спецификаций. Всего: 1787897
🔄 Запрос #17867 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 57 спецификаций. Всего: 1787954
🔄 Запрос #17868 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 47 спецификаций. Всего: 1788001
🔄 Запрос #17869 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 56 спецификаций. Всего: 1788057
🔄 Запрос #17870 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 1788149
🔄 Запрос #17871 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 117 спецификаций. Всего: 1788266
🔄 Запрос #17872 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 93 спецификаций. Всего: 1788359
🔄 Запрос #17873 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 130 спецификаций. Всего: 1788489
🔄 Запрос #17874 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 192 спецификаций. Всего: 1788681
🔄 Запрос #17875 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 163 спецификаций. Всего: 1788844
🔄 Запрос #17876 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 66 спецификаций. Всего: 1788910
🔄 Запрос #17877 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 97 спецификаций. Всего: 1789007
🔄 Запрос #17878 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 140 спецификаций. Всего: 1789147
🔄 Запрос #17879 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 129 спецификаций. Всего: 1789276
🔄 Запрос #17880 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 82 спецификаций. Всего: 1789358
🔄 Запрос #17881 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 1789471
🔄 Запрос #17882 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 85 спецификаций. Всего: 1789556
📤 Сохранено 10044 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #17883 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 130 спецификаций. Всего: 1789686
🔄 Запрос #17884 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 116 спецификаций. Всего: 1789802
🔄 Запрос #17885 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 138 спецификаций. Всего: 1789940
🔄 Запрос #17886 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 133 спецификаций. Всего: 1790073
🔄 Запрос #17887 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 119 спецификаций. Всего: 1790192
🔄 Запрос #17888 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 1790307
🔄 Запрос #17889 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1790423
🔄 Запрос #17890 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 139 спецификаций. Всего: 1790562
🔄 Запрос #17891 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 135 спецификаций. Всего: 1790697
🔄 Запрос #17892 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1790808
🔄 Запрос #17893 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1790919
🔄 Запрос #17894 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1791030
🔄 Запрос #17895 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 106 спецификаций. Всего: 1791136
🔄 Запрос #17896 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1791232
🔄 Запрос #17897 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 1791334
🔄 Запрос #17898 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 1791447
🔄 Запрос #17899 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 122 спецификаций. Всего: 1791569
🔄 Запрос #17900 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 1791672
🔄 Запрос #17901 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 118 спецификаций. Всего: 1791790
🔄 Запрос #17902 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 1791890
🔄 Запрос #17903 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 1791997
🔄 Запрос #17904 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 116 спецификаций. Всего: 1792113
🔄 Запрос #17905 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 112 спецификаций. Всего: 1792225
🔄 Запрос #17906 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 64 спецификаций. Всего: 1792289
🔄 Запрос #17907 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 84 спецификаций. Всего: 1792373
🔄 Запрос #17908 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 114 спецификаций. Всего: 1792487
🔄 Запрос #17909 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 1792585
🔄 Запрос #17910 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 115 спецификаций. Всего: 1792700
🔄 Запрос #17911 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 105 спецификаций. Всего: 1792805
🔄 Запрос #17912 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1792899
🔄 Запрос #17913 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 1792988
🔄 Запрос #17914 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 1793089
🔄 Запрос #17915 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 114 спецификаций. Всего: 1793203
🔄 Запрос #17916 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 83 спецификаций. Всего: 1793286
🔄 Запрос #17917 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 1793386
🔄 Запрос #17918 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 1793490
🔄 Запрос #17919 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1793599
🔄 Запрос #17920 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1793695
🔄 Запрос #17921 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1793793
🔄 Запрос #17922 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 1793900
🔄 Запрос #17923 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 1794002
🔄 Запрос #17924 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1794108
🔄 Запрос #17925 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09

📥 Загружено 104 спецификаций. Всего: 1794212
🔄 Запрос #17926 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 102 спецификаций. Всего: 1794314
🔄 Запрос #17927 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 88 спецификаций. Всего: 1794402
🔄 Запрос #17928 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 1794500
🔄 Запрос #17929 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 124 спецификаций. Всего: 1794624
🔄 Запрос #17930 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1794743
🔄 Запрос #17931 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 106 спецификаций. Всего: 1794849
🔄 Запрос #17932 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 116 спецификаций. Всего: 1794965
🔄 Запрос #17933 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 111 спецификаций. Всего: 1795076
🔄 Запрос #17934 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 86 спецификаций. Всего: 1795162
🔄 Запрос #17935 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 89 спецификаций. Всего: 1795251
🔄 Запрос #17936 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 1795350
🔄 Запрос #17937 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 122 спецификаций. Всего: 1795472
🔄 Запрос #17938 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 1795582
🔄 Запрос #17939 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 1795695
🔄 Запрос #17940 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 80 спецификаций. Всего: 1795775
🔄 Запрос #17941 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 81 спецификаций. Всего: 1795856
🔄 Запрос #17942 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 1795954
🔄 Запрос #17943 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 96 спецификаций. Всего: 1796050
🔄 Запрос #17944 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 110 спецификаций. Всего: 1796160
🔄 Запрос #17945 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 113 спецификаций. Всего: 1796273
🔄 Запрос #17946 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1796385
🔄 Запрос #17947 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 104 спецификаций. Всего: 1796489
🔄 Запрос #17948 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 119 спецификаций. Всего: 1796608
🔄 Запрос #17949 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 92 спецификаций. Всего: 1796700
🔄 Запрос #17950 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 98 спецификаций. Всего: 1796798
🔄 Запрос #17951 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 1796897
🔄 Запрос #17952 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 1797000
🔄 Запрос #17953 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 103 спецификаций. Всего: 1797103
🔄 Запрос #17954 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 99 спецификаций. Всего: 1797202
🔄 Запрос #17955 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 100 спецификаций. Всего: 1797302
🔄 Запрос #17956 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 133 спецификаций. Всего: 1797435
🔄 Запрос #17957 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 156 спецификаций. Всего: 1797591
🔄 Запрос #17958 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 121 спецификаций. Всего: 1797712
🔄 Запрос #17959 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 90 спецификаций. Всего: 1797802
🔄 Запрос #17960 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 89 спецификаций. Всего: 1797891
🔄 Запрос #17961 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 101 спецификаций. Всего: 1797992
🔄 Запрос #17962 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 107 спецификаций. Всего: 1798099
🔄 Запрос #17963 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 125 спецификаций. Всего: 1798224
🔄 Запрос #17964 для 2024-02-08 20:44:09 - 2024-02-15 20:44:09
📥 Загружено 48 спецификаций. Всего: 1798272
📅 Обрабатываем диапазон 2024-02-01 20:44:09 - 2024-02-08 20:44:09 (попытка 1/5)
🔄 Запрос #17965 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1798396
🔄 Запрос #17966 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1798508
🔄 Запрос #17967 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1798599
🔄 Запрос #17968 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 73 спецификаций. Всего: 1798672
🔄 Запрос #17969 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 95 спецификаций. Всего: 1798767
🔄 Запрос #17970 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1798867
🔄 Запрос #17971 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 131 спецификаций. Всего: 1798998
🔄 Запрос #17972 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 1799118
🔄 Запрос #17973 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 1799239
🔄 Запрос #17974 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1799357
🔄 Запрос #17975 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 1799483
🔄 Запрос #17976 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1799601
📤 Сохранено 10045 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #17977 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 1799702
🔄 Запрос #17978 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 1799807
🔄 Запрос #17979 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1799907
🔄 Запрос #17980 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 99 спецификаций. Всего: 1800006
🔄 Запрос #17981 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1800120
🔄 Запрос #17982 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 1800235
🔄 Запрос #17983 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1800351
🔄 Запрос #17984 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1800468
🔄 Запрос #17985 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 1800594
🔄 Запрос #17986 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 130 спецификаций. Всего: 1800724
🔄 Запрос #17987 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1800840
🔄 Запрос #17988 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1800940
🔄 Запрос #17989 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 91 спецификаций. Всего: 1801031
🔄 Запрос #17990 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 97 спецификаций. Всего: 1801128
🔄 Запрос #17991 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 97 спецификаций. Всего: 1801225

🔄 Запрос #17992 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 96 спецификаций. Всего: 1801321
🔄 Запрос #17993 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 1801431
🔄 Запрос #17994 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 95 спецификаций. Всего: 1801526
🔄 Запрос #17995 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 1801627
🔄 Запрос #17996 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 1801738
🔄 Запрос #17997 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1801846
🔄 Запрос #17998 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 99 спецификаций. Всего: 1801945
🔄 Запрос #17999 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 1802047
🔄 Запрос #18000 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 99 спецификаций. Всего: 1802146
🔄 Запрос #18001 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 1802247
🔄 Запрос #18002 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 1802352
🔄 Запрос #18003 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 109 спецификаций. Всего: 1802461
🔄 Запрос #18004 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1802575
🔄 Запрос #18005 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 1802680
🔄 Запрос #18006 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 1802786
🔄 Запрос #18007 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 1802891
🔄 Запрос #18008 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 94 спецификаций. Всего: 1802985
🔄 Запрос #18009 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 1803096
🔄 Запрос #18010 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 97 спецификаций. Всего: 1803193
🔄 Запрос #18011 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1803293
🔄 Запрос #18012 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 96 спецификаций. Всего: 1803389
🔄 Запрос #18013 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 1803509
🔄 Запрос #18014 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 1803620
🔄 Запрос #18015 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 109 спецификаций. Всего: 1803729
🔄 Запрос #18016 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 83 спецификаций. Всего: 1803812
🔄 Запрос #18017 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 72 спецификаций. Всего: 1803884
🔄 Запрос #18018 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 1803997
🔄 Запрос #18019 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 132 спецификаций. Всего: 1804129
🔄 Запрос #18020 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1804245
🔄 Запрос #18021 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 1804356
🔄 Запрос #18022 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 1804476
🔄 Запрос #18023 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 1804577
🔄 Запрос #18024 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 103 спецификаций. Всего: 1804680
🔄 Запрос #18025 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 1804786
🔄 Запрос #18026 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 1804888
🔄 Запрос #18027 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1804988
🔄 Запрос #18028 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 103 спецификаций. Всего: 1805091
🔄 Запрос #18029 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1805199
🔄 Запрос #18030 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 1805312
🔄 Запрос #18031 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 90 спецификаций. Всего: 1805402
🔄 Запрос #18032 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1805518
🔄 Запрос #18033 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1805619
🔄 Запрос #18034 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1805727
🔄 Запрос #18035 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1805835
🔄 Запрос #18036 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 91 спецификаций. Всего: 1805926
🔄 Запрос #18037 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 103 спецификаций. Всего: 1806029
🔄 Запрос #18038 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1806141
🔄 Запрос #18039 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 94 спецификаций. Всего: 1806235
🔄 Запрос #18040 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 94 спецификаций. Всего: 1806329
🔄 Запрос #18041 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 99 спецификаций. Всего: 1806428
🔄 Запрос #18042 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1806532
🔄 Запрос #18043 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 1806633
🔄 Запрос #18044 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1806733
🔄 Запрос #18045 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 62 спецификаций. Всего: 1806795
🔄 Запрос #18046 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 89 спецификаций. Всего: 1806884
🔄 Запрос #18047 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 81 спецификаций. Всего: 1806965
🔄 Запрос #18048 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 89 спецификаций. Всего: 1807054
🔄 Запрос #18049 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 92 спецификаций. Всего: 1807146
🔄 Запрос #18050 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1807240
🔄 Запрос #18051 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1807367
🔄 Запрос #18052 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 96 спецификаций. Всего: 1807463
🔄 Запрос #18053 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 1807574
🔄 Запрос #18054 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1807676
🔄 Запрос #18055 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 154 спецификаций. Всего: 1807830
🔄 Запрос #18056 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 167 спецификаций. Всего: 1807997
🔄 Запрос #18057 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 132 спецификаций. Всего: 1808129
🔄 Запрос #18058 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1808251
🔄 Запрос #18059 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 137 спецификаций. Всего: 1808388
🔄 Запрос #18060 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 107 спецификаций. Всего: 1808495
🔄 Запрос #18061 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1808622
🔄 Запрос #18062 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 138 спецификаций. Всего: 1808760

🔄 Запрос #18063 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1808878
🔄 Запрос #18064 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1808994
🔄 Запрос #18065 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 1809120
🔄 Запрос #18066 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 148 спецификаций. Всего: 1809268
🔄 Запрос #18067 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 150 спецификаций. Всего: 1809418
🔄 Запрос #18068 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1809545
🔄 Запрос #18069 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 148 спецификаций. Всего: 1809693
📤 Сохранено 10092 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #18070 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 138 спецификаций. Всего: 1809831
🔄 Запрос #18071 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 124 спецификаций. Всего: 1809955
🔄 Запрос #18072 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1810059
🔄 Запрос #18073 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 134 спецификаций. Всего: 1810193
🔄 Запрос #18074 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 131 спецификаций. Всего: 1810324
🔄 Запрос #18075 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1810451
🔄 Запрос #18076 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 45 спецификаций. Всего: 1810496
🔄 Запрос #18077 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1810611
🔄 Запрос #18078 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 122 спецификаций. Всего: 1810733
🔄 Запрос #18079 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1810833
🔄 Запрос #18080 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 1810948
🔄 Запрос #18081 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1811052
🔄 Запрос #18082 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 1811165
🔄 Запрос #18083 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1811279
🔄 Запрос #18084 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1811383
🔄 Запрос #18085 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 1811496
🔄 Запрос #18086 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 109 спецификаций. Всего: 1811605
🔄 Запрос #18087 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1811730
🔄 Запрос #18088 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1811847
🔄 Запрос #18089 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1811964
🔄 Запрос #18090 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 1812089
🔄 Запрос #18091 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 1812214
🔄 Запрос #18092 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1812330
🔄 Запрос #18093 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 103 спецификаций. Всего: 1812433
🔄 Запрос #18094 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1812533
🔄 Запрос #18095 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 74 спецификаций. Всего: 1812607
🔄 Запрос #18096 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1812707
🔄 Запрос #18097 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1812811
🔄 Запрос #18098 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 1812921
🔄 Запрос #18099 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 87 спецификаций. Всего: 1813008
🔄 Запрос #18100 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 1813114
🔄 Запрос #18101 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1813226
🔄 Запрос #18102 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1813330
🔄 Запрос #18103 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 1813436
🔄 Запрос #18104 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 1813538
🔄 Запрос #18105 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1813650
🔄 Запрос #18106 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 94 спецификаций. Всего: 1813744
🔄 Запрос #18107 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 82 спецификаций. Всего: 1813826
🔄 Запрос #18108 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 1813931
🔄 Запрос #18109 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 1814051
🔄 Запрос #18110 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 95 спецификаций. Всего: 1814146
🔄 Запрос #18111 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 1814247
🔄 Запрос #18112 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 91 спецификаций. Всего: 1814338
🔄 Запрос #18113 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 1814471
🔄 Запрос #18114 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 1814594
🔄 Запрос #18115 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 1814704
🔄 Запрос #18116 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1814816
🔄 Запрос #18117 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 1814931
🔄 Запрос #18118 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 1815052
🔄 Запрос #18119 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 124 спецификаций. Всего: 1815176
🔄 Запрос #18120 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 119 спецификаций. Всего: 1815295
🔄 Запрос #18121 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1815412
🔄 Запрос #18122 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 122 спецификаций. Всего: 1815534
🔄 Запрос #18123 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 129 спецификаций. Всего: 1815663
🔄 Запрос #18124 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1815790
🔄 Запрос #18125 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 128 спецификаций. Всего: 1815918
🔄 Запрос #18126 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 128 спецификаций. Всего: 1816046
🔄 Запрос #18127 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1816158
🔄 Запрос #18128 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 1816278
🔄 Запрос #18129 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 1816398
🔄 Запрос #18130 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 130 спецификаций. Всего: 1816528
🔄 Запрос #18131 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1816645

🔄 Запрос #18132 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 119 спецификаций. Всего: 1816764
🔄 Запрос #18133 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 112 спецификаций. Всего: 1816876
🔄 Запрос #18134 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1816990
🔄 Запрос #18135 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1817094
🔄 Запрос #18136 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1817221
🔄 Запрос #18137 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 1817336
🔄 Запрос #18138 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1817450
🔄 Запрос #18139 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1817567
🔄 Запрос #18140 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 93 спецификаций. Всего: 1817660
🔄 Запрос #18141 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1817777
🔄 Запрос #18142 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1817894
🔄 Запрос #18143 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1818009
🔄 Запрос #18144 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 1818130
🔄 Запрос #18145 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 1818240
🔄 Запрос #18146 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 107 спецификаций. Всего: 1818347
🔄 Запрос #18147 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1818459
🔄 Запрос #18148 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1818585
🔄 Запрос #18149 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 51 спецификаций. Всего: 1818636
🔄 Запрос #18150 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 89 спецификаций. Всего: 1818725
🔄 Запрос #18151 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 1818827
🔄 Запрос #18152 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 81 спецификаций. Всего: 1818908
🔄 Запрос #18153 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 75 спецификаций. Всего: 1818983
🔄 Запрос #18154 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 86 спецификаций. Всего: 1819069
🔄 Запрос #18155 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 124 спецификаций. Всего: 1819193
🔄 Запрос #18156 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 1819319
🔄 Запрос #18157 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 107 спецификаций. Всего: 1819426
🔄 Запрос #18158 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1819540
🔄 Запрос #18159 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 1819673
🔄 Запрос #18160 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1819791
📤 Сохранено 10098 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #18161 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 103 спецификаций. Всего: 1819894
🔄 Запрос #18162 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1819994
🔄 Запрос #18163 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 87 спецификаций. Всего: 1820081
🔄 Запрос #18164 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1820189
🔄 Запрос #18165 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1820317
🔄 Запрос #18166 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1820429
🔄 Запрос #18167 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 134 спецификаций. Всего: 1820563
🔄 Запрос #18168 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1820681
🔄 Запрос #18169 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 109 спецификаций. Всего: 1820790
🔄 Запрос #18170 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1820914
🔄 Запрос #18171 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 141 спецификаций. Всего: 1821055
🔄 Запрос #18172 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 129 спецификаций. Всего: 1821184
🔄 Запрос #18173 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 1821285
🔄 Запрос #18174 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 85 спецификаций. Всего: 1821370
🔄 Запрос #18175 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1821487
🔄 Запрос #18176 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 122 спецификаций. Всего: 1821609
🔄 Запрос #18177 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 1821719
🔄 Запрос #18178 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 1821842
🔄 Запрос #18179 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 1821952
🔄 Запрос #18180 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 122 спецификаций. Всего: 1822074
🔄 Запрос #18181 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 119 спецификаций. Всего: 1822193
🔄 Запрос #18182 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 1822306
🔄 Запрос #18183 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 122 спецификаций. Всего: 1822428
🔄 Запрос #18184 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1822555
🔄 Запрос #18185 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 1822688
🔄 Запрос #18186 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 137 спецификаций. Всего: 1822825
🔄 Запрос #18187 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 132 спецификаций. Всего: 1822957
🔄 Запрос #18188 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1823071
🔄 Запрос #18189 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 130 спецификаций. Всего: 1823201
🔄 Запрос #18190 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1823325
🔄 Запрос #18191 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 1823451
🔄 Запрос #18192 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 1823576
🔄 Запрос #18193 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1823693
🔄 Запрос #18194 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1823807
🔄 Запрос #18195 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1823915
🔄 Запрос #18196 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1824033
🔄 Запрос #18197 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 119 спецификаций. Всего: 1824152

🔄 Запрос #18198 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1824264
🔄 Запрос #18199 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 1824379
🔄 Запрос #18200 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1824496
🔄 Запрос #18201 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1824609
🔄 Запрос #18202 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1824725
🔄 Запрос #18203 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1824852
🔄 Запрос #18204 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 1824975
🔄 Запрос #18205 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 123 спецификаций. Всего: 1825098
🔄 Запрос #18206 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 124 спецификаций. Всего: 1825222
🔄 Запрос #18207 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 1825333
🔄 Запрос #18208 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1825438
🔄 Запрос #18209 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 1825539
🔄 Запрос #18210 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 119 спецификаций. Всего: 1825658
🔄 Запрос #18211 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 1825779
🔄 Запрос #18212 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 134 спецификаций. Всего: 1825913
🔄 Запрос #18213 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 131 спецификаций. Всего: 1826044
🔄 Запрос #18214 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 1826147
🔄 Запрос #18215 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1826247
🔄 Запрос #18216 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1826353
🔄 Запрос #18217 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1826457
🔄 Запрос #18218 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1826573
🔄 Запрос #18219 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 149 спецификаций. Всего: 1826722
🔄 Запрос #18220 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 135 спецификаций. Всего: 1826857
🔄 Запрос #18221 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 1826978
🔄 Запрос #18222 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 139 спецификаций. Всего: 1827117
🔄 Запрос #18223 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 132 спецификаций. Всего: 1827249
🔄 Запрос #18224 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 1827382
🔄 Запрос #18225 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 139 спецификаций. Всего: 1827521
🔄 Запрос #18226 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 128 спецификаций. Всего: 1827649
🔄 Запрос #18227 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 131 спецификаций. Всего: 1827780
🔄 Запрос #18228 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 1827913
🔄 Запрос #18229 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 135 спецификаций. Всего: 1828048
🔄 Запрос #18230 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 131 спецификаций. Всего: 1828179
🔄 Запрос #18231 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1828306
🔄 Запрос #18232 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 109 спецификаций. Всего: 1828415
🔄 Запрос #18233 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 1828526
🔄 Запрос #18234 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 1828643
🔄 Запрос #18235 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 1828756
🔄 Запрос #18236 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1828860
🔄 Запрос #18237 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1828974
🔄 Запрос #18238 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 1829084
🔄 Запрос #18239 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1829198
🔄 Запрос #18240 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1829302
🔄 Запрос #18241 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1829420
🔄 Запрос #18242 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1829545
🔄 Запрос #18243 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 1829660
🔄 Запрос #18244 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 1829762
🔄 Запрос #18245 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 131 спецификаций. Всего: 1829893
📤 Сохранено 10102 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #18246 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 1830018
🔄 Запрос #18247 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1830135
🔄 Запрос #18248 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 92 спецификаций. Всего: 1830227
🔄 Запрос #18249 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1830341
🔄 Запрос #18250 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1830445
🔄 Запрос #18251 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1830561
🔄 Запрос #18252 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 90 спецификаций. Всего: 1830651
🔄 Запрос #18253 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 116 спецификаций. Всего: 1830767
🔄 Запрос #18254 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 1830894
🔄 Запрос #18255 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1831010

🔄 Запрос #18256 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 1831131
🔄 Запрос #18257 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 1831242
🔄 Запрос #18258 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 131 спецификаций. Всего: 1831373
🔄 Запрос #18259 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 143 спецификаций. Всего: 1831516
🔄 Запрос #18260 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 128 спецификаций. Всего: 1831644
🔄 Запрос #18261 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1831771
🔄 Запрос #18262 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1831867
🔄 Запрос #18263 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1831971
🔄 Запрос #18264 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1832085
🔄 Запрос #18265 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 1832218
🔄 Запрос #18266 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 1832338
🔄 Запрос #18267 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1832465
🔄 Запрос #18268 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 129 спецификаций. Всего: 1832594
🔄 Запрос #18269 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 1832699
🔄 Запрос #18270 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 137 спецификаций. Всего: 1832836
🔄 Запрос #18271 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 88 спецификаций. Всего: 1832924
🔄 Запрос #18272 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 91 спецификаций. Всего: 1833015
🔄 Запрос #18273 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 97 спецификаций. Всего: 1833112
🔄 Запрос #18274 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 94 спецификаций. Всего: 1833206
🔄 Запрос #18275 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 1833316
🔄 Запрос #18276 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1833438
🔄 Запрос #18277 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 143 спецификаций. Всего: 1833581
🔄 Запрос #18278 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 1833707
🔄 Запрос #18279 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 1833827
🔄 Запрос #18280 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 107 спецификаций. Всего: 1833934
🔄 Запрос #18281 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1834048
🔄 Запрос #18282 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1834164
🔄 Запрос #18283 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 1834285
🔄 Запрос #18284 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 138 спецификаций. Всего: 1834423
🔄 Запрос #18285 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 134 спецификаций. Всего: 1834557
🔄 Запрос #18286 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 1834678
🔄 Запрос #18287 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 1834783
🔄 Запрос #18288 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 1834906
🔄 Запрос #18289 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1835028
🔄 Запрос #18290 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1835156
🔄 Запрос #18291 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 1835289
🔄 Запрос #18292 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 139 спецификаций. Всего: 1835428
🔄 Запрос #18293 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 149 спецификаций. Всего: 1835577
🔄 Запрос #18294 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 148 спецификаций. Всего: 1835725
🔄 Запрос #18295 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 130 спецификаций. Всего: 1835855
🔄 Запрос #18296 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 124 спецификаций. Всего: 1835979
🔄 Запрос #18297 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1836106
🔄 Запрос #18298 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 1836227
🔄 Запрос #18299 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1836341
🔄 Запрос #18300 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 1836464
🔄 Запрос #18301 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 122 спецификаций. Всего: 1836586
🔄 Запрос #18302 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 1836692
🔄 Запрос #18303 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1836818
🔄 Запрос #18304 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1836935
🔄 Запрос #18305 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1837051
🔄 Запрос #18306 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 107 спецификаций. Всего: 1837158
🔄 Запрос #18307 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1837276
🔄 Запрос #18308 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1837392
🔄 Запрос #18309 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 1837507
🔄 Запрос #18310 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1837624
🔄 Запрос #18311 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1837732
🔄 Запрос #18312 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 1837853
🔄 Запрос #18313 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1837958
🔄 Запрос #18314 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 1838071
🔄 Запрос #18315 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1838178
🔄 Запрос #18316 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 1838284
🔄 Запрос #18317 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 1838407
🔄 Запрос #18318 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1838507
🔄 Запрос #18319 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 94 спецификаций. Всего: 1838601
🔄 Запрос #18320 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 86 спецификаций. Всего: 1838687
🔄 Запрос #18321 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 1838793

🔄 Запрос #18322 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 1838895
🔄 Запрос #18323 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 79 спецификаций. Всего: 1838974
🔄 Запрос #18324 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1839086
🔄 Запрос #18325 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 96 спецификаций. Всего: 1839182
🔄 Запрос #18326 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1839290
🔄 Запрос #18327 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1839392
🔄 Запрос #18328 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 93 спецификаций. Всего: 1839485
🔄 Запрос #18329 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 1839600
🔄 Запрос #18330 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 131 спецификаций. Всего: 1839731
🔄 Запрос #18331 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 92 спецификаций. Всего: 1839823
🔄 Запрос #18332 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1839927
📤 Сохранено 10034 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #18333 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 1840032
🔄 Запрос #18334 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1840150
🔄 Запрос #18335 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1840266
🔄 Запрос #18336 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 102 спецификаций. Всего: 1840368
🔄 Запрос #18337 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 95 спецификаций. Всего: 1840463
🔄 Запрос #18338 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 103 спецификаций. Всего: 1840566
🔄 Запрос #18339 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 1840686
🔄 Запрос #18340 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 1840812
🔄 Запрос #18341 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 1840945
🔄 Запрос #18342 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 1841066
🔄 Запрос #18343 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 89 спецификаций. Всего: 1841155
🔄 Запрос #18344 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 59 спецификаций. Всего: 1841214
🔄 Запрос #18345 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 1841340
🔄 Запрос #18346 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1841447
🔄 Запрос #18347 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 1841553
🔄 Запрос #18348 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 99 спецификаций. Всего: 1841652
🔄 Запрос #18349 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 100 спецификаций. Всего: 1841752
🔄 Запрос #18350 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1841865
🔄 Запрос #18351 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1841983
🔄 Запрос #18352 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1842100
🔄 Запрос #18353 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 132 спецификаций. Всего: 1842232
🔄 Запрос #18354 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 122 спецификаций. Всего: 1842354
🔄 Запрос #18355 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 1842477
🔄 Запрос #18356 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1842593
🔄 Запрос #18357 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 1842713
🔄 Запрос #18358 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 1842838
🔄 Запрос #18359 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 130 спецификаций. Всего: 1842968
🔄 Запрос #18360 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 1843101
🔄 Запрос #18361 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 132 спецификаций. Всего: 1843233
🔄 Запрос #18362 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1843357
🔄 Запрос #18363 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 129 спецификаций. Всего: 1843486
🔄 Запрос #18364 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 132 спецификаций. Всего: 1843618
🔄 Запрос #18365 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1843730
🔄 Запрос #18366 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 128 спецификаций. Всего: 1843858
🔄 Запрос #18367 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 76 спецификаций. Всего: 1843934
🔄 Запрос #18368 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 53 спецификаций. Всего: 1843987
🔄 Запрос #18369 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 135 спецификаций. Всего: 1844122
🔄 Запрос #18370 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 92 спецификаций. Всего: 1844214
🔄 Запрос #18371 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 65 спецификаций. Всего: 1844279
🔄 Запрос #18372 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 90 спецификаций. Всего: 1844369
🔄 Запрос #18373 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 1844458
🔄 Запрос #18374 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 73 спецификаций. Всего: 1844531
🔄 Запрос #18375 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 101 спецификаций. Всего: 1844632
🔄 Запрос #18376 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 78 спецификаций. Всего: 1844710
🔄 Запрос #18377 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 120 спецификаций. Всего: 1844830
🔄 Запрос #18378 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 1844941
🔄 Запрос #18379 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 106 спецификаций. Всего: 1845047
🔄 Запрос #18380 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1845163
🔄 Запрос #18381 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1845290
🔄 Запрос #18382 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 1845413
🔄 Запрос #18383 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 108 спецификаций. Всего: 1845521
🔄 Запрос #18384 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 134 спецификаций. Всего: 1845655
🔄 Запрос #18385 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 57 спецификаций. Всего: 1845712
🔄 Запрос #18386 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1845829
🔄 Запрос #18387 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09

📥 Загружено 85 спецификаций. Всего: 1845914
🔄 Запрос #18388 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 142 спецификаций. Всего: 1846056
🔄 Запрос #18389 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 104 спецификаций. Всего: 1846160
🔄 Запрос #18390 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 153 спецификаций. Всего: 1846313
🔄 Запрос #18391 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 107 спецификаций. Всего: 1846420
🔄 Запрос #18392 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 72 спецификаций. Всего: 1846492
🔄 Запрос #18393 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 53 спецификаций. Всего: 1846545
🔄 Запрос #18394 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 71 спецификаций. Всего: 1846616
🔄 Запрос #18395 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 86 спецификаций. Всего: 1846702
🔄 Запрос #18396 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 1846827
🔄 Запрос #18397 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 114 спецификаций. Всего: 1846941
🔄 Запрос #18398 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 1847056
🔄 Запрос #18399 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 111 спецификаций. Всего: 1847167
🔄 Запрос #18400 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 66 спецификаций. Всего: 1847233
🔄 Запрос #18401 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 53 спецификаций. Всего: 1847286
🔄 Запрос #18402 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 71 спецификаций. Всего: 1847357
🔄 Запрос #18403 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1847485
🔄 Запрос #18404 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 130 спецификаций. Всего: 1847615
🔄 Запрос #18405 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 154 спецификаций. Всего: 1847769
🔄 Запрос #18406 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 150 спецификаций. Всего: 1847919
🔄 Запрос #18407 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 148 спецификаций. Всего: 1848067
🔄 Запрос #18408 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 141 спецификаций. Всего: 1848208
🔄 Запрос #18409 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 150 спецификаций. Всего: 1848358
🔄 Запрос #18410 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 132 спецификаций. Всего: 1848490
🔄 Запрос #18411 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 135 спецификаций. Всего: 1848625
🔄 Запрос #18412 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 152 спецификаций. Всего: 1848777
🔄 Запрос #18413 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1848895
🔄 Запрос #18414 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 122 спецификаций. Всего: 1849017
🔄 Запрос #18415 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1849129
🔄 Запрос #18416 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 109 спецификаций. Всего: 1849238
🔄 Запрос #18417 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 1849351
🔄 Запрос #18418 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 138 спецификаций. Всего: 1849489
🔄 Запрос #18419 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 1849612
🔄 Запрос #18420 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 1849737
🔄 Запрос #18421 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 136 спецификаций. Всего: 1849873
🔄 Запрос #18422 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 131 спецификаций. Всего: 1850004
📤 Сохранено 10077 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #18423 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 1850117
🔄 Запрос #18424 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1850232
🔄 Запрос #18425 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 121 спецификаций. Всего: 1850353
🔄 Запрос #18426 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1850471
🔄 Запрос #18427 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 1850597
🔄 Запрос #18428 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 1850707
🔄 Запрос #18429 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1850825
🔄 Запрос #18430 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1850933
🔄 Запрос #18431 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1851041
🔄 Запрос #18432 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1851149
🔄 Запрос #18433 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 1851270
🔄 Запрос #18434 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 3/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
Сервер недоступен. Ожидаем восстановления связи...
Проблема с запросом — повторяем диапазон.
Диапазон не завершен, повторяем через 30 секунд...
📅 Обрабатываем диапазон 2024-02-01 20:44:09 - 2024-02-08 20:44:09 (попытка 2/5)
🔄 Запрос #18435 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 84 спецификаций. Всего: 1851354
🔄 Запрос #18436 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1851470
🔄 Запрос #18437 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1851578
🔄 Запрос #18438 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 146 спецификаций. Всего: 1851724
🔄 Запрос #18439 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 127 спецификаций. Всего: 1851851
🔄 Запрос #18440 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 128 спецификаций. Всего: 1851979
🔄 Запрос #18441 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1852091
🔄 Запрос #18442 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1852199
🔄 Запрос #18443 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 109 спецификаций. Всего: 1852308
🔄 Запрос #18444 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 121 спецификаций. Всего: 1852429
🔄 Запрос #18445 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 1852562
🔄 Запрос #18446 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 1852687
🔄 Запрос #18447 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 1852811
🔄 Запрос #18448 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09

📥 Загружено 133 спецификаций. Всего: 1852944
🔄 Запрос #18449 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 135 спецификаций. Всего: 1853079
🔄 Запрос #18450 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 144 спецификаций. Всего: 1853223
🔄 Запрос #18451 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 1853356
🔄 Запрос #18452 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1853481
🔄 Запрос #18453 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 133 спецификаций. Всего: 1853614
🔄 Запрос #18454 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 129 спецификаций. Всего: 1853743
🔄 Запрос #18455 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 117 спецификаций. Всего: 1853860
🔄 Запрос #18456 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 141 спецификаций. Всего: 1854001
🔄 Запрос #18457 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 131 спецификаций. Всего: 1854132
🔄 Запрос #18458 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 122 спецификаций. Всего: 1854254
🔄 Запрос #18459 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 70 спецификаций. Всего: 1854324
🔄 Запрос #18460 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 95 спецификаций. Всего: 1854419
🔄 Запрос #18461 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 108 спецификаций. Всего: 1854527
🔄 Запрос #18462 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 123 спецификаций. Всего: 1854650
🔄 Запрос #18463 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 122 спецификаций. Всего: 1854772
🔄 Запрос #18464 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 1854897
🔄 Запрос #18465 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 128 спецификаций. Всего: 1855025
🔄 Запрос #18466 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 107 спецификаций. Всего: 1855132
🔄 Запрос #18467 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 4 спецификаций. Всего: 1855136
🔄 Запрос #18468 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 20 спецификаций. Всего: 1855156
🔄 Запрос #18469 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 112 спецификаций. Всего: 1855268
🔄 Запрос #18470 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 103 спецификаций. Всего: 1855371
🔄 Запрос #18471 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 1855476
🔄 Запрос #18472 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1855592
🔄 Запрос #18473 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 118 спецификаций. Всего: 1855710
🔄 Запрос #18474 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 131 спецификаций. Всего: 1855841
🔄 Запрос #18475 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 129 спецификаций. Всего: 1855970
🔄 Запрос #18476 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 130 спецификаций. Всего: 1856100
🔄 Запрос #18477 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 132 спецификаций. Всего: 1856232
🔄 Запрос #18478 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 115 спецификаций. Всего: 1856347
🔄 Запрос #18479 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 1856472
🔄 Запрос #18480 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 110 спецификаций. Всего: 1856582
🔄 Запрос #18481 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 124 спецификаций. Всего: 1856706
🔄 Запрос #18482 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 128 спецификаций. Всего: 1856834
🔄 Запрос #18483 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 93 спецификаций. Всего: 1856927
🔄 Запрос #18484 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1857038
🔄 Запрос #18485 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 80 спецификаций. Всего: 1857118
🔄 Запрос #18486 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 76 спецификаций. Всего: 1857194
🔄 Запрос #18487 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 0 спецификаций. Всего: 1857194
🔄 Запрос #18488 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 0 спецификаций. Всего: 1857194
🔄 Запрос #18489 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 0 спецификаций. Всего: 1857194
🔄 Запрос #18490 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 0 спецификаций. Всего: 1857194
🔄 Запрос #18491 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 25 спецификаций. Всего: 1857219
🔄 Запрос #18492 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 50 спецификаций. Всего: 1857269
🔄 Запрос #18493 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 166 спецификаций. Всего: 1857435
🔄 Запрос #18494 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 142 спецификаций. Всего: 1857577
🔄 Запрос #18495 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1857695
🔄 Запрос #18496 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 126 спецификаций. Всего: 1857821
🔄 Запрос #18497 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 116 спецификаций. Всего: 1857937
🔄 Запрос #18498 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 1858059
🔄 Запрос #18499 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 105 спецификаций. Всего: 1858164
🔄 Запрос #18500 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 125 спецификаций. Всего: 1858289
🔄 Запрос #18501 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 118 спецификаций. Всего: 1858407
🔄 Запрос #18502 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 113 спецификаций. Всего: 1858520
🔄 Запрос #18503 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 145 спецификаций. Всего: 1858665
🔄 Запрос #18504 для 2024-02-01 20:44:09 - 2024-02-08 20:44:09
📥 Загружено 49 спецификаций. Всего: 1858714
📅 Обрабатываем диапазон 2024-01-25 20:44:09 - 2024-02-01 20:44:09 (попытка 1/5)
🔄 Запрос #18505 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 164 спецификаций. Всего: 1858878
🔄 Запрос #18506 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 134 спецификаций. Всего: 1859012
🔄 Запрос #18507 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 131 спецификаций. Всего: 1859143
🔄 Запрос #18508 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 123 спецификаций. Всего: 1859266
🔄 Запрос #18509 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 153 спецификаций. Всего: 1859419
🔄 Запрос #18510 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 132 спецификаций. Всего: 1859551
🔄 Запрос #18511 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 107 спецификаций. Всего: 1859658
🔄 Запрос #18512 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 141 спецификаций. Всего: 1859799
🔄 Запрос #18513 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 142 спецификаций. Всего: 1859941
🔄 Запрос #18514 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 122 спецификаций. Всего: 1860063
📤 Сохранено 10059 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #18515 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 137 спецификаций. Всего: 1860200

🔄 Запрос #18516 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 110 спецификаций. Всего: 1860310
🔄 Запрос #18517 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 133 спецификаций. Всего: 1860443
🔄 Запрос #18518 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 122 спецификаций. Всего: 1860565
🔄 Запрос #18519 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 123 спецификаций. Всего: 1860688
🔄 Запрос #18520 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1860803
🔄 Запрос #18521 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 129 спецификаций. Всего: 1860932
🔄 Запрос #18522 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 124 спецификаций. Всего: 1861056
🔄 Запрос #18523 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 114 спецификаций. Всего: 1861170
🔄 Запрос #18524 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 114 спецификаций. Всего: 1861284
🔄 Запрос #18525 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 113 спецификаций. Всего: 1861397
🔄 Запрос #18526 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 114 спецификаций. Всего: 1861511
🔄 Запрос #18527 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 113 спецификаций. Всего: 1861624
🔄 Запрос #18528 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 129 спецификаций. Всего: 1861753
🔄 Запрос #18529 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 106 спецификаций. Всего: 1861859
🔄 Запрос #18530 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 79 спецификаций. Всего: 1861938
🔄 Запрос #18531 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 110 спецификаций. Всего: 1862048
🔄 Запрос #18532 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 1862151
🔄 Запрос #18533 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1862256
🔄 Запрос #18534 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 90 спецификаций. Всего: 1862346
🔄 Запрос #18535 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 117 спецификаций. Всего: 1862463
🔄 Запрос #18536 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 113 спецификаций. Всего: 1862576
🔄 Запрос #18537 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 1862709
🔄 Запрос #18538 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 120 спецификаций. Всего: 1862829
🔄 Запрос #18539 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 118 спецификаций. Всего: 1862947
🔄 Запрос #18540 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1863075
🔄 Запрос #18541 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 116 спецификаций. Всего: 1863191
🔄 Запрос #18542 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 124 спецификаций. Всего: 1863315
🔄 Запрос #18543 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 131 спецификаций. Всего: 1863446
🔄 Запрос #18544 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 1863557
🔄 Запрос #18545 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 1863655
🔄 Запрос #18546 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 124 спецификаций. Всего: 1863779
🔄 Запрос #18547 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1863884
🔄 Запрос #18548 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 120 спецификаций. Всего: 1864004
🔄 Запрос #18549 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1864118
🔄 Запрос #18550 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 1864230
🔄 Запрос #18551 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 1864341
🔄 Запрос #18552 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 1864444
🔄 Запрос #18553 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1864559
🔄 Запрос #18554 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 110 спецификаций. Всего: 1864669
🔄 Запрос #18555 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1864784
🔄 Запрос #18556 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 21 спецификаций. Всего: 1864805
🔄 Запрос #18557 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 11 спецификаций. Всего: 1864816
🔄 Запрос #18558 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 55 спецификаций. Всего: 1864871
🔄 Запрос #18559 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 26 спецификаций. Всего: 1864897
🔄 Запрос #18560 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 106 спецификаций. Всего: 1865003
🔄 Запрос #18561 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 91 спецификаций. Всего: 1865094
🔄 Запрос #18562 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 86 спецификаций. Всего: 1865180
🔄 Запрос #18563 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 73 спецификаций. Всего: 1865253
🔄 Запрос #18564 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 96 спецификаций. Всего: 1865349
🔄 Запрос #18565 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 3/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
Сервер недоступен. Ожидаем восстановления связи...
Проблема с запросом — повторяем диапазон.
Диапазон не завершен, повторяем через 30 секунд...
📅 Обрабатываем диапазон 2024-01-25 20:44:09 - 2024-02-01 20:44:09 (попытка 2/5)
🔄 Запрос #18566 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 1865457
🔄 Запрос #18567 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 130 спецификаций. Всего: 1865587
🔄 Запрос #18568 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 130 спецификаций. Всего: 1865717
🔄 Запрос #18569 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 139 спецификаций. Всего: 1865856
🔄 Запрос #18570 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 117 спецификаций. Всего: 1865973
🔄 Запрос #18571 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 118 спецификаций. Всего: 1866091
🔄 Запрос #18572 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1866206
🔄 Запрос #18573 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 27 спецификаций. Всего: 1866233
🔄 Запрос #18574 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 91 спецификаций. Всего: 1866324
🔄 Запрос #18575 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 110 спецификаций. Всего: 1866434
🔄 Запрос #18576 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 121 спецификаций. Всего: 1866555
🔄 Запрос #18577 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 152 спецификаций. Всего: 1866707
🔄 Запрос #18578 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 139 спецификаций. Всего: 1866846
🔄 Запрос #18579 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 134 спецификаций. Всего: 1866980
🔄 Запрос #18580 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 147 спецификаций. Всего: 1867127
🔄 Запрос #18581 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1867246
🔄 Запрос #18582 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 139 спецификаций. Всего: 1867385
🔄 Запрос #18583 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 133 спецификаций. Всего: 1867518
🔄 Запрос #18584 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 140 спецификаций. Всего: 1867658
🔄 Запрос #18585 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 118 спецификаций. Всего: 1867776
🔄 Запрос #18586 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 123 спецификаций. Всего: 1867899
🔄 Запрос #18587 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 143 спецификаций. Всего: 1868042
🔄 Запрос #18588 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 138 спецификаций. Всего: 1868180
🔄 Запрос #18589 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 156 спецификаций. Всего: 1868336
🔄 Запрос #18590 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 152 спецификаций. Всего: 1868488
🔄 Запрос #18591 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 1868599
🔄 Запрос #18592 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 145 спецификаций. Всего: 1868744
🔄 Запрос #18593 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 134 спецификаций. Всего: 1868878
🔄 Запрос #18594 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 128 спецификаций. Всего: 1869006
🔄 Запрос #18595 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 135 спецификаций. Всего: 1869141
🔄 Запрос #18596 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 127 спецификаций. Всего: 1869268
🔄 Запрос #18597 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 1869363
🔄 Запрос #18598 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 1869471
🔄 Запрос #18599 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 1869586
🔄 Запрос #18600 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 120 спецификаций. Всего: 1869706
🔄 Запрос #18601 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 123 спецификаций. Всего: 1869829
🔄 Запрос #18602 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 69 спецификаций. Всего: 1869898
🔄 Запрос #18603 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 123 спецификаций. Всего: 1870021
🔄 Запрос #18604 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1870139
📤 Сохранено 10076 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #18605 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 99 спецификаций. Всего: 1870238
🔄 Запрос #18606 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 1870340
🔄 Запрос #18607 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 87 спецификаций. Всего: 1870427
🔄 Запрос #18608 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1870537
🔄 Запрос #18609 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 15 спецификаций. Всего: 1870552
🔄 Запрос #18610 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 0 спецификаций. Всего: 1870552
🔄 Запрос #18611 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 0 спецификаций. Всего: 1870552
🔄 Запрос #18612 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 0 спецификаций. Всего: 1870552
🔄 Запрос #18613 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 1 спецификаций. Всего: 1870553
🔄 Запрос #18614 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 2 спецификаций. Всего: 1870555
🔄 Запрос #18615 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 1870658
🔄 Запрос #18616 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 117 спецификаций. Всего: 1870775
🔄 Запрос #18617 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 174 спецификаций. Всего: 1870949
🔄 Запрос #18618 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 78 спецификаций. Всего: 1871027
🔄 Запрос #18619 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 1 спецификаций. Всего: 1871028
🔄 Запрос #18620 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1871126
🔄 Запрос #18621 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 148 спецификаций. Всего: 1871274
🔄 Запрос #18622 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 125 спецификаций. Всего: 1871399
🔄 Запрос #18623 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 110 спецификаций. Всего: 1871509
🔄 Запрос #18624 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 1871611
🔄 Запрос #18625 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 1871732
🔄 Запрос #18626 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 57 спецификаций. Всего: 1871789
🔄 Запрос #18627 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 35 спецификаций. Всего: 1871824
🔄 Запрос #18628 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 92 спецификаций. Всего: 1871916
🔄 Запрос #18629 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 82 спецификаций. Всего: 1871998
🔄 Запрос #18630 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 101 спецификаций. Всего: 1872099
🔄 Запрос #18631 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 99 спецификаций. Всего: 1872198
🔄 Запрос #18632 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1872312
🔄 Запрос #18633 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1872418
🔄 Запрос #18634 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 109 спецификаций. Всего: 1872527
🔄 Запрос #18635 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 1872647
🔄 Запрос #18636 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 1872750
🔄 Запрос #18637 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 96 спецификаций. Всего: 1872846
🔄 Запрос #18638 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 94 спецификаций. Всего: 1872940

🔄 Запрос #18639 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 1873035
🔄 Запрос #18640 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 1873138
🔄 Запрос #18641 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 81 спецификаций. Всего: 1873219
🔄 Запрос #18642 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 91 спецификаций. Всего: 1873310
🔄 Запрос #18643 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 94 спецификаций. Всего: 1873404
🔄 Запрос #18644 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 79 спецификаций. Всего: 1873483
🔄 Запрос #18645 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 77 спецификаций. Всего: 1873560
🔄 Запрос #18646 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 91 спецификаций. Всего: 1873651
🔄 Запрос #18647 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 100 спецификаций. Всего: 1873751
🔄 Запрос #18648 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 87 спецификаций. Всего: 1873838
🔄 Запрос #18649 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 79 спецификаций. Всего: 1873917
🔄 Запрос #18650 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 88 спецификаций. Всего: 1874005
🔄 Запрос #18651 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 83 спецификаций. Всего: 1874088
🔄 Запрос #18652 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 1874183
🔄 Запрос #18653 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 1874285
🔄 Запрос #18654 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 64 спецификаций. Всего: 1874349
🔄 Запрос #18655 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 80 спецификаций. Всего: 1874429
🔄 Запрос #18656 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 90 спецификаций. Всего: 1874519
🔄 Запрос #18657 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 53 спецификаций. Всего: 1874572
🔄 Запрос #18658 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 86 спецификаций. Всего: 1874658
🔄 Запрос #18659 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 71 спецификаций. Всего: 1874729
🔄 Запрос #18660 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 38 спецификаций. Всего: 1874767
🔄 Запрос #18661 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 77 спецификаций. Всего: 1874844
🔄 Запрос #18662 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 1874956
🔄 Запрос #18663 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 1875060
🔄 Запрос #18664 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 76 спецификаций. Всего: 1875136
🔄 Запрос #18665 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 101 спецификаций. Всего: 1875237
🔄 Запрос #18666 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 110 спецификаций. Всего: 1875347
🔄 Запрос #18667 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 49 спецификаций. Всего: 1875396
🔄 Запрос #18668 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1875511
🔄 Запрос #18669 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 123 спецификаций. Всего: 1875634
🔄 Запрос #18670 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1875749
🔄 Запрос #18671 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 113 спецификаций. Всего: 1875862
🔄 Запрос #18672 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 1875973
🔄 Запрос #18673 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 1876076
🔄 Запрос #18674 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 101 спецификаций. Всего: 1876177
🔄 Запрос #18675 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 1876281
🔄 Запрос #18676 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 59 спецификаций. Всего: 1876340
🔄 Запрос #18677 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 107 спецификаций. Всего: 1876447
🔄 Запрос #18678 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 28 спецификаций. Всего: 1876475
🔄 Запрос #18679 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 86 спецификаций. Всего: 1876561
🔄 Запрос #18680 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 80 спецификаций. Всего: 1876641
🔄 Запрос #18681 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 94 спецификаций. Всего: 1876735
🔄 Запрос #18682 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 106 спецификаций. Всего: 1876841
🔄 Запрос #18683 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 1876953
🔄 Запрос #18684 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 76 спецификаций. Всего: 1877029
🔄 Запрос #18685 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 105 спецификаций. Всего: 1877134
🔄 Запрос #18686 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 100 спецификаций. Всего: 1877234
🔄 Запрос #18687 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 76 спецификаций. Всего: 1877310
🔄 Запрос #18688 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 89 спецификаций. Всего: 1877399
🔄 Запрос #18689 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 119 спецификаций. Всего: 1877518
🔄 Запрос #18690 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 84 спецификаций. Всего: 1877602
🔄 Запрос #18691 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 56 спецификаций. Всего: 1877658
🔄 Запрос #18692 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 64 спецификаций. Всего: 1877722
🔄 Запрос #18693 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 202 спецификаций. Всего: 1877924
🔄 Запрос #18694 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 125 спецификаций. Всего: 1878049
🔄 Запрос #18695 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 89 спецификаций. Всего: 1878138
🔄 Запрос #18696 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 137 спецификаций. Всего: 1878275
🔄 Запрос #18697 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 126 спецификаций. Всего: 1878401
🔄 Запрос #18698 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 99 спецификаций. Всего: 1878500
🔄 Запрос #18699 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 87 спецификаций. Всего: 1878587
🔄 Запрос #18700 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 46 спецификаций. Всего: 1878633
🔄 Запрос #18701 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 63 спецификаций. Всего: 1878696
🔄 Запрос #18702 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 91 спецификаций. Всего: 1878787
🔄 Запрос #18703 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 105 спецификаций. Всего: 1878892
🔄 Запрос #18704 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 1878987
🔄 Запрос #18705 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1879103
🔄 Запрос #18706 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 89 спецификаций. Всего: 1879192
🔄 Запрос #18707 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 1879300
🔄 Запрос #18708 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 96 спецификаций. Всего: 1879396
🔄 Запрос #18709 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 93 спецификаций. Всего: 1879489
🔄 Запрос #18710 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 75 спецификаций. Всего: 1879564
🔄 Запрос #18711 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 91 спецификаций. Всего: 1879655

🔄 Запрос #18712 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1879770
🔄 Запрос #18713 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 1879873
🔄 Запрос #18714 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 101 спецификаций. Всего: 1879974
🔄 Запрос #18715 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 83 спецификаций. Всего: 1880057
🔄 Запрос #18716 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 75 спецификаций. Всего: 1880132
🔄 Запрос #18717 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 87 спецификаций. Всего: 1880219
📤 Сохранено 10080 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #18718 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 83 спецификаций. Всего: 1880302
🔄 Запрос #18719 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 1880400
🔄 Запрос #18720 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 76 спецификаций. Всего: 1880476
🔄 Запрос #18721 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1880574
🔄 Запрос #18722 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 1880682
🔄 Запрос #18723 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 81 спецификаций. Всего: 1880763
🔄 Запрос #18724 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 85 спецификаций. Всего: 1880848
🔄 Запрос #18725 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 74 спецификаций. Всего: 1880922
🔄 Запрос #18726 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 75 спецификаций. Всего: 1880997
🔄 Запрос #18727 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 72 спецификаций. Всего: 1881069
🔄 Запрос #18728 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 74 спецификаций. Всего: 1881143
🔄 Запрос #18729 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 72 спецификаций. Всего: 1881215
🔄 Запрос #18730 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 87 спецификаций. Всего: 1881302
🔄 Запрос #18731 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 79 спецификаций. Всего: 1881381
🔄 Запрос #18732 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 62 спецификаций. Всего: 1881443
🔄 Запрос #18733 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 82 спецификаций. Всего: 1881525
🔄 Запрос #18734 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 86 спецификаций. Всего: 1881611
🔄 Запрос #18735 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 81 спецификаций. Всего: 1881692
🔄 Запрос #18736 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 77 спецификаций. Всего: 1881769
🔄 Запрос #18737 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 77 спецификаций. Всего: 1881846
🔄 Запрос #18738 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 1881932
🔄 Запрос #18739 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 73 спецификаций. Всего: 1882005
🔄 Запрос #18740 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 58 спецификаций. Всего: 1882063
🔄 Запрос #18741 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 82 спецификаций. Всего: 1882145
🔄 Запрос #18742 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 84 спецификаций. Всего: 1882229
🔄 Запрос #18743 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 1882333
🔄 Запрос #18744 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 89 спецификаций. Всего: 1882422
🔄 Запрос #18745 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 67 спецификаций. Всего: 1882489
🔄 Запрос #18746 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 1882591
🔄 Запрос #18747 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 94 спецификаций. Всего: 1882685
🔄 Запрос #18748 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 90 спецификаций. Всего: 1882775
🔄 Запрос #18749 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 1882870
🔄 Запрос #18750 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 119 спецификаций. Всего: 1882989
🔄 Запрос #18751 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 74 спецификаций. Всего: 1883063
🔄 Запрос #18752 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 1883167
🔄 Запрос #18753 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 1883275
🔄 Запрос #18754 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 1883387
🔄 Запрос #18755 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 124 спецификаций. Всего: 1883511
🔄 Запрос #18756 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 109 спецификаций. Всего: 1883620
🔄 Запрос #18757 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 1883724
🔄 Запрос #18758 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 1883835
🔄 Запрос #18759 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 101 спецификаций. Всего: 1883936
🔄 Запрос #18760 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 1884047
🔄 Запрос #18761 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1884138
🔄 Запрос #18762 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1884234
🔄 Запрос #18763 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 113 спецификаций. Всего: 1884347
🔄 Запрос #18764 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 88 спецификаций. Всего: 1884435
🔄 Запрос #18765 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 92 спецификаций. Всего: 1884527
🔄 Запрос #18766 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 87 спецификаций. Всего: 1884614
🔄 Запрос #18767 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 107 спецификаций. Всего: 1884721
🔄 Запрос #18768 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 76 спецификаций. Всего: 1884797
🔄 Запрос #18769 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 62 спецификаций. Всего: 1884859
🔄 Запрос #18770 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 33 спецификаций. Всего: 1884892
🔄 Запрос #18771 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 154 спецификаций. Всего: 1885046
🔄 Запрос #18772 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 130 спецификаций. Всего: 1885176
🔄 Запрос #18773 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 1885280
🔄 Запрос #18774 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 128 спецификаций. Всего: 1885408
🔄 Запрос #18775 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 165 спецификаций. Всего: 1885573
🔄 Запрос #18776 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 107 спецификаций. Всего: 1885680
🔄 Запрос #18777 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09

📥 Загружено 82 спецификаций. Всего: 1885762
🔄 Запрос #18778 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 68 спецификаций. Всего: 1885830
🔄 Запрос #18779 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 77 спецификаций. Всего: 1885907
🔄 Запрос #18780 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 120 спецификаций. Всего: 1886027
🔄 Запрос #18781 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 132 спецификаций. Всего: 1886159
🔄 Запрос #18782 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 159 спецификаций. Всего: 1886318
🔄 Запрос #18783 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1886444
🔄 Запрос #18784 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 134 спецификаций. Всего: 1886578
🔄 Запрос #18785 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 134 спецификаций. Всего: 1886712
🔄 Запрос #18786 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 121 спецификаций. Всего: 1886833
🔄 Запрос #18787 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 127 спецификаций. Всего: 1886960
🔄 Запрос #18788 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 1887072
🔄 Запрос #18789 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 114 спецификаций. Всего: 1887186
🔄 Запрос #18790 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 105 спецификаций. Всего: 1887291
🔄 Запрос #18791 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 126 спецификаций. Всего: 1887417
🔄 Запрос #18792 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 1887529
🔄 Запрос #18793 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 109 спецификаций. Всего: 1887638
🔄 Запрос #18794 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 94 спецификаций. Всего: 1887732
🔄 Запрос #18795 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 69 спецификаций. Всего: 1887801
🔄 Запрос #18796 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 70 спецификаций. Всего: 1887871
🔄 Запрос #18797 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 81 спецификаций. Всего: 1887952
🔄 Запрос #18798 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 67 спецификаций. Всего: 1888019
🔄 Запрос #18799 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1888126
🔄 Запрос #18800 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 1888238
🔄 Запрос #18801 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 146 спецификаций. Всего: 1888384
🔄 Запрос #18802 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 66 спецификаций. Всего: 1888450
🔄 Запрос #18803 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 94 спецификаций. Всего: 1888544
🔄 Запрос #18804 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 100 спецификаций. Всего: 1888644
🔄 Запрос #18805 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 1888747
🔄 Запрос #18806 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 86 спецификаций. Всего: 1888833
🔄 Запрос #18807 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 1888937
🔄 Запрос #18808 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 81 спецификаций. Всего: 1889018
🔄 Запрос #18809 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 92 спецификаций. Всего: 1889110
🔄 Запрос #18810 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 96 спецификаций. Всего: 1889206
🔄 Запрос #18811 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1889294
🔄 Запрос #18812 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 99 спецификаций. Всего: 1889393
🔄 Запрос #18813 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 1889491
🔄 Запрос #18814 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 105 спецификаций. Всего: 1889596
🔄 Запрос #18815 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 88 спецификаций. Всего: 1889684
🔄 Запрос #18816 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 75 спецификаций. Всего: 1889759
🔄 Запрос #18817 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 88 спецификаций. Всего: 1889847
🔄 Запрос #18818 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 73 спецификаций. Всего: 1889920
🔄 Запрос #18819 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1890035
🔄 Запрос #18820 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1890131
🔄 Запрос #18821 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 119 спецификаций. Всего: 1890250
📤 Сохранено 10031 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #18822 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 118 спецификаций. Всего: 1890368
🔄 Запрос #18823 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 107 спецификаций. Всего: 1890475
🔄 Запрос #18824 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 126 спецификаций. Всего: 1890601
🔄 Запрос #18825 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 123 спецификаций. Всего: 1890724
🔄 Запрос #18826 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 108 спецификаций. Всего: 1890832
🔄 Запрос #18827 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 109 спецификаций. Всего: 1890941
🔄 Запрос #18828 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1891056
🔄 Запрос #18829 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1891182
🔄 Запрос #18830 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 121 спецификаций. Всего: 1891303
🔄 Запрос #18831 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 1891414
🔄 Запрос #18832 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 101 спецификаций. Всего: 1891515
🔄 Запрос #18833 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 1891619
🔄 Запрос #18834 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 1891730
🔄 Запрос #18835 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1891835
🔄 Запрос #18836 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 105 спецификаций. Всего: 1891940
🔄 Запрос #18837 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 123 спецификаций. Всего: 1892063
🔄 Запрос #18838 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 100 спецификаций. Всего: 1892163
🔄 Запрос #18839 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 1892267
🔄 Запрос #18840 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 3/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
Сервер недоступен. Ожидаем восстановления связи...
Проблема с запросом — повторяем диапазон.
Диапазон не завершен, повторяем через 30 секунд...

📅 Обрабатываем диапазон 2024-01-25 20:44:09 - 2024-02-01 20:44:09 (попытка 3/5)
🔄 Запрос #18841 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 110 спецификаций. Всего: 1892377
🔄 Запрос #18842 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 84 спецификаций. Всего: 1892461
🔄 Запрос #18843 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 97 спецификаций. Всего: 1892558
🔄 Запрос #18844 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 112 спецификаций. Всего: 1892670
🔄 Запрос #18845 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 122 спецификаций. Всего: 1892792
🔄 Запрос #18846 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 123 спецификаций. Всего: 1892915
🔄 Запрос #18847 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1893033
🔄 Запрос #18848 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 1893119
🔄 Запрос #18849 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 72 спецификаций. Всего: 1893191
🔄 Запрос #18850 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 88 спецификаций. Всего: 1893279
🔄 Запрос #18851 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 120 спецификаций. Всего: 1893399
🔄 Запрос #18852 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 99 спецификаций. Всего: 1893498
🔄 Запрос #18853 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 47 спецификаций. Всего: 1893545
🔄 Запрос #18854 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 81 спецификаций. Всего: 1893626
🔄 Запрос #18855 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1893731
🔄 Запрос #18856 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 148 спецификаций. Всего: 1893879
🔄 Запрос #18857 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 148 спецификаций. Всего: 1894027
🔄 Запрос #18858 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 107 спецификаций. Всего: 1894134
🔄 Запрос #18859 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 84 спецификаций. Всего: 1894218
🔄 Запрос #18860 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 69 спецификаций. Всего: 1894287
🔄 Запрос #18861 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 70 спецификаций. Всего: 1894357
🔄 Запрос #18862 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 92 спецификаций. Всего: 1894449
🔄 Запрос #18863 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 119 спецификаций. Всего: 1894568
🔄 Запрос #18864 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 92 спецификаций. Всего: 1894660
🔄 Запрос #18865 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 68 спецификаций. Всего: 1894728
🔄 Запрос #18866 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 54 спецификаций. Всего: 1894782
🔄 Запрос #18867 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 155 спецификаций. Всего: 1894937
🔄 Запрос #18868 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 129 спецификаций. Всего: 1895066
🔄 Запрос #18869 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 109 спецификаций. Всего: 1895175
🔄 Запрос #18870 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1895280
🔄 Запрос #18871 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 89 спецификаций. Всего: 1895369
🔄 Запрос #18872 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 132 спецификаций. Всего: 1895501
🔄 Запрос #18873 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 139 спецификаций. Всего: 1895640
🔄 Запрос #18874 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 65 спецификаций. Всего: 1895705
🔄 Запрос #18875 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 85 спецификаций. Всего: 1895790
🔄 Запрос #18876 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 90 спецификаций. Всего: 1895880
🔄 Запрос #18877 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 116 спецификаций. Всего: 1895996
🔄 Запрос #18878 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1896111
🔄 Запрос #18879 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 106 спецификаций. Всего: 1896217
🔄 Запрос #18880 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 92 спецификаций. Всего: 1896309
🔄 Запрос #18881 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 123 спецификаций. Всего: 1896432
🔄 Запрос #18882 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 1896530
🔄 Запрос #18883 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 130 спецификаций. Всего: 1896660
🔄 Запрос #18884 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 1896771
🔄 Запрос #18885 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 144 спецификаций. Всего: 1896915
🔄 Запрос #18886 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 139 спецификаций. Всего: 1897054
🔄 Запрос #18887 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 122 спецификаций. Всего: 1897176
🔄 Запрос #18888 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 1897274
🔄 Запрос #18889 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 1897407
🔄 Запрос #18890 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 121 спецификаций. Всего: 1897528
🔄 Запрос #18891 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 1897623
🔄 Запрос #18892 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 125 спецификаций. Всего: 1897748
🔄 Запрос #18893 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 133 спецификаций. Всего: 1897881
🔄 Запрос #18894 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 65 спецификаций. Всего: 1897946
🔄 Запрос #18895 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 124 спецификаций. Всего: 1898070
🔄 Запрос #18896 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 130 спецификаций. Всего: 1898200
🔄 Запрос #18897 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 114 спецификаций. Всего: 1898314
🔄 Запрос #18898 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1898429
🔄 Запрос #18899 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 119 спецификаций. Всего: 1898548
🔄 Запрос #18900 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 1898652
🔄 Запрос #18901 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 1898754
🔄 Запрос #18902 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 89 спецификаций. Всего: 1898843
🔄 Запрос #18903 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 119 спецификаций. Всего: 1898962
🔄 Запрос #18904 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 109 спецификаций. Всего: 1899071
🔄 Запрос #18905 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 1899174
🔄 Запрос #18906 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 91 спецификаций. Всего: 1899265
🔄 Запрос #18907 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 1899358
🔄 Запрос #18908 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 99 спецификаций. Всего: 1899457
🔄 Запрос #18909 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 94 спецификаций. Всего: 1899551
🔄 Запрос #18910 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 101 спецификаций. Всего: 1899652
🔄 Запрос #18911 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 54 спецификаций. Всего: 1899706
🔄 Запрос #18912 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 88 спецификаций. Всего: 1899794
🔄 Запрос #18913 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 1899892
🔄 Запрос #18914 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1900008
🔄 Запрос #18915 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 1900119
🔄 Запрос #18916 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1900234
🔄 Запрос #18917 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 93 спецификаций. Всего: 1900327
📤 Сохранено 10077 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #18918 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 114 спецификаций. Всего: 1900441
🔄 Запрос #18919 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 118 спецификаций. Всего: 1900559
🔄 Запрос #18920 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1900674
🔄 Запрос #18921 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 128 спецификаций. Всего: 1900802
🔄 Запрос #18922 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 102 спецификаций. Всего: 1900904
🔄 Запрос #18923 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 114 спецификаций. Всего: 1901018
🔄 Запрос #18924 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 86 спецификаций. Всего: 1901104
🔄 Запрос #18925 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 99 спецификаций. Всего: 1901203
🔄 Запрос #18926 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 105 спецификаций. Всего: 1901308
🔄 Запрос #18927 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 92 спецификаций. Всего: 1901400
🔄 Запрос #18928 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 107 спецификаций. Всего: 1901507
🔄 Запрос #18929 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 87 спецификаций. Всего: 1901594
🔄 Запрос #18930 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 93 спецификаций. Всего: 1901687
🔄 Запрос #18931 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 103 спецификаций. Всего: 1901790
🔄 Запрос #18932 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 100 спецификаций. Всего: 1901890
🔄 Запрос #18933 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 115 спецификаций. Всего: 1902005
🔄 Запрос #18934 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 95 спецификаций. Всего: 1902100
🔄 Запрос #18935 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 104 спецификаций. Всего: 1902204
🔄 Запрос #18936 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 98 спецификаций. Всего: 1902302
🔄 Запрос #18937 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 1902393
🔄 Запрос #18938 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 96 спецификаций. Всего: 1902489
🔄 Запрос #18939 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1902587
🔄 Запрос #18940 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 72 спецификаций. Всего: 1902659
🔄 Запрос #18941 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 50 спецификаций. Всего: 1902709
🔄 Запрос #18942 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 83 спецификаций. Всего: 1902792
🔄 Запрос #18943 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 3/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
Сервер недоступен. Ожидаем восстановления связи...
Проблема с запросом — повторяем диапазон.
Диапазон не завершен, повторяем через 30 секунд...
📅 Обрабатываем диапазон 2024-01-25 20:44:09 - 2024-02-01 20:44:09 (попытка 4/5)
🔄 Запрос #18944 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 118 спецификаций. Всего: 1902910
🔄 Запрос #18945 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 45 спецификаций. Всего: 1902955
🔄 Запрос #18946 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 121 спецификаций. Всего: 1903076
🔄 Запрос #18947 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 109 спецификаций. Всего: 1903185
🔄 Запрос #18948 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 73 спецификаций. Всего: 1903258
🔄 Запрос #18949 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 111 спецификаций. Всего: 1903369
🔄 Запрос #18950 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 126 спецификаций. Всего: 1903495
🔄 Запрос #18951 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 134 спецификаций. Всего: 1903629
🔄 Запрос #18952 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1903734
🔄 Запрос #18953 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 97 спецификаций. Всего: 1903831
🔄 Запрос #18954 для 2024-01-25 20:44:09 - 2024-02-01 20:44:09
📥 Загружено 0 спецификаций. Всего: 1903831
📅 Обрабатываем диапазон 2024-01-18 20:44:09 - 2024-01-25 20:44:09 (попытка 1/5)
🔄 Запрос #18955 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1903957
🔄 Запрос #18956 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1904071
🔄 Запрос #18957 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1904193
🔄 Запрос #18958 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1904304
🔄 Запрос #18959 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1904412
🔄 Запрос #18960 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1904515
🔄 Запрос #18961 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 83 спецификаций. Всего: 1904598
🔄 Запрос #18962 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1904712
🔄 Запрос #18963 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 128 спецификаций. Всего: 1904840
🔄 Запрос #18964 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 1904964
🔄 Запрос #18965 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1905071

🔄 Запрос #18966 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1905179
🔄 Запрос #18967 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1905301
🔄 Запрос #18968 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1905413
🔄 Запрос #18969 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1905529
🔄 Запрос #18970 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1905637
🔄 Запрос #18971 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1905750
🔄 Запрос #18972 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1905836
🔄 Запрос #18973 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 138 спецификаций. Всего: 1905974
🔄 Запрос #18974 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 127 спецификаций. Всего: 1906101
🔄 Запрос #18975 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 87 спецификаций. Всего: 1906188
🔄 Запрос #18976 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1906292
🔄 Запрос #18977 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 80 спецификаций. Всего: 1906372
🔄 Запрос #18978 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1906483
🔄 Запрос #18979 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1906597
🔄 Запрос #18980 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1906706
🔄 Запрос #18981 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1906822
🔄 Запрос #18982 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1906926
🔄 Запрос #18983 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1907023
🔄 Запрос #18984 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 93 спецификаций. Всего: 1907116
🔄 Запрос #18985 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 93 спецификаций. Всего: 1907209
🔄 Запрос #18986 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 1907300
🔄 Запрос #18987 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1907389
🔄 Запрос #18988 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 1907485
🔄 Запрос #18989 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1907596
🔄 Запрос #18990 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1907684
🔄 Запрос #18991 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 77 спецификаций. Всего: 1907761
🔄 Запрос #18992 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 74 спецификаций. Всего: 1907835
🔄 Запрос #18993 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 67 спецификаций. Всего: 1907902
🔄 Запрос #18994 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 75 спецификаций. Всего: 1907977
🔄 Запрос #18995 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1908067
🔄 Запрос #18996 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Max retries exceeded with url: /v3/graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026BAEE33E90>, 'Connection to ows.goszakup.gov.kz timed out. (connect timeout=15)'))
📥 Загружено 110 спецификаций. Всего: 1908177
🔄 Запрос #18997 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1908290
🔄 Запрос #18998 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1908378
🔄 Запрос #18999 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1908486
🔄 Запрос #19000 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 76 спецификаций. Всего: 1908562
🔄 Запрос #19001 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1908648
🔄 Запрос #19002 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1908738
🔄 Запрос #19003 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 1908829
🔄 Запрос #19004 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1908923
🔄 Запрос #19005 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1909031
🔄 Запрос #19006 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1909130
🔄 Запрос #19007 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 130 спецификаций. Всего: 1909260
🔄 Запрос #19008 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 1909348
🔄 Запрос #19009 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 1909469
🔄 Запрос #19010 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1909568
🔄 Запрос #19011 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1909681
🔄 Запрос #19012 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1909787
🔄 Запрос #19013 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1909900
🔄 Запрос #19014 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1910008
🔄 Запрос #19015 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1910102
🔄 Запрос #19016 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1910221
🔄 Запрос #19017 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1910338
📤 Сохранено 10011 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #19018 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 136 спецификаций. Всего: 1910474
🔄 Запрос #19019 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 1910594
🔄 Запрос #19020 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1910691
🔄 Запрос #19021 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1910801
🔄 Запрос #19022 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 73 спецификаций. Всего: 1910874
🔄 Запрос #19023 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 5 спецификаций. Всего: 1910879
🔄 Запрос #19024 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 1 спецификаций. Всего: 1910880
🔄 Запрос #19025 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 4 спецификаций. Всего: 1910884
🔄 Запрос #19026 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1910988
🔄 Запрос #19027 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1911089
🔄 Запрос #19028 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 123 спецификаций. Всего: 1911212
🔄 Запрос #19029 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1911319
🔄 Запрос #19030 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 130 спецификаций. Всего: 1911449
🔄 Запрос #19031 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 137 спецификаций. Всего: 1911586
🔄 Запрос #19032 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1911683
🔄 Запрос #19033 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09

📥 Загружено 126 спецификаций. Всего: 1911809
🔄 Запрос #19034 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 1911933
🔄 Запрос #19035 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 134 спецификаций. Всего: 1912067
🔄 Запрос #19036 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1912172
🔄 Запрос #19037 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1912286
🔄 Запрос #19038 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1912390
🔄 Запрос #19039 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 132 спецификаций. Всего: 1912522
🔄 Запрос #19040 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1912635
🔄 Запрос #19041 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1912736
🔄 Запрос #19042 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1912846
🔄 Запрос #19043 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1912954
🔄 Запрос #19044 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1913058
🔄 Запрос #19045 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1913163
🔄 Запрос #19046 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1913260
🔄 Запрос #19047 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1913366
🔄 Запрос #19048 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 77 спецификаций. Всего: 1913443
🔄 Запрос #19049 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1913551
🔄 Запрос #19050 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1913649
🔄 Запрос #19051 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 65 спецификаций. Всего: 1913714
🔄 Запрос #19052 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1913802
🔄 Запрос #19053 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1913900
🔄 Запрос #19054 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 85 спецификаций. Всего: 1913985
🔄 Запрос #19055 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1914075
🔄 Запрос #19056 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1914184
🔄 Запрос #19057 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1914273
🔄 Запрос #19058 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 1914381
🔄 Запрос #19059 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1914491
🔄 Запрос #19060 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1914581
🔄 Запрос #19061 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1914689
🔄 Запрос #19062 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1914802
🔄 Запрос #19063 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 87 спецификаций. Всего: 1914889
🔄 Запрос #19064 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1914987
🔄 Запрос #19065 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 82 спецификаций. Всего: 1915069
🔄 Запрос #19066 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 81 спецификаций. Всего: 1915150
🔄 Запрос #19067 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1915254
🔄 Запрос #19068 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1915371
🔄 Запрос #19069 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 100 спецификаций. Всего: 1915471
🔄 Запрос #19070 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1915568
🔄 Запрос #19071 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 72 спецификаций. Всего: 1915640
🔄 Запрос #19072 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 95 спецификаций. Всего: 1915735
🔄 Запрос #19073 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1915851
🔄 Запрос #19074 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1915964
🔄 Запрос #19075 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1916075
🔄 Запрос #19076 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1916181
🔄 Запрос #19077 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1916298
🔄 Запрос #19078 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 3/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
Сервер недоступен. Ожидаем восстановления связи...
Проблема с запросом — повторяем диапазон.
Диапазон не завершен, повторяем через 30 секунд...
📅 Обрабатываем диапазон 2024-01-18 20:44:09 - 2024-01-25 20:44:09 (попытка 2/5)
🔄 Запрос #19079 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1916411
🔄 Запрос #19080 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 100 спецификаций. Всего: 1916511
🔄 Запрос #19081 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1916627
🔄 Запрос #19082 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1916731
🔄 Запрос #19083 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1916830
🔄 Запрос #19084 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1916925
🔄 Запрос #19085 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 1917009
🔄 Запрос #19086 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1917095
🔄 Запрос #19087 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1917191
🔄 Запрос #19088 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1917292
🔄 Запрос #19089 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1917410
🔄 Запрос #19090 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1917515
🔄 Запрос #19091 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 81 спецификаций. Всего: 1917596
🔄 Запрос #19092 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 83 спецификаций. Всего: 1917679
🔄 Запрос #19093 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1917765
🔄 Запрос #19094 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1917862
🔄 Запрос #19095 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1917967
🔄 Запрос #19096 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1918083
🔄 Запрос #19097 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 100 спецификаций. Всего: 1918183
🔄 Запрос #19098 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1918288
🔄 Запрос #19099 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 52 спецификаций. Всего: 1918340
🔄 Запрос #19100 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09

📥 Загружено 63 спецификаций. Всего: 1918403
🔄 Запрос #19101 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1918504
🔄 Запрос #19102 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 68 спецификаций. Всего: 1918572
🔄 Запрос #19103 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1918674
🔄 Запрос #19104 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1918780
🔄 Запрос #19105 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 158 спецификаций. Всего: 1918938
🔄 Запрос #19106 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1919055
🔄 Запрос #19107 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 101 спецификаций. Всего: 1919156
🔄 Запрос #19108 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1919273
🔄 Запрос #19109 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1919384
🔄 Запрос #19110 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1919493
🔄 Запрос #19111 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 82 спецификаций. Всего: 1919575
🔄 Запрос #19112 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 69 спецификаций. Всего: 1919644
🔄 Запрос #19113 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 69 спецификаций. Всего: 1919713
🔄 Запрос #19114 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1919809
🔄 Запрос #19115 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1919914
🔄 Запрос #19116 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 94 спецификаций. Всего: 1920008
🔄 Запрос #19117 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1920116
🔄 Запрос #19118 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1920202
🔄 Запрос #19119 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1920314
🔄 Запрос #19120 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 148 спецификаций. Всего: 1920462
📤 Сохранено 10124 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #19121 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1920571
🔄 Запрос #19122 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1920685
🔄 Запрос #19123 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 1920806
🔄 Запрос #19124 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1920923
🔄 Запрос #19125 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1921031
🔄 Запрос #19126 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1921143
🔄 Запрос #19127 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1921255
🔄 Запрос #19128 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1921366
🔄 Запрос #19129 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1921460
🔄 Запрос #19130 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1921564
🔄 Запрос #19131 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 1921669
🔄 Запрос #19132 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1921776
🔄 Запрос #19133 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1921882
🔄 Запрос #19134 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1921989
🔄 Запрос #19135 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1922091
🔄 Запрос #19136 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1922205
🔄 Запрос #19137 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1922313
🔄 Запрос #19138 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1922410
🔄 Запрос #19139 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1922498
🔄 Запрос #19140 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 81 спецификаций. Всего: 1922579
🔄 Запрос #19141 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1922671
🔄 Запрос #19142 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1922769
🔄 Запрос #19143 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1922879
🔄 Запрос #19144 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 1923003
🔄 Запрос #19145 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1923102
🔄 Запрос #19146 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1923211
🔄 Запрос #19147 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1923316
🔄 Запрос #19148 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1923422
🔄 Запрос #19149 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1923508
🔄 Запрос #19150 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1923612
🔄 Запрос #19151 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1923726
🔄 Запрос #19152 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1923834
🔄 Запрос #19153 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 109 спецификаций. Всего: 1923943
🔄 Запрос #19154 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1924045
🔄 Запрос #19155 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1924135
🔄 Запрос #19156 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1924225
🔄 Запрос #19157 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1924327
🔄 Запрос #19158 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 76 спецификаций. Всего: 1924403
🔄 Запрос #19159 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1924492
🔄 Запрос #19160 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1924586
🔄 Запрос #19161 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1924689
🔄 Запрос #19162 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1924783
🔄 Запрос #19163 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 95 спецификаций. Всего: 1924878
🔄 Запрос #19164 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 1924962
🔄 Запрос #19165 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1925052
🔄 Запрос #19166 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 85 спецификаций. Всего: 1925137
🔄 Запрос #19167 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1925234
🔄 Запрос #19168 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1925339
🔄 Запрос #19169 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1925459
🔄 Запрос #19170 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1925565

🔄 Запрос #19171 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1925664
🔄 Запрос #19172 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1925752
🔄 Запрос #19173 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 85 спецификаций. Всего: 1925837
🔄 Запрос #19174 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1925935
🔄 Запрос #19175 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1926041
🔄 Запрос #19176 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1926159
🔄 Запрос #19177 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 1926266
🔄 Запрос #19178 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1926388
🔄 Запрос #19179 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1926507
🔄 Запрос #19180 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1926623
🔄 Запрос #19181 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1926734
🔄 Запрос #19182 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 44 спецификаций. Всего: 1926778
🔄 Запрос #19183 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 76 спецификаций. Всего: 1926854
🔄 Запрос #19184 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1926966
🔄 Запрос #19185 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1927083
🔄 Запрос #19186 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1927186
🔄 Запрос #19187 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1927275
🔄 Запрос #19188 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1927374
🔄 Запрос #19189 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1927485
🔄 Запрос #19190 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1927583
🔄 Запрос #19191 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 85 спецификаций. Всего: 1927668
🔄 Запрос #19192 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 1927752
🔄 Запрос #19193 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1927857
🔄 Запрос #19194 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 46 спецификаций. Всего: 1927903
🔄 Запрос #19195 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 72 спецификаций. Всего: 1927975
🔄 Запрос #19196 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 79 спецификаций. Всего: 1928054
🔄 Запрос #19197 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1928144
🔄 Запрос #19198 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1928255
🔄 Запрос #19199 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1928377
🔄 Запрос #19200 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1928496
🔄 Запрос #19201 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1928593
🔄 Запрос #19202 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 87 спецификаций. Всего: 1928680
🔄 Запрос #19203 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1928788
🔄 Запрос #19204 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1928880
🔄 Запрос #19205 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 1928984
🔄 Запрос #19206 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1929090
🔄 Запрос #19207 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 127 спецификаций. Всего: 1929217
🔄 Запрос #19208 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1929325
🔄 Запрос #19209 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 143 спецификаций. Всего: 1929468
🔄 Запрос #19210 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 133 спецификаций. Всего: 1929601
🔄 Запрос #19211 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 77 спецификаций. Всего: 1929678
🔄 Запрос #19212 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 76 спецификаций. Всего: 1929754
🔄 Запрос #19213 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 78 спецификаций. Всего: 1929832
🔄 Запрос #19214 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1929948
🔄 Запрос #19215 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1930064
🔄 Запрос #19216 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 75 спецификаций. Всего: 1930139
🔄 Запрос #19217 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1930227
🔄 Запрос #19218 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 1930351
🔄 Запрос #19219 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 130 спецификаций. Всего: 1930481
📤 Сохранено 10019 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #19220 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 141 спецификаций. Всего: 1930622
🔄 Запрос #19221 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 137 спецификаций. Всего: 1930759
🔄 Запрос #19222 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 143 спецификаций. Всего: 1930902
🔄 Запрос #19223 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 136 спецификаций. Всего: 1931038
🔄 Запрос #19224 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1931157
🔄 Запрос #19225 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1931276
🔄 Запрос #19226 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 47 спецификаций. Всего: 1931323
🔄 Запрос #19227 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 4 спецификаций. Всего: 1931327
🔄 Запрос #19228 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1931432
🔄 Запрос #19229 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1931544
🔄 Запрос #19230 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1931642
🔄 Запрос #19231 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1931743
🔄 Запрос #19232 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1931848
🔄 Запрос #19233 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1931965
🔄 Запрос #19234 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1932066
🔄 Запрос #19235 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1932161
🔄 Запрос #19236 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 61 спецификаций. Всего: 1932222
🔄 Запрос #19237 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 126 спецификаций. Всего: 1932348
🔄 Запрос #19238 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1932451
🔄 Запрос #19239 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1932550
🔄 Запрос #19240 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 95 спецификаций. Всего: 1932645
🔄 Запрос #19241 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1932756
🔄 Запрос #19242 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1932855
🔄 Запрос #19243 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1932949
🔄 Запрос #19244 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 54 спецификаций. Всего: 1933003
🔄 Запрос #19245 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1933099
🔄 Запрос #19246 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1933196
🔄 Запрос #19247 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1933294
🔄 Запрос #19248 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1933390
🔄 Запрос #19249 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1933480
🔄 Запрос #19250 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 57 спецификаций. Всего: 1933537
🔄 Запрос #19251 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 81 спецификаций. Всего: 1933618
🔄 Запрос #19252 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 93 спецификаций. Всего: 1933711
🔄 Запрос #19253 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1933812
🔄 Запрос #19254 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1933909
🔄 Запрос #19255 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1933995
🔄 Запрос #19256 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1934105
🔄 Запрос #19257 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1934206
🔄 Запрос #19258 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 140 спецификаций. Всего: 1934346
🔄 Запрос #19259 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 126 спецификаций. Всего: 1934472
🔄 Запрос #19260 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1934585
🔄 Запрос #19261 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1934704
🔄 Запрос #19262 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 1934788
🔄 Запрос #19263 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1934900
🔄 Запрос #19264 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1935020
🔄 Запрос #19265 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1935137
🔄 Запрос #19266 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1935255
🔄 Запрос #19267 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 35 спецификаций. Всего: 1935290
🔄 Запрос #19268 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 61 спецификаций. Всего: 1935351
🔄 Запрос #19269 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 1935475
🔄 Запрос #19270 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1935583
🔄 Запрос #19271 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 135 спецификаций. Всего: 1935718
🔄 Запрос #19272 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1935804
🔄 Запрос #19273 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 95 спецификаций. Всего: 1935899
🔄 Запрос #19274 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1935998
🔄 Запрос #19275 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 1936107
🔄 Запрос #19276 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1936226
🔄 Запрос #19277 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 129 спецификаций. Всего: 1936355
🔄 Запрос #19278 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 103 спецификаций. Всего: 1936458
🔄 Запрос #19279 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 85 спецификаций. Всего: 1936543
🔄 Запрос #19280 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1936661
🔄 Запрос #19281 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1936774
🔄 Запрос #19282 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1936870
🔄 Запрос #19283 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 79 спецификаций. Всего: 1936949
🔄 Запрос #19284 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 1937060
🔄 Запрос #19285 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1937171
🔄 Запрос #19286 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1937291
🔄 Запрос #19287 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 130 спецификаций. Всего: 1937421
🔄 Запрос #19288 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1937524
🔄 Запрос #19289 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1937646
🔄 Запрос #19290 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1937756
🔄 Запрос #19291 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 126 спецификаций. Всего: 1937882
🔄 Запрос #19292 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 119 спецификаций. Всего: 1938001
🔄 Запрос #19293 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1938118
🔄 Запрос #19294 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1938210
🔄 Запрос #19295 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 159 спецификаций. Всего: 1938369
🔄 Запрос #19296 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 100 спецификаций. Всего: 1938469
🔄 Запрос #19297 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 1938553
🔄 Запрос #19298 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 78 спецификаций. Всего: 1938631
🔄 Запрос #19299 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 133 спецификаций. Всего: 1938764
🔄 Запрос #19300 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 99 спецификаций. Всего: 1938863
🔄 Запрос #19301 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 136 спецификаций. Всего: 1938999
🔄 Запрос #19302 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09

📥 Загружено 118 спецификаций. Всего: 1939117
🔄 Запрос #19303 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 152 спецификаций. Всего: 1939269
🔄 Запрос #19304 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 169 спецификаций. Всего: 1939438
🔄 Запрос #19305 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1939551
🔄 Запрос #19306 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 1939637
🔄 Запрос #19307 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 94 спецификаций. Всего: 1939731
🔄 Запрос #19308 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 106 спецификаций. Всего: 1939837
🔄 Запрос #19309 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1939951
🔄 Запрос #19310 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 128 спецификаций. Всего: 1940079
🔄 Запрос #19311 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 77 спецификаций. Всего: 1940156
🔄 Запрос #19312 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 38 спецификаций. Всего: 1940194
🔄 Запрос #19313 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1940314
🔄 Запрос #19314 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 140 спецификаций. Всего: 1940454
🔄 Запрос #19315 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 135 спецификаций. Всего: 1940589
📤 Сохранено 10108 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #19316 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 1940701
🔄 Запрос #19317 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 33 спецификаций. Всего: 1940734
🔄 Запрос #19318 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 62 спецификаций. Всего: 1940796
🔄 Запрос #19319 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1940914
🔄 Запрос #19320 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1941011
🔄 Запрос #19321 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1941113
🔄 Запрос #19322 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 79 спецификаций. Всего: 1941192
🔄 Запрос #19323 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 61 спецификаций. Всего: 1941253
🔄 Запрос #19324 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 51 спецификаций. Всего: 1941304
🔄 Запрос #19325 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 84 спецификаций. Всего: 1941388
🔄 Запрос #19326 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 46 спецификаций. Всего: 1941434
🔄 Запрос #19327 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 153 спецификаций. Всего: 1941587
🔄 Запрос #19328 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 95 спецификаций. Всего: 1941682
🔄 Запрос #19329 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 89 спецификаций. Всего: 1941771
🔄 Запрос #19330 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 64 спецификаций. Всего: 1941835
🔄 Запрос #19331 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1941925
🔄 Запрос #19332 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 143 спецификаций. Всего: 1942068
🔄 Запрос #19333 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 153 спецификаций. Всего: 1942221
🔄 Запрос #19334 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1942332
🔄 Запрос #19335 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1942448
🔄 Запрос #19336 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 132 спецификаций. Всего: 1942580
🔄 Запрос #19337 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1942705
🔄 Запрос #19338 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 128 спецификаций. Всего: 1942833
🔄 Запрос #19339 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1942947
🔄 Запрос #19340 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1943058
🔄 Запрос #19341 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1943170
🔄 Запрос #19342 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1943282
🔄 Запрос #19343 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1943393
🔄 Запрос #19344 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1943509
🔄 Запрос #19345 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 88 спецификаций. Всего: 1943597
🔄 Запрос #19346 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1943695
🔄 Запрос #19347 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1943813
🔄 Запрос #19348 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1943918
🔄 Запрос #19349 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 127 спецификаций. Всего: 1944045
🔄 Запрос #19350 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 1944169
🔄 Запрос #19351 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 123 спецификаций. Всего: 1944292
🔄 Запрос #19352 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 126 спецификаций. Всего: 1944418
🔄 Запрос #19353 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1944538
🔄 Запрос #19354 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1944651
🔄 Запрос #19355 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 124 спецификаций. Всего: 1944775
🔄 Запрос #19356 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1944893
🔄 Запрос #19357 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1944995
🔄 Запрос #19358 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 77 спецификаций. Всего: 1945072
🔄 Запрос #19359 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 111 спецификаций. Всего: 1945183
🔄 Запрос #19360 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 78 спецификаций. Всего: 1945261
🔄 Запрос #19361 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 104 спецификаций. Всего: 1945365
🔄 Запрос #19362 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 116 спецификаций. Всего: 1945481
🔄 Запрос #19363 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1945589
🔄 Запрос #19364 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1945707
🔄 Запрос #19365 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 103 спецификаций. Всего: 1945810
🔄 Запрос #19366 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 76 спецификаций. Всего: 1945886
🔄 Запрос #19367 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1945993
🔄 Запрос #19368 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 96 спецификаций. Всего: 1946089
🔄 Запрос #19369 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1946196
🔄 Запрос #19370 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 125 спецификаций. Всего: 1946321

🔄 Запрос #19371 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1946438
🔄 Запрос #19372 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 90 спецификаций. Всего: 1946528
🔄 Запрос #19373 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 98 спецификаций. Всего: 1946626
🔄 Запрос #19374 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1946733
🔄 Запрос #19375 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 118 спецификаций. Всего: 1946851
🔄 Запрос #19376 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 120 спецификаций. Всего: 1946971
🔄 Запрос #19377 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 1947089
🔄 Запрос #19378 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1947201
🔄 Запрос #19379 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 72 спецификаций. Всего: 1947273
🔄 Запрос #19380 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 123 спецификаций. Всего: 1947396
🔄 Запрос #19381 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 129 спецификаций. Всего: 1947525
🔄 Запрос #19382 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1947637
🔄 Запрос #19383 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 132 спецификаций. Всего: 1947769
🔄 Запрос #19384 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1947877
🔄 Запрос #19385 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 97 спецификаций. Всего: 1947974
🔄 Запрос #19386 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1948102
🔄 Запрос #19387 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 107 спецификаций. Всего: 1948209
🔄 Запрос #19388 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1948321
🔄 Запрос #19389 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1948443
🔄 Запрос #19390 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 126 спецификаций. Всего: 1948569
🔄 Запрос #19391 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 128 спецификаций. Всего: 1948697
🔄 Запрос #19392 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 130 спецификаций. Всего: 1948827
🔄 Запрос #19393 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 128 спецификаций. Всего: 1948955
🔄 Запрос #19394 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1949057
🔄 Запрос #19395 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 91 спецификаций. Всего: 1949148
🔄 Запрос #19396 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 99 спецификаций. Всего: 1949247
🔄 Запрос #19397 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 92 спецификаций. Всего: 1949339
🔄 Запрос #19398 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 1949436
🔄 Запрос #19399 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 101 спецификаций. Всего: 1949537
🔄 Запрос #19400 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1949652
🔄 Запрос #19401 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 114 спецификаций. Всего: 1949766
🔄 Запрос #19402 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 105 спецификаций. Всего: 1949871
🔄 Запрос #19403 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 113 спецификаций. Всего: 1949984
🔄 Запрос #19404 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 1950105
🔄 Запрос #19405 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1950227
🔄 Запрос #19406 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1950337
🔄 Запрос #19407 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1950452
🔄 Запрос #19408 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 102 спецификаций. Всего: 1950554
🔄 Запрос #19409 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 134 спецификаций. Всего: 1950688
📤 Сохранено 10099 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #19410 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 140 спецификаций. Всего: 1950828
🔄 Запрос #19411 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 121 спецификаций. Всего: 1950949
🔄 Запрос #19412 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1951066
🔄 Запрос #19413 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 127 спецификаций. Всего: 1951193
🔄 Запрос #19414 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 136 спецификаций. Всего: 1951329
🔄 Запрос #19415 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 112 спецификаций. Всего: 1951441
🔄 Запрос #19416 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 149 спецификаций. Всего: 1951590
🔄 Запрос #19417 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 55 спецификаций. Всего: 1951645
🔄 Запрос #19418 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 136 спецификаций. Всего: 1951781
🔄 Запрос #19419 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 122 спецификаций. Всего: 1951903
🔄 Запрос #19420 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 117 спецификаций. Всего: 1952020
🔄 Запрос #19421 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 108 спецификаций. Всего: 1952128
🔄 Запрос #19422 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 115 спецификаций. Всего: 1952243
🔄 Запрос #19423 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 135 спецификаций. Всего: 1952378
🔄 Запрос #19424 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 65 спецификаций. Всего: 1952443
🔄 Запрос #19425 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1952545
🔄 Запрос #19426 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 126 спецификаций. Всего: 1952671
🔄 Запрос #19427 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1952757
🔄 Запрос #19428 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 110 спецификаций. Всего: 1952867
🔄 Запрос #19429 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 86 спецификаций. Всего: 1952953
🔄 Запрос #19430 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 0 спецификаций. Всего: 1952953
🔄 Запрос #19431 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 0 спецификаций. Всего: 1952953
🔄 Запрос #19432 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 0 спецификаций. Всего: 1952953
🔄 Запрос #19433 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 0 спецификаций. Всего: 1952953
🔄 Запрос #19434 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 1 спецификаций. Всего: 1952954
🔄 Запрос #19435 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 24 спецификаций. Всего: 1952978
🔄 Запрос #19436 для 2024-01-18 20:44:09 - 2024-01-25 20:44:09
📥 Загружено 39 спецификаций. Всего: 1953017
📅 Обрабатываем диапазон 2024-01-11 20:44:09 - 2024-01-18 20:44:09 (попытка 1/5)
🔄 Запрос #19437 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 1953132
🔄 Запрос #19438 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1953236
🔄 Запрос #19439 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09

📥 Загружено 125 спецификаций. Всего: 1953361
🔄 Запрос #19440 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1953486
🔄 Запрос #19441 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1953616
🔄 Запрос #19442 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1953735
🔄 Запрос #19443 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 1953858
🔄 Запрос #19444 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 1953990
🔄 Запрос #19445 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 137 спецификаций. Всего: 1954127
🔄 Запрос #19446 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 142 спецификаций. Всего: 1954269
🔄 Запрос #19447 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 147 спецификаций. Всего: 1954416
🔄 Запрос #19448 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1954532
🔄 Запрос #19449 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 136 спецификаций. Всего: 1954668
🔄 Запрос #19450 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 1954786
🔄 Запрос #19451 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 124 спецификаций. Всего: 1954910
🔄 Запрос #19452 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1955009
🔄 Запрос #19453 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1955114
🔄 Запрос #19454 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1955214
🔄 Запрос #19455 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1955317
🔄 Запрос #19456 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 1955408
🔄 Запрос #19457 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 74 спецификаций. Всего: 1955482
🔄 Запрос #19458 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1955589
🔄 Запрос #19459 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1955693
🔄 Запрос #19460 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1955793
🔄 Запрос #19461 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 61 спецификаций. Всего: 1955854
🔄 Запрос #19462 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1955957
🔄 Запрос #19463 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 129 спецификаций. Всего: 1956086
🔄 Запрос #19464 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 1956186
🔄 Запрос #19465 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1956300
🔄 Запрос #19466 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1956409
🔄 Запрос #19467 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1956498
🔄 Запрос #19468 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1956606
🔄 Запрос #19469 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1956720
🔄 Запрос #19470 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1956839
🔄 Запрос #19471 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1956937
🔄 Запрос #19472 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 1957070
🔄 Запрос #19473 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1957192
🔄 Запрос #19474 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1957297
🔄 Запрос #19475 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1957406
🔄 Запрос #19476 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1957525
🔄 Запрос #19477 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1957630
🔄 Запрос #19478 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1957734
🔄 Запрос #19479 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1957832
🔄 Запрос #19480 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1957934
🔄 Запрос #19481 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 142 спецификаций. Всего: 1958076
🔄 Запрос #19482 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1958184
🔄 Запрос #19483 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 79 спецификаций. Всего: 1958263
🔄 Запрос #19484 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1958363
🔄 Запрос #19485 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 45 спецификаций. Всего: 1958408
🔄 Запрос #19486 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 78 спецификаций. Всего: 1958486
🔄 Запрос #19487 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1958596
🔄 Запрос #19488 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1958705
🔄 Запрос #19489 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1958801
🔄 Запрос #19490 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 88 спецификаций. Всего: 1958889
🔄 Запрос #19491 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1958987
🔄 Запрос #19492 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1959109
🔄 Запрос #19493 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1959202
🔄 Запрос #19494 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1959316
🔄 Запрос #19495 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 148 спецификаций. Всего: 1959464
🔄 Запрос #19496 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 141 спецификаций. Всего: 1959605
🔄 Запрос #19497 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 128 спецификаций. Всего: 1959733
🔄 Запрос #19498 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1959839
🔄 Запрос #19499 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1959967
🔄 Запрос #19500 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 135 спецификаций. Всего: 1960102
🔄 Запрос #19501 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1960212
🔄 Запрос #19502 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 48 спецификаций. Всего: 1960260
🔄 Запрос #19503 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1960363

🔄 Запрос #19504 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 1960454
🔄 Запрос #19505 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1960552
🔄 Запрос #19506 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1960668
🔄 Запрос #19507 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1960772
📤 Сохранено 10084 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #19508 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1960874
🔄 Запрос #19509 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 55 спецификаций. Всего: 1960929
🔄 Запрос #19510 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 5 спецификаций. Всего: 1960934
🔄 Запрос #19511 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 8 спецификаций. Всего: 1960942
🔄 Запрос #19512 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 2 спецификаций. Всего: 1960944
🔄 Запрос #19513 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 76 спецификаций. Всего: 1961020
🔄 Запрос #19514 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1961127
🔄 Запрос #19515 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 70 спецификаций. Всего: 1961197
🔄 Запрос #19516 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1961300
🔄 Запрос #19517 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1961399
🔄 Запрос #19518 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1961513
🔄 Запрос #19519 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 67 спецификаций. Всего: 1961580
🔄 Запрос #19520 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1961687
🔄 Запрос #19521 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1961792
🔄 Запрос #19522 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1961901
🔄 Запрос #19523 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 79 спецификаций. Всего: 1961980
🔄 Запрос #19524 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1962091
🔄 Запрос #19525 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1962196
🔄 Запрос #19526 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1962301
🔄 Запрос #19527 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1962396
🔄 Запрос #19528 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1962493
🔄 Запрос #19529 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 82 спецификаций. Всего: 1962575
🔄 Запрос #19530 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1962664
🔄 Запрос #19531 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1962754
🔄 Запрос #19532 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1962859
🔄 Запрос #19533 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1962973
🔄 Запрос #19534 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1963090
🔄 Запрос #19535 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 1963205
🔄 Запрос #19536 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 78 спецификаций. Всего: 1963283
🔄 Запрос #19537 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1963393
🔄 Запрос #19538 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1963499
🔄 Запрос #19539 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1963598
🔄 Запрос #19540 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1963685
🔄 Запрос #19541 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 1963804
🔄 Запрос #19542 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1963920
🔄 Запрос #19543 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1964045
🔄 Запрос #19544 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1964170
🔄 Запрос #19545 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 1964245
🔄 Запрос #19546 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 1964371
🔄 Запрос #19547 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 129 спецификаций. Всего: 1964500
🔄 Запрос #19548 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 152 спецификаций. Всего: 1964652
🔄 Запрос #19549 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 165 спецификаций. Всего: 1964817
🔄 Запрос #19550 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1964947
🔄 Запрос #19551 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 133 спецификаций. Всего: 1965080
🔄 Запрос #19552 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1965194
🔄 Запрос #19553 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1965300
🔄 Запрос #19554 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1965407
🔄 Запрос #19555 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 78 спецификаций. Всего: 1965485
🔄 Запрос #19556 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 49 спецификаций. Всего: 1965534
🔄 Запрос #19557 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 12 спецификаций. Всего: 1965546
🔄 Запрос #19558 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 67 спецификаций. Всего: 1965613
🔄 Запрос #19559 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 71 спецификаций. Всего: 1965684
🔄 Запрос #19560 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1965774
🔄 Запрос #19561 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1965871
🔄 Запрос #19562 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1965979
🔄 Запрос #19563 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 1966100
🔄 Запрос #19564 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 137 спецификаций. Всего: 1966237
🔄 Запрос #19565 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1966333
🔄 Запрос #19566 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 135 спецификаций. Всего: 1966468
🔄 Запрос #19567 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 141 спецификаций. Всего: 1966609
🔄 Запрос #19568 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 93 спецификаций. Всего: 1966702
🔄 Запрос #19569 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1966819
🔄 Запрос #19570 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 37 спецификаций. Всего: 1966856
🔄 Запрос #19571 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09

⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 134 спецификаций. Всего: 1966990
🔄 Запрос #19572 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 50 спецификаций. Всего: 1967040
🔄 Запрос #19573 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 1967166
🔄 Запрос #19574 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1967274
🔄 Запрос #19575 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1967388
🔄 Запрос #19576 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1967505
🔄 Запрос #19577 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1967607
🔄 Запрос #19578 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 88 спецификаций. Всего: 1967695
🔄 Запрос #19579 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1967808
🔄 Запрос #19580 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 113 спецификаций. Всего: 1967921
🔄 Запрос #19581 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 1968042
🔄 Запрос #19582 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1968156
🔄 Запрос #19583 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1968267
🔄 Запрос #19584 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1968378
🔄 Запрос #19585 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1968497
🔄 Запрос #19586 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1968599
🔄 Запрос #19587 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 1968674
🔄 Запрос #19588 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1968760
🔄 Запрос #19589 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1968861
🔄 Запрос #19590 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1968954
🔄 Запрос #19591 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 114 спецификаций. Всего: 1969068
🔄 Запрос #19592 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1969179
🔄 Запрос #19593 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 78 спецификаций. Всего: 1969257
🔄 Запрос #19594 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1969367
🔄 Запрос #19595 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1969460
🔄 Запрос #19596 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1969572
🔄 Запрос #19597 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1969674
🔄 Запрос #19598 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1969769
🔄 Запрос #19599 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1969872
🔄 Запрос #19600 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 1969974
🔄 Запрос #19601 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 79 спецификаций. Всего: 1970053
🔄 Запрос #19602 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1970152
🔄 Запрос #19603 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1970241
🔄 Запрос #19604 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1970338
🔄 Запрос #19605 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1970431
🔄 Запрос #19606 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1970527
🔄 Запрос #19607 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1970614
🔄 Запрос #19608 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 80 спецификаций. Всего: 1970694
🔄 Запрос #19609 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1970783
📤 Сохранено 10011 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #19610 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 56 спецификаций. Всего: 1970839
🔄 Запрос #19611 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1970943
🔄 Запрос #19612 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1971052
🔄 Запрос #19613 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1971141
🔄 Запрос #19614 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1971244
🔄 Запрос #19615 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 88 спецификаций. Всего: 1971332
🔄 Запрос #19616 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1971430
🔄 Запрос #19617 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 82 спецификаций. Всего: 1971512
🔄 Запрос #19618 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 69 спецификаций. Всего: 1971581
🔄 Запрос #19619 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 77 спецификаций. Всего: 1971658
🔄 Запрос #19620 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 88 спецификаций. Всего: 1971746
🔄 Запрос #19621 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 71 спецификаций. Всего: 1971817
🔄 Запрос #19622 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 76 спецификаций. Всего: 1971893
🔄 Запрос #19623 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 78 спецификаций. Всего: 1971971
🔄 Запрос #19624 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 77 спецификаций. Всего: 1972048
🔄 Запрос #19625 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 81 спецификаций. Всего: 1972129
🔄 Запрос #19626 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1972251
🔄 Запрос #19627 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1972361
🔄 Запрос #19628 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 1972487
🔄 Запрос #19629 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1972606
🔄 Запрос #19630 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1972736
🔄 Запрос #19631 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 98 спецификаций. Всего: 1972834
🔄 Запрос #19632 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 106 спецификаций. Всего: 1972940
🔄 Запрос #19633 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1973051
🔄 Запрос #19634 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 127 спецификаций. Всего: 1973178
🔄 Запрос #19635 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1973276
🔄 Запрос #19636 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1973377
🔄 Запрос #19637 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1973474
🔄 Запрос #19638 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1973578
🔄 Запрос #19639 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1973688

🔄 Запрос #19640 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1973813
🔄 Запрос #19641 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 127 спецификаций. Всего: 1973940
🔄 Запрос #19642 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1974056
🔄 Запрос #19643 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1974162
🔄 Запрос #19644 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1974273
🔄 Запрос #19645 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 1974388
🔄 Запрос #19646 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 133 спецификаций. Всего: 1974521
🔄 Запрос #19647 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1974637
🔄 Запрос #19648 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 1974769
🔄 Запрос #19649 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 116 спецификаций. Всего: 1974885
🔄 Запрос #19650 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 135 спецификаций. Всего: 1975020
🔄 Запрос #19651 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 140 спецификаций. Всего: 1975160
🔄 Запрос #19652 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1975290
🔄 Запрос #19653 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 1975382
🔄 Запрос #19654 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 129 спецификаций. Всего: 1975511
🔄 Запрос #19655 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 84 спецификаций. Всего: 1975595
🔄 Запрос #19656 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 37 спецификаций. Всего: 1975632
🔄 Запрос #19657 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1975731
🔄 Запрос #19658 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1975841
🔄 Запрос #19659 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 77 спецификаций. Всего: 1975918
🔄 Запрос #19660 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1976043
🔄 Запрос #19661 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 1976175
🔄 Запрос #19662 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 128 спецификаций. Всего: 1976303
🔄 Запрос #19663 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1976419
🔄 Запрос #19664 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1976524
🔄 Запрос #19665 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 78 спецификаций. Всего: 1976602
🔄 Запрос #19666 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 142 спецификаций. Всего: 1976744
🔄 Запрос #19667 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1976853
🔄 Запрос #19668 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 60 спецификаций. Всего: 1976913
🔄 Запрос #19669 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 31 спецификаций. Всего: 1976944
🔄 Запрос #19670 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 38 спецификаций. Всего: 1976982
🔄 Запрос #19671 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 68 спецификаций. Всего: 1977050
🔄 Запрос #19672 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 1977136
🔄 Запрос #19673 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1977241
🔄 Запрос #19674 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1977334
🔄 Запрос #19675 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 129 спецификаций. Всего: 1977463
🔄 Запрос #19676 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1977568
🔄 Запрос #19677 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 72 спецификаций. Всего: 1977640
🔄 Запрос #19678 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 63 спецификаций. Всего: 1977703
🔄 Запрос #19679 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 58 спецификаций. Всего: 1977761
🔄 Запрос #19680 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 81 спецификаций. Всего: 1977842
🔄 Запрос #19681 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 81 спецификаций. Всего: 1977923
🔄 Запрос #19682 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 43 спецификаций. Всего: 1977966
🔄 Запрос #19683 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 55 спецификаций. Всего: 1978021
🔄 Запрос #19684 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 46 спецификаций. Всего: 1978067
🔄 Запрос #19685 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 42 спецификаций. Всего: 1978109
🔄 Запрос #19686 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 84 спецификаций. Всего: 1978193
🔄 Запрос #19687 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 17 спецификаций. Всего: 1978210
🔄 Запрос #19688 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 1978328
🔄 Запрос #19689 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 137 спецификаций. Всего: 1978465
🔄 Запрос #19690 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 133 спецификаций. Всего: 1978598
🔄 Запрос #19691 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 132 спецификаций. Всего: 1978730
🔄 Запрос #19692 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1978860
🔄 Запрос #19693 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 131 спецификаций. Всего: 1978991
🔄 Запрос #19694 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 1979117
🔄 Запрос #19695 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1979245
🔄 Запрос #19696 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 1979370
🔄 Запрос #19697 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1979495
🔄 Запрос #19698 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 146 спецификаций. Всего: 1979641
🔄 Запрос #19699 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 1979773
🔄 Запрос #19700 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1979898
🔄 Запрос #19701 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 72 спецификаций. Всего: 1979970
🔄 Запрос #19702 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1980056
🔄 Запрос #19703 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1980186
🔄 Запрос #19704 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 124 спецификаций. Всего: 1980310
🔄 Запрос #19705 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 1980428
🔄 Запрос #19706 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 111 спецификаций. Всего: 1980539
🔄 Запрос #19707 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1980639

🔄 Запрос #19708 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1980747
🔄 Запрос #19709 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 135 спецификаций. Всего: 1980882
📤 Сохранено 10099 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #19710 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1980994
🔄 Запрос #19711 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 128 спецификаций. Всего: 1981122
🔄 Запрос #19712 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1981232
🔄 Запрос #19713 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 29 спецификаций. Всего: 1981261
🔄 Запрос #19714 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1981370
🔄 Запрос #19715 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1981492
🔄 Запрос #19716 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1981598
🔄 Запрос #19717 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1981699
🔄 Запрос #19718 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1981805
🔄 Запрос #19719 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 127 спецификаций. Всего: 1981932
🔄 Запрос #19720 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1982049
🔄 Запрос #19721 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1982161
🔄 Запрос #19722 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1982267
🔄 Запрос #19723 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1982366
🔄 Запрос #19724 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 123 спецификаций. Всего: 1982489
🔄 Запрос #19725 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1982599
🔄 Запрос #19726 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 58 спецификаций. Всего: 1982657
🔄 Запрос #19727 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 88 спецификаций. Всего: 1982745
🔄 Запрос #19728 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 62 спецификаций. Всего: 1982807
🔄 Запрос #19729 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1982904
🔄 Запрос #19730 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1982999
🔄 Запрос #19731 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1983102
🔄 Запрос #19732 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1983206
🔄 Запрос #19733 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 66 спецификаций. Всего: 1983272
🔄 Запрос #19734 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 81 спецификаций. Всего: 1983353
🔄 Запрос #19735 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1983442
🔄 Запрос #19736 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1983559
🔄 Запрос #19737 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1983657
🔄 Запрос #19738 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 1983771
🔄 Запрос #19739 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1983857
🔄 Запрос #19740 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 82 спецификаций. Всего: 1983939
🔄 Запрос #19741 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 80 спецификаций. Всего: 1984019
🔄 Запрос #19742 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1984119
🔄 Запрос #19743 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1984205
🔄 Запрос #19744 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 1984296
🔄 Запрос #19745 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1984389
🔄 Запрос #19746 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1984488
🔄 Запрос #19747 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 95 спецификаций. Всего: 1984583
🔄 Запрос #19748 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1984679
🔄 Запрос #19749 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1984765
🔄 Запрос #19750 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 127 спецификаций. Всего: 1984892
🔄 Запрос #19751 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1985022
🔄 Запрос #19752 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1985139
🔄 Запрос #19753 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1985242
🔄 Запрос #19754 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1985340
🔄 Запрос #19755 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1985449
🔄 Запрос #19756 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 1985551
🔄 Запрос #19757 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 144 спецификаций. Всего: 1985695
🔄 Запрос #19758 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 80 спецификаций. Всего: 1985775
🔄 Запрос #19759 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1985883
🔄 Запрос #19760 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 1986002
🔄 Запрос #19761 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 1986113
🔄 Запрос #19762 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1986226
🔄 Запрос #19763 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1986336
🔄 Запрос #19764 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1986439
🔄 Запрос #19765 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 124 спецификаций. Всего: 1986563
🔄 Запрос #19766 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1986670
🔄 Запрос #19767 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1986771
🔄 Запрос #19768 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 1986862
🔄 Запрос #19769 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 80 спецификаций. Всего: 1986942
🔄 Запрос #19770 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1987043
🔄 Запрос #19771 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1987138
🔄 Запрос #19772 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1987244
🔄 Запрос #19773 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1987360
🔄 Запрос #19774 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1987449
🔄 Запрос #19775 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1987548
🔄 Запрос #19776 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1987647
🔄 Запрос #19777 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1987740
🔄 Запрос #19778 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09

📥 Загружено 120 спецификаций. Всего: 1987860
🔄 Запрос #19779 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 136 спецификаций. Всего: 1987996
🔄 Запрос #19780 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1988126
🔄 Запрос #19781 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1988236
🔄 Запрос #19782 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1988349
🔄 Запрос #19783 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1988454
🔄 Запрос #19784 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1988561
🔄 Запрос #19785 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1988666
🔄 Запрос #19786 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 87 спецификаций. Всего: 1988753
🔄 Запрос #19787 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1988878
🔄 Запрос #19788 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1988981
🔄 Запрос #19789 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 1989103
🔄 Запрос #19790 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 1989178
🔄 Запрос #19791 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 84 спецификаций. Всего: 1989262
🔄 Запрос #19792 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 42 спецификаций. Всего: 1989304
🔄 Запрос #19793 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 67 спецификаций. Всего: 1989371
🔄 Запрос #19794 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 139 спецификаций. Всего: 1989510
🔄 Запрос #19795 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1989614
🔄 Запрос #19796 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1989730
🔄 Запрос #19797 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1989816
🔄 Запрос #19798 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 1989891
🔄 Запрос #19799 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1990001
🔄 Запрос #19800 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 1990094
🔄 Запрос #19801 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 67 спецификаций. Всего: 1990161
🔄 Запрос #19802 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1990266
🔄 Запрос #19803 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1990373
🔄 Запрос #19804 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 1990474
🔄 Запрос #19805 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1990563
🔄 Запрос #19806 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1990666
🔄 Запрос #19807 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 78 спецификаций. Всего: 1990744
🔄 Запрос #19808 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1990860
🔄 Запрос #19809 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1990976
📤 Сохранено 10094 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #19810 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 1991109
🔄 Запрос #19811 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 1991225
🔄 Запрос #19812 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1991350
🔄 Запрос #19813 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 148 спецификаций. Всего: 1991498
🔄 Запрос #19814 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1991610
🔄 Запрос #19815 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1991718
🔄 Запрос #19816 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 131 спецификаций. Всего: 1991849
🔄 Запрос #19817 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 140 спецификаций. Всего: 1991989
🔄 Запрос #19818 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 1992121
🔄 Запрос #19819 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 1992242
🔄 Запрос #19820 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 1992363
🔄 Запрос #19821 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1992471
🔄 Запрос #19822 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1992570
🔄 Запрос #19823 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1992673
🔄 Запрос #19824 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1992776
🔄 Запрос #19825 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 85 спецификаций. Всего: 1992861
🔄 Запрос #19826 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 1992953
🔄 Запрос #19827 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 85 спецификаций. Всего: 1993038
🔄 Запрос #19828 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 1993128
🔄 Запрос #19829 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 85 спецификаций. Всего: 1993213
🔄 Запрос #19830 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 1993299
🔄 Запрос #19831 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1993403
🔄 Запрос #19832 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1993510
🔄 Запрос #19833 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 1993616
🔄 Запрос #19834 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1993729
🔄 Запрос #19835 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 84 спецификаций. Всего: 1993813
🔄 Запрос #19836 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 90 спецификаций. Всего: 1993903
🔄 Запрос #19837 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 82 спецификаций. Всего: 1993985
🔄 Запрос #19838 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 65 спецификаций. Всего: 1994050
🔄 Запрос #19839 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 1994155
🔄 Запрос #19840 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1994251
🔄 Запрос #19841 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 38 спецификаций. Всего: 1994289
🔄 Запрос #19842 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 53 спецификаций. Всего: 1994342
🔄 Запрос #19843 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 136 спецификаций. Всего: 1994478
🔄 Запрос #19844 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1994581
🔄 Запрос #19845 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1994679
🔄 Запрос #19846 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 134 спецификаций. Всего: 1994813
🔄 Запрос #19847 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 1994928

🔄 Запрос #19848 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 127 спецификаций. Всего: 1995055
🔄 Запрос #19849 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1995159
🔄 Запрос #19850 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1995266
🔄 Запрос #19851 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 128 спецификаций. Всего: 1995394
🔄 Запрос #19852 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 128 спецификаций. Всего: 1995522
🔄 Запрос #19853 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 1995629
🔄 Запрос #19854 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 33 спецификаций. Всего: 1995662
🔄 Запрос #19855 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 81 спецификаций. Всего: 1995743
🔄 Запрос #19856 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1995856
🔄 Запрос #19857 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 1995952
🔄 Запрос #19858 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 1996041
🔄 Запрос #19859 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1996147
🔄 Запрос #19860 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1996257
🔄 Запрос #19861 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 1996361
🔄 Запрос #19862 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1996467
🔄 Запрос #19863 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 1996577
🔄 Запрос #19864 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 1996689
🔄 Запрос #19865 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 1996786
🔄 Запрос #19866 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1996892
🔄 Запрос #19867 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 1997001
🔄 Запрос #19868 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 1997109
🔄 Запрос #19869 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 134 спецификаций. Всего: 1997243
🔄 Запрос #19870 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 144 спецификаций. Всего: 1997387
🔄 Запрос #19871 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 172 спецификаций. Всего: 1997559
🔄 Запрос #19872 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 129 спецификаций. Всего: 1997688
🔄 Запрос #19873 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 1997813
🔄 Запрос #19874 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 127 спецификаций. Всего: 1997940
🔄 Запрос #19875 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 141 спецификаций. Всего: 1998081
🔄 Запрос #19876 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1998184
🔄 Запрос #19877 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 1998290
🔄 Запрос #19878 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 1998400
🔄 Запрос #19879 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 1998499
🔄 Запрос #19880 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 1998616
🔄 Запрос #19881 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 1998734
🔄 Запрос #19882 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 1998834
🔄 Запрос #19883 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 128 спецификаций. Всего: 1998962
🔄 Запрос #19884 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 1999075
🔄 Запрос #19885 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 1999173
🔄 Запрос #19886 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 76 спецификаций. Всего: 1999249
🔄 Запрос #19887 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 1999344
🔄 Запрос #19888 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 1999447
🔄 Запрос #19889 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 141 спецификаций. Всего: 1999588
🔄 Запрос #19890 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 153 спецификаций. Всего: 1999741
🔄 Запрос #19891 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 1999864
🔄 Запрос #19892 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 1999994
🔄 Запрос #19893 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 129 спецификаций. Всего: 2000123
🔄 Запрос #19894 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 124 спецификаций. Всего: 2000247
🔄 Запрос #19895 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 66 спецификаций. Всего: 2000313
🔄 Запрос #19896 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 2000429
🔄 Запрос #19897 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 2000534
🔄 Запрос #19898 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 2000647
🔄 Запрос #19899 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 2000764
🔄 Запрос #19900 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 2000869
🔄 Запрос #19901 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 2000978
📤 Сохранено 10002 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #19902 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 2001069
🔄 Запрос #19903 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 2001172
🔄 Запрос #19904 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 2001279
🔄 Запрос #19905 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 128 спецификаций. Всего: 2001407
🔄 Запрос #19906 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 2001513
🔄 Запрос #19907 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 2001605
🔄 Запрос #19908 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 70 спецификаций. Всего: 2001675
🔄 Запрос #19909 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 2001785
🔄 Запрос #19910 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 2001898
🔄 Запрос #19911 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 2002005
🔄 Запрос #19912 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 92 спецификаций. Всего: 2002097
🔄 Запрос #19913 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 2002204
🔄 Запрос #19914 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 2002313
🔄 Запрос #19915 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 2002408
🔄 Запрос #19916 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 2002511
🔄 Запрос #19917 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 2002613
🔄 Запрос #19918 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 103 спецификаций. Всего: 2002716
🔄 Запрос #19919 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 124 спецификаций. Всего: 2002840
🔄 Запрос #19920 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 2002949
🔄 Запрос #19921 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 2003046
🔄 Запрос #19922 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 2003149
🔄 Запрос #19923 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 120 спецификаций. Всего: 2003269
🔄 Запрос #19924 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 120 спецификаций. Всего: 2003389
🔄 Запрос #19925 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 141 спецификаций. Всего: 2003530
🔄 Запрос #19926 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 132 спецификаций. Всего: 2003662
🔄 Запрос #19927 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 2003758
🔄 Запрос #19928 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 2003868
🔄 Запрос #19929 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 2003983
🔄 Запрос #19930 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 142 спецификаций. Всего: 2004125
🔄 Запрос #19931 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 56 спецификаций. Всего: 2004181
🔄 Запрос #19932 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 51 спецификаций. Всего: 2004232
🔄 Запрос #19933 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 181 спецификаций. Всего: 2004413
🔄 Запрос #19934 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 2004510
🔄 Запрос #19935 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 2004614
🔄 Запрос #19936 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 71 спецификаций. Всего: 2004685
🔄 Запрос #19937 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 2004817
🔄 Запрос #19938 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 2004913
🔄 Запрос #19939 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 99 спецификаций. Всего: 2005012
🔄 Запрос #19940 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 2005135
🔄 Запрос #19941 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 138 спецификаций. Всего: 2005273
🔄 Запрос #19942 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 2005379
🔄 Запрос #19943 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 2005501
🔄 Запрос #19944 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 2005620
🔄 Запрос #19945 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 142 спецификаций. Всего: 2005762
🔄 Запрос #19946 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 2005852
🔄 Запрос #19947 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 115 спецификаций. Всего: 2005967
🔄 Запрос #19948 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 2006073
🔄 Запрос #19949 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 76 спецификаций. Всего: 2006149
🔄 Запрос #19950 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 6 спецификаций. Всего: 2006155
🔄 Запрос #19951 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 33 спецификаций. Всего: 2006188
🔄 Запрос #19952 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 164 спецификаций. Всего: 2006352
🔄 Запрос #19953 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 144 спецификаций. Всего: 2006496
🔄 Запрос #19954 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 131 спецификаций. Всего: 2006627
🔄 Запрос #19955 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 2006750
🔄 Запрос #19956 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 168 спецификаций. Всего: 2006918
🔄 Запрос #19957 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 2007031
🔄 Запрос #19958 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 24 спецификаций. Всего: 2007055
🔄 Запрос #19959 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 77 спецификаций. Всего: 2007132
🔄 Запрос #19960 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 2007245
🔄 Запрос #19961 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 106 спецификаций. Всего: 2007351
🔄 Запрос #19962 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 88 спецификаций. Всего: 2007439
🔄 Запрос #19963 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 2007534
🔄 Запрос #19964 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 2007666
🔄 Запрос #19965 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 22 спецификаций. Всего: 2007688
🔄 Запрос #19966 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 78 спецификаций. Всего: 2007766
🔄 Запрос #19967 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 103 спецификаций. Всего: 2007869
🔄 Запрос #19968 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 2007978
🔄 Запрос #19969 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 2008078
🔄 Запрос #19970 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 69 спецификаций. Всего: 2008147
🔄 Запрос #19971 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 2008246
🔄 Запрос #19972 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 2008364
🔄 Запрос #19973 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 158 спецификаций. Всего: 2008522
🔄 Запрос #19974 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 2008644
🔄 Запрос #19975 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 103 спецификаций. Всего: 2008747
🔄 Запрос #19976 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 154 спецификаций. Всего: 2008901
🔄 Запрос #19977 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 2008997
🔄 Запрос #19978 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 69 спецификаций. Всего: 2009066
🔄 Запрос #19979 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 2009152
🔄 Запрос #19980 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 74 спецификаций. Всего: 2009226
🔄 Запрос #19981 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 50 спецификаций. Всего: 2009276
🔄 Запрос #19982 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 88 спецификаций. Всего: 2009364
🔄 Запрос #19983 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 45 спецификаций. Всего: 2009409
🔄 Запрос #19984 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 38 спецификаций. Всего: 2009447
🔄 Запрос #19985 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09

📥 Загружено 130 спецификаций. Всего: 2009577
🔄 Запрос #19986 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 42 спецификаций. Всего: 2009619
🔄 Запрос #19987 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 18 спецификаций. Всего: 2009637
🔄 Запрос #19988 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 73 спецификаций. Всего: 2009710
🔄 Запрос #19989 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 2009827
🔄 Запрос #19990 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 139 спецификаций. Всего: 2009966
🔄 Запрос #19991 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 2010092
🔄 Запрос #19992 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 47 спецификаций. Всего: 2010139
🔄 Запрос #19993 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 90 спецификаций. Всего: 2010229
🔄 Запрос #19994 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 133 спецификаций. Всего: 2010362
🔄 Запрос #19995 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 144 спецификаций. Всего: 2010506
🔄 Запрос #19996 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 2010638
🔄 Запрос #19997 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 2010747
🔄 Запрос #19998 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 2010856
🔄 Запрос #19999 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 86 спецификаций. Всего: 2010942
🔄 Запрос #20000 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 2011059
📤 Сохранено 10081 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #20001 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 2011160
🔄 Запрос #20002 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 2011265
🔄 Запрос #20003 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 140 спецификаций. Всего: 2011405
🔄 Запрос #20004 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 129 спецификаций. Всего: 2011534
🔄 Запрос #20005 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 141 спецификаций. Всего: 2011675
🔄 Запрос #20006 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 129 спецификаций. Всего: 2011804
🔄 Запрос #20007 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 2011920
🔄 Запрос #20008 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 153 спецификаций. Всего: 2012073
🔄 Запрос #20009 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 2012198
🔄 Запрос #20010 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 152 спецификаций. Всего: 2012350
🔄 Запрос #20011 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 2012463
🔄 Запрос #20012 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 2012584
🔄 Запрос #20013 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 2012694
🔄 Запрос #20014 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 140 спецификаций. Всего: 2012834
🔄 Запрос #20015 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 2012952
🔄 Запрос #20016 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 128 спецификаций. Всего: 2013080
🔄 Запрос #20017 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 2013191
🔄 Запрос #20018 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 131 спецификаций. Всего: 2013322
🔄 Запрос #20019 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 2013441
🔄 Запрос #20020 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 2013551
🔄 Запрос #20021 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 2013665
🔄 Запрос #20022 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 2013780
🔄 Запрос #20023 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 2013897
🔄 Запрос #20024 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 2014022
🔄 Запрос #20025 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 2014126
🔄 Запрос #20026 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 2014235
🔄 Запрос #20027 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 120 спецификаций. Всего: 2014355
🔄 Запрос #20028 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 127 спецификаций. Всего: 2014482
🔄 Запрос #20029 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 2014609
🔄 Запрос #20030 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 93 спецификаций. Всего: 2014702
🔄 Запрос #20031 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 2014807
🔄 Запрос #20032 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 131 спецификаций. Всего: 2014938
🔄 Запрос #20033 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 2015027
🔄 Запрос #20034 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 133 спецификаций. Всего: 2015160
🔄 Запрос #20035 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 117 спецификаций. Всего: 2015277
🔄 Запрос #20036 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 2 спецификаций. Всего: 2015279
🔄 Запрос #20037 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 72 спецификаций. Всего: 2015351
🔄 Запрос #20038 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 2015458
🔄 Запрос #20039 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 2015570
🔄 Запрос #20040 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 82 спецификаций. Всего: 2015652
🔄 Запрос #20041 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 2015758
🔄 Запрос #20042 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 2015857
🔄 Запрос #20043 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 97 спецификаций. Всего: 2015954
🔄 Запрос #20044 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 2016060
🔄 Запрос #20045 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 2016165
🔄 Запрос #20046 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 2016279
🔄 Запрос #20047 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 122 спецификаций. Всего: 2016401
🔄 Запрос #20048 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 2016513
🔄 Запрос #20049 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 2016643
🔄 Запрос #20050 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 2016741
🔄 Запрос #20051 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 2016837
🔄 Запрос #20052 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 2016964
🔄 Запрос #20053 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 2017077

🔄 Запрос #20054 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 2017177
🔄 Запрос #20055 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 2017281
🔄 Запрос #20056 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 2017383
🔄 Запрос #20057 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 125 спецификаций. Всего: 2017508
🔄 Запрос #20058 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 2017608
🔄 Запрос #20059 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 99 спецификаций. Всего: 2017707
🔄 Запрос #20060 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 74 спецификаций. Всего: 2017781
🔄 Запрос #20061 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 85 спецификаций. Всего: 2017866
🔄 Запрос #20062 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 2017983
🔄 Запрос #20063 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 2018091
🔄 Запрос #20064 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 2018186
🔄 Запрос #20065 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 108 спецификаций. Всего: 2018294
🔄 Запрос #20066 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 64 спецификаций. Всего: 2018358
🔄 Запрос #20067 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 75 спецификаций. Всего: 2018433
🔄 Запрос #20068 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 2018549
🔄 Запрос #20069 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 2018675
🔄 Запрос #20070 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 62 спецификаций. Всего: 2018737
🔄 Запрос #20071 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 118 спецификаций. Всего: 2018855
🔄 Запрос #20072 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 2018987
🔄 Запрос #20073 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 123 спецификаций. Всего: 2019110
🔄 Запрос #20074 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 2019226
🔄 Запрос #20075 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 2019341
🔄 Запрос #20076 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 119 спецификаций. Всего: 2019460
🔄 Запрос #20077 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 71 спецификаций. Всего: 2019531
🔄 Запрос #20078 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 56 спецификаций. Всего: 2019587
🔄 Запрос #20079 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 2019699
🔄 Запрос #20080 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 104 спецификаций. Всего: 2019803
🔄 Запрос #20081 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 2019915
🔄 Запрос #20082 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 2020028
🔄 Запрос #20083 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 130 спецификаций. Всего: 2020158
🔄 Запрос #20084 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 121 спецификаций. Всего: 2020279
🔄 Запрос #20085 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 2020385
🔄 Запрос #20086 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 2020499
🔄 Запрос #20087 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 2020616
🔄 Запрос #20088 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 45 спецификаций. Всего: 2020661
🔄 Запрос #20089 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 2020775
🔄 Запрос #20090 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 117 спецификаций. Всего: 2020892
🔄 Запрос #20091 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 98 спецификаций. Всего: 2020990
🔄 Запрос #20092 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 2021090
📤 Сохранено 10031 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #20093 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 105 спецификаций. Всего: 2021195
🔄 Запрос #20094 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 106 спецификаций. Всего: 2021301
🔄 Запрос #20095 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 2021408
🔄 Запрос #20096 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 2021522
🔄 Запрос #20097 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 2021631
🔄 Запрос #20098 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 124 спецификаций. Всего: 2021755
🔄 Запрос #20099 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 2021847
🔄 Запрос #20100 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 126 спецификаций. Всего: 2021973
🔄 Запрос #20101 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 109 спецификаций. Всего: 2022082
🔄 Запрос #20102 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 2022196
🔄 Запрос #20103 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 110 спецификаций. Всего: 2022306
🔄 Запрос #20104 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 2022395
🔄 Запрос #20105 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 100 спецификаций. Всего: 2022495
🔄 Запрос #20106 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 89 спецификаций. Всего: 2022584
🔄 Запрос #20107 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 96 спецификаций. Всего: 2022680
🔄 Запрос #20108 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 2022781
🔄 Запрос #20109 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 91 спецификаций. Всего: 2022872
🔄 Запрос #20110 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 120 спецификаций. Всего: 2022992
🔄 Запрос #20111 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 107 спецификаций. Всего: 2023099
🔄 Запрос #20112 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 156 спецификаций. Всего: 2023255
🔄 Запрос #20113 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 129 спецификаций. Всего: 2023384
🔄 Запрос #20114 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 102 спецификаций. Всего: 2023486
🔄 Запрос #20115 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 112 спецификаций. Всего: 2023598
🔄 Запрос #20116 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 152 спецификаций. Всего: 2023750
🔄 Запрос #20117 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 132 спецификаций. Всего: 2023882
🔄 Запрос #20118 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 126 спецификаций. Всего: 2024008
🔄 Запрос #20119 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 115 спецификаций. Всего: 2024123
🔄 Запрос #20120 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 70 спецификаций. Всего: 2024193
🔄 Запрос #20121 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 83 спецификаций. Всего: 2024276
🔄 Запрос #20122 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 69 спецификаций. Всего: 2024345
🔄 Запрос #20123 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 92 спецификаций. Всего: 2024437
🔄 Запрос #20124 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 134 спецификаций. Всего: 2024571
🔄 Запрос #20125 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 139 спецификаций. Всего: 2024710
🔄 Запрос #20126 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 56 спецификаций. Всего: 2024766
🔄 Запрос #20127 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 3 спецификаций. Всего: 2024769

🔄 Запрос #20128 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 95 спецификаций. Всего: 2024864
🔄 Запрос #20129 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 111 спецификаций. Всего: 2024975
🔄 Запрос #20130 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 137 спецификаций. Всего: 2025112
🔄 Запрос #20131 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 184 спецификаций. Всего: 2025296
🔄 Запрос #20132 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 147 спецификаций. Всего: 2025443
🔄 Запрос #20133 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 2025544
🔄 Запрос #20134 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 113 спецификаций. Всего: 2025657
🔄 Запрос #20135 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 147 спецификаций. Всего: 2025804
🔄 Запрос #20136 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 114 спецификаций. Всего: 2025918
🔄 Запрос #20137 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 93 спецификаций. Всего: 2026011
🔄 Запрос #20138 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 53 спецификаций. Всего: 2026064
🔄 Запрос #20139 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 17 спецификаций. Всего: 2026081
🔄 Запрос #20140 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 9 спецификаций. Всего: 2026090
🔄 Запрос #20141 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 70 спецификаций. Всего: 2026160
🔄 Запрос #20142 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 116 спецификаций. Всего: 2026276
🔄 Запрос #20143 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 101 спецификаций. Всего: 2026377
🔄 Запрос #20144 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 135 спецификаций. Всего: 2026512
🔄 Запрос #20145 для 2024-01-11 20:44:09 - 2024-01-18 20:44:09
📥 Загружено 36 спецификаций. Всего: 2026548
📅 Обрабатываем диапазон 2024-01-04 20:44:09 - 2024-01-11 20:44:09 (попытка 1/5)
🔄 Запрос #20146 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2026659
🔄 Запрос #20147 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2026774
🔄 Запрос #20148 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2026893
🔄 Запрос #20149 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2027003
🔄 Запрос #20150 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2027105
🔄 Запрос #20151 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 2027200
🔄 Запрос #20152 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 61 спецификаций. Всего: 2027261
🔄 Запрос #20153 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2027385
🔄 Запрос #20154 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2027518
🔄 Запрос #20155 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2027628
🔄 Запрос #20156 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2027744
🔄 Запрос #20157 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2027842
🔄 Запрос #20158 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 2027973
🔄 Запрос #20159 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 47 спецификаций. Всего: 2028020
🔄 Запрос #20160 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2028119
🔄 Запрос #20161 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2028240
🔄 Запрос #20162 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2028364
🔄 Запрос #20163 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2028494
🔄 Запрос #20164 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 142 спецификаций. Всего: 2028636
🔄 Запрос #20165 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2028758
🔄 Запрос #20166 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2028870
🔄 Запрос #20167 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2028991
🔄 Запрос #20168 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2029130
🔄 Запрос #20169 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2029258
🔄 Запрос #20170 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 2029394
🔄 Запрос #20171 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 2029526
🔄 Запрос #20172 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2029644
🔄 Запрос #20173 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 2029748
🔄 Запрос #20174 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 77 спецификаций. Всего: 2029825
🔄 Запрос #20175 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 80 спецификаций. Всего: 2029905
🔄 Запрос #20176 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2030038
🔄 Запрос #20177 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 143 спецификаций. Всего: 2030181
🔄 Запрос #20178 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 84 спецификаций. Всего: 2030265
🔄 Запрос #20179 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2030363
🔄 Запрос #20180 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 2030467
🔄 Запрос #20181 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2030578
🔄 Запрос #20182 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2030687
🔄 Запрос #20183 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2030793
🔄 Запрос #20184 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2030884
🔄 Запрос #20185 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 78 спецификаций. Всего: 2030962
🔄 Запрос #20186 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 142 спецификаций. Всего: 2031104
📤 Сохранено 10014 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #20187 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 196 спецификаций. Всего: 2031300
🔄 Запрос #20188 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 196 спецификаций. Всего: 2031496
🔄 Запрос #20189 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 198 спецификаций. Всего: 2031694
🔄 Запрос #20190 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 158 спецификаций. Всего: 2031852
🔄 Запрос #20191 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 73 спецификаций. Всего: 2031925
🔄 Запрос #20192 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2032035
🔄 Запрос #20193 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 2032123
🔄 Запрос #20194 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 2032252
🔄 Запрос #20195 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2032366
🔄 Запрос #20196 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2032465
🔄 Запрос #20197 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 47 спецификаций. Всего: 2032512
🔄 Запрос #20198 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2032640
🔄 Запрос #20199 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2032775
🔄 Запрос #20200 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2032885
🔄 Запрос #20201 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09

📥 Загружено 133 спецификаций. Всего: 2033018
🔄 Запрос #20202 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 116 спецификаций. Всего: 2033134
🔄 Запрос #20203 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2033221
🔄 Запрос #20204 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2033331
🔄 Запрос #20205 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 2033427
🔄 Запрос #20206 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2033543
🔄 Запрос #20207 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2033656
🔄 Запрос #20208 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 126 спецификаций. Всего: 2033782
🔄 Запрос #20209 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2033876
🔄 Запрос #20210 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 58 спецификаций. Всего: 2033934
🔄 Запрос #20211 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 58 спецификаций. Всего: 2033992
🔄 Запрос #20212 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2034109
🔄 Запрос #20213 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2034227
🔄 Запрос #20214 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2034339
🔄 Запрос #20215 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 156 спецификаций. Всего: 2034495
🔄 Запрос #20216 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 34 спецификаций. Всего: 2034529
🔄 Запрос #20217 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2034627
🔄 Запрос #20218 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 108 спецификаций. Всего: 2034735
🔄 Запрос #20219 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 2034828
🔄 Запрос #20220 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 2034932
🔄 Запрос #20221 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2035023
🔄 Запрос #20222 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2035158
🔄 Запрос #20223 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2035270
🔄 Запрос #20224 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 106 спецификаций. Всего: 2035376
🔄 Запрос #20225 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2035484
🔄 Запрос #20226 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2035619
🔄 Запрос #20227 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2035729
🔄 Запрос #20228 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 151 спецификаций. Всего: 2035880
🔄 Запрос #20229 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2035982
🔄 Запрос #20230 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 134 спецификаций. Всего: 2036116
🔄 Запрос #20231 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2036255
🔄 Запрос #20232 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2036341
🔄 Запрос #20233 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 36 спецификаций. Всего: 2036377
🔄 Запрос #20234 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2036494
🔄 Запрос #20235 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2036603
🔄 Запрос #20236 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 2036708
🔄 Запрос #20237 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2036830
🔄 Запрос #20238 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 2036913
🔄 Запрос #20239 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 81 спецификаций. Всего: 2036994
🔄 Запрос #20240 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 81 спецификаций. Всего: 2037075
🔄 Запрос #20241 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2037199
🔄 Запрос #20242 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 60 спецификаций. Всего: 2037259
🔄 Запрос #20243 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 62 спецификаций. Всего: 2037321
🔄 Запрос #20244 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 57 спецификаций. Всего: 2037378
🔄 Запрос #20245 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2037500
🔄 Запрос #20246 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 57 спецификаций. Всего: 2037557
🔄 Запрос #20247 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 2 спецификаций. Всего: 2037559
🔄 Запрос #20248 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 55 спецификаций. Всего: 2037614
🔄 Запрос #20249 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 84 спецификаций. Всего: 2037698
🔄 Запрос #20250 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2037822
🔄 Запрос #20251 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 2037915
🔄 Запрос #20252 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 32 спецификаций. Всего: 2037947
🔄 Запрос #20253 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2038053
🔄 Запрос #20254 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2038176
🔄 Запрос #20255 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2038289
🔄 Запрос #20256 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2038397
🔄 Запрос #20257 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 2038502
🔄 Запрос #20258 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2038604
🔄 Запрос #20259 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2038710
🔄 Запрос #20260 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 69 спецификаций. Всего: 2038779
🔄 Запрос #20261 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 69 спецификаций. Всего: 2038848
🔄 Запрос #20262 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 2038930
🔄 Запрос #20263 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 2039013
🔄 Запрос #20264 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2039126
🔄 Запрос #20265 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 69 спецификаций. Всего: 2039195
🔄 Запрос #20266 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 2039280
🔄 Запрос #20267 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2039397
🔄 Запрос #20268 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 2039497
🔄 Запрос #20269 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2039620
🔄 Запрос #20270 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2039723
🔄 Запрос #20271 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2039832
🔄 Запрос #20272 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2039929
🔄 Запрос #20273 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2040043
🔄 Запрос #20274 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09

📥 Загружено 137 спецификаций. Всего: 2040180
🔄 Запрос #20275 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2040296
🔄 Запрос #20276 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2040417
🔄 Запрос #20277 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2040552
🔄 Запрос #20278 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 2040640
🔄 Запрос #20279 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 2040744
🔄 Запрос #20280 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2040874
🔄 Запрос #20281 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 2040999
🔄 Запрос #20282 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2041127
📤 Сохранено 10023 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #20283 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2041262
🔄 Запрос #20284 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2041379
🔄 Запрос #20285 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 2041469
🔄 Запрос #20286 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2041591
🔄 Запрос #20287 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2041711
🔄 Запрос #20288 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 134 спецификаций. Всего: 2041845
🔄 Запрос #20289 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 56 спецификаций. Всего: 2041901
🔄 Запрос #20290 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2041987
🔄 Запрос #20291 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2042074
🔄 Запрос #20292 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 75 спецификаций. Всего: 2042149
🔄 Запрос #20293 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2042243
🔄 Запрос #20294 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 73 спецификаций. Всего: 2042316
🔄 Запрос #20295 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2042428
🔄 Запрос #20296 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2042534
🔄 Запрос #20297 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2042664
🔄 Запрос #20298 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2042758
🔄 Запрос #20299 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 77 спецификаций. Всего: 2042835
🔄 Запрос #20300 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2042942
🔄 Запрос #20301 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 2043052
🔄 Запрос #20302 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2043166
🔄 Запрос #20303 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 145 спецификаций. Всего: 2043311
🔄 Запрос #20304 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2043444
🔄 Запрос #20305 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2043538
🔄 Запрос #20306 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2043636
🔄 Запрос #20307 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 89 спецификаций. Всего: 2043725
🔄 Запрос #20308 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2043823
🔄 Запрос #20309 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2043937
🔄 Запрос #20310 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 126 спецификаций. Всего: 2044063
🔄 Запрос #20311 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2044169
🔄 Запрос #20312 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 134 спецификаций. Всего: 2044303
🔄 Запрос #20313 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 2044403
🔄 Запрос #20314 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2044518
🔄 Запрос #20315 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 63 спецификаций. Всего: 2044581
🔄 Запрос #20316 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2044702
🔄 Запрос #20317 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2044793
🔄 Запрос #20318 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2044903
🔄 Запрос #20319 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 118 спецификаций. Всего: 2045021
🔄 Запрос #20320 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 150 спецификаций. Всего: 2045171
🔄 Запрос #20321 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 158 спецификаций. Всего: 2045329
🔄 Запрос #20322 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 109 спецификаций. Всего: 2045438
🔄 Запрос #20323 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2045547
🔄 Запрос #20324 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 135 спецификаций. Всего: 2045682
🔄 Запрос #20325 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2045805
🔄 Запрос #20326 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 2045922
🔄 Запрос #20327 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 2046007
🔄 Запрос #20328 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 2046112
🔄 Запрос #20329 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2046222
🔄 Запрос #20330 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 137 спецификаций. Всего: 2046359
🔄 Запрос #20331 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2046475
🔄 Запрос #20332 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2046598
🔄 Запрос #20333 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2046721
🔄 Запрос #20334 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2046860
🔄 Запрос #20335 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 2046989
🔄 Запрос #20336 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 134 спецификаций. Всего: 2047123
🔄 Запрос #20337 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2047232
🔄 Запрос #20338 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2047341
🔄 Запрос #20339 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2047448
🔄 Запрос #20340 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2047564
🔄 Запрос #20341 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2047671

🔄 Запрос #20342 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 2047772
🔄 Запрос #20343 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2047893
🔄 Запрос #20344 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 17 спецификаций. Всего: 2047910
🔄 Запрос #20345 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2048028
🔄 Запрос #20346 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2048138
🔄 Запрос #20347 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2048259
🔄 Запрос #20348 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 143 спецификаций. Всего: 2048402
🔄 Запрос #20349 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2048512
🔄 Запрос #20350 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2048609
🔄 Запрос #20351 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2048729
🔄 Запрос #20352 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 2048814
🔄 Запрос #20353 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2048931
🔄 Запрос #20354 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2049018
🔄 Запрос #20355 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 60 спецификаций. Всего: 2049078
🔄 Запрос #20356 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2049177
🔄 Запрос #20357 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 2049282
🔄 Запрос #20358 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2049388
🔄 Запрос #20359 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2049504
🔄 Запрос #20360 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2049624
🔄 Запрос #20361 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 2049753
🔄 Запрос #20362 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 68 спецификаций. Всего: 2049821
🔄 Запрос #20363 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2049941
🔄 Запрос #20364 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2050052
🔄 Запрос #20365 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2050174
🔄 Запрос #20366 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 148 спецификаций. Всего: 2050322
🔄 Запрос #20367 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2050434
🔄 Запрос #20368 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2050555
🔄 Запрос #20369 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2050677
🔄 Запрос #20370 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2050780
🔄 Запрос #20371 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 104 спецификаций. Всего: 2050884
🔄 Запрос #20372 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 68 спецификаций. Всего: 2050952
🔄 Запрос #20373 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2051064
🔄 Запрос #20374 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2051158
📤 Сохранено 10031 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #20375 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2051252
🔄 Запрос #20376 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2051374
🔄 Запрос #20377 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 76 спецификаций. Всего: 2051450
🔄 Запрос #20378 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2051541
🔄 Запрос #20379 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 126 спецификаций. Всего: 2051667
🔄 Запрос #20380 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2051758
🔄 Запрос #20381 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2051856
🔄 Запрос #20382 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2051942
🔄 Запрос #20383 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 2052024
🔄 Запрос #20384 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 143 спецификаций. Всего: 2052167
🔄 Запрос #20385 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 53 спецификаций. Всего: 2052220
🔄 Запрос #20386 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 2052303
🔄 Запрос #20387 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2052406
🔄 Запрос #20388 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 2052501
🔄 Запрос #20389 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 76 спецификаций. Всего: 2052577
🔄 Запрос #20390 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 2052667
🔄 Запрос #20391 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 38 спецификаций. Всего: 2052705
🔄 Запрос #20392 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 2052787
🔄 Запрос #20393 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 2052875
🔄 Запрос #20394 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 57 спецификаций. Всего: 2052932
🔄 Запрос #20395 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 68 спецификаций. Всего: 2053000
🔄 Запрос #20396 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2053123
🔄 Запрос #20397 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 72 спецификаций. Всего: 2053195
🔄 Запрос #20398 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 76 спецификаций. Всего: 2053271
🔄 Запрос #20399 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 70 спецификаций. Всего: 2053341
🔄 Запрос #20400 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2053463
🔄 Запрос #20401 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2053557
🔄 Запрос #20402 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2053680
🔄 Запрос #20403 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 2053785
🔄 Запрос #20404 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2053910
🔄 Запрос #20405 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 2054010
🔄 Запрос #20406 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2054132
🔄 Запрос #20407 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2054245
🔄 Запрос #20408 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 89 спецификаций. Всего: 2054334
🔄 Запрос #20409 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2054452
🔄 Запрос #20410 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2054555
🔄 Запрос #20411 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2054675
🔄 Запрос #20412 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2054777
🔄 Запрос #20413 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2054890
🔄 Запрос #20414 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2055001

🔄 Запрос #20415 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2055087
🔄 Запрос #20416 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2055185
🔄 Запрос #20417 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 2055268
🔄 Запрос #20418 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2055359
🔄 Запрос #20419 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 2055460
🔄 Запрос #20420 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2055576
🔄 Запрос #20421 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 65 спецификаций. Всего: 2055641
🔄 Запрос #20422 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2055740
🔄 Запрос #20423 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2055870
🔄 Запрос #20424 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 2055974
🔄 Запрос #20425 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 130 спецификаций. Всего: 2056104
🔄 Запрос #20426 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2056203
🔄 Запрос #20427 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2056322
🔄 Запрос #20428 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2056443
🔄 Запрос #20429 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2056576
🔄 Запрос #20430 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 2056712
🔄 Запрос #20431 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 146 спецификаций. Всего: 2056858
🔄 Запрос #20432 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 75 спецификаций. Всего: 2056933
🔄 Запрос #20433 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2057058
🔄 Запрос #20434 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2057165
🔄 Запрос #20435 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2057292
🔄 Запрос #20436 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 2057384
🔄 Запрос #20437 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 2057516
🔄 Запрос #20438 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 2057612
🔄 Запрос #20439 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2057742
🔄 Запрос #20440 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2057851
🔄 Запрос #20441 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 2057944
🔄 Запрос #20442 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2058051
🔄 Запрос #20443 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 61 спецификаций. Всего: 2058112
🔄 Запрос #20444 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 78 спецификаций. Всего: 2058190
🔄 Запрос #20445 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2058299
🔄 Запрос #20446 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2058419
🔄 Запрос #20447 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2058525
🔄 Запрос #20448 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 2058615
🔄 Запрос #20449 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2058722
🔄 Запрос #20450 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 2058810
🔄 Запрос #20451 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 70 спецификаций. Всего: 2058880
🔄 Запрос #20452 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 2058970
🔄 Запрос #20453 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 62 спецификаций. Всего: 2059032
🔄 Запрос #20454 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 89 спецификаций. Всего: 2059121
🔄 Запрос #20455 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2059227
🔄 Запрос #20456 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 99 спецификаций. Всего: 2059326
🔄 Запрос #20457 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2059438
🔄 Запрос #20458 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 77 спецификаций. Всего: 2059515
🔄 Запрос #20459 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2059612
🔄 Запрос #20460 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2059715
🔄 Запрос #20461 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 2059815
🔄 Запрос #20462 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 2059919
🔄 Запрос #20463 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 77 спецификаций. Всего: 2059996
🔄 Запрос #20464 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2060087
🔄 Запрос #20465 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2060173
🔄 Запрос #20466 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 78 спецификаций. Всего: 2060251
🔄 Запрос #20467 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2060359
🔄 Запрос #20468 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 70 спецификаций. Всего: 2060429
🔄 Запрос #20469 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 96 спецификаций. Всего: 2060525
🔄 Запрос #20470 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 2060617
🔄 Запрос #20471 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 2060717
🔄 Запрос #20472 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 69 спецификаций. Всего: 2060786
🔄 Запрос #20473 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 93 спецификаций. Всего: 2060879
🔄 Запрос #20474 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 23 спецификаций. Всего: 2060902
🔄 Запрос #20475 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 74 спецификаций. Всего: 2060976
🔄 Запрос #20476 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2061063
🔄 Запрос #20477 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 2061155
🔄 Запрос #20478 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 60 спецификаций. Всего: 2061215
📤 Сохранено 10057 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #20479 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2061306
🔄 Запрос #20480 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2061404
🔄 Запрос #20481 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 2061499
🔄 Запрос #20482 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 2061581
🔄 Запрос #20483 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 30 спецификаций. Всего: 2061611

🔄 Запрос #20484 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 59 спецификаций. Всего: 2061670
🔄 Запрос #20485 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 78 спецификаций. Всего: 2061748
🔄 Запрос #20486 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 80 спецификаций. Всего: 2061828
🔄 Запрос #20487 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 78 спецификаций. Всего: 2061906
🔄 Запрос #20488 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 2061988
🔄 Запрос #20489 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2062090
🔄 Запрос #20490 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 62 спецификаций. Всего: 2062152
🔄 Запрос #20491 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2062246
🔄 Запрос #20492 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2062371
🔄 Запрос #20493 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2062495
🔄 Запрос #20494 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 2062587
🔄 Запрос #20495 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 75 спецификаций. Всего: 2062662
🔄 Запрос #20496 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 59 спецификаций. Всего: 2062721
🔄 Запрос #20497 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 137 спецификаций. Всего: 2062858
🔄 Запрос #20498 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2062971
🔄 Запрос #20499 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 69 спецификаций. Всего: 2063040
🔄 Запрос #20500 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2063150
🔄 Запрос #20501 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2063260
🔄 Запрос #20502 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2063383
🔄 Запрос #20503 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2063500
🔄 Запрос #20504 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2063598
🔄 Запрос #20505 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2063726
🔄 Запрос #20506 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 113 спецификаций. Всего: 2063839
🔄 Запрос #20507 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 57 спецификаций. Всего: 2063896
🔄 Запрос #20508 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 2063979
🔄 Запрос #20509 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2064104
🔄 Запрос #20510 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 2064235
🔄 Запрос #20511 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 145 спецификаций. Всего: 2064380
🔄 Запрос #20512 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2064501
🔄 Запрос #20513 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 65 спецификаций. Всего: 2064566
🔄 Запрос #20514 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2064696
🔄 Запрос #20515 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 153 спецификаций. Всего: 2064849
🔄 Запрос #20516 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2064972
🔄 Запрос #20517 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 2065099
🔄 Запрос #20518 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 155 спецификаций. Всего: 2065254
🔄 Запрос #20519 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2065389
🔄 Запрос #20520 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 143 спецификаций. Всего: 2065532
🔄 Запрос #20521 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2065660
🔄 Запрос #20522 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 138 спецификаций. Всего: 2065798
🔄 Запрос #20523 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 134 спецификаций. Всего: 2065932
🔄 Запрос #20524 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2066048
🔄 Запрос #20525 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2066161
🔄 Запрос #20526 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2066263
🔄 Запрос #20527 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2066390
🔄 Запрос #20528 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 2066483
🔄 Запрос #20529 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2066608
🔄 Запрос #20530 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2066714
🔄 Запрос #20531 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 2066850
🔄 Запрос #20532 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 2066982
🔄 Запрос #20533 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 148 спецификаций. Всего: 2067130
🔄 Запрос #20534 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2067241
🔄 Запрос #20535 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2067358
🔄 Запрос #20536 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2067486
🔄 Запрос #20537 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2067605
🔄 Запрос #20538 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2067733
🔄 Запрос #20539 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2067844
🔄 Запрос #20540 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 2067976
🔄 Запрос #20541 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 60 спецификаций. Всего: 2068036
🔄 Запрос #20542 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2068155
🔄 Запрос #20543 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2068246
🔄 Запрос #20544 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 57 спецификаций. Всего: 2068303
🔄 Запрос #20545 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2068419
🔄 Запрос #20546 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2068549
🔄 Запрос #20547 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2068672
🔄 Запрос #20548 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2068793
🔄 Запрос #20549 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 125 спецификаций. Всего: 2068918
🔄 Запрос #20550 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 150 спецификаций. Всего: 2069068
🔄 Запрос #20551 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 142 спецификаций. Всего: 2069210
🔄 Запрос #20552 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 2069314
🔄 Запрос #20553 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2069434
🔄 Запрос #20554 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2069562

🔄 Запрос #20555 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2069678
🔄 Запрос #20556 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 2069773
🔄 Запрос #20557 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 73 спецификаций. Всего: 2069846
🔄 Запрос #20558 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2069933
🔄 Запрос #20559 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2070050
🔄 Запрос #20560 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2070163
🔄 Запрос #20561 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2070290
🔄 Запрос #20562 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 2070382
🔄 Запрос #20563 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2070492
🔄 Запрос #20564 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2070600
🔄 Запрос #20565 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 39 спецификаций. Всего: 2070639
🔄 Запрос #20566 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 140 спецификаций. Всего: 2070779
🔄 Запрос #20567 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2070892
🔄 Запрос #20568 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2071002
🔄 Запрос #20569 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2071126
🔄 Запрос #20570 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 144 спецификаций. Всего: 2071270
📤 Сохранено 10055 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #20571 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2071379
🔄 Запрос #20572 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2071494
🔄 Запрос #20573 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2071604
🔄 Запрос #20574 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2071722
🔄 Запрос #20575 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2071825
🔄 Запрос #20576 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2071932
🔄 Запрос #20577 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 2072027
🔄 Запрос #20578 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 75 спецификаций. Всего: 2072102
🔄 Запрос #20579 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 2072192
🔄 Запрос #20580 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 2072297
🔄 Запрос #20581 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2072411
🔄 Запрос #20582 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 2072496
🔄 Запрос #20583 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 81 спецификаций. Всего: 2072577
🔄 Запрос #20584 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 34 спецификаций. Всего: 2072611
🔄 Запрос #20585 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 2072703
🔄 Запрос #20586 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2072806
🔄 Запрос #20587 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 2072910
🔄 Запрос #20588 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 61 спецификаций. Всего: 2072971
🔄 Запрос #20589 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2073057
🔄 Запрос #20590 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 2073150
🔄 Запрос #20591 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2073237
🔄 Запрос #20592 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 2073320
🔄 Запрос #20593 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 2073416
🔄 Запрос #20594 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 2073521
🔄 Запрос #20595 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 2073616
🔄 Запрос #20596 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2073730
🔄 Запрос #20597 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2073844
🔄 Запрос #20598 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2073938
🔄 Запрос #20599 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2074032
🔄 Запрос #20600 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2074154
🔄 Запрос #20601 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2074264
🔄 Запрос #20602 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2074399
🔄 Запрос #20603 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2074518
🔄 Запрос #20604 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2074653
🔄 Запрос #20605 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2074770
🔄 Запрос #20606 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 81 спецификаций. Всего: 2074851
🔄 Запрос #20607 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2074971
🔄 Запрос #20608 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 141 спецификаций. Всего: 2075112
🔄 Запрос #20609 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2075231
🔄 Запрос #20610 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2075318
🔄 Запрос #20611 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2075448
🔄 Запрос #20612 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2075542
🔄 Запрос #20613 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2075662
🔄 Запрос #20614 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2075789
🔄 Запрос #20615 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2075912
🔄 Запрос #20616 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2076025
🔄 Запрос #20617 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 2076154
🔄 Запрос #20618 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2076275
🔄 Запрос #20619 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2076414
🔄 Запрос #20620 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 72 спецификаций. Всего: 2076486
🔄 Запрос #20621 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2076601
🔄 Запрос #20622 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2076716
🔄 Запрос #20623 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2076841
🔄 Запрос #20624 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 2076931
🔄 Запрос #20625 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 73 спецификаций. Всего: 2077004
🔄 Запрос #20626 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 52 спецификаций. Всего: 2077056
🔄 Запрос #20627 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2077153
🔄 Запрос #20628 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2077280
🔄 Запрос #20629 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 84 спецификаций. Всего: 2077364

🔄 Запрос #20630 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 2077500
🔄 Запрос #20631 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 2077624
🔄 Запрос #20632 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2077731
🔄 Запрос #20633 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2077855
🔄 Запрос #20634 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 74 спецификаций. Всего: 2077929
🔄 Запрос #20635 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 75 спецификаций. Всего: 2078004
🔄 Запрос #20636 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2078137
🔄 Запрос #20637 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 2078238
🔄 Запрос #20638 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2078352
🔄 Запрос #20639 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2078468
🔄 Запрос #20640 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 2078573
🔄 Запрос #20641 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 72 спецификаций. Всего: 2078645
🔄 Запрос #20642 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 72 спецификаций. Всего: 2078717
🔄 Запрос #20643 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 2078809
🔄 Запрос #20644 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2078936
🔄 Запрос #20645 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2079030
🔄 Запрос #20646 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 6 спецификаций. Всего: 2079036
🔄 Запрос #20647 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 2079121
🔄 Запрос #20648 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2079208
🔄 Запрос #20649 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2079323
🔄 Запрос #20650 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 104 спецификаций. Всего: 2079427
🔄 Запрос #20651 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 69 спецификаций. Всего: 2079496
🔄 Запрос #20652 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 80 спецификаций. Всего: 2079576
🔄 Запрос #20653 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2079689
🔄 Запрос #20654 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2079791
🔄 Запрос #20655 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 26 спецификаций. Всего: 2079817
🔄 Запрос #20656 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2079904
🔄 Запрос #20657 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2079990
🔄 Запрос #20658 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 2080122
🔄 Запрос #20659 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2080257
🔄 Запрос #20660 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2080385
🔄 Запрос #20661 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 162 спецификаций. Всего: 2080547
🔄 Запрос #20662 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 2080679
🔄 Запрос #20663 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2080806
🔄 Запрос #20664 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 2080901
🔄 Запрос #20665 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 78 спецификаций. Всего: 2080979
🔄 Запрос #20666 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 63 спецификаций. Всего: 2081042
🔄 Запрос #20667 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2081155
🔄 Запрос #20668 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 45 спецификаций. Всего: 2081200
🔄 Запрос #20669 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2081306
📤 Сохранено 10036 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #20670 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 49 спецификаций. Всего: 2081355
🔄 Запрос #20671 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 70 спецификаций. Всего: 2081425
🔄 Запрос #20672 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2081544
🔄 Запрос #20673 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2081667
🔄 Запрос #20674 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2081758
🔄 Запрос #20675 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 52 спецификаций. Всего: 2081810
🔄 Запрос #20676 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2081913
🔄 Запрос #20677 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 84 спецификаций. Всего: 2081997
🔄 Запрос #20678 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2082111
🔄 Запрос #20679 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2082208
🔄 Запрос #20680 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2082318
🔄 Запрос #20681 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 2082449
🔄 Запрос #20682 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2082577
🔄 Запрос #20683 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 200 спецификаций. Всего: 2082777
🔄 Запрос #20684 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 180 спецификаций. Всего: 2082957
🔄 Запрос #20685 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2083085
🔄 Запрос #20686 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 72 спецификаций. Всего: 2083157
🔄 Запрос #20687 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 150 спецификаций. Всего: 2083307
🔄 Запрос #20688 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 152 спецификаций. Всего: 2083459
🔄 Запрос #20689 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2083570
🔄 Запрос #20690 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2083694
🔄 Запрос #20691 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2083803
🔄 Запрос #20692 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2083931
🔄 Запрос #20693 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2084043
🔄 Запрос #20694 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2084130
🔄 Запрос #20695 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2084249
🔄 Запрос #20696 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2084382
🔄 Запрос #20697 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2084493
🔄 Запрос #20698 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2084612
🔄 Запрос #20699 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 154 спецификаций. Всего: 2084766
🔄 Запрос #20700 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2084893
🔄 Запрос #20701 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 140 спецификаций. Всего: 2085033

🔄 Запрос #20702 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2085158
🔄 Запрос #20703 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2085286
🔄 Запрос #20704 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 2085417
🔄 Запрос #20705 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2085544
🔄 Запрос #20706 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 150 спецификаций. Всего: 2085694
🔄 Запрос #20707 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 143 спецификаций. Всего: 2085837
🔄 Запрос #20708 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 2085957
🔄 Запрос #20709 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2086079
🔄 Запрос #20710 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 2086169
🔄 Запрос #20711 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2086268
🔄 Запрос #20712 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2086378
🔄 Запрос #20713 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2086503
🔄 Запрос #20714 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 150 спецификаций. Всего: 2086653
🔄 Запрос #20715 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2086772
🔄 Запрос #20716 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 134 спецификаций. Всего: 2086906
🔄 Запрос #20717 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2087017
🔄 Запрос #20718 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2087145
🔄 Запрос #20719 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 137 спецификаций. Всего: 2087282
🔄 Запрос #20720 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 2087418
🔄 Запрос #20721 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
⚠️ Ошибка (попытка 3/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
Сервер недоступен. Ожидаем восстановления связи...
Проблема с запросом — повторяем диапазон.
Диапазон не завершен, повторяем через 30 секунд...
📅 Обрабатываем диапазон 2024-01-04 20:44:09 - 2024-01-11 20:44:09 (попытка 2/5)
🔄 Запрос #20722 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2087539
🔄 Запрос #20723 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 35 спецификаций. Всего: 2087574
🔄 Запрос #20724 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2087686
🔄 Запрос #20725 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2087802
🔄 Запрос #20726 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 2087933
🔄 Запрос #20727 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2088053
🔄 Запрос #20728 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 143 спецификаций. Всего: 2088196
🔄 Запрос #20729 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 126 спецификаций. Всего: 2088322
🔄 Запрос #20730 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 2088423
🔄 Запрос #20731 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 2088518
🔄 Запрос #20732 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 2088622
🔄 Запрос #20733 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2088719
🔄 Запрос #20734 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 2088816
🔄 Запрос #20735 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2088930
🔄 Запрос #20736 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2089036
🔄 Запрос #20737 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2089154
🔄 Запрос #20738 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2089268
🔄 Запрос #20739 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2089391
🔄 Запрос #20740 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 55 спецификаций. Всего: 2089446
🔄 Запрос #20741 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2089574
🔄 Запрос #20742 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 2089703
🔄 Запрос #20743 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2089794
🔄 Запрос #20744 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2089912
🔄 Запрос #20745 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2090019
🔄 Запрос #20746 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2090135
🔄 Запрос #20747 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2090256
🔄 Запрос #20748 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2090379
🔄 Запрос #20749 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2090503
🔄 Запрос #20750 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2090616
🔄 Запрос #20751 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 129 спецификаций. Всего: 2090745
🔄 Запрос #20752 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2090867
🔄 Запрос #20753 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2090986
🔄 Запрос #20754 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2091108
🔄 Запрос #20755 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2091207
🔄 Запрос #20756 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 2091339
📤 Сохранено 10033 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #20757 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 134 спецификаций. Всего: 2091473
🔄 Запрос #20758 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2091587
🔄 Запрос #20759 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2091704
🔄 Запрос #20760 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 137 спецификаций. Всего: 2091841
🔄 Запрос #20761 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2091954
🔄 Запрос #20762 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2092093
🔄 Запрос #20763 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 2092175
🔄 Запрос #20764 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 2092260
🔄 Запрос #20765 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2092399
🔄 Запрос #20766 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 70 спецификаций. Всего: 2092469
🔄 Запрос #20767 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09

📥 Загружено 121 спецификаций. Всего: 2092590
🔄 Запрос #20768 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 146 спецификаций. Всего: 2092736
🔄 Запрос #20769 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 2092868
🔄 Запрос #20770 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 2093000
🔄 Запрос #20771 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2093113
🔄 Запрос #20772 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2093199
🔄 Запрос #20773 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2093309
🔄 Запрос #20774 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2093406
🔄 Запрос #20775 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2093512
🔄 Запрос #20776 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 74 спецификаций. Всего: 2093586
🔄 Запрос #20777 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2093709
🔄 Запрос #20778 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 78 спецификаций. Всего: 2093787
🔄 Запрос #20779 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 141 спецификаций. Всего: 2093928
🔄 Запрос #20780 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2094053
🔄 Запрос #20781 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 75 спецификаций. Всего: 2094128
🔄 Запрос #20782 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 157 спецификаций. Всего: 2094285
🔄 Запрос #20783 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2094406
🔄 Запрос #20784 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 168 спецификаций. Всего: 2094574
🔄 Запрос #20785 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 2094669
🔄 Запрос #20786 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 76 спецификаций. Всего: 2094745
🔄 Запрос #20787 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2094864
🔄 Запрос #20788 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 2094996
🔄 Запрос #20789 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 68 спецификаций. Всего: 2095064
🔄 Запрос #20790 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 2095146
🔄 Запрос #20791 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 67 спецификаций. Всего: 2095213
🔄 Запрос #20792 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2095304
🔄 Запрос #20793 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 142 спецификаций. Всего: 2095446
🔄 Запрос #20794 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 2095582
🔄 Запрос #20795 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2095712
🔄 Запрос #20796 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 155 спецификаций. Всего: 2095867
🔄 Запрос #20797 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2095978
🔄 Запрос #20798 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2096076
🔄 Запрос #20799 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2096173
🔄 Запрос #20800 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2096275
🔄 Запрос #20801 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2096373
🔄 Запрос #20802 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2096485
🔄 Запрос #20803 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 141 спецификаций. Всего: 2096626
🔄 Запрос #20804 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 166 спецификаций. Всего: 2096792
🔄 Запрос #20805 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2096906
🔄 Запрос #20806 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2097008
🔄 Запрос #20807 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2097124
🔄 Запрос #20808 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 2097225
🔄 Запрос #20809 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2097348
🔄 Запрос #20810 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 119 спецификаций. Всего: 2097467
🔄 Запрос #20811 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2097594
🔄 Запрос #20812 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2097680
🔄 Запрос #20813 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2097783
🔄 Запрос #20814 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 143 спецификаций. Всего: 2097926
🔄 Запрос #20815 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2098061
🔄 Запрос #20816 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2098180
🔄 Запрос #20817 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 71 спецификаций. Всего: 2098251
🔄 Запрос #20818 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 76 спецификаций. Всего: 2098327
🔄 Запрос #20819 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2098430
🔄 Запрос #20820 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2098536
🔄 Запрос #20821 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 74 спецификаций. Всего: 2098610
🔄 Запрос #20822 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2098709
🔄 Запрос #20823 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2098830
🔄 Запрос #20824 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2098944
🔄 Запрос #20825 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 2099040
🔄 Запрос #20826 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2099146
🔄 Запрос #20827 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 10 спецификаций. Всего: 2099156
🔄 Запрос #20828 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2099254
🔄 Запрос #20829 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 153 спецификаций. Всего: 2099407
🔄 Запрос #20830 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2099531
🔄 Запрос #20831 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2099644
🔄 Запрос #20832 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2099774
🔄 Запрос #20833 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2099881
🔄 Запрос #20834 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 134 спецификаций. Всего: 2100015
🔄 Запрос #20835 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 2100120
🔄 Запрос #20836 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2100241
🔄 Запрос #20837 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2100359
🔄 Запрос #20838 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2100469
🔄 Запрос #20839 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 144 спецификаций. Всего: 2100613
🔄 Запрос #20840 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2100737
🔄 Запрос #20841 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 158 спецификаций. Всего: 2100895
🔄 Запрос #20842 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09

📥 Загружено 123 спецификаций. Всего: 2101018
🔄 Запрос #20843 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 2101103
🔄 Запрос #20844 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2101218
🔄 Запрос #20845 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2101332
🔄 Запрос #20846 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2101418
📤 Сохранено 10079 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #20847 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2101546
🔄 Запрос #20848 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 146 спецификаций. Всего: 2101692
🔄 Запрос #20849 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2101819
🔄 Запрос #20850 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 72 спецификаций. Всего: 2101891
🔄 Запрос #20851 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2101994
🔄 Запрос #20852 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2102085
🔄 Запрос #20853 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2102187
🔄 Запрос #20854 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 176 спецификаций. Всего: 2102363
🔄 Запрос #20855 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 138 спецификаций. Всего: 2102501
🔄 Запрос #20856 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2102621
🔄 Запрос #20857 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2102715
🔄 Запрос #20858 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 2102815
🔄 Запрос #20859 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2102934
🔄 Запрос #20860 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2103042
🔄 Запрос #20861 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 66 спецификаций. Всего: 2103108
🔄 Запрос #20862 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 2103190
🔄 Запрос #20863 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2103304
🔄 Запрос #20864 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2103401
🔄 Запрос #20865 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2103510
🔄 Запрос #20866 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2103632
🔄 Запрос #20867 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2103753
🔄 Запрос #20868 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2103874
🔄 Запрос #20869 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 134 спецификаций. Всего: 2104008
🔄 Запрос #20870 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2104143
🔄 Запрос #20871 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 70 спецификаций. Всего: 2104213
🔄 Запрос #20872 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 30 спецификаций. Всего: 2104243
🔄 Запрос #20873 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 2104338
🔄 Запрос #20874 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 53 спецификаций. Всего: 2104391
🔄 Запрос #20875 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 62 спецификаций. Всего: 2104453
🔄 Запрос #20876 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 117 спецификаций. Всего: 2104570
🔄 Запрос #20877 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2104668
🔄 Запрос #20878 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 74 спецификаций. Всего: 2104742
🔄 Запрос #20879 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 72 спецификаций. Всего: 2104814
🔄 Запрос #20880 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 2104906
🔄 Запрос #20881 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 140 спецификаций. Всего: 2105046
🔄 Запрос #20882 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2105163
🔄 Запрос #20883 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2105272
🔄 Запрос #20884 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2105359
🔄 Запрос #20885 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 73 спецификаций. Всего: 2105432
🔄 Запрос #20886 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 13 спецификаций. Всего: 2105445
🔄 Запрос #20887 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2105562
🔄 Запрос #20888 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2105674
🔄 Запрос #20889 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2105789
🔄 Запрос #20890 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2105907
🔄 Запрос #20891 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2106014
🔄 Запрос #20892 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2106122
🔄 Запрос #20893 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2106229
🔄 Запрос #20894 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2106364
🔄 Запрос #20895 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2106463
🔄 Запрос #20896 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2106581
🔄 Запрос #20897 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 2106682
🔄 Запрос #20898 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 50 спецификаций. Всего: 2106732
🔄 Запрос #20899 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2106841
🔄 Запрос #20900 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 81 спецификаций. Всего: 2106922
🔄 Запрос #20901 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 74 спецификаций. Всего: 2106996
🔄 Запрос #20902 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 2107127
🔄 Запрос #20903 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 2107228
🔄 Запрос #20904 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 142 спецификаций. Всего: 2107370
🔄 Запрос #20905 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2107461
🔄 Запрос #20906 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 89 спецификаций. Всего: 2107550
🔄 Запрос #20907 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 2107679
🔄 Запрос #20908 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 135 спецификаций. Всего: 2107814
🔄 Запрос #20909 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2107912
🔄 Запрос #20910 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2108015
🔄 Запрос #20911 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 2108098
🔄 Запрос #20912 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 14 спецификаций. Всего: 2108112
🔄 Запрос #20913 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 53 спецификаций. Всего: 2108165

🔄 Запрос #20914 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2108251
🔄 Запрос #20915 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 137 спецификаций. Всего: 2108388
🔄 Запрос #20916 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2108475
🔄 Запрос #20917 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2108569
🔄 Запрос #20918 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2108686
🔄 Запрос #20919 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2108777
🔄 Запрос #20920 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 46 спецификаций. Всего: 2108823
🔄 Запрос #20921 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2108929
🔄 Запрос #20922 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2109049
🔄 Запрос #20923 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2109171
🔄 Запрос #20924 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 2109259
🔄 Запрос #20925 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 2109390
🔄 Запрос #20926 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2109517
🔄 Запрос #20927 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 137 спецификаций. Всего: 2109654
🔄 Запрос #20928 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2109748
🔄 Запрос #20929 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2109851
🔄 Запрос #20930 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 2109987
🔄 Запрос #20931 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2110111
🔄 Запрос #20932 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 149 спецификаций. Всего: 2110260
🔄 Запрос #20933 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2110367
🔄 Запрос #20934 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 57 спецификаций. Всего: 2110424
🔄 Запрос #20935 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2110532
🔄 Запрос #20936 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2110642
🔄 Запрос #20937 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2110763
🔄 Запрос #20938 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 144 спецификаций. Всего: 2110907
🔄 Запрос #20939 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 2111008
🔄 Запрос #20940 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 2111093
🔄 Запрос #20941 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 66 спецификаций. Всего: 2111159
🔄 Запрос #20942 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 31 спецификаций. Всего: 2111190
🔄 Запрос #20943 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 74 спецификаций. Всего: 2111264
🔄 Запрос #20944 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 32 спецификаций. Всего: 2111296
🔄 Запрос #20945 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 2 спецификаций. Всего: 2111298
🔄 Запрос #20946 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 51 спецификаций. Всего: 2111349
🔄 Запрос #20947 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2111463
📤 Сохранено 10045 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #20948 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2111554
🔄 Запрос #20949 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 75 спецификаций. Всего: 2111629
🔄 Запрос #20950 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 2111721
🔄 Запрос #20951 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 76 спецификаций. Всего: 2111797
🔄 Запрос #20952 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 73 спецификаций. Всего: 2111870
🔄 Запрос #20953 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 142 спецификаций. Всего: 2112012
🔄 Запрос #20954 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2112151
🔄 Запрос #20955 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2112242
🔄 Запрос #20956 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 149 спецификаций. Всего: 2112391
🔄 Запрос #20957 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 50 спецификаций. Всего: 2112441
🔄 Запрос #20958 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2112556
🔄 Запрос #20959 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 121 спецификаций. Всего: 2112677
🔄 Запрос #20960 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 2112770
🔄 Запрос #20961 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2112892
🔄 Запрос #20962 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2113020
🔄 Запрос #20963 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 2113149
🔄 Запрос #20964 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2113258
🔄 Запрос #20965 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 64 спецификаций. Всего: 2113322
🔄 Запрос #20966 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 58 спецификаций. Всего: 2113380
🔄 Запрос #20967 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2113467
🔄 Запрос #20968 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2113566
🔄 Запрос #20969 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2113672
🔄 Запрос #20970 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2113789
🔄 Запрос #20971 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2113903
🔄 Запрос #20972 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2114010
🔄 Запрос #20973 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 2114095
🔄 Запрос #20974 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2114197
🔄 Запрос #20975 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 104 спецификаций. Всего: 2114301
🔄 Запрос #20976 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2114400
🔄 Запрос #20977 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 2114536
🔄 Запрос #20978 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2114633
🔄 Запрос #20979 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2114732
🔄 Запрос #20980 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2114856
🔄 Запрос #20981 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2114989
🔄 Запрос #20982 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2115101
🔄 Запрос #20983 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 84 спецификаций. Всего: 2115185
🔄 Запрос #20984 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2115309
🔄 Запрос #20985 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 58 спецификаций. Всего: 2115367
🔄 Запрос #20986 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09

📥 Загружено 100 спецификаций. Всего: 2115467
🔄 Запрос #20987 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 77 спецификаций. Всего: 2115544
🔄 Запрос #20988 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2115663
🔄 Запрос #20989 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2115781
🔄 Запрос #20990 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 2115871
🔄 Запрос #20991 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2115982
🔄 Запрос #20992 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 82 спецификаций. Всего: 2116064
🔄 Запрос #20993 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2116177
🔄 Запрос #20994 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2116289
🔄 Запрос #20995 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 2116377
🔄 Запрос #20996 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 70 спецификаций. Всего: 2116447
🔄 Запрос #20997 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 142 спецификаций. Всего: 2116589
🔄 Запрос #20998 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 134 спецификаций. Всего: 2116723
🔄 Запрос #20999 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 61 спецификаций. Всего: 2116784
🔄 Запрос #21000 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2116893
🔄 Запрос #21001 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 141 спецификаций. Всего: 2117034
🔄 Запрос #21002 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2117147
🔄 Запрос #21003 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 150 спецификаций. Всего: 2117297
🔄 Запрос #21004 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2117400
🔄 Запрос #21005 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 100 спецификаций. Всего: 2117500
🔄 Запрос #21006 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2117621
🔄 Запрос #21007 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 87 спецификаций. Всего: 2117708
🔄 Запрос #21008 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2117819
🔄 Запрос #21009 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 31 спецификаций. Всего: 2117850
🔄 Запрос #21010 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 61 спецификаций. Всего: 2117911
🔄 Запрос #21011 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 100 спецификаций. Всего: 2118011
🔄 Запрос #21012 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2118130
🔄 Запрос #21013 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 2118227
🔄 Запрос #21014 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 126 спецификаций. Всего: 2118353
🔄 Запрос #21015 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2118460
🔄 Запрос #21016 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2118559
🔄 Запрос #21017 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2118656
🔄 Запрос #21018 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2118763
🔄 Запрос #21019 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2118862
🔄 Запрос #21020 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2118970
🔄 Запрос #21021 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2119091
🔄 Запрос #21022 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 146 спецификаций. Всего: 2119237
🔄 Запрос #21023 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 2119366
🔄 Запрос #21024 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2119493
🔄 Запрос #21025 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2119616
🔄 Запрос #21026 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 168 спецификаций. Всего: 2119784
🔄 Запрос #21027 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2119894
🔄 Запрос #21028 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2120029
🔄 Запрос #21029 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 1 спецификаций. Всего: 2120030
🔄 Запрос #21030 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2120136
🔄 Запрос #21031 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 144 спецификаций. Всего: 2120280
🔄 Запрос #21032 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 124 спецификаций. Всего: 2120404
🔄 Запрос #21033 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2120518
🔄 Запрос #21034 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 2120647
🔄 Запрос #21035 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2120759
🔄 Запрос #21036 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2120856
🔄 Запрос #21037 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2120965
🔄 Запрос #21038 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2121104
🔄 Запрос #21039 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 153 спецификаций. Всего: 2121257
🔄 Запрос #21040 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2121373
🔄 Запрос #21041 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2121512
📤 Сохранено 10049 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #21042 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 150 спецификаций. Всего: 2121662
🔄 Запрос #21043 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 2121791
🔄 Запрос #21044 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2121913
🔄 Запрос #21045 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2121999
🔄 Запрос #21046 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2122115
🔄 Запрос #21047 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2122240
🔄 Запрос #21048 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 64 спецификаций. Всего: 2122304
🔄 Запрос #21049 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 45 спецификаций. Всего: 2122349
🔄 Запрос #21050 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2122463
🔄 Запрос #21051 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2122573
🔄 Запрос #21052 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2122675
🔄 Запрос #21053 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 2122771
🔄 Запрос #21054 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 138 спецификаций. Всего: 2122909
🔄 Запрос #21055 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2123048
🔄 Запрос #21056 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2123169
🔄 Запрос #21057 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09

📥 Загружено 85 спецификаций. Всего: 2123254
🔄 Запрос #21058 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2123363
🔄 Запрос #21059 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2123479
🔄 Запрос #21060 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2123609
🔄 Запрос #21061 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 120 спецификаций. Всего: 2123729
🔄 Запрос #21062 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 131 спецификаций. Всего: 2123860
🔄 Запрос #21063 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 134 спецификаций. Всего: 2123994
🔄 Запрос #21064 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2124103
🔄 Запрос #21065 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 2124195
🔄 Запрос #21066 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2124302
🔄 Запрос #21067 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2124405
🔄 Запрос #21068 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 2124498
🔄 Запрос #21069 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2124606
🔄 Запрос #21070 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2124726
🔄 Запрос #21071 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2124848
🔄 Запрос #21072 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2124965
🔄 Запрос #21073 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2125068
🔄 Запрос #21074 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2125186
🔄 Запрос #21075 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 166 спецификаций. Всего: 2125352
🔄 Запрос #21076 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 141 спецификаций. Всего: 2125493
🔄 Запрос #21077 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2125601
🔄 Запрос #21078 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2125731
🔄 Запрос #21079 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2125854
🔄 Запрос #21080 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 121 спецификаций. Всего: 2125975
🔄 Запрос #21081 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 155 спецификаций. Всего: 2126130
🔄 Запрос #21082 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2126257
🔄 Запрос #21083 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 144 спецификаций. Всего: 2126401
🔄 Запрос #21084 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 140 спецификаций. Всего: 2126541
🔄 Запрос #21085 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2126680
🔄 Запрос #21086 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 132 спецификаций. Всего: 2126812
🔄 Запрос #21087 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2126928
🔄 Запрос #21088 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2127047
🔄 Запрос #21089 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 163 спецификаций. Всего: 2127210
🔄 Запрос #21090 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2127335
🔄 Запрос #21091 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2127468
🔄 Запрос #21092 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 153 спецификаций. Всего: 2127621
🔄 Запрос #21093 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2127735
🔄 Запрос #21094 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 126 спецификаций. Всего: 2127861
🔄 Запрос #21095 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 148 спецификаций. Всего: 2128009
🔄 Запрос #21096 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 129 спецификаций. Всего: 2128138
🔄 Запрос #21097 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 143 спецификаций. Всего: 2128281
🔄 Запрос #21098 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 146 спецификаций. Всего: 2128427
🔄 Запрос #21099 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2128541
🔄 Запрос #21100 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 2128634
🔄 Запрос #21101 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 166 спецификаций. Всего: 2128800
🔄 Запрос #21102 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2128933
🔄 Запрос #21103 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2129050
🔄 Запрос #21104 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2129153
🔄 Запрос #21105 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2129286
🔄 Запрос #21106 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2129393
🔄 Запрос #21107 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 137 спецификаций. Всего: 2129530
🔄 Запрос #21108 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2129632
🔄 Запрос #21109 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2129738
🔄 Запрос #21110 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 85 спецификаций. Всего: 2129823
🔄 Запрос #21111 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 142 спецификаций. Всего: 2129965
🔄 Запрос #21112 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 69 спецификаций. Всего: 2130034
🔄 Запрос #21113 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 103 спецификаций. Всего: 2130137
🔄 Запрос #21114 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2130267
🔄 Запрос #21115 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 152 спецификаций. Всего: 2130419
🔄 Запрос #21116 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 137 спецификаций. Всего: 2130556
🔄 Запрос #21117 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 137 спецификаций. Всего: 2130693
🔄 Запрос #21118 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2130808
🔄 Запрос #21119 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2130899
🔄 Запрос #21120 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 67 спецификаций. Всего: 2130966
🔄 Запрос #21121 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 2131067
🔄 Запрос #21122 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2131174
🔄 Запрос #21123 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 138 спецификаций. Всего: 2131312
🔄 Запрос #21124 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 127 спецификаций. Всего: 2131439
🔄 Запрос #21125 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2131557
📤 Сохранено 10045 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #21126 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2131684
🔄 Запрос #21127 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 78 спецификаций. Всего: 2131762
🔄 Запрос #21128 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09

📥 Загружено 90 спецификаций. Всего: 2131852
🔄 Запрос #21129 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2131954
🔄 Запрос #21130 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 107 спецификаций. Всего: 2132061
🔄 Запрос #21131 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 2132166
🔄 Запрос #21132 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2132263
🔄 Запрос #21133 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 74 спецификаций. Всего: 2132337
🔄 Запрос #21134 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 55 спецификаций. Всего: 2132392
🔄 Запрос #21135 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 78 спецификаций. Всего: 2132470
🔄 Запрос #21136 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2132592
🔄 Запрос #21137 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2132702
🔄 Запрос #21138 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2132816
🔄 Запрос #21139 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 135 спецификаций. Всего: 2132951
🔄 Запрос #21140 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 2133051
🔄 Запрос #21141 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 84 спецификаций. Всего: 2133135
🔄 Запрос #21142 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 3 спецификаций. Всего: 2133138
🔄 Запрос #21143 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 137 спецификаций. Всего: 2133275
🔄 Запрос #21144 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2133394
🔄 Запрос #21145 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 122 спецификаций. Всего: 2133516
🔄 Запрос #21146 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2133618
🔄 Запрос #21147 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2133741
🔄 Запрос #21148 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 127 спецификаций. Всего: 2133868
🔄 Запрос #21149 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 125 спецификаций. Всего: 2133993
🔄 Запрос #21150 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2134108
🔄 Запрос #21151 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 140 спецификаций. Всего: 2134248
🔄 Запрос #21152 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 144 спецификаций. Всего: 2134392
🔄 Запрос #21153 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 135 спецификаций. Всего: 2134527
🔄 Запрос #21154 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 112 спецификаций. Всего: 2134639
🔄 Запрос #21155 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2134762
🔄 Запрос #21156 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 154 спецификаций. Всего: 2134916
🔄 Запрос #21157 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 2135052
🔄 Запрос #21158 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 134 спецификаций. Всего: 2135186
🔄 Запрос #21159 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2135314
🔄 Запрос #21160 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2135425
🔄 Запрос #21161 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2135558
🔄 Запрос #21162 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 126 спецификаций. Всего: 2135684
🔄 Запрос #21163 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 2135820
🔄 Запрос #21164 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 136 спецификаций. Всего: 2135956
🔄 Запрос #21165 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 139 спецификаций. Всего: 2136095
🔄 Запрос #21166 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 152 спецификаций. Всего: 2136247
🔄 Запрос #21167 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2136377
🔄 Запрос #21168 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2136495
🔄 Запрос #21169 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 115 спецификаций. Всего: 2136610
🔄 Запрос #21170 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 75 спецификаций. Всего: 2136685
🔄 Запрос #21171 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 128 спецификаций. Всего: 2136813
🔄 Запрос #21172 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 113 спецификаций. Всего: 2136926
🔄 Запрос #21173 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 2137026
🔄 Запрос #21174 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 152 спецификаций. Всего: 2137178
🔄 Запрос #21175 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 72 спецификаций. Всего: 2137250
🔄 Запрос #21176 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2137359
🔄 Запрос #21177 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2137469
🔄 Запрос #21178 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2137578
🔄 Запрос #21179 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 120 спецификаций. Всего: 2137698
🔄 Запрос #21180 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 68 спецификаций. Всего: 2137766
🔄 Запрос #21181 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 92 спецификаций. Всего: 2137858
🔄 Запрос #21182 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 79 спецификаций. Всего: 2137937
🔄 Запрос #21183 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 141 спецификаций. Всего: 2138078
🔄 Запрос #21184 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 100 спецификаций. Всего: 2138178
🔄 Запрос #21185 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2138295
🔄 Запрос #21186 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 105 спецификаций. Всего: 2138400
🔄 Запрос #21187 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 122 спецификаций. Всего: 2138522
🔄 Запрос #21188 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 110 спецификаций. Всего: 2138632
🔄 Запрос #21189 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 109 спецификаций. Всего: 2138741
🔄 Запрос #21190 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 62 спецификаций. Всего: 2138803
🔄 Запрос #21191 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 48 спецификаций. Всего: 2138851
🔄 Запрос #21192 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2138942
🔄 Запрос #21193 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2139028
🔄 Запрос #21194 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 102 спецификаций. Всего: 2139130
🔄 Запрос #21195 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 155 спецификаций. Всего: 2139285
🔄 Запрос #21196 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 146 спецификаций. Всего: 2139431
🔄 Запрос #21197 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 174 спецификаций. Всего: 2139605
🔄 Запрос #21198 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 59 спецификаций. Всего: 2139664
🔄 Запрос #21199 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 119 спецификаций. Всего: 2139783
🔄 Запрос #21200 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 148 спецификаций. Всего: 2139931
🔄 Запрос #21201 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2140042
🔄 Запрос #21202 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09

📥 Загружено 113 спецификаций. Всего: 2140155
🔄 Запрос #21203 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 91 спецификаций. Всего: 2140246
🔄 Запрос #21204 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 152 спецификаций. Всего: 2140398
🔄 Запрос #21205 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 130 спецификаций. Всего: 2140528
🔄 Запрос #21206 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 123 спецификаций. Всего: 2140651
🔄 Запрос #21207 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 133 спецификаций. Всего: 2140784
🔄 Запрос #21208 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2140890
🔄 Запрос #21209 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 131 спецификаций. Всего: 2141021
🔄 Запрос #21210 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 116 спецификаций. Всего: 2141137
🔄 Запрос #21211 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2141234
🔄 Запрос #21212 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 75 спецификаций. Всего: 2141309
🔄 Запрос #21213 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 117 спецификаций. Всего: 2141426
🔄 Запрос #21214 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 96 спецификаций. Всего: 2141522
🔄 Запрос #21215 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 97 спецификаций. Всего: 2141619
📤 Сохранено 10062 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #21216 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2141727
🔄 Запрос #21217 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 83 спецификаций. Всего: 2141810
🔄 Запрос #21218 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 47 спецификаций. Всего: 2141857
🔄 Запрос #21219 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 138 спецификаций. Всего: 2141995
🔄 Запрос #21220 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 2142083
🔄 Запрос #21221 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 88 спецификаций. Всего: 2142171
🔄 Запрос #21222 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 114 спецификаций. Всего: 2142285
🔄 Запрос #21223 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 78 спецификаций. Всего: 2142363
🔄 Запрос #21224 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 118 спецификаций. Всего: 2142481
🔄 Запрос #21225 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 38 спецификаций. Всего: 2142519
🔄 Запрос #21226 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 75 спецификаций. Всего: 2142594
🔄 Запрос #21227 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2142700
🔄 Запрос #21228 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 88 спецификаций. Всего: 2142788
🔄 Запрос #21229 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 90 спецификаций. Всего: 2142878
🔄 Запрос #21230 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 45 спецификаций. Всего: 2142923
🔄 Запрос #21231 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 101 спецификаций. Всего: 2143024
🔄 Запрос #21232 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2143122
🔄 Запрос #21233 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 95 спецификаций. Всего: 2143217
🔄 Запрос #21234 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 98 спецификаций. Всего: 2143315
🔄 Запрос #21235 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 86 спецификаций. Всего: 2143401
🔄 Запрос #21236 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 2143494
🔄 Запрос #21237 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 108 спецификаций. Всего: 2143602
🔄 Запрос #21238 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 111 спецификаций. Всего: 2143713
🔄 Запрос #21239 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 66 спецификаций. Всего: 2143779
🔄 Запрос #21240 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2143885
🔄 Запрос #21241 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2143979
🔄 Запрос #21242 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 106 спецификаций. Всего: 2144085
🔄 Запрос #21243 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 44 спецификаций. Всего: 2144129
🔄 Запрос #21244 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 94 спецификаций. Всего: 2144223
🔄 Запрос #21245 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 93 спецификаций. Всего: 2144316
🔄 Запрос #21246 для 2024-01-04 20:44:09 - 2024-01-11 20:44:09
📥 Загружено 99 спецификаций. Всего: 2144415
📅 Обрабатываем диапазон 2024-01-01 00:00:00 - 2024-01-04 20:44:09 (попытка 1/5)
🔄 Запрос #21247 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 2144531
🔄 Запрос #21248 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 2144627
🔄 Запрос #21249 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 2144742
🔄 Запрос #21250 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 2144865
🔄 Запрос #21251 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 47 спецификаций. Всего: 2144912
🔄 Запрос #21252 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 2145036
🔄 Запрос #21253 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 77 спецификаций. Всего: 2145113
🔄 Запрос #21254 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 13 спецификаций. Всего: 2145126
🔄 Запрос #21255 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 74 спецификаций. Всего: 2145200
🔄 Запрос #21256 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 136 спецификаций. Всего: 2145336
🔄 Запрос #21257 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 2145459
🔄 Запрос #21258 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 158 спецификаций. Всего: 2145617
🔄 Запрос #21259 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 2145708
🔄 Запрос #21260 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 138 спецификаций. Всего: 2145846
🔄 Запрос #21261 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 145 спецификаций. Всего: 2145991
🔄 Запрос #21262 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 2146117
🔄 Запрос #21263 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 143 спецификаций. Всего: 2146260
🔄 Запрос #21264 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 2146371
🔄 Запрос #21265 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 161 спецификаций. Всего: 2146532
🔄 Запрос #21266 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 168 спецификаций. Всего: 2146700
🔄 Запрос #21267 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 2146802
🔄 Запрос #21268 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 132 спецификаций. Всего: 2146934
🔄 Запрос #21269 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 2147054
🔄 Запрос #21270 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 2147157
🔄 Запрос #21271 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 2147246
🔄 Запрос #21272 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 2147352
🔄 Запрос #21273 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 2147471
🔄 Запрос #21274 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 2147579

🔄 Запрос #21275 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 78 спецификаций. Всего: 2147657
🔄 Запрос #21276 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 2147753
🔄 Запрос #21277 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 2147858
🔄 Запрос #21278 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 2147981
🔄 Запрос #21279 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 74 спецификаций. Всего: 2148055
🔄 Запрос #21280 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 2148164
🔄 Запрос #21281 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 2148262
🔄 Запрос #21282 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 2148380
🔄 Запрос #21283 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 2148469
🔄 Запрос #21284 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 128 спецификаций. Всего: 2148597
🔄 Запрос #21285 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 2148718
🔄 Запрос #21286 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 2148845
🔄 Запрос #21287 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 2148969
🔄 Запрос #21288 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 2149088
🔄 Запрос #21289 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 131 спецификаций. Всего: 2149219
🔄 Запрос #21290 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 2149345
🔄 Запрос #21291 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 2149457
🔄 Запрос #21292 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 61 спецификаций. Всего: 2149518
🔄 Запрос #21293 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 144 спецификаций. Всего: 2149662
🔄 Запрос #21294 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 2149758
🔄 Запрос #21295 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 125 спецификаций. Всего: 2149883
🔄 Запрос #21296 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 131 спецификаций. Всего: 2150014
🔄 Запрос #21297 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 2150117
🔄 Запрос #21298 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 2150216
🔄 Запрос #21299 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 2150343
🔄 Запрос #21300 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 2150462
🔄 Запрос #21301 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 172 спецификаций. Всего: 2150634
🔄 Запрос #21302 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 112 спецификаций. Всего: 2150746
🔄 Запрос #21303 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 63 спецификаций. Всего: 2150809
🔄 Запрос #21304 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 146 спецификаций. Всего: 2150955
🔄 Запрос #21305 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 2151052
🔄 Запрос #21306 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 2151162
🔄 Запрос #21307 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 39 спецификаций. Всего: 2151201
🔄 Запрос #21308 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 6 спецификаций. Всего: 2151207
🔄 Запрос #21309 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 78 спецификаций. Всего: 2151285
🔄 Запрос #21310 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 2151390
🔄 Запрос #21311 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 184 спецификаций. Всего: 2151574
🔄 Запрос #21312 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 2151692
📤 Сохранено 10073 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #21313 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 2151806
🔄 Запрос #21314 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 2151933
🔄 Запрос #21315 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 2152044
🔄 Запрос #21316 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 2152156
🔄 Запрос #21317 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 2152270
🔄 Запрос #21318 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 2152374
🔄 Запрос #21319 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 130 спецификаций. Всего: 2152504
🔄 Запрос #21320 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 2152611
🔄 Запрос #21321 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 2152727
🔄 Запрос #21322 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 71 спецификаций. Всего: 2152798
🔄 Запрос #21323 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 83 спецификаций. Всего: 2152881
🔄 Запрос #21324 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 110 спецификаций. Всего: 2152991
🔄 Запрос #21325 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 136 спецификаций. Всего: 2153127
🔄 Запрос #21326 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 2153225
🔄 Запрос #21327 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 2153330
🔄 Запрос #21328 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 73 спецификаций. Всего: 2153403
🔄 Запрос #21329 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 142 спецификаций. Всего: 2153545
🔄 Запрос #21330 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 2153672
🔄 Запрос #21331 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 67 спецификаций. Всего: 2153739
🔄 Запрос #21332 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 132 спецификаций. Всего: 2153871
🔄 Запрос #21333 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 2153994
🔄 Запрос #21334 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 2154090
🔄 Запрос #21335 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 2154202
🔄 Запрос #21336 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 84 спецификаций. Всего: 2154286
🔄 Запрос #21337 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 2154405
🔄 Запрос #21338 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 129 спецификаций. Всего: 2154534
🔄 Запрос #21339 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 2154654
🔄 Запрос #21340 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 72 спецификаций. Всего: 2154726
🔄 Запрос #21341 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 43 спецификаций. Всего: 2154769
🔄 Запрос #21342 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 84 спецификаций. Всего: 2154853
🔄 Запрос #21343 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 2154939
🔄 Запрос #21344 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 9 спецификаций. Всего: 2154948
🔄 Запрос #21345 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 27 спецификаций. Всего: 2154975
🔄 Запрос #21346 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 2155066
🔄 Запрос #21347 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09

📥 Загружено 122 спецификаций. Всего: 2155188
🔄 Запрос #21348 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 2155296
🔄 Запрос #21349 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 2155409
🔄 Запрос #21350 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 2155517
🔄 Запрос #21351 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 2155619
🔄 Запрос #21352 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 60 спецификаций. Всего: 2155679
🔄 Запрос #21353 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 2155796
🔄 Запрос #21354 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 2155918
🔄 Запрос #21355 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 2156044
🔄 Запрос #21356 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 2156148
🔄 Запрос #21357 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 62 спецификаций. Всего: 2156210
🔄 Запрос #21358 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 2156320
🔄 Запрос #21359 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 139 спецификаций. Всего: 2156459
🔄 Запрос #21360 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 2156571
🔄 Запрос #21361 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 44 спецификаций. Всего: 2156615
🔄 Запрос #21362 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 2156702
🔄 Запрос #21363 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 2156807
🔄 Запрос #21364 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 2156910
🔄 Запрос #21365 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 2156996
🔄 Запрос #21366 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 85 спецификаций. Всего: 2157081
🔄 Запрос #21367 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 19 спецификаций. Всего: 2157100
🔄 Запрос #21368 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 76 спецификаций. Всего: 2157176
🔄 Запрос #21369 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 76 спецификаций. Всего: 2157252
🔄 Запрос #21370 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 2157364
🔄 Запрос #21371 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 134 спецификаций. Всего: 2157498
🔄 Запрос #21372 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 2157616
🔄 Запрос #21373 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 2157717
🔄 Запрос #21374 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 2157826
🔄 Запрос #21375 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 120 спецификаций. Всего: 2157946
🔄 Запрос #21376 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 2158050
🔄 Запрос #21377 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 59 спецификаций. Всего: 2158109
🔄 Запрос #21378 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 58 спецификаций. Всего: 2158167
🔄 Запрос #21379 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 2158274
🔄 Запрос #21380 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 2158397
🔄 Запрос #21381 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 2158501
🔄 Запрос #21382 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 85 спецификаций. Всего: 2158586
🔄 Запрос #21383 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 2158684
🔄 Запрос #21384 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 2158790
🔄 Запрос #21385 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 2158905
🔄 Запрос #21386 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 2159025
🔄 Запрос #21387 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 56 спецификаций. Всего: 2159081
🔄 Запрос #21388 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 2159168
🔄 Запрос #21389 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 2159282
🔄 Запрос #21390 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 83 спецификаций. Всего: 2159365
🔄 Запрос #21391 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 2159466
🔄 Запрос #21392 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 2159586
🔄 Запрос #21393 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 65 спецификаций. Всего: 2159651
🔄 Запрос #21394 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 38 спецификаций. Всего: 2159689
🔄 Запрос #21395 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 122 спецификаций. Всего: 2159811
🔄 Запрос #21396 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 2159909
🔄 Запрос #21397 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 2160011
🔄 Запрос #21398 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 138 спецификаций. Всего: 2160149
🔄 Запрос #21399 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 2160257
🔄 Запрос #21400 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 147 спецификаций. Всего: 2160404
🔄 Запрос #21401 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 63 спецификаций. Всего: 2160467
🔄 Запрос #21402 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 2160562
🔄 Запрос #21403 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 2160661
🔄 Запрос #21404 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 2160767
🔄 Запрос #21405 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 79 спецификаций. Всего: 2160846
🔄 Запрос #21406 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 2160960
🔄 Запрос #21407 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 2161062
🔄 Запрос #21408 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 68 спецификаций. Всего: 2161130
🔄 Запрос #21409 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 2161226
🔄 Запрос #21410 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 2161334
🔄 Запрос #21411 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 81 спецификаций. Всего: 2161415
🔄 Запрос #21412 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 2161535
🔄 Запрос #21413 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 2161657
🔄 Запрос #21414 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 2161779
📤 Сохранено 10087 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #21415 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 2161880
🔄 Запрос #21416 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 2161976
🔄 Запрос #21417 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09

📥 Загружено 83 спецификаций. Всего: 2162059
🔄 Запрос #21418 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 2162160
🔄 Запрос #21419 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 2162264
🔄 Запрос #21420 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 129 спецификаций. Всего: 2162393
🔄 Запрос #21421 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 2162504
🔄 Запрос #21422 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 102 спецификаций. Всего: 2162606
🔄 Запрос #21423 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 28 спецификаций. Всего: 2162634
🔄 Запрос #21424 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 106 спецификаций. Всего: 2162740
🔄 Запрос #21425 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 34 спецификаций. Всего: 2162774
🔄 Запрос #21426 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 68 спецификаций. Всего: 2162842
🔄 Запрос #21427 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 2162933
🔄 Запрос #21428 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 93 спецификаций. Всего: 2163026
🔄 Запрос #21429 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 134 спецификаций. Всего: 2163160
🔄 Запрос #21430 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 2163257
🔄 Запрос #21431 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 70 спецификаций. Всего: 2163327
🔄 Запрос #21432 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 5 спецификаций. Всего: 2163332
🔄 Запрос #21433 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 2 спецификаций. Всего: 2163334
🔄 Запрос #21434 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 66 спецификаций. Всего: 2163400
🔄 Запрос #21435 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 112 спецификаций. Всего: 2163512
🔄 Запрос #21436 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 2163639
🔄 Запрос #21437 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 105 спецификаций. Всего: 2163744
🔄 Запрос #21438 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 153 спецификаций. Всего: 2163897
🔄 Запрос #21439 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 147 спецификаций. Всего: 2164044
🔄 Запрос #21440 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 95 спецификаций. Всего: 2164139
🔄 Запрос #21441 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 2164266
🔄 Запрос #21442 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 2164363
🔄 Запрос #21443 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 39 спецификаций. Всего: 2164402
🔄 Запрос #21444 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 2164500
🔄 Запрос #21445 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 70 спецификаций. Всего: 2164570
🔄 Запрос #21446 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 179 спецификаций. Всего: 2164749
🔄 Запрос #21447 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 2164864
🔄 Запрос #21448 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 151 спецификаций. Всего: 2165015
🔄 Запрос #21449 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 136 спецификаций. Всего: 2165151
🔄 Запрос #21450 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 77 спецификаций. Всего: 2165228
🔄 Запрос #21451 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 2165337
🔄 Запрос #21452 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 132 спецификаций. Всего: 2165469
🔄 Запрос #21453 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 140 спецификаций. Всего: 2165609
🔄 Запрос #21454 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 139 спецификаций. Всего: 2165748
🔄 Запрос #21455 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 2165865
🔄 Запрос #21456 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 78 спецификаций. Всего: 2165943
🔄 Запрос #21457 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 146 спецификаций. Всего: 2166089
🔄 Запрос #21458 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 137 спецификаций. Всего: 2166226
🔄 Запрос #21459 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 2166333
🔄 Запрос #21460 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 78 спецификаций. Всего: 2166411
🔄 Запрос #21461 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 135 спецификаций. Всего: 2166546
🔄 Запрос #21462 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 2166666
🔄 Запрос #21463 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 146 спецификаций. Всего: 2166812
🔄 Запрос #21464 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 138 спецификаций. Всего: 2166950
🔄 Запрос #21465 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 2167052
🔄 Запрос #21466 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 2167166
🔄 Запрос #21467 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 132 спецификаций. Всего: 2167298
🔄 Запрос #21468 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 78 спецификаций. Всего: 2167376
🔄 Запрос #21469 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 75 спецификаций. Всего: 2167451
🔄 Запрос #21470 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 74 спецификаций. Всего: 2167525
🔄 Запрос #21471 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 125 спецификаций. Всего: 2167650
🔄 Запрос #21472 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 2167749
🔄 Запрос #21473 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 74 спецификаций. Всего: 2167823
🔄 Запрос #21474 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 76 спецификаций. Всего: 2167899
🔄 Запрос #21475 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 45 спецификаций. Всего: 2167944
🔄 Запрос #21476 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 2168045
🔄 Запрос #21477 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 2168139
🔄 Запрос #21478 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 2168248
🔄 Запрос #21479 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 2168359
🔄 Запрос #21480 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 125 спецификаций. Всего: 2168484
🔄 Запрос #21481 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 105 спецификаций. Всего: 2168589
🔄 Запрос #21482 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 2168690
🔄 Запрос #21483 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 92 спецификаций. Всего: 2168782
🔄 Запрос #21484 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 2168883
🔄 Запрос #21485 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09

📥 Загружено 112 спецификаций. Всего: 2168995
🔄 Запрос #21486 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 2169098
🔄 Запрос #21487 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 85 спецификаций. Всего: 2169183
🔄 Запрос #21488 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 2169290
🔄 Запрос #21489 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 2169379
🔄 Запрос #21490 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 2169500
🔄 Запрос #21491 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 2169597
🔄 Запрос #21492 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 2169701
🔄 Запрос #21493 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 2169822
🔄 Запрос #21494 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 92 спецификаций. Всего: 2169914
🔄 Запрос #21495 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 2170001
🔄 Запрос #21496 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 73 спецификаций. Всего: 2170074
🔄 Запрос #21497 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 2170171
🔄 Запрос #21498 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 46 спецификаций. Всего: 2170217
🔄 Запрос #21499 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 2170303
🔄 Запрос #21500 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 2170390
🔄 Запрос #21501 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 58 спецификаций. Всего: 2170448
🔄 Запрос #21502 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 36 спецификаций. Всего: 2170484
🔄 Запрос #21503 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 39 спецификаций. Всего: 2170523
🔄 Запрос #21504 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 66 спецификаций. Всего: 2170589
🔄 Запрос #21505 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 2170713
🔄 Запрос #21506 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 132 спецификаций. Всего: 2170845
🔄 Запрос #21507 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 151 спецификаций. Всего: 2170996
🔄 Запрос #21508 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 2171110
🔄 Запрос #21509 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 123 спецификаций. Всего: 2171233
🔄 Запрос #21510 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 2171354
🔄 Запрос #21511 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 142 спецификаций. Всего: 2171496
🔄 Запрос #21512 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 138 спецификаций. Всего: 2171634
🔄 Запрос #21513 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 144 спецификаций. Всего: 2171778
🔄 Запрос #21514 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 2171878
📤 Сохранено 10099 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #21515 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 143 спецификаций. Всего: 2172021
🔄 Запрос #21516 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 156 спецификаций. Всего: 2172177
🔄 Запрос #21517 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 144 спецификаций. Всего: 2172321
🔄 Запрос #21518 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 2172421
🔄 Запрос #21519 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 2172548
🔄 Запрос #21520 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 135 спецификаций. Всего: 2172683
🔄 Запрос #21521 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 134 спецификаций. Всего: 2172817
🔄 Запрос #21522 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 2172935
🔄 Запрос #21523 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 128 спецификаций. Всего: 2173063
🔄 Запрос #21524 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 2173175
🔄 Запрос #21525 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 2173290
🔄 Запрос #21526 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 131 спецификаций. Всего: 2173421
🔄 Запрос #21527 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 2173529
🔄 Запрос #21528 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 2173645
🔄 Запрос #21529 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 2173769
🔄 Запрос #21530 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 153 спецификаций. Всего: 2173922
🔄 Запрос #21531 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 149 спецификаций. Всего: 2174071
🔄 Запрос #21532 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 45 спецификаций. Всего: 2174116
🔄 Запрос #21533 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 2174225
🔄 Запрос #21534 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 138 спецификаций. Всего: 2174363
🔄 Запрос #21535 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 129 спецификаций. Всего: 2174492
🔄 Запрос #21536 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 2174594
🔄 Запрос #21537 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 2174704
🔄 Запрос #21538 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 138 спецификаций. Всего: 2174842
🔄 Запрос #21539 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 133 спецификаций. Всего: 2174975
🔄 Запрос #21540 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 41 спецификаций. Всего: 2175016
🔄 Запрос #21541 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 2175143
🔄 Запрос #21542 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 103 спецификаций. Всего: 2175246
🔄 Запрос #21543 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 2175348
🔄 Запрос #21544 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 70 спецификаций. Всего: 2175418
🔄 Запрос #21545 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 79 спецификаций. Всего: 2175497
🔄 Запрос #21546 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 9 спецификаций. Всего: 2175506
🔄 Запрос #21547 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 75 спецификаций. Всего: 2175581
🔄 Запрос #21548 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 53 спецификаций. Всего: 2175634
🔄 Запрос #21549 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 49 спецификаций. Всего: 2175683
🔄 Запрос #21550 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 2175782
🔄 Запрос #21551 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 2175894
🔄 Запрос #21552 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 2175985
🔄 Запрос #21553 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 77 спецификаций. Всего: 2176062
🔄 Запрос #21554 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 145 спецификаций. Всего: 2176207
🔄 Запрос #21555 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 139 спецификаций. Всего: 2176346
🔄 Запрос #21556 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 90 спецификаций. Всего: 2176436

🔄 Запрос #21557 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 11 спецификаций. Всего: 2176447
🔄 Запрос #21558 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 63 спецификаций. Всего: 2176510
🔄 Запрос #21559 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 2176628
🔄 Запрос #21560 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 69 спецификаций. Всего: 2176697
🔄 Запрос #21561 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 2176808
🔄 Запрос #21562 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 2176896
🔄 Запрос #21563 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 2177012
🔄 Запрос #21564 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 79 спецификаций. Всего: 2177091
🔄 Запрос #21565 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 3 спецификаций. Всего: 2177094
🔄 Запрос #21566 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 3 спецификаций. Всего: 2177097
🔄 Запрос #21567 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 48 спецификаций. Всего: 2177145
🔄 Запрос #21568 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 2177261
🔄 Запрос #21569 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 2177387
🔄 Запрос #21570 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 2177513
🔄 Запрос #21571 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 2177629
🔄 Запрос #21572 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 2177741
🔄 Запрос #21573 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 107 спецификаций. Всего: 2177848
🔄 Запрос #21574 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 2177966
🔄 Запрос #21575 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 36 спецификаций. Всего: 2178002
🔄 Запрос #21576 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 2178093
🔄 Запрос #21577 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 89 спецификаций. Всего: 2178182
🔄 Запрос #21578 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 142 спецификаций. Всего: 2178324
🔄 Запрос #21579 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 70 спецификаций. Всего: 2178394
🔄 Запрос #21580 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 2178513
🔄 Запрос #21581 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 125 спецификаций. Всего: 2178638
🔄 Запрос #21582 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 2178732
🔄 Запрос #21583 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 129 спецификаций. Всего: 2178861
🔄 Запрос #21584 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 161 спецификаций. Всего: 2179022
🔄 Запрос #21585 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 2179144
🔄 Запрос #21586 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 193 спецификаций. Всего: 2179337
🔄 Запрос #21587 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 142 спецификаций. Всего: 2179479
🔄 Запрос #21588 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 126 спецификаций. Всего: 2179605
🔄 Запрос #21589 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 127 спецификаций. Всего: 2179732
🔄 Запрос #21590 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 2179842
🔄 Запрос #21591 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 2179951
🔄 Запрос #21592 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 2180055
🔄 Запрос #21593 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 74 спецификаций. Всего: 2180129
🔄 Запрос #21594 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 85 спецификаций. Всего: 2180214
🔄 Запрос #21595 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 2180338
🔄 Запрос #21596 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 112 спецификаций. Всего: 2180450
🔄 Запрос #21597 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 121 спецификаций. Всего: 2180571
🔄 Запрос #21598 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 2180697
🔄 Запрос #21599 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 91 спецификаций. Всего: 2180788
🔄 Запрос #21600 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 71 спецификаций. Всего: 2180859
🔄 Запрос #21601 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 63 спецификаций. Всего: 2180922
🔄 Запрос #21602 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 2181022
🔄 Запрос #21603 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 138 спецификаций. Всего: 2181160
🔄 Запрос #21604 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 2181254
🔄 Запрос #21605 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 19 спецификаций. Всего: 2181273
🔄 Запрос #21606 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 14 спецификаций. Всего: 2181287
🔄 Запрос #21607 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 4 спецификаций. Всего: 2181291
🔄 Запрос #21608 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 108 спецификаций. Всего: 2181399
🔄 Запрос #21609 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 81 спецификаций. Всего: 2181480
🔄 Запрос #21610 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 125 спецификаций. Всего: 2181605
🔄 Запрос #21611 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 149 спецификаций. Всего: 2181754
🔄 Запрос #21612 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 2181869
🔄 Запрос #21613 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 137 спецификаций. Всего: 2182006
📤 Сохранено 10128 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #21614 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 67 спецификаций. Всего: 2182073
🔄 Запрос #21615 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 2182175
🔄 Запрос #21616 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 82 спецификаций. Всего: 2182257
🔄 Запрос #21617 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 62 спецификаций. Всего: 2182319
🔄 Запрос #21618 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 109 спецификаций. Всего: 2182428
🔄 Запрос #21619 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 101 спецификаций. Всего: 2182529
🔄 Запрос #21620 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 86 спецификаций. Всего: 2182615
🔄 Запрос #21621 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 68 спецификаций. Всего: 2182683
🔄 Запрос #21622 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 79 спецификаций. Всего: 2182762
🔄 Запрос #21623 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 2182881
🔄 Запрос #21624 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 2182980
🔄 Запрос #21625 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 119 спецификаций. Всего: 2183099
🔄 Запрос #21626 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 2183185
🔄 Запрос #21627 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09

📥 Загружено 132 спецификаций. Всего: 2183317
🔄 Запрос #21628 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 2183428
🔄 Запрос #21629 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 2183522
🔄 Запрос #21630 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 2183644
🔄 Запрос #21631 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 92 спецификаций. Всего: 2183736
🔄 Запрос #21632 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 134 спецификаций. Всего: 2183870
🔄 Запрос #21633 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 2183974
🔄 Запрос #21634 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 2184100
🔄 Запрос #21635 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 2184220
🔄 Запрос #21636 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 137 спецификаций. Всего: 2184357
🔄 Запрос #21637 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 173 спецификаций. Всего: 2184530
🔄 Запрос #21638 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 124 спецификаций. Всего: 2184654
🔄 Запрос #21639 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 110 спецификаций. Всего: 2184764
🔄 Запрос #21640 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 145 спецификаций. Всего: 2184909
🔄 Запрос #21641 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 131 спецификаций. Всего: 2185040
🔄 Запрос #21642 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 123 спецификаций. Всего: 2185163
🔄 Запрос #21643 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 2185281
🔄 Запрос #21644 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 111 спецификаций. Всего: 2185392
🔄 Запрос #21645 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 62 спецификаций. Всего: 2185454
🔄 Запрос #21646 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 2 спецификаций. Всего: 2185456
🔄 Запрос #21647 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 3 спецификаций. Всего: 2185459
🔄 Запрос #21648 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 32 спецификаций. Всего: 2185491
🔄 Запрос #21649 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 144 спецификаций. Всего: 2185635
🔄 Запрос #21650 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 149 спецификаций. Всего: 2185784
🔄 Запрос #21651 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 2185882
🔄 Запрос #21652 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 57 спецификаций. Всего: 2185939
🔄 Запрос #21653 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 79 спецификаций. Всего: 2186018
🔄 Запрос #21654 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 2186115
🔄 Запрос #21655 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 73 спецификаций. Всего: 2186188
🔄 Запрос #21656 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 2186312
🔄 Запрос #21657 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 2186414
🔄 Запрос #21658 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 147 спецификаций. Всего: 2186561
🔄 Запрос #21659 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 2186683
🔄 Запрос #21660 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 107 спецификаций. Всего: 2186790
🔄 Запрос #21661 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 2186890
🔄 Запрос #21662 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 113 спецификаций. Всего: 2187003
🔄 Запрос #21663 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 69 спецификаций. Всего: 2187072
🔄 Запрос #21664 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 136 спецификаций. Всего: 2187208
🔄 Запрос #21665 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 69 спецификаций. Всего: 2187277
🔄 Запрос #21666 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
⚠️ Ошибка (попытка 2/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 97 спецификаций. Всего: 2187374
🔄 Запрос #21667 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 128 спецификаций. Всего: 2187502
🔄 Запрос #21668 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 42 спецификаций. Всего: 2187544
🔄 Запрос #21669 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 2187659
🔄 Запрос #21670 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 146 спецификаций. Всего: 2187805
🔄 Запрос #21671 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 77 спецификаций. Всего: 2187882
🔄 Запрос #21672 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 2188002
🔄 Запрос #21673 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 2188113
🔄 Запрос #21674 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 2188235
🔄 Запрос #21675 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 70 спецификаций. Всего: 2188305
🔄 Запрос #21676 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 2188420
🔄 Запрос #21677 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 2188522
🔄 Запрос #21678 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 74 спецификаций. Всего: 2188596
🔄 Запрос #21679 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 143 спецификаций. Всего: 2188739
🔄 Запрос #21680 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 120 спецификаций. Всего: 2188859
🔄 Запрос #21681 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 2188973
🔄 Запрос #21682 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 91 спецификаций. Всего: 2189064
🔄 Запрос #21683 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 79 спецификаций. Всего: 2189143
🔄 Запрос #21684 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 132 спецификаций. Всего: 2189275
🔄 Запрос #21685 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 76 спецификаций. Всего: 2189351
🔄 Запрос #21686 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 2189445
🔄 Запрос #21687 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 2189556
🔄 Запрос #21688 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 151 спецификаций. Всего: 2189707
🔄 Запрос #21689 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 63 спецификаций. Всего: 2189770
🔄 Запрос #21690 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 122 спецификаций. Всего: 2189892
🔄 Запрос #21691 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 132 спецификаций. Всего: 2190024
🔄 Запрос #21692 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 45 спецификаций. Всего: 2190069
🔄 Запрос #21693 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 51 спецификаций. Всего: 2190120
🔄 Запрос #21694 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 87 спецификаций. Всего: 2190207
🔄 Запрос #21695 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09

📥 Загружено 0 спецификаций. Всего: 2190207
🔄 Запрос #21696 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 1 спецификаций. Всего: 2190208
🔄 Запрос #21697 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 1 спецификаций. Всего: 2190209
🔄 Запрос #21698 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 7 спецификаций. Всего: 2190216
🔄 Запрос #21699 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 2190304
🔄 Запрос #21700 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 31 спецификаций. Всего: 2190335
🔄 Запрос #21701 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 135 спецификаций. Всего: 2190470
🔄 Запрос #21702 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 61 спецификаций. Всего: 2190531
🔄 Запрос #21703 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 47 спецификаций. Всего: 2190578
🔄 Запрос #21704 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 150 спецификаций. Всего: 2190728
🔄 Запрос #21705 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 59 спецификаций. Всего: 2190787
🔄 Запрос #21706 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 69 спецификаций. Всего: 2190856
🔄 Запрос #21707 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 65 спецификаций. Всего: 2190921
🔄 Запрос #21708 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out. (read timeout=15)
📥 Загружено 52 спецификаций. Всего: 2190973
🔄 Запрос #21709 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 80 спецификаций. Всего: 2191053
🔄 Запрос #21710 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 65 спецификаций. Всего: 2191118
🔄 Запрос #21711 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 2191217
🔄 Запрос #21712 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 42 спецификаций. Всего: 2191259
🔄 Запрос #21713 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 131 спецификаций. Всего: 2191390
🔄 Запрос #21714 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 90 спецификаций. Всего: 2191480
🔄 Запрос #21715 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 138 спецификаций. Всего: 2191618
🔄 Запрос #21716 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 102 спецификаций. Всего: 2191720
🔄 Запрос #21717 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 2191819
🔄 Запрос #21718 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 55 спецификаций. Всего: 2191874
🔄 Запрос #21719 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 37 спецификаций. Всего: 2191911
🔄 Запрос #21720 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 43 спецификаций. Всего: 2191954
🔄 Запрос #21721 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 151 спецификаций. Всего: 2192105
📤 Сохранено 10099 записей в plans_data_spec\plans_combined_spec.parquet
🔄 Запрос #21722 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 58 спецификаций. Всего: 2192163
🔄 Запрос #21723 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 115 спецификаций. Всего: 2192278
🔄 Запрос #21724 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 58 спецификаций. Всего: 2192336
🔄 Запрос #21725 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 64 спецификаций. Всего: 2192400
🔄 Запрос #21726 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 22 спецификаций. Всего: 2192422
🔄 Запрос #21727 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 2192536
🔄 Запрос #21728 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 137 спецификаций. Всего: 2192673
🔄 Запрос #21729 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 126 спецификаций. Всего: 2192799
🔄 Запрос #21730 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 67 спецификаций. Всего: 2192866
🔄 Запрос #21731 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 88 спецификаций. Всего: 2192954
🔄 Запрос #21732 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 111 спецификаций. Всего: 2193065
🔄 Запрос #21733 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 71 спецификаций. Всего: 2193136
🔄 Запрос #21734 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 128 спецификаций. Всего: 2193264
🔄 Запрос #21735 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 2193364
🔄 Запрос #21736 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 117 спецификаций. Всего: 2193481
🔄 Запрос #21737 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 129 спецификаций. Всего: 2193610
🔄 Запрос #21738 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 56 спецификаций. Всего: 2193666
🔄 Запрос #21739 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 96 спецификаций. Всего: 2193762
🔄 Запрос #21740 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 68 спецификаций. Всего: 2193830
🔄 Запрос #21741 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 61 спецификаций. Всего: 2193891
🔄 Запрос #21742 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 104 спецификаций. Всего: 2193995
🔄 Запрос #21743 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 133 спецификаций. Всего: 2194128
🔄 Запрос #21744 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 118 спецификаций. Всего: 2194246
🔄 Запрос #21745 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 124 спецификаций. Всего: 2194370
🔄 Запрос #21746 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 116 спецификаций. Всего: 2194486
🔄 Запрос #21747 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 99 спецификаций. Всего: 2194585
🔄 Запрос #21748 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 83 спецификаций. Всего: 2194668
🔄 Запрос #21749 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 2194754
🔄 Запрос #21750 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 114 спецификаций. Всего: 2194868
🔄 Запрос #21751 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 78 спецификаций. Всего: 2194946
🔄 Запрос #21752 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 18 спецификаций. Всего: 2194964
🔄 Запрос #21753 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 98 спецификаций. Всего: 2195062
🔄 Запрос #21754 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 86 спецификаций. Всего: 2195148
🔄 Запрос #21755 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 100 спецификаций. Всего: 2195248
🔄 Запрос #21756 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 80 спецификаций. Всего: 2195328
🔄 Запрос #21757 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 133 спецификаций. Всего: 2195461
🔄 Запрос #21758 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 82 спецификаций. Всего: 2195543
🔄 Запрос #21759 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 21 спецификаций. Всего: 2195564
🔄 Запрос #21760 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 51 спецификаций. Всего: 2195615
🔄 Запрос #21761 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 97 спецификаций. Всего: 2195712
🔄 Запрос #21762 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 73 спецификаций. Всего: 2195785
🔄 Запрос #21763 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 130 спецификаций. Всего: 2195915
🔄 Запрос #21764 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 42 спецификаций. Всего: 2195957
🔄 Запрос #21765 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 67 спецификаций. Всего: 2196024
🔄 Запрос #21766 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
📥 Загружено 94 спецификаций. Всего: 2196118
🔄 Запрос #21767 для 2024-01-01 00:00:00 - 2024-01-04 20:44:09
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.

📥 Загружено 10 спецификаций. Всего: 2196128
📤 Сохранено 4023 записей в plans_data_spec\plans_combined_spec.parquet
Итог: планов без PlansSpec: 2176157
✅ Завершено. Всего загружено: 2196128

In [7]:
df = pd.read_parquet(combined_file)
df["dateCreate"] = pd.to_datetime(df["dateCreate"], errors="coerce")  # Преобразуем дату
df_sorted = df.sort_values("dateCreate")  # Сортируем по возрастанию

print("🔝 ПЕРВЫЕ 5 СТРОК ПО dateCreate:")
display(df_sorted.head())

print("\n🔚 ПОСЛЕДНИЕ 5 СТРОК ПО dateCreate:")
display(df_sorted.tail())

🔝 ПЕРВЫЕ 5 СТРОК ПО dateCreate:

,plan_id,dateCreate,specId,plnPointsId,refEkrbId,ekrbCode,ekrbNameRu,ekrbNameKz,count,price,...,abpNameKz,amount,refFkrbProgramId,fkrbProgramCode,fkrbProgramNameRu,fkrbProgramNameKz,isActive,isDeleted,systemId,indexDate
498883,76384157,2025-01-09 20:44:09,46008689,76384157,863,431,Строительство новых объектов и реконструкция и...,Жаңа объектілерді салу және қолдағы объектілер...,1.0,7.916578e+08,...,Облыстың жолаушылар көлігі және автомобиль жол...,7.916578e+08,735431,002,Развитие транспортной инфраструктуры,Көлік инфрақұрылымын дамыту,1,0,3,2025-01-16 15:24:49
498882,76384158,2025-01-09 20:44:09,46008690,76384158,851,141,Приобретение продуктов питания,Азық-түлiк өнiмдерiн сатып алу,250.0,1.200000e+03,...,Облыстың білім басқармасы,3.000000e+05,2152337,003,Общеобразовательное обучение по специальным об...,Арнаулы білім беретін оқу бағдарламалары бойын...,1,0,3,2025-01-15 18:07:13
498881,76384160,2025-01-09 20:44:13,46008692,76384160,888,149,Приобретение прочих запасов,Өзге де қорларды сатып алу,1.0,2.678570e+03,...,,2.678570e+03,2116967,001,Услуги по обеспечению деятельности акима город...,"Аудандық маңызы бар қала, ауыл, кент, ауылдық ...",1,0,3,2025-01-10 18:06:01
498880,76384165,2025-01-09 20:44:27,46008698,76384165,3577,158,Оплата работ и услуг в сфере информатизации,Ақпараттандыру саласындағы жұмыстар мен қызмет...,1.0,3.600000e+05,...,Облыстың білім басқармасы,3.600000e+05,2152338,203,Реализация подушевого финансирования в государ...,Мемлекеттік орта білім беру ұйымдарында жан ба...,1,0,3,2025-01-27 22:00:55
498879,76384167,2025-01-09 20:44:30,46009013,76384167,894,159,Оплата прочих услуг и работ,Өзге де қызметтер мен жұмыстарға ақы төлеу,1.0,7.232142e+04,...,Облыстың білім басқармасы,7.232142e+04,2151629,029,Методическое и финансовое сопровождение систем...,Білім беру жүйесін әдістемелік және қаржылық с...,1,0,3,2025-01-09 22:40:52

🔚 ПОСЛЕДНИЕ 5 СТРОК ПО dateCreate:

,plan_id,dateCreate,specId,plnPointsId,refEkrbId,ekrbCode,ekrbNameRu,ekrbNameKz,count,price,...,abpNameKz,amount,refFkrbProgramId,fkrbProgramCode,fkrbProgramNameRu,fkrbProgramNameKz,isActive,isDeleted,systemId,indexDate
4,78042724,2025-03-05 17:57:42,47070499,78042724,888,149,Приобретение прочих запасов,Өзге де қорларды сатып алу,30.0,357.00,...,"Республикалық маңызы бар қаланың, астананың кә...",10710.00,737733,001,Услуги по реализации государственной политики ...,Жергілікті деңгейде кәсіпкерлік және индустриа...,1,0,3,2025-03-05 18:20:43
3,78042747,2025-03-05 17:59:05,47070522,78042747,886,143,"Приобретение, пошив и ремонт предметов вещевог...","Заттай мүлiктердi, басқа да киім нысанын және ...",1.0,4138392.86,...,Ауданның (облыстық маңызы бар қаланың) мәдение...,4138392.86,2117293,032,Капитальные расходы подведомственных государст...,Ведомстволық бағыныстағы мемлекеттік мекемелер...,1,0,3,2025-03-05 18:20:43
2,78042748,2025-03-05 17:59:11,47070524,78042748,894,159,Оплата прочих услуг и работ,Өзге де қызметтер мен жұмыстарға ақы төлеу,1.0,148000.00,...,Ауданның (облыстық маңызы бар қаланың) кәсіпке...,148000.00,736627,001,Услуги по реализации государственной политики ...,Жергілікті деңгейде кәсіпкерлікті және ауыл ша...,1,0,3,2025-03-05 18:20:43
1,78042806,2025-03-05 18:02:48,47070576,78042806,894,159,Оплата прочих услуг и работ,Өзге де қызметтер мен жұмыстарға ақы төлеу,1.0,30000.00,...,Ауданның (облыстық маңызы бар қаланың) жұмыспе...,30000.00,735298,001,Услуги по реализации государственной политики ...,Жергілікті деңгейде халық үшін әлеуметтік бағд...,1,0,3,2025-03-05 18:20:43
0,78042883,2025-03-05 18:07:40,47070648,78042883,878,123,Взносы на обязательное страхование,Мiндеттi сақтандыру жарналары,1.0,33035.71,...,Ауданның (облыстық маңызы бар қаланың) дене шы...,33035.71,739421,001,Услуги по реализации государственной политики ...,Жергілікті деңгейде дене шынықтыру және спорт ...,1,0,3,2025-03-05 18:20:43

In [12]:
import pandas as pd

# Load the DataFrame from the Parquet file
df = pd.read_parquet(combined_file)

# Count the total number of duplicate rows
duplicate_count = df.duplicated().sum()

print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

### Для дозагрузки новых данных

In [13]:
import requests
import pandas as pd
import time
import os
from datetime import datetime, timedelta

GRAPHQL_URL = "https://ows.goszakup.gov.kz/v3/graphql"
HEADERS = {
    "Content-Type": "application/json",
    "Authorization": "Bearer d5c3d78fc111d88a0a37b4ab8f83cbd5"
}

query_template = """
query GetPlans($filter: PlansFiltersInput, $after: Int) {
    Plans(filter: $filter, limit: 200, after: $after) {
        id
        dateCreate
        
        PlansSpec {
            id
            plnPointsId
            refEkrbId
            ekrbCode
            ekrbNameRu
            ekrbNameKz
            count
            price
            refFkrbSubprogramId
            fkrbSubprogramCode
            fkrbSubprogramNameRu
            fkrbSubprogramNameKz
            refFkrbId
            abpCode
            abpNameRu
            abpNameKz
            amount
            refFkrbProgramId
            fkrbProgramCode
            fkrbProgramNameRu
            fkrbProgramNameKz
            isActive
            isDeleted
            systemId
            indexDate
        }
    }
}
"""

output_dir = "plans_data_spec"
os.makedirs(output_dir, exist_ok=True)
combined_file = os.path.join(output_dir, "plans_combined_spec.parquet")

# Определяем даты для новых данных
today = datetime.now()
yesterday = today - timedelta(days=1)

request_count = 0
total_loaded = 0
plans_without_spec = 0
batch_size = 10000

def save_batch(plans_batch, file_path, append=True):
    df = pd.DataFrame(plans_batch)
    if append and os.path.exists(file_path):
        df.to_parquet(file_path, engine='fastparquet', append=True)
    else:
        df.to_parquet(file_path, index=False)
    print(f"📤 Сохранено {len(plans_batch)} записей в {file_path}")
    return []

def check_server_availability(url, headers, timeout=10):
    try:
        response = requests.get(url, headers=headers, timeout=timeout)
        return response.status_code == 200
    except:
        return False

plans_batch = []

# Устанавливаем диапазон дат для новых данных
variables = {
    "filter": {
        "dateCreate": {
            "gte": yesterday.strftime("%Y-%m-%d %H:%M:%S"),
            "lte": today.strftime("%Y-%m-%d %H:%M:%S")
        }
    },
    "after": None
}

print(f"📅 Загружаем новые данные с {yesterday} до {today}")

completed = False
retry_attempts = 0
max_retries = 5

while not completed and retry_attempts < max_retries:
    retry_attempts += 1
    print(f"🔄 Попытка {retry_attempts}/{max_retries}")
    
    while True:
        request_count += 1
        print(f"📡 Запрос #{request_count}")

        response = None
        for attempt in range(3):
            try:
                response = requests.post(GRAPHQL_URL, json={"query": query_template, "variables": variables}, headers=HEADERS, timeout=15)
                response.raise_for_status()
                break
            except Exception as e:
                print(f"⚠️ Ошибка (попытка {attempt + 1}/3): {e}")
                if attempt < 2:
                    time.sleep(5)
                else:
                    if not check_server_availability(GRAPHQL_URL, HEADERS):
                        print("Сервер недоступен. Ожидаем восстановления связи...")
                        time.sleep(30)
                        break
                    else:
                        print("Сервер доступен, но запрос не удался.")
                        break
        
        if response is None:
            print("Проблема с запросом — повторяем попытку.")
            break

        data = response.json()
        plans = data.get("data", {}).get("Plans", [])
        if not plans:
            completed = True
            break

        count_loaded = 0
        for plan in plans:
            plans_spec = plan.get("PlansSpec", [])
            if not plans_spec:
                plans_without_spec += 1
                continue

            for spec in plans_spec:
                plans_batch.append({
                    "plan_id": plan.get("id"),
                    "dateCreate": plan.get("dateCreate"),
                    "specId": spec.get("id"),
                    "plnPointsId": spec.get("plnPointsId"),
                    "refEkrbId": spec.get("refEkrbId"),
                    "ekrbCode": spec.get("ekrbCode"),
                    "ekrbNameRu": spec.get("ekrbNameRu"),
                    "ekrbNameKz": spec.get("ekrbNameKz"),
                    "count": spec.get("count"),
                    "price": spec.get("price"),
                    "refFkrbSubprogramId": spec.get("refFkrbSubprogramId"),
                    "fkrbSubprogramCode": spec.get("fkrbSubprogramCode"),
                    "fkrbSubprogramNameRu": spec.get("fkrbSubprogramNameRu"),
                    "fkrbSubprogramNameKz": spec.get("fkrbSubprogramNameKz"),
                    "refFkrbId": spec.get("refFkrbId"),
                    "abpCode": spec.get("abpCode"),
                    "abpNameRu": spec.get("abpNameRu"),
                    "abpNameKz": spec.get("abpNameKz"),
                    "amount": spec.get("amount"),
                    "refFkrbProgramId": spec.get("refFkrbProgramId"),
                    "fkrbProgramCode": spec.get("fkrbProgramCode"),
                    "fkrbProgramNameRu": spec.get("fkrbProgramNameRu"),
                    "fkrbProgramNameKz": spec.get("fkrbProgramNameKz"),
                    "isActive": spec.get("isActive"),
                    "isDeleted": spec.get("isDeleted"),
                    "systemId": spec.get("systemId"),
                    "indexDate": spec.get("indexDate")
                })
                count_loaded += 1

        total_loaded += count_loaded
        print(f"📥 Загружено {count_loaded} спецификаций. Всего: {total_loaded}")

        if len(plans_batch) >= batch_size:
            plans_batch = save_batch(plans_batch, combined_file, append=True)

        last_id = plans[-1].get("id")
        if last_id and len(plans) == 200:
            variables["after"] = int(last_id) if isinstance(last_id, str) and last_id.isdigit() else last_id
        else:
            completed = True
            break

        time.sleep(1)

    if not completed:
        print(f"Загрузка не завершена, повторяем через 30 секунд...")
        time.sleep(30)

if plans_batch:
    plans_batch = save_batch(plans_batch, combined_file, append=True)

print(f"Итог: планов без PlansSpec: {plans_without_spec}")
print(f"✅ Завершено. Всего загружено: {total_loaded} новых записей")

📅 Загружаем новые данные с 2025-04-01 20:05:49.741564 до 2025-04-02 20:05:49.741564
🔄 Попытка 1/5
📡 Запрос #1
📥 Загружено 15 спецификаций. Всего: 15
📡 Запрос #2
📥 Загружено 82 спецификаций. Всего: 97
📡 Запрос #3
📥 Загружено 110 спецификаций. Всего: 207
📡 Запрос #4
📥 Загружено 90 спецификаций. Всего: 297
📡 Запрос #5
📥 Загружено 50 спецификаций. Всего: 347
📡 Запрос #6
📥 Загружено 87 спецификаций. Всего: 434
📡 Запрос #7
📥 Загружено 82 спецификаций. Всего: 516
📡 Запрос #8
📥 Загружено 86 спецификаций. Всего: 602
📡 Запрос #9
📥 Загружено 77 спецификаций. Всего: 679
📡 Запрос #10
📥 Загружено 93 спецификаций. Всего: 772
📡 Запрос #11
📥 Загружено 96 спецификаций. Всего: 868
📡 Запрос #12
📥 Загружено 98 спецификаций. Всего: 966
📡 Запрос #13
📥 Загружено 102 спецификаций. Всего: 1068
📡 Запрос #14
📥 Загружено 92 спецификаций. Всего: 1160
📡 Запрос #15
📥 Загружено 106 спецификаций. Всего: 1266
📡 Запрос #16
📥 Загружено 97 спецификаций. Всего: 1363
📡 Запрос #17
📥 Загружено 79 спецификаций. Всего: 1442
📡 Запрос #18
📥 Загружено 89 спецификаций. Всего: 1531
📡 Запрос #19
📥 Загружено 102 спецификаций. Всего: 1633
📡 Запрос #20
📥 Загружено 109 спецификаций. Всего: 1742
📡 Запрос #21
📥 Загружено 105 спецификаций. Всего: 1847
📡 Запрос #22
📥 Загружено 99 спецификаций. Всего: 1946
📡 Запрос #23
📥 Загружено 79 спецификаций. Всего: 2025
📡 Запрос #24
📥 Загружено 33 спецификаций. Всего: 2058
📡 Запрос #25
📥 Загружено 128 спецификаций. Всего: 2186
📡 Запрос #26
📥 Загружено 80 спецификаций. Всего: 2266
📡 Запрос #27
📥 Загружено 88 спецификаций. Всего: 2354
📡 Запрос #28
📥 Загружено 106 спецификаций. Всего: 2460
📡 Запрос #29
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 132 спецификаций. Всего: 2592
📡 Запрос #30
⚠️ Ошибка (попытка 1/3): HTTPSConnectionPool(host='ows.goszakup.gov.kz', port=443): Read timed out.
📥 Загружено 141 спецификаций. Всего: 2733
📡 Запрос #31
📥 Загружено 71 спецификаций. Всего: 2804
📤 Сохранено 2804 записей в plans_data_spec\plans_combined_spec.parquet
Итог: планов без PlansSpec: 3354
✅ Завершено. Всего загружено: 2804 новых записей

In [14]:
df = pd.read_parquet(combined_file)
df["dateCreate"] = pd.to_datetime(df["dateCreate"], errors="coerce")  # Преобразуем дату
df_sorted = df.sort_values("dateCreate")  # Сортируем по возрастанию

print("🔝 ПЕРВЫЕ 5 СТРОК ПО dateCreate:")
display(df_sorted.head())

print("\n🔚 ПОСЛЕДНИЕ 5 СТРОК ПО dateCreate:")
display(df_sorted.tail())

🔝 ПЕРВЫЕ 5 СТРОК ПО dateCreate:

,plan_id,dateCreate,specId,plnPointsId,refEkrbId,ekrbCode,ekrbNameRu,ekrbNameKz,count,price,...,abpNameKz,amount,refFkrbProgramId,fkrbProgramCode,fkrbProgramNameRu,fkrbProgramNameKz,isActive,isDeleted,systemId,indexDate
2695003,66674926,2024-01-01 00:16:53,41129927,66674926,878,123,Взносы на обязательное страхование,Мiндеттi сақтандыру жарналары,1.0,14285.71,...,Облыстың білім басқармасы,14285.71,2112181,001,Услуги по реализации государственной политики ...,Жергілікті деңгейде білім беру саласындағы мем...,1,0,3,2024-11-21 10:47:06
2695002,66674957,2024-01-01 01:05:33,41129950,66674957,888,149,Приобретение прочих запасов,Өзге де қорларды сатып алу,100.0,107.14,...,Облыстың білім басқармасы,10714.00,2112181,001,Услуги по реализации государственной политики ...,Жергілікті деңгейде білім беру саласындағы мем...,1,0,3,2024-11-21 10:47:06
2695001,66674966,2024-01-01 01:18:47,41129957,66674966,889,152,Оплата услуг связи,Байланыс қызметтерiне ақы төлеу,1.0,66071.42,...,Облыстың білім басқармасы,66071.42,2112181,001,Услуги по реализации государственной политики ...,Жергілікті деңгейде білім беру саласындағы мем...,1,0,3,2025-01-05 02:20:27
2695000,66675011,2024-01-01 02:17:47,41129995,66675011,894,159,Оплата прочих услуг и работ,Өзге де қызметтер мен жұмыстарға ақы төлеу,1.0,14285714.29,...,Қаладағы аудан әкімінің аппараты,14285714.29,737798,009,Обеспечение санитарии населенных пунктов,Елді мекендердің санитариясын қамтамасыз ету,1,0,3,2024-06-27 20:56:23
2694999,66675275,2024-01-01 10:22:41,41130199,66675275,888,149,Приобретение прочих запасов,Өзге де қорларды сатып алу,23.0,2589.29,...,Ауданның (облыстық маңызы бар қаланың) мәдение...,59553.67,736001,006,Функционирование районных (городских) библиотек,Аудандық (қалалық) кiтапханалардың жұмыс iстеуi,1,0,3,2024-06-27 20:56:23

🔚 ПОСЛЕДНИЕ 5 СТРОК ПО dateCreate:

,plan_id,dateCreate,specId,plnPointsId,refEkrbId,ekrbCode,ekrbNameRu,ekrbNameKz,count,price,...,abpNameKz,amount,refFkrbProgramId,fkrbProgramCode,fkrbProgramNameRu,fkrbProgramNameKz,isActive,isDeleted,systemId,indexDate
2695008,78457267,2025-04-02 15:49:41,47369780,78457267,888,149,Приобретение прочих запасов,Өзге де қорларды сатып алу,3.0,650.0,...,Ауданның (облыстық маңызы бар қаланың) кәсіпке...,1950.0,736627,001,Услуги по реализации государственной политики ...,Жергілікті деңгейде кәсіпкерлікті және ауыл ша...,1,0,3,2025-04-02 16:11:12
2695007,78457327,2025-04-02 15:50:41,47369824,78457327,911,414,"Приобретение машин, оборудования, инструментов...","Машиналар, жабдықтар, өндірістік және шаруашыл...",1.0,800000.0,...,Облыстың білім басқармасы,800000.0,2152338,203,Реализация подушевого финансирования в государ...,Мемлекеттік орта білім беру ұйымдарында жан ба...,1,0,3,2025-04-02 16:11:12
2695006,78457458,2025-04-02 15:52:54,47369902,78457458,888,149,Приобретение прочих запасов,Өзге де қорларды сатып алу,1.0,155000.0,...,Облыстың білім басқармасы,155000.0,2152338,203,Реализация подушевого финансирования в государ...,Мемлекеттік орта білім беру ұйымдарында жан ба...,1,0,3,2025-04-02 16:11:12
2695005,78457575,2025-04-02 15:54:53,47369979,78457575,888,149,Приобретение прочих запасов,Өзге де қорларды сатып алу,60.0,480.0,...,,28800.0,2116888,011,Благоустройство и озеленение населенных пунктов,Елді мекендерді абаттандыру мен көгалдандыру,0,0,3,2025-04-02 16:11:12
2695004,78457882,2025-04-02 16:00:52,47370202,78457882,888,149,Приобретение прочих запасов,Өзге де қорларды сатып алу,150.0,250.0,...,,37500.0,2116888,011,Благоустройство и озеленение населенных пунктов,Елді мекендерді абаттандыру мен көгалдандыру,1,0,3,2025-04-02 16:11:12